export const ACTION_TYPES = {
  AUTH_REQUEST_SUCCESS: 'AUTH_REQUEST_SUCCESS',
  AUTH_REQUEST_FAIL: 'AUTH_REQUEST_FAIL',
  SIGN_OUT: 'SIGN_OUT',
  SEARCH_TOPICS: 'SEARCH_TOPICS',
  SEARCH_COLLEAGUES: 'SEARCH_COLLEAGUES',
  SEARCH_SIDEBAR_USERS: 'SEARCH_SIDEBAR_USERS',
  SEARCH_INVITE_USERS: 'SEARCH_INVITE_USERS',
  UPDATE_PINNED_TOPICS_FILTER: 'UPDATE_PINNED_TOPICS_FILTER',
  UPDATE_ARCHIVE_TOPICS_FILTER: 'UPDATE_ARCHIVE_TOPICS_FILTER',

  INIT_STEPPER: 'INIT_STEPPER',
  SET_CURRENT_STEP: 'SET_CURRENT_STEP',
  SET_STEP_STATUS: 'SET_STEP_STATUS',
  SET_CONFIGURATIONS: 'SET_CONFIGURATIONS'

};
