export const ACTION_TYPES = {
  FETCH_USER: 'FETCH_USER',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
};

export const DESKTOP_NOTIFICATION_TYPES = {
  NONE: 'none',
  DIRECT: 'direct',
  ALL: 'all'
};

export const USER_TYPES = {
  USER: 'user',
  ANONYMOUS: 'anonymous'
};

export const USER_PERMISSION_GROUP_TYPES = {
  USERSELF_PERMISSION_GROUP: 'USERSELF_PERMISSION_GROUP',
  IT_ADMIN_PERMISSION_GROUP: 'IT_ADMIN_PERMISSION_GROUP',
  SITE_ADMIN_PERMISSION_GROUP: 'SITE_ADMIN_PERMISSION_GROUP'
};
