export const ACTION_TYPES = {
  FETCH_QUOTE: 'FETCH_QUOTE',
  FETCH_QUOTE_SUCCESS: 'FETCH_QUOTE_SUCCESS',
  FETCH_QUOTE_FAILURE: 'FETCH_QUOTE_FAILURE',

  CREATE_QUOTE: 'CREATE_QUOTE',
  CREATE_QUOTE_SUCCESS: 'CREATE_QUOTE_SUCCESS',
  CREATE_QUOTE_FAILURE: 'CREATE_QUOTE_FAILURE',

  UPDATE_QUOTE: 'UPDATE_QUOTE',
  UPDATE_QUOTE_SUCCESS: 'UPDATE_QUOTE_SUCCESS',
  UPDATE_QUOTE_ERROR: 'UPDATE_QUOTE_FAILURE'
};

export const QUOTE_DAYS_TO_EXPIRATION = 30