const SALESMODEL_RULE_HOOK_EVENTS = {
  BEFORE_UPDATE_CART: 'before-update-cart',
};

const CART_TITLE_DESCRIPTIONS_IDENTIFIER = 'cart-title';

module.exports = {
  SALESMODEL_RULE_HOOK_EVENTS,
  CART_TITLE_DESCRIPTIONS_IDENTIFIER,
};
