export const ACTION_TYPES = {
  FETCH_REGIONS: 'FETCH_REGIONS',
  FETCH_REGIONS_SUCCESS: 'FETCH_REGIONS_SUCCESS',
  FETCH_REGIONS_ERROR: 'FETCH_REGIONS_ERROR',

  FETCH_CURRENT_REGIONS: 'FETCH_CURRENT_REGIONS',
  FETCH_CURRENT_REGIONS_SUCCESS: 'FETCH_CURRENT_REGIONS_SUCCESS',
  FETCH_CURRENT_REGIONS_ERROR: 'FETCH_CURRENT_REGIONS_ERROR',

  FETCH_ALL_REGIONS: 'FETCH_ALL_REGIONS',
  FETCH_ALL_REGIONS_SUCCESS: 'FETCH_ALL_REGIONS_SUCCESS',
  FETCH_ALL_REGIONS_ERROR: 'FETCH_ALL_REGIONS_ERROR'

}