export const ACTION_TYPES = {
  FETCH_PARTNER_QUOTES: 'FETCH_PARTNER_QUOTES',
  FETCH_PARTNER_QUOTES_SUCCESS: 'FETCH_PARTNER_QUOTES_SUCCESS',
  FETCH_PARTNER_QUOTES_FAILURE: 'FETCH_PARTNER_QUOTES_FAILURE',

  FETCH_PARTNER_AGENT_QUOTES: 'FETCH_PARTNER_AGENT_QUOTES',
  FETCH_PARTNER_AGENT_QUOTES_SUCCESS: 'FETCH_PARTNER_AGENT_QUOTES_SUCCESS',
  FETCH_PARTNER_AGENT_QUOTES_FAILURE: 'FETCH_PARTNER_AGENT_QUOTES_FAILURE',

  FETCH_PARTNER_REGION: 'FETCH_PARTNER_REGION',
  FETCH_PARTNER_REGION_SUCCESS: 'FETCH_PARTNER_REGION_SUCCESS',
  FETCH_PARTNER_REGION_FAILURE: 'FETCH_PARTNER_REGION_FAILURE',
};