const PRODUCT_ENGINE_NAME = 'ip-office';

const IPOFFICE_USER_TYPES_TAG = 'user-types';
const IPOFFICE_DEVICE_TAG = 'devices';
const IPOFFICE_USER_TYPE_ESSENTIAL = 'essential-user';
const IPOFFICE_USER_TYPE_BUSINESS = 'business-user';
const IPOFFICE_USER_TYPE_BASIC = 'basic-user';
const IPOFFICE_USER_TYPE_STANDARD = 'standard-user';
const IPOFFICE_USER_TYPE_POWER = 'power-user';
const IPOFFICE_USER_TYPES = [
  IPOFFICE_USER_TYPE_ESSENTIAL,
  IPOFFICE_USER_TYPE_BUSINESS,
  IPOFFICE_USER_TYPE_POWER,
];
const IPOFFICE_USER_TYPE_NAMES = {
  'essential-user': {
    title: 'Essential',
    resource: 'ESSENTIAL',
  },
  'business-user': {
    title: 'Business',
    resource: 'BUSINESS',
  },
  'power-user': {
    title: 'Power',
    resource: 'POWER',
  },
};

const IPOFFICE_SETTINGXML_TASK_STATUS = 'new_ipoffice_settingxml_status';
const IPOFFICE_SETTINGXML_TASK_INPROCESS = 1;
const IPOFFICE_SETTINGXML_TASK_IDLE = 0;
const IPOFFICE_SETTINGXML_TASK_LOCKTM = 3600 * 1000; //In million seconds.

const IPOFFICE_SIP_PROVISION_TASK_STATUS = 'ipoffice_sip_provision_status';
const IPOFFICE_SIP_PROVISION_TASK_INPROCESS = 1;
const IPOFFICE_SIP_PROVISION_TASK_IDLE = 0;
const IPOFFICE_SIP_PROVISION_TASK_LOCKTM = 3600 * 1000; //In million seconds.

const SUBSCRIPTION_TRACK_TABLE_NAME = '_ipofficesubscriptiontracks';

const IPOFFICE_CONTAINER_FLAG = '@Container@';
const IPOFFICE_VM_FLAG = '@VMInstance@';

module.exports = {
  PRODUCT_ENGINE_NAME,

  IPOFFICE_USER_TYPES_TAG,
  IPOFFICE_DEVICE_TAG,

  IPOFFICE_USER_TYPE_ESSENTIAL,
  IPOFFICE_USER_TYPE_BUSINESS,
  IPOFFICE_USER_TYPE_POWER,
  IPOFFICE_USER_TYPE_BASIC,
  IPOFFICE_USER_TYPE_STANDARD,
  IPOFFICE_USER_TYPES,
  IPOFFICE_USER_TYPE_NAMES,

  IPOFFICE_SETTINGXML_TASK_STATUS,
  IPOFFICE_SETTINGXML_TASK_INPROCESS,
  IPOFFICE_SETTINGXML_TASK_IDLE,
  IPOFFICE_SETTINGXML_TASK_LOCKTM,

  IPOFFICE_SIP_PROVISION_TASK_STATUS,
  IPOFFICE_SIP_PROVISION_TASK_INPROCESS,
  IPOFFICE_SIP_PROVISION_TASK_IDLE,
  IPOFFICE_SIP_PROVISION_TASK_LOCKTM,

  SUBSCRIPTION_TRACK_TABLE_NAME,

  IPOFFICE_CONTAINER_FLAG,
  IPOFFICE_VM_FLAG,
};
