const ns = '[blling.error]';

export class BillingError extends Error {
    constructor(message, code)  {
        super(message);
        this.code = code;
    }
}

export const ERROR_CODES = {
    INVALID_WEBHOOK_EVENT: 'INVALID_WEBHOOK_EVENT',
    CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    BILLING_ACCOUNT_NOT_FOUND: 'BILLING_ACCOUNT_NOT_FOUND',
    EMAIL_TEMPLATE_NOT_FOUND: 'EMAIL_TEMPLATE_NOT_FOUND',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    TAX_CODE_NOT_FOUND: 'TAX_CODE_NOT_FOUND',
    AVALARA_ERROR: 'AVALARA_ERROR',
    PAYMENT_GATEWAY_NOT_FOUND: 'PAYMENT_GATEWAY_NOT_FOUND',
    TAX_GATEWAY_NOT_FOUND: 'TAX_GATEWAY_NOT_FOUND',
    NO_PLANS: 'NO_PLANS',
    PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
    GATEWAY_REF_NOT_FOUND: 'GATEWAY_REF_NOT_FOUND',
    ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
    BILL_ADDRESS_NOT_FOUND: 'BILL_ADDRESS_NOT_FOUND',
    SHIP_ADDRESS_NOT_FOUND: 'SHIP_ADDRESS_NOT_FOUND',
    INVALID_CREDIT_CARD: 'INVALID_CREDIT_CARD'
};