// known events
const ASEVENT_CART_BEFORE_UPDATE = 'cart-before-update';
const ASEVENT_QUOTE_BEFORE_CREATE = 'quote-before-create';
const ASEVENT_ORDER_BEFORE_CREATE = 'order-before-create';
const ASEVENT_CHANGE_ORDER_BEFORE_CREATE = 'change-order-before-create';
const ASEVENT_ORDER_CREATED = 'order-created';
const ASEVENT_CHANGE_ORDER_CREATED = 'change-order-created';
const ASEVENT_ORDER_BEFORE_DELETE = 'order-before-delete';
const ASEVENT_QUOTE_CREATED = 'quote-created'
const ASEVENT_ORDER_SUBSCRIPTIONS_BILLING_SUCCESS = 'order-subscriptions-billing-success';
const ASEVENT_ORDER_SUBSCRIPTIONS_BILLING_FAILED = 'order-subscriptions-billing-failed';
const ASEVENT_ORDER_ONETIME_BILLING_SUCCESS = 'order-onetime-billing-success';
const ASEVENT_ORDER_ONETIME_BILLING_FAILED = 'order-onetime-billing-failed';
const ASEVENT_ORDER_SUCCESS = 'order-success';
const ASEVENT_CHANGE_ORDER_SUCCESS = 'change-order-success';
const ASEVENT_ORDER_FAILED = 'order-failed';
const ASEVENT_ORDER_BILLING = 'order-billing';
const ASEVENT_CHANGE_ORDER_BILLING = 'change-order-billing';
const ASEVENT_PO_APPROVED = 'po-approved';
const ASEVENT_PO_REJECTED = 'po-rejected';
const ASEVENT_PO_BILL_RECURRING = 'po-bill-recurring';
const ASEVENT_CLOCK_TICK_12_HOUR = 'clock-tick-12-hour';
const ASEVENT_PURCHASED_PLAN_INTERVAL = 'purchased-plan-interval';

module.exports = {
  ASEVENT_CART_BEFORE_UPDATE,
  ASEVENT_QUOTE_BEFORE_CREATE,
  ASEVENT_CHANGE_ORDER_BEFORE_CREATE,
  ASEVENT_ORDER_BEFORE_CREATE,
  ASEVENT_ORDER_CREATED,
  ASEVENT_CHANGE_ORDER_CREATED,
  ASEVENT_ORDER_BEFORE_DELETE,
  ASEVENT_QUOTE_CREATED,
  ASEVENT_ORDER_SUBSCRIPTIONS_BILLING_SUCCESS,
  ASEVENT_ORDER_SUBSCRIPTIONS_BILLING_FAILED,
  ASEVENT_ORDER_ONETIME_BILLING_SUCCESS,
  ASEVENT_ORDER_ONETIME_BILLING_FAILED,
  ASEVENT_ORDER_SUCCESS,
  ASEVENT_ORDER_FAILED,
  ASEVENT_PO_APPROVED,
  ASEVENT_ORDER_BILLING,
  ASEVENT_CHANGE_ORDER_BILLING,
  ASEVENT_CHANGE_ORDER_SUCCESS,
  ASEVENT_PO_REJECTED,
  ASEVENT_PO_BILL_RECURRING,
  ASEVENT_CLOCK_TICK_12_HOUR,
  ASEVENT_PURCHASED_PLAN_INTERVAL,
};
