export const ACTION_TYPES = {
  FETCH_CART: 'FETCH_CART',
  FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
  FETCH_CART_FAILURE: 'FETCH_CART_FAILURE',

  CREATE_CART: 'CREATE_CART',
  CREATE_CART_SUCCESS: 'CREATE_CART_SUCCESS',
  CREATE_CART_FAILURE: 'CREATE_CART_FAILURE',
  DELETE_CART: 'DELETE_CART',
  DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
  DELETE_CART_FAILURE: 'DELETE_CART_FAILURE',

  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',

  CLEAR_CART: 'CLEAR_CART',
  
  INIT_CART: 'INIT_CART',
  INIT_CART_SUCCESS: 'INIT_CART_SUCCESS',
  INIT_CART_FAILURE: 'INIT_CART_FAILURE',

  UPDATE_CART: 'UPDATE_CART',
  UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
  UPDATE_CART_ERROR: 'UPDATE_CART_FAILURE',


  UPDATE_CART_ACCOUNT_INFO: 'UPDATE_CART_ACCOUNT_INFO',
  UPDATE_CART_PARTNER_INFO: 'UPDATE_CART_PARTNER_INFO',
  SET_CART_SHIPPING_SAME_AS_BILLING: 'SET_CART_SHIPPING_SAME_AS_BILLING',
  RESET_CART_INFO: 'RESET_CART_INFO',
  CLEAR_CART_WARNINGS: 'CLEAR_CART_WARNINGS',
  CART_VALIDATION: 'CART_VALIDATION',

  SEND_CART_SUMMARY: 'SEND_CART_SUMMARY',
  SEND_CART_SUMMARY_SUCCESS: 'SEND_CART_SUMMARY_SUCCESS',
  SEND_CART_SUMMARY_ERROR: 'SEND_CART_SUMMARY_ERROR'
};


export const QUOTE_CART = 'quote'
export const DEFAULT_CART = 'default'