module.exports = {
  SPECIAL_OFFER_STATES: [
    "Alabama", "Florida", "Georgia", "Louisiana", "North Carolina", "South Carolina", "Texas", "Tennessee", "Mississippi"
  ],
  SPECIAL_OFFER_COUNTRIES: [
    'Puerto Pico'
  ],
  SUPPORT_EMAILS: {
    CLOUD_SUPPORT: "cloudsupport@avaya.com",
    CLOUD_CS: "cloudsuccess@avaya.com",
    CLOUD_SVC: "cloudservice@avaya.com",
    CLOUD_DEVOPS: "clouddevops@avaya.com",
    ZANG_OFFICE: "zosupport@zang.io",
    IP_OFFICE: "cloudsupport@avaya.com",
    IP_OFFICE_CS: "cloudsuccess@avaya.com",
    ZANG_SPACES: "zasupport@zang.io",
    PARTNER_PROGRAM: "cloudsuccess@avaya.com",
    GSMB_DEVICE_PROVISIONING_EMAIL: 'zang@direct.de',
    GSMB_SUPPORT: 'servicecloud@avaya.com',
    GSMB_SUPPORT_ORDER: 'ordercloud@avaya.com',
  },
  LEGAL_DOCS: {
    ipofficeCheckout: ['general-tos-ipo', 'general-privacy-statement'],
    preChecked: ['general-privacy-statement'],
    emailDoc: 'general-tos-ipo',
    legalDocEmail: 'gcpdocs@avaya.com'
  },
  CUSTOMER_SUCCESS: {
    FIRST_NAME: 'Your Customer Success Team'
  },
  TECH_SUPPORT: {
    firstName: "Tech",
    lastName: "Support",
    email: "cloudsupport@avaya.com",
    phoneNumber: "+1111111111"
  },
  PRODUCT_PRICING: [
    "month-1:month-1",
    "year-1:month-1",
    "year-1:year-1",
    "year-2:month-1",
    "year-2:year-1",
    "year-2:year-2",
    "year-3:month-1",
    "year-3:year-1",
    "year-3:year-3"
  ],
  PARTNER_INVITEE_TYPES: {
    COMPANY: 'COMPANY',
    INDIVIDUAL: 'INDIVIDUAL'
  },
  PRODUCTS_MAXIMUM_USERS: 10000,//incremented to 10000 from 999, Ray @ 2018-01-19
  AGENT_LEVELS: {
    OWNER: 1,
    ADMIN: 2,
    AGENT: 3
  },
  PARTNER_TYPES: {
    referral: "referral",
    sales: "sales",
    msa: "msa"
  },
  PARTNER_CODE_COOKIE_NAME: "___zspccn",
  PARTNER_STATUS_TYPES: {
    APPROVED: "APPROVED",
    PENDING: "PENDING",
    REJECTED: "REJECTED"
  },
  PARTNER_APPROVERS: [
    "wesleyf@esna.com",
    "nicholasz@esna.com"
  ],
  AGENT_CODE_LENGTH: 20,
  PLAN_TYPES: {
    "month": {
      active: true,
      text: "Monthly Plan",
      frequencyCount: 1
    },
    "1year": {
      active: true,
      text: "1 Year Plan",
      frequencyCount: 12
    },
    "2year": {
      active: false,
      text: "2 Year Plan",
      frequencyCount:24
    }
  },
  superAdmins: [
    "wesleyf@esna.com",
    "ericd@esna.com"
  ],
  SALESFORCE_CHARGE_TYPES: {
    ONETIME: 'One-Time',
    RECURRING: 'Recurring',
    USAGE: 'Usage'
  },
  BIG_QUERY: {
    DATASET_NAME: 'accounts_dataset',
    CANCELLATIONS_TABLE_NAME: 'zs_cancellations'
  },
  ZANG_OFFICE_RELEASE_YEAR: 2016,
  IP_OFFICE_RELEASE_YEAR: 2018,
  ZANG_OFFICE_CDR_CHECK_TASK_NAME: "zang-office-cdr-check",
  GOOGLE_API_KEY: 'AIzaSyBd9UbpXdZ1Zc5F82kSj7x0dVGrmq0eduY',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'There was an error placing your order. Please contact Zang support (zosupport@zang.io) for more information.',
  APPLICATION_GENERAL_FATAL_ERROR: "There was an error submitting your application. Please contact Zang support (zosupport@zang.io) for more information.",
  APP_VERSION: 'Wed Apr 12 2017 16:21:12 GMT-0400 (Eastern Daylight Time)',
  UI_DATE_FORMAT: 'MMMM Do YYYY, h:mm:ss a',
  UI_ONLY_DATE_FORMAT: 'MMMM Do YYYY',
  ZANG_OFFICE_FOLLOW_UP_EMAIL_COUNT: 20,
  ZANG_OFFICE_FOLLOW_UP_EMAIL_UNIT: 'days',
  ZANG_OFFICE_AUTO_RENEWAL_EMAIL_COUNT: 5,
  ZANG_OFFICE_AUTO_RENEWAL_EMAIL_UNIT: 'minutes',
  USER_LEVELS: {
    ADMIN: 1,
    EDITOR: 2,
    CUSTOMER: 3
  },
  TASK_TYPES: {
    ZANG_SPACES_SUBSCRIPTION_UPDATE: 'ZANG_SPACES_SUBSCRIPTION_UPDATE'
  },
  ZANG_WEBSITE_URL: 'https://www.zang.io',
  ADVANCED_PRODUCTS: {
    'zang-office': {
      slug: 'zang-office',
      entityName: 'ZangOffice',
      contractUpdatable: false
    },
    'ip-office': {
      slug: 'ip-office',
      entityName: 'IPOffice',
      contractUpdatable: false
    },
    'zang-spaces': {
      slug: 'zang-spaces',
      entityName: 'ZangSpaces',
      allowedTeamTypes: ["personal", "existing", "new"],
      contractUpdatable: false
    }
  },
  LOOKUP_TYPES: {
    INDUSTRY_TYPES: 'INDUSTRY_TYPES',
    COUNTRIES: 'COUNTRIES',
    STATES: 'STATES'
  },
  CONTRACT_STATUS_TYPES: {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED',
    DELETED: 'DELETED',
    IN_PROGRESS: 'IN_PROGRESS'
  },
  PLANS_STATUS_TYPES: {
    SUCCESS: 'success',
    NEW: 'new',
    PENDING: 'pending_approval',
    CANCELED: 'canceled',
    REQUESTED_CANCEL: 'requested_cancel'
  },
  CANCELLATION_REQUEST_SYSTEM_TYPES: {
    ZO_ACCOUNTID: 'ZO_ACCOUNTID',
    ZA_USER: 'ZA_USER',
    ZA_COMPANY: 'ZA_COMPANY',
    OL_SENTINUM: 'OL_SENTINUM'
  },
  BILLING_ENGINE_INTERVALS: {
    "day" : 0,
    "week" : 1,
    "month" : 2,
    "year" : 3
  },
  BILLING_ENGINE_EVENT_TYPES: {
    ACCOUNT_EXTERNAL_ACCOUNT_CREATED : "account.external_account.created",
    ACCOUNT_EXTERNAL_ACCOUNT_DELETED : "account.external_account.deleted",
    ACCOUNT_EXTERNAL_ACCOUNT_UPDATED : "account.external_account.updated",
    ACCOUNT_UPDATED : "account.updated",
    BALANCE_AVALIABLE : "balance.avaliable",
    BITCOIN_RECEIVER_CREATED : "bitcoin.receiver.created",
    BITCOIN_RECEIVER_FILLED : "bitcoin.receiver.filled",
    BITCOIN_RECEIVER_UPDATED : "bitcoin.receiver.updated",
    BITCOINSECEIVER_TRANSACTION_CREATED : "bitcoinseceiver.transaction.created",
    CHARGE_CAPTURED : "charge.captured",
    CHARGE_DISPUTE_CLOSED : "charge.dispute.closed",
    CHARGE_DISPUTE_CREATED : "charge.dispute.created",
    CHARGE_DISPUTE_FUNDS_REINSTATED : "charge.dispute.funds_reinstated",
    CHARGE_DISPUTE_FUNDS_WITHDRAWN : "charge.dispute.funds_withdrawn",
    CHARGE_DISPUTE_UPDATED : "charge.dispute.updated",
    CHARGE_FAILED : "charge.failed",
    CHARGE_PENDING : "charge.pending",
    CHARGE_REFUNDED : "charge.refunded",
    CHARGE_SUCCEEDED : "charge.succeeded",
    CHARGE_UPDATED : "charge.updated",
    COUPON_CREATED : "coupon.created",
    COUPON_DELETED : "coupon.deleted",
    COUPON_UPDATED : "coupon.updated",
    CUSTOMER_BANK_ACCOUNT_DETETED : "customer.bank_account.deteted",
    CUSTOMER_CREATED : "customer.created",
    CUSTOMER_DELETED : "customer.deleted",
    CUSTOMER_DISCOUNT_CREATED : "customer.discount.created",
    CUSTOMER_DISCOUNT_DELETED : "customer.discount.deleted",
    CUSTOMER_DISCOUNT_UPDATED : "customer.discount.updated",
    CUSTOMER_SOURCE_DELETED : "customer.source.deleted",
    CUSTOMER_SOURCE_UPDATED : "customer.source.updated",
    CUSTOMER_SUBSCNPTION_CREATED : "customer.subscnption.created",
    CUSTOMER_SUBSCRIPTION_DELETED : "customer.subscription.deleted",
    CUSTOMER_SUBSCRIPTION_TRIAL_WILLEND : "customer.subscription.trial_willend",
    CUSTOMER_SUBSCRIPTION_UPDATED : "customer.subscription.updated",
    CUSTOMER_UPDATED : "customer.updated",
    CUSTOMER_SOURCE_CREATED : "custorner.source.created",
    INVOICE_CREATED : "invoice.created",
    INVOICE_PAYMENT_FAITED : "invoice.payment_failed",
    INVOICE_PAYRNENT_SUCCEEDED : "invoice.payrnent_succeeded",
    INVOICE_SENT : "invoice.sent",
    INVOICE_UPDATED : "invoice.updated",
    INVOICEITEM_CREATED : "invoiceitem.created",
    INVOICEITEM_UPDATED : "invoiceitem.updated",
    INVOICEITEM_DELETED : "invoiceitern.deleted",
    ORDER_CREATED : "order.created",
    ORDER_PAYMENT_SUCCEEDED : "order.payment_succeeded",
    ORDER_PAYRNENT_FAILED : "order.payrnent_failed",
    ORDER_RETURN_CREATED : "order_return.created",
    ORDER_UPDATED : "order.updated",
    PLAN_CREATED : "plan.created",
    PLAN_DELETED : "plan.deleted",
    PLAN_UPDATED : "plan.updated",
    PRODUCT_CREATED : "product.created",
    PRODUCT_DELETED : "product.deleted",
    PRODUCT_UPDATED : "product.updated",
    RECIPIENT_CREATED : "recipient.created",
    RECIPIENT_DELETED : "recipient.deleted",
    RECIPIENT_UPDATED : "recipient.updated",
    REVIEW_CLOSED : "review.closed",
    REVIEW_OPENED : "review.opened",
    SKU_CREATED : "sku.created",
    SKU_DELETED : "sku.deleted",
    SKU_UPDATED : "sku.updated",
    SOURCE_CANCELED : "source.canceled",
    SOURCE_CHARGEABLE : "source.chargeable",
    SOURCE_FALIED : "source.falied",
    SOURCE_TRANSACTION_CREATED : "source.transaction.created",
    TRANSFER_CREATED : "transfer.created",
    TRANSFER_LADED : "transfer.laded",
    TRANSFER_PAID : "transfer.paid",
    TRANSFER_REVERSED : "transfer.reversed",
    TRANSFER_UPDATED : "transfer.updated"
  },
  CHECKOUT_STEPS: {
    PLACING_ORDER: 'PLACING_ORDER',
    CHARGING_CREDIT_CARD: 'CHARGING_CREDIT_CARD',
    CREATING_ZANG_OFFICE_ACCOUNT: 'CREATING_ZANG_OFFICE_ACCOUNT',
    CREATING_ZANG_OFFICE_USERS: 'CREATING_ZANG_OFFICE_USERS',
    ORDERING_DEVICES: 'ORDERING_DEVICES',
    FINALIZING_ORDER: 'FINALIZING_ORDER'
  },
  ORDER_TYPES: {
    USER_CREATED: 'USER_CREATED',
    SUBSCRIPION_UPDATE: 'SUBSCRIPION_UPDATE',
    ZANG_OFFICE_DEVICES: 'ZANG_OFFICE_DEVICES'
  },
  KAZOO_VIRTUAL_RECEPTIONIST_TEXT_MESSAGE: "Thank you for calling. Please dial the extension you would like to reach or please stay on the line for further assistance.",
  ORDER_STATUS_TYPES: {
    IN_PROGRESS: 'IN_PROGRESS',
    BILLING_ENGINE_GETTING_CUSTOMER: 'BILLING_ENGINE_GETTING_CUSTOMER',
    BILLING_ENGINE_GET_CUSTOMER_ERROR: 'BILLING_ENGINE_GET_CUSTOMER_ERROR',
    BILLING_ENGINE_GET_CUSTOMER_SUCCESS: 'BILLING_ENGINE_GET_CUSTOMER_SUCCESS',
    BILLING_ENGINE_GETTING_CREATING_CREDIT_CARD: 'BILLING_ENGINE_GETTING_CREATING_CREDIT_CARD',
    BILLING_ENGINE_GET_CREATE_CREDIT_CARD_ERROR: 'BILLING_ENGINE_GET_CREATE_CREDIT_CARD_ERROR',
    BILLING_ENGINE_GET_CREATE_CREDIT_CARD_SUCCESS: 'BILLING_ENGINE_GET_CREATE_CREDIT_CARD_SUCCESS',
    BILLING_ENGINE_CREATING_CHARGE: 'BILLING_ENGINE_CREATING_CHARGE',
    BILLING_ENGINE_CREATE_CHARGE_ERROR: 'BILLING_ENGINE_CREATE_CHARGE_ERROR',
    BILLING_ENGINE_CREATE_CHARGE_SUCCESS: 'BILLING_ENGINE_CREATE_CHARGE_SUCCESS',
    BILLING_ENGINE_CREATING_SUBSCRIPTION: 'BILLING_ENGINE_CREATING_SUBSCRIPTION',
    BILLING_ENGINE_CREATE_SUBSCRIPTION_ERROR: 'BILLING_ENGINE_CREATE_SUBSCRIPTION_ERROR',
    BILLING_ENGINE_CREATE_SUBSCRIPTION_SUCCESS: 'BILLING_ENGINE_CREATE_SUBSCRIPTION_SUCCESS',
    BILLING_ENGINE_CREATING_PLAN: 'BILLING_ENGINE_CREATING_PLAN',
    BILLING_ENGINE_CREATE_PLAN_ERROR: 'BILLING_ENGINE_CREATE_PLAN_ERROR',
    BILLING_ENGINE_CREATE_PLAN_SUCCESS: 'BILLING_ENGINE_CREATE_PLAN_SUCCESS',
    BILLING_ENGINE_CHARGING_ADVANCED_PRODUCTS: 'BILLING_ENGINE_CHARGING_ADVANCED_PRODUCTS',
    BILLING_ENGINE_CHARGE_ADVANCED_PRODUCTS_ERROR: 'BILLING_ENGINE_CHARGE_ADVANCED_PRODUCTS_ERROR',
    BILLING_ENGINE_CHARGE_ADVANCED_PRODUCTS_SUCCESS: 'BILLING_ENGINE_CHARGE_ADVANCED_PRODUCTS_SUCCESS',
    CRI_ORDERING: 'CRI_ORDERING',
    CRI_ORDER_ERROR: 'CRI_ORDER_ERROR',
    CRI_ORDER_SUCCESS: 'CRI_ORDER_SUCCESS',
    EMAIL_ORDER_TO_CUSTOMER_SUCCESS: 'EMAIL_ORDER_TO_CUSTOMER_SUCCESS',
    CREATING_SUMMARY: 'CREATING_SUMMARY',
    CREATE_SUMMARY_ERROR: 'CREATE_SUMMARY_ERROR',
    CREATE_SUMMARY_SUCCESS: 'CREATE_SUMMARY_SUCCESS',
    CREATING_PLAN_ORDER: 'CREATING_PLAN_ORDER',
    CREATE_PLAN_ORDER_ERROR: 'CREATE_PLAN_ORDER_ERROR',
    CREATE_PLAN_ORDER_SUCCESS: 'CREATE_PLAN_ORDER_SUCCESS',
    INITIATING_ZANG_ACCOUNT: 'INITIATING_ZANG_ACCOUNT',
    INITIATE_ZANG_ACCOUNT_ERROR: 'INITIATE_ZANG_ACCOUNT_ERROR',
    INITIATE_ZANG_ACCOUNT_SUCCESS: 'INITIATE_ZANG_ACCOUNT_SUCCESS',
    PAYMENT_IN_PROGRESS: 'PAYMENT_IN_PROGRESS',
    PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
    ORDER_PROCESS_COMPLETED: 'ORDER_PROCESS_COMPLETED',
    INVALIDATE: 'INVALIDATE',
    COMPLETED: 'COMPLETED',
    INVALID: 'INVALID',
    KAZOO_AUTHENTICATING: 'KAZOO_AUTHENTICATING',
    KAZOO_AUTHENTICATE_ERROR: 'KAZOO_AUTHENTICATE_ERROR',
    KAZOO_AUTHENTICATE_SUCCESS: 'KAZOO_AUTHENTICATE_SUCCESS',
    KAZOO_CREATING_ACCOUNT: 'KAZOO_CREATING_ACCOUNT',
    KAZOO_CREATE_ACCOUNT_ERROR: 'KAZOO_CREATE_ACCOUNT_ERROR',
    KAZOO_CREATE_ACCOUNT_SUCCESS: 'KAZOO_CREATE_ACCOUNT_SUCCESS',
    KAZOO_DELETING_ACCOUNT: 'KAZOO_DELETING_ACCOUNT',
    KAZOO_DELETE_ACCOUNT_ERROR: 'KAZOO_DELETE_ACCOUNT_ERROR',
    KAZOO_DELETE_ACCOUNT_SUCCESS: 'KAZOO_DELETE_ACCOUNT_SUCCESS',
    KAZOO_CREATING_USERS: 'KAZOO_CREATING_USERS',
    KAZOO_CREATE_USERS_ERROR: 'KAZOO_CREATE_USERS_ERROR',
    KAZOO_CREATE_USERS_SUCCESS: 'KAZOO_CREATE_USERS_SUCCESS',
    KAZOO_CREATING_USER_DEVICES: 'KAZOO_CREATING_USER_DEVICES',
    KAZOO_CREATE_USER_DEVICES_ERROR: 'KAZOO_CREATE_USER_DEVICES_ERROR',
    KAZOO_CREATE_USER_DEVICES_SUCCESS: 'KAZOO_CREATE_USER_DEVICES_SUCCESS',
    KAZOO_CREATING_USER_VMBOXES: 'KAZOO_CREATING_USER_VMBOXES',
    KAZOO_CREATE_USER_VMBOXES_ERROR: 'KAZOO_CREATE_USER_VMBOXES_ERROR',
    KAZOO_CREATE_USER_VMBOXES_SUCCESS: 'KAZOO_CREATE_USER_VMBOXES_SUCCESS',
    KAZOO_CREATING_USER_CALLFLOWS: 'KAZOO_CREATING_USER_CALLFLOWS',
    KAZOO_CREATE_USER_CALLFLOWS_ERROR: 'KAZOO_CREATE_USER_CALLFLOWS_ERROR',
    KAZOO_CREATE_USER_CALLFLOWS_SUCCESS: 'KAZOO_CREATE_USER_CALLFLOWS_SUCCESS',
    KAZOO_CREATING_ACCOUNT_LIMITS: 'KAZOO_CREATING_ACCOUNT_LIMITS',
    KAZOO_CREATE_ACCOUNT_LIMITS_ERROR: 'KAZOO_CREATE_ACCOUNT_LIMITS_ERROR',
    KAZOO_CREATE_ACCOUNT_LIMITS_SUCCESS: 'KAZOO_CREATE_ACCOUNT_LIMITS_SUCCESS',
    KAZOO_ASSIGNING_NUMBER: 'KAZOO_ASSIGNING_NUMBER',
    KAZOO_ASSIGN_NUMBER_ERROR: 'KAZOO_ASSIGN_NUMBER_ERROR',
    KAZOO_ASSIGN_NUMBER_SUCCESS: 'KAZOO_ASSIGN_NUMBER_SUCCESS',
    KAZOO_ADDING_USER: 'KAZOO_ADDING_USER',
    KAZOO_ADD_USER_ERROR: 'KAZOO_ADD_USER_ERROR',
    KAZOO_ADD_USER_SUCCESS: 'KAZOO_ADD_USER_SUCCESS',
    KAZOO_GETTING_CONTRACT: 'KAZOO_GETTING_CONTRACT',
    KAZOO_GET_CONTRACT_ERROR: 'KAZOO_GET_CONTRACT_ERROR',
    KAZOO_GET_CONTRACT_SUCCESS: 'KAZOO_GET_CONTRACT_SUCCESS',
    KAZOO_GETTING_APP_STORE: 'KAZOO_GETTING_APP_STORE',
    KAZOO_GET_APPSTORE_SUCCESS: 'KAZOO_GET_APPSTORE_SUCCESS',
    KAZOO_GET_APPSTORE_ERROR: 'KAZOO_GET_APPSTORE_ERROR',
    KAZOO_PUTTING_USER_PORTAL_APP: 'KAZOO_PUTTING_USER_PORTAL_APP',
    KAZOO_PUT_USER_PORTAL_APP_SUCCESS: 'KAZOO_PUT_USER_PORTAL_APP_SUCCESS',
    KAZOO_PUT_USER_PORTAL_APP_ERROR: 'KAZOO_PUT_USER_PORTAL_APP_ERROR',
    KAZOO_PUTTING_SMART_PBX_APP: 'KAZOO_PUTTING_SMART_PBX_APP',
    KAZOO_PUT_SMART_PBX_APP_SUCCESS: 'KAZOO_PUT_SMART_PBX_APP_SUCCESS',
    KAZOO_PUT_SMART_PBX_APP_ERROR: 'KAZOO_PUT_SMART_PBX_APP_ERROR',

    KAZOO_CREATING_NO_MATCH_CALLFLOW: 'KAZOO_CREATING_NO_MATCH_CALLFLOW',
    KAZOO_CREATE_NO_MATCH_CALLFLOW_ERROR: 'KAZOO_CREATE_NO_MATCH_CALLFLOW_ERROR',
    KAZOO_CREATE_NO_MATCH_CALLFLOW_SUCCESS: 'KAZOO_CREATE_NO_MATCH_CALLFLOW_SUCCESS',

    KAZOO_CREATING_ACCOUNT_MAIN_CALLFLOWS: 'KAZOO_CREATING_ACCOUNT_MAIN_CALLFLOWS',
    KAZOO_CREATE_MAIN_CALLFLOWS_ERROR: 'KAZOO_CREATE_MAIN_CALLFLOWS_ERROR',
    KAZOO_CREATE_MAIN_CALLFLOWS_SUCCESS: 'KAZOO_CREATE_MAIN_CALLFLOWS_SUCCESS',

    KAZOO_CREATING_FEATURE_CODES_CALLFLOWS: 'KAZOO_CREATING_FEATURE_CODES_CALLFLOWS',
    KAZOO_CREATE_FEATURE_CODES_CALLFLOWS_ERROR: 'KAZOO_CREATE_FEATURE_CODES_CALLFLOWS_ERROR',
    KAZOO_CREATE_FEATURE_CODES_CALLFLOWS_SUCCESS: 'KAZOO_CREATE_FEATURE_CODES_CALLFLOWS_SUCCESS',

    KAZOO_CREATING_MAIN_CONFERENCE_AND_FAXING_CALLFLOWS: 'KAZOO_CREATING_MAIN_CONFERENCE_AND_FAXING_CALLFLOWS',
    KAZOO_CREATE_MAIN_CONFERENCE_AND_FAXING_CALLFLOWS_ERROR: 'KAZOO_CREATE_MAIN_CONFERENCE_AND_FAXING_CALLFLOWS_ERROR',
    KAZOO_CREATE_MAIN_CONFERENCE_AND_FAXING_CALLFLOWS_SUCCESS: 'KAZOO_CREATE_MAIN_CONFERENCE_AND_FAXING_CALLFLOWS_SUCCESS',


    KAZOO_CREATING_MENU_CALLFLOWS: 'KAZOO_CREATING_MENU_CALLFLOWS',
    KAZOO_CREATE_MENU_CALL_FLOWS_ERROR: 'KAZOO_CREATE_MENU_CALL_FLOWS_ERROR',
    KAZOO_CREATE_MENU_CALL_FLOWS_SUCCESS: 'KAZOO_CREATE_MENU_CALL_FLOWS_SUCCESS',

    KAZOO_CREATING_TEMPORAL_RULES: 'KAZOO_CREATING_TEMPORAL_RULES',
    KAZOO_CREATE_TEMPORAL_RULES_ERROR: 'KAZOO_CREATE_TEMPORAL_RULES_ERROR',
    KAZOO_CREATE_TEMPORAL_RULES_SUCCESS: 'KAZOO_CREATE_TEMPORAL_RULES_SUCCESS',

    KAZOO_CREATING_VIRTUAL_RECEPTIONIST: 'KAZOO_CREATING_VIRTUAL_RECEPTIONIST',
    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_ERROR: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_ERROR',
    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_SUCCESS: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_SUCCESS',

    KAZOO_CREATING_SERVICE_PLANS: 'KAZOO_CREATING_SERVICE_PLANS',
    KAZOO_CREATE_SERVICE_PLANS_ERROR: 'KAZOO_CREATE_SERVICE_PLANS_ERROR',
    KAZOO_CREATE_SERVICE_PLANS_SUCCESS: 'KAZOO_CREATE_SERVICE_PLANS_SUCCESS',

    KAZOO_CREATING_SERVICE_PLANS_OVERRIDE: 'KAZOO_CREATING_SERVICE_PLANS_OVERRIDE',
    KAZOO_CREATE_SERVICE_PLANS_OVERRIDE_ERROR: 'KAZOO_CREATE_SERVICE_PLANS_OVERRIDE_ERROR',
    KAZOO_CREATE_SERVICE_PLANS_OVERRIDE_SUCCESS: 'KAZOO_CREATE_SERVICE_PLANS_OVERRIDE_SUCCESS',

    KAZOO_SEARCHING_FOR_NUMBER: 'KAZOO_SEARCHING_FOR_NUMBER',
    KAZOO_SEARCH_FOR_NUMBER_ERROR: 'KAZOO_SEARCH_FOR_NUMBER_ERROR',
    KAZOO_SEARCH_FOR_NUMBER_SUCCESS: 'KAZOO_SEARCH_FOR_NUMBER_SUCCESS',

    KAZOO_ACTIVATING_NUMBER: 'KAZOO_ACTIVATING_NUMBER',
    KAZOO_ACTIVATE_NUMBER_ERROR: 'KAZOO_ACTIVATE_NUMBER_ERROR',
    KAZOO_ACTIVATE_NUMBER_SUCCESS: 'KAZOO_ACTIVATE_NUMBER_SUCCESS',

    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_GET_MAIN_OPEN_HOURS_MENU_ERROR: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_GET_MAIN_OPEN_HOURS_MENU_ERROR',
    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_GET_MAIN_OPEN_HOURS_MENU_SUCCESS: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_GET_MAIN_OPEN_HOURS_MENU_SUCCESS',

    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_PUT_MEDIA_ERROR: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_PUT_MEDIA_ERROR',
    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_PUT_MEDIA_SUCCESS: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_PUT_MEDIA_SUCCESS',

    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_ERROR: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_ERROR',
    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_SUCCESS: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_SUCCESS',

    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_CALLFLOW_ERROR: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_CALLFLOW_ERROR',
    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_CALLFLOW_SUCCESS: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_CALLFLOW_SUCCESS',

    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_CALLFLOW_ERROR: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_CALLFLOW_ERROR',
    KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_CALLFLOW_SUCCESS: 'KAZOO_CREATE_VIRTUAL_RECEPTIONIST_UPDATE_MAIN_OPEN_HOURS_MENU_CALLFLOW_SUCCESS',

    KAZOO_CREATING_ADMIN_USER: 'KAZOO_CREATING_ADMIN_USER',
    KAZOO_CREATE_ADMIN_USER_ERROR: 'KAZOO_CREATE_ADMIN_USER_ERROR',
    KAZOO_CREATE_ADMIN_USER_SUCCESS: 'KAZOO_CREATE_ADMIN_USER_SUCCESS',

    PLACING_NEW_ORDER: 'PLACING_NEW_ORDER',
    PLACE_NEW_ORDER_ERROR: 'PLACE_NEW_ORDER_ERROR',
    PLACE_NEW_ORDER_SUCCESS: 'PLACE_NEW_ORDER_SUCCESS',
    BILLING_ENGINE_UPDATING_PLAN: 'BILLING_ENGINE_UPDATING_PLAN',
    BILLING_ENGINE_UPDATE_PLAN_ERROR: 'BILLING_ENGINE_UPDATE_PLAN_ERROR',
    BILLING_ENGINE_UPDATE_PLAN_SUCCESS: 'BILLING_ENGINE_UPDATE_PLAN_SUCCESS',
    BILLING_ENGINE_UPDATING_SUBSCRIPTION: 'BILLING_ENGINE_UPDATING_SUBSCRIPTION',
    BILLING_ENGINE_UPDATE_SUBSCRIPTION_ERROR: 'BILLING_ENGINE_UPDATE_SUBSCRIPTION_ERROR',
    BILLING_ENGINE_UPDATE_SUBSCRIPTION_SUCCESS: 'BILLING_ENGINE_UPDATE_SUBSCRIPTION_SUCCESS',
    BILLING_ENGINE_DELETING_OLD_PLAN: 'BILLING_ENGINE_DELETING_OLD_PLAN',
    BILLING_ENGINE_DELETE_OLD_PLAN_ERROR: 'BILLING_ENGINE_DELETE_OLD_PLAN_ERROR',
    BILLING_ENGINE_DELETE_OLD_PLAN_SUCCESS: 'BILLING_ENGINE_DELETE_OLD_PLAN_SUCCESS',
    KAZOO_UPDATING_ACCOUNT: 'KAZOO_UPDATING_ACCOUNT',
    KAZOO_UPDATE_ACCOUNT_ERROR: 'KAZOO_UPDATE_ACCOUNT_ERROR',
    KAZOO_UPDATE_ACCOUNT_SUCCESS: 'KAZOO_UPDATE_ACCOUNT_SUCCESS',


    ZANG_SPACES_CREATING_LICENSE: 'ZANG_SPACES_CREATING_LICENSE',
    ZANG_SPACES_CREATE_LICENSE_ERROR: 'ZANG_SPACES_CREATE_LICENSE_ERROR',
    ZANG_SPACES_CREATE_LICENSE_SUCCESS: 'ZANG_SPACES_CREATE_LICENSE_SUCCESS',

    ZANG_SPACES_CREATING_CONTRACT: 'ZANG_SPACES_CREATING_CONTRACT',
    ZANG_SPACES_CREATE_CONTRACT_ERROR: 'ZANG_SPACES_CREATE_CONTRACT_ERROR',
    ZANG_SPACES_CREATE_CONTRACT_SUCCESS: 'ZANG_SPACES_CREATE_CONTRACT_SUCCESS',

    ZANG_SPACES_CREATING_ZANG_COMPANY: 'ZANG_SPACES_CREATING_ZANG_COMPANY',
    ZANG_SPACES_CREATE_ZANG_COMPANY_ERROR: 'ZANG_SPACES_CREATE_ZANG_COMPANY_ERROR',
    ZANG_SPACES_CREATE_ZANG_COMPANY_SUCCESS: 'ZANG_SPACES_CREATE_ZANG_COMPANY_SUCCESS',


    ZANG_SPACES_CREATING_ZANG_COMPANY_DOMAIN: 'ZANG_SPACES_CREATING_ZANG_COMPANY_DOMAIN',
    ZANG_SPACES_CREATE_ZANG_COMPANY_DOMAIN_ERROR: 'ZANG_SPACES_CREATE_ZANG_COMPANY_DOMAIN_ERROR',
    ZANG_SPACES_CREATE_ZANG_COMPANY_DOMAIN_SUCCESS: 'ZANG_SPACES_CREATE_ZANG_COMPANY_DOMAIN_SUCCESS',

    ZANG_SPACES_UPDATING_CONTRACT: 'ZANG_SPACES_UPDATING_CONTRACT',
    ZANG_SPACES_UPDATE_CONTRACT_ERROR: 'ZANG_SPACES_UPDATE_CONTRACT_ERROR',
    ZANG_SPACES_UPDATE_CONTRACT_SUCCESS: 'ZANG_SPACES_UPDATE_CONTRACT_SUCCESS',


    IP_OFFICE_CREATING_SIP_DOMAIN: 'IP_OFFICE_CREATING_SIP_DOMAIN',
    IP_OFFICE_CREATE_SIP_DOMAIN_SUCCESS: 'IP_OFFICE_CREATE_SIP_DOMAIN_SUCCESS',
    IP_OFFICE_CREATE_SIP_DOMAIN_ERROR: 'IP_OFFICE_CREATE_SIP_DOMAIN_ERROR',

    IP_OFFICE_PROVISIONING_SUBSCRIPTION: 'IP_OFFICE_PROVISIONING_SUBSCRIPTION',
    IP_OFFICE_PROVISION_SUBSCRIPTION_ERROR: 'IP_OFFICE_PROVISION_SUBSCRIPTION_ERROR',
    IP_OFFICE_PROVISION_SUBSCRIPTION_SUCCESS: 'IP_OFFICE_PROVISION_SUBSCRIPTION_SUCCESS',


    IP_OFFICE_PROVISIONING_CUSTOMER_SETTINGS: 'IP_OFFICE_PROVISIONING_CUSTOMER_SETTINGS',
    IP_OFFICE_PROVISION_CUSTOMER_SETTINGS_ERROR: 'IP_OFFICE_PROVISION_CUSTOMER_SETTINGS_ERROR',
    IP_OFFICE_PROVISION_CUSTOMER_SETTINGS_SUCCESS: 'IP_OFFICE_PROVISION_CUSTOMER_SETTINGS_SUCCESS',

    IP_OFFICE_PROVISIONING_SIP_TRUNKING: 'IP_OFFICE_PROVISIONING_SIP_TRUNKING',
    IP_OFFICE_PROVISION_SIP_TRUNKING_ERROR: 'IP_OFFICE_PROVISION_SIP_TRUNKING_ERROR',
    IP_OFFICE_PROVISION_SIP_TRUNKING_SUCCESS: 'IP_OFFICE_PROVISION_SIP_TRUNKING_SUCCESS',

    ZCLOUD_PURCHASING_PHONE_NUMBER: 'ZCLOUD_PURCHASING_PHONE_NUMBER',
    ZCLOUD_PURCHASE_PHONE_NUMBER_SUCCESS: 'ZCLOUD_PURCHASE_PHONE_NUMBER_SUCCESS',
    ZCLOUD_PURCHASE_PHONE_NUMBER_ERROR: 'ZCLOUD_PURCHASE_PHONE_NUMBER_ERROR'





  },
  API_STATUS_CODES: {
    '200': '200 OK',
    '401': '401 Unauthorized',
    '404': '404 Not found',
    '500': '500 Internal Server Error',
    '453': '453 Initial Order Not Found',
    '454': '454 Kazoo Account Not Found',
    '455': '455 User Not Found',
    '456': '456 Plan Not Updated',
    '457': '457 Subscription Not Updated',
    '458': '458 Kazoo Account Not Updated',
    '459':'459 Invalid Input Format',
    '460':'460 Could Not Authenticate Kazoo Account',
    '461':'460 Could Not Get Kazoo Users',
    '462':'462 User Emails Not Found In Kazoo Users',
    '463':'463 Old Plan could not be deleted',
    '464':'464 Failed To Send Email',
    '465':'465 The device does not exist',
    '466':'466 No Credit Card found',
    '467':'467 Invalid or Expired Credit Card'
  },
  PICTURE_URL_DOMAIN: "https://storage.googleapis.com/",
  NO_PICTURE_URL: "https://www.onesna.com/norevimages/noimage.jpg",
  ERROR_CODES: {
    PARTNER_EXISTS: "The user that is trying to apply is already a partner.",
    YOU_ARE_ALREADY_A_PARTNER_WITH_ZANG: "You are already a partner with Zang",
    PARTNER_ID_IS_NOT_PRESEND_NO_ORDER_TO_PLACE: "Partner Id is not present. No order to place.",
    PARTNER_NOT_FOUND_OR_PARTNER_IS_NOT_APPROVED: "Partner not found or Partner is not approved",
    CUSTOMER_ALREADY_EXISTS_FOR_THIS_PARTNER: "Customer already exists for this partner"
  },
  AUTH_TOKEN:'_AUTH_TOKEN',
  AUTH_TOKEN_SIG:'AUTH_TOKEN_SIG',
  EXTENSION_START_RANGE: 200,
  SALESFORCE_PHONE_CREDIT_PRODUCT_CODE: 'PhoneCredit',
  SALESFORCE_LICENSE_CREDIT_PRODUCT_CODE: 'LicenseCredit',
  PAYMENT_METHODS:  {
    CREDIT_CARD: "Credit Card"
  },
  PAYMENT_GATEWAYS: {
    STRIPE: "STRIPE",
    SALESFORCE: "SALESFORCE"
  },
  STRIPE_OBJECTS: {
    card: "CREDIT_CARD"
  },
  CHARGE_STATUS:  {
    NONE: "NONE",
    PENDING: "PENDING",
    CHARGED: "CHARGE_SUCCESS",
    CHARGE_FAILED: "CHARGE_FAILED"
  },
  BILLING_ENGINE_METHOD: {
    PLAN_B: "PLAN_B",
    PLAN_A: "PLAN_A",
    PLAN_C: "PLAN_C"
  },

  CORS_CFG: {
    origin: [/\.onesna\.com$/, /\.avayamarket\.com$/, /\.zang\.io$/, /\.esna\.com$/]
  }
}
