export const ACTION_TYPES = {
  INIT_MAIN_SUBMENU: 'INIT_MAIN_SUBMENU',   
  FETCH_PAGE_SUBMENUS: 'FETCH_PAGE_SUBMENUS',
  FETCH_PAGE_SUBMENUS_SUCCESS: 'FETCH_PAGE_SUBMENUS_SUCCESS',
  FETCH_PAGE_SUBMENUS_FAILURE: 'FETCH_PAGE_SUBMENUS_FAILURE',
};
