export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'Can not dcrypt the data from Accounts system',
  PHONE_TYPES: 'Phone types',
  IMAGINE_A_BETTER_WAY: 'Imagine a better way',
  OF_DOING_THINGS: 'of doing things.',
  GET_STARTED: 'Get Started',
  PURCHASE: 'Purchase',
  DOWNLOADS_AND_EXTENSIONS: 'Downloads & Extensions',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: 'Make the most of your Zang products with these must have add-ons!',
  ALL: 'All',
  REFERRAL_AGENT: 'Referral Agent',
  SALES_AGENT: 'Sales Agent',
  CART: 'Cart',
  PARTNER_PROGRAMS: 'Partner Programs',
  HOME: 'Home',
  MANAGE_CREDIT_CARDS: 'Manage Credit Cards',
  MANAGE_PAYMENT_OPTIONS: 'Manage Payment Options',
  MANAGE_BILLING_ACCOUNT: 'Manage Billing Account',
  LIMIT: "Limit",
  MY_PROFILE: 'My Profile',
  MY_SETTINGS: 'My Settings',
  MY_PARTNER_PORTAL: 'My Partner Portal',
  CLEAR_ZANG_OFFICE: 'Clear Avaya Cloud',
  CLEAR_ZANG_SPACES: 'Clear Avaya Spaces',
  FEATURE_BREAKDOWN: 'Feature Breakdown',
  PLAN_BREAKDOWN: 'Plan Breakdown', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'The business phone you need. At a price you\'ll love',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Imagine what you can get done in Avaya Spaces',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'A discount of 50% will be applied to your total amount after you checkout',
  HURRICANE_HARVEY_MESSAGE: '<h1 class="text-400">Avaya and Zang would like to help those businesses affected by a hurricane during the 2017 Hurricane Season.</h1><h3 class="text-300">Three months of free Zang services available to any impacted business in the US, Canada or Puerto Rico.</b></h3>',
  LEARN_MORE: 'Learn more',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ IS NOW AVAILABLE',
  NEW: 'NEW!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Experience the best of Avaya Cloud Solutions with this all-glass, easy-to-use, voice, video & chat collaboration phone.',
  LOG_IN: 'Log In',
  SIGN_UP: 'Sign Up',
  SIGN_OUT: 'Sign Out',
  SIGN_IN: 'Sign In', //login to the system, connect
  ADMINISTRATION: 'Administration',
  PRODUCTS: 'Products',
  ORDERS: 'Orders',
  PAGES: 'Pages',
  CUSTOMERS: 'Customers',
  USERS: 'Users',
  PLANS: 'Plans',
  ZANG_OFFICE: 'Avaya Cloud',
  IP_OFFICE: 'IP Office',
  CDRS: 'Cdrs',
  CDR_CHECKS: 'Cdr Checks',
  PARTNERS: 'Partners',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'It seems that you have already purchased Avaya Cloud. You cannot place any more Avaya Cloud orders.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'It seems that you have already purchased Avaya Cloud for this company. Please select a different company.',
  PARTNER_CONNECTIONS: 'Partner Connections',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'There was an error placing your order. Please contact Avaya Cloud support ({SUPPORT_EMAIL}) for more information.',
  APPLICATION_GENERAL_FATAL_ERROR: 'There was an error submitting your application. Please contact Avaya Cloud support ({SUPPORT_EMAIL}) for more information.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Please select at least one user type to continue.',
  BACK: 'Back',
  SAVE_CHANGES: 'Save changes',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: 'Are you sure you want to proceed?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'You have {PLACEHOLDER} in credit to spend towards the purchase of any device. This credit will be lost once your order has been submitted.',
  JUST_A_REMINDER: 'Just a reminder',
  LAST_CHANCE: 'LAST CHANCE',
  IM_GOOD_PLACE_MY_ORDER: 'I\'m good - Place My Order',
  BUY_MORE_DEVICES: 'Buy more devices',
  YES_PLACE_MY_ORDER: 'Yes, place my order',
  NO_THANKS: 'No, thanks!',
  YES: 'Yes',
  ABOUT_US: 'About us',
  NEWS_AND_PRESS: 'News & Press',
  CARREERS: 'Carreers',
  CONTACT_US: 'Contact Us',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Thank you for shopping with us. Your order details are indicated below.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: 'Please contact <a href="mailto:{EMAIL}">{EMAIL}</a> for this information',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'Our Customer Success and Technical Support Teams will contact you when your system is ready. <br/><br/><b>Please note it could take up to an hour to set up your system.</b>',
  QUESTION_CUSTOMER_SERVICE: 'Please email us at <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a> if you have any questions!',
  BLOG: 'Blog',
  FAQS: 'FAQs',
  DOCUMENTATION: 'Documentation',
  TERMS_OF_SERVICE: 'Terms Of Service',
  HELP: 'Help',
  PRIVACY_STATEMENT: 'Privacy Statement',
  GENERAL_PRIVACY_STATEMENT: 'General Privacy Statement',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: 'General Terms Of Service - Avaya Cloud Solutions',
  COOKIE_STATEMENT: 'Website Cookie Statement',
  COOKIE: 'Cookie Statement',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. All Rights Reserved.',
  PROCESSING: 'Processing',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Please be patient. The process might take sometime',
  OPEN_IN_A_NEW_TAB: 'Open in a new Tab',
  GOT_IT: 'Got it!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' This action will have the following results:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Delete the monthly subscription for this plan',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Disable any account on any third party systems',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Change the status of this plan to DISABLED',
  LAST_ACTION_STEPS: 'Last Action Steps',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'Add-ons are purchased through the Avaya Cloud admin portal once the account has been created.',
  TYPE: 'Type',
  ADMIN: 'Admin',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'This user will be configured as the primary / billing contact for the corporate account.  It can be changed at anytime through the Avaya Cloud admin portal.',
  DESCRIPTION: 'Description',
  SUCCESS: 'Success',
  REQUEST_CANCELATION: 'Request Cancellation',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Well, this isn\'t good! Sorry to hear that you want to leave.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Please fill out the form below to start the cancellation process. A member of our customer success department will review and follow up your request within 1-2 business days to make this a seamless process.',
  YOUR_NAME: 'Your name',
  COMPANY: 'Company',
  SERVICE: 'Service',
  REASON_FOR_CANCELING: 'Reason for Canceling',
  SUBMIT: 'Submit',
  EXIT: 'Exit',
  REQUEST_SUBMITTED: 'Request Submitted!',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'A member of our customer success department will review and follow up your request within 1-2 business days to make this a seamless process.',
  DATE: 'Date',
  PRODUCT: 'Product',
  USER: 'User',
  STATUS: 'Status',
  ACTIONS: 'Actions',
  VIEW_DETAILS: 'View Details',
  DISABLE: 'Disable',
  ENABLE: 'Enable',
  CANCEL: 'Cancel',
  PLAN_DETAILS: 'Plan Details',
  SUMMARY: 'Summary',
  QUANTITIES: 'Quantities',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*Total includes the prices of plan features',
  TOTAL: 'Total',
  BILLED: 'Billed',
  PLAN_INFORMATION: 'Plan Information',
  UPDATE_PLAN: 'Update Plan',
  ADMIN_ACTIONS: 'Admin Actions',
  NAME_ON_CREDIT_CARD: 'Name on Credit Card',
  CREDIT_CARD_BRAND: 'Credit Card Brand',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: 'Credit Card Number',
  EXPIRATION: 'Expiration',
  MONTH: 'Month',
  YEAR: 'Year',
  SECURITY_CODE: 'Security Code',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'The code on the back of your credit card',
  BACK_TO_CHECKOUT: 'Back to checkout',
  NO_ORDERS_FOUND: 'No orders found',
  ADD: 'Add',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Use the form above to add a new credit card. Please make sure you fill all the fields',
  NUMBER: 'Number',
  EXPIRES: 'Expires',
  DELETE: 'Delete',
  ITEM_DETAILS: 'Item Details',
  FEE: 'Fee',
  ITEMS: 'Items',
  SEARCH_BY_CONFIRMATION: 'Search by Confirmation',
  CONFIRMATION: 'Confirmation',
  CHECKOUT_STATUS: 'Checkout Status',
  ORDER_STATUS_PROCESS: 'Order Status Process',
  CREATED_ON: 'Created on',
  ORDER_SUMMARY: 'Order Summary',
  APPROVED: 'Approved', //example: partner application approved
  REJECTED: 'Rejected', //example: partner application rejected
  APPROVE: 'Approve', //example: partner application approved
  REJECT: 'Reject', //example: partner application rejected
  PENDING: 'Pending', //example: partner application pending
  PENDING_APPROVAL: 'Pending Approval',
  CANCELED: 'Canceled',
  FAILED: 'Failed',
  EDIT: 'Edit',
  ONE_TIME_FEE: 'One Time Fee',
  SUB_TOTAL: 'Sub-total',
  TAXES: 'Taxes',
  CHANGES: 'Changes',
  CREATE_A_QUOTE: 'Create a Quote',
  EXTRA_INFORMATION: 'Extra Information',
  THANK_YOU_FOR_YOUR_ORDER: 'Thank you for your order',
  ORDER_CONFIRMATION: 'Order Confirmation',
  INVALID_ORDER: 'Invalid Order',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'Don\'t worry, we\'ve also emailed this to you :)',
  HELLO: 'Hello',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Thank you for shopping with us. We\'ll send a confirmation once your items have shipped. Your order details are indicated below.',
  ACCOUNT_INFORMATION: 'Account Information',
  CONTACT_INFORMATION: 'Contact Information',
  COMPANY_INFORMATION: 'Company Information',
  BILLING_INFORMATION: 'Billing Information',
  SHIPPING_INFORMATION: 'Shipping Information',
  NAME: 'Name',
  EMAIL: 'Email',
  SEARCH: 'Search',
  CLEAR: 'Clear',
  PARTNER: 'Partner',
  NO_PARTNERS_FOUND: 'No Partners Found',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'A partner connection is created when a customer lands on the store from a partner\'s personal link.',
  CUSTOMER: 'Customer',
  AGENT: 'Agent',
  NO_PARTNER_CONNECTIONS_FOUND: 'No Partner Connections Found',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'I have read and agree with the',
  ZANG_PRIVACY_STATEMENT: 'Zang Privacy Statement',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'Agent Program Terms Of Service',
  SUBMIT_APPLICATION: 'Submit Application',
  SUBMITTING: 'Submiting',
  SUBMITTING_YOUR_APPLICATION: 'Submiting your application',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'All bank and account information is held private & secure under our terms and conditions.',
  BANK_NAME: 'Bank Name',
  ADDRESS: 'Address',
  COUNTRY: 'Country',
  SELECT_ONE: '- Select One -',
  STATE_PROVINCE: 'State/Province',
  PROVINCE: 'Province',
  STATE: 'State',
  CITY: 'City',
  ZIP_POSTAL_CODE: 'Zip/Postal Code',
  POSTAL_CODE: 'Postal Code',
  ZIP_CODE: 'Zip Code',
  ACCOUNT_NUMBER: 'Account Number',
  BANK_NUMBER: 'Bank Number',
  TRANSIT_NUMBER: 'Transit Number',
  SWIFT_CODE: 'Swift Code',
  TAX_REGISTRATION_NUMBER: 'Tax Registration Number',
  SAVE_BANK_INFORMATION: 'Save Bank Information',
  SAVING_BANK_INFORMATION: 'Saving Bank Information',
  NO_CUSTOMERS_FOUND: 'No Customers Found',
  YOU_ARE_A: 'You are a ',
  A_DISCOUNT_OF: 'A discount of',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'will be applied to your total amount after you checkout.',
  FIRST_NAME: 'First Name',
  INVALID_EMAIL: 'Please provide a valid email address',
  INVALID_PHONE_NUMBER: 'Please enter a valid phone number',
  LAST_NAME: 'Last Name',
  COMPANY_NAME: 'Company Name',
  LEGAL_COMPANY_NAME: 'Legal Company Name',
  PHONE_NUMBER: 'Phone Number',
  WEBSITE: 'Website',
  OPERATIONAL_ADDRESS: 'Operational Address',
  SAME_AS_ORGANIZATION_ADDRESS: 'Same as Organization Address',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: 'Are you an existing Avaya Partner?',
  NO: 'No',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'If yes, please enter your Avaya Partner ID',
  MY_PARTNER_PORTAL: 'My Partner Portal',
  THANK_YOU_FOR_APPLYING: 'thank you for applying!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'One more step and you\'re done! To complete your Sales Agent Application, please follow the link below and answer all questions.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' If not, please give ',
  PLEASE_GIVE: 'Please give',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'If you are an existing Avaya Partner please do NOT follow the link below. <br />We are currently reviewing your Partner ID and will contact you shortly.',
  BUSINESS: 'business',
  DAYS: 'days',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'for Senior Management to review your application.<br /> In the meantime, all questions can be sent to',
  COMPLETE_MY_APPLICATION: 'Complete My Application',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'We have reviewed your application. Unfortunately at this time, we have determined that it is unfit for our program. It’s probably nothing serious but we cannot move forward with our partnership until we figure this out. We understand this might be frustrating. Please be aware that we are looking into the reasoning and will contact you as soon as we have more information. In the meantime, feel free to contact',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'with any questions regarding this process.',
  CONGRATULATIONS: 'congratulations',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: 'You are now an official Zang Agent!',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Get Started by sharing your personal link with all of your leads',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'and help them experience a better way of doing things.',
  CHANGE_STATUS: 'Change Status',
  AGENT_DETAILS: 'Agent Details',
  BANK_INFORMATION: 'Bank Information',
  THIS_ORDER_WAS_PLACED_BY_A: 'This order was placed by a',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'was applied to the total amount',
  REFERRALS: 'Referrals',
  SALES: 'Sales',
  FOUND: 'Found',
  HOW_IT_WORKS: 'How it works',
  WHAT_YOU_GET: 'What you get',
  SUPPORT: 'Support',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'Which Program is best for me?',
  WHY_JOIN: 'Why join?',
  QUOTE: 'Quote',
  PRINT_THIS_QUOTE: 'Print this Quote',
  CLOSE_THIS_WINDOW: 'Close this window',
  SEARCH_BY_PLAN: 'Search by Plan',
  ACCESS_LEVEL: 'Access Level',
  DISPLAY_NAME: 'Display Name',
  INDUSTRY: 'Industry',
  COMPANY_INDUSTRY: 'Company Industry',
  CONTACT_PHONE_NUMBER: 'Contact Phone Number',
  EMAIL_ADDRESS: 'Email Address',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Yes, send me email regarding Avaya news, applications, deals and special events!',
  INFORMATION: 'Information',
  ORDER_HISTORY: 'Order History',
  FILTER: 'Filter',
  ACCOUNT: 'Account',
  AMOUNT_CHARGED: 'Amount Charged',
  DETAILS: 'Details',
  NO_RECORDS_FOUND: 'No Records Found',
  CALL_LOGS: 'Call Logs',
  EXPORT: 'Export',
  CALLER_NAME: 'Caller Name',
  DIALED_NUMBER: 'Dialed Number',
  DURATION_SEC: 'Duration (Sec)',
  COST: 'Cost',
  PAYMENT_METHOD: 'Payment Method',
  PURCHASE_ORDER: 'Purchase Order',
  PURCHASE_ORDERS: 'Purchase Orders',
  CREDIT_CARD: 'Credit Card',
  SHIPPING_ADDRESS: 'Shipping Address',
  BILLING_ADDRESS: 'Billing Address',
  NO_EXISTING_QUOTES_FOUND: 'You do not have any existing quotes. Start by adding new Quote',
  ADDRESS1: "Address 1",
  SAME_AS_BILLING_ADDRESS: 'Same as Billing Address',
  SAME_AS_SHIPPING_ADDRESS: 'Same as Shipping Address',
  OTHER: 'Other',
  SHIPPING_OPTIONS: 'Shipping Options',
  FREE_SHIPPING: 'FREE Shipping',
  ADDITIONAL_NOTES: 'Additional Notes',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'I have read and I agree to the following:',
  EMERGENCY_911_SERVICE_NOTICE: 'Emergency 911 service notice',
  PLACE_MY_ORDER: 'Place My Order',
  CLEAR_MY_ORDER: 'Clear My Order',
  PLACING_YOUR_ORDER: 'Placing Your Order',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'This might take up to 1 minute. To ensure your order is not interrupted, please avoid closing this browser window or clicking the back or refresh buttons.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'This process may take some time. Thank you for your patience. To ensure your order is not interrupted, please avoid closing this browser window or clicking the back or refresh buttons.',
  YOUR_NEW_NUMBER: 'Your new number',
  NO_NUMBER_SELECTED: 'No Number Selected',
  WELL_THAT_WAS_EASY: 'Well that was easy!',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'A couple more steps and you\'re done :)',
  NEXT: 'Next',
  TITLE: 'Title',
  SUB_TITLE: 'Sub Title',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Search by area code...',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: 'Enter area code...',
  SELECT_A_PREFIX: 'Select a prefix',
  PICK_THIS_NUMBER: 'Pick this number',
  DEVICES: 'Devices',
  BILLING: 'Billing',
  CHANGE: 'Change',
  USER_INFO: 'User info',
  USER_ID: 'User ID',
  USE_MY_INFORMATION: 'Use my information',
  SELECT_YOUR_DEVICES: 'Assign devices to your users!',
  MONTHLY_FEE: 'Monthly Fee',
  ANNUAL_FEE: 'Annual Fee',
  TWO_YEAR_FEE: '2 Year Fee',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Each Avaya Cloud plan requires at least one Standard OR Power user.',
  CHECKOUT: 'Checkout',
  MINE: 'Mine',
  REMOVE_THIS_USER: 'Remove this user',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Select a device for this user',
  ADD_ANOTHER: 'Add Another',
  GET_STARTED_WITH_ZANG_OFFICE: 'Get Started with Avaya Cloud Solutions',
  BUNDLE: 'bundle',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Sign-up for a year and receive',
  OFF: 'OFF',
  EACH_USER: 'each user',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'To adjust your user quantities, you must either clear your order or continue to the ‘devices’ step.',
  EVERY_TWO_YEARS: 'Every 2 years',
  YOU_VE_SAVED: 'You\'ve saved',
  INCLUDED: 'Included',
  ADDONS: 'Add-ons',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Customize each user to their liking!',
  UNITS_PER: 'Units Per',
  TALK_ANYWERE_ANYTIME: 'Talk anywhere, anytime!',
  DOWNLOAD_FOR_MAC: 'Download for MAC',
  DOWNLOAD_FOR_WINDOWS: 'Download for Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Thank you for buying Avaya Cloud! View your order here!',
  CONTINUE_WITH_YOUR_PURCHASE: 'Continue with your purchase!',
  GET_STARTED_TODAY: 'Get Started Today!',
  FEATURES: 'Features',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Let\'s break it down for you!',
  BASIC: 'Basic',
  STANDARD: 'Standard',
  POWER: 'Power',
  RATE_MIN_STARTING_FROM: 'Rate/min, Starting from*:',
  RATE_MIN_STARTING_FROM_1: 'Rate/min, Starting from',
  LONG_DISTANCE: 'International Long Distance',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'International Long Distance Rates*',
  COMMON_DESTINATIONS: 'Common Destinations',
  BEST_DEAL: 'best deal',
  PER_ACTIVE_USER_PER_MONTH: 'Per active user, per month.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'according to annual contract',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'Billed according to selected plan.',
  MONTHLY: 'Monthly',
  ANNUALLY: 'Annually',
  BILLED_ANNUALY: 'Billed Annually',
  BILLED_EVERY_TWO_YEARS: 'Billed every 2 Years',
  CONFIGURE_YOUR_ADDONS: 'Configure your Add-ons',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Select a quantity for each of the available Add-ons.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'Maximum quantity for this addon is',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'This addon is only available for',
  BILLING_AND_SHIPPING: 'Billing and Shipping',
  BILLING: 'Billing',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'This will be your Avaya Cloud Account Name.',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'This will be your Avaya Cloud Account Name.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'If you\'ve chosen to use your existing or a toll-free number as your Avaya Cloud Solutions number, we will try to find a local number with the extension used in this field.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Everything Happens in Spaces',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'The cloud-based team collaboration tool you\'ve always wanted but could never find.',
  YOUR_CURRENT_PURCHASES: 'Your current purchases',
  PURCHASED_ON: 'Purchased On',
  PLAN_NUMBER: 'Plan Number',
  UPDATE: 'Update',
  UPDATED: 'Updated',
  OR: 'or',
  MAKE_A_NEW_PURCHASE: 'Make a new purchase',
  FEATURES_AND_ADDONS: 'Features & Add-ons',
  FREE: 'BASIC',
  PLUS: 'STANDARD',
  BUSINESS: 'Business',
  ESSENTIAL: 'Essential',
  VIEW: 'View',
  TEAM: 'Team',
  LETS_SETUP_YOUR_TEAM: 'Let\'s set-up your Team',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Simply select the type of the team you want to create and set-up your private environment.',
  COMPANY_TYPE: 'Company Type',
  DOMAIN: 'Domain',
  NO_TEAM_IS_SETUP_YET: 'No team is setup yet',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'Do not set-up a team for me',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Purchase Avaya Spaces just for you.',
  CHOOSE_AN_EXISTING_COMPANY: 'Choose an existing company',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Select one of the companies you\'re currently administrating.',
  CREATE_A_NEW_TEAM: 'Create a new team',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Provide a team and domain name.',
  NO_DOMAIN_IS_CONFIGURED: 'No domain is configured.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Please provide a domain name (ex: \'zang.io\')',
  CHECK: 'Check',
  TEAM_DOMAIN: 'Team Domain (ex: \'zang.io\')',
  TEAM_NAME: 'Team Name (ex: \'Zang\')',
  OK: 'OK',
  ZANG_SPACES_ADMIN_CONSOLE: 'Avaya Spaces Admin Console',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'You can change the values below to update your plan',
  CHARGABLE_USERS: 'Chargeable Users',
  TOTAL_USERS: 'Total Users',
  CURRENT_PRICE: 'Current Price',
  SAVE: 'Save',
  SAVE_CHANGES_AND_UPDATE_PLAN: 'Save changes and update the plan?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Please select at least one type of user to continue',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'You\'re purchasing Avaya Spaces for',
  BUY_NOW: 'Buy Now',
  SELECT: "Select",
  UP_TO: 'Up to',
  NO_PURCHASE_REQUIRED: 'no purchase required',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'No billing or upfront commitment.',
  SIGN_UP_FOR_FREE: 'Sign-up for FREE!',
  ONE_YEAR_PLAN: '1 Year Plan',
  MONTHLY_PLAN: 'Monthly Plan',
  MONTHS_PLAN: '{0} Months Plan',
  YEARS_PLAN: '{0} Year Plan',
  TWO_YEAR_PLAN: '2 Year Plan',
  MONTHS: 'Months',
  ZANG_OFFICE_ACCOUNT_NAME: 'Avaya Cloud Solutions Account Name',
  ZANG_OFFICE_PLAN_NUMBER: 'Avaya Cloud Solutions Plan Number',
  TEMPORARY_NUMBER: 'Temporary Number',
  START_SETTING_UP_ZANG_OFFICE: 'Start setting up Avaya Cloud Solutions!',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'If you are transferring an existing number to your Avaya Cloud account, you will need to fill out and return this <b><a href="{0}">LNP Authorization Form</a></b> along with a copy of your most recent phone bill. If you are transferring a toll-free number, please also fill out this <b><a href="{1}">RODAA Form</a></b>. Please send all applicable paperwork to <b>customersuccess@zang.io</b>. The phone number transferring process could take up to 10 business days.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'There was an error buying/activating the chosen Avaya Cloud Solutions Numbers.Click \'Start setting up Avaya Cloud Solutions\' to activate/buy your numbers manually. In case you\'ve chosen to use your existing number, the porting process will not be affected.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'If you are transferring an existing number to your Avaya Cloud Solutions account, you will need to fill out and email this <a href="{LNP_FORM_LINK}" target="_blank" rel="noopener noreferrer">LNP Authorization Form</a> along with a copy of your most recent phone bill. If you are transferring a toll-free number, please also fill out this <a href="{RODAA_LINK}" target="_blank" rel="noopener noreferrer">RODAA Form</a>. Please send all applicable paper work to <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. The phone number transferring process could take up to 10 business days.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Please note that the phone number transferring process could take up to 10 business days. In the meantime, we will attach a temporary phone number for you to use within your account.',
  PURCHASE_NUMBER_DISCLAIMER: 'If the chosen number is not available at checkout, a similar number will be selected.',
  PLAN_STATUS: 'Plan Status',
  PLAN_ID: 'Plan ID',
  SUBSCRIPTION_ID: 'Subscription ID',
  STRIPE_PLAN_ID: 'Stripe Plan ID',
  ACCOUNT_ID: 'Account ID',
  START_SETTING_UP_ZANG_SPACES: 'Start setting up Avaya Spaces',
  COMPANY_DOMAIN: 'Company Domain',
  THIS_FIELD_IS_REQUIRED: 'This field is required.',
  PLEASE_ANSWER_THIS_QUESTION: 'Please answer this question.',
  PARTNER_TYPE: 'Partner Type',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Please enter your Avaya Partner ID.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Please read and agree with the Privacy Statement to continue.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Please read and agree with the Agent Program Terms of Services to continue.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'This Avaya Partner ID is already in use.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'This Tax Registration Number is already in use.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'This is not a valid Avaya Partner ID.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'Quantity must be a positive number',
  ORDER_COMPLETE: 'Order Complete!',
  PLEASE_TRY_AGAIN: 'Please try again',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Please select at least one positive value',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'Update is still in progress.Please try again later.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'You cannot have more than one user for a personal license. To upgrade or downgrade your plan, change the quantites accordingly.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'You don\'t have access to this account.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Your current plan does not allow you to decrease users less than your original amount. If this is something you’d like to adjust, please contact us at customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'There was an error placing your order. Please ensure that all the fields have valid values and if the error insists, contact Avaya Cloud support for more information',

  USE_EXISTING_NUMBER: 'Transfer Existing Number',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Select to transfer an existing number to your plan',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Pre-select a Toll-Free Number',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Select to add a toll-free number to your plan',
  FIND_A_LOCAL_NUMBER: 'Find a Local Number',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Select from a list of local numbers in your area to add to your plan',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: 'Select to add a local number to your plan',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: 'Search by area code for available phone numbers',
  SEARCH_AVAILABLE_PHONE_NUMBERS: 'Search available phone numbers',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: 'Enter existing number you plan to transfer',


  ZANG_OFFICE_PHONE_APP: 'Avaya Cloud Solutions Phone App',
  ZANG_OFFICE_SOFTPHONE: 'Avaya Cloud Solutions Softphone',
  ZANG_OFFICE_PHONE_APPLICATION: 'Avaya Cloud Solutions Phone Application',
  SOFTPHONE_MARKETING_DESCRIPTION: 'The Avaya Cloud Solutions softphone includes all the communication features you have come to expect right on your desktop or mobile device. Take advantage of all the great Avaya Cloud Solution features without breaking the bank as the Avaya Cloud Solutions softphone is included for free with your Avaya Cloud Solutions subscription!',
  E129_SIP_DESK_PHONE: 'E129 SIP Desk Phone',
  STANDARD_PHONE: 'Standard Phone',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'The Avaya E129 SIP Deskphone packs all the essential call handling features you’d expect in an affordable, yet highly functional SIP phone.The Avaya E129 deskphone enables users to transfer, mute, forward and place calls on hold as well as initiate ad-hoc conferences with the press of a button. The full duplex speakerphone allows for hands-free conversations, and its Power over Ethernet port offers convenient connection to the network. The Avaya E129  SIP Deskphone has the right calling capabilities and is both affordable and attractive. AC Power adapter included.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Engage using an innovative, all-glass, dedicated desktop device. Use voice, chat, and collaboration apps through one-touch connections. There are no unnatural breaks or pauses. And no need to manage multiple devices for engagement. Mesh unique custom experiences into your workflows and business processes. This powerful, customizable device gives you the advantages of a deskphone and the flexibility of an application platform.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'B179 Conference Phone',
  CONFERENCE_PHONE: 'Conference Phone',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Best suited for board rooms and large conference rooms with groups greater than 10 people, the B179 Conference Phone helps improve employee productivity and collaboration.The B179 Conference Phone is a versatile high performer that complements your existing solutions and can be easily redeployed as your business grows or as needs change. AC Power adapter included.',
  PLAN: 'Plan',
  REDIRECTING: 'Redirecting',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Please ensure that all the fields have valid values',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Each Avaya Cloud Solutions plan requires at least one user type. Please go back to the devices selection step and change your configuration.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'It seems that you haven\'t selected any number for your Avaya Cloud Solutions account. Please go back to the number selection step to select a number.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'That Avaya Cloud Account Name is Taken. Try another',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'The Avaya Cloud Solutions number you selected has already been purchased by another customer. Please go back to the number selection step and select a different number.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Go month-to-month with no commitment and get the <span class="text-400">FIRST 30 DAYS FREE</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'or commit to an annual plan and get better pricing and a',
  FREE_PHONE: 'FREE PHONE',
  DISCOUNT: 'discount',
  DISCOUNTED_PHONE: 'discounted phone',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'off the total value of your phone purchases',
  LIMITED_TIME_OFFER: 'Limited time offer',
  PROMOTION: 'Promotion',
  ZANG_SPACES_PROMOTION: 'Avaya Spaces Promotion',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Continue to phone number selection',
  DURATION: 'Duration',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'Congratulations! You have a credit of <strong>{amount}</strong> to put towards the total of your devices order!',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'All applicable discounts will be adjusted within your final order summary.',
  SHIPPING_TYPE: 'Shipping Type',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'Tracking details will be sent once your items have shipped from our warehouse',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Receive {amount} credit per user towards the purchase of any device. Limited time offer.',
  PARTNER_ORDERS: 'Partner Orders',
  COMMISSION: 'Commission',

  ADDITIONAL_DEVICES: 'Additional Devices',
  NO_USER: 'No User',
  QUANTITY: 'Quantity',
  BUY_DEVICES: 'Buy Devices',
  DEVICE: 'Device',
  PRICE: 'Price',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'Please type at least {chars} characters to search for an Agent',
  NO_RESULTS_FOUND: 'No results found',
  RESULTS_COULD_NOT_BE_LOADED: 'Results counld not be loaded',
  CLEAR_SELECTION: 'Clear Selection',


  RESET_ALL_PURCHASES: 'Clear All Purchases',
  LISTS: 'Lists',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Please fill out your phone number before you create a quote.',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Please fill out your billing and shipping information before you create a quote',
  CALCULATING_TAXES_PLEASE_WAIT: 'Calculating Taxes. Please wait...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Something is wrong with the creditcard you chose.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Something is wrong with this Credit Card. Please use a different one',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'There was an error charging your order. Please choose a different credit card',
  INVALID_CREDIT_CARD: 'Invalid Credit Card',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: 'The {address_type} does not match with the credit card address information',
  INVALID_SECURITY_CODE: 'Invalid Security Code (cvc)',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Any applicable discounts & promotional pricing has been applied to this invoice',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'We were unable to create your customer account. Please try again',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'We were unable to create your Credit Card. Please try again',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'This credit card is in use for a recurring subscription.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Error setting this credit card as default.',
  DEFAULT: 'Default',
  SET_DEFAULT: 'Set default',
  SALES_FORCE_QUOTE_ID: 'Salesforce Quote ID',
  SALES_FORCE_ORDER_ID: 'Salesforce Order ID',
  SALES_FORCE_OPPORTUNITY_ID: 'Salesforce Opportunity ID',
  SALES_FORCE_CONTACT_ID: 'Salesforce Contact ID',
  SALES_FORCE_CONTRACT_ID: 'Salesforce Contract ID',
  SALES_FORCE_ACCOUNT_ID: 'Salesforce Account ID',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Simply \'Add a device\' and connect it with a user.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Simply \'Add a device\' and connect it with a user.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Buy additional devices for your Avaya Cloud Account',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'Opps! Something is wrong with your order. Refresh the page, clear your order and start over.',
  CREATE_A_NEW_COMPANY: 'Create a new company',
  ADD_A_NEW_COMPANY: 'Add a new Company',
  PARTNER_DETAILS: 'Partner Details',
  AGENTS: 'Agents',
  PARTNER_PORTAL: 'Partner Portal',
  AGENT: 'Agent',
  AGENT_PORTAL: 'Agent Portal',
  NO_AGENTS_FOUND: 'No Agents Found',
  NO_AGENT: 'No agent',
  RELATION: 'Relation',
  OWNER: 'Owner',
  ADMIN: 'Admin',
  MANAGER: 'Manager',
  EMPLOYEE: 'Employee',
  ACTIVE: 'Active',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: 'Please one of the partners that you are associated with',
  APPLIED_ON: 'Applied on',
  JOIN_A_PARTNER: 'Join a partner',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'You are a step away from joining <b>{COMPANY_NAME}</b>',
  JOIN_PLACEHOLDER_NOW: 'Join {COMPANY_NAME} now',
  UPDATE_AGENT_INFO: 'Update agent info',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Get Started with Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'In Association with Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'A Simple, Powerful, Unified Collaboration Solution',
  IP_OFFICE_DONT_PAY_TILL: 'Don\'t pay until April 15th, 2018!',
  LOGIN: 'Login',
  DISCOVER: 'Discover',
  SOLUTIONS: 'Solutions',
  SERVICES: 'Services',
  INDUSTRIES: 'Industries',
  CASE_STUDIES: 'Case Studies',
  PROGRAMS_AND_PROMOTIONS: 'Programs and Promotions',
  AUTHENTIC_AVAYA: 'Authentic Avaya',
  PERSPECTIVES: 'Perspectives',
  AVAYA_CONNECTED_BLOG: 'Avaya Connected Blog',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: 'Solution Finder',
  INFO_FOR: 'Info for',
  DEVELOPERS: 'Developers',
  CHANNEL_PARTNERS: 'Channel Partners',
  TECHNOLOGY_PARTNERS: 'Technology Partners',
  CONSULTANTS: 'Consultants',
  INVESTORS: 'Investors',
  MEDIA_ANALYSTS: 'Media Analysts',
  SUPPLIERS: 'Suppliers',
  CONNECT_WITH_US: 'Connect with us',
  FIND_A_CHANNEL_PARTNER: 'Find a Channel Partner',
  FIND_A_TECHNOLOGY_PARTNER: 'Find a Technology Partner',
  EXECUTIVE_BRIEFING_CENTER: 'Executive Briefing Center',
  AVAYA_LEARNING_SERVICES: 'Avaya Learning Services',
  CONTACTS: 'Contacts',
  ABOUT_AVAYA: 'About Avaya',
  EVENTS: 'Events',
  NEWSROOM: 'Newsroom',
  INVESTOR_RELATIONS: 'Investor Relations',
  CORPORATE_RESPONSIBILITY: 'Corporate Responsibility',
  OUR_COMPANY: 'Our Company',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'International Avaya Users Group - IAUG',
  CAREERS: 'Careers',
  YOUR_PERSONAL_LINK: 'Your personal link',
  SITEMAP: 'Sitemap',
  TERMS_OF_USE: 'Terms of Use',
  PRIVACY: 'Privacy',
  COOKIES: 'Cookies',
  AVAYA_INVOICE: 'Invoice',
  IP_OFFICE_ACCOUNT_NAME: 'Avaya Cloud Account Name',
  IP_OFFICE_PLAN_NUMBER: 'Avaya Cloud Plan Number',
  IP_OFFICE_PHONE_APPLICATION: 'Avaya Cloud Solutions Softphone',
  IP_OFFICE_PHONE_DESCRIPTION: 'The Avaya Cloud Solutions softphone provides users with simple access to all the communication channels in a single interface. Avaya Cloud Solutions softphone enables you to log into your Avaya Cloud Solutions and make and receive voice and video calls from your deskphone extension using your PC. Softphone is included for free with Avaya Cloud Solutions Standard and Power user subscriptions.',
  PLAN_MONTH_1_MONTH_1: 'Monthly Plan (No Device Credit)',
  PLAN_YEAR_1_MONTH_1: '1 Year Plan | Billed Monthly',
  PLAN_YEAR_1_YEAR_1: '1 Year Plan, Pay in Full',
  PLAN_YEAR_2_MONTH_1: '2 Year Plan | Billed Monthly',
  PLAN_YEAR_2_YEAR_1: '2 Year Plan | Billed Yearly',
  PLAN_YEAR_2_YEAR_2: '2 Year Plan, Pay in Full',
  PLAN_YEAR_3_MONTH_1: '3 Year Plan | Billed Monthly',
  PLAN_YEAR_3_YEAR_1: '3 Year Plan | Billed Yearly',
  PLAN_YEAR_3_YEAR_3: '3 Year Plan,  Pay in Full',
  PLAN_YEAR_5_MONTH_1: '5 Year Plan | Billed Monthly',
  ACCORDING_TO_PLAN: 'According to Plan',
  TOTAL_USER_PLAN_FEE: 'Total User Plan Fee',
  HEALTHCARE_DENY_MESSAGE: 'Thank you for choosing Avaya Cloud as your solutions, unfortunately we\'re not HIPAA compliant yet, so we can\'t provide you our service because you\'re in healthcare.  We\'ll be sure to let know when we get our certification, and we hope can have you back then!  Feel free to reach out to <a href="mailto:cloudsuccess@avaya.com">cloudsuccess@avaya.com</a> if you have any questions.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Select your Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup> Devices',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Select your Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup> Number',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'Adjust your users and assign them devices.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Add a phone number you want to use for your Avaya Cloud Solutions.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'Assign a phone number to your solution.',
  INVITE_A_NEW_AGENT: 'Invite a new Agent',
  I_WANT_TO_INVITE_A: 'I want to invite a',
  CONTACT_EMAIL: 'Contact Email',
  CONTACT_NAME: 'Contact Name',
  CONTACT: 'Contact',
  COMPANY_IS_INCORPORATED: 'Is Company incorporated?',
  INDIVIDUAL: 'Individual',
  INDIVIDUALS: 'Individuals',
  SEND_INVITATION_EMAIL: 'Send Invitation Email',
  SENDING_INVITATION_EMAIL: 'Sending invitation email...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: 'The invitation was sent successfully',
  ALL_FIELDS_ARE_REQUIRED: 'All fields are required',
  PARTNER_NOT_FOUND: 'Partner not found',
  SALE_AGENT_REGISTRATION: 'Sales Agent Registration',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: 'Simply fill out the form below to become a Sales Agent for',
  COMPANIES: 'Companies',
  ADD_A_PARTNER: 'Add a Partner',
  ADD_PARTNER: 'Add Partner',
  PARTNERS_PERSONAL_LINK: 'Partner\'s Personal Link',
  MASTER_SALES_AGENT: 'Master Sales Agent',
  AVAYA_J129_LABEL: 'Avaya J129 IP Phone',
  AVAYA_J129_DESCRIPTION: 'Get all your essential call-handling features in an affordable, yet highly functional SIP Phone. This phone delivers the key features needed by users in any-size businesses. The phone supports two call appearances with single-line call display. Buy a phone with solid features that trumps what’s available in the market today.',
  AVAYA_J139_LABEL: 'Avaya J139 IP Phone',
  AVAYA_J139_DESCRIPTION: 'Get all your essential call-handling features in an affordable, yet highly functional SIP Phone. This phone delivers the key features needed by users in any-size businesses. The phone supports two call appearances with single-line call display. Buy a phone with solid features that trumps what’s available in the market today.',
  AVAYA_J169_LABEL: 'Avaya J169 IP Phone',
  AVAYA_J169_DESCRIPTION: 'Get all your essential call-handling features in an affordable, yet highly functional SIP Phone. This phone delivers the key features needed by users in any-size businesses. The phone supports two call appearances with single-line call display. Buy a phone with solid features that trumps what’s available in the market today.',
  AVAYA_J179_LABEL: 'Avaya J179 IP Phone',
  AVAYA_J179_DESCRIPTION: 'Get all your essential call-handling features in an affordable, yet highly functional SIP Phone. This phone delivers the key features needed by users in any-size businesses. The phone supports two call appearances with single-line call display. Buy a phone with solid features that trumps what’s available in the market today.',
  AVAYA_K175_LABEL: 'Avaya Vantage™ K175',
  AVAYA_K175_DESCRIPTION: 'Get all your essential call-handling features in an affordable, yet highly functional SIP Phone. This phone delivers the key features needed by users in any-size businesses. The phone supports two call appearances with single-line call display. Buy a phone with solid features that trumps what’s available in the market today.',


  AVAYA_9641G_LABEL: 'Avaya 9641GS IP Deskphone',
  AVAYA_9641G_DESCRIPTION: 'The Avaya 9641GS is a multi-line premium deskphone ideally suited for people who spend considerable amounts of time on the phone and who rely on intelligent communications and productivity enhancing capabilities. The 9641GS has a 5.0 inch color graphical display, larger touch screen and high definition audio quality. Its wideband audio codec provides exceptional audio performance on all audio interfaces including handset, headset and speaker phone.',
  AVAYA_9608G_LABEL: 'Avaya 9608G IP Deskphone',
  AVAYA_9608G_DESCRIPTION: 'The 9608G deskphone is a cost-effective fully functional phone with support for integrated gigabit and monochrome display. Power over Ethernet simplifies deployment and its wideband audio codec provides exceptional audio performance. Designed for small to large enterprises, this deskphone includes access to eight lines and graphical labels that can be administered centrally.',
  AVAYA_9611G_LABEL: 'Avaya 9611G IP Deskphone',
  AVAYA_9611G_DESCRIPTION: 'The 9611G model includes integrated gigabit and a USB interface. It has a 3.5 inch graphical color display with a white backlight and graphical labels that can be administered centrally. Power over Ethernet simplifies deployment and its wideband audio codec provides exceptional audio performance.',
  AVAYA_PHONE_B179_LABEL: 'Avaya B179 SIP Conference Phone',
  AVAYA_PHONE_B179_DESCRIPTION: 'Tested by Tolly, this flexible SIP-based conference phone delivers clear, natural sound from OmniSound 2.0, Avaya’s patented wideband audio technology. The phone is packed with intelligent features for more efficient conference calls. Use the conference guide to call pre-programmed groups. Import and export contact details conveniently via the web interface. Create your own contact list with the personal user profile feature.',
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  HAVE_LARGE_NUMBERS_OF_USERS: 'Have large numbers of users?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'Review our volume discount breakdown.',
  DEVICE_FEE: 'Device Fee',
  UP_TO_DEVICE_CREDITE_PER_USER: 'Up to {$} Device Credit Per User',
  PROMOTION_REMAINING_DETAIL_INFO: 'You still have <b>{0}</b> in promotional device credit left to spend. Please note, that all remaining credit will be invalid after your purchase and will not be carried over to your account for future purchases.',
  VIEW_USER_FEATURES: 'View User Features',
  FREE_DEVICES_PER_USER_INFO: '{0} (Up to {1} device credit per user)',
  VALUE_OF_DEVICE_CREDIT: '{0} Users = {0} in total device credit',
  PROMOTION_DELAYED_BILLING_INFO: 'Promotion: Detailed receipts will be supplied and your credit card will be charged any outstanding balance when your billing cycle officially begins.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'Please select an agent to complete the order',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: 'Please provide a valid domain name (example.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Your Avaya Cloud Solution system is Ready!',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Your Avaya Cloud Solution system is now set-up!',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Avaya Cloud Solutions Phone Number',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Avaya Cloud Solutions SIP Domain Name',
  IP_OFFICE_SIP_DOMAIN_ID: 'Avaya Cloud Solutions SIP Domain ID',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Your Avaya Cloud Solution system is being configured.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'Thank you for your order. We are currently setting up your Avaya Cloud Solutions system and will contact you once configuration is complete. <br /> For any questions, please feel free to contact Avaya Cloud Solutions Support {IPO_SUPPORT_EMAIL}',
  AVAYA_CLOUD_ORDER_MESSAGE: 'Thank you for shopping with us. Please check your email. Your order details are indicated below.',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'This account failed to provision',
  ERROR_CODE: 'Error Code',
  ERROR_MESSAGE: 'Error Message',
  ADMIN_PORTAL_LINK: 'Admin Portal Link',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Avaya Cloud Solutions Default User password',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Avaya Cloud Solutions Temporary Phone number',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'Basic user extensions',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Standard user extensions',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'Power user extensions',
  IP_OFFICE_DEFAULT_USER_PIN: 'Default user pin',
  IP_OFFICE_SAME_AS_PIN: 'Same as extension (e.g.: 200)',
  IP_OFFICE_ORDERID: 'Avaya Cloud Solutions order ID',
  IP_OFFICE_HOST_NAME: 'Your Avaya Cloud Solutions host name',
  IP_OFFICE_IP_ADDRESS: 'Your Avaya Cloud Solutions IP address',
  IP_OFFICE_SUBSCRIPTIONID: 'Avaya Cloud Solutions subscription ID',
  CALCULATING: 'calculating...',
  RESET_ALL_PARTNERS: 'Clear Partner Data',
  ERROR_GETTING_AGENTS: 'Error checking the agents. Please try again',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'There is already an agent with this email in your team',
  AUTO_APPROVE_ACTIVATE_AGENT: 'Auto approve/activate agent',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'There is already a company with this email in your team',
  MASTER_SALES_AGENT_PORTAL: 'Master Sales Agent Portal',
  SALES_AGENT_PORTAL: 'Sales Agent Portal',
  E911_ADDRESS: 'E911 Address',
  OVERVIEW: 'Overview',
  ADD_COMPANY_OR_SALES_AGENT: 'Add a Company or an Agent',
  ADD_AN_AGENT: 'Add an Agent to',
  INACTIVE: 'Inactive',
  AGENTS_PERSONAL_CONNECTION_LINK: 'Agent\'s personal connection link',
  PURCHASE_DATE_AND_CUSTOMER: 'Purchase date & Customer',
  ORDER_DETAILS: 'Order Details',
  SELECT_AGENT: 'All Agents',
  FROM: 'from',
  TO: 'to',
  EXPORT_REPORT: 'Export Report',
  NO_SALES_FOUND: 'No Sales Found',
  ADD_A_COMPANY: 'Add a Company',
  AUTO_APPROVE_COMPANY: 'Auto approve company',
  AUTO_ACTIVATE_AGENT: 'Auto activate agent',
  ADD_COMPANY: 'Add Company',
  ADD_COMPANY_NAME_AGENT_ADMIN: 'Add {COMPANY_NAME} agent/admin',
  ADD_AGENT_ADMIN: 'Add Agent/Admin',
  ALL_COMPANIES: 'All Companies',
  START_DATE: 'Start Date',
  HEY: 'Hey',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: 'We are your Customer Success Team. We are here to help you get value from your Avaya Cloud solutions. Your Avaya Cloud Solutions support team also includes our Technical Support Team - <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: 'We would like to schedule a kickoff call in the next few days -- to introduce your support team and finish configuring your system. <strong>Please contact me at <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> to let us know a convenient day and time for a one hour kickoff call.<strong>',
  START_USING_YOUR_IP_OFFICE: 'Start using your Avaya Cloud Solutions system now!',
  BELOW_ARE_DETAILS: 'Below are your system’s account information, user credentials and application downloads:',
  YOUR_IP_OFFICE_INFO: 'Your system information:',
  LOGIN_INFO_TABLE: 'Your user information chart:',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'All your users can configure their information, adjust call forwarding, listen to voicemails, and more by using the information above and logging into their individual Cloud User Portals.',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'Available applications for your users:',
  DO_NOT_HESITATE_TO_EMAIL_US: 'Do not hesitate to email us at <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a> if you have any questions!',
  THANK_YOU: 'Thank you,',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web (Chrome Extension)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions Soft Console (Windows)</a>',

  EQUINOX_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-equinox/id933220295?mt=8">Avaya Equinox Mobile Application for iOS</a>',
  EQUINOX_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.android.flare&hl=en">Avaya Equinox Mobile Application for Android</a>',
  EQUINOX_FOR_MAC_LINK: '<a href="https://storage.googleapis.com/avaya-cloud-clients/downloads/equinox/Avaya-Equinox.dmg">Avaya Equinox Desktop Application for Mac</a>',
  EQUINOX_FOR_WINDOWS_LINK: '<a href="https://storage.googleapis.com/avaya-cloud-clients/downloads/equinox/Avaya-Equinox.msi">Avaya Equinox Desktop Application for Windows</a>',

  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">Install Doc</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">Install Doc</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">Install Doc</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">Install Doc</a>',

  DELETE_PURCHASE_ORDER: "Delete Purchase Order",

  USER_NAMES_COLUMN: 'Username',
  EXTENSIONS_COLUMN: 'Ext',
  TEMP_PIN_COLUMN: 'Pin',
  TEMP_PASSWORD_COLUMN: 'Password',
  USER_TYPE_COLUMN: 'User Type',
  DEVICE_MODEL_COLUMN: 'Device',
  POWER_USER: 'Power',
  STANDARD_USER: 'Standard',
  BASIC_USER: 'Basic',
  ORDERID: 'Order ID',
  ACCOUNT_NAME: 'Account Name',
  HOST_NAME: 'Host Name',
  ADMIN_PORTAL: 'Admin Portal',
  IP_ADDRESS: 'IP Address',
  PHONE_NUMBER: 'Phone Number',
  TEMPORARY_PHONE_NUMBER: 'Temporary Phone Number',
  EXCITING_TIMES_AHEAD: 'Exciting times ahead',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'The domain name {DOMAIN_NAME} is either an invalid domain name or is being used by another company.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'The domain name {1} is either an invalid domain name or is being used by another company.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: 'The system could not validate your company. Please try again',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'For any N/A information (if any) please contact Avaya Cloud support: ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'An Avaya Cloud Account failed to start provisioning',
  LEGAL: 'Legal',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Select a 1 Year Plan (or more) and receive a credit per user towards the purchase of any device. Limited time offer.',
  USER_PORTAL: 'User Portal',
  E_911: 'E911',
  DECLINE: 'Decline',
  ACCEPT: 'Accept',
  PRINT: 'Print',
  PO_NUMBER: 'Purchase Order Number',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'Please agree to all the above terms to complete your order',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'Assign a device to your users.',
  SELECT: 'Select',
  USER_DETAILS: 'User Details',
  DEVICE_DETAILS: 'Device Details',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: 'Please carefully read our Terms of Service before accepting.',
  PARTNER_ORDERS_RECORDS_HINT: '*All sales records are for reference only. Official and final sales reports will be supplied by Avaya Finance as per Master Sales Agent agreement. Select Region to view total',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: 'Please select a Sales Agent to create the quote',
  COMPANY_DETAILS: 'Company Details',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'Plus applicable taxes.',
  SELECT_PRODUCT: 'Select Product',
  CLOUD_UC_SMALL_MONTH1: 'Cloud UC Essentials Monthly',
  SMALL: 'Small',
  CLOUD_UC_SMALL_MONTH12: 'Cloud UC Essentials 1 Year Plan',
  CLOUD_UC_SMALL_3YEARS: 'Cloud UC Essentials 3 Year Plan',
  CLOUD_UC_SMALL_5YEARS: 'Cloud UC Essentials 5 Year Plan',
  MEDIUM: 'Medium',
  CLOUD_UC_MEDIUM_MONTL1: 'Cloud UC Business Monthly Plan',
  CLOUD_UC_MEDIUM_MONTH12: 'Cloud UC Business 1 Year Plan',
  CLOUD_UC_MEDIUM_3YEARS: 'Cloud UC Business 3 Year Plan',
  CLOUD_UC_MEDIUM_5YEARS: 'Cloud UC Business 5 Year Plan',
  LARGE: 'Large',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC Large Pay As You Go',
  CLOUD_UC_LARGE_MONTL12: 'Cloud UC Large Annual Plan',
  CLOUD_UC_SMALL_SHORT_INFO: '1 - 99 Employees',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100 - 999 Employees',
  CLOUD_UC_LARGE_SHORT_INFO: '1000+ Employees',
  SELECTED: 'Selected',
  BASIC_PHONE_SERVICE: 'Basic Phone Service',
  UNLIMITED_NATIONAL_WIDE: 'Unlimited Nationwide Long Distance',
  STANDARD_FEATURES: 'Standard Features',
  HOW_MANY_USERS: 'How many users do you need?',
  ADD_ON_ADDITIONAL_FEATURES: 'Additional features',
  ONETIME_FEE: 'One-Time Fee',
  RECURRING_FEE: 'Recurring Fee',
  SELECT_MAIN_NUMBER: 'Select your main phone number!',
  TOLL_FREE: 'Toll-Free Number',
  LOCAL_NUMBER: 'Local Number',
  TRANSFER_NUMBER: 'Transfer Number',
  USERS_COUNT: '{qty} users',
  USERS_COUNT_NEW: 'You have {numUser, plural, =0 {no users} =1 {one user}other {# users}}',
  DEVICES_COUNT: '{qty} device(s)',
  DEVICES_COUNT_NEW: '{numUser, plural, =0 {no devices} =1 {one device}other {# devices}}',
  UC_OFFER_TITLE: 'We have the right solution for you!',
  UC_OFFER_DESCRIPTION: 'Regardless of whether you are a small, medium-sized or large corporation, we have what you\'re looking for! What type of business are you?',

  // 'BASIC_PHONE_SERVICE': 'Basic Phone Service',

  TAX_CALC_ERROR_MSG: 'Unable to calculate tax. Please verify the billing address is correct.',
  'VIOLATION.FIELD_IS_EMPTY': '{1} is required',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} - {2} is required',
  'VIOLATION.FIELD_VALUE_INVALID': '{1} value is invalid',
  'VIOLATION.FIELD_VALUE_INVALID2': '{1} - {2} value is invalid',
  'VIOLATION.TAX_CALCULATION_FAILED': 'Failed to calculate tax',
  'VIOLATION.AGREE_ON_LEGAL_DOC': 'You must read and agree to the "{1}"',
  'VIOLATION.CART_IS_EMPTY': 'Cart is empty',
  'VIOLATION.CART_IS_TOO_BIG': 'Cart has too many items',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} is removed from cart',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': '{1} quantity is adjusted from {2} to {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': '{1} discount is adjusted from {2} to {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': 'Cannot add item with {1} currency to cart with {2} currency',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': 'Discount rule {1} is not defined',
  'SALESMODELRULE.UNKNOWN_ERROR': 'Unknown error',
  'SALESMODELRULE.INVALID_PARAMETER': 'Invalid parameter: {1}',
  ONE_TIME: 'One Time',
  ADDON_PRICING_HINT: '*Add-ons pricing are per seat and applied to all users. Adding specific add-ons to users can be done post-purchase within your admin portal.',
  ADD_TO_CART_HINT: 'Complete the above steps to add to cart',
  ADD_QUOTE: 'Add Quote',
  ITEM_UNITS: '{qty} Units',
  ADDONS_COUNT: '{qty} Add-ons',
  ADDON_COUNT: '{qty} Add-on',
  MULTIPLE_TYPES: 'Multiple Types',
  MIXED: 'Mixed',
  FREE_PRICE: 'FREE',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essentials',
  UC_ESSENTIALS_DESCRIPTION: 'The best cloud-based communications for any sized business.',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: 'Empower your company with the ultimate enterprise communications in the cloud',
  UC_BUSINESS_POWER_PACKAGE: 'Upgrade to POWER Users',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>Direct phone number:</strong> Dedicated, unique number, so anyone can call you directly instead of working through the office main number and receptionist (virtual or human).</li><li><strong>Direct video calling:</strong> Add video to your point to point phone calls.</li><li><strong>Salesforce© integration:</strong> Complete, rich, communications for end users directly from inside Salesforce.</li><li><strong>Google© integration:</strong> Browser based real time communications directly from Google Chrome and in all your Google Apps.</li><li><strong>Skype for Business© integration:</strong> Modern, streamlined and easy to use collaboration experience with Skype for Business.</li></ul>',
  SHOW_MORE: 'Show More',
  HIDE: 'Hide',
  VIEW_COMPLETE_FEATURE_LIST: ' View complete feature list',
  FILTER_BY: 'Filter By',
  UC_OFFERS: 'UC Solutions',
  PAY_MONTHLY: 'Pay Monthly',
  PAY_ANNUALLY: 'Pay Annually',
  COMING_SOON: 'Coming Soon',
  TAX_CALC_ERROR_MSG: 'Unable to calculate tax. Please verify the address is correct.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: 'Please enter the name of a country to review current long distance rates.',
  LONG_DISTANCE_RATE_NOT_FOUND: 'Long distance rate not found for this country, please contact {CUSTOMER_SUCCESS_EMAIL} for information on long distance calls to this country.',
  AREA_CODE: 'Area Code',
  INVALID_CREDIT_CARD_ZIP: 'Credit card does not match zip/postal code.',
  VIEW_LONG_DISTANCE_RATES: 'View Long Distance Rates',
  LONG_DISTANCE_SUBTITLE_TEXT: 'Our low long distance calling rates keep you in touch with everyone around the world.',
  RATES_SUBJECT_TO_CHANGE: '*Rates subject to change without notice.',
  CREDIT_CARD_DECLINED: 'Credit card was declined.',
  ENTER_COUNTRY_NAME: 'Enter country name',
  ADD_TO_CART: 'Add To Cart',
  UPDATE_CART: 'Update Cart',
  PER_USER: 'Per User',
  COMPARE_UC_OFFERS: 'Compare UC Offers',
  PROCEED_TO_CHECKOUT: 'Proceed To Checkout',
  BEFORE_APPLICABLE_TAXES: '* Before applicable taxes',
  YEAR_PLAN: '1 Year Plan',
  YEARS_PLAN: '{0} Year Plan',
  MONTHS_PLAN: '{0} Months Plan',
  ENTER_NUMBER_OF_USERS: 'Enter the number of users you\'d like for this solution',
  YEAR: 'Year',
  BILLED_MONTH: 'Billed Monthly',
  COMPANY_INCORPORATED: 'Incorporated',
  COMPANY_NOT_INCORPORATED: 'Not Incorporated',
  EXISTING_CONFIG_WARNING: 'You have an existing configuration for <br/><b>{0}</b>.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: 'Do you want to discard your current configuration?',
  DISCARD_MY_CONFIGURATION: 'Discard My Configuration',
  DISCARD: 'Discard',
  EDIT_MY_CONFIGURATION: 'Edit My Current Configuration',
  CONTINUE: 'Continue',
  SELECT_A_PLAN: 'Select a plan',
  PROMOTION_DETAIL_INFO: '*You have selected a total of <b>{0} users</b>!<br/> Equivalent to <b>{1}</b> in total device credit.',
  BILLED_MONTH_FREQUENCY: 'Billed every {0} months',
  BILLED_YEAR_FREQUENCY: 'Billed every {0} years',
  BILLED_YEAR: 'Billed Yearly',
  CONTACT_OUR_CUSTOMER_CARE: 'Contact our Customer Care team',
  NEED_HELP_INFO: 'Need help? Our Customer Care team are always ready to help you with any possible questions, problem or information.',
  REMOVE: 'Remove',
  REMOVE_ITEM_FROM_CART_WARNING: 'Do you want to remove <b>{0}</b> from cart?',
  NO_ITEM_IN_THE_CART: 'There are no items in your cart.',
  CONTINUE_SHOPPING: 'Continue Shopping',
  TOTAL_TAXES: 'Total Taxes',
  UC_SOLUTIONS: 'UC Solutions',
  UNIFIED_COMMUNICATIONS: 'Unified Communications',
  ADD_ONS: 'Add-ons',
  SYSTEM_ADDONS: 'System Add-ons',
  ADD_DEVICES: 'Add Devices',
  SELECT_UPTO_DEVICES: 'Select up-to (<b>{0}</b>) Devices for <b>{1}</b>',
  DONE: 'Done',
  SELECT_DEVICES: 'Select devices',
  EDIT_DEVICE_SELECTION: 'Edit Devices',
  ESSENTIAL_USERS: 'Essential Users',
  BUSINESS_USERS: 'Business Users',
  POWER_USERS: 'Power Users',
  N_A: 'N/A',
  QUOTES: 'Quotes',
  SAVE_QUOTE: 'Save Quote',
  CREATE_QUOTE: 'Create Quote',
  BACK_TO_QUOTES: 'Back to Quotes',
  CUSTOMER_QUOTE_TITLE1: 'Thank you for your business. Your quote details are indicated below.',
  QUOTE_DETAILS: 'Quote Details',
  CONTINUE_CONFIGURATION: 'Continue Configuration',
  CUSTOMER_INFORMATION: 'Customer Information',
  QUOTE_PREPARED_BY: 'Quote Prepared By',
  QUOTE_NOT_FOUND: 'Sorry! Quote Not Found',
  QUOTE_HAS_BEEN_EXPIRED: 'Sorry! This quote is expired',
  QUOTE_TO_CART_LAST_STEP: 'Last step to complete your configurations',
  INVALID_DOMAIN_FORMAT: 'Invalid domain format',
  NO_DEVICE_CREDIT: 'No Device Credit',
  RANGE_USERS: '{0} Users',
  SHARE_QUOTE_LINK: ' Share Quote Link:',
  EXPIRES_ON: 'Expires On',
  SUBSCRIPTION_RENEWAL: 'Thank you for shopping with us. Your payment method has been charged for this billing cycle.',
  SUBSCRIPTION_DETAILS: 'Subscription Details',
  SPACES_OFFER_TITLE: 'Imagine What <b>You Can Get Done</b> in Avaya Spaces',
  SPACES_OFFER_DESCRIPTION: 'Avaya Spaces is a cloud-based team collaboration and meeting app. It seamlessly integrates voice, video, tasks, sharing and more into one app you can access anywhere. Use it on your laptop at work, your tablet at home, your phone on-the-go, or even from your space computer in the dark depths of outer space (well, that last one could be an exaggeration).',

  PAGE_NOT_FOUND: 'File or Directory Not Found!',
  PAGE_NOT_FOUND_MESSAGE: 'It looks like the page you’re looking for might have been removed, had its name changed, or is temporarily unavailable.',
  HOME_PAGE: 'Continue Shopping',
  CHOOSE_REGION_WARNING: 'Choose another country or region to see content specific to your location and shop online.',
  OTHER_COUNTRY_REGION: 'Other country or region',
  CHOOSE_YOUR_COUNTRY_OR_REGION: 'Choose your country or region',
  CHANGE_YOUR_COUNTRY_OR_REGION: 'Change your country or region',
  CHOOSE_YOUR_LANGUAGE: 'Choose your language',
  CANADA: 'Canada',
  UNITED_STATES: 'United States',
  UNITED_KINGDOM: 'United Kingdom',
  DEUTSCHLAND: 'Deutschland',
  AVAYA_CLOUD_INC: 'Avaya Cloud Inc.',
  AVAYA_ADDRESS: 'Avaya Cloud Inc. 350 Mt Kemble Ave, Morristown, NJ 07960, USA',
  COLLABORATION: 'Collaboration',
  AVAYA_OFFICE: 'Avaya Office',
  AVAYA_OFFICE_KZ: 'Avaya Office',
  AVAYA_SPACES: 'Avaya Spaces',
  OFFER: 'Offer',
  REGION: 'Region',
  VAT_NUMBER: 'VAT Number/Tax Number/Company Registration/or similar',
  CHANGE_REGION: 'Change Region',
  PLUS_APPLICABLE_TAX: 'Plus applicable tax',
  SEND_ME_QUOTE: 'Send me quote',
  EMAIL_ME_CART_SUMMARY: 'Email me cart',
  IBAN_AUTHORIZATION: 'I authorize (We authorize) to collect payments from my (our) account \
  by direct debit to Avaya GmbH & Co. KG. At the same time I instruct my (we point our) credit \
  institution to redeem the direct debits drawn by Avaya GmbH & Co. KG on my (our) account. \
  Note: I can (We can) demand reimbursement of the amount due within eight weeks of the debit date. \
  The conditions agreed with my (our) credit institute apply',
  KAZOO_GERMANY_USER_LIMIT_ENTERPRISE_SALES: 'You have selected more than 50 users, please contact our enterprise sales team to assist you with this order.',
  IBAN_CREDITOR_ID: 'Creditor ID: DE32ZZZ00000281275 / Mandate reference: NOTIFIED SEPARATELY',
  THIS_PRODUCT_IS_NOT_OFFERED_IN_YOUR_REGION: 'Sorry, this product is not available in your region!',
  YOU_CAN_BUY_THIS_PRODUCT_FROM_THESE_REGIONS: 'However, this product is available in the following regions',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_SPACES_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'It seems that you have already purchased Avaya Spaces for this company. Please select a different company.',
  EACH_SPACES_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Each Avaya Spaces plan requires at least one user type. Please go back to the devices selection step and change your configuration.',
  SELECT_REGION: 'Select Region',
  CART_SUMMARY_TITLE1: 'Thank you for your business. Your cart summary is indicated below.',
  CART_SUMMARY_DETAILS: 'Cart Summary Details',
  USAGE_RATE_ADDONS: 'Usage Add-ons',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  COMPANY_VAT_NUMBER: 'VAT Number',
  FLATRATE_NATIONAL_FIXED_NET_MOBILE: 'Flatrate national fixed net and mobile',
  FLATRATE_NATIONAL_FIXED_NET: 'Flatrate national fixed net',
  PAY_AS_YOU_GO_MINUTES: 'Pay as you go minutes',
  COOKIE_PREFERENCE: 'Cookie Preference',
  PURCHASE_HISTORY: 'Purchase History',
  CANCEL_PLAN: 'Cancel Plan',
  ORGANIZATION_INFORMATION: 'Organization Information',
  CLICK_TO_COPY_THIS_LINK: 'Click to copy this link',
  CLOSE: 'CLOSE',
  DESIGN: 'Design',
  EDUCATION: 'Education',
  TECHNOLOGY: 'Technology',
  HEALTHCARE: 'Health Care',
  TRANSPORTATION: 'Transportation',
  INSURANCE: 'Insurance',
  GOVERNMENT: 'Government',
  FEES: 'FEES',
  TENOVIS_DIRECT: 'We will forward your order to our partner TenovisDirect. <a href="https://www.direct.de/avayashop/agb" target="_blank" rel="noopener noreferrer">Here</a> you will find more details about the process and the data.',
  GENERAL_TERMS_OF_SERVICE_AVAYA_OFFICE_SPACES: 'General Terms of Service - Avaya Office and Spaces',
  AVAYA_OFFICE_PRICE_LIST: 'Avaya Office Price List',
  EMAIL_SENT: 'Email Sent',
  AVAYA_GSMB_CO: 'Avaya GmbH & Co. KG, Theodor-Heuss-Allee 112, 60486 Frankfurt am Main, Deutschland',
  AVAYA_FAQ: 'Avaya FAQ',
  SUPPORT_OVERVIEW: 'Support',
  MANUALS: 'Manuals',
  CUSTOMER_PORTAL_GSMB: 'Customer Portal (Avaya GmbH & Co.KG)',
  DIGITAL_EXPERIENCE_CENTER: 'Digital Experience Center',
  COMPLIANCE: 'Compliance',
  IMPRESSUM: 'Impressum',
  I_AM_EXISTING_AVAYA_CUSTOMER: 'I am an existing Avaya customer',
  CUSTOMER_OR_CONTRACT_ID: 'Customer or contract ID',
  THANK_YOU_TOS: 'Thank you for accepting our Avaya Terms of Service',
  ONE_TIME_CHARGE: 'One-time Charges',
  RECURRING_CHARGES: 'Recurring Charges',
  IBAN: 'IBAN',
  PLEASE_FIND_ATTACHED_RECEIPTS: 'Please find attached receipts - also available within your <a href={PROFILE_LINK}> Avaya Cloud Store Profile </a>.',
  SALUTATIONS: 'Hi',
  FULL_ORDER_HISTORY: 'Full Order History Available within your <a href={PROFILE_LINK}> Avaya Cloud Store Profile </a>.',
  SUBSCRIPTIONS :'Subscriptions',
  VAT_19: 'VAT 19 %',
  GSMB_GENERAL_LEGAL_TOS: 'The <a href="https://www.avaya.com/de/documents/avaya-office-und-spaces-allgemeine-geschaftsbedingungen.pdf" target="_blank" rel="noopener noreferrer"> Avaya Communication Cloud Terms & Conditions </a>, which are <a href="https://www.avaya.com/de/documents/avaya-office-und-spaces-leistungsbeschreibung.pdf" target="_blank rel="noopener noreferrer">specifications</a> and the <a href="https://www.avaya.com/de/documents/avaya-office-und-spaces-preisliste.pdf" target="_blank" rel="noopener noreferrer"> price lists </a> of the selected products and the <a href="https://www.avaya.com/de/documents/avaya-office-und-spaces-datenschutz.pdf" target="_blank" rel="noopener noreferrer"> privacy policy </a> I have read and agree with this.',
  ORDER_NUMBER: 'Order No.',
  PLEASE_UPDATE_YOUR_BROWSER: 'Please update your browser',
  YOU_ARE_USING_OUTDATED_BROWSER: "You're using a web browser we don't support. Try one of these instead:",
  GOOGLE_CHROME: 'Google Chrome',
  FIREFOX: 'Mozilla Firefox',
  FIRMA: 'Company Name',
  INVOICING_EMAIL: 'Invoice Email',
  SAME_AS_ACCOUNT: 'Same as account',
  ACCOUNT_ADDRESS: 'Account Address',
  CLOUD_UC_SOLUTION_MONTHLY_PLAN: 'Cloud UC Solution Monthly Plan',
  GSMB_TOS: 'GSMB Terms of Service',
  CART_SUMMARY: 'Cart Summary',
  ESTIMATED_TAX_VALUE: '*Estimated Tax',
  RETRY_PROVISIONING: 'Retry provisioning',
  PROVISION_STATUS: 'Provision status',
  DEVICE_ADDON: 'Device addon',
  CONTRACT_LENGTH: 'Contract Length',
  BILLING_CYCLE: 'Billing Cycle',
  TRIAL_LENGTH: 'Trial Length',
  CART_INSTRUCTIONS_1: 'To order, simply log into the store and proceed directly from the shopping cart.',
  CART_INSTRUCTIONS_2: 'The prices offered are exclusive of VAT at the statutory rate (currently 19%). This will be billed separately according to the legal regulations. In addition, the general terms and conditions apply <a href="https://www.avaya.com/en/documents/avaya-office-and-spaces-general-goods.pdf" target="_blank"rel="noopener noreferrer">Avaya Communications Cloud Terms and Conditions </a> and the <a href = "https://www.avaya.com/en/documents/avaya-office-and-spaces-servicedescription.pdf" target = "_ blank" rel = "noopener noreferrer "> Terms of Reference. </a>',
  CART_INSTRUCTIONS_3: 'If you have questions about your cart, please contact our Avaya Cloud Team at any time by e-mail at ordercloud@avaya.com.',
  AVAYA_GSMB: 'Avaya GmbH & Co. KG',
  AVAYA_EMAIL_FOOTER: 'Avaya Cloud Inc., 4655 Great America Parkway, Santa Clara, CA 95054-1233 USA.',
  AVAYA_EMAIL_FOOTER_GSMB: 'Theodor-Heuss-Allee 112 60486 Frankfurt am Main <br><br> Sitz der Gesellschaft: Frankfurt/Main <br> Registergericht: Amtsgericht Frankfurt/Main - HRA 29419 <br> Persönlich haftender Gesellschafter: Avaya Verwaltungs GmbH in Frankfurt/Main <br>Registergericht: Amtsgericht Frankfurt/Main - HRB 76816 <br> Geschäftsführer: Antonio Beltran, Wolfgang Zorn',
  BEST_REGARDS: 'Best Regards,',
  QTY: 'QTY',
  ORDER_SUBJECT_GSMB: 'Your Order',
  GOOD_DAY: 'Guten Tag',
  THANK_YOU_FOR_CHOOSING_AVAYA_GSMB: 'Thank you for your order and choosing Avaya Cloud as your communications solution.',
  IN_PARALLEL_TO_THIS_GSMB_EMAIL: 'In parallel to this order confirmation, you will receive two separate emails for your Avaya Office and Avaya Spaces account. <br><br> Our Avaya Cloud team will send you further information as soon as your solution is available to the public telephone network.',
  PS_IN_THE_FOLLOWING_GSMB: "P.S .: Below, we've listed your order ({ORDER_NUMBER}) from {ORDER_DATE} that you placed from Avaya Communications Cloud Solution:",
  WE_HAVE_FORWARDED_PARTNER_GSMB: 'We have forwarded the following hardware order to our partner Tenovis Direct GmbH',
  A_PURCHASE_CONTRACT_GSMB: 'A purchase contract is only concluded with an order confirmation issued by Tenovis Direct GmbH.',
  IF_YOU_ASKED_TO_PORT_GSMB: "If you've asked to port your phone number, our Avaya Cloud team will contact you shortly and send you the porting forms. If you have any questions about your order, please contact our Avaya Cloud Team at any time by e-mailing ({SUPPORT_EMAIL}). Thank you for your confidence, as we look forward in being your professional partner for the commissioned service in the future.",
  HERE_YOU_WILL_FIND_GSMB_TOS: 'Here you will find the general terms and conditions of Tenovis Direct GmbH.',
  BUY_OFFER_OF_TENOVIS: 'Buy from our partner, Tenovis Direct GmbH',
  VOICEMAIL_BOX_ADDON: 'Voicemail Box Addon'
}


