export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'No se pueden desencriptar los datos del sistema Cuentas',
  PHONE_TYPES: 'Tipos de teléfono',
  IMAGINE_A_BETTER_WAY: 'Imagine una manera mejor',
  OF_DOING_THINGS: 'de hacer las cosas.',
  GET_STARTED: 'Comencemos',
  PURCHASE: 'Comprar',
  DOWNLOADS_AND_EXTENSIONS: 'Descargas y extensiones',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: '¡Aproveche sus productos Zang al máximo con estos complementos imprescindibles!',
  ALL: 'Todos',
  REFERRAL_AGENT: 'Agente que recomienda',
  SALES_AGENT: 'Agente de ventas',
  CART: 'Carro de compras',
  PARTNER_PROGRAMS: 'Programas de partners',
  HOME: 'Inicio',
  MANAGE_CREDIT_CARDS: 'Administrar tarjetas de crédito',
  MANAGE_PAYMENT_OPTIONS: 'Administrar Opciones de pago',
  MANAGE_BILLING_ACCOUNT: 'Administrar Cuenta de facturación',
  LIMIT: "Límite",
  MY_PROFILE: 'Mi perfil',
  MY_SETTINGS: 'Mi configuración',
  MY_PARTNER_PORTAL: 'Mi portal de partner',
  CLEAR_ZANG_OFFICE: 'Borrar Zang Office',
  CLEAR_ZANG_SPACES: 'Borrar Zang Spaces',
  FEATURE_BREAKDOWN: 'Desglose de la función',
  PLAN_BREAKDOWN: 'Desglose del plan', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'El teléfono para empresas que necesita. A un precio increíble.',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Imagine lo que puede hacer con Zang Spaces.',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'Se aplicará un descuento del 50 % al monto total después del pago.',
  HURRICANE_HARVEY_MESSAGE: 'Avaya y Zang desean ayudar a las empresas afectadas por el huracán Harvey y, posiblemente, por el huracán Irma. Cualquier empresa de los estados de TX, LA, FL, AL, GA, NC, SC, TN y MS que haya sido afectada podrá <b>recibir de inmediato 3 meses de Zang Office</b> y <b>Zang Spaces de manera GRATUITA</b>.',
  LEARN_MORE: 'Más información',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'YA ESTÁ DISPONIBLE AVAYA VANTAGE™',
  NEW: '¡NUEVO!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Experimente lo mejor de Zang Office con este teléfono que admite voz, video, chat y aplicaciones de colaboración, que es fácil de usar y que es pura pantalla.',
  LOG_IN: 'Iniciar sesión',
  SIGN_UP: 'Suscribirse',
  SIGN_OUT: 'Cerrar sesión',
  SIGN_IN: 'Iniciar sesión', //login to the system, connect
  ADMINISTRATION: 'Administración',
  PRODUCTS: 'Productos',
  ORDERS: 'Pedidos',
  PAGES: 'Páginas',
  CUSTOMERS: 'Clientes',
  USERS: 'Usuarios',
  PLANS: 'Planes',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'Registros de detalles de llamada (CDR)',
  CDR_CHECKS: 'Controles de CDR',
  PARTNERS: 'Partners',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'Parece que ya ha comprado Zang Office. No puede realizar más pedidos de Zang Office.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'Parece que ya adquirió Avaya Cloud para esta empresa. Seleccione una empresa diferente.',
  PARTNER_CONNECTIONS: 'Conexiones con partners',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'Se produjo un error al realizar su pedido. Comuníquese con el Servicio de Atención de Zang ({SUPPORT_EMAIL}) para obtener más información.',
  APPLICATION_GENERAL_FATAL_ERROR: 'Se produjo un error al enviar su solicitud. Comuníquese con el Servicio de Atención de Zang ({SUPPORT_EMAIL}) para obtener más información.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Seleccione al menos un tipo de usuario para continuar.',
  BACK: 'Volver',
  SAVE_CHANGES: 'Guardar cambios',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: '¿Desea continuar?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'Tiene {PLACEHOLDER} de crédito para gastar en la compra de cualquier dispositivo. Perderá el crédito una vez que envíe el pedido.',
  JUST_A_REMINDER: 'Un simple recordatorio',
  LAST_CHANCE: 'ÚLTIMA OPORTUNIDAD',
  IM_GOOD_PLACE_MY_ORDER: 'Así está bien. Realizar el pedido',
  BUY_MORE_DEVICES: 'Comprar más dispositivos',
  YES_PLACE_MY_ORDER: 'Sí, realizar el pedido',
  NO_THANKS: 'No, gracias.',
  YES: 'Sí',
  ABOUT_US: 'Acerca de',
  NEWS_AND_PRESS: 'Noticias y prensa',
  CARREERS: 'Oportunidades profesionales',
  CONTACT_US: 'Contacto',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Gracias por su compra. A continuación se indican los detalles del pedido.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: 'Comuníquese con <a href="mailto:{EMAIL}">{EMAIL}</a> para obtener esta información',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'Nuestros Equipos de soporte técnico y satisfacción de clientes se comunicarán con usted cuando el sistema esté listo. <br/><br/><b>Tenga en cuenta que podría demorar hasta una hora configurar su sistema.</b>',
  QUESTION_CUSTOMER_SERVICE: 'Envíenos un correo electrónico a <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a> si tiene alguna pregunta.',
  BLOG: 'Blog',
  FAQS: 'Preguntas frecuentes',
  DOCUMENTATION: 'Documentación',
  TERMS_OF_SERVICE: 'Condiciones del servicio',
  HELP: 'Ayuda',
  PRIVACY_STATEMENT: 'Declaración de privacidad',
  GENERAL_PRIVACY_STATEMENT: 'Declaración general de privacidad',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: 'Términos generales del servicio - Avaya Cloud Solutions',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. Todos los derechos reservados.',
  PROCESSING: 'Procesando',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Sea paciente. El proceso podría demorar un momento',
  OPEN_IN_A_NEW_TAB: 'Abrir en pestaña nueva',
  GOT_IT: '¡Entendido!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' Esta acción tendrá los siguientes resultados:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Eliminar la suscripción mensual de este plan',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Desactivar cualquier cuenta ubicada en sistemas de terceros',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Cambiar el estado del plan a DESACTIVADO',
  LAST_ACTION_STEPS: 'Últimos pasos',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'Los complementos se compran a través del portal de administrador de Zang Office después de crear la cuenta.',
  TYPE: 'Tipo',
  ADMIN: 'Administrador',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'Este usuario se configurará como contacto principal/de facturación de la cuenta corporativa. Se podrá cambiar en cualquier momento a través del portal de administrador de Zang Office.',
  DESCRIPTION: 'Descripción',
  SUCCESS: 'Correctamente',
  REQUEST_CANCELATION: 'Solicitar cancelación',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Esto no es bueno... Nos apena que quiera dejarnos.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Complete el siguiente formulario para comenzar el proceso de cancelación. Un integrante de nuestro Departamento de Satisfacción de Clientes revisará y realizará un seguimiento de su solicitud en el plazo de 1 a 2 días hábiles para que el proceso no presente inconvenientes.',
  YOUR_NAME: 'Su nombre',
  COMPANY: 'Empresa',
  SERVICE: 'Servicio',
  REASON_FOR_CANCELING: 'Motivo de la cancelación',
  SUBMIT: 'Enviar',
  EXIT: 'Salir',
  REQUEST_SUBMITTED: 'Solicitud enviada.',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Un integrante de nuestro Departamento de Satisfacción de Clientes revisará y realizará un seguimiento de su solicitud en el plazo de 1 a 2 días hábiles para que el proceso no presente inconvenientes.',
  DATE: 'Fecha',
  PRODUCT: 'Producto',
  USER: 'Usuario',
  STATUS: 'Estado',
  ACTIONS: 'Acciones',
  VIEW_DETAILS: 'Ver detalles',
  DISABLE: 'Deshabilitar',
  ENABLE: 'Activar',
  CANCEL: 'Cancelar',
  PLAN_DETAILS: 'Detalles del plan',
  SUMMARY: 'Resumen',
  QUANTITIES: 'Cantidades',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*El total incluye precios de funciones del plan',
  TOTAL: 'Total',
  BILLED: 'Facturado',
  PLAN_INFORMATION: 'Información sobre el plan',
  UPDATE_PLAN: 'Actualizar plan',
  ADMIN_ACTIONS: 'Acciones de administrador',
  NAME_ON_CREDIT_CARD: 'Nombre que aparece en la tarjeta de crédito',
  CREDIT_CARD_BRAND: 'Empresa de tarjeta de crédito',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: 'Número de tarjeta de crédito',
  EXPIRATION: 'Vencimiento',
  MONTH: 'Mes',
  YEAR: 'Año',
  SECURITY_CODE: 'Código de seguridad',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'El código que figura al dorso de su tarjeta de crédito',
  BACK_TO_CHECKOUT: 'Volver a la página de pago',
  NO_ORDERS_FOUND: 'No se encontraron pedidos',
  ADD: 'Agregar',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Use el formulario anterior para agregar una tarjeta de crédito nueva. No olvide completar todos los campos',
  NUMBER: 'Número',
  EXPIRES: 'Vence el',
  DELETE: 'Eliminar',
  ITEM_DETAILS: 'Detalles de los artículos',
  FEE: 'Tarifa',
  ITEMS: 'Artículos',
  SEARCH_BY_CONFIRMATION: 'Buscar por confirmación',
  CONFIRMATION: 'Confirmación',
  CHECKOUT_STATUS: 'Estado del pago',
  ORDER_STATUS_PROCESS: 'Proceso de estado del pedido',
  CREATED_ON: 'Creado el',
  ORDER_SUMMARY: 'Resumen del pedido',
  APPROVED: 'Aprobado', //example: partner application approved
  REJECTED: 'Rechazado', //example: partner application rejected
  APPROVE: 'Aprobar', //example: partner application approved
  REJECT: 'Rechazar', //example: partner application rejected
  PENDING: 'Pendiente', //example: partner application pending
  EDIT: 'Editar',
  ONE_TIME_FEE: 'Cargo por única vez',
  SUB_TOTAL: 'Subtotal',
  TAXES: 'Impuestos',
  CHANGES: 'Cambios',
  CREATE_A_QUOTE: 'Crear un presupuesto',
  EXTRA_INFORMATION: 'Información adicional',
  THANK_YOU_FOR_YOUR_ORDER: 'Gracias por su pedido',
  ORDER_CONFIRMATION: 'Confirmación del pedido',
  INVALID_ORDER: 'Pedido no válido',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'No se preocupe, también se lo hemos enviado por correo electrónico :)',
  HELLO: 'Hola',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Gracias por su compra. Le enviaremos una confirmación una vez que se hayan despachado los artículos. A continuación se indican los detalles del pedido.',
  ACCOUNT_INFORMATION: 'Información de la cuenta',
  BILLING_INFORMATION: 'Información de facturación',
  SHIPPING_INFORMATION: 'Información de envío',
  NAME: 'Nombre',
  EMAIL: 'Dirección de correo electrónico',
  SEARCH: 'Buscar',
  CLEAR: 'Borrar',
  PARTNER: 'Partner',
  NO_PARTNERS_FOUND: 'No se encontraron partners',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'Las conexiones de partner se crean cuando un cliente ingresa en la tienda desde el enlace personal de un partner.',
  CUSTOMER: 'Cliente',
  AGENT: 'Agente',
  NO_PARTNER_CONNECTIONS_FOUND: 'No se encontraron conexiones de partner',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'He leído y acepto la',
  ZANG_PRIVACY_STATEMENT: 'Declaración de privacidad de Zang',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'Condiciones del servicio del programa de agentes',
  SUBMIT_APPLICATION: 'Enviar postulación',
  SUBMITTING: 'Enviando',
  SUBMITTING_YOUR_APPLICATION: 'Enviando su postulación',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'Toda la información bancaria y de cuenta se mantiene de manera privada y segura de acuerdo con nuestros términos y condiciones.',
  BANK_NAME: 'Nombre del banco',
  ADDRESS: 'Dirección',
  COUNTRY: 'País',
  SELECT_ONE: '- Elija uno -',
  STATE_PROVINCE: 'Estado/provincia',
  CITY: 'Ciudad',
  ZIP_POSTAL_CODE: 'Código ZIP/postal',
  ACCOUNT_NUMBER: 'Número de cuenta',
  BANK_NUMBER: 'Número de banco',
  TRANSIT_NUMBER: 'Número de tránsito',
  SWIFT_CODE: 'Código Swift',
  TAX_REGISTRATION_NUMBER: 'Identificación impositiva',
  SAVE_BANK_INFORMATION: 'Guardar datos del banco',
  SAVING_BANK_INFORMATION: 'Guardando datos del banco',
  NO_CUSTOMERS_FOUND: 'No se encontraron clientes',
  YOU_ARE_A: 'Usted es ',
  A_DISCOUNT_OF: 'Se aplicará un descuento de',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'al monto total después del pago.',
  FIRST_NAME: 'Nombre',
  LAST_NAME: 'Apellido',
  COMPANY_NAME: 'Nombre de la empresa',
  LEGAL_COMPANY_NAME: 'Denominación legal de la empresa',
  PHONE_NUMBER: 'Número de teléfono',
  WEBSITE: 'Sitio web',
  OPERATIONAL_ADDRESS: 'Dirección de operaciones',
  SAME_AS_ORGANIZATION_ADDRESS: 'Igual que la dirección de la organización',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: '¿Es actualmente partner de Avaya?',
  NO: 'No',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Si la respuesta es sí, ingrese su ID de Partner de Avaya',
  MY_PARTNER_PORTAL: 'Mi portal de partner',
  THANK_YOU_FOR_APPLYING: '¡Gracias por postularse!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'Solo falta un paso para terminar. Para completar la postulación como agente de ventas, ingrese al siguiente enlace y responda todas las preguntas.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' De lo contrario, proporcione ',
  PLEASE_GIVE: 'Proporcione',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'Si actualmente es un Avaya Partner, NO use el siguiente enlace. <br />Estamos examinando su ID de Partner y nos comunicaremos con usted a la brevedad.',
  BUSINESS: 'días',
  DAYS: 'hace',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'para que la gerencia superior revise su postulación.<br /> Mientras, puede enviar todas sus preguntas a',
  COMPLETE_MY_APPLICATION: 'Completar mi postulación',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'Hemos examinado su postulación. Lamentablemente, en este momento hemos determinado que no se adecua a nuestro programa. Probablemente no se trate de nada serio, pero no podemos avanzar en nuestra sociedad sin antes resolverlo. Comprendemos que esto puede ser frustrante. Le informamos que estamos analizando los motivos y nos comunicaremos con usted apenas tengamos más información. Mientras tanto, no dude en escribir a',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'para enviar sus dudas acerca de este proceso.',
  CONGRATULATIONS: 'felicitaciones',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: '¡Ya es agente oficial de Zang!',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Para comenzar, comparta su enlace personal con todos los clientes potenciales',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'y ayúdelos a vivir una manera mejor de hacer las cosas.',
  CHANGE_STATUS: 'Cambiar estado',
  AGENT_DETAILS: 'Detalles del agente',
  BANK_INFORMATION: 'Datos bancarios',
  THIS_ORDER_WAS_PLACED_BY_A: 'Este pedido fue realizado por un',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'se aplicó al monto total',
  REFERRALS: 'Recomendaciones',
  SALES: 'Ventas',
  FOUND: 'Encontrado',
  HOW_IT_WORKS: 'Cómo funciona',
  WHAT_YOU_GET: 'Qué obtiene',
  SUPPORT: 'Soporte',
  WHICH_PROGRAM_IS_BEST_FOR_ME: '¿Qué programa es mejor para mí?',
  WHY_JOIN: '¿Por qué debo unirme?',
  QUOTE: 'Presupuesto',
  PRINT_THIS_QUOTE: 'Imprimir este presupuesto',
  CLOSE_THIS_WINDOW: 'Cerrar esta ventana',
  SEARCH_BY_PLAN: 'Buscar por plan',
  ACCESS_LEVEL: 'Nivel de acceso',
  DISPLAY_NAME: 'Mostrar nombre',
  INDUSTRY: 'Industria',
  COMPANY_INDUSTRY: 'Sector de la empresa',
  CONTACT_PHONE_NUMBER: 'Número de teléfono de contacto',
  EMAIL_ADDRESS: 'Dirección de correo electrónico',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Sí, envíenme un mensaje de correo electrónico sobre noticias, aplicaciones, promociones y eventos especiales de zang.',
  INFORMATION: 'Información',
  ORDER_HISTORY: 'Historial de pedidos',
  FILTER: 'Filtrar',
  ACCOUNT: 'Cuenta',
  AMOUNT_CHARGED: 'Monto cobrado',
  DETAILS: 'Detalles',
  NO_RECORDS_FOUND: 'No se encontraron registros',
  CALL_LOGS: 'Registros de llamadas',
  EXPORT: 'Exportar',
  CALLER_NAME: 'Nombre del autor de la llamada',
  DIALED_NUMBER: 'Número marcado',
  DURATION_SEC: 'Duración (s)',
  COST: 'Costo',
  PAYMENT_METHOD: 'Método de pago',
  PURCHASE_ORDER: 'Orden de compra',
  PURCHASE_ORDERS: 'Órdenes de compra',
  CREDIT_CARD: 'Tarjeta de crédito',
  SHIPPING_ADDRESS: 'Dirección de envío',
  SAME_AS_BILLING_ADDRESS: 'Igual que la dirección de facturación',
  SAME_AS_SHIPPING_ADDRESS: 'La misma que la dirección de envío',
  OTHER: 'Otro',
  SHIPPING_OPTIONS: 'Opciones de envío',
  FREE_SHIPPING: 'Envío GRATIS',
  ADDITIONAL_NOTES: 'Notas adicionales',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'He leído y acepto lo siguiente:',
  EMERGENCY_911_SERVICE_NOTICE: 'Aviso sobre servicio de emergencias 911',
  PLACE_MY_ORDER: 'Efectuar pedido',
  CLEAR_MY_ORDER: 'Borrar pedido',
  PLACING_YOUR_ORDER: 'Efectuando pedido',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'Sea paciente. Este proceso puede demorar hasta 1 minuto.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'Este proceso puede demorar un tiempo. Gracias por su paciencia. Para asegurarse de que no se interrumpa su pedido, no cierre esta ventana del navegador ni haga clic en los botones Atrás o Actualizar.',
  YOUR_NEW_NUMBER: 'Su número nuevo',
  NO_NUMBER_SELECTED: 'No se seleccionó ningún número',
  WELL_THAT_WAS_EASY: '¡Qué fácil resultó!',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'Solo faltan unos pasos para terminar.',
  NEXT: 'Siguiente',
  TITLE: 'Título',
  SUB_TITLE: 'Subtítulo',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Buscar por código de área... (EE. UU. y Canadá solamente)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: 'Ingrese el código de área... (solo para EE. UU.)',
  SELECT_A_PREFIX: 'Seleccionar un prefijo',
  PICK_THIS_NUMBER: 'Elegir este número',
  DEVICES: 'Dispositivos',
  BILLING: 'Facturación',
  CHANGE: 'Cambiar',
  USER_INFO: 'Datos del usuario',
  USE_MY_INFORMATION: 'Usar mis datos',
  SELECT_YOUR_DEVICES: 'Seleccionar sus dispositivos',
  MONTHLY_FEE: 'Tarifa mensual',
  ANNUAL_FEE: 'Tarifa anual',
  TWO_YEAR_FEE: 'Tarifa por 2 años',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Cada plan Zang Office requiere al menos un usuario estándar O avanzado.',
  CHECKOUT: 'Pagar',
  MINE: 'Mío',
  REMOVE_THIS_USER: 'Quitar este usuario',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Seleccionar un dispositivo para este usuario',
  ADD_ANOTHER: 'Agregar Otro',
  GET_STARTED_WITH_ZANG_OFFICE: 'Comenzar a usar Zang Office',
  BUNDLE: 'paquete',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Suscríbase por un año y reciba',
  OFF: 'DE DESCUENTO',
  EACH_USER: 'cada usuario',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'Para modificar las cantidades de usuario, debe borrar el pedido o continuar con el paso "dispositivos".',
  EVERY_TWO_YEARS: 'Cada 2 años',
  YOU_VE_SAVED: 'Ha guardado los cambios',
  INCLUDED: 'Se incluyó',
  ADDONS: 'Complementos',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Personalice cada usuario según sus preferencias.',
  UNITS_PER: 'Unidades por',
  TALK_ANYWERE_ANYTIME: '¡Hable en cualquier momento y lugar!',
  DOWNLOAD_FOR_MAC: 'Descargar para MAC',
  DOWNLOAD_FOR_WINDOWS: 'Descargar para Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: '¡Gracias por comprar Zang Office! Vea su pedido aquí.',
  CONTINUE_WITH_YOUR_PURCHASE: 'Continuar con la compra.',
  GET_STARTED_TODAY: '¡Comience hoy!',
  FEATURES: 'Funciones',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Veamos el detalle.',
  BASIC: 'Básico',
  STANDARD: 'Estándar',
  POWER: 'Avanzado',
  RATE_MIN_STARTING_FROM: 'Tarifa/min desde*:',
  RATE_MIN_STARTING_FROM_1: 'Tarifa/min, Desde',
  LONG_DISTANCE: 'Larga distancia internacional',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'Tarifas de larga distancia internacional',
  COMMON_DESTINATIONS: 'Destinos frecuentes',
  BEST_DEAL: 'mejor oferta',
  PER_ACTIVE_USER_PER_MONTH: 'Por usuario activo por mes.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'según el contrato anual',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'Se factura de acuerdo con el plan seleccionado.',
  MONTHLY: 'Mensualmente',
  ANNUALLY: 'Anualmente',
  BILLED_ANNUALY: 'Facturado anualmente',
  BILLED_EVERY_TWO_YEARS: 'Facturado cada 2 años',
  CONFIGURE_YOUR_ADDONS: 'Configurar complementos',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Seleccione una cantidad de cada uno de los complementos disponibles.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'La cantidad máxima para este complemento es',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'Este complemento está disponible solamente para',
  BILLING_AND_SHIPPING: 'Facturación y envío',
  BILLING: 'Facturación',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'Este será el nombre de su cuenta de Zang Office.',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'Este será su Nombre de cuenta de Avaya Cloud.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Si ha elegido usar su número actual o una línea gratuita como su número de Zang Office, intentaremos encontrar un número local con la extensión que se usó en este campo.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Todo sucede en Spaces',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'La herramienta de colaboración en equipo basada en la nube que siempre quiso y no podía encontrar.',
  YOUR_CURRENT_PURCHASES: 'Sus compras',
  PURCHASED_ON: 'Comprado el',
  PLAN_NUMBER: 'Número de plan',
  UPDATE: 'Actualizar',
  UPDATED: 'Actualizado',
  OR: 'o',
  MAKE_A_NEW_PURCHASE: 'Hacer otra compra',
  FEATURES_AND_ADDONS: 'Funciones y complementos',
  FREE: 'GRATIS',
  PLUS: 'PLUS',
  BUSINESS: 'AVANZADO',
  VIEW: 'Ver',
  TEAM: 'Equipo',
  LETS_SETUP_YOUR_TEAM: 'Configuremos su equipo',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Simplemente seleccione el tipo de equipo que desea crear y configure su entorno privado.',
  COMPANY_TYPE: 'Tipo de empresa',
  DOMAIN: 'Dominio',
  NO_TEAM_IS_SETUP_YET: 'Aún no se han configurado equipos',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'No configurar un equipo para mí',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Compre Zang Spaces solamente para usted.',
  CHOOSE_AN_EXISTING_COMPANY: 'Elegir una empresa existente.',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Seleccione una de las empresas que administra actualmente.',
  CREATE_A_NEW_TEAM: 'Crear un equipo nuevo',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Proporcionar nombre de equipo y dominio.',
  NO_DOMAIN_IS_CONFIGURED: 'No se han configurado dominios.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Proporcione un nombre de dominio (p. ej.: \'zang.io\')',
  CHECK: 'Comprobar',
  TEAM_DOMAIN: 'Dominio del equipo (p. ej.: \'zang.io\')',
  TEAM_NAME: 'Nombre del equipo (p. ej.: \'Zang\')',
  OK: 'Aceptar',
  ZANG_SPACES_ADMIN_CONSOLE: 'Consola de administración de Zang Spaces',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'Puede modificar los siguientes valores para actualizar su plan',
  CHARGABLE_USERS: 'Usuarios pasibles de cargos',
  TOTAL_USERS: 'Total de usuarios',
  CURRENT_PRICE: 'Precio actual',
  SAVE: 'Guardar',
  SAVE_CHANGES_AND_UPDATE_PLAN: '¿Guardar los cambios y actualizar el plan?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Seleccione al menos un tipo de usuario para continuar',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Está comprando Zang Spaces por',
  BUY_NOW: 'Comprar ahora',
  SELECT: "Seleccionar",
  UP_TO: 'Hasta',
  NO_PURCHASE_REQUIRED: 'sin obligación de compra',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'Sin compromiso de facturación ni anticipo.',
  SIGN_UP_FOR_FREE: '¡Suscríbase SIN CARGO!',
  ONE_YEAR_PLAN: 'Plan por 1 año',
  MONTHLY_PLAN: 'Plan mensual',
  TWO_YEAR_PLAN: 'Plan por 2 años',
  MONTHS: 'Meses',
  ZANG_OFFICE_ACCOUNT_NAME: 'Nombre de la cuenta de Zang Office',
  ZANG_OFFICE_PLAN_NUMBER: 'Número de plan de Zang Office',
  TEMPORARY_NUMBER: 'Número temporal',
  START_SETTING_UP_ZANG_OFFICE: '¡Comience a configurar Zang Office!',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'Si piensa transferir un número existente a su solución Zang Office, deberá enviar por correo electrónico a zosupport@zang.io el formulario de autorización LNP y una copia de su factura telefónica más reciente. Si piensa transferir un número de línea gratuita, envíe también por correo electrónico el formulario RODAA. Tenga en cuenta que finalizar la transferencia puede llevar hasta 10 días hábiles.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'Se produjo un error al comprar/activar los números de Zang Office elegidos. Haga clic en \'Comenzar a configurar Zang Office\' to activate/buy your numbers manually. In case you\'ve chosen to use your existing number, the porting process will not be affected.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'Tenga en cuenta que: Si piensa transferir un número existente a su cuenta de Zang Office, deberá completar y enviar por correo electrónico este <a href="{LNP_FORM_LINK}" target="blank">formulario de autorización LNP</a> y una copia de su factura telefónica más reciente. Si piensa transferir un número de línea gratuita, complete también este <a href="{RODAA_LINK}" target="blank">formulario RODAA</a>. Envíe toda la documentación correspondiente a <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. El proceso de transferencia de número de teléfono podría demorar hasta 10 días hábiles.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Tenga en cuenta que el proceso de transferencia de número de teléfono podría demorar hasta 10 días hábiles. Mientras tanto, agregaremos un número de teléfono temporal para que lo use dentro de la cuenta.',
  PLAN_STATUS: 'Estado del plan',
  PLAN_ID: 'ID del plan',
  SUBSCRIPTION_ID: 'ID de suscripción',
  STRIPE_PLAN_ID: 'ID del plan de Stripe',
  ACCOUNT_ID: 'ID de cuenta',
  START_SETTING_UP_ZANG_SPACES: 'Comenzar a configurar Zang Spaces',
  COMPANY_DOMAIN: 'Dominio de la empresa',
  THIS_FIELD_IS_REQUIRED: 'Este campo es obligatorio.',
  PLEASE_ANSWER_THIS_QUESTION: 'Responda esta pregunta.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Ingrese su ID de Partner de Avaya.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Lea y acepte la Declaración de privacidad para continuar.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Lea y acepte las condiciones de servicio del Programa de agentes para continuar.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'Esta ID de partner de Avaya ya está en uso.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'Este número de identificación fiscal ya está en uso.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'Esta no es una ID de partner de Avaya válida.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'La cantidad debe ser un número positivo',
  ORDER_COMPLETE: 'Pedido finalizado',
  PLEASE_TRY_AGAIN: 'Intente nuevamente',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Seleccione al menos un valor positivo',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'La actualización todavía está en curso. Intente nuevamente en otro momento.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'No puede tener más de un usuario para una licencia personal. Para subir o bajar la categoría de su plan, cambie las cantidades según corresponda.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'Usted no tiene acceso a esta cuenta.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Su plan actual no le permite disminuir la cantidad de usuarios a un número menor que el original. Si desea modificarla, escríbanos a customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'Se produjo un error al efectuar su pedido. Compruebe que todos los campos contienen valores válidos y, si el error persiste, comuníquese con Atención al Cliente de Zang para obtener más información',

  USE_EXISTING_NUMBER: 'Usar número existente',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Seleccione para usar su número existente con su plan',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Preseleccionar un número GRATUITO',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Seleccione para agregar su propio número de línea gratuita a su plan',
  FIND_A_LOCAL_NUMBER: 'Buscar un número local',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Seleccione en la lista de números locales de su área para agregarlo al plan',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: 'Seleccione para agregar un número local a su plan',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: 'Busque por código de área números de teléfono disponibles',
  SEARCH_AVAILABLE_PHONE_NUMBERS: 'Busque números de teléfono disponibles',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: 'Ingrese el número existente que desea transferir',


  ZANG_OFFICE_PHONE_APP: 'App telefónica Zang Office',
  ZANG_OFFICE_SOFTPHONE: 'Softphone Zang Office',
  ZANG_OFFICE_PHONE_APPLICATION: 'Aplicación telefónica Zang Office',
  SOFTPHONE_MARKETING_DESCRIPTION: 'El softphone Zang Office incluye todas las funciones de comunicación de esperar en un dispositivo móvil o de escritorio. Aproveche todas las funciones increíbles de Zang Office sin quedarse en rojo: el softphone de Zang Office viene incluido sin cargo con la suscripción a Zang Office.',
  E129_SIP_DESK_PHONE: 'Teléfono de escritorio SIP E129',
  STANDARD_PHONE: 'Teléfono estándar',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'El teléfono de escritorio SIP E129 reúne todas las funciones básicas de gestión de llamadas de esperar en un teléfono SIP accesible pero altamente funcional. El teléfono de escritorio Avaya E129 permite a los usuarios transferir, silenciar, reenviar y poner llamadas en espera, además de iniciar conferencias ad hoc con solo presionar un botón. El altavoz dúplex total permite mantener conversaciones manos libres, y su puerto PoE (Power over Ethernet) ofrece una práctico conexión a la red. El teléfono SIP Avaya E129 tiene las capacidades indicadas de llamada, y es tan accesible como atractivo. Incluye adaptador de alimentación de CA.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Interactúe a través de un dispositivo de escritorio pura pantalla para esta finalidad exclusivamente. Use aplicaciones de voz, chat y colaboración mediante conexiones en un solo toque. Sin interrupciones ni pausas incómodas. Y sin necesidad de controlar múltiples dispositivos para interactuar. Incorpore experiencias personalizadas exclusivas a sus flujos de trabajo y procesos comerciales. Este potente dispositivo personalizable le ofrece las ventajas de un teléfono de escritorio con la flexibilidad de una plataforma para aplicaciones.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'Teléfono para conferencias B179',
  CONFERENCE_PHONE: 'Teléfono para conferencias',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Ideal para salas de directorio y salas de conferencia grandes, de grupos de más de 10 personas, el teléfono para conferencias B179 ayuda a mejorar la productividad y colaboración de los empleados. El teléfono B179 es un aparato versátil de alto rendimiento que complementa las soluciones existentes, y puede volver a implementarse fácilmente a medida que su actividad se expande o las necesidades cambian. Incluye adaptador de alimentación de CA.',
  PLAN: 'Plan',
  REDIRECTING: 'Redirigiendo',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Compruebe que todos los campos contienen valores válidos',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Cada plan Zang Office requiere al menos un tipo de usuario. Regrese al paso de selección de dispositivos y cambie su configuración.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Parece que no ha seleccionado ningún número para su cuenta de Zang Office. Regrese al paso de selección de números para seleccionar un número.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'Ese nombre de cuenta de Zang Office ya está en uso. Pruebe con otro',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'El número de Zang Office que ha seleccionado ya ha sido comprado por otro cliente. Regrese al paso de selección de números y seleccione otro número.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Avance mes a mes sin compromiso y reciba los <span class="text-400">PRIMEROS 30 DÍAS GRATIS</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'o contrate un plan anual y reciba precios más convenientes y un',
  FREE_PHONE: 'TELÉFONO SIN CARGO',
  DISCOUNT: 'descuento',
  DISCOUNTED_PHONE: 'teléfono con descuento',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'menos sobre el valor total de sus compras de teléfonos',
  LIMITED_TIME_OFFER: 'Oferta por tiempo limitado',
  PROMOTION: 'Promoción',
  ZANG_SPACES_PROMOTION: 'Promoción de Zang Spaces',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Avanzar a la selección de números de teléfono',
  DURATION: 'Duración',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: '¡Felicitaciones! Tiene un crédito de <strong>{amount}</strong> para aplicarlo sobre el total de su pedido de dispositivos.',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'Todos los descuentos aplicables se ajustarán en el resumen del pedido final.',
  SHIPPING_TYPE: 'Tipo de envío',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'Enviaremos los detalles de rastreo una vez que los artículos hayan sido despachados de nuestro depósito',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Reciba {amount} de crédito por usuario para la compra de cualquier dispositivo. Oferta por tiempo limitado.',
  PARTNER_ORDERS: 'Pedidos de Partners',
  COMMISSION: 'Comisión',

  ADDITIONAL_DEVICES: 'Dispositivos adicionales',
  NO_USER: 'No hay usuario',
  QUANTITY: 'Cantidad',
  BUY_DEVICES: 'Comprar dispositivos',
  DEVICE: 'Dispositivo',
  PRICE: 'Precio',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'Escriba al menos {chars} caracteres para buscar un agente',
  NO_RESULTS_FOUND: 'No se encontraron resultados',
  RESULTS_COULD_NOT_BE_LOADED: 'No se pudieron cargar los resultados',
  CLEAR_SELECTION: 'Borrar selección',


  RESET_ALL_PURCHASES: 'Eliminar todas las compras',
  LISTS: 'Listas',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Ingrese su número de teléfono antes de generar una cotización.',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Ingrese su información de facturación y envío antes de generar una cotización.',
  CALCULATING_TAXES_PLEASE_WAIT: 'Calculando impuestos. Espere por favor...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Hay un problema con la tarjeta de crédito elegida.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Hay un problema con esta tarjeta de crédito. Use otra tarjeta.',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'Se produjo un error al cobrar su pedido. Elija otra tarjeta de crédito.',
  INVALID_CREDIT_CARD: 'Tarjeta de crédito no válida',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: 'El {address_type} no se corresponde con la información de la dirección de la tarjeta de crédito',
  INVALID_SECURITY_CODE: 'Código de seguridad (cvc) no válido',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Cualquier descuento y precio promocional pertinente se ha aplicado a esta factura',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'No pudimos crear su cuenta de cliente. Intente nuevamente',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'No pudimos crear su tarjeta de crédito. Intente nuevamente',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Esta tarjeta de crédito ya está en uso para una suscripción recurrente.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'No se pudo establecer esta tarjeta de crédito como predeterminada.',
  DEFAULT: 'Predeterminado',
  SET_DEFAULT: 'Establecer predeterminado',
  SALES_FORCE_QUOTE_ID: 'ID del presupuesto de Salesforce',
  SALES_FORCE_ORDER_ID: 'ID del pedido de Salesforce',
  SALES_FORCE_OPPORTUNITY_ID: 'ID de oportunidad de Salesforce',
  SALES_FORCE_CONTACT_ID: 'ID de contacto de Salesforce',
  SALES_FORCE_CONTRACT_ID: 'ID de contrato de Salesforce',
  SALES_FORCE_ACCOUNT_ID: 'ID de cuenta de Salesforce',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Simplemente \'agregar un dispositivo\' and connect it with a user.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Simplemente \'Agregue un dispositivo\' y conéctelo con un usuario.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Compre dispositivos adicionales para su cuenta de Zang Office',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: '¡Oh, oh! Hay un problema con su pedido. Actualice la página, borre el pedido y vuelva a empezar.',
  CREATE_A_NEW_COMPANY: 'Crear empresa nueva',
  ADD_A_NEW_COMPANY: 'Agregar empresa nueva',
  PARTNER_DETAILS: 'Detalles del partner',
  AGENTS: 'Agentes',
  PARTNER_PORTAL: 'Portal de partner',
  AGENT: 'Agente',
  AGENT_PORTAL: 'Portal de agente',
  NO_AGENTS_FOUND: 'No se encontraron agentes',
  NO_AGENT: 'No hay agente',
  RELATION: 'Relación',
  OWNER: 'Propietario',
  ADMIN: 'Administrador',
  MANAGER: 'Gerente',
  EMPLOYEE: 'Empleado',
  ACTIVE: 'Activo',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: 'Ingrese uno de los partners con los que está asociado',
  APPLIED_ON: 'Se aplicó el',
  JOIN_A_PARTNER: 'Unirse a un partner',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'Está a un paso de unirse a <b>{COMPANY_NAME}</b>',
  JOIN_PLACEHOLDER_NOW: 'Únase a {COMPANY_NAME} ahora',
  UPDATE_AGENT_INFO: 'Actualizar la información del agente',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Comience a usar Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'En asociación con Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'Una solución de colaboración simple, poderosa y unificada',
  IP_OFFICE_DONT_PAY_TILL: '¡No pague hasta el 15 de abril de 2018!',
  LOGIN: 'Iniciar sesión',
  DISCOVER: 'Descubra',
  SOLUTIONS: 'Soluciones',
  SERVICES: 'Servicios',
  INDUSTRIES: 'Industrias',
  CASE_STUDIES: 'Casos de estudio',
  PROGRAMS_AND_PROMOTIONS: 'Programas y promociones',
  AUTHENTIC_AVAYA: 'Avaya auténtico',
  PERSPECTIVES: 'Perspectivas',
  AVAYA_CONNECTED_BLOG: 'Blog conectado de Avaya',
  AVAYA_TV: 'TV de Avaya',
  SOLUTION_FINDER: 'Buscador de soluciones',
  INFO_FOR: 'Información para',
  DEVELOPERS: 'Desarrolladores',
  CHANNEL_PARTNERS: 'Partners de canal',
  TECHNOLOGY_PARTNERS: 'Partners de tecnología',
  CONSULTANTS: 'Consultores',
  INVESTORS: 'Inversionistas',
  MEDIA_ANALYSTS: 'Analistas de medios',
  SUPPLIERS: 'Proveedores',
  CONNECT_WITH_US: 'Comuníquese con nosotros',
  FIND_A_CHANNEL_PARTNER: 'Encuentre un Partner de canal',
  FIND_A_TECHNOLOGY_PARTNER: 'Encuentre un Partner de tecnología',
  EXECUTIVE_BRIEFING_CENTER: 'Centro de reuniones ejecutivas',
  AVAYA_LEARNING_SERVICES: 'Servicios de aprendizaje de Avaya',
  CONTACTS: 'Contactos',
  ABOUT_AVAYA: 'Acerca de Avaya',
  EVENTS: 'Eventos',
  NEWSROOM: 'Sala de prensa',
  INVESTOR_RELATIONS: 'Relaciones con inversionistas',
  CORPORATE_RESPONSIBILITY: 'Responsabilidad corporativa',
  OUR_COMPANY: 'Nuestra empresa',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'Grupo de usuarios internacionales de Avaya - IAUG',
  CAREERS: 'Profesiones',
  YOUR_PERSONAL_LINK: 'Su enlace personal',
  SITEMAP: 'Mapa del sitio',
  TERMS_OF_USE: 'Términos de uso',
  PRIVACY: 'Privacidad',
  COOKIES: 'Cookies',
  AVAYA_INVOICE: 'Recibo',
  IP_OFFICE_ACCOUNT_NAME: 'Nombre de cuenta de Avaya Cloud',
  IP_OFFICE_PLAN_NUMBER: 'Número de plan de Avaya Cloud',
  IP_OFFICE_PHONE_APPLICATION: 'Softphone de Avaya Cloud Solutions',
  IP_OFFICE_PHONE_DESCRIPTION: 'El softphone de Avaya Cloud Solutions les ofrece a los usuarios acceso simple a todos los canales de comunicación en una única interfaz. El softphone de Avaya Cloud Solutions le permite iniciar sesión en Avaya Cloud Solutions y realizar y recibir llamadas de voz y video desde su extensión del teléfono de escritorio usando su computadora personal. El softphone se incluye sin cargo con las suscripciones de usuario estándar y avanzado de Avaya Cloud Solutions.',
  PLAN_MONTH_1_MONTH_1: 'Plan mensual (sin crédito para dispositivo)',
  PLAN_YEAR_1_MONTH_1: 'Plan por 1 año | Facturación mensual',
  PLAN_YEAR_1_YEAR_1: 'Plan por 1 año, pago total',
  PLAN_YEAR_2_MONTH_1: 'Plan por 2 años | Facturación mensual',
  PLAN_YEAR_2_YEAR_1: 'Plan por 2 años | Facturación anual',
  PLAN_YEAR_2_YEAR_2: 'Plan por 2 años, pago total',
  PLAN_YEAR_3_MONTH_1: 'Plan por 3 años | Facturación mensual',
  PLAN_YEAR_3_YEAR_1: 'Plan por 3 años | Facturación anual',
  PLAN_YEAR_3_YEAR_3: 'Plan por 3 años, pago total',
  PLAN_YEAR_5_MONTH_1: 'Plan por 5 años | Facturación mensual',
  ACCORDING_TO_PLAN: 'Según el plan',
  TOTAL_USER_PLAN_FEE: 'Tarifa total del plan del usuario',
  HEALTHCARE_DENY_MESSAGE: 'Gracias por elegir Avaya Cloud como solución. Desafortunadamente, no podemos brindarle nuestro servicio porque aún no cumplimos con las disposiciones de la Ley de Responsabilidad y Transferibilidad de Seguros Médicos (HIPAA) y usted recibe atención médica. Nos comunicaremos con usted cuando recibamos nuestra certificación y esperamos que nos acepte. No dude en comunicarse con <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a> si tiene alguna pregunta.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Seleccione sus dispositivos de Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Seleccione su número de Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'Ajuste sus usuarios y asígneles dispositivos.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Agregue un número de teléfono que desee utilizar para su Avaya Cloud Solutions.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'Asigne un número de teléfono a su solución.',
  INVITE_A_NEW_AGENT: 'Invite a un nuevo agente',
  I_WANT_TO_INVITE_A: 'Deseo invitar',
  CONTACT_EMAIL: 'Correo electrónico de contacto',
  CONTACT_NAME: 'Nombre de contacto',
  COMPANY_NAME: 'Nombre de la empresa',
  CONTACT: 'Contacto',
  COMPANY_IS_INCORPORATED: 'La empresa está registrada',
  INDIVIDUAL: 'Persona',
  INDIVIDUALS: 'Personas',
  SEND_INVITATION_EMAIL: 'Enviar correo electrónico de invitación',
  SENDING_INVITATION_EMAIL: 'Enviando correo electrónico de invitación...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: 'La invitación se envió correctamente',
  ALL_FIELDS_ARE_REQUIRED: 'Todos los campos son obligatorios',
  PARTNER_NOT_FOUND: 'No se encontró al partner',
  SALE_AGENT_REGISTRATION: 'Registro de agente de ventas',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: 'Simplemente complete el siguiente formulario para convertirse en Agente de ventas de',
  VIEW: 'VER',
  COMPANIES: 'Empresas',
  ADD_A_PARTNER: 'Agregar un partner',
  ADD_PARTNER: 'Agregar partner',
  PARTNERS_PERSONAL_LINK: 'Enlace personal del partner',
  MASTER_SALES_AGENT: 'Agente maestro de ventas',
  AVAYA_J129_LABEL: 'Teléfono IP J129',
  AVAYA_J129_DESCRIPTION: 'Obtenga todas las funciones básicas de gestión de llamadas en un teléfono SIP accesible pero altamente funcional. Este teléfono ofrece las funciones clave que los usuarios necesitan en negocios de cualquier tamaño. El teléfono admite dos apariencias de llamada con pantalla de llamada de una línea. Compre un teléfono con funciones sólidas que supera a todo lo disponible actualmente en el mercado.',
  AVAYA_J169_LABEL: 'Teléfono IP J169',
  AVAYA_J169_DESCRIPTION: 'Obtenga todas las funciones básicas de gestión de llamadas en un teléfono SIP accesible pero altamente funcional. Este teléfono ofrece las funciones clave que los usuarios necesitan en negocios de cualquier tamaño. El teléfono admite dos apariencias de llamada con pantalla de llamada de una línea. Compre un teléfono con funciones sólidas que supera a todo lo disponible actualmente en el mercado.',
  AVAYA_J179_LABEL: 'Teléfono IP J179',
  AVAYA_J179_DESCRIPTION: 'Obtenga todas las funciones básicas de gestión de llamadas en un teléfono SIP accesible pero altamente funcional. Este teléfono ofrece las funciones clave que los usuarios necesitan en negocios de cualquier tamaño. El teléfono admite dos apariencias de llamada con pantalla de llamada de una línea. Compre un teléfono con funciones sólidas que supera a todo lo disponible actualmente en el mercado.',
  AVAYA_K175_LABEL: 'Avaya Vantage™ K175',
  AVAYA_K175_DESCRIPTION: 'Obtenga todas las funciones básicas de gestión de llamadas en un teléfono SIP accesible pero altamente funcional. Este teléfono ofrece las funciones clave que los usuarios necesitan en negocios de cualquier tamaño. El teléfono admite dos apariencias de llamada con pantalla de llamada de una línea. Compre un teléfono con funciones sólidas que supera a todo lo disponible actualmente en el mercado.',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: 'Teléfono de escritorio IP 9641GS',
  AVAYA_9641G_DESCRIPTION: 'El Avaya 9641GS es un teléfono de escritorio multilínea de primera calidad ideal para personas que pasan una cantidad de tiempo considerable al teléfono y que dependen de comunicaciones inteligentes y capacidades de ampliación de productividad. El 9641GS tiene una pantalla gráfica a color de 5.0 pulgadas, pantalla táctil más grande y calidad de audio de alta definición. Su códec de audio de banda ancha ofrece rendimiento de audio excepcional en todas las interfaces de audio, incluido el auricular, el auricular con micrófono y el altavoz.',
  AVAYA_9608G_LABEL: 'Teléfono de escritorio IP 9608G',
  AVAYA_9608G_DESCRIPTION: 'El teléfono de escritorio 9608G es un teléfono rentable totalmente funcional compatible con pantalla monocromática y gigabit integrado. La tecnología PoE (alimentación a través de Ethernet) simplifica la implementación y su códec de audio de banda ancha ofrece rendimiento excepcional de audio. Diseñado para empresas desde pequeñas hasta grandes, este teléfono de escritorio incluye acceso a ocho líneas y etiquetas gráficas que pueden administrarse de forma central.',
  AVAYA_9611G_LABEL: 'Teléfono de escritorio IP 9611G',
  AVAYA_9611G_DESCRIPTION: 'El modelo 9611G incluye gigabit integrado y una interfaz USB. Tiene pantalla gráfica a color de 3.5 pulgadas con luz de fondo blanca y etiquetas gráficas que pueden administrarse de forma central. La tecnología PoE (alimentación a través de Ethernet) simplifica la implementación y su códec de audio de banda ancha ofrece rendimiento excepcional de audio.',
  AVAYA_PHONE_B179_LABEL: 'Teléfono para conferencias SIP B179',
  AVAYA_PHONE_B179_DESCRIPTION: 'Probado por Tolly, este teléfono para conferencias flexible basado en SIP ofrece sonido claro y natural de OmniSound 2.0, la tecnología de audio de banda ancha patentada de Avaya. El teléfono contiene funciones inteligentes para llamadas de conferencia más eficientes. Utilice la guía para conferencias para llamar a grupos preprogramados. Importe y exporte detalles de contactos de manera conveniente a través de la interfaz web. Cree su propia lista de contactos con la función de perfil de usuario personal.',
  HAVE_LARGE_NUMBERS_OF_USERS: '¿Tiene una gran cantidad de usuarios?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'Revise nuestro detalle de descuento por volumen.',
  DEVICE_FEE: 'Tarifa de dispositivo',
  UP_TO_DEVICE_CREDITE_PER_USER: 'Hasta {$} de crédito para dispositivo por usuario',
  PROMOTION_REMAINING_DETAIL_INFO: 'Todavía le quedan <b>{0}</b> en crédito para dispositivo por gastar. Tenga en cuenta que todo el resto del crédito será inválido después de su compra y no se trasladará a su cuenta para compras futuras.',
  VIEW_USER_FEATURES: 'Ver funciones de usuario',
  FREE_DEVICES_PER_USER_INFO: '{0} (Hasta {1} de crédito para dispositivo por usuario)',
  VALUE_OF_DEVICE_CREDIT: '{0} Usuarios = {0} en crédito total para dispositivo',
  PROMOTION_DELAYED_BILLING_INFO: 'Promoción: se enviarán recibos detallados y se cobrará en su tarjeta de crédito cualquier saldo pendiente cuando comience oficialmente el ciclo de facturación.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'Seleccione un agente para completar el pedido',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: 'Ingrese un nombre de dominio válido (ejemplo.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: '¡Su sistema de Avaya Cloud Solution está listo!',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: '¡Su sistema de Avaya Cloud Solution ya está configurado!',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Número de teléfono de Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Nombre de dominio SIP de Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_ID: 'ID de dominio SIP de Avaya Cloud Solutions',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Su sistema de Avaya Cloud Solution se está configurando.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'Gracias por su pedido. Estamos configurando su sistema de Avaya Cloud Solutions y nos comunicaremos con usted una vez que se haya completado la configuración. <br /> Si tiene alguna pregunta, no dude en comunicarse con el Departamento de soporte técnico de Avaya Cloud Solutions {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'No se pudo aprovisionar esta cuenta',
  ERROR_CODE: 'Código de error',
  ERROR_MESSAGE: 'Mensaje de error',
  ADMIN_PORTAL_LINK: 'Enlace a portal de administrador',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Contraseña de usuario predeterminada de Avaya Cloud Solutions',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Número de teléfono temporal de Avaya Cloud Solutions',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'Extensiones de usuario básico',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Extensiones de usuario estándar',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'Extensiones de usuario avanzado',
  IP_OFFICE_DEFAULT_USER_PIN: 'Pin predeterminado del usuario',
  IP_OFFICE_SAME_AS_PIN: 'El mismo que la extensión: (por ejemplo: 200)',
  IP_OFFICE_ORDERID: 'ID de pedido de Avaya Cloud Solutions',
  IP_OFFICE_HOST_NAME: 'Su nombre de host de Avaya Cloud Solutions',
  IP_OFFICE_IP_ADDRESS: 'Su dirección IP de Avaya Cloud Solutions',
  IP_OFFICE_SUBSCRIPTIONID: 'ID de suscripción de Avaya Cloud Solutions',
  CALCULATING: 'calculando...',
  RESET_ALL_PARTNERS: 'Borrar datos de partner',
  ERROR_GETTING_AGENTS: 'Se produjo un error al verificar los agentes. Vuelva a intentar',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Ya existe un agente con este correo electrónico en su equipo',
  AUTO_APPROVE_ACTIVATE_AGENT: 'Aprobar/activar automáticamente al agente',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Ya existe una empresa con este correo electrónico en su equipo',
  MASTER_SALES_AGENT_PORTAL: 'Portal de agente maestro de ventas',
  SALES_AGENT_PORTAL: 'Portal de agente de ventas',
  E911_ADDRESS: 'Dirección e911',
  OVERVIEW: 'Descripción general',
  ADD_COMPANY_OR_SALES_AGENT: 'Agregar una empresa o un agente',
  ADD_AN_AGENT: 'Agregar un agente a',
  INACTIVE: 'Inactivo',
  AGENTS_PERSONAL_CONNECTION_LINK: 'Enlace de conexión personal del agente',
  PURCHASE_DATE_AND_CUSTOMER: 'Cliente y fecha de compra',
  ORDER_DETAILS: 'Detalles del pedido',
  SELECT_AGENT: 'Todos los agentes',
  FROM: 'de',
  TO: 'a',
  EXPORT_REPORT: 'Informe de exportación',
  NO_SALES_FOUND: 'No se encontraron ventas',
  ADD_A_COMPANY: 'Agregar una empresa',
  AUTO_APPROVE_COMPANY: 'Aprobar automáticamente a la empresa',
  AUTO_ACTIVATE_AGENT: 'Activar automáticamente al agente',
  ADD_COMPANY: 'Agregar empresa',
  ADD_COMPANY_NAME_AGENT_ADMIN: 'Agregar agente/administrador de {COMPANY_NAME}',
  ADD_AGENT_ADMIN: 'Agregar agente/administrador',
  ALL_COMPANIES: 'Todas las empresas',
  START_DATE: 'Fecha de inicio',
  HEY: '¡Hola!',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: 'Somos su Gerente de Satisfacción de Clientes. Estamos aquí para ayudarlo a obtener valor de sus soluciones de Avaya Cloud. Su equipo de Avaya Cloud Solutions también incluye a nuestro Equipo de soporte técnico - <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: 'Nos gustaría programar una llamada de bienvenida en los próximos días -- para presentarle a su equipo de soporte técnico y terminar de configurar su sistema. <strong>Comuníquese conmigo al <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> para informarnos sobre un día y una hora convenientes para una llamada de bienvenida de una hora.<strong>',
  START_USING_YOUR_IP_OFFICE: '¡Comience a usar su sistema de Avaya Cloud Solutions ahora!',
  BELOW_ARE_DETAILS: 'A continuación incluimos la información de su cuenta del sistema, las credenciales de usuario y las descargas de la aplicación:',
  YOUR_IP_OFFICE_INFO: 'La información de su sistema:',
  LOGIN_INFO_TABLE: 'Su gráfico de información de usuario:',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'Todos los usuarios pueden configurar su información, ajustar el reenvío de llamadas, escuchar mensajes de correo de voz, y más usando la información que antecede e iniciando sesión en sus Portales de usuario de Cloud individuales.',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'Aplicaciones disponibles para sus usuarios:',
  DO_NOT_HESITATE_TO_EMAIL_US: 'No dude en enviarnos un correo electrónico a <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a> si tiene alguna pregunta.',
  THANK_YOU: '¡Gracias!',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator para Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator para Web (Extensión de Chrome)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred para IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred para IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions Soft Console (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">Instalar Doc</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">Instalar Doc</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">Instalar Doc</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">Instalar Doc</a>',




  USER_NAMES_COLUMN: 'Nombre de usuario',
  EXTENSIONS_COLUMN: 'Ext.',
  TEMP_PIN_COLUMN: 'Pin',
  TEMP_PASSWORD_COLUMN: 'Contraseña',
  USER_TYPE_COLUMN: 'Tipo de usuario',
  DEVICE_MODEL_COLUMN: 'Dispositivo',
  POWER_USER: 'Avanzado',
  STANDARD_USER: 'Estándar',
  BASIC_USER: 'Básico',
  ORDERID: 'ID de pedido',
  ACCOUNT_NAME: 'Nombre de la cuenta',
  HOST_NAME: 'Nombre de host',
  ADMIN_PORTAL: 'Portal de administrador',
  IP_ADDRESS: 'Dirección IP',
  PHONE_NUMBER: 'Número de teléfono',
  TEMPORARY_PHONE_NUMBER: 'Número de teléfono temporal',
  EXCITING_TIMES_AHEAD: 'Prepárese para vivir momentos emocionantes',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'El nombre de dominio {DOMAIN_NAME} no es válido o lo está usando otra empresa.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'El nombre de dominio {1} no es válido o lo está usando otra empresa.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: 'El sistema no pudo validar su empresa. Vuelva a intentar',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'Para cualquier información N/C (si hubiera), comuníquese con el equipo de soporte técnico de Avaya Cloud: ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Una cuenta de Avaya Cloud no pudo comenzar el aprovisionamiento',
  LEGAL: 'Legal',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Seleccione un Plan por 1 año (o más) y reciba crédito por usuario para la compra de cualquier dispositivo. Oferta limitada.',
  USER_PORTAL: 'Portal de usuario',
  E_911: 'E911',
  DECLINE: 'Rechazar',
  ACCEPT: 'Aceptar',
  PRINT: 'Imprimir',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'Acepte todos los términos que anteceden para completar su pedido',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'Asigne un dispositivo a sus usuarios.',
  SELECT: 'Seleccionar',
  USER_DETAILS: 'Detalles del usuario',
  DEVICE_DETAILS: 'Detalles del dispositivo',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: 'Lea atentamente nuestros Términos de servicio antes de aceptar.',
  PARTNER_ORDERS_RECORDS_HINT: '*Todos los registros de venta se conservan solo para referencia. El Departamento financiero de Avaya brindará los informes de ventas oficiales y finales de conformidad con el Acuerdo del agente maestro de ventas.',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: 'Seleccione un Agente de ventas para crear la cotización',
  COMPANY_DETAILS: 'Detalles de la empresa',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'Más los impuestos correspondientes.',
  SELECT_PRODUCT: 'Seleccionar un producto',
  CLOUD_UC_SMALL_MONTH1: 'Cloud UC Essentials Mensual',
  SMALL: 'Pequeña',
  CLOUD_UC_SMALL_MONTH12: 'Plan por 1 año de Cloud UC Essentials',
  CLOUD_UC_SMALL_3YEARS: 'Plan por 3 años de Cloud UC Essentials',
  CLOUD_UC_SMALL_5YEARS: 'Plan por 5 años de Cloud UC Essentials',
  MEDIUM: 'Mediana',
  CLOUD_UC_MEDIUM_MONTL1: 'Plan mensual de Cloud UC Business',
  CLOUD_UC_MEDIUM_MONTH12: 'Plan por 1 año de Cloud UC Business',
  CLOUD_UC_MEDIUM_3YEARS: 'Plan por 3 años de Cloud UC Business',
  CLOUD_UC_MEDIUM_5YEARS: 'Plan por 5 años de Cloud UC Business',
  LARGE: 'Grande',
  CLOUD_UC_LARGE_MONTL1: 'Plan prepago de Cloud UC Large',
  CLOUD_UC_LARGE_MONTL12: 'Plan anual de Cloud UC Large',
  CLOUD_UC_SMALL_SHORT_INFO: '1 - 99 empleados',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100 - 999 empleados',
  CLOUD_UC_LARGE_SHORT_INFO: 'Más de 1000 empleados',
  SELECTED: 'Seleccionado',
  BASIC_PHONE_SERVICE: 'Servicio telefónico básico',
  UNLIMITED_NATIONAL_WIDE: 'Larga distancia nacional ilimitada',
  STANDARD_FEATURES: 'Funciones estándar',
  HOW_MANY_USERS: '¿Cuántos usuarios necesita?',
  ADD_ON_ADDITIONAL_FEATURES: 'Funciones adicionales',
  ONETIME_FEE: 'Cargo por única vez',
  RECURRING_FEE: 'Cargo recurrente',
  SELECT_MAIN_NUMBER: 'Seleccionar número principal',
  TOLL_FREE: 'Números de línea gratuita',
  LOCAL_NUMBER: 'Número local',
  TRANSFER_NUMBER: 'Transferir número',
  USERS_COUNT: '{qty} de usuarios',
  DEVICES_COUNT: '{qty} de dispositivo(s)',
  UC_OFFER_TITLE: '¡Tenemos la solución adecuada para usted!',
  UC_OFFER_DESCRIPTION: 'Independientemente de que sea una empresa pequeña, mediana o grande, ¡tenemos lo que busca! ¿Qué tipo de negocio tiene?',

  // 'BASIC_PHONE_SERVICE': 'Servicio telefónico básico',

  TAX_CALC_ERROR_MSG: 'No se pudieron calcular los impuestos. Verifique que la dirección de facturación sea la correcta.',
  'VIOLATION.FIELD_IS_EMPTY': '{1} es obligatorio',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} - {2} es obligatorio',
  'VIOLATION.FIELD_VALUE_INVALID': 'El valor {1} no es válido',
  'VIOLATION.FIELD_VALUE_INVALID2': 'El valor {1} - {2} no es válido',
  'VIOLATION.TAX_CALCULATION_FAILED': 'No se pudieron calcular los impuestos',
  'VIOLATION.AGREE_ON_LEGAL_DOC': 'Debe leer y aceptar el "{1}"',
  'VIOLATION.CART_IS_EMPTY': 'El carrito está vacío',
  'VIOLATION.CART_IS_TOO_BIG': 'El carrito tiene demasiados artículos',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} se elimina del carrito',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': 'La cantidad {1} se ajusta de {2} a {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': 'El descuento {1} se ajusta de {2} a {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': 'No se puede agregar un artículo con la moneda {1} al carrito con moneda {2}',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': 'No está definida la regla de descuento {1}',
  'SALESMODELRULE.UNKNOWN_ERROR': 'Error desconocido',
  'SALESMODELRULE.INVALID_PARAMETER': 'Parámetro no válido: {1}',
  ONE_TIME: 'Una vez',
  ADDON_PRICING_HINT: '*El precio de los complementos son por usuario y se aplica a todos los usuarios. Luego de la compra, puede agregar complementos específicos para usuarios dentro de su portal de administrador.',
  ADD_TO_CART_HINT: 'Complete los pasos anteriores para agregar al carrito',
  ITEM_UNITS: '{qty} Unidades',
  ADDONS_COUNT: '{qty} Complementos',
  ADDON_COUNT: '{qty} Complemento',
  MULTIPLE_TYPES: 'Varios tipos',
  MIXED: 'Mixto',
  FREE_PRICE: 'GRATIS',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essentials',
  UC_ESSENTIALS_DESCRIPTION: 'Las mejores comunicaciones basadas en la nube para cualquier tamaño de negocio.',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: 'Fortalezca su empresa con las mejores comunicaciones corporativas en la nube',
  UC_BUSINESS_POWER_PACKAGE: 'Suba de categoría a Usuarios AVANZADOS',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>Número de teléfono directo:</strong> Número único y exclusivo para que cualquier persona pueda llamarlo directamente en vez de pasar por el número principal de la oficina y un recepcionista (virtual o humano).</li><li><strong>Llamada de video directa:</strong> Agregue video a sus llamadas telefónicas de punto a punto.</li><li><strong>Integración con Salesforce©:</strong> Comunicaciones completas y ricas para usuarios finales directamente desde dentro de Salesforce.</li><li><strong>Integración con Google©:</strong> Comunicaciones en tiempo real basadas en navegador directamente desde Google Chrome y en todas sus aplicaciones de Google.</li><li><strong>Integración con Skype for Business©:</strong> Experiencia de colaboración moderna, simplificada y fácil de usar con Skype for Business.</li></ul>',
  SHOW_MORE: 'Mostrar más',
  HIDE: 'Ocultar',
  VIEW_COMPLETE_FEATURE_LIST: ' Ver lista completa de funciones',
  FILTER_BY: 'Filtrar por',
  UC_OFFERS: 'UC Solutions',
  PAY_MONTHLY: 'Pagar mensualmente',
  PAY_ANNUALLY: 'Pagar anualmente',
  COMING_SOON: 'Próximamente',
  TAX_CALC_ERROR_MSG: 'No se pudieron calcular los impuestos. Verifique que la dirección sea la correcta.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: 'Ingrese el nombre de un país para revisar las tarifas de larga distancia actuales.',
  LONG_DISTANCE_RATE_NOT_FOUND: 'No se encontró una tarifa de larga distancia para este país, comuníquese con {CUSTOMER_SUCCESS_EMAIL} para obtener más información sobre llamadas de larga distancia a este país.',
  AREA_CODE: 'Código de área',
  INVALID_CREDIT_CARD_ZIP: 'La tarjeta de crédito no coincide con el código postal.',
  VIEW_LONG_DISTANCE_RATES: 'Ver tarifas de larga distancia',
  LONG_DISTANCE_SUBTITLE_TEXT: 'Nuestras tarifas bajas para llamadas de larga distancia lo mantienen en contacto con personas e todo el mundo.',
  RATES_SUBJECT_TO_CHANGE: '*Tarifas sujetas a modificaciones sin previo aviso.',
  CREDIT_CARD_DECLINED: 'La tarjeta de crédito fue rechazada.',
  ENTER_COUNTRY_NAME: 'Ingresar nombre del país',
  ADD_TO_CART: 'Agregar al carrito',
  UPDATE_CART: 'Actualizar carrito',
  PER_USER: 'Por usuario',
  COMPARE_UC_OFFERS: 'Compare ofertas de UC',
  PROCEED_TO_CHECKOUT: 'Pasar a pantalla de compra',
  BEFORE_APPLICABLE_TAXES: '* Antes de los impuestos correspondientes',
  YEAR_PLAN: 'Plan por 1 año',
  YEARS_PLAN: 'Plan por {0} años',
  MONTHS_PLAN: 'Plan por {0} meses',
  ENTER_NUMBER_OF_USERS: 'Ingrese la cantidad de usuarios que le gustaría para esta solución',
  YEAR: 'Año',
  BILLED_MONTH: 'Facturación mensual',
  COMPANY_INCORPORATED: 'Incorporado',
  COMPANY_NOT_INCORPORATED: 'No incorporado',
  EXISTING_CONFIG_WARNING: 'Tiene una configuración existente para <br/><b>{0}</b>.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: '¿Desea descartar su configuración actual?',
  DISCARD_MY_CONFIGURATION: 'Descartar mi configuración',
  DISCARD: 'Descartar',
  EDIT_MY_CONFIGURATION: 'Editar mi configuración actual',
  CONTINUE: 'Continuar',
  SELECT_A_PLAN: 'Seleccionar un plan',
  PROMOTION_DETAIL_INFO: '*Seleccionó un total de <b>{0} usuarios</b>!<br/> Equivalente a <b>{1}</b> en crédito total para dispositivos.',
  BILLED_MONTH_FREQUENCY: 'Facturado cada {0} meses',
  BILLED_YEAR_FREQUENCY: 'Facturado cada {0} años',
  CONTACT_OUR_CUSTOMER_CARE: 'Comuníquese con nuestro equipo de Atención al cliente',
  NEED_HELP_INFO: '¿Necesita ayuda? Nuestro equipo de Atención al cliente está siempre listo para ayudarlo con cualquier pregunta, problema o información.',
  REMOVE: 'Eliminar',
  REMOVE_ITEM_FROM_CART_WARNING: '¿Desea eliminar <b>{0}</b> del carrito?',
  NO_ITEM_IN_THE_CART: 'No hay artículos en su carrito.',
  CONTINUE_SHOPPING: 'Continuar con la compra',
  TOTAL_TAXES: 'Impuestos totales',
  UC_SOLUTIONS: 'UC Solutions',
  UNIFIED_COMMUNICATIONS: 'Comunicaciones unificadas',
  ADD_ONS: 'Complementos',
  SYSTEM_ADDONS: 'Complementos del sistema',
  ADD_DEVICES: 'Agregar dispositivos',
  SELECT_UPTO_DEVICES: 'Seleccione hasta (<b>{0}</b>) dispositivos para <b>{1}</b>',
  DONE: 'Listo',
  SELECT_DEVICES: 'Seleccionar dispositivos',
  EDIT_DEVICE_SELECTION: 'Editar dispositivos',
  ESSENTIAL_USERS: 'Usuarios Essential',
  BUSINESS_USERS: 'Usuarios Business',
  POWER_USERS: 'Usuarios avanzados',
  N_A: 'N/C'
}
