export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'Impossible de déchiffrer les données du système de comptes',
  PHONE_TYPES: 'Types de téléphone',
  IMAGINE_A_BETTER_WAY: 'Imaginez une meilleure façon',
  OF_DOING_THINGS: 'de faire les choses.',
  GET_STARTED: 'Démarrer',
  PURCHASE: 'Acheter',
  DOWNLOADS_AND_EXTENSIONS: 'Téléchargements et extensions',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: 'Tirer le meilleur parti de vos produits Zang avec ces composants additionnels essentiels!',
  ALL: 'Tous',
  REFERRAL_AGENT: 'Parrain',
  SALES_AGENT: 'Représentant',
  CART: 'Panier',
  PARTNER_PROGRAMS: 'Programmes partenaires',
  HOME: 'Accueil',
  MANAGE_CREDIT_CARDS: 'Gérer les cartes de crédit',
  MANAGE_PAYMENT_OPTIONS: 'Gérer les options de paiement',
  MANAGE_BILLING_ACCOUNT: 'Gérer le compte de facturation',
  LIMIT: "Limite",
  MY_PROFILE: 'Mon profil',
  MY_SETTINGS: 'Mes paramètres',
  MY_PARTNER_PORTAL: 'Mon portail partenaire',
  CLEAR_ZANG_OFFICE: 'Effacer Zang Office',
  CLEAR_ZANG_SPACES: 'Effacer Zang Spaces',
  FEATURE_BREAKDOWN: 'Détails des fonctionnalités',
  PLAN_BREAKDOWN: 'Détails du forfait', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'Le téléphone d\'affaires dont vous avez besoin. À un prix que vous adorerez',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Imaginez tout ce que vous pouvez faire dans Zang Spaces',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'Une remise de 50 % sera appliquée à votre montant total après votre passage à la caisse',
  HURRICANE_HARVEY_MESSAGE: 'Avaya et Zang voudraient aider les entreprises affectées par l\'ouragan Harvey ainsi que par l\'ouragan Irma. Toutes les entreprises situées dans les états suivants : TX, LA, FL, AL, GA, NC, SC, TN et MS qui sont touchées peuvent <b>recevoir immédiatement trois (3) mois de Zang Office</b> et de <b>Zang Spaces GRATUITEMENT</b>.',
  LEARN_MORE: 'En savoir plus',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ EST MAINTENANT DISPONIBLE',
  NEW: 'NOUVEAU!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Faites l\'expérience du meilleur de Zang Office avec ce téléphone coopératif voix, vidéo et clavardage facile à utiliser et tout en verre.',
  LOG_IN: 'Se connecter',
  SIGN_UP: 'S\'inscrire',
  SIGN_OUT: 'Déconnexion',
  SIGN_IN: 'Se connecter', //login to the system, connect
  ADMINISTRATION: 'Administration',
  PRODUCTS: 'Produits',
  ORDERS: 'Commandes',
  PAGES: 'Pages',
  CUSTOMERS: 'Clients',
  USERS: 'Utilisateurs',
  PLANS: 'Forfaits',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'Cdrs',
  CDR_CHECKS: 'Vérifications Cdr',
  PARTNERS: 'Partenaires',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'Il semble que vous avez déjà acheté Zang Office. Vous ne pouvez plus passer de commandes Zang Office.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'Il semble que vous ayez déjà acheté la solution Avaya Cloud pour cette entreprise. Veuillez sélectionner une autre entreprise.',
  PARTNER_CONNECTIONS: 'Connexions partenaires',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'Une erreur est survenue lors de la passation de votre commande. Veuillez communiquer le soutien Zang ({SUPPORT_EMAIL}) pour obtenir plus d\'informations.',
  APPLICATION_GENERAL_FATAL_ERROR: 'Une erreur est survenue lors de la soumission de votre candidature. Veuillez communiquer le soutien Zang ({SUPPORT_EMAIL}) pour obtenir plus d\'informations.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Veuillez sélectionner au moins un type d\'utilisateur pour continuer.',
  BACK: 'Retour',
  SAVE_CHANGES: 'Enregistrer les modifications',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: 'Êtes-vous certain de vouloir continuer?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'Vous avez {PLACEHOLDER} en crédit à dépenser pour l\'achat de n\'importe quel appareil. Ce crédit sera perdu dès que votre commande aura été soumise.',
  JUST_A_REMINDER: 'Un petit rappel',
  LAST_CHANCE: 'DERNIÈRE CHANCE',
  IM_GOOD_PLACE_MY_ORDER: 'C\'est bon - Passer ma commande',
  BUY_MORE_DEVICES: 'Acheter plus d\'appareils',
  YES_PLACE_MY_ORDER: 'Oui, passer ma commande',
  NO_THANKS: 'Nom merci!',
  YES: 'Oui',
  ABOUT_US: 'À propos de nous',
  NEWS_AND_PRESS: 'Nouvelles et communiqués de presse',
  CARREERS: 'Carrières',
  CONTACT_US: 'Contactez-nous',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Merci d\'avoir magasiné chez nous. Les détails de votre commande sont affichés ci-dessous.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: 'Veuillez communiquer avec <a href="mailto:{EMAIL}">{EMAIL}</a> pour obtenir cette information',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'Nos équipes de réussite de la clientèle et de soutien technique communiqueront avec vous lorsque votre système sera prêt. <br/><br/><b> Veuillez prendre note que la configuration de votre système peut prendre jusqu\'à une heure. </b>',
  QUESTION_CUSTOMER_SERVICE: 'Veuillez nous envoyer un courriel à l\'adresse <a href="mailto:{SUPPORT_EMAIL}"> {SUPPORT_EMAIL} </a> si vous avez des questions.',
  BLOG: 'Blogue',
  FAQS: 'FAQ',
  DOCUMENTATION: 'Documentation',
  TERMS_OF_SERVICE: 'Modalités de service',
  HELP: 'Aide',
  PRIVACY_STATEMENT: 'Énoncé de confidentialité',
  GENERAL_PRIVACY_STATEMENT: 'Énoncé général de confidentialité',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: 'Conditions générales d\'utilisation – Solutions Avaya Cloud',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. Tous droits réservés.',
  PROCESSING: 'En traitement',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Veuillez patienter. Le processus pourrait prendre un certain temps',
  OPEN_IN_A_NEW_TAB: 'Ouvrir dans un nouvel onglet',
  GOT_IT: 'J\'ai compris!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' Cette action aura les résultats suivants :',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Supprimer l\'abonnement mensuel pour ce forfait',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Désactiver tout compte sur tout système tiers',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Modifier l\'état de ce forfait pour DÉSACTIVÉ',
  LAST_ACTION_STEPS: 'Étapes de la dernière action',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'Les modules complémentaires sont achetés par l\'entremise du portail d\'administration Zang Office dès que le compte est créé.',
  TYPE: 'Type',
  ADMIN: 'Administrateur',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'Cet utilisateur sera configuré comme utilisateur principal/contact de facturation pour le compte d\'entreprise. Il peut être modifié en tout temps par l\'entremise du portail d’administration Zang Office.',
  DESCRIPTION: 'Description',
  SUCCESS: 'Réussite',
  REQUEST_CANCELATION: 'Annulation de la demande',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Dommage! Nous sommes désolés d\'entendre que vous voulez partir.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Veuillez remplir le formulaire ci-dessous pour commencer le processus d\'annulation. Un membre de notre service Réussite de la clientèle révisera et fera le suivi de votre demande au cours des 2 prochains jours pour rendre ce processus transparent.',
  YOUR_NAME: 'Votre nom',
  COMPANY: 'Entreprise',
  SERVICE: 'Service',
  REASON_FOR_CANCELING: 'Raison pour l\'annulation',
  SUBMIT: 'Soumettre',
  EXIT: 'Quitter',
  REQUEST_SUBMITTED: 'Demande soumise!',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Un membre de notre service Réussite de la clientèle révisera et fera le suivi de votre demande au cours des 2 prochains jours pour rendre ce processus transparent.',
  DATE: 'Date',
  PRODUCT: 'Produit',
  USER: 'Utilisateur',
  STATUS: 'État',
  ACTIONS: 'Actions',
  VIEW_DETAILS: 'Afficher les détails',
  DISABLE: 'Désactiver',
  ENABLE: 'Activer',
  CANCEL: 'Annuler',
  PLAN_DETAILS: 'Détails du forfait',
  SUMMARY: 'Résumé',
  QUANTITIES: 'Quantités',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*Le total comprend les prix des fonctions du forfait',
  TOTAL: 'Total',
  BILLED: 'Facturé',
  PLAN_INFORMATION: 'Renseignements sur le forfait',
  UPDATE_PLAN: 'Mise à jour du forfait',
  ADMIN_ACTIONS: 'Actions administrateur',
  NAME_ON_CREDIT_CARD: 'Nom sur la carte de crédit',
  CREDIT_CARD_BRAND: 'Marque de la carte de crédit',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: 'Numéro de carte de crédit',
  EXPIRATION: 'Expiration',
  MONTH: 'Mois',
  YEAR: 'Année',
  SECURITY_CODE: 'Code de sécurité',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'Le code apparaissant au dos de votre carte de crédit',
  BACK_TO_CHECKOUT: 'Revenir à la caisse',
  NO_ORDERS_FOUND: 'Aucune commande trouvée',
  ADD: 'Ajouter',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Utiliser le formulaire ci-dessus pour ajouter une nouvelle carte de crédit. Veuillez vous assurer de remplir tous les champs',
  NUMBER: 'Numéro',
  EXPIRES: 'Expire le',
  DELETE: 'Supprimer',
  ITEM_DETAILS: 'Détails de l\'élément',
  FEE: 'Frais',
  ITEMS: 'Éléments',
  SEARCH_BY_CONFIRMATION: 'Recherche par confirmation',
  CONFIRMATION: 'Confirmation',
  CHECKOUT_STATUS: 'État du processus de paiement',
  ORDER_STATUS_PROCESS: 'Processus de l\'état de commande',
  CREATED_ON: 'Créé le',
  ORDER_SUMMARY: 'Sommaire de la commande',
  APPROVED: 'Autorisé', //example: partner application approved
  REJECTED: 'Rejeté', //example: partner application rejected
  APPROVE: 'Approuver', //example: partner application approved
  REJECT: 'Rejeter', //example: partner application rejected
  PENDING: 'En attente', //example: partner application pending
  EDIT: 'Modifier',
  ONE_TIME_FEE: 'Frais uniques',
  SUB_TOTAL: 'Sous-total',
  TAXES: 'Taxes',
  CHANGES: 'Modifications',
  CREATE_A_QUOTE: 'Créer une soumission',
  EXTRA_INFORMATION: 'Autres informations',
  THANK_YOU_FOR_YOUR_ORDER: 'Merci d\'avoir passé une commande',
  ORDER_CONFIRMATION: 'Confirmation de commande',
  INVALID_ORDER: 'Commande non valide',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'Ne vous en faites pas! Nous vous l\'avons aussi envoyé par courriel :)',
  HELLO: 'Bonjour',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Merci d\'avoir magasiné chez nous. Nous enverrons une confirmation dès que vos éléments seront expédiés. Les détails de votre commande sont affichés ci-dessous.',
  ACCOUNT_INFORMATION: 'Informations sur le compte',
  BILLING_INFORMATION: 'Informations de facturation',
  SHIPPING_INFORMATION: 'Informations d\'expédition',
  NAME: 'Nom',
  EMAIL: 'Courriel',
  SEARCH: 'Rechercher',
  CLEAR: 'Effacer',
  PARTNER: 'Partenaire',
  NO_PARTNERS_FOUND: 'Aucun partenaire trouvé',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'Une connexion partenaire est créée lorsqu\'un client se retrouve dans le magasin depuis un lien personnel d\'un partenaire.',
  CUSTOMER: 'Client',
  AGENT: 'Agent',
  NO_PARTNER_CONNECTIONS_FOUND: 'Aucune connexion partenaire trouvée',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'J’ai lu et j\'accepte l\'',
  ZANG_PRIVACY_STATEMENT: 'Énoncé de confidentialité',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'Modalités de service du programme d\'agent',
  SUBMIT_APPLICATION: 'Soumettre la candidature',
  SUBMITTING: 'Soumettre',
  SUBMITTING_YOUR_APPLICATION: 'Soumettre votre candidature',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'Toutes les informations bancaires et de compte sont gardées confidentielles et sécurisées en vertu de nos modalités.',
  BANK_NAME: 'Nom de la banque',
  ADDRESS: 'Adresse',
  COUNTRY: 'Pays',
  SELECT_ONE: '- Sélectionnez-en un -',
  STATE_PROVINCE: 'État/Province',
  CITY: 'Ville',
  ZIP_POSTAL_CODE: 'Code postal/ZIP',
  ACCOUNT_NUMBER: 'Numéro de compte',
  BANK_NUMBER: 'Numéro de banque',
  TRANSIT_NUMBER: 'Numéro transitaire',
  SWIFT_CODE: 'Code Swift',
  TAX_REGISTRATION_NUMBER: 'Numéro d\'identification fiscale',
  SAVE_BANK_INFORMATION: 'Enregistrer les informations bancaires',
  SAVING_BANK_INFORMATION: 'Enregistrement des informations bancaires',
  NO_CUSTOMERS_FOUND: 'Aucun client trouvé',
  YOU_ARE_A: 'Vous êtes un ',
  A_DISCOUNT_OF: 'Une remise de',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'sera appliquée à votre montant total après votre passage à la caisse.',
  FIRST_NAME: 'Prénom',
  LAST_NAME: 'Nom de famille',
  COMPANY_NAME: 'Nom de l\'entreprise',
  LEGAL_COMPANY_NAME: 'Nom légal de l\'entreprise',
  PHONE_NUMBER: 'Numéro de téléphone',
  WEBSITE: 'Site Web',
  OPERATIONAL_ADDRESS: 'Adresse d\'unité d\'exploitation',
  SAME_AS_ORGANIZATION_ADDRESS: 'Même que l\'adresse organisationnelle',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: 'Êtes-vous un partenaire Avaya existant?',
  NO: 'Non',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Si oui, veuillez entrer votre identifiant de partenaire Avaya',
  MY_PARTNER_PORTAL: 'Mon portail partenaire',
  THANK_YOU_FOR_APPLYING: 'merci d\'avoir postulé!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'Une dernière étape et c\'est tout! Pour terminer votre candidature de représentant, veuillez cliquer sur le lien ci-dessous et répondez à toutes les questions.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' Sinon, veuillez donner ',
  PLEASE_GIVE: 'Veuillez donner',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'Si vous êtes un partenaire Avaya existant, veuillez NE PAS suivre le lien ci-dessous. <br />Nous révisons votre ID de partenaire et nous communiquerons avec vous bientôt.',
  BUSINESS: 'affaires',
  DAYS: 'jours',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'pour que la haute direction révise votre candidature.<br /> Entre temps, toutes vos questions peuvent être envoyées à',
  COMPLETE_MY_APPLICATION: 'Terminer ma candidature',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'Nous avons vérifié votre candidature. Malheureusement, nous avons déterminé que vous ne répondez pas aux exigences de notre programme pour le moment. Ce n\'est probablement pas grand-chose, mais nous ne pouvons aller de l\'avant avec notre partenariat tant que nous n\'aurons pas résolu le problème. Nous comprenons que cela peut être frustrant. Veuillez noter que nous nous penchons sur le raisonnement et nous communiquerons avec vous dès que nous aurons de plus amples renseignements. Entre temps, n\'hésitez pas à communiquer avec',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'pour toute question concernant ce processus.',
  CONGRATULATIONS: 'félicitations',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: 'Vous êtes maintenant un agent Zang officiel!',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Commencez en partageant votre lien personnel avec tous vos clients potentiels',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'et aidez-les à faire l\'expérience d\'une meilleure façon de faire les choses.',
  CHANGE_STATUS: 'Modifier l\'état',
  AGENT_DETAILS: 'Détails de l\'agent',
  BANK_INFORMATION: 'Informations bancaires',
  THIS_ORDER_WAS_PLACED_BY_A: 'Cette commande a été passée par un',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'a été appliqué au montant total',
  REFERRALS: 'Références',
  SALES: 'Ventes',
  FOUND: 'Trouvé',
  HOW_IT_WORKS: 'Comment ça marche',
  WHAT_YOU_GET: 'Ce que vous obtenez',
  SUPPORT: 'Soutien',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'Quel est le meilleur programme pour moi?',
  WHY_JOIN: 'Pourquoi adhérer?',
  QUOTE: 'Soumission',
  PRINT_THIS_QUOTE: 'Imprimer cette soumission',
  CLOSE_THIS_WINDOW: 'Fermer cette fenêtre',
  SEARCH_BY_PLAN: 'Rechercher par forfait',
  ACCESS_LEVEL: 'Niveau d\'accès',
  DISPLAY_NAME: 'Afficher le nom',
  INDUSTRY: 'Industrie',
  COMPANY_INDUSTRY: 'Secteur d\'activité de l\'entreprise',
  CONTACT_PHONE_NUMBER: 'Numéro de téléphone du contact',
  EMAIL_ADDRESS: 'Adresse de courriel',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Oui, envoyez-moi un courriel concernant les nouvelles, les applications, les aubaines et les événements spéciaux de Zang!',
  INFORMATION: 'Informations',
  ORDER_HISTORY: 'Historique des commandes',
  FILTER: 'Filtre',
  ACCOUNT: 'Compte',
  AMOUNT_CHARGED: 'Montant facturé',
  DETAILS: 'Détails',
  NO_RECORDS_FOUND: 'Aucun enregistrement trouvé',
  CALL_LOGS: 'Journaux des appels',
  EXPORT: 'Exporter',
  CALLER_NAME: 'Nom de l\'appelant',
  DIALED_NUMBER: 'Numéro composé',
  DURATION_SEC: 'Durée (s)',
  COST: 'Coût',
  PAYMENT_METHOD: 'Mode de paiement',
  PURCHASE_ORDER: 'Bon de commande',
  PURCHASE_ORDERS: 'Bons de commande',
  CREDIT_CARD: 'Carte de crédit',
  SHIPPING_ADDRESS: 'Adresse d\'expédition',
  SAME_AS_BILLING_ADDRESS: 'Identique à l\'adresse de facturation',
  SAME_AS_SHIPPING_ADDRESS: 'Identique à l\'adresse d\'expédition',
  OTHER: 'Autre',
  SHIPPING_OPTIONS: 'Options d\'expédition',
  FREE_SHIPPING: 'Expédition GRATUITE',
  ADDITIONAL_NOTES: 'Notes supplémentaires',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'J’ai lu et j\'accepte le :',
  EMERGENCY_911_SERVICE_NOTICE: 'Préavis du service d\'urgences 911',
  PLACE_MY_ORDER: 'Soumettre ma commande',
  CLEAR_MY_ORDER: 'Effacer ma commande',
  PLACING_YOUR_ORDER: 'Soumission de votre commande',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'Veuillez patienter. Ce processus peut prendre jusqu\'à 1 minute.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'Ce processus peut prendre un certain temps. Merci de votre patience. Pour vous assurer que votre commande n\'est pas interrompue, évitez de fermer la fenêtre du navigateur ou de cliquer sur les boutons Précédent ou Actualiser.',
  YOUR_NEW_NUMBER: 'Votre nouveau numéro',
  NO_NUMBER_SELECTED: 'Aucun numéro sélectionné',
  WELL_THAT_WAS_EASY: 'C\'était facile!',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'Quelques étapes encore et vous avez terminé :)',
  NEXT: 'Suivant',
  TITLE: 'Titre',
  SUB_TITLE: 'Sous-titre',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Rechercher par indicatif régional... (É.-U. et Canada seulement)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: 'Entrez l\'indicatif régional... (uniquement pour les États-Unis)',
  SELECT_A_PREFIX: 'Sélectionner un préfixe',
  PICK_THIS_NUMBER: 'Choisir ce numéro',
  DEVICES: 'Appareils',
  BILLING: 'Facturation',
  CHANGE: 'Modifier',
  USER_INFO: 'Informations utilisateur',
  USE_MY_INFORMATION: 'Utiliser mes informations',
  SELECT_YOUR_DEVICES: 'Sélectionnez vos appareils',
  MONTHLY_FEE: 'Frais mensuels',
  ANNUAL_FEE: 'Frais annuels',
  TWO_YEAR_FEE: 'Frais bisannuels',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Chaque forfait Zang Office exige au moins un utilisateur standard ou un grand utilisateur.',
  CHECKOUT: 'Passer à la caisse',
  MINE: 'Mien',
  REMOVE_THIS_USER: 'Retirer cet utilisateur',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Sélectionner un appareil pour cet utilisateur',
  ADD_ANOTHER: 'Ajouter un autre',
  GET_STARTED_WITH_ZANG_OFFICE: 'Commencez avec Zang Office',
  BUNDLE: 'offre groupée',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Inscrivez-vous pour un an et recevez',
  OFF: 'DÉSACTIVÉ',
  EACH_USER: 'chaque utilisateur',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'Pour ajuster votre quantité d\'utilisateurs, vous devez soit effacer votre commande ou continuer jusqu\'à l\'étape « appareils ».',
  EVERY_TWO_YEARS: 'Chaque 2 ans',
  YOU_VE_SAVED: 'Vous avez enregistré',
  INCLUDED: 'Inclut',
  ADDONS: 'Modules complémentaires',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Personnalisez chaque utilisateur à leur goût!',
  UNITS_PER: 'Unités par',
  TALK_ANYWERE_ANYTIME: 'Parlez partout, en tout temps!',
  DOWNLOAD_FOR_MAC: 'Télécharger pour Mac',
  DOWNLOAD_FOR_WINDOWS: 'Télécharger pour Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Merci d\'avoir acheté Zang Office! Affichez votre commande ici!',
  CONTINUE_WITH_YOUR_PURCHASE: 'Continuez avec votre commande!',
  GET_STARTED_TODAY: 'Commencez dès aujourd\'hui!',
  FEATURES: 'Fonctions',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Analysons la situation.',
  BASIC: 'De base',
  STANDARD: 'Standard',
  POWER: 'Grand',
  RATE_MIN_STARTING_FROM: 'Taux/min, à partir de* :',
  RATE_MIN_STARTING_FROM_1: 'Taux/min, à partir de',
  LONG_DISTANCE: 'Interurbains internationaux',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'Taux interurbains internationaux',
  COMMON_DESTINATIONS: 'Destinations courantes',
  BEST_DEAL: 'meilleure affaire',
  PER_ACTIVE_USER_PER_MONTH: 'Par utilisateur actif, par mois.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'selon le contrat annuel',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'Facturé en fonction du forfait sélectionné.',
  MONTHLY: 'Mensuellement',
  ANNUALLY: 'Annuellement',
  BILLED_ANNUALY: 'Facturé annuellement',
  BILLED_EVERY_TWO_YEARS: 'Facturé aux 2 ans',
  CONFIGURE_YOUR_ADDONS: 'Configurez vos modules complémentaires',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Sélectionnez une quantité pour chaque module complémentaire disponible.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'La quantité maximale pour ce module complémentaire est',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'Ce module complémentaire n\'est offert que pour',
  BILLING_AND_SHIPPING: 'Facturation et expédition',
  BILLING: 'Facturation',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'Voici votre nom de compte Zang Office.',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'Voici votre nom de compte Avaya Cloud.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Si vous avez choisi d\'utiliser votre numéro existant ou un numéro sans frais comme numéro de téléphone Zang Office, nous essaierons de trouver un numéro local avec le poste utilisé dans ce champ.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Tout peut survenir dans Spaces',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'Un outil infonuagique de collaboration d’équipe dont vous avez toujours rêvé, mais ne pouviez trouver nulle part.',
  YOUR_CURRENT_PURCHASES: 'Vos achats courants',
  PURCHASED_ON: 'Acheté le',
  PLAN_NUMBER: 'Numéro de forfait',
  UPDATE: 'Mettre à jour',
  UPDATED: 'Mis à jour',
  OR: 'ou',
  MAKE_A_NEW_PURCHASE: 'Effectuer un nouvel achat',
  FEATURES_AND_ADDONS: 'Fonctions et modules complémentaires',
  FREE: 'GRATUIT',
  PLUS: 'PLUS',
  BUSINESS: 'GRAND',
  VIEW: 'Afficher',
  TEAM: 'Équipe',
  LETS_SETUP_YOUR_TEAM: 'Configurons votre équipe',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Sélectionnez simplement le type d\'équipe que vous souhaitez créer et configurez votre environnement privé.',
  COMPANY_TYPE: 'Type d\'entreprise',
  DOMAIN: 'Domaine',
  NO_TEAM_IS_SETUP_YET: 'Aucune équipe n\'est configurée',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'Ne pas configurer une équipe pour moi',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Acheter Zang Spaces seulement pour vous.',
  CHOOSE_AN_EXISTING_COMPANY: 'Choisir une entreprise existante',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Sélectionner l\'une des entreprises que vous administrez en ce moment.',
  CREATE_A_NEW_TEAM: 'Créer une nouvelle équipe',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Fournir une équipe et un nom de domaine.',
  NO_DOMAIN_IS_CONFIGURED: 'Aucun domaine configuré.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Veuillez fournir un nom de domaine (p. ex : \'zang.io\')',
  CHECK: 'Vérifier',
  TEAM_DOMAIN: 'Domaine d\'équipe (p. ex. : \'zang.io\')',
  TEAM_NAME: 'Nom d\'équipe (p. ex. : \'Zang\')',
  OK: 'OK',
  ZANG_SPACES_ADMIN_CONSOLE: 'Console administrateur Zang Spaces',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'Vous pouvez modifier les valeurs ci-dessous pour mettre à jour votre forfait',
  CHARGABLE_USERS: 'Utilisateurs payants',
  TOTAL_USERS: 'Nombre total d\'utilisateurs',
  CURRENT_PRICE: 'Prix courant',
  SAVE: 'Enregistrer',
  SAVE_CHANGES_AND_UPDATE_PLAN: 'Enregistrer les modifications et mettre à jour le forfait?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Veuillez sélectionner au moins un type d\'utilisateur pour continuer',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Vous avez acheté Zang Spaces pour',
  BUY_NOW: 'Achetez maintenant',
  SELECT: "Sélectionner",
  UP_TO: 'Jusqu\'à',
  NO_PURCHASE_REQUIRED: 'aucun achat requis',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'Aucune facturation, aucun engagement préalable.',
  SIGN_UP_FOR_FREE: 'Inscrivez-vous GRATUITEMENT!',
  ONE_YEAR_PLAN: 'Forfait de 1 an',
  MONTHLY_PLAN: 'Forfait mensuel',
  TWO_YEAR_PLAN: 'Forfait de 2 ans',
  MONTHS: 'Mois',
  ZANG_OFFICE_ACCOUNT_NAME: 'Nom de compte Zang Office',
  ZANG_OFFICE_PLAN_NUMBER: 'Numéro de forfait Zang Office',
  TEMPORARY_NUMBER: 'Numéro temporaire',
  START_SETTING_UP_ZANG_OFFICE: 'Commencez à configurer Zang Office!',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'Si vous transférez un numéro existant vers votre solution Zang Office, vous devez envoyer un courriel à l\'adresse zosupport@zang.io contenant le formulaire d\'autorisation LNP et une copie de votre plus récente facture téléphonique. Si vous transférez un numéro sans frais, veuillez aussi envoyer le formulaire RODAA par courriel. Veuillez noter qu\'il pourrait s\'écouler jusqu\'à 10 jours ouvrables pour terminer le ou les transferts.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'Une erreur est survenue lors de l\'achat ou de l\'activation des numéros Zang Office choisis. Cliquez sur \'Commencez à configurer Zang Office\' to activate/buy your numbers manually. In case you\'ve chosen to use your existing number, the porting process will not be affected.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'Veuillez noter : Si vous transférez un numéro existant vers votre compte Zang Office, vous devez remplir et envoyer par courriel ce <a href="{LNP_FORM_LINK}" target="blank">formulaire d\'autorisation LNP</a> accompagné d\'une copie de votre plus récente facture téléphonique. Si vous transférez un numéro sans frais, veuillez aussi remplir ce <a href="{RODAA_LINK}" target="blank">formulaire RODAA</a>. Veuillez envoyer tous les documents applicables à <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. Le processus de transfert du numéro de téléphone pourrait prendre jusqu\'à 10 jours ouvrables.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Veuillez noter que le processus de transfert du numéro de téléphone pourrait prendre jusqu\'à 10 jours ouvrables. Pendant ce temps, nous brancherons un numéro de téléphone temporaire pour que vous puissiez l\'utiliser dans votre compte.',
  PLAN_STATUS: 'État du forfait',
  PLAN_ID: 'ID de forfait',
  SUBSCRIPTION_ID: 'ID d’abonnement',
  STRIPE_PLAN_ID: 'ID de forfait de bande',
  ACCOUNT_ID: 'ID de compte',
  START_SETTING_UP_ZANG_SPACES: 'Commencer à configurer Zang Spaces',
  COMPANY_DOMAIN: 'Domaine de l\'entreprise',
  THIS_FIELD_IS_REQUIRED: 'Ce champ est obligatoire.',
  PLEASE_ANSWER_THIS_QUESTION: 'Veuillez répondre à la question.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Veuillez entrer votre identifiant de partenaire Avaya.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Veuillez lire et accepter l\'Énoncé de confidentialité pour continuer.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Veuillez lire et accepter les Modalités du programme d\'agent pour continuer.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'Cet identifiant de partenaire Avaya est déjà utilisé.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'Ce numéro d\'identification fiscale est déjà utilisé.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'Ce n\'est pas un identifiant de partenaire Avaya valide.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'La quantité doit être un nombre positif',
  ORDER_COMPLETE: 'Commande terminée!',
  PLEASE_TRY_AGAIN: 'Veuillez réessayer',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Veuillez sélectionner au moins une valeur positive',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'La mise à jour est toujours en cours. Veuillez réessayer plus tard.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'Vous ne pouvez pas avoir plus d\'un utilisateur pour une licence personnelle. Pour mettre à niveau ou rétrograder votre forfait, modifiez les quantités en conséquence.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'Vous n\'avez pas accès à ce compte.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Votre forfait actuel ne vous permet pas de diminuer les utilisateurs à un nombre inférieur à celui d\'origine. Si vous voulez ajuster quelque chose, veuillez communiquer avec nous à l\'adresse customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'Une erreur est survenue lors de la passation de votre commande. Veuillez vous assurer que tous les champs comportent des valeurs valides et si l\'erreur persiste, communiquez avec le soutien de Zang pour obtenir des informations',

  USE_EXISTING_NUMBER: 'Utiliser un numéro existant',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Sélectionnez pour utiliser votre numéro existant avec votre forfait',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Présélectionnez un numéro SANS FRAIS',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Sélectionnez pour ajouter votre propre numéro sans frais à votre forfait',
  FIND_A_LOCAL_NUMBER: 'Trouver un numéro local',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Sélectionnez à partir d\'une liste de numéros locaux dans votre région pour ajouter à votre forfait',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: 'Sélectionnez cette option pour ajouter un numéro local à votre forfait',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: 'Recherchez par indicatif régional pour obtenir les numéros de téléphone disponibles',
  SEARCH_AVAILABLE_PHONE_NUMBERS: 'Recherchez les numéros de téléphone disponibles',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: 'Entrez le numéro existant que vous envisagez de transférer',


  ZANG_OFFICE_PHONE_APP: 'Appli téléphonique Zang Office',
  ZANG_OFFICE_SOFTPHONE: 'Téléphone logiciel Zang Office',
  ZANG_OFFICE_PHONE_APPLICATION: 'Application téléphonique Zang Office',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Le téléphone logiciel Zang Office comprend toutes les fonctions de communications que vous souhaitez voir sur votre ordinateur de bureau ou votre appareil mobile. Tirez avantage de toutes les formidables fonctions de Zang Office sans vous ruiner, car le téléphone logiciel Zang Office est inclus gratuitement avec votre abonnement Zang Office!',
  E129_SIP_DESK_PHONE: 'Téléphone de bureau SIP E129',
  STANDARD_PHONE: 'Téléphone standard',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Le téléphone de bureau SIP E129 d\'Avaya comporte toutes les fonctions de traitement des appels essentielles que vous désirez retrouver dans un téléphone SIP abordable et hautement fonctionnel. Le téléphone de bureau E129 d\'Avaya permet aux utilisateurs de transférer, de mettre en mode discrétion, d\'acheminer et de mettre des appels en attente et de commencer des audioconférences non planifiées en appuyant sur un bouton. Le haut-parleur duplex intégral permet des conversations mains libres et son port d\'alimentation par Ethernet offre une connexion pratique au réseau. Le téléphone de bureau SIP E129 d\'Avaya possède les bonnes capacités d\'appels et il est abordable et attrayant. Adaptateur c.a. inclus.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Participez en utilisant un appareil de bureau dédié, tout en verre et novateur. Utilisez la voix, le clavardage et des applis coopératives grâce à des connexions par touche unique. Il n\'y a aucune interruption ou pause anormale. Et aucun besoin de gérer plusieurs appareils pour participer. Tissez des expériences personnalisées et uniques dans vos flux de travail et vos processus commerciaux. Ce puissant appareil personnalisable vous offre l\'avantage d\'un téléphone de bureau et la flexibilité d\'une plateforme d\'application.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'Téléphone d\'audioconférence B179',
  CONFERENCE_PHONE: 'Téléphone d\'audioconférence',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Idéal pour les salles du conseil et les grandes salles de conférence pour des groupes de plus de 10 personnes, le téléphone d\'audioconférence B179 aide à améliorer la productivité et la collaboration des employés. Le téléphone d\'audioconférence B179 est versatile et il complète vos solutions existantes tout en étant facilement redéployé lorsque votre entreprise grandit ou que vos besoins changent. Adaptateur c.a. inclus.',
  PLAN: 'Forfait',
  REDIRECTING: 'Réacheminement',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Veuillez vous assurer que tous les champs comportent des valeurs valides',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Chaque forfait Zang Office exige au moins un type d\'utilisateur. Veuillez retourner à l\'étape de sélection des appareils et modifiez votre configuration.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Il semblerait que vous n\'avez pas sélectionné de numéro pour votre compte Zang Office. Veuillez retourner à l\'étape de sélection du numéro pour sélectionner un numéro.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'Ce nom de compte Zang Office est déjà pris. Essayez-en un autre',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'Le numéro Zang Office que vous avez sélectionné a déjà été acheté par un autre client. Veuillez retourner à l\'étape de sélection du numéro pour sélectionner un autre numéro.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Passez à un forfait au mois sans engagement et obtenez les <span class="text-400">30 PREMIERS JOURS GRATUITEMENT</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'ou engagez-vous avec un forfait annuel et obtenez un meilleur prix ainsi qu\'un',
  FREE_PHONE: 'TÉLÉPHONE GRATUIT',
  DISCOUNT: 'remise',
  DISCOUNTED_PHONE: 'téléphone à prix réduit',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'de la valeur totale de vos achats de téléphones',
  LIMITED_TIME_OFFER: 'Offre d\'une durée limitée',
  PROMOTION: 'Promotion',
  ZANG_SPACES_PROMOTION: 'Promotion Zang Spaces',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Poursuivre pour la sélection du numéro de téléphone',
  DURATION: 'Durée',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'Félicitations! Vous avez un crédit de <strong>{amount}</strong> pour appliquer sur le total de votre commande d\'appareils!',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'Toutes les remises applicables seront ajustées dans votre sommaire final de commande.',
  SHIPPING_TYPE: 'Type d\'expédition',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'Les détails du suivi seront envoyés lorsque vos éléments auront été expédiés de notre entrepôt',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Recevez {amount} en crédit par utilisateur pour dépenser à l\'achat de n\'importe quel appareil. Offre limitée dans le temps.',
  PARTNER_ORDERS: 'Commandes du partenaire',
  COMMISSION: 'Commission',

  ADDITIONAL_DEVICES: 'Appareils supplémentaires',
  NO_USER: 'Aucun utilisateur',
  QUANTITY: 'Quantité',
  BUY_DEVICES: 'Acheter des appareils',
  DEVICE: 'Appareil',
  PRICE: 'Prix',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'Veuillez entrer au moins {chars} caractères pour rechercher un agent',
  NO_RESULTS_FOUND: 'Aucun résultat trouvé',
  RESULTS_COULD_NOT_BE_LOADED: 'Les résultats n\'ont pas pu être chargés',
  CLEAR_SELECTION: 'Effacer la sélection',


  RESET_ALL_PURCHASES: 'Effacer tous les achats',
  LISTS: 'Listes',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Veuillez entrer votre numéro de téléphone avant de créer une soumission.',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Veuillez entrer vos informations de facturation et d\'expédition avant de créer une soumission',
  CALCULATING_TAXES_PLEASE_WAIT: 'Calcul des taxes. Veuillez patienter...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Une erreur est survenue avec la carte de crédit que vous avez choisie.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Une erreur est survenue avec cette carte de crédit. Veuillez en utiliser une autre',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'Une erreur est survenue lors de la facturation de votre commande. Veuillez choisir une autre carte de crédit',
  INVALID_CREDIT_CARD: 'Carte de crédit non valide',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: 'Le {address_type} ne correspond pas avec l\'adresse associée à la carte de crédit',
  INVALID_SECURITY_CODE: 'Code de sécurité (cvc) non valide',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Tout rabais et prix promotionnel applicable a été appliqué à cette facture',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'Nous ne pouvons pas créer votre compte client. Veuillez réessayer',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Nous ne pouvons pas créer votre carte de crédit. Veuillez réessayer',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Cette carte de crédit est utilisée pour un abonnement récurrent.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Erreur lors de la configuration de cette carte de crédit comme carte par défaut.',
  DEFAULT: 'Par défaut',
  SET_DEFAULT: 'Configurer par défaut',
  SALES_FORCE_QUOTE_ID: 'ID de soumission Salesforce',
  SALES_FORCE_ORDER_ID: 'ID de commande Salesforce',
  SALES_FORCE_OPPORTUNITY_ID: 'ID d\'opportunité Salesforce',
  SALES_FORCE_CONTACT_ID: 'ID de contact Salesforce',
  SALES_FORCE_CONTRACT_ID: 'ID de contrat Salesforce',
  SALES_FORCE_ACCOUNT_ID: 'ID de compte Salesforce',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Simplement \'Ajouter un appareil\' and connect it with a user.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '\'Ajoutez un appareil\' tout simplement et connectez-le à un utilisateur.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Acheter des appareils supplémentaires pour votre compte Zang Office',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'Oups! Une erreur est survenue avec votre commande. Actualisez la page, effacez votre commande et recommencez.',
  CREATE_A_NEW_COMPANY: 'Créer une entreprise',
  ADD_A_NEW_COMPANY: 'Ajouter une nouvelle entreprise',
  PARTNER_DETAILS: 'Détails du partenaire',
  AGENTS: 'Agents',
  PARTNER_PORTAL: 'Portail partenaire',
  AGENT: 'Agent',
  AGENT_PORTAL: 'Portail agent',
  NO_AGENTS_FOUND: 'Aucun agent trouvé',
  NO_AGENT: 'Aucun agent',
  RELATION: 'Relation',
  OWNER: 'Propriétaire',
  ADMIN: 'Administrateur',
  MANAGER: 'Gestionnaire',
  EMPLOYEE: 'Employé',
  ACTIVE: 'Actif',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: 'Veuillez communiquer avec l\'un des partenaires avec lesquels vous êtes associé',
  APPLIED_ON: 'Appliqué sur',
  JOIN_A_PARTNER: 'Rejoindre un partenaire',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'Vous êtes à deux doigts de rejoindre <b>{COMPANY_NAME}</b>',
  JOIN_PLACEHOLDER_NOW: 'Rejoindre {COMPANY_NAME} maintenant',
  UPDATE_AGENT_INFO: 'Mettre à jour les renseignements sur l\'agent',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Démarrez avec Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'En partenariat avec Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'Une solution de collaboration simple, puissante et unifiée',
  IP_OFFICE_DONT_PAY_TILL: 'Ne payez rien avant le 15 avril 2018!',
  LOGIN: 'Se connecter',
  DISCOVER: 'Découvrir',
  SOLUTIONS: 'Solutions',
  SERVICES: 'Services',
  INDUSTRIES: 'Industries',
  CASE_STUDIES: 'Études de cas',
  PROGRAMS_AND_PROMOTIONS: 'Programmes et promotions',
  AUTHENTIC_AVAYA: 'Avaya authentique',
  PERSPECTIVES: 'Points de vue',
  AVAYA_CONNECTED_BLOG: 'Blog Avaya Connected',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: 'Solution Finder',
  INFO_FOR: 'Renseignements pour',
  DEVELOPERS: 'Développeurs',
  CHANNEL_PARTNERS: 'Partenaires de distribution',
  TECHNOLOGY_PARTNERS: 'Partenaires technologiques',
  CONSULTANTS: 'Consultants',
  INVESTORS: 'Investisseurs',
  MEDIA_ANALYSTS: 'Analystes médias',
  SUPPLIERS: 'Fournisseurs',
  CONNECT_WITH_US: 'Communiquez avec nous',
  FIND_A_CHANNEL_PARTNER: 'Trouver un partenaire de distribution',
  FIND_A_TECHNOLOGY_PARTNER: 'Trouver un partenaire technologique',
  EXECUTIVE_BRIEFING_CENTER: 'Executive Briefing Center (Centre d\'information pour les cadres)',
  AVAYA_LEARNING_SERVICES: 'Services d\'apprentissage Avaya',
  CONTACTS: 'Contacts',
  ABOUT_AVAYA: 'À propos d\'Avaya',
  EVENTS: 'Événements',
  NEWSROOM: 'Salle de presse',
  INVESTOR_RELATIONS: 'Relations avec les investisseurs',
  CORPORATE_RESPONSIBILITY: 'Responsabilité de l\'entreprise',
  OUR_COMPANY: 'Notre entreprise',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'International Avaya Users Group – IAUG (Groupe d\'utilisateurs internationaux Avaya)',
  CAREERS: 'Carrières',
  YOUR_PERSONAL_LINK: 'Votre lien personnel',
  SITEMAP: 'Plan du site',
  TERMS_OF_USE: 'Modalités d\'utilisation',
  PRIVACY: 'Confidentialité',
  COOKIES: 'Témoins',
  AVAYA_INVOICE: 'Facture',
  IP_OFFICE_ACCOUNT_NAME: 'Nom de compte Avaya Cloud',
  IP_OFFICE_PLAN_NUMBER: 'Numéro de forfait Avaya Cloud',
  IP_OFFICE_PHONE_APPLICATION: 'Téléphone logiciel d\'Avaya Cloud Solutions',
  IP_OFFICE_PHONE_DESCRIPTION: 'Le téléphone logiciel d\'Avaya Cloud Solutions offre aux utilisateurs un accès simple à tous les canaux de communication dans une seule interface. Le téléphone logiciel Avaya Cloud Solutions vous permet de vous connecter à vos solutions infonuagiques d\'Avaya et d\'émettre et de recevoir des appels vocaux et vidéo à partir de votre poste de travail sur votre PC. Le téléphone logiciel est inclus gratuitement dans les abonnements Avaya Cloud Solutions Standard et Grand.',
  PLAN_MONTH_1_MONTH_1: 'Forfait mensuel (aucun crédit d\'appareil)',
  PLAN_YEAR_1_MONTH_1: 'Forfait de 1 an | Facturé mensuellement',
  PLAN_YEAR_1_YEAR_1: 'Forfait de 1 an, payer en entier',
  PLAN_YEAR_2_MONTH_1: 'Forfait de 2 ans | Facturé mensuellement',
  PLAN_YEAR_2_YEAR_1: 'Forfait de 2 ans | Facturé annuellement',
  PLAN_YEAR_2_YEAR_2: 'Forfait de 2 ans, payer en entier',
  PLAN_YEAR_3_MONTH_1: 'Forfait de 3 ans | Facturé mensuellement',
  PLAN_YEAR_3_YEAR_1: 'Forfait de 3 ans | Facturé annuellement',
  PLAN_YEAR_3_YEAR_3: 'Forfait de 3 ans, payer en entier',
  PLAN_YEAR_5_MONTH_1: 'Forfait de 5 ans | Facturé mensuellement',
  ACCORDING_TO_PLAN: 'Selon le forfait',
  TOTAL_USER_PLAN_FEE: 'Total des frais du forfait d\'utilisateur',
  HEALTHCARE_DENY_MESSAGE: 'Nous vous remercions d\'avoir choisi la solution Avaya Cloud. Malheureusement, nous ne sommes pas encore conformes à la loi HIPAA, nous ne pouvons donc pas vous fournir notre service parce que vous êtes dans le secteur de la santé. Nous vous aviserons lorsque nous obtiendrons notre certification, et nous espérons pouvoir compter sur vous à ce moment! N\'hésitez pas à communiquer avec nous à l\'adresse <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a> si vous avez des questions.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Sélectionnez vos appareils Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Sélectionnez votre numéro Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'Modifiez vos utilisateurs et attribuez-leur des appareils.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Ajoutez un numéro de téléphone que vous souhaitez utiliser pour vos Avaya Cloud Solutions.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'Attribuez un numéro de téléphone à votre solution.',
  INVITE_A_NEW_AGENT: 'Inviter un nouvel agent',
  I_WANT_TO_INVITE_A: 'Je veux inviter un',
  CONTACT_EMAIL: 'Adresse de courriel du contact',
  CONTACT_NAME: 'Nom du contact',
  COMPANY_NAME: 'Nom de l\'entreprise',
  CONTACT: 'Contact',
  COMPANY_IS_INCORPORATED: 'L\'entreprise est incorporée',
  INDIVIDUAL: 'Particulier',
  INDIVIDUALS: 'Particuliers',
  SEND_INVITATION_EMAIL: 'Envoyer un courriel d\'invitation',
  SENDING_INVITATION_EMAIL: 'Envoi d\'un courriel d\'invitation...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: 'L\'invitation a été envoyée',
  ALL_FIELDS_ARE_REQUIRED: 'Tous les champs sont obligatoires',
  PARTNER_NOT_FOUND: 'Aucun partenaire trouvé',
  SALE_AGENT_REGISTRATION: 'Inscription en tant que représentant',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: 'Remplissez simplement le formulaire ci-dessous pour devenir un représentant pour',
  VIEW: 'AFFICHER',
  COMPANIES: 'Entreprises',
  ADD_A_PARTNER: 'Ajouter un partenaire',
  ADD_PARTNER: 'Ajouter un partenaire',
  PARTNERS_PERSONAL_LINK: 'Lien personnel du partenaire',
  MASTER_SALES_AGENT: 'Représentant principal',
  AVAYA_J129_LABEL: 'Téléphone IP J129',
  AVAYA_J129_DESCRIPTION: 'Obtenez toutes vos fonctions essentielles de gestion des appels dans un téléphone SIP abordable et hautement fonctionnel. Ce téléphone offre les fonctions essentielles requises par les utilisateurs dans les entreprises de toute taille. Le téléphone prend en charge deux touches de ligne avec affichage d\'appel sur une seule ligne. Achetez un téléphone avec des fonctions solides qui dépasse largement tout ce qui disponible sur le marché aujourd\'hui.',
  AVAYA_J169_LABEL: 'Téléphone IP J169',
  AVAYA_J169_DESCRIPTION: 'Obtenez toutes vos fonctions essentielles de gestion des appels dans un téléphone SIP abordable et hautement fonctionnel. Ce téléphone offre les fonctions essentielles requises par les utilisateurs dans les entreprises de toute taille. Le téléphone prend en charge deux touches de ligne avec affichage d\'appel sur une seule ligne. Achetez un téléphone avec des fonctions solides qui dépasse largement tout ce qui disponible sur le marché aujourd\'hui.',
  AVAYA_J179_LABEL: 'Téléphone IP J179',
  AVAYA_J179_DESCRIPTION: 'Obtenez toutes vos fonctions essentielles de gestion des appels dans un téléphone SIP abordable et hautement fonctionnel. Ce téléphone offre les fonctions essentielles requises par les utilisateurs dans les entreprises de toute taille. Le téléphone prend en charge deux touches de ligne avec affichage d\'appel sur une seule ligne. Achetez un téléphone avec des fonctions solides qui dépasse largement tout ce qui disponible sur le marché aujourd\'hui.',
  AVAYA_K175_LABEL: 'K175 d\'Avaya Vantage™',
  AVAYA_K175_DESCRIPTION: 'Obtenez toutes vos fonctions essentielles de gestion des appels dans un téléphone SIP abordable et hautement fonctionnel. Ce téléphone offre les fonctions essentielles requises par les utilisateurs dans les entreprises de toute taille. Le téléphone prend en charge deux touches de ligne avec affichage d\'appel sur une seule ligne. Achetez un téléphone avec des fonctions solides qui dépasse largement tout ce qui disponible sur le marché aujourd\'hui.',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: 'Téléphone de bureau IP 9641GS',
  AVAYA_9641G_DESCRIPTION: 'Le téléphone 9641GS d\'Avaya est un téléphone de bureau multiligne haut de gamme idéal pour les personnes qui passent beaucoup de temps au téléphone et qui comptent sur des capacités de communications intelligentes et d\'amélioration de la productivité. Le 9641GS dispose d\'un écran graphique couleur de 5,0 pouces, d\'un écran tactile plus grand et d\'une qualité audio haute définition. Son codec audio à large bande offre des performances audio exceptionnelles sur toutes les interfaces audio, notamment le combiné, le casque et le haut-parleur.',
  AVAYA_9608G_LABEL: 'Téléphone de bureau IP 9608G',
  AVAYA_9608G_DESCRIPTION: 'Le téléphone de bureau 9608G est un téléphone entièrement fonctionnel et économique qui prend en charge l\'affichage intégré gigabit et monochrome. Son port d\'alimentation par Ethernet simplifie le déploiement et son codec audio à large bande offre des performances audio exceptionnelles. Conçu pour les petites et grandes entreprises, ce téléphone de bureau comprend l\'accès à huit lignes et des étiquettes graphiques pouvant être administrées de manière centralisée.',
  AVAYA_9611G_LABEL: 'Téléphone de bureau IP 9611G',
  AVAYA_9611G_DESCRIPTION: 'Le modèle 9611G comprend un gigabit intégré et une interface USB. Il dispose d\'un écran couleur graphique de 3,5 pouces avec rétroéclairage blanc et des étiquettes graphiques pouvant être administrées de manière centralisée. Son port d\'alimentation par Ethernet simplifie le déploiement et son codec audio à large bande offre des performances audio exceptionnelles.',
  AVAYA_PHONE_B179_LABEL: 'Téléphone d\'audioconférence SIP B179',
  AVAYA_PHONE_B179_DESCRIPTION: 'Testé par Tolly, ce téléphone de conférence SIP flexible offre un son clair et naturel grâce à OmniSound 2.0, la technologie audio à large bande brevetée d\'Avaya. Le téléphone est doté de fonctions intelligentes pour des conférences téléphoniques plus efficaces. Utilisez le guide de conférence pour appeler des groupes préprogrammés. Importez et exportez facilement des coordonnées via l\'interface Web. Créez votre propre liste de contacts avec la fonction de profil personnel de l\'utilisateur.',
  HAVE_LARGE_NUMBERS_OF_USERS: 'Vous avez un grand nombre d\'utilisateurs?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'Consultez notre répartition des rabais de volume.',
  DEVICE_FEE: 'Frais d\'appareil',
  UP_TO_DEVICE_CREDITE_PER_USER: 'Jusqu\'à {$} de crédit d\'appareil par utilisateur',
  PROMOTION_REMAINING_DETAIL_INFO: 'Il vous reste encore <b>{0}</b> à dépenser en crédit pour les appareils promotionnels. Veuillez noter que tout crédit restant ne sera plus valide après votre achat et ne sera pas reporté sur votre compte pour de futurs achats.',
  VIEW_USER_FEATURES: 'Afficher les fonctions de l\'utilisateur',
  FREE_DEVICES_PER_USER_INFO: '{0} (Jusqu\'à {1} de crédit d\'appareil par utilisateur)',
  VALUE_OF_DEVICE_CREDIT: '{0} Utilisateurs = {0} en total de crédit d\'appareil',
  PROMOTION_DELAYED_BILLING_INFO: 'Promotion : des reçus détaillés vous seront fournis et votre carte de crédit sera débitée de tout solde impayé lorsque votre cycle de facturation débutera officiellement.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'Veuillez sélectionner un agent pour terminer la commande',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: 'Veuillez fournir un nom de domaine valide (exemple.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Votre système Avaya Cloud Solution est prêt!',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Votre système Avaya Cloud Solution est maintenant configuré!',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Numéro de téléphone Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Nom de domaine SIP Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_ID: 'ID de domaine SIP Avaya Cloud Solutions',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Votre système Avaya Cloud Solution est en cours de configuration.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'Nous vous remercions de votre commande. Nous sommes en train de configurer votre système Avaya Cloud Solutions et nous communiquerons avec vous une fois la configuration terminée. <br /> N\'hésitez pas à communiquer avec le soutien Avaya Cloud Solutions si vous avez des questions {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'Ce compte n\'a pas pu être approvisionné',
  ERROR_CODE: 'Code d\'erreur',
  ERROR_MESSAGE: 'Message d\'erreur',
  ADMIN_PORTAL_LINK: 'Lien du portail d\'administration',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Mot de passe utilisateur par défaut Avaya Cloud Solutions',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Numéro de téléphone temporaire Avaya Cloud Solutions',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'Postes d\'utilisateur de base',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Postes d\'utilisateur standard',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'Postes d\'utilisateur avancé',
  IP_OFFICE_DEFAULT_USER_PIN: 'NIP utilisateur par défaut',
  IP_OFFICE_SAME_AS_PIN: 'Identique au poste (exemple : 200)',
  IP_OFFICE_ORDERID: 'ID de commande Avaya Cloud Solutions',
  IP_OFFICE_HOST_NAME: 'Votre nom d\'hôte Avaya Cloud Solutions',
  IP_OFFICE_IP_ADDRESS: 'Votre adresse IP Avaya Cloud Solutions',
  IP_OFFICE_SUBSCRIPTIONID: 'Numéro d\'abonnement Avaya Cloud Solutions',
  CALCULATING: 'calcul en cours...',
  RESET_ALL_PARTNERS: 'Effacer les données du partenaire',
  ERROR_GETTING_AGENTS: 'Erreur lors de la vérification des agents. Veuillez réessayer',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Il existe déjà un agent avec cette adresse de courriel dans votre équipe',
  AUTO_APPROVE_ACTIVATE_AGENT: 'Approuver/activer automatiquement l\'agent',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Il existe déjà une entreprise avec cette adresse de courriel dans votre équipe',
  MASTER_SALES_AGENT_PORTAL: 'Portail de représentant principal',
  SALES_AGENT_PORTAL: 'Portail de représentant',
  E911_ADDRESS: 'Adresse E911',
  OVERVIEW: 'Aperçu',
  ADD_COMPANY_OR_SALES_AGENT: 'Ajouter une entreprise ou un agent',
  ADD_AN_AGENT: 'Ajouter un agent à',
  INACTIVE: 'Inactif',
  AGENTS_PERSONAL_CONNECTION_LINK: 'Lien de connexion personnel de l\'agent',
  PURCHASE_DATE_AND_CUSTOMER: 'Date d\'achat et client',
  ORDER_DETAILS: 'Détails de la commande',
  SELECT_AGENT: 'Tous les agents',
  FROM: 'de',
  TO: 'à',
  EXPORT_REPORT: 'Rapport d\'exportation',
  NO_SALES_FOUND: 'Aucune vente trouvée',
  ADD_A_COMPANY: 'Ajouter une entreprise',
  AUTO_APPROVE_COMPANY: 'Approuver automatiquement l\'entreprise',
  AUTO_ACTIVATE_AGENT: 'Activer automatiquement l\'agent',
  ADD_COMPANY: 'Ajouter une entreprise',
  ADD_COMPANY_NAME_AGENT_ADMIN: 'Ajouter un agent/administrateur {COMPANY_NAME}',
  ADD_AGENT_ADMIN: 'Ajouter un agent/administrateur',
  ALL_COMPANIES: 'Toutes les entreprises',
  START_DATE: 'Date de début',
  HEY: 'Bonjour',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: 'Nous sommes votre gestionnaire de réussite de la clientèle. Nous sommes là pour vous aider à tirer le meilleur parti de vos Avaya Cloud Solutions. Votre équipe de soutien Avaya Cloud Solutions comprend également notre équipe de soutien technique – <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: 'Nous aimerions programmer un appel de lancement dans les prochains jours pour vous présenter votre équipe de soutien et terminer la configuration de votre système. <strong> Veuillez communiquer avec nous à l\'adresse <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}"> {CUSTOMER_SUCCESS_EMAIL}</a> pour nous indiquer le jour et l\'heure qui vous conviennent pour un appel d\'une heure. <strong>',
  START_USING_YOUR_IP_OFFICE: 'Commencez à utiliser votre système Avaya Cloud Solutions maintenant!',
  BELOW_ARE_DETAILS: 'Vous trouverez ci-dessous les informations sur le compte de votre système, les informations de connexion de l\'utilisateur et les téléchargements d\'applications :',
  YOUR_IP_OFFICE_INFO: 'Vos informations système :',
  LOGIN_INFO_TABLE: 'Votre tableau d\'informations utilisateur :',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'Tous vos utilisateurs peuvent configurer leurs informations, régler le renvoi d\'appel, écouter les messages vocaux et plus encore, en utilisant les informations ci-dessus et en se connectant à leurs portails individuels d\'utilisateur des services en nuage.',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'Applications disponibles pour vos utilisateurs :',
  DO_NOT_HESITATE_TO_EMAIL_US: 'N\'hésitez pas à nous envoyer un courriel à l\'adresse <a href="mailto:{CS_EMAIL}"> {CS_EMAIL}</a> si vous avez des questions.',
  THANK_YOU: 'Merci!',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi"> Avaya Communicator for Web (Windows) </a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm"> Avaya Communicator for Web (extension Chrome) </a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Console logicielle Avaya Cloud Solutions (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">Document d\'installation</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">Document d\'installation</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">Document d\'installation</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">Document d\'installation</a>',




  USER_NAMES_COLUMN: 'Nom d\'utilisateur',
  EXTENSIONS_COLUMN: 'Poste',
  TEMP_PIN_COLUMN: 'Épingler',
  TEMP_PASSWORD_COLUMN: 'Mot de passe',
  USER_TYPE_COLUMN: 'Type d\'utilisateur',
  DEVICE_MODEL_COLUMN: 'Appareil',
  POWER_USER: 'Grand',
  STANDARD_USER: 'Standard',
  BASIC_USER: 'De base',
  ORDERID: 'ID de commande',
  ACCOUNT_NAME: 'Nom de compte',
  HOST_NAME: 'Nom d\'hôte',
  ADMIN_PORTAL: 'Portail administrateur',
  IP_ADDRESS: 'Adresse IP',
  PHONE_NUMBER: 'Numéro de téléphone',
  TEMPORARY_PHONE_NUMBER: 'Numéro de téléphone temporaire',
  EXCITING_TIMES_AHEAD: 'Des moments passionnants à venir',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'Le nom de domaine {DOMAIN_NAME} n\'est pas valide ou il est présentement utilisé par une autre entreprise.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'Le nom de domaine {1} n\'est pas valide ou il est présentement utilisé par une autre entreprise.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: 'Le système ne peut pas valider votre entreprise. Veuillez réessayer',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'Pour toute information non disponible (le cas échéant), veuillez communiquer avec le soutien Avaya Cloud : ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Un compte Avaya Cloud n\'a pas pu démarrer l\'approvisionnement',
  LEGAL: 'Mentions légales',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Sélectionnez un forfait d\'un an (ou plus) et recevez un crédit par utilisateur pour l\'achat de tout appareil. Offre d\'une durée limitée.',
  USER_PORTAL: 'Portail utilisateur',
  E_911: 'E911',
  DECLINE: 'Refuser',
  ACCEPT: 'Accepter',
  PRINT: 'Imprimer',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'Veuillez accepter toutes les conditions ci-dessus pour terminer votre commande',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'Attribuez un appareil à vos utilisateurs.',
  SELECT: 'Sélectionner',
  USER_DETAILS: 'Détails de l\'utilisateur',
  DEVICE_DETAILS: 'Détails de l\'appareil',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: 'Veuillez lire attentivement nos modalités de service avant d\'accepter.',
  PARTNER_ORDERS_RECORDS_HINT: '*Tous les registres de ventes sont fournis à titre d\'information uniquement. Les rapports de ventes officiels et finaux seront fournis par Avaya Finance conformément au contrat de représentant principal.',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: 'Veuillez sélectionner un représentant pour créer le devis',
  COMPANY_DETAILS: 'Détails de l\'entreprise',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'Plus taxes applicables.',
  SELECT_PRODUCT: 'Sélectionner un produit',
  CLOUD_UC_SMALL_MONTH1: 'Cloud UC Essentials – Mensuel',
  SMALL: 'Petit',
  CLOUD_UC_SMALL_MONTH12: 'Cloud UC Essentials – Forfait de 1 an',
  CLOUD_UC_SMALL_3YEARS: 'Cloud UC Essentials – Forfait de 3 ans',
  CLOUD_UC_SMALL_5YEARS: 'Cloud UC Essentials – Forfait de 5 ans',
  MEDIUM: 'Moyen',
  CLOUD_UC_MEDIUM_MONTL1: 'Cloud UC Business – Forfait mensuel',
  CLOUD_UC_MEDIUM_MONTH12: 'Cloud UC Business – Forfait de 1 an',
  CLOUD_UC_MEDIUM_3YEARS: 'Cloud UC Business – Forfait de 3 ans',
  CLOUD_UC_MEDIUM_5YEARS: 'Cloud UC Business – Forfait de 5 ans',
  LARGE: 'Grand',
  CLOUD_UC_LARGE_MONTL1: 'Grand Cloud UC – Prépayé',
  CLOUD_UC_LARGE_MONTL12: 'Grand Cloud UC – Forfait Annuel',
  CLOUD_UC_SMALL_SHORT_INFO: 'Entre 1 et 99 employés',
  CLOUD_UC_MEDIUM_SHORT_INFO: 'Entre 100 et 999 employés',
  CLOUD_UC_LARGE_SHORT_INFO: 'Plus de 1 000 employés',
  SELECTED: 'Sélectionné',
  BASIC_PHONE_SERVICE: 'Service téléphonique de base',
  UNLIMITED_NATIONAL_WIDE: 'Interurbains nationaux illimités',
  STANDARD_FEATURES: 'Fonctions standards',
  HOW_MANY_USERS: 'De combien d\'utilisateurs avez-vous besoin?',
  ADD_ON_ADDITIONAL_FEATURES: 'Fonctions supplémentaires',
  ONETIME_FEE: 'Frais uniques',
  RECURRING_FEE: 'Frais récurrents',
  SELECT_MAIN_NUMBER: 'Sélectionnez le numéro principal',
  TOLL_FREE: 'Numéro sans frais',
  LOCAL_NUMBER: 'Numéro local',
  TRANSFER_NUMBER: 'Numéro de transfert',
  USERS_COUNT: '{qty} utilisateurs',
  DEVICES_COUNT: '{qty} appareil(s)',
  UC_OFFER_TITLE: 'Nous avons la solution idéale pour vous!',
  UC_OFFER_DESCRIPTION: 'Que vous soyez une petite, moyenne ou grande entreprise, nous avons ce que vous recherchez! Quel type d\'entreprise êtes-vous?',

  // 'BASIC_PHONE_SERVICE': 'Service téléphonique de base',

  TAX_CALC_ERROR_MSG: 'Impossible de calculer la taxe. Veuillez vérifier que l\'adresse de facturation est correcte.',
  'VIOLATION.FIELD_IS_EMPTY': '{1} est requis',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} – {2} est requis',
  'VIOLATION.FIELD_VALUE_INVALID': 'La valeur {1} n\'est pas valide',
  'VIOLATION.FIELD_VALUE_INVALID2': 'La valeur {1} – {2} n\'est pas valide',
  'VIOLATION.TAX_CALCULATION_FAILED': 'Impossible de calculer la taxe',
  'VIOLATION.AGREE_ON_LEGAL_DOC': 'Vous devez lire et accepter « {1} »',
  'VIOLATION.CART_IS_EMPTY': 'Le panier est vide',
  'VIOLATION.CART_IS_TOO_BIG': 'Le panier contient trop d\'articles',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} a été supprimé du panier',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': 'La quantité {1} est ajustée de {2} à {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': 'La remise {1} est ajustée de {2} à {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': 'Impossible d\'ajouter un élément avec {1} comme devise à un panier avec {2} comme devise',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': 'La règle de remise {1} n\'est pas définie',
  'SALESMODELRULE.UNKNOWN_ERROR': 'Erreur inconnue',
  'SALESMODELRULE.INVALID_PARAMETER': 'Paramètre non valide : {1}',
  ONE_TIME: 'Une fois',
  ADDON_PRICING_HINT: '*Les prix des ajouts sont par siège et appliqués à tous les utilisateurs. L\'ajout d\'articles complémentaires spécifiques aux utilisateurs peut être effectué après l\'achat dans votre portail administrateur.',
  ADD_TO_CART_HINT: 'Effectuez les étapes ci-dessus pour ajouter au panier',
  ITEM_UNITS: '{qty} unités',
  ADDONS_COUNT: '{qty} articles complémentaires',
  ADDON_COUNT: '{qty} article complémentaire',
  MULTIPLE_TYPES: 'Plusieurs types',
  MIXED: 'Mixte',
  FREE_PRICE: 'GRATUIT',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essentials',
  UC_ESSENTIALS_DESCRIPTION: 'Les meilleures communications infonuagiques pour les entreprises de toute taille.',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: 'Dotez votre entreprise des toutes dernières solutions en matière de communications d\'entreprise en nuage.',
  UC_BUSINESS_POWER_PACKAGE: 'Mise à niveau vers les utilisateurs AVANCÉS',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>Numéro de téléphone direct :</strong> Numéro unique dédié, de sorte que tout le monde peut vous appeler directement au lieu de passer par le numéro principal du bureau et la réceptionniste (virtuelle ou humaine). </li><li><strong> Appel vidéo direct :</strong> Ajoutez la fonction vidéo à vos appels téléphoniques. </li><li><strong>Intégration de Salesforce© :</strong> Des communications riches et complètes pour les utilisateurs finaux directement à partir de Salesforce. </li><li><strong>Intégration de Google© :</strong> Des communications en temps réel basées sur le navigateur directement depuis Google Chrome et dans toutes vos applications Google.</li><li><strong>Intégration de Skype Entreprise© :</strong> Une expérience de collaboration moderne, simplifiée et conviviale avec Skype Entreprise©.</li></ul>',
  SHOW_MORE: 'Afficher plus',
  HIDE: 'Masquer',
  VIEW_COMPLETE_FEATURE_LIST: ' Afficher la liste complète des fonctions',
  FILTER_BY: 'Filtrer par',
  UC_OFFERS: 'Solutions UC',
  PAY_MONTHLY: 'Payer mensuellement',
  PAY_ANNUALLY: 'Payer annuellement',
  COMING_SOON: 'Très bientôt',
  TAX_CALC_ERROR_MSG: 'Impossible de calculer la taxe. Veuillez vérifier que l\'adresse est correcte.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: 'Veuillez entrer le nom d\'un pays pour consulter les tarifs interurbains actuels.',
  LONG_DISTANCE_RATE_NOT_FOUND: 'Le tarif interurbain n\'est pas disponible pour ce pays. Veuillez communiquer avec nous à l\'adresse {CUSTOMER_SUCCESS_EMAIL} pour obtenir des informations sur les appels interurbains vers ce pays.',
  AREA_CODE: 'Indicatif régional',
  INVALID_CREDIT_CARD_ZIP: 'La carte de crédit ne correspond pas au code postal/ZIP.',
  VIEW_LONG_DISTANCE_RATES: 'Afficher les tarifs interurbains',
  LONG_DISTANCE_SUBTITLE_TEXT: 'Nos tarifs d\'appels interurbains à moindre coût vous permettent de rester en contact avec des personnes partout dans le monde.',
  RATES_SUBJECT_TO_CHANGE: '*Tarifs modifiables sans préavis.',
  CREDIT_CARD_DECLINED: 'La carte de crédit a été refusée.',
  ENTER_COUNTRY_NAME: 'Entrez le nom du pays',
  ADD_TO_CART: 'Ajouter au panier',
  UPDATE_CART: 'Mettre à jour le panier',
  PER_USER: 'Par utilisateur',
  COMPARE_UC_OFFERS: 'Comparez les offres UC',
  PROCEED_TO_CHECKOUT: 'Passer à la caisse',
  BEFORE_APPLICABLE_TAXES: '* Avant les taxes applicables',
  YEAR_PLAN: 'Forfait de 1 an',
  YEARS_PLAN: 'Forfait de {0} ans',
  MONTHS_PLAN: 'Forfait de {0} mois',
  ENTER_NUMBER_OF_USERS: 'Entrez le nombre d\'utilisateurs que vous voulez pour cette solution',
  YEAR: 'Année',
  BILLED_MONTH: 'Facturé mensuellement',
  COMPANY_INCORPORATED: 'Incorporé',
  COMPANY_NOT_INCORPORATED: 'Non incorporé',
  EXISTING_CONFIG_WARNING: 'Vous avez déjà une configuration pour <br/><b>{0}</b>.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: 'Voulez-vous supprimer votre configuration actuelle?',
  DISCARD_MY_CONFIGURATION: 'Supprimer ma configuration',
  DISCARD: 'Supprimer',
  EDIT_MY_CONFIGURATION: 'Modifier ma configuration actuelle',
  CONTINUE: 'Continuer',
  SELECT_A_PLAN: 'Sélectionner un forfait',
  PROMOTION_DETAIL_INFO: '*Vous avez sélectionné un total de <b>{0} utilisateurs</b>!<br/> Ce qui équivaut à un total de <b>{1}</b> de crédit d\'appareil.',
  BILLED_MONTH_FREQUENCY: 'Facturé tous les {0} mois',
  BILLED_YEAR_FREQUENCY: 'Facturé tous les {0} ans',
  CONTACT_OUR_CUSTOMER_CARE: 'Communiquez avec notre équipe de service à la clientèle',
  NEED_HELP_INFO: 'Besoin d\'aide? Notre équipe de service à la clientèle est toujours prête à répondre à vos questions, problèmes ou renseignements.',
  REMOVE: 'Retirer',
  REMOVE_ITEM_FROM_CART_WARNING: 'Voulez-vous retirer <b>{0}</b> du panier?',
  NO_ITEM_IN_THE_CART: 'Vous n\'avez aucun article dans votre panier.',
  CONTINUE_SHOPPING: 'Continuer vos achats',
  TOTAL_TAXES: 'Total des taxes',
  UC_SOLUTIONS: 'Solutions UC',
  UNIFIED_COMMUNICATIONS: 'Communications unifiées',
  ADD_ONS: 'Modules complémentaires',
  SYSTEM_ADDONS: 'Modules système',
  ADD_DEVICES: 'Ajouter des appareils',
  SELECT_UPTO_DEVICES: 'Sélectionnez jusqu\'à (<b>{0}</b>) appareils pour <b>{1}</b>',
  DONE: 'Terminé',
  SELECT_DEVICES: 'Sélectionner des appareils',
  EDIT_DEVICE_SELECTION: 'Modifier des appareils',
  ESSENTIAL_USERS: 'Utilisateurs Essential',
  BUSINESS_USERS: 'Utilisateurs Business',
  POWER_USERS: 'Grands utilisateurs',
  N_A: 'Non disponible'
}
