export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'Ne peut pas décrypter les données du système de comptes',
  PHONE_TYPES: 'Types de téléphone',
  IMAGINE_A_BETTER_WAY: 'Un outil performant pour',
  OF_DOING_THINGS: 'travailler efficacement.',
  GET_STARTED: 'Commencer',
  PURCHASE: 'Acheter',
  DOWNLOADS_AND_EXTENSIONS: 'Téléchargements et extensions',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: 'Tirez le meilleur parti de vos produits Zang grâce à ces extensions.',
  ALL: 'Toutes',
  REFERRAL_AGENT: 'Agent référent',
  SALES_AGENT: 'Agent commercial',
  CART: 'Panier',
  PARTNER_PROGRAMS: 'Programmes partenaires',
  HOME: 'Accueil',
  MANAGE_CREDIT_CARDS: 'Gestion des cartes de crédit',
  MANAGE_PAYMENT_OPTIONS: 'Gérer les options de paiement',
  MANAGE_BILLING_ACCOUNT: 'Gérer le compte de facturation',
  LIMIT: "Limite",
  MY_PROFILE: 'Mon profil',
  MY_SETTINGS: 'Mes paramètres',
  MY_PARTNER_PORTAL: 'Mon portail partenaire',
  CLEAR_ZANG_OFFICE: 'Effacer les paramètres existants de Zang Office',
  CLEAR_ZANG_SPACES: 'Effacer les paramètres existants de Zang Spaces',
  FEATURE_BREAKDOWN: 'Détails des fonctionnalités',
  PLAN_BREAKDOWN: 'Détails du forfait', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'Le téléphone professionnel dont vous avez besoin, à un prix que vous allez adorer',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Imaginez tout ce que vous pouvez entreprendre avec Zang Spaces',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'Une remise de 50 % sera appliquée au montant total après validation',
  HURRICANE_HARVEY_MESSAGE: 'Avaya et Zang souhaitent aider les entreprises affectées par la tempête tropicale Harvey et potentiellement par la tempête tropicale Irma. Les entreprises situées dans les États suivants : Texas, Louisiane, Floride, Alabama, Géorgie, Caroline du Nord, Caroline du Sud, Tennessee et Mississippi et qui ont été touchées peuvent immédiatement <b>recevoir GRATUITEMENT 3 mois de Zang Office</b> et <b>Zang Spaces</b>.',
  LEARN_MORE: 'En savoir plus',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ EST DÉSORMAIS DISPONIBLE',
  NEW: 'NOUVEAU !',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Profitez des meilleures fonctionnalités de Zang Spaces grâce ce téléphone de collaboration vocal, vidéo et de conversation tout en verre et facile à utiliser.',
  LOG_IN: 'Connexion',
  SIGN_UP: 'S\'inscrire',
  SIGN_OUT: 'Se déconnecter',
  SIGN_IN: 'Se connecter', //login to the system, connect
  ADMINISTRATION: 'Administration',
  PRODUCTS: 'Produits',
  ORDERS: 'Commandes',
  PAGES: 'Pages',
  CUSTOMERS: 'Clients',
  USERS: 'Utilisateurs',
  PLANS: 'Forfaits',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'Statistiques d\'appel',
  CDR_CHECKS: 'Contrôles des statistiques d\'appel',
  PARTNERS: 'Partenaires',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'Il semble que vous avez déjà acheté Zang Office. Vous ne pouvez plus passer de commandes Zang Office.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'Il semblerait que vous ayez déjà acheté Avaya Cloud pour cette société. Veuillez sélectionner une autre entreprise.',
  PARTNER_CONNECTIONS: 'Connexions des partenaires',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'Une erreur est survenue lors du passage de votre commande. Veuillez contacter l\'assistance Zang ({SUPPORT_EMAIL}) pour plus d\'informations.',
  APPLICATION_GENERAL_FATAL_ERROR: 'Une erreur est survenue lors de l\'envoi de votre demande. Veuillez contacter l\'assistance Zang ({SUPPORT_EMAIL}) pour plus d\'informations.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Sélectionnez au moins un type d\'utilisateur pour continuer.',
  BACK: 'Retour',
  SAVE_CHANGES: 'Enregistrer les modifications',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: 'Êtes-vous sûr de vouloir continuer ?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'Vous possédez un bon de {PLACEHOLDER} à dépenser pour l\'achat de n\'importe quel appareil. Ce bon sera perdu une fois votre commande envoyée.',
  JUST_A_REMINDER: 'Un simple rappel',
  LAST_CHANCE: 'DERNIÈRE CHANCE',
  IM_GOOD_PLACE_MY_ORDER: 'C\'est bon, passer ma commande',
  BUY_MORE_DEVICES: 'Acheter des appareils supplémentaires',
  YES_PLACE_MY_ORDER: 'Oui, passer ma commande',
  NO_THANKS: 'Non merci.',
  YES: 'Oui',
  ABOUT_US: 'À propos de Zang',
  NEWS_AND_PRESS: 'Actualité et médias',
  CARREERS: 'Emplois',
  CONTACT_US: 'Contactez-nous',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Merci d\'avoir choisi notre boutique. Les détails de votre commande figurent ci-dessous.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: 'Veuillez contacter <a href="mailto:{EMAIL}">{EMAIL}</a> pour obtenir cette information',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'Nos équipes dédiées au service de la réussite des clients et au support technique vous contacteront lorsque votre système sera prêt. <br/><br/><b>Veuillez noter que la configuration de votre système peut prendre jusqu\'à une heure.</b>',
  QUESTION_CUSTOMER_SERVICE: 'Pour toutes questions éventuelles, veuillez nous contacter par e-mail à l\'adresse suivante : <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  BLOG: 'Blog',
  FAQS: 'FAQ',
  DOCUMENTATION: 'Documents',
  TERMS_OF_SERVICE: 'Les conditions de service',
  HELP: 'Aide',
  PRIVACY_STATEMENT: 'Déclaration de confidentialité',
  GENERAL_PRIVACY_STATEMENT: 'Déclaration générale de confidentialité',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: 'Conditions de service générales - Solutions cloud d\'Avaya',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. Tous droits réservés.',
  PROCESSING: 'Traitement en cours',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Veuillez patienter. Ce processus peut prendre quelques instants',
  OPEN_IN_A_NEW_TAB: 'Ouvrir dans un nouvel onglet',
  GOT_IT: 'J\'ai compris.',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' Cette action entraînera les résultats suivants :',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Supprimer l\'abonnement mensuel pour ce forfait',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Désactiver tous les comptes sur l\'ensemble des systèmes tiers',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Placer le statut de ce forfait sur DÉSACTIVER',
  LAST_ACTION_STEPS: 'Dernières étapes',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'Les extensions sont disponibles à l\'achat sur le portail d\'administration Zang Office une fois le compte créé.',
  TYPE: 'Type',
  ADMIN: 'Administrateur',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'Cet utilisateur sera configuré comme contact principal/de facturation pour le compte d\'entreprise. Il peut être changé à tout moment sur le portail d\'administration Zang Office.',
  DESCRIPTION: 'Description',
  SUCCESS: 'Réussite',
  REQUEST_CANCELATION: 'Demander une annulation',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Nous sommes navrés d\'apprendre que vous souhaitez partir.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Veuillez remplir le formulaire ci-dessous afin de lancer la procédure d\'annulation. Un membre de notre équipe au service de la réussite des clients examinera et donnera suite à votre demande sous un à deux jours ouvrables afin de faciliter la procédure.',
  YOUR_NAME: 'Votre nom',
  COMPANY: 'Entreprise',
  SERVICE: 'Service',
  REASON_FOR_CANCELING: 'Raison de l\'annulation',
  SUBMIT: 'Envoyer',
  EXIT: 'Quitter',
  REQUEST_SUBMITTED: 'Votre demande a été envoyée.',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Un membre de notre équipe au service de la réussite des clients examinera et donnera suite à votre demande sous un à deux jours ouvrables afin de faciliter la procédure.',
  DATE: 'Date',
  PRODUCT: 'Produit',
  USER: 'Utilisateur',
  STATUS: 'Statut',
  ACTIONS: 'Actions',
  VIEW_DETAILS: 'Afficher les informations',
  DISABLE: 'Désactiver',
  ENABLE: 'Activer',
  CANCEL: 'Annuler',
  PLAN_DETAILS: 'Détail du forfait',
  SUMMARY: 'Résumé',
  QUANTITIES: 'Quantités',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*Le prix total comprend le prix des fonctionnalités de votre forfait',
  TOTAL: 'Total',
  BILLED: 'Facturé',
  PLAN_INFORMATION: 'Informations sur le forfait',
  UPDATE_PLAN: 'Mise à jour du forfait',
  ADMIN_ACTIONS: 'Actions de l\'administrateur',
  NAME_ON_CREDIT_CARD: 'Nom figurant sur la carte de crédit',
  CREDIT_CARD_BRAND: 'Type de carte de crédit',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'MasterCard',
  CREDIT_CARD_NUMBER: 'Numéro de carte de crédit',
  EXPIRATION: 'Expiration',
  MONTH: 'Mois',
  YEAR: 'Année',
  SECURITY_CODE: 'Cryptogramme visuel',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'Code figurant au dos de votre carte de crédit',
  BACK_TO_CHECKOUT: 'Retour à la page de paiement',
  NO_ORDERS_FOUND: 'Aucune commande trouvée',
  ADD: 'Ajouter',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Utilisez le formulaire ci-dessus pour ajouter une nouvelle carte de crédit. Veillez à remplir tous les champs',
  NUMBER: 'Numéro',
  EXPIRES: 'Expire le',
  DELETE: 'Supprimer',
  ITEM_DETAILS: 'Informations sur l\'article',
  FEE: 'Prix',
  ITEMS: 'Articles',
  SEARCH_BY_CONFIRMATION: 'Rechercher par confirmation',
  CONFIRMATION: 'Confirmation',
  CHECKOUT_STATUS: 'Statut du paiement',
  ORDER_STATUS_PROCESS: 'Processus du statut de la commande',
  CREATED_ON: 'Créée le',
  ORDER_SUMMARY: 'Récapitulatif de la commande',
  APPROVED: 'Validé', //example: partner application approved
  REJECTED: 'Rejeté', //example: partner application rejected
  APPROVE: 'Approuver', //example: partner application approved
  REJECT: 'Rejeter', //example: partner application rejected
  PENDING: 'En attente', //example: partner application pending
  EDIT: 'Modifier',
  ONE_TIME_FEE: 'Paiement unique',
  SUB_TOTAL: 'Sous-total',
  TAXES: 'Taxes',
  CHANGES: 'Modifications',
  CREATE_A_QUOTE: 'Créer un devis',
  EXTRA_INFORMATION: 'Informations supplémentaires',
  THANK_YOU_FOR_YOUR_ORDER: 'Nous vous remercions pour votre commande',
  ORDER_CONFIRMATION: 'Confirmation de la commande',
  INVALID_ORDER: 'Commande non valide',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'Ne vous inquiétez pas, vous la recevrez également par e-mail.',
  HELLO: 'Bonjour',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Merci d\'avoir choisi notre boutique. Nous vous enverrons une confirmation une fois vos articles expédiés. Les détails de votre commande figurent ci-dessous.',
  ACCOUNT_INFORMATION: 'Informations de compte',
  BILLING_INFORMATION: 'Données de facturation',
  SHIPPING_INFORMATION: 'Informations sur la livraison',
  NAME: 'Nom',
  EMAIL: 'E-mail',
  SEARCH: 'Rechercher',
  CLEAR: 'Effacer',
  PARTNER: 'Partenaire',
  NO_PARTNERS_FOUND: 'Aucun partenaire n\'a été trouvé',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'Une connexion partenaire est créée lorsqu\'un client accède à la boutique à partir d\'un lien personnel de partenaire.',
  CUSTOMER: 'Client',
  AGENT: 'Agent',
  NO_PARTNER_CONNECTIONS_FOUND: 'Aucune connexion partenaire n\'a été trouvée',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'J\'ai lu et j\'accepte ce qui suit',
  ZANG_PRIVACY_STATEMENT: 'Déclaration de confidentialité de Zang',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'Conditions de service du programme des agents',
  SUBMIT_APPLICATION: 'Envoyer la demande',
  SUBMITTING: 'Envoi en cours',
  SUBMITTING_YOUR_APPLICATION: 'Envoi de votre demande en cours',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'La confidentialité et la sécurité de l\'ensemble des informations bancaires sont assurées et soumises à nos conditions générales.',
  BANK_NAME: 'Nom de la banque',
  ADDRESS: 'Adresse',
  COUNTRY: 'Pays',
  SELECT_ONE: '- Sélectionnez -',
  STATE_PROVINCE: 'État/Province',
  CITY: 'Ville',
  ZIP_POSTAL_CODE: 'Code postal',
  ACCOUNT_NUMBER: 'Numéro de compte',
  BANK_NUMBER: 'Numéro de banque',
  TRANSIT_NUMBER: 'Numéro de routage',
  SWIFT_CODE: 'Code swift',
  TAX_REGISTRATION_NUMBER: 'Numéro d\'identification fiscale',
  SAVE_BANK_INFORMATION: 'Enregistrer les données bancaires',
  SAVING_BANK_INFORMATION: 'Enregistrement des données bancaires en cours',
  NO_CUSTOMERS_FOUND: 'Aucun client n\'a été trouvé',
  YOU_ARE_A: 'Vous êtes ',
  A_DISCOUNT_OF: 'Une remise de',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'sera appliquée au montant total après validation.',
  FIRST_NAME: 'Prénom',
  LAST_NAME: 'Nom',
  COMPANY_NAME: 'Nom de l\'entreprise',
  LEGAL_COMPANY_NAME: 'Dénomination sociale de l\'entreprise',
  PHONE_NUMBER: 'Numéro de téléphone',
  WEBSITE: 'Site Web',
  OPERATIONAL_ADDRESS: 'Adresse d\'exploitation',
  SAME_AS_ORGANIZATION_ADDRESS: 'Similaire à l\'adresse de l\'entreprise',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: 'Êtes-vous partenaire d\'Avaya ?',
  NO: 'Non',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Le cas échéant, saisissez votre identifiant de partenaire Avaya',
  MY_PARTNER_PORTAL: 'Mon portail partenaire',
  THANK_YOU_FOR_APPLYING: 'merci pour votre demande !',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'Il ne vous reste plus qu\'une étape. Pour terminer votre demande d\'agent commercial, suivez le lien ci-dessous et répondez à toutes les questions.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' Sinon, veuillez fournir ',
  PLEASE_GIVE: 'Veuillez fournir',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'Si vous êtes un partenaire Avaya, veuillez ne PAS suivre le lien ci-dessous. <br />Nous examinons actuellement votre ID de partenaire et vous contacterons rapidement.',
  BUSINESS: 'jours',
  DAYS: 'ouvrables',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'à l\'équipe de direction pour que celle-ci examine votre demande.<br /> Entre-temps, vous pouvez envoyer toutes vos questions à',
  COMPLETE_MY_APPLICATION: 'Terminer ma demande',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'Nous avons examiné votre demande. Malheureusement, à ce jour, nous considérons que votre profil ne correspond pas à notre programme. Il ne s\'agit probablement que d\'un problème mineur, mais nous ne pouvons pas faire avancer notre partenariat tant que celui-ci n\'est pas réglé. Nous comprenons votre frustration. Soyez assuré que nous mettrons tout en œuvre pour trouver une solution. Nous vous contacterons dès que nous aurons de plus amples informations. D\'ici là, n\'hésitez pas à contacter',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'pour poser vos questions concernant cette procédure.',
  CONGRATULATIONS: 'Félicitations !',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: 'Vous êtes désormais un agent Zang !',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Commencez par partager votre lien personnel avec vos collaborateurs',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'pour qu\'ils puissent bénéficier de cet outil performant.',
  CHANGE_STATUS: 'Modifier le statut',
  AGENT_DETAILS: 'Informations sur l\'agent',
  BANK_INFORMATION: 'Données bancaires',
  THIS_ORDER_WAS_PLACED_BY_A: 'Cette commande a été passée par un',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'a été appliquée au montant total',
  REFERRALS: 'Référents',
  SALES: 'Ventes',
  FOUND: 'Découvertes',
  HOW_IT_WORKS: 'Fonctionnement',
  WHAT_YOU_GET: 'Vos avantages',
  SUPPORT: 'Assistance',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'Quel programme est le plus adapté à mes besoins ?',
  WHY_JOIN: 'Pourquoi rejoindre l\'équipe ?',
  QUOTE: 'Devis',
  PRINT_THIS_QUOTE: 'Imprimer ce devis',
  CLOSE_THIS_WINDOW: 'Fermer cette fenêtre',
  SEARCH_BY_PLAN: 'Recherche par forfait',
  ACCESS_LEVEL: 'Niveau d\'accès',
  DISPLAY_NAME: 'Nom d\'affichage',
  INDUSTRY: 'Industrie',
  COMPANY_INDUSTRY: 'Entreprise',
  CONTACT_PHONE_NUMBER: 'Numéro de téléphone du contact',
  EMAIL_ADDRESS: 'Adresse e-mail',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Oui, je souhaite recevoir des e-mails concernant l\'actualité, les applications, les offres et les événements Zang.',
  INFORMATION: 'Informations',
  ORDER_HISTORY: 'Historique des commandes',
  FILTER: 'Filtrer',
  ACCOUNT: 'Compte',
  AMOUNT_CHARGED: 'Montant facturé',
  DETAILS: 'Détails',
  NO_RECORDS_FOUND: 'Aucun enregistrement trouvé',
  CALL_LOGS: 'Journaux des appels',
  EXPORT: 'Exportation',
  CALLER_NAME: 'Nom d\'appelant',
  DIALED_NUMBER: 'Numéro composé',
  DURATION_SEC: 'Durée (s)',
  COST: 'Coût',
  PAYMENT_METHOD: 'Mode de paiement',
  PURCHASE_ORDER: 'Bon de commande',
  PURCHASE_ORDERS: 'Bons de commande',
  CREDIT_CARD: 'Carte de crédit',
  SHIPPING_ADDRESS: 'Adresse de livraison',
  SAME_AS_BILLING_ADDRESS: 'Similaire à l\'adresse de facturation',
  SAME_AS_SHIPPING_ADDRESS: 'Identique à l\'adresse de livraison',
  OTHER: 'Autre',
  SHIPPING_OPTIONS: 'Options de livraison',
  FREE_SHIPPING: 'Livraison GRATUITE',
  ADDITIONAL_NOTES: 'Notes complémentaires',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'J\'ai lu et j\'accepte ce qui suit :',
  EMERGENCY_911_SERVICE_NOTICE: 'Informations sur les services d\'urgence 911',
  PLACE_MY_ORDER: 'Passer ma commande',
  CLEAR_MY_ORDER: 'Effacer ma commande',
  PLACING_YOUR_ORDER: 'Passer votre commande',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'Veuillez patienter. Ce processus peut prendre jusqu\'à 1 minute.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'Ce processus peut prendre un certain temps. Merci pour votre patience. Pour être sûr que votre commande ne soit pas interrompue, veuillez éviter de fermer cette fenêtre, cliquer sur retour ou rafraîchir la page.',
  YOUR_NEW_NUMBER: 'Votre nouveau numéro',
  NO_NUMBER_SELECTED: 'Aucun numéro sélectionné',
  WELL_THAT_WAS_EASY: 'Rien de plus simple !',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'Plus que deux petites étapes.',
  NEXT: 'Suivant',
  TITLE: 'Titre',
  SUB_TITLE: 'Sous-titre',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Rechercher par indicatif régional… (États-Unis et Canada uniquement)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: 'Entrez l\'indicatif régional... (uniquement pour les États-Unis)',
  SELECT_A_PREFIX: 'Sélectionner un préfixe',
  PICK_THIS_NUMBER: 'Choisir ce numéro',
  DEVICES: 'Appareils',
  BILLING: 'Facturation',
  CHANGE: 'Modifier',
  USER_INFO: 'Informations sur l\'utilisateur',
  USE_MY_INFORMATION: 'Utiliser mes informations',
  SELECT_YOUR_DEVICES: 'Sélectionnez vos appareils',
  MONTHLY_FEE: 'Frais mensuels',
  ANNUAL_FEE: 'Frais annuels',
  TWO_YEAR_FEE: 'Frais pour 2 ans',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Chaque forfait Zang Office doit comporter au moins un utilisateur standard OU avancé.',
  CHECKOUT: 'Paiement',
  MINE: 'Ma commande',
  REMOVE_THIS_USER: 'Supprimer cet utilisateur',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Sélectionner un appareil pour cet utilisateur',
  ADD_ANOTHER: 'Ajouter un autre appareil',
  GET_STARTED_WITH_ZANG_OFFICE: 'Commencer à utiliser Zang Office',
  BUNDLE: 'offre groupée',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Inscrivez-vous pour une durée d\'un an et recevez',
  OFF: 'INACTIF',
  EACH_USER: 'chaque utilisateur',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'Pour modifier les quantités d\'utilisateur, vous devez supprimer votre commande ou accéder à l\'étape « appareils ».',
  EVERY_TWO_YEARS: 'Tous les 2 ans',
  YOU_VE_SAVED: 'Vous avez enregistré',
  INCLUDED: 'Inclus',
  ADDONS: 'Extensions',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Personnalisez chaque utilisateur en fonction de leurs préférences.',
  UNITS_PER: 'Unités par',
  TALK_ANYWERE_ANYTIME: 'Communiquez partout, quand vous le voulez !',
  DOWNLOAD_FOR_MAC: 'Téléchargement pour MAC',
  DOWNLOAD_FOR_WINDOWS: 'Téléchargement pour Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Merci d\'avoir choisi Zang Office ! Consultez votre commande ici.',
  CONTINUE_WITH_YOUR_PURCHASE: 'Continuez vos achats.',
  GET_STARTED_TODAY: 'Commencez dès aujourd\'hui.',
  FEATURES: 'Fonctions',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Voici quelques renseignements supplémentaires.',
  BASIC: 'Basique',
  STANDARD: 'Standard',
  POWER: 'Avancé',
  RATE_MIN_STARTING_FROM: 'Tarif/min, à partir de* :',
  RATE_MIN_STARTING_FROM_1: 'Tarif/min, à partir de',
  LONG_DISTANCE: 'International (longue distance)',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'Tarifs pour l\'international (longue distance)',
  COMMON_DESTINATIONS: 'Destinations fréquentes',
  BEST_DEAL: 'meilleure offre',
  PER_ACTIVE_USER_PER_MONTH: 'Par utilisateur actif et par mois.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'en fonction de l\'abonnement annuel',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'Facturation selon le forfait choisi.',
  MONTHLY: 'Mensuel',
  ANNUALLY: 'Annuel',
  BILLED_ANNUALY: 'Facturation annuelle',
  BILLED_EVERY_TWO_YEARS: 'Facturation tous les 2 ans',
  CONFIGURE_YOUR_ADDONS: 'Configurez vos extensions',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Sélectionnez une quantité pour chacune des extensions disponibles.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'La quantité maximale pour cette extension est',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'Cette extension est uniquement disponible pour',
  BILLING_AND_SHIPPING: 'Facturation et livraison',
  BILLING: 'Facturation',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'Ceci sera votre nom de compte Zang Office.',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'Ce sera votre nom de compte Avaya Cloud.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Si vous souhaitez utiliser votre numéro existant ou un numéro SVA en tant que numéro Zang Office, nous tâcherons de trouver un numéro local à associer à l\'extension utilisée dans ce champ.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Tout est possible avec Spaces',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'L\'outil de collaboration en équipe dans le Cloud dont vous avez toujours rêvé.',
  YOUR_CURRENT_PURCHASES: 'Vos achats courants',
  PURCHASED_ON: 'Acheté le',
  PLAN_NUMBER: 'Référence du forfait',
  UPDATE: 'Mettre à jour',
  UPDATED: 'Mis à jour',
  OR: 'ou',
  MAKE_A_NEW_PURCHASE: 'Effectuer un nouvel achat',
  FEATURES_AND_ADDONS: 'Fonctionnalités et extensions',
  FREE: 'GRATUIT',
  PLUS: 'PLUS',
  BUSINESS: 'AVANCÉ',
  VIEW: 'Afficher',
  TEAM: 'Équipe',
  LETS_SETUP_YOUR_TEAM: 'Passons à la configuration de votre équipe',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Sélectionnez simplement le type d\'équipe que vous souhaitez créer et configurez votre environnement privé.',
  COMPANY_TYPE: 'Type d\'entreprise',
  DOMAIN: 'Domaine',
  NO_TEAM_IS_SETUP_YET: 'Aucune équipe n\'a été configurée',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'Ne pas me configurer d\'équipe',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Achetez des Zang Spaces qui vous seront exclusivement destinés.',
  CHOOSE_AN_EXISTING_COMPANY: 'Sélectionnez une entreprise existante',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Sélectionnez l\'une des entreprises pour lesquelles vous êtes l\'administrateur actuel.',
  CREATE_A_NEW_TEAM: 'Créer une nouvelle équipe',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Fournissez un nom d\'équipe et de domaine.',
  NO_DOMAIN_IS_CONFIGURED: 'Aucun domaine n\'a été configuré.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Veuillez fournir un nom de domaine (par ex. \'zang.io\')',
  CHECK: 'Vérifier',
  TEAM_DOMAIN: 'Domaine de l\'équipe (par ex. \'zang.io\')',
  TEAM_NAME: 'Nom de l\'équipe (par ex. \'Zang\')',
  OK: 'OK',
  ZANG_SPACES_ADMIN_CONSOLE: 'Console d\'administration de Zang Spaces',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'Vous pouvez modifier les valeurs ci-dessous pour effectuer la mise à jour de votre forfait',
  CHARGABLE_USERS: 'Utilisateurs facturables',
  TOTAL_USERS: 'Nombre total d\'utilisateurs',
  CURRENT_PRICE: 'Prix actuel',
  SAVE: 'Enregistrer',
  SAVE_CHANGES_AND_UPDATE_PLAN: 'Voulez-vous enregistrer les modifications et effectuer la mise à jour de votre forfait ?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Sélectionnez au moins un type d\'utilisateur pour continuer',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Vous achetez Zang Spaces pour',
  BUY_NOW: 'Acheter maintenant',
  SELECT: "Sélectionner",
  UP_TO: 'Jusqu\'à',
  NO_PURCHASE_REQUIRED: 'aucun achat requis',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'Aucune facturation et aucun engagement.',
  SIGN_UP_FOR_FREE: 'Inscrivez-vous GRATUITEMENT !',
  ONE_YEAR_PLAN: 'Forfait 1 an',
  MONTHLY_PLAN: 'Forfait mensuel',
  TWO_YEAR_PLAN: 'Forfait 2 ans',
  MONTHS: 'Mois',
  ZANG_OFFICE_ACCOUNT_NAME: 'Nom de compte Zang Office',
  ZANG_OFFICE_PLAN_NUMBER: 'Référence du forfait Zang Office',
  TEMPORARY_NUMBER: 'Numéro temporaire',
  START_SETTING_UP_ZANG_OFFICE: 'Configuration de Zang Office.',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'Si vous transférez un numéro existant vers votre solution Zang Office, envoyez un e-mail à l\'adresse zosupport@zang.io en y joignant un formulaire d\'autorisation de portabilité du numéro local ainsi qu\'une copie de votre dernière facture de téléphone. Si vous transférez un numéro SVA, envoyez également un formulaire RODAA par e-mail. Notez que le délai des transferts peut aller jusqu\'à 10 jours ouvrables.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'Une erreur est survenue lors de l\'achat/activation de vos numéros Zang Office. Cliquez sur \'Configuration de Zang Office\' to activate/buy your numbers manually. In case you\'ve chosen to use your existing number, the porting process will not be affected.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'Veuillez noter : si vous transférez un numéro existant vers votre compte Zang Office, vous devrez remplir ce <a href="{LNP_FORM_LINK}" target="blank">formulaire d\'autorisation de portabilité du numéro local</a> et l\'envoyer par e-mail en y joignant une copie de votre dernière facture de téléphone. Si vous transférez un numéro SVA, veuillez également remplir ce <a href="{RODAA_LINK}" target="blank">formulaire RODAA</a>. Veuillez envoyer tous les documents demandés à <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. Le processus de transfert du numéro de téléphone peut prendre jusqu\'à 10 jours ouvrables.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Veuillez noter que le processus de transfert du numéro de téléphone peut prendre jusqu\'à 10 jours ouvrables. En attendant, nous vous fournirons un numéro de téléphone temporaire à utiliser sur votre compte.',
  PLAN_STATUS: 'Statut du forfait',
  PLAN_ID: 'ID du forfait',
  SUBSCRIPTION_ID: 'ID d\'abonnement',
  STRIPE_PLAN_ID: 'ID de forfait Stripe',
  ACCOUNT_ID: 'ID du compte',
  START_SETTING_UP_ZANG_SPACES: 'Configuration de Zang Spaces',
  COMPANY_DOMAIN: 'Domaine d\'entreprise',
  THIS_FIELD_IS_REQUIRED: 'Ce champ est obligatoire.',
  PLEASE_ANSWER_THIS_QUESTION: 'Veuillez répondre à cette question.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Saisissez votre identifiant de partenaire Avaya.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Veuillez lire et accepter la déclaration de confidentialité pour continuer.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Veuillez lire et accepter les conditions de service du programme des agents pour continuer.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'Cet identifiant de partenaire Avaya est déjà utilisé.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'Ce numéro d\'identification fiscale est déjà utilisé.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'Cet identifiant de partenaire Avaya n\'est pas valide.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'La quantité doit être représentée par un nombre positif',
  ORDER_COMPLETE: 'Commande terminée !',
  PLEASE_TRY_AGAIN: 'Veuillez réessayer',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Veuillez sélectionner au moins une valeur positive',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'La mise à jour est toujours en cours. Veuillez réessayer ultérieurement.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'Il ne peut pas y avoir plus d\'un utilisateur sur une licence personnelle. Pour effectuer une mise à niveau ou passer à une version antérieure, modifiez les quantités en conséquence.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'Vous n\'avez pas accès à ce compte.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Votre forfait actuel ne vous permet pas de réduire le nombre d\'utilisateurs en dessous de la quantité d\'origine. Si vous souhaitez modifier cela, contactez-nous à l\'adresse customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'Une erreur est survenue lors du passage de votre commande. Vérifiez que toutes les valeurs saisies dans les champs sont correctes. Si l\'erreur persiste, contactez l\'assistance Zang pour plus d\'informations',

  USE_EXISTING_NUMBER: 'Utiliser le numéro existant',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Sélectionnez pour associer votre numéro existant à votre forfait',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Présélectionnez un numéro SVA',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Sélectionnez pour ajouter votre propre numéro SVA à votre forfait',
  FIND_A_LOCAL_NUMBER: 'Trouver un numéro local',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Choisissez un numéro dans liste des numéros locaux de votre région afin de l\'ajouter à votre forfait',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: 'Sélectionnez cette option pour ajouter un numéro local à votre forfait',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: 'Recherchez par indicatif régional pour les numéros de téléphone disponibles',
  SEARCH_AVAILABLE_PHONE_NUMBERS: 'Recherchez les numéros de téléphone disponibles',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: 'Entrez le numéro existant que vous prévoyez de transférer',


  ZANG_OFFICE_PHONE_APP: 'Appli de téléphone Zang Office',
  ZANG_OFFICE_SOFTPHONE: 'Téléphone logiciel Zang Office',
  ZANG_OFFICE_PHONE_APPLICATION: 'Application de téléphone Zang Office',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Le téléphone logiciel Zang Office comprend toutes les fonctionnalités de communication dont vous avez besoin sur votre ordinateur de bureau ou votre appareil mobile. Bénéficiez de l\'ensemble des fonctionnalités avantageuses de Zang Office sans vous ruiner : le téléphone logiciel est fourni gratuitement avec votre abonnement Zang Office !',
  E129_SIP_DESK_PHONE: 'Téléphone de bureau SIP E129',
  STANDARD_PHONE: 'Téléphone standard',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Le téléphone de bureau SIP E129 d\'Avaya est un outil très fonctionnel qui comprend toutes les fonctionnalités clés de gestion des appels que vous recherchez. Ce téléphone permet à ses utilisateurs de transférer, désactiver le son, renvoyer et placer des appels en attente ainsi que de démarrer des conférences ad hoc à l\'aide d\'une simple touche. Son haut-parleur duplex intégral permet de communiquer en mains libres et son port d\'alimentation électrique par câble Ethernet offre une connexion pratique au réseau. Le téléphone de bureau SIP E129 d\'Avaya est un outil accessible, agréable à utiliser et qui offre des fonctionnalités adaptées. L\'adaptateur secteur est inclus.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Collaborez à l\'aide d\'un appareil de bureau dédié innovant et tout en verre. Utilisez les applications vocales, de conversation et de collaboration par le biais de connexions à une touche. Vous ne subissez aucune pause ni aucun temps d\'arrêt. Et la gestion de plusieurs appareils pour la collaboration n\'est pas nécessaire. Expériences personnalisées et uniques de collaboration au sein de vos flux de travail et processus d\'entreprise. Cet appareil puissant et personnalisable vous offre les avantages d\'un téléphone de bureau et la flexibilité d\'une plateforme d\'applications.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'Téléphone de conférence B179',
  CONFERENCE_PHONE: 'Téléphone de conférence',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Particulièrement adapté aux salles de réunion et aux salles de conférence accueillant plus de 10 personnes, le téléphone de conférence B179 contribue à la productivité et à la collaboration des employés. Il s\'agit d\'un outil haute performance polyvalent qui s\'associe aux solutions existantes et qui peut être facilement redéployé en fonction de la croissance de l\'entreprise et des besoins. L\'adaptateur secteur est inclus.',
  PLAN: 'Forfait',
  REDIRECTING: 'Redirection',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Vérifiez que des valeurs valides ont été saisies dans les champs',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Chaque forfait Zang Office doit comporter au moins un type d\'utilisateur. Veuillez revenir à l\'étape de sélection des appareils et modifier votre configuration.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Il semblerait que vous n\'ayez pas sélectionné de numéro pour votre compte Zang Office. Veuillez revenir à l\'étape de sélection d\'un numéro pour en choisir un.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'Ce nom de compte Zang Office est déjà utilisé. Veuillez en choisir un autre',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'Le numéro Zang Office que vous avez sélectionné a déjà été acheté par un autre client. Veuillez revenir à l\'étape de sélection d\'un numéro et sélectionner un autre numéro.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Choisissez l\'option mensuelle sans engagement et obtenez les <span class="text-400">30 PREMIERS JOURS GRATUITEMENT</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'ou sélectionnez un forfait annuel pour obtenir de meilleures offres et un',
  FREE_PHONE: 'TÉLÉPHONE GRATUIT',
  DISCOUNT: 'remise',
  DISCOUNTED_PHONE: 'téléphone avec remise',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'de remise sur la valeur totale de vos achats de téléphones',
  LIMITED_TIME_OFFER: 'Offre à durée limitée',
  PROMOTION: 'Promotion',
  ZANG_SPACES_PROMOTION: 'Promotion Zang Spaces',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Poursuivez vers la sélection du numéro de téléphone',
  DURATION: 'Durée',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'Félicitations ! Vous disposez d\'un bon d\'achat de <strong>{amount}</strong> à appliquer au montant total de votre commande d\'appareils !',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'Toutes les remises applicables seront incluses dans votre récapitulatif de commande final.',
  SHIPPING_TYPE: 'Type de livraison',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'Le détail du suivi vous sera envoyé une fois que les articles auront quitté notre entrepôt',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Recevez un bon de {amount} par utilisateur applicable à l\'achat de tout appareil. Offre à durée limitée.',
  PARTNER_ORDERS: 'Commandes des partenaires',
  COMMISSION: 'Commission',

  ADDITIONAL_DEVICES: 'Appareils supplémentaires',
  NO_USER: 'Aucun utilisateur',
  QUANTITY: 'Quantité',
  BUY_DEVICES: 'Acheter des appareils',
  DEVICE: 'Appareil',
  PRICE: 'Prix',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'Veuillez taper au moins {chars} caractères pour rechercher un agent',
  NO_RESULTS_FOUND: 'Aucun résultat',
  RESULTS_COULD_NOT_BE_LOADED: 'Chargement des résultats impossible',
  CLEAR_SELECTION: 'Effacer la sélection',


  RESET_ALL_PURCHASES: 'Effacer tous les achats',
  LISTS: 'Listes',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Veuillez indiquer votre numéro de téléphone avant de créer un devis.',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Veuillez indiquer vos informations de facturation et de livraison avant de créer un devis.',
  CALCULATING_TAXES_PLEASE_WAIT: 'Calcul des taxes en cours. Veuillez patienter…',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Un problème est survenu au niveau de la carte de crédit que vous avez choisie.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Un problème est survenu au niveau de cette carte de crédit. Veuillez en utiliser une autre',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'Une erreur est survenue lors de la facturation de votre commande. Veuillez choisir une autre carte de crédit',
  INVALID_CREDIT_CARD: 'Carte de crédit non valide',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: 'Le {address_type} ne correspond pas aux coordonnées liées à la carte bancaire',
  INVALID_SECURITY_CODE: 'Code de sécurité (cvc) non valide',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Toutes les remises applicables et offres promotionnelles ont été appliquées à cette facture',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'Nous n\'avons pas pu créer votre compte client. Veuillez réessayer',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Nous n\'avons pas pu créer votre carte de crédit. Veuillez réessayer',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Cette carte de crédit est utilisée pour un abonnement récurrent.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Erreur dans la configuration par défaut de cette carte de crédit.',
  DEFAULT: 'Par défaut',
  SET_DEFAULT: 'Configurer par défaut',
  SALES_FORCE_QUOTE_ID: 'ID de devis Salesforce',
  SALES_FORCE_ORDER_ID: 'ID de commande Salesforce',
  SALES_FORCE_OPPORTUNITY_ID: 'ID de l\'offre Salesforce',
  SALES_FORCE_CONTACT_ID: 'ID de contact Salesforce',
  SALES_FORCE_CONTRACT_ID: 'ID de contrat Salesforce',
  SALES_FORCE_ACCOUNT_ID: 'ID de compte Salesforce',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Ajouter un appareil, tout simplement',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Il vous suffit d’\'Ajouter un appareil\' et de le connecter à un utilisateur.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Acheter des appareils supplémentaires pour votre compte Zang Office',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'Oups ! Un problème est survenu au niveau de votre commande. Actualisez la page, supprimez votre commande et recommencez.',
  CREATE_A_NEW_COMPANY: 'Créer une nouvelle entreprise',
  ADD_A_NEW_COMPANY: 'Ajouter une nouvelle entreprise',
  PARTNER_DETAILS: 'Coordonnées du partenaire',
  AGENTS: 'Agents',
  PARTNER_PORTAL: 'Portail partenaire',
  AGENT: 'Agent',
  AGENT_PORTAL: 'Portail agent',
  NO_AGENTS_FOUND: 'Aucun agent trouvé',
  NO_AGENT: 'Aucun agent',
  RELATION: 'Relation',
  OWNER: 'Propriétaire',
  ADMIN: 'Administrateur',
  MANAGER: 'Gestionnaire',
  EMPLOYEE: 'Employé',
  ACTIVE: 'Activé',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: 'Veuillez vous adresser à l\'un des partenaires auxquels vous êtes associé',
  APPLIED_ON: 'Appliqué le',
  JOIN_A_PARTNER: 'Contacter un partenaire',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'Il ne vous reste que quelques étapes avant de contacter <b>{COMPANY_NAME}</b>',
  JOIN_PLACEHOLDER_NOW: 'Rejoindre {COMPANY_NAME} dès maintenant',
  UPDATE_AGENT_INFO: 'Mettre à jour les informations de l\'agent',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Commencez avec les solutions cloud d\'Avaya<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'En collaboration avec Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'Une solution de collaboration simple, puissante et unifiée',
  IP_OFFICE_DONT_PAY_TILL: 'Ne payez pas avant le 15 avril 2018 !',
  LOGIN: 'Connexion',
  DISCOVER: 'Découvrir',
  SOLUTIONS: 'Solutions',
  SERVICES: 'Services',
  INDUSTRIES: 'Secteurs',
  CASE_STUDIES: 'Études de cas',
  PROGRAMS_AND_PROMOTIONS: 'Programmes et promotions',
  AUTHENTIC_AVAYA: 'L\'authenticité Avaya',
  PERSPECTIVES: 'Perspectives',
  AVAYA_CONNECTED_BLOG: 'Blog Avaya Connected',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: 'Recherche de solutions',
  INFO_FOR: 'Informations pour',
  DEVELOPERS: 'Développeurs',
  CHANNEL_PARTNERS: 'Partenaires revendeurs',
  TECHNOLOGY_PARTNERS: 'Partenaires technologiques',
  CONSULTANTS: 'Consultants',
  INVESTORS: 'Investisseurs',
  MEDIA_ANALYSTS: 'Analystes médias',
  SUPPLIERS: 'Fournisseurs',
  CONNECT_WITH_US: 'Contactez-nous',
  FIND_A_CHANNEL_PARTNER: 'Trouver un partenaire revendeur',
  FIND_A_TECHNOLOGY_PARTNER: 'Trouver un partenaire technologique',
  EXECUTIVE_BRIEFING_CENTER: 'Centre d\'information exécutif',
  AVAYA_LEARNING_SERVICES: 'Services de formation Avaya',
  CONTACTS: 'Contacts',
  ABOUT_AVAYA: 'À propos d\'Avaya',
  EVENTS: 'Événements',
  NEWSROOM: 'Salle de presse',
  INVESTOR_RELATIONS: 'Relations avec les investisseurs',
  CORPORATE_RESPONSIBILITY: 'Responsabilité de l\'entreprise',
  OUR_COMPANY: 'Notre entreprise',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'Groupe international d\'utilisateurs Avaya - IAUG',
  CAREERS: 'Carrières',
  YOUR_PERSONAL_LINK: 'Votre lien personnel',
  SITEMAP: 'Plan du site',
  TERMS_OF_USE: 'Conditions d\'utilisation',
  PRIVACY: 'Confidentialité',
  COOKIES: 'Cookies',
  AVAYA_INVOICE: 'Facture',
  IP_OFFICE_ACCOUNT_NAME: 'Nom de compte Avaya Cloud',
  IP_OFFICE_PLAN_NUMBER: 'Référence du forfait Avaya Cloud',
  IP_OFFICE_PHONE_APPLICATION: 'Téléphone logiciel des solutions cloud d\'Avaya',
  IP_OFFICE_PHONE_DESCRIPTION: 'Le téléphone logiciel des solutions cloud d\'Avaya offre aux utilisateurs un accès simple à tous les canaux de communication dans une seule interface. Il vous permet de vous connecter à vos solutions cloud d\'Avaya tout en passant et en recevant des appels vocaux et vidéo à partir de votre poste de bureau depuis votre PC. Le téléphone logiciel est inclus gratuitement avec les solutions d\'abonnement utilisateur Avaya Cloud standard et avancé.',
  PLAN_MONTH_1_MONTH_1: 'Forfait mensuel (aucun crédit d\'appareil)',
  PLAN_YEAR_1_MONTH_1: 'Forfait 1 an | Facture mensuelle',
  PLAN_YEAR_1_YEAR_1: 'Forfait 1 an, facture totale réglée',
  PLAN_YEAR_2_MONTH_1: 'Forfait 2 ans | Facture mensuelle',
  PLAN_YEAR_2_YEAR_1: 'Forfait 2 ans | Facture annuelle',
  PLAN_YEAR_2_YEAR_2: 'Forfait 2 ans, facture totale réglée',
  PLAN_YEAR_3_MONTH_1: 'Forfait 3 ans | Facture mensuelle',
  PLAN_YEAR_3_YEAR_1: 'Forfait 3 ans | Facture annuelle',
  PLAN_YEAR_3_YEAR_3: 'Forfait 3 ans, facture totale réglée',
  PLAN_YEAR_5_MONTH_1: 'Forfait 5 ans | Facture mensuelle',
  ACCORDING_TO_PLAN: 'Selon le forfait',
  TOTAL_USER_PLAN_FEE: 'Total des frais du forfait de l\'utilisateur',
  HEALTHCARE_DENY_MESSAGE: 'Merci d\'avoir choisi Avaya Cloud comme solution, malheureusement nous ne sommes pas encore conformes à l\'HIPAA, et votre entreprise étant dans le domaine de la santé, nous ne pouvons donc pas vous proposer notre service. Nous vous tiendrons au courant lorsque nous aurons obtenu notre certification, et nous espérons que vous pourrez revenir à ce moment-là !  N\'hésitez pas à contacter <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a> si vous avez la moindre question.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Sélectionnez vos appareils de solutions cloud d\'Avaya<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Sélectionnez votre numéro de solutions cloud d\'Avaya<sup style="font-size:50%;vertical-align:middle;">™</sup> Number',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'Paramétrez vos utilisateurs et attribuez-leur des appareils.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Ajoutez un numéro de téléphone que vous souhaitez utiliser pour vos solutions cloud d\'Avaya.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'Attribuez un numéro de téléphone à votre solution.',
  INVITE_A_NEW_AGENT: 'Inviter un nouvel agent',
  I_WANT_TO_INVITE_A: 'Je souhaiterais inviter',
  CONTACT_EMAIL: 'Adresse e-mail du contact',
  CONTACT_NAME: 'Nom du contact',
  COMPANY_NAME: 'Nom de l\'entreprise',
  CONTACT: 'Contact',
  COMPANY_IS_INCORPORATED: 'L\'entreprise est incorporée',
  INDIVIDUAL: 'Particulier',
  INDIVIDUALS: 'Particuliers',
  SEND_INVITATION_EMAIL: 'Envoyer un e-mail d\'invitation',
  SENDING_INVITATION_EMAIL: 'Envoi de l\'e-mail d\'invitation...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: 'L\'invitation a été envoyée',
  ALL_FIELDS_ARE_REQUIRED: 'Tous les champs sont obligatoires',
  PARTNER_NOT_FOUND: 'Aucun partenaire n\'a été trouvé',
  SALE_AGENT_REGISTRATION: 'Inscription de l\'agent commercial',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: 'Il vous suffit de remplir le formulaire ci-dessous pour devenir agent commercial pour',
  VIEW: 'AFFICHER',
  COMPANIES: 'Entreprises',
  ADD_A_PARTNER: 'Ajouter un partenaire',
  ADD_PARTNER: 'Ajouter partenaire',
  PARTNERS_PERSONAL_LINK: 'Lien personnel du partenaire',
  MASTER_SALES_AGENT: 'Agent commercial principal',
  AVAYA_J129_LABEL: 'Téléphone IP J129',
  AVAYA_J129_DESCRIPTION: 'Disposez de toutes les fonctions d\'appel essentielles dans un téléphone SIP économique malgré la richesse de ses fonctionnalités. Ce combiné téléphonique dispose des fonctions les plus utilisées par les utilisateurs, quelle que soit la taille de leur entreprise. Il prend en charge deux appels avec affichage d\'appel sur une seule ligne. Achetez un téléphone robuste qui couvre tout ce qui existe aujourd\'hui sur le marché.',
  AVAYA_J169_LABEL: 'Téléphone IP J169',
  AVAYA_J169_DESCRIPTION: 'Disposez de toutes les fonctions d\'appel essentielles dans un téléphone SIP économique malgré la richesse de ses fonctionnalités. Ce combiné téléphonique dispose des fonctions les plus utilisées par les utilisateurs, quelle que soit la taille de leur entreprise. Il prend en charge deux appels avec affichage d\'appel sur une seule ligne. Achetez un téléphone robuste qui couvre tout ce qui existe aujourd\'hui sur le marché.',
  AVAYA_J179_LABEL: 'Téléphone IP J179',
  AVAYA_J179_DESCRIPTION: 'Disposez de toutes les fonctions d\'appel essentielles dans un téléphone SIP économique malgré la richesse de ses fonctionnalités. Ce combiné téléphonique dispose des fonctions les plus utilisées par les utilisateurs, quelle que soit la taille de leur entreprise. Il prend en charge deux appels avec affichage d\'appel sur une seule ligne. Achetez un téléphone robuste qui couvre tout ce qui existe aujourd\'hui sur le marché.',
  AVAYA_K175_LABEL: 'K175 Avaya Vantage™',
  AVAYA_K175_DESCRIPTION: 'Disposez de toutes les fonctions d\'appel essentielles dans un téléphone SIP économique malgré la richesse de ses fonctionnalités. Ce combiné téléphonique dispose des fonctions les plus utilisées par les utilisateurs, quelle que soit la taille de leur entreprise. Il prend en charge deux appels avec affichage d\'appel sur une seule ligne. Achetez un téléphone robuste qui couvre tout ce qui existe aujourd\'hui sur le marché.',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: 'Téléphone de bureau IP 9641GS',
  AVAYA_9641G_DESCRIPTION: 'Le 9641GS d\'Avaya est un téléphone de bureau haut de gamme multiligne, idéal pour les personnes qui passent beaucoup de temps au téléphone et qui comptent sur des communications intelligentes et des capacités d\'amélioration de la productivité. Le 9641GS dispose d\'un écran couleur de 5 pouces, d\'un écran tactile plus grand et d\'une qualité audio haute définition. Son codec audio à large bande offre des performances audio exceptionnelles sur toutes les interfaces audio, y compris le combiné, le casque et le haut-parleur du téléphone.',
  AVAYA_9608G_LABEL: 'Téléphone de bureau IP 9608G',
  AVAYA_9608G_DESCRIPTION: 'Le téléphone de bureau 9608G est un téléphone économique et pleinement fonctionnel. Il propose une connexion gigabit intégrée et un écran monochrome. L\'alimentation par Ethernet simplifie le déploiement et son codec audio à large bande offre des performances audio exceptionnelles. Conçu pour les petites et grandes entreprises, ce téléphone de bureau comprend un accès à huit lignes et des étiquettes graphiques pouvant être gérées de façon centralisée.',
  AVAYA_9611G_LABEL: 'Téléphone de bureau IP 9611G',
  AVAYA_9611G_DESCRIPTION: 'Le modèle 9611G comporte une interface USB et une connexion gigabit intégrées. Son affichage graphique en couleur de 3,5 pouces est doté d\'un rétroéclairage blanc et d\'étiquettes graphiques pouvant être gérées au niveau central. L\'alimentation par Ethernet simplifie le déploiement et son codec audio à large bande offre des performances audio exceptionnelles.',
  AVAYA_PHONE_B179_LABEL: 'Téléphone de conférence SIP ouvert B179',
  AVAYA_PHONE_B179_DESCRIPTION: 'Testé par Tolly, ce téléphone de conférence flexible basé sur SIP offre un son clair et naturel à partir d\'OmniSound 2.0, la technologie audio à large bande brevetée d\'Avaya. Le téléphone est doté de fonctions intelligentes pour des conférences téléphoniques plus efficaces. Utilisez le guide de conférence pour appeler des groupes préprogrammés. Importez et exportez facilement les coordonnées de contact via l\'interface Web. Créez votre propre liste de contacts avec la fonction profil utilisateur personnel.',
  HAVE_LARGE_NUMBERS_OF_USERS: 'Vous avez un grand nombre d\'utilisateurs ?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'Consultez notre répartition des remises en fonction du volume.',
  DEVICE_FEE: 'Prix de l\'appareil',
  UP_TO_DEVICE_CREDITE_PER_USER: 'Jusqu\'à {$} de bon d\'achat d\'appareils par utilisateur',
  PROMOTION_REMAINING_DETAIL_INFO: 'Il vous reste <b>{0}</b> dans le bon d\'achat d\'appareils à dépenser. Veuillez noter que tout crédit restant sera invalide après votre achat et ne sera pas reporté sur votre compte pour des achats futurs.',
  VIEW_USER_FEATURES: 'Afficher les fonctions utilisateur',
  FREE_DEVICES_PER_USER_INFO: '{0} (Jusqu\'à {1} bon d\'achat d\'appareils par utilisateur)',
  VALUE_OF_DEVICE_CREDIT: '{0} Utilisateurs = {0} dans le bon d\'achat total d\'appareils',
  PROMOTION_DELAYED_BILLING_INFO: 'Promotion : des reçus détaillés vous seront fournis et votre carte de crédit sera débitée de tout solde impayé au début officiel de votre cycle de facturation.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'Veuillez sélectionner un agent pour terminer votre commande',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: 'Veuillez fournir un nom de domaine valide (exemple.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Votre système de solutions cloud d\'Avaya est prêt !',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Votre système de solutions cloud d\'Avaya est maintenant installé !',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Numéro de téléphone des solutions cloud d\'Avaya',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Nom de domaine SIP des solutions cloud d\'Avaya',
  IP_OFFICE_SIP_DOMAIN_ID: 'Identifiant de domaine SIP des solutions cloud d\'Avaya',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Votre système de solutions cloud d\'Avaya est en cours de configuration.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'Merci pour votre commande. Nous sommes en train de mettre en place votre système de solutions cloud d\'Avaya et nous vous contacterons une fois la configuration terminée. <br /> Pour toute question, n\'hésitez pas à contacter le support des solutions cloud d\'Avaya {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'Ce compte n\'a pas été provisionné',
  ERROR_CODE: 'Code d\'erreur',
  ERROR_MESSAGE: 'Message d\'erreur',
  ADMIN_PORTAL_LINK: 'Lien vers le portail administrateur',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Solutions cloud d\'Avaya par défaut Mot de passe utilisateur par défaut',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Numéro de téléphone temporaire des solutions cloud d\'Avaya',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'Extensions pour utilisateur basic',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Extensions pour utilisateur standard',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'Extensions pour utilisateurs avancés',
  IP_OFFICE_DEFAULT_USER_PIN: 'Code confidentiel utilisateur par défaut',
  IP_OFFICE_SAME_AS_PIN: 'Identique à l\'extension (ex. : 200)',
  IP_OFFICE_ORDERID: 'Identifiant de commande de solutions cloud d\'Avaya',
  IP_OFFICE_HOST_NAME: 'Votre nom d\'hôte des solutions cloud d\'Avaya',
  IP_OFFICE_IP_ADDRESS: 'Votre adresse IP des solutions cloud d\'Avaya',
  IP_OFFICE_SUBSCRIPTIONID: 'Identifiant d\'abonnement des solutions cloud d\'Avaya',
  CALCULATING: 'Calcul en cours...',
  RESET_ALL_PARTNERS: 'Effacer les données des partenaires',
  ERROR_GETTING_AGENTS: 'Erreur de vérification des agents. Veuillez réessayer',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Un agent utilisant cet e-mail existe déjà dans votre équipe',
  AUTO_APPROVE_ACTIVATE_AGENT: 'Valider/activer automatiquement l\'agent',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Une entreprise utilisant cet e-mail existe déjà dans votre équipe',
  MASTER_SALES_AGENT_PORTAL: 'Portail agent commercial principal',
  SALES_AGENT_PORTAL: 'Portail agent commercial',
  E911_ADDRESS: 'Adresse E911',
  OVERVIEW: 'Aperçu',
  ADD_COMPANY_OR_SALES_AGENT: 'Ajouter une entreprise ou un agent',
  ADD_AN_AGENT: 'Ajouter un agent à',
  INACTIVE: 'Inactif',
  AGENTS_PERSONAL_CONNECTION_LINK: 'Lien personnel de connexion de l\'agent',
  PURCHASE_DATE_AND_CUSTOMER: 'Date d\'achat et client',
  ORDER_DETAILS: 'Informations sur la commande',
  SELECT_AGENT: 'Tous les agents',
  FROM: 'de',
  TO: 'à',
  EXPORT_REPORT: 'Rapport d\'export',
  NO_SALES_FOUND: 'Aucune vente trouvée',
  ADD_A_COMPANY: 'Ajouter une entreprise',
  AUTO_APPROVE_COMPANY: 'Validation automatique de l\'entreprise',
  AUTO_ACTIVATE_AGENT: 'Activation automatique de l\'agent',
  ADD_COMPANY: 'Ajouter l\'entreprise',
  ADD_COMPANY_NAME_AGENT_ADMIN: 'Ajouter agent/administrateur {COMPANY_NAME}',
  ADD_AGENT_ADMIN: 'Ajouter agent/administrateur',
  ALL_COMPANIES: 'Toutes les entreprises',
  START_DATE: 'Date de début',
  HEY: 'Salut',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: 'Nous sommes votre responsable de l\'équipe au service de la réussite des clients. Nous sommes là pour vous aider à tirer profit de vos solutions cloud d\'Avaya. Votre équipe de support de solutions cloud d\'Avaya inclut également notre équipe de support technique - <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: 'Nous aimerions programmer un appel de lancement dans les prochains jours pour présenter votre équipe de support et terminer la configuration de votre système.<strong>Veuillez me contacter à <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> pour convenir d\'un jour et d\'une heure pour un rendez-vous téléphonique d\'une heure.<strong>',
  START_USING_YOUR_IP_OFFICE: 'Commencez à utiliser votre système de solutions cloud d\'Avaya dès maintenant !',
  BELOW_ARE_DETAILS: 'Vous trouverez ci-dessous les informations relatives à votre compte, les identifiants utilisateur et les téléchargements d\'applications :',
  YOUR_IP_OFFICE_INFO: 'Les informations de votre système :',
  LOGIN_INFO_TABLE: 'Votre charte d\'information de l\'utilisateur :',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'Tous vos utilisateurs peuvent configurer leurs informations, paramétrer le transfert d\'appel, écouter les messages vocaux, et plus encore en utilisant les informations ci-dessus et en se connectant à leur propre portail utilisateur sur le cloud.',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'Applications disponibles pour vos utilisateurs :',
  DO_NOT_HESITATE_TO_EMAIL_US: 'N\'hésitez pas à nous envoyer un e-mail à <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a> si vous avez la moindre question !',
  THANK_YOU: 'Merci,',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator pour le Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator pour le Web (Chrome Extension)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred pour IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred pour IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Console logiciel Solutions cloud d’Avaya (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">Installer Doc</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">Installer Doc</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">Installer Doc</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">Installer Doc</a>',




  USER_NAMES_COLUMN: 'Nom d\'utilisateur',
  EXTENSIONS_COLUMN: 'Ext.',
  TEMP_PIN_COLUMN: 'Épingler',
  TEMP_PASSWORD_COLUMN: 'Mot de passe',
  USER_TYPE_COLUMN: 'Type d\'utilisateur',
  DEVICE_MODEL_COLUMN: 'Appareil',
  POWER_USER: 'Avancé',
  STANDARD_USER: 'Standard',
  BASIC_USER: 'Basique',
  ORDERID: 'Identifiant de la commande',
  ACCOUNT_NAME: 'Nom du compte',
  HOST_NAME: 'Nom d\'hôte',
  ADMIN_PORTAL: 'Portail administrateur',
  IP_ADDRESS: 'Adresse IP',
  PHONE_NUMBER: 'Numéro de téléphone',
  TEMPORARY_PHONE_NUMBER: 'Numéro de téléphone temporaire',
  EXCITING_TIMES_AHEAD: 'Temps forts en perspective',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'Le nom de domaine {DOMAIN_NAME} est soit invalide, soit utilisé par une autre entreprise.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'Le nom de domaine {1} est soit invalide, soit utilisé par une autre entreprise.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: 'Le système n\'a pas pu valider votre entreprise. Veuillez réessayer.',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'Pour toute information non disponible (le cas échéant), veuillez contacter le support d\'Avaya Cloud : ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Échec de mise à disposition d\'un compte Avaya Cloud',
  LEGAL: 'Légal',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Choisissez un forfait d\'un an (ou plus) et recevez un bon par utilisateur pour l\'achat d\'un appareil. Offre à durée limitée.',
  USER_PORTAL: 'Portail utilisateur',
  E_911: 'E911',
  DECLINE: 'Refuser',
  ACCEPT: 'Accepter',
  PRINT: 'Imprimer',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'Veuillez accepter toutes les conditions ci-dessus pour terminer votre commande',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'Attribuez un appareil à vos utilisateurs.',
  SELECT: 'Sélectionner',
  USER_DETAILS: 'Informations utilisateur',
  DEVICE_DETAILS: 'Informations appareil',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: 'Veuillez lire attentivement nos conditions d\'utilisation avant d\'accepter.',
  PARTNER_ORDERS_RECORDS_HINT: '*Tous les dossiers de vente sont pour référence seulement. Les rapports de vente officiels et finaux seront fournis par Avaya Finance conformément à l\'accord-cadre de l\'agent commercial.',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: 'Veuillez sélectionner un agent commercial pour créer le devis',
  COMPANY_DETAILS: `Informations sur l'entreprise`,
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'Taxes applicables en sus.',
  SELECT_PRODUCT: 'Sélectionner le produit',
  CLOUD_UC_SMALL_MONTH1: 'Forfait mensuel Cloud UC Essentials',
  SMALL: 'Petit',
  CLOUD_UC_SMALL_MONTH12: 'Forfait 1 an Cloud UC Essentials',
  CLOUD_UC_SMALL_3YEARS: 'Forfait 3 ans Cloud UC Essentials',
  CLOUD_UC_SMALL_5YEARS: 'Forfait 5 ans Cloud UC Essentials',
  MEDIUM: 'Moyen',
  CLOUD_UC_MEDIUM_MONTL1: 'Forfait mensuel Cloud UC Business',
  CLOUD_UC_MEDIUM_MONTH12: 'Forfait 1 an Cloud UC Business',
  CLOUD_UC_MEDIUM_3YEARS: 'Forfait 3 ans Cloud UC Business',
  CLOUD_UC_MEDIUM_5YEARS: 'Forfait 5 ans Cloud UC Business',
  LARGE: 'Grand',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC Large Pay As You Go',
  CLOUD_UC_LARGE_MONTL12: 'Forfait annuel Cloud UC Large',
  CLOUD_UC_SMALL_SHORT_INFO: 'de 1 à 99 employés',
  CLOUD_UC_MEDIUM_SHORT_INFO: 'de 100 à 999 employés',
  CLOUD_UC_LARGE_SHORT_INFO: '+ de 1 000 employés',
  SELECTED: 'Sélectionné',
  BASIC_PHONE_SERVICE: 'Service téléphonique basic',
  UNLIMITED_NATIONAL_WIDE: 'Appels interurbains illimités à l\'échelle nationale',
  STANDARD_FEATURES: 'Fonctions standard',
  HOW_MANY_USERS: 'De combien d\'utilisateurs avez-vous besoin ?',
  ADD_ON_ADDITIONAL_FEATURES: 'Fonctions supplémentaires',
  ONETIME_FEE: 'Paiement unique',
  RECURRING_FEE: 'Paiement récurrent',
  SELECT_MAIN_NUMBER: 'Sélectionnez le numéro principal',
  TOLL_FREE: 'Numéro gratuit',
  LOCAL_NUMBER: 'Numéro local',
  TRANSFER_NUMBER: 'Numéro de transfert',
  USERS_COUNT: '{qty} utilisateurs',
  DEVICES_COUNT: '{qty} appareil(s)',
  UC_OFFER_TITLE: 'Nous avons la solution qu\'il vous faut !',
  UC_OFFER_DESCRIPTION: 'Que vous soyez une petite, moyenne ou grande entreprise, nous avons ce que vous cherchez ! Quel type d\'entreprise êtes-vous ?',

  // 'BASIC_PHONE_SERVICE': 'Service téléphonique basic',

  TAX_CALC_ERROR_MSG: 'Impossible de calculer la taxe. Veuillez vérifier que l\'adresse de facturation est correcte.',
  'VIOLATION.FIELD_IS_EMPTY': '{1} est requis',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} - {2} est requis',
  'VIOLATION.FIELD_VALUE_INVALID': 'La valeur {1} n\'est pas valide',
  'VIOLATION.FIELD_VALUE_INVALID2': 'La valeur {1} - {2} n\'est pas valide',
  'VIOLATION.TAX_CALCULATION_FAILED': 'Échec dans le calcul de la taxe',
  'VIOLATION.AGREE_ON_LEGAL_DOC': 'Vous devez lire et accepter le "{1}"',
  'VIOLATION.CART_IS_EMPTY': 'Le panier est vide',
  'VIOLATION.CART_IS_TOO_BIG': 'Le panier contient trop d\'articles',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} est retiré du panier',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': '{1} la quantité est réglée de {2} à {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': '{1} la remise est ajustée de {2} à {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': 'Impossible d\'ajouter un article avec la devise {1} à un panier ayant la devise {2}',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': 'La règle de remise {1} n\'est pas définie',
  'SALESMODELRULE.UNKNOWN_ERROR': 'Erreur inconnue',
  'SALESMODELRULE.INVALID_PARAMETER': 'Les paramètres ne sont pas valides : {1}',
  ONE_TIME: 'Unique',
  ADDON_PRICING_HINT: '*Les prix des extensions sont par siège et s\'appliquent à tous les utilisateurs. L\'ajout d\'extensions spécifiques aux utilisateurs peut se faire après l\'achat depuis votre portail administrateur.',
  ADD_TO_CART_HINT: 'Terminez les étapes ci-dessus pour ajouter au panier',
  ITEM_UNITS: '{qty} unités',
  ADDONS_COUNT: '{qty} extensions',
  ADDON_COUNT: '{qty} extension',
  MULTIPLE_TYPES: 'Types multiples',
  MIXED: 'mélangés',
  FREE_PRICE: 'GRATUIT',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essentials',
  UC_ESSENTIALS_DESCRIPTION: 'Les meilleures communications en Cloud pour toutes les entreprises, quelle que soit leur taille.',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: 'Donnez à votre entreprise les meilleures communications d\'entreprise sur le Cloud',
  UC_BUSINESS_POWER_PACKAGE: 'Mise à niveau vers les utilisateurs AVANCÉS',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong><ul><li><strong>Direct phone number :</strong> Numéro de téléphone dédié, unique, de sorte que n\'importe qui peut vous appeler directement au lieu de passer par l\'intermédiaire du numéro principal du bureau et de la réceptionniste (virtuelle ou humaine).</li><li><strong>Appels vidéo en direct :</strong> Ajoutez de la vidéo à vos appels téléphoniques.</li><li><strong>Intégration Salesforce© :</strong> Communications complètes et riches pour les utilisateurs finaux directement à partir de Salesforce.</li><li><strong>Intégration Google© :</strong> Communications en temps réel par navigateur directement à partir de Google Chrome et dans toutes vos applications Google.</li><li><strong>Intégration Skype for Business© :</strong> Une expérience de collaboration moderne, rationalisée et facile à utiliser avec Skype pour les entreprises.</li></ul>',
  SHOW_MORE: 'Afficher plus',
  HIDE: 'Masquer',
  VIEW_COMPLETE_FEATURE_LIST: ' Voir la liste complète des fonctions',
  FILTER_BY: 'Filtrer par',
  UC_OFFERS: 'Solutions de communications unifiées',
  PAY_MONTHLY: 'Paiement mensuel',
  PAY_ANNUALLY: 'Paiement annuel',
  COMING_SOON: 'Bientôt disponible',
  TAX_CALC_ERROR_MSG: 'Impossible de calculer la taxe. Veuillez vérifier que l\'adresse est correcte.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: 'Veuillez entrer le nom d\'un pays pour consulter les tarifs interurbains actuels.',
  LONG_DISTANCE_RATE_NOT_FOUND: 'Si vous ne trouvez pas le tarif interurbain pour ce pays, veuillez contacter {CUSTOMER_SUCCESS_EMAIL} pour plus d\'informations sur les appels interurbains vers ce pays.',
  AREA_CODE: 'Indicatif régional',
  INVALID_CREDIT_CARD_ZIP: 'La carte de crédit ne correspond pas au code postal.',
  VIEW_LONG_DISTANCE_RATES: 'Voir les tarifs interurbains',
  LONG_DISTANCE_SUBTITLE_TEXT: 'Nos tarifs d\'appels interurbains avantageux vous permettent de rester en contact avec le monde entier.',
  RATES_SUBJECT_TO_CHANGE: '*Tarifs pouvant être modifiés, sans préavis.',
  CREDIT_CARD_DECLINED: 'La carte de crédit a été refusée.',
  ENTER_COUNTRY_NAME: 'Entrez le nom du pays',
  ADD_TO_CART: 'Ajouter au panier',
  UPDATE_CART: 'Mettre à jour le panier',
  PER_USER: 'Par utilisateur',
  COMPARE_UC_OFFERS: 'Comparer les offres de communications unifiées',
  PROCEED_TO_CHECKOUT: 'Procéder au règlement',
  BEFORE_APPLICABLE_TAXES: '* Avant taxes applicables',
  YEAR_PLAN: 'Forfait 1 an',
  YEARS_PLAN: 'Forfait {0} ans',
  MONTHS_PLAN: 'Forfait {0} mois',
  ENTER_NUMBER_OF_USERS: 'Entrez le nombre d\'utilisateurs que vous souhaitez pour cette solution',
  YEAR: 'Année',
  BILLED_MONTH: 'Facturation mensuelle',
  COMPANY_INCORPORATED: 'Incorporé',
  COMPANY_NOT_INCORPORATED: 'Non incorporé',
  EXISTING_CONFIG_WARNING: 'Vous avez une configuration existante pour <br/><b>{0}</b>.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: 'Voulez-vous abandonner votre configuration actuelle ?',
  DISCARD_MY_CONFIGURATION: 'Abandonner ma configuration',
  DISCARD: 'Abandonner',
  EDIT_MY_CONFIGURATION: 'Modifier ma configuration actuelle',
  CONTINUE: 'Continuer',
  SELECT_A_PLAN: 'Sélectionner un forfait',
  PROMOTION_DETAIL_INFO: '*Vous avez sélectionné un total de <b>{0} utilisateurs </b>!<br/> Équivalent à <b>{1}</b> sur le total de votre bon d\'achat d\'appareil.',
  BILLED_MONTH_FREQUENCY: 'Facturation tous les {0} mois',
  BILLED_YEAR_FREQUENCY: 'Facturation tous les {0} ans',
  CONTACT_OUR_CUSTOMER_CARE: 'Contactez notre équipe du service à la clientèle',
  NEED_HELP_INFO: 'Besoin d\'aide ? Notre équipe du service à la clientèle est toujours prête à vous aider en cas de questions, problèmes ou si vous avez besoin d\'informations complémentaires.',
  REMOVE: 'Supprimer',
  REMOVE_ITEM_FROM_CART_WARNING: 'Voulez-vous supprimer <b>{0}</b> du panier ?',
  NO_ITEM_IN_THE_CART: 'Aucun article dans votre panier.',
  CONTINUE_SHOPPING: 'Poursuivre vos achats',
  TOTAL_TAXES: 'Taxes totales',
  UC_SOLUTIONS: 'Solutions de communications unifiées',
  UNIFIED_COMMUNICATIONS: 'Communications unifiées',
  ADD_ONS: 'Extensions',
  SYSTEM_ADDONS: 'Système d\'extensions',
  ADD_DEVICES: 'Ajouter des appareils',
  SELECT_UPTO_DEVICES: 'Sélectionner jusqu\'à (<b>{0}</b>) appareils pour <b>{1}</b>',
  DONE: 'Terminé',
  SELECT_DEVICES: 'Sélectionner des appareils',
  EDIT_DEVICE_SELECTION: 'Modifier les appareils',
  ESSENTIAL_USERS: 'Utilisateurs Essential',
  BUSINESS_USERS: 'Utilisateurs Business',
  POWER_USERS: 'Utilisateurs avancés',
  N_A: 'ND'
}
