export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'Impossibile decodificare i dati dal sistema Account',
  PHONE_TYPES: 'Tipi di telefono',
  IMAGINE_A_BETTER_WAY: 'Immagina un modo migliore',
  OF_DOING_THINGS: 'di lavorare.',
  GET_STARTED: 'Inizia',
  PURCHASE: 'Acquista',
  DOWNLOADS_AND_EXTENSIONS: 'Download ed estensioni',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: 'Ottieni il massimo dai tuoi prodotti Zang grazie a questi indispensabili componenti aggiuntivi!',
  ALL: 'Tutti',
  REFERRAL_AGENT: 'Agente di riferimento',
  SALES_AGENT: 'Agente di vendita',
  CART: 'Carrello',
  PARTNER_PROGRAMS: 'Programmi partner',
  HOME: 'Home',
  MANAGE_CREDIT_CARDS: 'Gestisci carte di credito',
  MANAGE_PAYMENT_OPTIONS: 'Gestisci opzioni di pagamento',
  MANAGE_BILLING_ACCOUNT: 'Gestisci account di fatturazione',
  LIMIT: "Limite",
  MY_PROFILE: 'Profilo personale',
  MY_SETTINGS: 'Impostazioni personali',
  MY_PARTNER_PORTAL: 'Portale partner personale',
  CLEAR_ZANG_OFFICE: 'Cancella impostazioni Zang Office',
  CLEAR_ZANG_SPACES: 'Cancella impostazioni Zang Spaces',
  FEATURE_BREAKDOWN: 'Interruzione funzioni',
  PLAN_BREAKDOWN: 'Interruzione piano', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'Il telefono aziendale che desideri a un prezzo imperdibile',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Immagina cosa puoi fare con Zang Spaces',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'Verrà applicato uno sconto del 50% all\'importo totale al termine della procedura di acquisto',
  HURRICANE_HARVEY_MESSAGE: 'Avaya e Zang desiderano aiutare le aziende che sono state colpite dall’uragano Harvey e potenzialmente dall’uragano Irma. Tutte le aziende ubicate in Texas, Louisiana, Florida, Alabama, Georgia, Carolina del Nord, Carolina del Sud, Tennessee e Mississippi che sono interessate possono <b>ricevere immediatamente 3 mesi GRATUITI di Zang Office</b> e <b>Zang Spaces</b>.',
  LEARN_MORE: 'Scopri di più',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'È ADESSO DISPONIBILE AVAYA VANTAGE™',
  NEW: 'NOVITÀ!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Sfrutta al massimo Zang Office con questo telefono completamente in vetro, facile da utilizzare, per la collaborazione vocale, video e chat.',
  LOG_IN: 'Accedi',
  SIGN_UP: 'Registrati',
  SIGN_OUT: 'Disconnetti',
  SIGN_IN: 'Accedi', //login to the system, connect
  ADMINISTRATION: 'Amministrazione',
  PRODUCTS: 'Prodotti',
  ORDERS: 'Ordini',
  PAGES: 'Pagine',
  CUSTOMERS: 'Clienti',
  USERS: 'Utenti',
  PLANS: 'Piani',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'CDR',
  CDR_CHECKS: 'Verifiche CDR',
  PARTNERS: 'Partner',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'Sembra che Zang Office sia già stato acquistato. Non è possibile inoltrare altri ordini Zang Office.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'Un account Avaya Cloud è già stato acquistato per questa azienda. Selezionare un\'altra azienda.',
  PARTNER_CONNECTIONS: 'Connessioni partner',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'Si è verificato un errore durante l\'ordine. Contatta il supporto Zang ({SUPPORT_EMAIL}) per maggiori informazioni.',
  APPLICATION_GENERAL_FATAL_ERROR: 'Si è verificato un errore durante l\'invio della tua candidatura. Contatta il supporto Zang ({SUPPORT_EMAIL}) per maggiori informazioni.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Seleziona almeno un tipo di utente per continuare.',
  BACK: 'Indietro',
  SAVE_CHANGES: 'Salva modifiche',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: 'Vuoi procedere?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'Hai {PLACEHOLDER} di credito da spendere per l’acquisto di un qualsiasi dispositivo. Il credito verrà perso una volta inoltrato l’ordine.',
  JUST_A_REMINDER: 'Promemoria',
  LAST_CHANCE: 'Ultima possibilità',
  IM_GOOD_PLACE_MY_ORDER: 'Sto bene - Inoltra il mio ordine',
  BUY_MORE_DEVICES: 'Acquista altri dispositivi',
  YES_PLACE_MY_ORDER: 'Sì, inoltra il mio ordine',
  NO_THANKS: 'No grazie!',
  YES: 'Sì',
  ABOUT_US: 'Su di noi',
  NEWS_AND_PRESS: 'Notizie e comunicati',
  CARREERS: 'Carriere',
  CONTACT_US: 'Contattaci',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Grazie per aver deciso di acquistare da noi. I dettagli del tuo ordine sono indicati di seguito.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: 'Contattare <a href="mailto:{EMAIL}">{EMAIL}</a> per informazioni in merito',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'I nostri team per il supporto tecnico e Customer Success ti contatteranno quando il sistema sarà pronto. <br/><br/><b>Tieni presente che potrebbe essere necessaria fino a un\'ora per configurare il sistema.</b>',
  QUESTION_CUSTOMER_SERVICE: 'Per qualsiasi domanda, inviaci un\'e-mail all\'indirizzo <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  BLOG: 'Blog',
  FAQS: 'FAQ',
  DOCUMENTATION: 'Documentazione',
  TERMS_OF_SERVICE: 'Termini del servizio',
  HELP: 'Guida',
  PRIVACY_STATEMENT: 'Informativa sulla privacy',
  GENERAL_PRIVACY_STATEMENT: 'Informativa generale sulla privacy',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: 'Termini generali del servizio - Soluzioni Avaya Cloud',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang Inc. Tutti i diritti riservati.',
  PROCESSING: 'Elaborazione in corso',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Un attimo di pazienza. Il processo potrebbe richiedere qualche minuto',
  OPEN_IN_A_NEW_TAB: 'Apri in una nuova scheda',
  GOT_IT: 'Ho capito!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' Questa azione produrrà i risultati seguenti:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Eliminazione dell\'abbonamento mensile per il piano',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Disattivazione degli account nei sistemi di terze parti',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Modifica dello stato di questo piano su DISATTIVATO',
  LAST_ACTION_STEPS: 'Ultimi passaggi azione',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'I componenti aggiuntivi vengono acquistati tramite il portale di amministrazione di Zang Office una volta creato l’account.',
  TYPE: 'Tipo',
  ADMIN: 'Amministratore',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'Questo utente sarà configurato come contatto primario/di fatturazione per l’account aziendale. Potrà essere modificato in qualsiasi momento dal portale di amministrazione di Zang Office.',
  DESCRIPTION: 'Descrizione',
  SUCCESS: 'Operazione eseguita correttamente',
  REQUEST_CANCELATION: 'Richiedi annullamento',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Questa è una brutta notizia! Ci dispiace che te ne vai.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Compila il modulo qui sotto per iniziare il processo di annullamento. Un membro del nostro reparto Customer Success esaminerà la tua richiesta e ti ricontatterà entro 1-2 giorni lavorativi, per garantirti una procedura senza intoppi.',
  YOUR_NAME: 'Il tuo nome',
  COMPANY: 'Azienda',
  SERVICE: 'Servizio',
  REASON_FOR_CANCELING: 'Motivo dell\'annullamento',
  SUBMIT: 'Invia',
  EXIT: 'Esci',
  REQUEST_SUBMITTED: 'Richiesta inviata!',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Un membro del nostro reparto Customer Success esaminerà la tua richiesta e ti ricontatterà entro 1-2 giorni lavorativi, per garantirti una procedura senza intoppi.',
  DATE: 'Data',
  PRODUCT: 'Prodotto',
  USER: 'Utente',
  STATUS: 'Stato',
  ACTIONS: 'Azioni',
  VIEW_DETAILS: 'Visualizza dettagli',
  DISABLE: 'Disattiva',
  ENABLE: 'Attiva',
  CANCEL: 'Annulla',
  PLAN_DETAILS: 'Dettagli piano',
  SUMMARY: 'Riepilogo',
  QUANTITIES: 'Quantità',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*Il totale include i prezzi delle funzioni del piano',
  TOTAL: 'Totale',
  BILLED: 'Fatturato',
  PLAN_INFORMATION: 'Informazioni piano',
  UPDATE_PLAN: 'Aggiorna piano',
  ADMIN_ACTIONS: 'Azioni amministratore',
  NAME_ON_CREDIT_CARD: 'Nome sulla carta di credito',
  CREDIT_CARD_BRAND: 'Marca della carta di credito',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: 'Numero della carta di credito',
  EXPIRATION: 'Scadenza',
  MONTH: 'Mese',
  YEAR: 'Anno',
  SECURITY_CODE: 'Codice di sicurezza',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'Il codice sul retro della tua carta di credito',
  BACK_TO_CHECKOUT: 'Torna alla procedura di acquisto',
  NO_ORDERS_FOUND: 'Nessun ordine trovato',
  ADD: 'Aggiungi',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Utilizza il modulo qui sopra per aggiungere una nuova carta di credito. Compila tutti i campi',
  NUMBER: 'Numero',
  EXPIRES: 'Scadenza',
  DELETE: 'Elimina',
  ITEM_DETAILS: 'Dettagli articolo',
  FEE: 'Tariffa',
  ITEMS: 'Articoli',
  SEARCH_BY_CONFIRMATION: 'Cerca per conferma',
  CONFIRMATION: 'Conferma',
  CHECKOUT_STATUS: 'Stato procedura di acquisto',
  ORDER_STATUS_PROCESS: 'Elaborazione stato ordine',
  CREATED_ON: 'Data di creazione',
  ORDER_SUMMARY: 'Riepilogo ordine',
  APPROVED: 'Approvato', //example: partner application approved
  REJECTED: 'Rifiutato', //example: partner application rejected
  APPROVE: 'Approvare', //example: partner application approved
  REJECT: 'Rifiutare', //example: partner application rejected
  PENDING: 'In sospeso', //example: partner application pending
  EDIT: 'Modifica',
  ONE_TIME_FEE: 'Tariffa una tantum',
  SUB_TOTAL: 'Subtotale',
  TAXES: 'Imposte',
  CHANGES: 'Modifiche',
  CREATE_A_QUOTE: 'Crea un preventivo',
  EXTRA_INFORMATION: 'Informazioni aggiuntive',
  THANK_YOU_FOR_YOUR_ORDER: 'Ti ringraziamo per il tuo ordine',
  ORDER_CONFIRMATION: 'Conferma dell\'ordine',
  INVALID_ORDER: 'Ordine non valido',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'Non preoccuparti, ti abbiamo anche inviato un\'e-mail :)',
  HELLO: 'Salve',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Grazie per aver deciso di acquistare da noi. Ti invieremo una conferma una volta che gli articoli vengono spediti. I dettagli del tuo ordine sono indicati di seguito.',
  ACCOUNT_INFORMATION: 'Informazioni account',
  BILLING_INFORMATION: 'Informazioni di fatturazione',
  SHIPPING_INFORMATION: 'Informazioni di spedizione',
  NAME: 'Nome',
  EMAIL: 'E-mail',
  SEARCH: 'Cerca',
  CLEAR: 'Cancella',
  PARTNER: 'Partner',
  NO_PARTNERS_FOUND: 'Nessun partner trovato',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'Una connessione partner viene creata quando un cliente arriva al negozio dal collegamento personale di un partner.',
  CUSTOMER: 'Cliente',
  AGENT: 'Agente',
  NO_PARTNER_CONNECTIONS_FOUND: 'Nessuna connessione partner trovata',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'Ho letto e accetto',
  ZANG_PRIVACY_STATEMENT: 'L\'informativa sulla privacy di Zang',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'I Termini del servizio del programma per agenti',
  SUBMIT_APPLICATION: 'Invia candidatura',
  SUBMITTING: 'Invio in corso',
  SUBMITTING_YOUR_APPLICATION: 'Invio candidatura in corso',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'Tutte le informazioni bancarie e sull\'account sono mantenute private e protette secondo i nostri termini e le nostre condizioni.',
  BANK_NAME: 'Nome banca',
  ADDRESS: 'Indirizzo',
  COUNTRY: 'Paese',
  SELECT_ONE: '- Seleziona un\'opzione -',
  STATE_PROVINCE: 'Stato/Provincia',
  CITY: 'Città',
  ZIP_POSTAL_CODE: 'CAP',
  ACCOUNT_NUMBER: 'Numero conto',
  BANK_NUMBER: 'Numero banca',
  TRANSIT_NUMBER: 'Numero transito',
  SWIFT_CODE: 'Codice Swift',
  TAX_REGISTRATION_NUMBER: 'Codice fiscale',
  SAVE_BANK_INFORMATION: 'Salva informazioni bancarie',
  SAVING_BANK_INFORMATION: 'Salvataggio informazioni bancarie in corso',
  NO_CUSTOMERS_FOUND: 'Nessun cliente trovato',
  YOU_ARE_A: 'Sei un ',
  A_DISCOUNT_OF: 'Uno sconto del',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'verrà applicato all\'importo totale al termine della procedura di acquisto.',
  FIRST_NAME: 'Nome',
  LAST_NAME: 'Cognome',
  COMPANY_NAME: 'Nome azienda',
  LEGAL_COMPANY_NAME: 'Nome legale azienda',
  PHONE_NUMBER: 'Numero di telefono',
  WEBSITE: 'Sito Web',
  OPERATIONAL_ADDRESS: 'Indirizzo operativo',
  SAME_AS_ORGANIZATION_ADDRESS: 'Stesso dell\'indirizzo dell\'organizzazione',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: 'Sei già partner Avaya?',
  NO: 'No',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'In caso affermativo, immetti il tuo ID partner Avaya',
  MY_PARTNER_PORTAL: 'Portale partner personale',
  THANK_YOU_FOR_APPLYING: 'grazie per la tua candidatura!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'Un altro passaggio ed è fatta! Per completare la candidatura come agente di vendita, segui il collegamento qui sotto e rispondi a tutte le domande.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' In caso contrario, specificare ',
  PLEASE_GIVE: 'Specificare',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'Se sei un Avaya Partner esistente NON seguire il collegamento di seguito. <br />Al momento stiamo controllando il tuo ID partner, ti contatteremo a breve.',
  BUSINESS: 'giorni',
  DAYS: 'lavorativi',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'affinché la dirigenza senior possa esaminare la tua candidatura.<br /> Nel frattempo, puoi inviare le tue domande a',
  COMPLETE_MY_APPLICATION: 'Completa la mia candidatura',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'Abbiamo esaminato la tua candidatura. Purtroppo, al momento abbiamo concluso che non è adatta al nostro programma. Probabilmente non è nulla di grave, ma non possiamo procedere con la nostra partnership se prima non capiamo il motivo. Ci rendiamo conto di quanto possa essere frustrante. Tieni presente che stiamo analizzando le motivazioni e ti contatteremo non appena avremo maggiori informazioni. Nel frattempo, contattaci pure all\'indirizzo',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'per qualsiasi domanda inerente a questa procedura.',
  CONGRATULATIONS: 'congratulazioni',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: 'Adesso sei un agente Zang ufficiale!',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Inizia condividendo il tuo collegamento personale con tutti i tuoi lead',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'e aiutali a scoprire un modo migliore per lavorare.',
  CHANGE_STATUS: 'Cambia stato',
  AGENT_DETAILS: 'Dettagli agente',
  BANK_INFORMATION: 'Informazioni bancarie',
  THIS_ORDER_WAS_PLACED_BY_A: 'Questo ordine è stato effettuato da',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'è stato applicato all\'importo totale',
  REFERRALS: 'Riferimenti',
  SALES: 'Vendite',
  FOUND: 'Trovato',
  HOW_IT_WORKS: 'Come funziona',
  WHAT_YOU_GET: 'Cosa ottieni',
  SUPPORT: 'Supporto',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'Quale programma è più adatto a me?',
  WHY_JOIN: 'Perché partecipare?',
  QUOTE: 'Preventivo',
  PRINT_THIS_QUOTE: 'Stampa questo preventivo',
  CLOSE_THIS_WINDOW: 'Chiudi la finestra',
  SEARCH_BY_PLAN: 'Cerca per piano',
  ACCESS_LEVEL: 'Livello di accesso',
  DISPLAY_NAME: 'Nome visualizzato',
  INDUSTRY: 'Settore',
  COMPANY_INDUSTRY: 'Settore aziendale',
  CONTACT_PHONE_NUMBER: 'Numero di telefono contatto',
  EMAIL_ADDRESS: 'Indirizzo e-mail',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Sì, inviami e-mail sulle novità, le applicazioni, le offerte e gli eventi speciali di Zang!',
  INFORMATION: 'Informazioni',
  ORDER_HISTORY: 'Cronologia ordini',
  FILTER: 'Filtro',
  ACCOUNT: 'Account',
  AMOUNT_CHARGED: 'Importo modificato',
  DETAILS: 'Dettagli',
  NO_RECORDS_FOUND: 'Nessun record trovato',
  CALL_LOGS: 'Log chiamate',
  EXPORT: 'Esporta',
  CALLER_NAME: 'Nome chiamante',
  DIALED_NUMBER: 'Numero composto',
  DURATION_SEC: 'Durata (sec)',
  COST: 'Costo',
  PAYMENT_METHOD: 'Metodo di pagamento',
  PURCHASE_ORDER: 'Ordine di acquisto',
  PURCHASE_ORDERS: 'Ordini di acquisto',
  CREDIT_CARD: 'Carta di credito',
  SHIPPING_ADDRESS: 'Indirizzo di spedizione',
  SAME_AS_BILLING_ADDRESS: 'Lo stesso dell\'indirizzo di fatturazione',
  SAME_AS_SHIPPING_ADDRESS: 'Uguale all\'indirizzo di spedizione',
  OTHER: 'Altro',
  SHIPPING_OPTIONS: 'Opzioni di spedizione',
  FREE_SHIPPING: 'Spedizione GRATUITA',
  ADDITIONAL_NOTES: 'Note aggiuntive',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'Ho letto e accetto quanto segue:',
  EMERGENCY_911_SERVICE_NOTICE: 'Note legali sui servizi di emergenza 911',
  PLACE_MY_ORDER: 'Invia ordine',
  CLEAR_MY_ORDER: 'Cancella ordine',
  PLACING_YOUR_ORDER: 'Invio ordine in corso',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'Un attimo di pazienza. Questo processo potrebbe richiedere fino a 1 minuto.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'Questo processo potrebbe richiedere qualche minuto. Ti ringraziamo per la pazienza. Per evitare che l\'ordine venga interrotto, non chiudere la finestra del browser e non fare clic sui pulsanti Indietro o Aggiorna.',
  YOUR_NEW_NUMBER: 'Il tuo nuovo numero',
  NO_NUMBER_SELECTED: 'Nessun numero selezionato',
  WELL_THAT_WAS_EASY: 'È stato facile!',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'Un altro paio di passaggi ed è fatta :)',
  NEXT: 'Successiva',
  TITLE: 'Titolo',
  SUB_TITLE: 'Sottotitolo',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Cerca per indicativo località... (solo Stati Uniti e Canada)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: 'Inserire l\'indicativo località... (solo per USA)',
  SELECT_A_PREFIX: 'Seleziona un prefisso',
  PICK_THIS_NUMBER: 'Seleziona questo numero',
  DEVICES: 'Dispositivi',
  BILLING: 'Fatturazione',
  CHANGE: 'Modifica',
  USER_INFO: 'Informazioni utente',
  USE_MY_INFORMATION: 'Utilizza le mie informazioni',
  SELECT_YOUR_DEVICES: 'Seleziona i tuoi dispositivi',
  MONTHLY_FEE: 'Tariffa mensile',
  ANNUAL_FEE: 'Tariffa annuale',
  TWO_YEAR_FEE: 'Tariffa biennale',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Ogni piano Zang Office richiede almeno un utente Standard OPPURE Power.',
  CHECKOUT: 'Processo di acquisto',
  MINE: 'Per me',
  REMOVE_THIS_USER: 'Rimuovi questo utente',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Seleziona un dispositivo per questo utente',
  ADD_ANOTHER: 'Aggiungi un altro',
  GET_STARTED_WITH_ZANG_OFFICE: 'Inizia con Zang Office',
  BUNDLE: 'pacchetto',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Registrati per un anno e ricevi',
  OFF: 'DISATTIVO',
  EACH_USER: 'ogni utente',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'Per modificare le quantità utente, devi cancellare l\'ordine o procedere al passaggio per la selezione dei dispositivi.',
  EVERY_TWO_YEARS: 'Ogni 2 anni',
  YOU_VE_SAVED: 'Hai risparmiato',
  INCLUDED: 'Componenti aggiuntivi',
  ADDONS: 'Inclusi',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Personalizza ogni utente in base ai suoi gusti!',
  UNITS_PER: 'Unità per',
  TALK_ANYWERE_ANYTIME: 'Conversa ovunque, in qualunque momento!',
  DOWNLOAD_FOR_MAC: 'Download per MAC',
  DOWNLOAD_FOR_WINDOWS: 'Download per Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Grazie per aver acquistato Zang Office! Visualizza il tuo ordine qui!',
  CONTINUE_WITH_YOUR_PURCHASE: 'Continua con il tuo acquisto!',
  GET_STARTED_TODAY: 'Inizia oggi stesso!',
  FEATURES: 'Funzioni',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Te le presentiamo in dettaglio!',
  BASIC: 'Basic',
  STANDARD: 'Standard',
  POWER: 'Power',
  RATE_MIN_STARTING_FROM: 'Tariffa/min, a partire da*:',
  RATE_MIN_STARTING_FROM_1: 'Tariffa/min, a partire da',
  LONG_DISTANCE: 'Chiamate internazionali',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'Tariffe chiamate internazionali',
  COMMON_DESTINATIONS: 'Destinazioni comuni',
  BEST_DEAL: 'offerta migliore',
  PER_ACTIVE_USER_PER_MONTH: 'Per utente attivo, al mese.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'in base al contratto annuale',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'Fatturato in base al piano selezionato.',
  MONTHLY: 'Mensile',
  ANNUALLY: 'Annuale',
  BILLED_ANNUALY: 'Fatturato annualmente',
  BILLED_EVERY_TWO_YEARS: 'Fatturato ogni 2 anni',
  CONFIGURE_YOUR_ADDONS: 'Configura i tuoi componenti aggiuntivi',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Seleziona una quantità per ogni componente aggiuntivo disponibile.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'La quantità massima per questo componente aggiuntivo è',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'Questo componente aggiuntivo è disponibile solo per',
  BILLING_AND_SHIPPING: 'Fatturazione e spedizione',
  BILLING: 'Fatturazione',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'Questo sarà il tuo nome account Zang Office.',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'Questo sarà il tuo nome account per Avaya Cloud.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Se hai scelto di utilizzare il tuo numero esistente o un numero verde come numero Zang Office, proveremo a individuare un numero locale con l\'interno utilizzato in questo campo.',
  EVERYTHING_HAPPENS_IN_SPACES: 'In Spaces succede di tutto',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'Lo strumento di collaborazione del team basato su cloud che hai sempre cercato.',
  YOUR_CURRENT_PURCHASES: 'I tuoi acquisti attuali',
  PURCHASED_ON: 'Acquistato in data',
  PLAN_NUMBER: 'Numero piano',
  UPDATE: 'Aggiorna',
  UPDATED: 'Aggiornato',
  OR: 'oppure',
  MAKE_A_NEW_PURCHASE: 'Effettua un nuovo acquisto',
  FEATURES_AND_ADDONS: 'Funzioni e componenti aggiuntivi',
  FREE: 'GRATUITO',
  PLUS: 'PLUS',
  BUSINESS: 'POWER',
  VIEW: 'Visualizza',
  TEAM: 'Team',
  LETS_SETUP_YOUR_TEAM: 'Configuriamo il tuo team',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Seleziona il tipo di team da creare e configura il tuo ambiente privato.',
  COMPANY_TYPE: 'Tipo di azienda',
  DOMAIN: 'Dominio',
  NO_TEAM_IS_SETUP_YET: 'Nessun team ancora configurato',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'Non configurare un team per me',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Acquista Zang Spaces solo per te.',
  CHOOSE_AN_EXISTING_COMPANY: 'Scegli un\'azienda esistente',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Seleziona una delle aziende che stai amministrando al momento.',
  CREATE_A_NEW_TEAM: 'Crea un nuovo team',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Fornisci un nome del team e di dominio.',
  NO_DOMAIN_IS_CONFIGURED: 'Nessun dominio configurato.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Fornisci un nome di dominio (ad es: \'zang.io\')',
  CHECK: 'Controlla',
  TEAM_DOMAIN: 'Nome di dominio (ad es. \'zang.io\')',
  TEAM_NAME: 'Nome del team (ad es. \'Zang\')',
  OK: 'OK',
  ZANG_SPACES_ADMIN_CONSOLE: 'Console di amministrazione Zang Spaces',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'Puoi modificare i valori qui sotto per aggiornare il tuo piano',
  CHARGABLE_USERS: 'Utenti a pagamento',
  TOTAL_USERS: 'Utenti totali',
  CURRENT_PRICE: 'Prezzo corrente',
  SAVE: 'Salva',
  SAVE_CHANGES_AND_UPDATE_PLAN: 'Salvare le modifiche e aggiornare il piano?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Seleziona almeno un tipo di utente per continuare',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Hai acquistato Zang Spaces per',
  BUY_NOW: 'Acquista ora',
  SELECT: "Seleziona",
  UP_TO: 'Fino a',
  NO_PURCHASE_REQUIRED: 'nessun acquisto richiesto',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'Nessuna fatturazione o impegno in anticipo.',
  SIGN_UP_FOR_FREE: 'Registrati GRATIS!',
  ONE_YEAR_PLAN: 'Piano di 1 anno',
  MONTHLY_PLAN: 'Piano mensile',
  TWO_YEAR_PLAN: 'Piano di 2 anni',
  MONTHS: 'Mesi',
  ZANG_OFFICE_ACCOUNT_NAME: 'Nome account Zang Office',
  ZANG_OFFICE_PLAN_NUMBER: 'Numero piano Zang Office',
  TEMPORARY_NUMBER: 'Numero temporaneo',
  START_SETTING_UP_ZANG_OFFICE: 'Inizia a configurare Zang Office!',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'Se devi trasferire un numero esistente alla tua soluzione Zang Office, devi inviare un\'e-mail a zosupport@zang.io con il modulo di autorizzazione LNP e una copia della bolletta telefonica più recente. Se devi trasferire un numero verde, allega all\'e-mail anche il modulo RODAA. Tieni presente che il completamento dei trasferimenti potrebbe richiedere fino a 10 giorni lavorativi.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'Si è verificato un errore durante l\'acquisto o l\'attivazione del numeri Zang Office scelti. Fai clic su \'Inizia a configurare Zang Office\' to activate/buy your numbers manually. In case you\'ve chosen to use your existing number, the porting process will not be affected.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'Tenere presente che: se devi trasferire un numero esistente alla tua soluzione Zang Office, devi inviare un\'e-mail con questo <a href="{LNP_FORM_LINK}" target="blank">modulo di autorizzazione LNP</a> insieme a una copia della bolletta telefonica più recente. Se devi trasferire un numero verde, completa anche questo <a href="{RODAA_LINK}" target="blank">modulo RODAA</a>. Invia tutta la documentazione necessaria a <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. Il processo di trasferimento del numero di telefono può richiedere fino a 10 giorni lavorativi.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Tenere presente che il processo di trasferimento del numero di telefono può richiedere fino a 10 giorni lavorativi. Nel frattempo ti forniremo un numero di telefono temporaneo da utilizzare con il tuo account.',
  PLAN_STATUS: 'Stato piano',
  PLAN_ID: 'ID piano',
  SUBSCRIPTION_ID: 'ID abbonamento',
  STRIPE_PLAN_ID: 'ID piano Stripe',
  ACCOUNT_ID: 'ID account',
  START_SETTING_UP_ZANG_SPACES: 'Inizia a configurare Zang Office',
  COMPANY_DOMAIN: 'Dominio azienda',
  THIS_FIELD_IS_REQUIRED: 'Questo campo è obbligatorio.',
  PLEASE_ANSWER_THIS_QUESTION: 'Rispondi alla domanda.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Immetti il tuo ID partner Avaya.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Per continuare, leggi e accetta l\'informativa sulla privacy.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Per continuare, leggi e accetta i Termini del servizio del programma per agenti.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'Questo ID partner Avaya è già in uso.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'Questo codice fiscale è già in uso.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'Questo non è un ID partner Avaya valido.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'La quantità deve essere un numero positivo',
  ORDER_COMPLETE: 'Ordine completato!',
  PLEASE_TRY_AGAIN: 'Riprova',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Seleziona almeno un valore positivo',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'L\'aggiornamento è ancora in corso. Riprova più tardi.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'Non puoi avere più di un utente per una licenza personale. Per l\'upgrade o il downgrade del tuo piano, modifica le quantità di conseguenza.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'Non hai l\'accesso a questo account.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Il tuo piano attuale non ti consente di diminuire gli utenti rispetto alla quantità originale. Se vuoi modificare questo dato, contattaci a customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'Si è verificato un errore durante l\'invio dell\'ordine. Assicurati che tutti i campi contengano valori validi e, se l\'errore persiste, contatta il supporto Zang per maggiori informazioni',

  USE_EXISTING_NUMBER: 'Utilizza numero esistente',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Scegli di utilizzare il tuo numero esistente con il piano',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Preseleziona un numero VERDE',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Seleziona per aggiungere il tuo numero verde al piano',
  FIND_A_LOCAL_NUMBER: 'Trova un numero locale',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Seleziona da un elenco di numeri locali della tua zona il numero da aggiungere al piano',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: 'Seleziona per aggiungere un numero locale al piano',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: 'Cerca i numeri di telefono disponibili in base all\'indicativo località',
  SEARCH_AVAILABLE_PHONE_NUMBERS: 'Cerca i numeri di telefono disponibili',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: 'Immetti il numero esistente da trasferire',


  ZANG_OFFICE_PHONE_APP: 'Applicazione per cellulari Zang Office',
  ZANG_OFFICE_SOFTPHONE: 'Softphone Zang Office',
  ZANG_OFFICE_PHONE_APPLICATION: 'Applicazione per cellulari Zang Office',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Il softphone Zang Office include tutte le funzioni di comunicazione che ti aspetti dal tuo cellulare o dal tuo desktop. Sfrutta i vantaggi di tutte le eccezionali funzioni di Zang Office senza esaurire il budget, grazie al softphone Zang Office incluso gratuitamente nel tuo abbonamento!',
  E129_SIP_DESK_PHONE: 'Deskphone SIP E129',
  STANDARD_PHONE: 'Telefono standard',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Il deskphone SIP Avaya E129 offre tutte le funzioni di gestione delle chiamate di base in un telefono SIP economico ma altamente funzionale. Il deskphone Avaya E129 consente agli utenti di trasferire le chiamate, disattivare il microfono, inoltrare e mettere le chiamate in attesa, nonché avviare conferenze ad hoc con il tocco di un pulsante. Il vivavoce full duplex consente di effettuare conversazioni senza l\'uso delle mani, mentre la porta Power over Ethernet offre un comodo accesso alla rete aziendale. Il deskphone SIP Avaya E129 offre le funzionalità di chiamata più importanti ed è economico ed esteticamente ben realizzato. Adattatore di alimentazione C.A. incluso.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Inizia a utilizzare un dispositivo desktop dedicato, innovativo e completamente in vetro. Usa le app voce, chat e collaborazione tramite collegamenti one-touch. Non vi saranno interruzioni o pause indesiderate. E non dovrai gestire più dispositivi. Inserisci le esperienze personalizzate uniche nei tuoi flussi di lavoro e nei processi di business. Questo potentissimo dispositivo personalizzabile ti offre i vantaggi di un deskphone e la flessibilità di una piattaforma applicativa.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'Telefono per conferenze B179',
  CONFERENCE_PHONE: 'Telefono per conferenze',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Ideale per le sale riunioni e le sale conferenze di grandi dimensioni con gruppi di oltre 10 persone, il telefono per conferenze B179 aiuta a migliorare la produttività e la collaborazione dei dipendenti. Il telefono per conferenze B179 è un prodotto versatile e ad alte prestazioni che completa la tua soluzione esistente ed è facilmente ridistribuibile al cambiare delle dimensioni o delle esigenze aziendali. Adattatore di alimentazione C.A. incluso.',
  PLAN: 'Piano',
  REDIRECTING: 'Reindirizzamento',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Assicurati che tutti i campi abbiano valori validi',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Ogni piano Zang Office richiede almeno un tipo di utente. Torna al passaggio per la selezione dei dispositivi e modifica la configurazione.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'A quanto pare non hai selezionato un numero per il tuo account Zang Office. Torna al passaggio per la selezione del numero per selezionarne uno.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'Questo nome account Zang Office è già in uso. Prova con un altro',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'Il numero Zang Office selezionato è già stato acquistato da un altro cliente. Torna al passaggio per la selezione del numero e selezionane uno diverso.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Scegli il piano mensile e ottieni senza impegno i <span class="text-400">PRIMI 30 GIORNI GRATUITI</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'oppure scegli un piano annuale e ottieni e il prezzo migliore oltre a un',
  FREE_PHONE: 'TELEFONO GRATIS',
  DISCOUNT: 'sconto',
  DISCOUNTED_PHONE: 'telefono scontato',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'di sconto sul valore totale dei tuoi acquisti telefonici',
  LIMITED_TIME_OFFER: 'Offerta limitata nel tempo',
  PROMOTION: 'Promozione',
  ZANG_SPACES_PROMOTION: 'Promozione Zang Spaces',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Continua con la selezione del numero di telefono',
  DURATION: 'Durata',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'Congratulazioni! Hai un credito di <strong>{amount}</strong> da utilizzare sul totale del tuo ordine dei dispositivi!',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'Tutti gli sconti applicabili verranno calcolati all\'interno del riepilogo finale dell\'ordine.',
  SHIPPING_TYPE: 'Tipo di spedizione',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'I dettagli del tracking verranno inviati una volta che gli articoli vengono spediti dal nostro magazzino',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Ricevi un credito di {amount} per l\'acquisto di un dispositivo. Offerta limitata nel tempo.',
  PARTNER_ORDERS: 'Ordini dei partner',
  COMMISSION: 'Commissione',

  ADDITIONAL_DEVICES: 'Dispositivi aggiuntivi',
  NO_USER: 'Nessun utente',
  QUANTITY: 'Quantità',
  BUY_DEVICES: 'Acquista dispositivi',
  DEVICE: 'Dispositivo',
  PRICE: 'Prezzo',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'Digitare almeno {chars} caratteri per cercare un agente',
  NO_RESULTS_FOUND: 'Nessun risultato trovato',
  RESULTS_COULD_NOT_BE_LOADED: 'Impossibile caricare i risultati',
  CLEAR_SELECTION: 'Annulla selezione',


  RESET_ALL_PURCHASES: 'Cancella tutti gli acquisti',
  LISTS: 'Elenchi',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Immetti il tuo numero di telefono prima di creare un preventivo.',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Inserisci le informazioni di fatturazione e spedizione prima di creare un preventivo',
  CALCULATING_TAXES_PLEASE_WAIT: 'Calcolo delle tasse in corso. Attendere...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Qualcosa non ha funzionato con la carta di credito scelta.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Si è verificato un errore con questa carta di credito. Sceglierne una diversa.',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'Si è verificato un errore durante l’addebito dell’ordine. Scegliere una carta di credito differente',
  INVALID_CREDIT_CARD: 'Carta di credito non valida',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type} non corrisponde alle informazioni sull\'indirizzo riportate sulla carta di credito',
  INVALID_SECURITY_CODE: 'Codice di sicurezza non valido (CVC)',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Gli sconti e le promozioni applicabili sono stati applicati a questa fattura',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'Non siamo riusciti a creare il tuo account cliente. Riprova',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Non siamo riusciti a creare la tua carta di credito. Riprova',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Questa carta di credito è in uso per un abbonamento ricorrente.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Errore durante l\'impostazione della carta di credito come predefinita.',
  DEFAULT: 'Predefinita',
  SET_DEFAULT: 'Imposta come predefinita',
  SALES_FORCE_QUOTE_ID: 'ID preventivo Salesforce',
  SALES_FORCE_ORDER_ID: 'ID ordine Salesforce',
  SALES_FORCE_OPPORTUNITY_ID: 'ID occasione Salesforce',
  SALES_FORCE_CONTACT_ID: 'ID contatto Salesforce',
  SALES_FORCE_CONTRACT_ID: 'ID contratto Salesforce',
  SALES_FORCE_ACCOUNT_ID: 'ID account Salesforce',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '\'Aggiungi un dispositivo\' and connect it with a user.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '\'Aggiungere un dispositivo\' e collegarlo a un utente.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Acquista altri dispositivi per il tuo account Zang Office',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'Ops! Si è verificato un problema con il tuo ordine. Aggiorna la pagina, cancella l’ordine e inizia daccapo.',
  CREATE_A_NEW_COMPANY: 'Crea una nuova azienda',
  ADD_A_NEW_COMPANY: 'Aggiungi una nuova azienda',
  PARTNER_DETAILS: 'Dettagli partner',
  AGENTS: 'Agenti',
  PARTNER_PORTAL: 'Portale partner',
  AGENT: 'Agente',
  AGENT_PORTAL: 'Portale agente',
  NO_AGENTS_FOUND: 'Nessun agente trovato',
  NO_AGENT: 'Nessun agente',
  RELATION: 'Relazione',
  OWNER: 'Proprietario',
  ADMIN: 'Amministratore',
  MANAGER: 'Responsabile',
  EMPLOYEE: 'Dipendente',
  ACTIVE: 'Attivo',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: 'Selezionare uno dei partner a cui si è associati',
  APPLIED_ON: 'Applicato su',
  JOIN_A_PARTNER: 'Unisciti a un partner',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'Stai per unirti a <b>{COMPANY_NAME}</b>',
  JOIN_PLACEHOLDER_NOW: 'Unisciti a {COMPANY_NAME} ora',
  UPDATE_AGENT_INFO: 'Aggiorna informazioni agente',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Inizia con Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'In associazione con Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'Una soluzione di collaborazione semplice, potente e unificata',
  IP_OFFICE_DONT_PAY_TILL: 'Non dovrai pagare fino al 15 aprile 2018!',
  LOGIN: 'Accedi',
  DISCOVER: 'Scopri',
  SOLUTIONS: 'Soluzioni',
  SERVICES: 'Servizi',
  INDUSTRIES: 'Settori',
  CASE_STUDIES: 'Case study',
  PROGRAMS_AND_PROMOTIONS: 'Programmi e promozioni',
  AUTHENTIC_AVAYA: 'Avaya autentico',
  PERSPECTIVES: 'Prospettive',
  AVAYA_CONNECTED_BLOG: 'Blog connesso di Avaya',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: 'Strumento di ricerca soluzioni',
  INFO_FOR: 'Informazioni su',
  DEVELOPERS: 'Sviluppatori',
  CHANNEL_PARTNERS: 'Partner di canale',
  TECHNOLOGY_PARTNERS: 'Partner di tecnologia',
  CONSULTANTS: 'Consulenti',
  INVESTORS: 'Investitori',
  MEDIA_ANALYSTS: 'Analisti contenuti multimediali',
  SUPPLIERS: 'Fornitori',
  CONNECT_WITH_US: 'Connettiti con noi',
  FIND_A_CHANNEL_PARTNER: 'Trova un partner di canale',
  FIND_A_TECHNOLOGY_PARTNER: 'Trova un partner di tecnologia',
  EXECUTIVE_BRIEFING_CENTER: 'Executive Briefing Center',
  AVAYA_LEARNING_SERVICES: 'Servizi di apprendimento Avaya',
  CONTACTS: 'Contatti',
  ABOUT_AVAYA: 'Informazioni su Avaya',
  EVENTS: 'Eventi',
  NEWSROOM: 'Newsroom',
  INVESTOR_RELATIONS: 'Rapporti con gli investitori',
  CORPORATE_RESPONSIBILITY: 'Responsabilità aziendali',
  OUR_COMPANY: 'La nostra azienda',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'International Avaya Users Group - IAUG',
  CAREERS: 'Lavora con noi',
  YOUR_PERSONAL_LINK: 'Link personale',
  SITEMAP: 'Mappa del sito',
  TERMS_OF_USE: 'Termini d\'utilizzo',
  PRIVACY: 'Privacy',
  COOKIES: 'Cookie',
  AVAYA_INVOICE: 'Fattura',
  IP_OFFICE_ACCOUNT_NAME: 'Nome account Avaya Cloud',
  IP_OFFICE_PLAN_NUMBER: 'Numero piano Avaya Cloud',
  IP_OFFICE_PHONE_APPLICATION: 'Softphone Avaya Cloud Solutions',
  IP_OFFICE_PHONE_DESCRIPTION: 'Il softphone Avaya Cloud Solutions offre agli utenti un accesso semplificato ai canali di comunicazione in un\'unica interfaccia. Il softphone Avaya Cloud Solutions consente di accedere ad Avaya Cloud Solutions ed effettuare e ricevere chiamate vocali e videochiamate dall\'interno deskphone mediante il PC. Il softphone è incluso gratuitamente negli abbonamenti utente Standard e Power per Avaya Cloud Solutions.',
  PLAN_MONTH_1_MONTH_1: 'Piano mensile (nessun credito per dispositivo)',
  PLAN_YEAR_1_MONTH_1: 'Piano da 1 anno | Fatturato mensilmente',
  PLAN_YEAR_1_YEAR_1: 'Piano da 1 anno, paga l\'intero importo',
  PLAN_YEAR_2_MONTH_1: 'Piano da 2 anni | Fatturato mensilmente',
  PLAN_YEAR_2_YEAR_1: 'Piano da 2 anni | Fatturato annualmente',
  PLAN_YEAR_2_YEAR_2: 'Piano da 2 anni, paga l\'intero importo',
  PLAN_YEAR_3_MONTH_1: 'Piano da 3 anni | Fatturato mensilmente',
  PLAN_YEAR_3_YEAR_1: 'Piano da 3 anni | Fatturato annualmente',
  PLAN_YEAR_3_YEAR_3: 'Piano da 3 anni, paga l\'intero importo',
  PLAN_YEAR_5_MONTH_1: 'Piano da 5 anni | Fatturato mensilmente',
  ACCORDING_TO_PLAN: 'In base al piano',
  TOTAL_USER_PLAN_FEE: 'Tariffa totale per piano utente',
  HEALTHCARE_DENY_MESSAGE: 'Grazie per aver scelto le soluzioni Avaya Cloud. Purtroppo, non disponiamo ancora della compatibilità HIPAA e non possiamo quindi fornirti il nostro servizio poiché lavori nel settore sanitario.  Ti invieremo una notifica quando otterremo la certificazione e speriamo di rivederti!  Per qualsiasi domanda, scrivici all\'indirizzo <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a>.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Seleziona i tuoi dispositivi Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Seleziona il tuo numero Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'Modifica gli utenti e assegna loro i dispositivi.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Aggiungi un numero di telefono da utilizzare per Avaya Cloud Solutions.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'Assegna un numero di telefono alla tua soluzione.',
  INVITE_A_NEW_AGENT: 'Invita un nuovo agente',
  I_WANT_TO_INVITE_A: 'Voglio invitare un',
  CONTACT_EMAIL: 'E-mail contatto',
  CONTACT_NAME: 'Nome contatto',
  COMPANY_NAME: 'Nome azienda',
  CONTACT: 'Contatto',
  COMPANY_IS_INCORPORATED: 'L\'azienda è incorporata',
  INDIVIDUAL: 'Singolo',
  INDIVIDUALS: 'Singoli',
  SEND_INVITATION_EMAIL: 'Invia e-mail di invito',
  SENDING_INVITATION_EMAIL: 'Invio dell\'e-mail di invito in corso...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: 'Invito inviato correttamente',
  ALL_FIELDS_ARE_REQUIRED: 'Tutti i campi sono obbligatori',
  PARTNER_NOT_FOUND: 'Partner non trovato',
  SALE_AGENT_REGISTRATION: 'Registrazione agente di vendita',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: 'Compila il modulo qui sotto per diventare un agente di vendita per',
  VIEW: 'VISUALIZZA',
  COMPANIES: 'Aziende',
  ADD_A_PARTNER: 'Aggiungi un partner',
  ADD_PARTNER: 'Aggiungi partner',
  PARTNERS_PERSONAL_LINK: 'Link personale del partner',
  MASTER_SALES_AGENT: 'Agente di vendita master',
  AVAYA_J129_LABEL: 'Telefono IP J129',
  AVAYA_J129_DESCRIPTION: 'Sfrutta tutte le più utili funzioni di gestione delle chiamate in un telefono IP conveniente ma estremamente funzionale. Questo telefono offre le funzioni principali necessarie nelle aziende di tutte le dimensioni. Il telefono supporta due stati chiamata con display a linea singola. Acquista un telefono con funzioni affidabili che batte tutta la concorrenza disponibile oggi sul mercato.',
  AVAYA_J169_LABEL: 'Telefono IP J169',
  AVAYA_J169_DESCRIPTION: 'Sfrutta tutte le più utili funzioni di gestione delle chiamate in un telefono IP conveniente ma estremamente funzionale. Questo telefono offre le funzioni principali necessarie nelle aziende di tutte le dimensioni. Il telefono supporta due stati chiamata con display a linea singola. Acquista un telefono con funzioni affidabili che batte tutta la concorrenza disponibile oggi sul mercato.',
  AVAYA_J179_LABEL: 'Telefono IP J179',
  AVAYA_J179_DESCRIPTION: 'Sfrutta tutte le più utili funzioni di gestione delle chiamate in un telefono IP conveniente ma estremamente funzionale. Questo telefono offre le funzioni principali necessarie nelle aziende di tutte le dimensioni. Il telefono supporta due stati chiamata con display a linea singola. Acquista un telefono con funzioni affidabili che batte tutta la concorrenza disponibile oggi sul mercato.',
  AVAYA_K175_LABEL: 'Avaya Vantage™ K175',
  AVAYA_K175_DESCRIPTION: 'Sfrutta tutte le più utili funzioni di gestione delle chiamate in un telefono IP conveniente ma estremamente funzionale. Questo telefono offre le funzioni principali necessarie nelle aziende di tutte le dimensioni. Il telefono supporta due stati chiamata con display a linea singola. Acquista un telefono con funzioni affidabili che batte tutta la concorrenza disponibile oggi sul mercato.',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: 'Deskphone IP 9641GS',
  AVAYA_9641G_DESCRIPTION: 'Il telefono Avaya 9641GS è un deskphone premium con più linee adatto per chi trascorre moltissimo tempo al telefono e fa affidamento sulle funzionalità smart di miglioramento delle comunicazioni e della produttività. Il modello 9641GS è dotato di un display grafico a colori da 5,0 pollici, ampio touch screen e audio ad alta definizione. Il suo codec audio a banda larga offre prestazioni eccezionali su tutte le interfacce, inclusi ricevitori, cuffie e altoparlanti.',
  AVAYA_9608G_LABEL: 'Deskphone IP 9608G',
  AVAYA_9608G_DESCRIPTION: 'Il deskphone 9608G è un telefono conveniente e funzionale con supporto per gigabit integrato e display monocromatico. Power over Ethernet semplifica la distribuzione e il codec audio a banda larga offe prestazioni eccezionali. Progettato per le piccole e grandi imprese, questo deskphone include l\'accesso a otto linee ed è dotato di etichette grafiche che possono essere gestite centralmente.',
  AVAYA_9611G_LABEL: 'Deskphone IP 9611G',
  AVAYA_9611G_DESCRIPTION: 'Il modello 9611G include gigabit integrato e un\'interfaccia USB. È dotato di un display grafico a colori da 3,5 pollici con retroilluminazione bianca ed etichette grafiche che possono essere gestite centralmente. Power over Ethernet semplifica la distribuzione e il codec audio a banda larga offre prestazioni eccezionali.',
  AVAYA_PHONE_B179_LABEL: 'Telefono SIP per conferenze B179',
  AVAYA_PHONE_B179_DESCRIPTION: 'Testato da Tolly, questo telefono flessibile per conferenze basato su SIP offre un audio chiaro e naturale grazie a OmniSound 2.0, la tecnologia audio a banda larga brevettata da Avaya. Il telefono è ricco di funzioni smart per chiamate in conferenza più efficienti. Utilizza la guida alla conferenza per chiamare gruppi pre-programmati. Importa ed esporta i dettagli dei contatti tramite l\'interfaccia Web. Crea il tuo elenco di contatti con la funzione del profilo utente personale.',
  HAVE_LARGE_NUMBERS_OF_USERS: 'Hai tanti utenti?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'Scopri i nostri sconti sui grandi volumi.',
  DEVICE_FEE: 'Tariffa per dispositivo',
  UP_TO_DEVICE_CREDITE_PER_USER: 'Fino a {$} di credito dispositivo per utente',
  PROMOTION_REMAINING_DETAIL_INFO: 'Hai ancora <b>{0}</b> crediti dispositivo promozionali da spendere. Tieni presente che tutto il credito residuo non sarà più valido dopo l\'acquisto e non verrà trasferito al tuo account per gli acquisti futuri.',
  VIEW_USER_FEATURES: 'Visualizza funzioni utente',
  FREE_DEVICES_PER_USER_INFO: '{0} (Fino a {1} credito dispositivo per utente)',
  VALUE_OF_DEVICE_CREDIT: '{0} utenti = {0} in crediti dispositivo totali',
  PROMOTION_DELAYED_BILLING_INFO: 'Promozione: verrà fornita una ricevuta dettagliata e gli importi in sospeso verranno addebitati sulla carta di credito all\'inizio del ciclo di fatturazione.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'Selezionare un agente per completare l\'ordine',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: 'Fornire un nome dominio valido (esempio.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Il tuo sistema Avaya Cloud Solution è pronto!',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Il tuo sistema Avaya Cloud Solution è configurato!',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Numero di telefono per Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Nome dominio SIP per Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_ID: 'ID dominio SIP per Avaya Cloud Solutions',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Il sistema Avaya Cloud Solution è in fase di configurazione.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'Ti ringraziamo per il tuo ordine. Stiamo configurando il tuo sistema Avaya Cloud Solutions e ti contatteremo al termine del processo. <br /> Per qualsiasi domanda, contatta il supporto di Avaya Cloud Solutions all\'indirizzo {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'Provisioning per questo account non riuscito',
  ERROR_CODE: 'Codice errore',
  ERROR_MESSAGE: 'Messaggio di errore',
  ADMIN_PORTAL_LINK: 'Link al portale amministratore',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Password predefinita per l\'utente Avaya Cloud Solutions',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Numero di telefono temporaneo per Avaya Cloud Solutions',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'Interni utente Basic',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Interni utente Standard',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'Interni utente Power',
  IP_OFFICE_DEFAULT_USER_PIN: 'Pin utente predefinito',
  IP_OFFICE_SAME_AS_PIN: 'Uguale all\'interno (ad es.: 200)',
  IP_OFFICE_ORDERID: 'ID ordine Avaya Cloud Solutions',
  IP_OFFICE_HOST_NAME: 'Nome host Avaya Cloud Solutions',
  IP_OFFICE_IP_ADDRESS: 'Indirizzo IP Avaya Cloud Solutions',
  IP_OFFICE_SUBSCRIPTIONID: 'ID abbonamento Avaya Cloud Solutions',
  CALCULATING: 'calcolo in corso...',
  RESET_ALL_PARTNERS: 'Cancella dati partner',
  ERROR_GETTING_AGENTS: 'Errore durante la verifica degli agenti. Riprova',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Un agente con questo indirizzo e-mail esiste già nel tuo team',
  AUTO_APPROVE_ACTIVATE_AGENT: 'Approva/attiva automaticamente agente',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Un\'azienda con questo indirizzo e-mail esiste già nel tuo team',
  MASTER_SALES_AGENT_PORTAL: 'Portale agente di vendita master',
  SALES_AGENT_PORTAL: 'Portale agente di vendita',
  E911_ADDRESS: 'Indirizzo E911',
  OVERVIEW: 'Panoramica',
  ADD_COMPANY_OR_SALES_AGENT: 'Aggiungi un\'azienda o un agente',
  ADD_AN_AGENT: 'Aggiungi un agente a',
  INACTIVE: 'Inattiva',
  AGENTS_PERSONAL_CONNECTION_LINK: 'Link di connessione personale dell\'agente',
  PURCHASE_DATE_AND_CUSTOMER: 'Data di acquisto e cliente',
  ORDER_DETAILS: 'Dettagli ordine',
  SELECT_AGENT: 'Tutti gli agenti',
  FROM: 'da',
  TO: 'a',
  EXPORT_REPORT: 'Esporta rapporto',
  NO_SALES_FOUND: 'Nessuna vendita trovata',
  ADD_A_COMPANY: 'Aggiungi un\'azienda',
  AUTO_APPROVE_COMPANY: 'Approva automaticamente azienda',
  AUTO_ACTIVATE_AGENT: 'Attiva automaticamente agente',
  ADD_COMPANY: 'Aggiungi azienda',
  ADD_COMPANY_NAME_AGENT_ADMIN: 'Aggiungi agente/amministratore di {COMPANY_NAME}',
  ADD_AGENT_ADMIN: 'Aggiungi agente/amministratore',
  ALL_COMPANIES: 'Tutte le aziende',
  START_DATE: 'Data di inizio',
  HEY: 'Salve',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: 'Siamo i tuoi responsabili Customer Success. Siamo qui per aiutarti a sfruttare al meglio le soluzioni Avaya Cloud. Il team del supporto Avaya Cloud Solutions include anche il nostro team del supporto tecnico - <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: 'Nei prossimi giorni vorremmo programmare una chiamata per presentarti il team del supporto e terminare la configurazione del sistema. <strong>Contattaci all\'indirizzo <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> e indica il giorno e l\'ora che preferisci per effettuare una chiamata da un\'ora.<strong>',
  START_USING_YOUR_IP_OFFICE: 'Inizia a utilizzare il tuo sistema Avaya Cloud Solutions ora!',
  BELOW_ARE_DETAILS: 'Qui sotto sono riportate le informazioni dell\'account di sistema, le credenziali dell\'utente e i download dell\'applicazione:',
  YOUR_IP_OFFICE_INFO: 'Informazioni sul tuo sistema:',
  LOGIN_INFO_TABLE: 'Grafico sulle informazioni utente:',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'Tutti gli utenti possono configurare le proprie informazioni, modificare l\'inoltro chiamate, ascoltare i messaggi vocali e molto altro utilizzando le informazioni qui sopra e accedendo ai rispettivi Portali utente cloud.',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'Applicazioni disponibili per gli utenti:',
  DO_NOT_HESITATE_TO_EMAIL_US: 'Per qualsiasi domanda, non esitare a inviarci un\'e-mail all\'indirizzo <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a>!',
  THANK_YOU: 'Grazie,',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web (estensione di Chrome)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Soft console Avaya Cloud Solutions (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">Installa documento</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">Installa documento</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">Installa documento</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">Installa documento</a>',




  USER_NAMES_COLUMN: 'Nome utente',
  EXTENSIONS_COLUMN: 'Int',
  TEMP_PIN_COLUMN: 'Pin',
  TEMP_PASSWORD_COLUMN: 'Password',
  USER_TYPE_COLUMN: 'Tipo di utente',
  DEVICE_MODEL_COLUMN: 'Dispositivo',
  POWER_USER: 'Power',
  STANDARD_USER: 'Standard',
  BASIC_USER: 'Basic',
  ORDERID: 'ID ordine',
  ACCOUNT_NAME: 'Nome account',
  HOST_NAME: 'Nome host',
  ADMIN_PORTAL: 'Portale di amministrazione',
  IP_ADDRESS: 'Indirizzo IP',
  PHONE_NUMBER: 'Numero di telefono',
  TEMPORARY_PHONE_NUMBER: 'Numero di telefono temporaneo',
  EXCITING_TIMES_AHEAD: 'Ti aspetta un periodo entusiasmante',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'Il nome dominio {DOMAIN_NAME} non è valido oppure è utilizzato da un’altra azienda.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'Il nome dominio {1} non è valido oppure è utilizzato da un’altra azienda.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: 'Il sistema potrebbe non confermare la tua azienda. Riprova',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'Per informazioni N/D (se presenti), contatta il supporto Avaya Cloud: ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Impossibile avviare il provisioning di un account Avaya Cloud',
  LEGAL: 'Legale',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Seleziona un Piano da 1 anno (o più) per ricevere un credito per utente da utilizzare per l\'acquisto di un dispositivo. Offerta limitata.',
  USER_PORTAL: 'Portale utente',
  E_911: 'E911',
  DECLINE: 'Rifiuta',
  ACCEPT: 'Accetta',
  PRINT: 'Stampa',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'Accetta tutti i termini qui sopra per completare l\'ordine',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'Assegna un dispositivo ai tuoi utenti.',
  SELECT: 'Seleziona',
  USER_DETAILS: 'Dettagli utente',
  DEVICE_DETAILS: 'Dettagli dispositivo',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: 'Leggi attentamente i nostri Termini di servizio prima di accettare.',
  PARTNER_ORDERS_RECORDS_HINT: '*Tutti i record di vendita sono indicati solo per riferimento. I report di vendita ufficiali e definitivi verranno forniti da Avaya in conformità con l\'accordo per gli agenti di vendita master.',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: 'Selezionare un agente di vendita per creare il preventivo',
  COMPANY_DETAILS: 'Dettagli azienda',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'Più imposte applicabili.',
  SELECT_PRODUCT: 'Seleziona prodotto',
  CLOUD_UC_SMALL_MONTH1: 'Cloud UC Essentials mensile',
  SMALL: 'Piccole imprese',
  CLOUD_UC_SMALL_MONTH12: 'Piano da 1 anno per Cloud UC Essentials',
  CLOUD_UC_SMALL_3YEARS: 'Piano da 3 anni per Cloud UC Essentials',
  CLOUD_UC_SMALL_5YEARS: 'Piano da 5 anni per Cloud UC Essentials',
  MEDIUM: 'Medie imprese',
  CLOUD_UC_MEDIUM_MONTL1: 'Piano mensile per Cloud UC Business',
  CLOUD_UC_MEDIUM_MONTH12: 'Piano da 1 anno per Cloud UC Business',
  CLOUD_UC_MEDIUM_3YEARS: 'Piano da 3 anni per Cloud UC Business',
  CLOUD_UC_MEDIUM_5YEARS: 'Piano da 5 anni per Cloud UC Business',
  LARGE: 'Grandi imprese',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC Large con pagamento a consumo',
  CLOUD_UC_LARGE_MONTL12: 'Piano annuale per Cloud UC Large',
  CLOUD_UC_SMALL_SHORT_INFO: '1 - 99 dipendenti',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100 - 999 dipendenti',
  CLOUD_UC_LARGE_SHORT_INFO: '1000+ dipendenti',
  SELECTED: 'Selezionato',
  BASIC_PHONE_SERVICE: 'Servizio telefonico di base',
  UNLIMITED_NATIONAL_WIDE: 'Chiamate nazionali illimitate',
  STANDARD_FEATURES: 'Funzioni standard',
  HOW_MANY_USERS: 'Di quanti utenti hai bisogno?',
  ADD_ON_ADDITIONAL_FEATURES: 'Funzioni aggiuntive',
  ONETIME_FEE: 'Tariffa una tantum',
  RECURRING_FEE: 'Tariffa ricorrente',
  SELECT_MAIN_NUMBER: 'Seleziona numero principale',
  TOLL_FREE: 'Numero verde',
  LOCAL_NUMBER: 'Numero locale',
  TRANSFER_NUMBER: 'Trasferisci numero',
  USERS_COUNT: '{qty} utenti',
  DEVICES_COUNT: '{qty} dispositivo(i)',
  UC_OFFER_TITLE: 'Abbiamo la soluzione giusta per te!',
  UC_OFFER_DESCRIPTION: 'Non importa se sei una piccola, media o grande impresa: abbiamo quello che stai cercando! Che tipo di azienda possiedi?',

  // 'BASIC_PHONE_SERVICE': 'Servizio telefonico di base',

  TAX_CALC_ERROR_MSG: 'Impossibile calcolare l\'imposta. Verifica che l\'indirizzo di fatturazione sia corretto.',
  'VIOLATION.FIELD_IS_EMPTY': '{1} è obbligatorio',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} - {2} è obbligatorio',
  'VIOLATION.FIELD_VALUE_INVALID': 'Valore {1} non valido',
  'VIOLATION.FIELD_VALUE_INVALID2': 'Valore {1} - {2} non valido',
  'VIOLATION.TAX_CALCULATION_FAILED': 'Impossibile calcolare l\'imposta',
  'VIOLATION.AGREE_ON_LEGAL_DOC': 'Leggere e accettare i "{1}"',
  'VIOLATION.CART_IS_EMPTY': 'Il carrello è vuoto',
  'VIOLATION.CART_IS_TOO_BIG': 'Il carrello ha troppi articoli',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} è stato rimosso dal carrello',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': 'La quantità di {1} è stata modificata da {2} a {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': 'Lo sconto di {1} è stato modificato da {2} a {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': 'Impossibile aggiungere un articolo con valuta {1} al carrello con valuta {2}',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': 'La regola dello sconto {1} non è stata definita',
  'SALESMODELRULE.UNKNOWN_ERROR': 'Errore sconosciuto',
  'SALESMODELRULE.INVALID_PARAMETER': 'Parametro non valido: {1}',
  ONE_TIME: 'Una tantum',
  ADDON_PRICING_HINT: '*Il prezzo per i componenti aggiuntivi è calcolato per posto ed è applicato a tutti gli utenti. È possibile aggiungere componenti aggiuntivi specifici dopo l\'acquisto dal portale di amministrazione.',
  ADD_TO_CART_HINT: 'Completa i passaggi qui sopra per aggiungere al carrello',
  ITEM_UNITS: '{qty} unità',
  ADDONS_COUNT: '{qty} componenti aggiuntivi',
  ADDON_COUNT: '{qty} componente aggiuntivo',
  MULTIPLE_TYPES: 'Più tipi',
  MIXED: 'Misti',
  FREE_PRICE: 'GRATUITO',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essentials',
  UC_ESSENTIALS_DESCRIPTION: 'Il miglior sistema di comunicazione basato su cloud per le aziende di qualsiasi dimensione.',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: 'Offri alla tua azienda il più recente sistema di comunicazione aziendale su cloud',
  UC_BUSINESS_POWER_PACKAGE: 'Effettua l\'upgrade agli utenti POWER',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>Numero di telefono diretto:</strong> numero unico e dedicato, così chiunque può chiamarti direttamente senza dover passare per il numero principale dell\'ufficio e il receptionist (virtuale o umano).</li><li><strong>Videochiamata diretta:</strong> aggiungi il video alle tue chiamate telefoniche punto a punto.</li><li><strong>Integrazione Salesforce©:</strong> sistema di comunicazione completo per gli utenti finali direttamente da Salesforce.</li><li><strong>Integrazione Google©:</strong> comunicazioni in tempo reale basate sul browser direttamente da Google Chrome e in tutte le tue app Google.</li><li><strong>Integrazione Skype for Business©:</strong> esperienza di collaborazione moderna, ottimizzata e facile da usare con Skype for Business.</li></ul>',
  SHOW_MORE: 'Mostra altro',
  HIDE: 'Nascondi',
  VIEW_COMPLETE_FEATURE_LIST: ' Visualizza l\'elenco funzioni completo',
  FILTER_BY: 'Filtra per',
  UC_OFFERS: 'Soluzioni UC',
  PAY_MONTHLY: 'Paga mensilmente',
  PAY_ANNUALLY: 'Paga annualmente',
  COMING_SOON: 'Disponibile a breve',
  TAX_CALC_ERROR_MSG: 'Impossibile calcolare l\'imposta. Verifica che l\'indirizzo sia corretto.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: 'Inserire il nome di un Paese per consultare le tariffe attuali per le chiamate internazionali.',
  LONG_DISTANCE_RATE_NOT_FOUND: 'Tariffe per chiamate internazionali non trovate per questo Paese, contattare {CUSTOMER_SUCCESS_EMAIL} per informazioni sulle chiamate personali a questo Paese.',
  AREA_CODE: 'Indicativo località',
  INVALID_CREDIT_CARD_ZIP: 'La carta di credito non corrisponde al CAP.',
  VIEW_LONG_DISTANCE_RATES: 'Visualizza tariffe per chiamate internazionali',
  LONG_DISTANCE_SUBTITLE_TEXT: 'Le nostre tariffe ridotte per le chiamate internazionali ti permettono di rimanere in contatto con chi conosci in tutti i Paesi del mondo.',
  RATES_SUBJECT_TO_CHANGE: '*Tariffe soggette a cambiamento senza previa notifica.',
  CREDIT_CARD_DECLINED: 'La carta di credito è stata rifiutata.',
  ENTER_COUNTRY_NAME: 'Inserisci nome del Paese',
  ADD_TO_CART: 'Aggiungi al carrello',
  UPDATE_CART: 'Aggiorna carrello',
  PER_USER: 'Per utente',
  COMPARE_UC_OFFERS: 'Confronta le offerte UC',
  PROCEED_TO_CHECKOUT: 'Procedi con il check out',
  BEFORE_APPLICABLE_TAXES: '* Prima delle imposte applicabili',
  YEAR_PLAN: 'Piano di 1 anno',
  YEARS_PLAN: 'Piano di {0} anni',
  MONTHS_PLAN: 'Piano di {0} mesi',
  ENTER_NUMBER_OF_USERS: 'Inserisci il numero di utenti per questa soluzione',
  YEAR: 'Anno',
  BILLED_MONTH: 'Fatturato mensilmente',
  COMPANY_INCORPORATED: 'Incuso',
  COMPANY_NOT_INCORPORATED: 'Non incluso',
  EXISTING_CONFIG_WARNING: 'Hai una configurazione esistente per <br/><b>{0}</b>.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: 'Annullare la configurazione corrente?',
  DISCARD_MY_CONFIGURATION: 'Annulla configurazione',
  DISCARD: 'Annulla',
  EDIT_MY_CONFIGURATION: 'Modifica la configurazione corrente',
  CONTINUE: 'Continua',
  SELECT_A_PLAN: 'Seleziona un piano',
  PROMOTION_DETAIL_INFO: '*Hai selezionato <b>{0} utenti</b>,<br/> equivalenti a <b>{1}</b> in crediti dispositivo totali.',
  BILLED_MONTH_FREQUENCY: 'Fatturato ogni {0} mesi',
  BILLED_YEAR_FREQUENCY: 'Fatturato ogni {0} anni',
  CONTACT_OUR_CUSTOMER_CARE: 'Contatta il team dell\'assistenza clienti',
  NEED_HELP_INFO: 'Hai bisogno di aiuto? Il nostro team dell\'assistenza clienti è pronto ad aiutarti in caso di domande, problemi o informazioni.',
  REMOVE: 'Rimuovi',
  REMOVE_ITEM_FROM_CART_WARNING: 'Rimuovere <b>{0}</b> dal carrello?',
  NO_ITEM_IN_THE_CART: 'Non ci sono articoli nel carrello.',
  CONTINUE_SHOPPING: 'Continua con lo shopping',
  TOTAL_TAXES: 'Imposte totali',
  UC_SOLUTIONS: 'Soluzioni UC',
  UNIFIED_COMMUNICATIONS: 'Unified Communications',
  ADD_ONS: 'Componenti aggiuntivi',
  SYSTEM_ADDONS: 'Componenti aggiuntivi di sistema',
  ADD_DEVICES: 'Aggiungi dispositivi',
  SELECT_UPTO_DEVICES: 'Seleziona fino a (<b>{0}</b>) dispositivi per <b>{1}</b>',
  DONE: 'Fine',
  SELECT_DEVICES: 'Seleziona dispositivi',
  EDIT_DEVICE_SELECTION: 'Modifica dispositivi',
  ESSENTIAL_USERS: 'Utenti Essential',
  BUSINESS_USERS: 'Utenti Business',
  POWER_USERS: 'Utenti Power',
  N_A: 'N/D'
}
