export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'アカウントシステムのデータ暗号化を解除できない',
  PHONE_TYPES: '電話のタイプ',
  IMAGINE_A_BETTER_WAY: '今よりもよい方法は',
  OF_DOING_THINGS: 'きっとある。',
  GET_STARTED: '開始',
  PURCHASE: '購入する',
  DOWNLOADS_AND_EXTENSIONS: 'ダウンロード＆拡張機能',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: 'Zangの製品を最大限に活用するための必携アドオン',
  ALL: '全て',
  REFERRAL_AGENT: '紹介代理店',
  SALES_AGENT: '販売代理店',
  CART: 'カート',
  PARTNER_PROGRAMS: 'パートナープログラム',
  HOME: 'ホーム',
  MANAGE_CREDIT_CARDS: 'クレジットカードを管理',
  MANAGE_PAYMENT_OPTIONS: 'お支払いオプションの管理',
  MANAGE_BILLING_ACCOUNT: '請求先アカウントの管理',
  LIMIT: "制限",
  MY_PROFILE: 'マイプロフィール',
  MY_SETTINGS: 'マイ設定',
  MY_PARTNER_PORTAL: 'マイパートナーポータル',
  CLEAR_ZANG_OFFICE: 'Zang Officeをクリア',
  CLEAR_ZANG_SPACES: 'Zang Spacesをクリア',
  FEATURE_BREAKDOWN: '機能詳細',
  PLAN_BREAKDOWN: 'プラン詳細', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: '必要な業務用電話を、低価格で',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Zang Spaces で何ができるでしょうか',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '50% の割引は、チェックアウト後の合計金額に適用されます',
  HURRICANE_HARVEY_MESSAGE: 'AvayaとZangは、ハリケーン・ハービーの影響を受け、またハリケーン・イルマの影響を受ける可能性のある企業を支援したいと考えています。影響を受けた、テキサスおよびルイジアナ、フロリダ、アラバマ、ジョージア、ノースカロライナ、サウスカロライナ、テネシー、ミシシッピ州の企業はただちに、<b>Zang Office</b>と<b>Zang Spacesを無料で</b>3か月受け取ることができます。',
  LEARN_MORE: '詳細',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ を利用できるようになりました',
  NEW: 'New!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'このすべてガラス製で使いやすい、音声とビデオ、チャットのコラボレーション電話で、Zang Officeのすべてをご体験ください。',
  LOG_IN: 'ログイン',
  SIGN_UP: '登録',
  SIGN_OUT: 'サインアウト',
  SIGN_IN: 'サインイン', //login to the system, connect
  ADMINISTRATION: '管理',
  PRODUCTS: '製品',
  ORDERS: '注文',
  PAGES: 'ページ',
  CUSTOMERS: '顧客',
  USERS: 'ユーザー',
  PLANS: 'プラン',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'CDR',
  CDR_CHECKS: 'CDRチェック',
  PARTNERS: 'パートナー',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'すでにZang Officeをご購入されているようです。これ以上Zang Officeの注文は行えません。',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'この会社はすでに Avaya Cloud を購入済みのようです。別の会社を選択してください。',
  PARTNER_CONNECTIONS: 'パートナーコネクション',
  CHECK_OUT_GENERAL_FATAL_ERROR: '注文時にエラーが発生しました。詳細については、Zangサポート({SUPPORT_EMAIL})までお問い合わせください',
  APPLICATION_GENERAL_FATAL_ERROR: '申し込みの送信にエラーが発生しました。詳細については、Zangサポート({SUPPORT_EMAIL})までお問い合わせください',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: '続行するには少なくとも1つのユーザータイプを選択してください。',
  BACK: '戻る',
  SAVE_CHANGES: '変更を保存',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: '続行します。よろしいですか?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'クレジットに、あらゆるデバイスの購入に使える{PLACEHOLDER}があります。このクレジットは、注文を送信するとなくなります。',
  JUST_A_REMINDER: 'お知らせ',
  LAST_CHANCE: '最後のチャンス',
  IM_GOOD_PLACE_MY_ORDER: '了解 - 注文を発注',
  BUY_MORE_DEVICES: 'さらにデバイスを購入',
  YES_PLACE_MY_ORDER: 'はい、注文を発注します',
  NO_THANKS: 'いいえ、結構です。',
  YES: 'はい',
  ABOUT_US: '当社について',
  NEWS_AND_PRESS: 'ニュース＆プレス',
  CARREERS: '採用情報',
  CONTACT_US: 'お問い合わせ先',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'ご利用いただきありがとうございます。ご注文内容は以下のとおりです。',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: '詳細については、<a href="mailto:{EMAIL}">{EMAIL}</a> にお問い合わせください',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'お使いになるシステムの準備が整いましたら Zang Customer Success チームと Technical Support チームからご連絡します。<br/><br/><b>システムの設定には最大 1 時間かかる場合があります。</b>',
  QUESTION_CUSTOMER_SERVICE: 'ご不明の点については <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a> までメールでお問い合わせください。',
  BLOG: 'ブログ',
  FAQS: 'FAQ',
  DOCUMENTATION: 'ドキュメント',
  TERMS_OF_SERVICE: 'サービス利用規約',
  HELP: 'ヘルプ',
  PRIVACY_STATEMENT: 'プライバシーポリシー',
  GENERAL_PRIVACY_STATEMENT: '一般プライバシーポリシー',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: '一般サービス利用規約 - Avaya Cloud Solutions',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. All Rights Reserved.',
  PROCESSING: '処理中です',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'しばらくお待ちください。少し時間がかかることがあります。',
  OPEN_IN_A_NEW_TAB: '新しいタブで開く',
  GOT_IT: '了解',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' このアクションを行うと次の結果になります:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'このプランの月間サブスクリプションを削除',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: '全てのサードパーティシステム上のアカウントが無効',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'このプランのステータスを無効に変更',
  LAST_ACTION_STEPS: '最後のアクションのステップ',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'アドオンは、アカウント作成後、Zang Office管理者ポータルを通じ購入します。',
  TYPE: 'タイプ',
  ADMIN: '管理者',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'このユーザーは、法人アカウントの主たる連絡先/請求先として設定されます。Zang Office管理者ポータルを通じ、いつでも変更できます。',
  DESCRIPTION: '内容',
  SUCCESS: '成功',
  REQUEST_CANCELATION: '解約依頼',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: '解約されるとのこと、残念です。',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '以下のフォームに記入し、解約手続きにお進みください。カスタマーサクセス部門の担当者が拝見し、1〜2営業日以内にご連絡します。',
  YOUR_NAME: 'お名前',
  COMPANY: '会社',
  SERVICE: 'サービス',
  REASON_FOR_CANCELING: '解約理由',
  SUBMIT: '送信',
  EXIT: '終了',
  REQUEST_SUBMITTED: 'リクエストが送信されました',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'カスタマーサクセス部門の担当者が拝見し、1〜2営業日以内にご連絡します。',
  DATE: '日付',
  PRODUCT: '製品',
  USER: 'ユーザー',
  STATUS: 'ステータス',
  ACTIONS: '操作',
  VIEW_DETAILS: '詳細を表示',
  DISABLE: '無効にする',
  ENABLE: '有効にする',
  CANCEL: 'キャンセル',
  PLAN_DETAILS: 'プランの詳細',
  SUMMARY: 'サマリー',
  QUANTITIES: '数量',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*合計にはプランの機能の料金が含まれます',
  TOTAL: '合計',
  BILLED: '請求済み',
  PLAN_INFORMATION: 'プラン情報',
  UPDATE_PLAN: 'プランをアップデート',
  ADMIN_ACTIONS: '管理者のアクション',
  NAME_ON_CREDIT_CARD: 'クレジットカード名義',
  CREDIT_CARD_BRAND: 'クレジットカードのブランド',
  VISA: 'VISA',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'MasterCard',
  CREDIT_CARD_NUMBER: 'クレジットカード番号',
  EXPIRATION: '有効期限',
  MONTH: '月',
  YEAR: '年',
  SECURITY_CODE: 'セキュリティコード',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'クレジットカードの裏面に記載されているコード',
  BACK_TO_CHECKOUT: 'チェックアウトに戻る',
  NO_ORDERS_FOUND: 'ご注文は見つかりません',
  ADD: '追加',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: '新しいクレジットカードを追加するには、上のフォームを使用してください。必ず全てのフィールドに記入してください',
  NUMBER: '番号',
  EXPIRES: '有効期限',
  DELETE: '削除',
  ITEM_DETAILS: 'アイテムの詳細',
  FEE: '料金',
  ITEMS: '項目',
  SEARCH_BY_CONFIRMATION: '確認番号で検索',
  CONFIRMATION: '確認',
  CHECKOUT_STATUS: 'チェックアウトステータス',
  ORDER_STATUS_PROCESS: '注文ステータス',
  CREATED_ON: '作成日',
  ORDER_SUMMARY: '注文履歴',
  APPROVED: '承認されました', //example: partner application approved
  REJECTED: '拒否されました', //example: partner application rejected
  APPROVE: '確定', //example: partner application approved
  REJECT: '拒否', //example: partner application rejected
  PENDING: '保留中', //example: partner application pending
  EDIT: '編集',
  ONE_TIME_FEE: '初期費用',
  SUB_TOTAL: '小計',
  TAXES: '税金',
  CHANGES: '変更',
  CREATE_A_QUOTE: '見積もりを作成',
  EXTRA_INFORMATION: '追加情報',
  THANK_YOU_FOR_YOUR_ORDER: 'ご注文ありがとうございます',
  ORDER_CONFIRMATION: '注文の確認',
  INVALID_ORDER: '注文が無効です',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'ご安心ください。これは電子メールでもお送りしています。',
  HELLO: 'こんにちは',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'ご利用いただきありがとうございます。商品の出荷が完了しましたら、確認のメールをお送りします。ご注文内容は以下のとおりです。',
  ACCOUNT_INFORMATION: 'アカウント情報',
  BILLING_INFORMATION: '請求情報',
  SHIPPING_INFORMATION: '配送情報',
  NAME: '名前',
  EMAIL: '電子メール',
  SEARCH: '検索',
  CLEAR: 'クリア',
  PARTNER: 'パートナー',
  NO_PARTNERS_FOUND: 'パートナーが見つかりません',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'パートナーコネクションは、お客様がパートナーの個人リンクからストアにアクセスしたときに作成されます。',
  CUSTOMER: 'お客様',
  AGENT: '代理店',
  NO_PARTNER_CONNECTIONS_FOUND: 'パートナーコネクションが見つかりません',
  I_HAVE_READ_AND_AGREE_WITH_THE: '私はこれを読み同意します：',
  ZANG_PRIVACY_STATEMENT: 'Zangのプライバシーポリシー',
  AGENT_PROGRAM_TERMS_OF_SERVICE: '代理店プログラムのサービス利用規約',
  SUBMIT_APPLICATION: '申し込みを送信',
  SUBMITTING: '送信',
  SUBMITTING_YOUR_APPLICATION: '申し込みを送信中',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: '銀行情報および口座情報は、当社の利用規約の下で機密情報として安全に保持されます。',
  BANK_NAME: '銀行名',
  ADDRESS: 'アドレス',
  COUNTRY: '国',
  SELECT_ONE: '- 1つ選択する -',
  STATE_PROVINCE: '都道府県',
  CITY: '市名',
  ZIP_POSTAL_CODE: '郵便番号',
  ACCOUNT_NUMBER: '口座番号',
  BANK_NUMBER: '銀行番号',
  TRANSIT_NUMBER: '転送番号',
  SWIFT_CODE: 'Swiftコード',
  TAX_REGISTRATION_NUMBER: '税金登録番号',
  SAVE_BANK_INFORMATION: '銀行情報を保存',
  SAVING_BANK_INFORMATION: '銀行情報を保存中',
  NO_CUSTOMERS_FOUND: 'お客様が見つかりません',
  YOU_ARE_A: 'あなたは ',
  A_DISCOUNT_OF: '割引',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'は、チェックアウト後の合計金額に適用されます。',
  FIRST_NAME: '名',
  LAST_NAME: '姓',
  COMPANY_NAME: '会社名',
  LEGAL_COMPANY_NAME: '登録名',
  PHONE_NUMBER: '電話番号',
  WEBSITE: 'ウェブサイト',
  OPERATIONAL_ADDRESS: '事業所住所',
  SAME_AS_ORGANIZATION_ADDRESS: '会社住所と同じ',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: '現在Avayaパートナーですか？',
  NO: 'いいえ',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'はいの場合、AvayaパートナーIDを入力してください',
  MY_PARTNER_PORTAL: 'マイパートナーポータル',
  THANK_YOU_FOR_APPLYING: 'お申し込みいただきありがとうございます。',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: '手続き完了まであと少しです。販売代理店への申し込みを完了するには、以下のリンクをたどり、全ての質問に回答してください。',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' 改良しない場合、 をご記入ください ',
  PLEASE_GIVE: 'をご記入ください',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: '現在Avayaパートナーの場合、以下のリンクはたどらないでください。<br />現在お客様のパートナーIDを見直しており、近日中にご連絡差し上げます。',
  BUSINESS: 'ビジネス',
  DAYS: '日',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'ほどお待ちください。弊社の幹部が貴社からのお申し込み検討を検討します。<br />その間、ご質問がありましたらこちらにお送りください。',
  COMPLETE_MY_APPLICATION: '申し込みを完了する',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'お申し込みについて検討しましたが、残念ながら、現時点では弊社のプログラムに適さないという結論に至りました。深刻なことではありませんが、これを解決するまでパートナーシップを前進させることはできません。ご希望に添えず申し訳ありません。現在その根拠を確認しています。詳細がわかり次第ご連絡差し上げます。それまでの間、このプロセスに関して何かご質問がありましたら、',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'までお気軽にお問い合わせください。',
  CONGRATULATIONS: 'お知らせがあります。',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: '貴社はZangの正式な代理店になりました。',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'まずは、個人のリンクを貴社の全ての見込み客と共有することから始め、',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: '今よりもよい方法を体験できるようサポートしてください。',
  CHANGE_STATUS: 'ステータスを変更',
  AGENT_DETAILS: '代理店の詳細',
  BANK_INFORMATION: '銀行方法',
  THIS_ORDER_WAS_PLACED_BY_A: '発注者は',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'が合計金額に適用されました',
  REFERRALS: '紹介',
  SALES: '販売',
  FOUND: '発見された',
  HOW_IT_WORKS: '仕組み',
  WHAT_YOU_GET: '特典',
  SUPPORT: 'サポート',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'プログラムの比較',
  WHY_JOIN: '参加すべき理由',
  QUOTE: '見積もり',
  PRINT_THIS_QUOTE: 'この見積もりを印刷',
  CLOSE_THIS_WINDOW: 'このウィンドウを閉じる',
  SEARCH_BY_PLAN: 'プランで検索',
  ACCESS_LEVEL: 'アクセスレベル',
  DISPLAY_NAME: '表示名',
  INDUSTRY: '業界',
  COMPANY_INDUSTRY: '会社の業界',
  CONTACT_PHONE_NUMBER: '連絡先電話番号',
  EMAIL_ADDRESS: '電子メールアドレス',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'はい。Zangのニュース、アプリケーション、割引、特別イベントに関する電子メールを送ってください。',
  INFORMATION: '情報',
  ORDER_HISTORY: '注文履歴',
  FILTER: 'フィルター',
  ACCOUNT: 'アカウント',
  AMOUNT_CHARGED: '請求金額',
  DETAILS: '詳細',
  NO_RECORDS_FOUND: '録音がありません',
  CALL_LOGS: '通話ログ',
  EXPORT: 'エクスポート',
  CALLER_NAME: '発呼者名',
  DIALED_NUMBER: '発信元番号',
  DURATION_SEC: '持続時間(秒)',
  COST: '料金',
  PAYMENT_METHOD: 'お支払い方法',
  PURCHASE_ORDER: '購入注文',
  PURCHASE_ORDERS: '購入注文',
  CREDIT_CARD: 'クレジットカード',
  SHIPPING_ADDRESS: '送付先住所',
  SAME_AS_BILLING_ADDRESS: '請求書送付先住所と同じ',
  SAME_AS_SHIPPING_ADDRESS: '送付先住所と同じ',
  OTHER: 'その他',
  SHIPPING_OPTIONS: '配送方法',
  FREE_SHIPPING: '送料無料',
  ADDITIONAL_NOTES: '追加メモ',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: '私は次を読み同意します：',
  EMERGENCY_911_SERVICE_NOTICE: '緊急電話911サービスの通知',
  PLACE_MY_ORDER: '注文する',
  CLEAR_MY_ORDER: '注文をクリア',
  PLACING_YOUR_ORDER: '注文を送信しています',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'しばらくお待ちください。この処理には最長で1分ほどかかることがあります。',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'この処理にはしばらく時間がかかる場合があります。ご不便をおかけし申し訳ございません。ご注文が中断されないよう、このブラウザのウィンドウを終了したり、「戻る」ボタンや「更新」ボタンを押したりしないでください。',
  YOUR_NEW_NUMBER: '新しい番号',
  NO_NUMBER_SELECTED: '番号が選択されていません',
  WELL_THAT_WAS_EASY: '簡単でした。',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: '手続き完了まであと少しです。',
  NEXT: '次へ',
  TITLE: '役職',
  SUB_TITLE: 'サブタイトル',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: '市外局番で検索... (米国、カナダのみ)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: '市外局番を入力...（アメリカ合衆国のみ）',
  SELECT_A_PREFIX: '局番を選択',
  PICK_THIS_NUMBER: 'この番号を選択',
  DEVICES: 'デバイス',
  BILLING: '請求',
  CHANGE: '変更',
  USER_INFO: 'ユーザー情報',
  USE_MY_INFORMATION: '自分の情報を使用',
  SELECT_YOUR_DEVICES: 'デバイスを選択',
  MONTHLY_FEE: '月間料金',
  ANNUAL_FEE: '年間料金',
  TWO_YEAR_FEE: '2年料金',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Zang Officeの各プランには、スタンダードまたはパワーユーザーが少なくとも1名必要です。',
  CHECKOUT: 'チェックアウト',
  MINE: '自分のもの',
  REMOVE_THIS_USER: 'このユーザーを削除',
  SELECT_A_DEVICE_FOR_THIS_USER: 'このユーザーのデバイスを選択',
  ADD_ANOTHER: '別のものを追加',
  GET_STARTED_WITH_ZANG_OFFICE: 'Zang Officeで始めましょう',
  BUNDLE: 'パッケージ',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: '1年に登録をすると、次の特典があります:',
  OFF: 'オフ',
  EACH_USER: '毎年',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'ユーザー数を調整するには、注文をクリアにするか、「デバイス」のステップに進む必要があります。',
  EVERY_TWO_YEARS: '2年ごと',
  YOU_VE_SAVED: '保存できました',
  INCLUDED: '含まれるもの',
  ADDONS: 'アドオン',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'ユーザーの好みに合わせてカスタマイズ。',
  UNITS_PER: 'あたりの単位',
  TALK_ANYWERE_ANYTIME: 'いつでも、どこからでも話ができる。',
  DOWNLOAD_FOR_MAC: 'Mac版のダウンロード',
  DOWNLOAD_FOR_WINDOWS: 'Windows版のダウンロード',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Zang Officeをお買い上げいただきありがとうございます。ご注文内容はこちらから確認できます。',
  CONTINUE_WITH_YOUR_PURCHASE: '購入を続けてください。',
  GET_STARTED_TODAY: '今日から始めましょう。',
  FEATURES: '機能',
  LETS_BREAK_IT_DOWN_FOR_YOU: '各プランの内容をご覧ください',
  BASIC: 'ベーシック',
  STANDARD: '標準',
  POWER: 'パワー',
  RATE_MIN_STARTING_FROM: '1分あたりの料金はこちらから*:',
  RATE_MIN_STARTING_FROM_1: '1 分あたりの料金（最小）',
  LONG_DISTANCE: '国際長距離',
  INTERNATIONAL_LONG_DISTANCE_RATES: '国際長距離料金',
  COMMON_DESTINATIONS: 'よくかける番号',
  BEST_DEAL: '一番お得',
  PER_ACTIVE_USER_PER_MONTH: 'アクティブなユーザー1名、1ヶ月あたり。',
  ACCORDING_TO_ANNUAL_CONTRACT: '年間の契約による',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'ご請求は選択されたプランに沿って行われます。',
  MONTHLY: '毎月',
  ANNUALLY: '年間',
  BILLED_ANNUALY: '1年に1回請求',
  BILLED_EVERY_TWO_YEARS: '2年に1回請求',
  CONFIGURE_YOUR_ADDONS: 'アドオンを設定',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: '利用可能な各アドオンの数量を選択',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'このアドオンの数量の上限は',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'このアドオンはこちらにのみ利用できます:',
  BILLING_AND_SHIPPING: '請求と配送',
  BILLING: '請求',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'これがZang Officeのアカウント名になります。',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'こちらが Avaya Cloud アカウント名となります。',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Zang Officeの番号に既存の番号または通話料無料の番号を使用する場合、このフィールドで使用されている内線番号があるローカル番号を探してみます。',
  EVERYTHING_HAPPENS_IN_SPACES: 'Spacesが全ての中心に',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: '今まで欲しいと思いながらも見つからなかった、クラウドベースのチームコラボレーションツールです。',
  YOUR_CURRENT_PURCHASES: '現在の購入内容',
  PURCHASED_ON: '購入日',
  PLAN_NUMBER: 'プラン番号',
  UPDATE: '更新',
  UPDATED: '更新済み',
  OR: 'または',
  MAKE_A_NEW_PURCHASE: '新規購入',
  FEATURES_AND_ADDONS: '特徴とアドオン',
  FREE: '無料',
  PLUS: 'プラス',
  BUSINESS: 'POWER',
  VIEW: '表示',
  TEAM: 'チーム',
  LETS_SETUP_YOUR_TEAM: 'チームを作成しましょう',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: '作成したいチームのタイプを選択し、個人の環境を作成して設定するだけです。',
  COMPANY_TYPE: '会社のタイプ',
  DOMAIN: 'ドメイン',
  NO_TEAM_IS_SETUP_YET: 'チームはまだ作成されていません',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'チームの作成は不要です',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Zang Spacesをあなたのために購入しましょう。',
  CHOOSE_AN_EXISTING_COMPANY: '既存の会社を選択',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: '現在管理している会社の1つを選択してください。',
  CREATE_A_NEW_TEAM: '新しいチームを作成',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'チームメイトドメイン名を設定してください。',
  NO_DOMAIN_IS_CONFIGURED: 'ドメインが設定されていません。',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'ドメイン名を設定してください(例: \'zang.io\')',
  CHECK: '確認',
  TEAM_DOMAIN: 'チームドメイン(例: \'zang.io\')',
  TEAM_NAME: 'チーム名(例: \'Zang\')',
  OK: 'OK',
  ZANG_SPACES_ADMIN_CONSOLE: 'Zang Spaces管理者コンソール',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: '以下の値を変更してプランを更新できます',
  CHARGABLE_USERS: '有償ユーザー',
  TOTAL_USERS: 'ユーザーの合計',
  CURRENT_PRICE: '現在の価格',
  SAVE: '保存',
  SAVE_CHANGES_AND_UPDATE_PLAN: '変更を保存してプランをアップデートしますか？',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: '続行するには少なくとも1つのタイプのユーザーを選択してください',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Zang Spacesを購入します：',
  BUY_NOW: '今すぐ購入',
  SELECT: "選択",
  UP_TO: '最大',
  NO_PURCHASE_REQUIRED: '購入不要',
  NO_BILLING_OF_UPFRONT_COMMITMENT: '請求や前払いの契約はありません。',
  SIGN_UP_FOR_FREE: '登録無料',
  ONE_YEAR_PLAN: '1年プラン',
  MONTHLY_PLAN: '月間プラン',
  TWO_YEAR_PLAN: '2年プラン',
  MONTHS: '月',
  ZANG_OFFICE_ACCOUNT_NAME: 'Zang Officeアカウント名',
  ZANG_OFFICE_PLAN_NUMBER: 'Zang Officeプラン番号',
  TEMPORARY_NUMBER: '仮番号',
  START_SETTING_UP_ZANG_OFFICE: 'Zang Officeの設定を始めましょう。',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: '既存の番号をZang Officeソリューションに移行する場合は、LNP Authorization Formと最新の電話請求書のコピーをzosupport@zang.ioまで電子メールでお送りいただく必要があります。フリーダイヤル番号を移行する場合は、RODAAフォームもメールでお送りください。移行完了まで、最長10営業日かかります。ご了承ください。',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: '選択したZang Office番号の購入/有効化にエラーが発生しました。番号を手動で有効化/購入するには、「Zang Officeの設定を開始」をクリックします。既存の番号の使用を選択した場合、移行プロセスは影響を受けません。' to activate/buy your numbers manually. In case you\'ve chosen to use your existing number, the porting process will not be affected.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: '注意：既存の番号をZang Officeアカウントに移行する場合は、この<a href="{LNP_FORM_LINK}" target="blank">LNP Authorization Form</a>と最新の電話請求書のコピーを電子メールでお送りいただく必要があります。フリーダイヤル番号を移行する場合は、この<a href="{RODAA_LINK}" target="blank">RODAAフォーム</a>にもご記入ください。すべての書類を<a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>にお送りください。電話番号の移行プロセスには、最大で10営業日ほどかかる場合があります。',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: '電話番号の移行プロセスには、最大で10営業日ほどかかる場合があることにご注意ください。その間、アカウント内で使用するための、一時的な電話番号を添付します。',
  PLAN_STATUS: 'プランのステータス',
  PLAN_ID: 'プランID',
  SUBSCRIPTION_ID: 'サブスクリプションID',
  STRIPE_PLAN_ID: 'ストライププランID',
  ACCOUNT_ID: 'アカウントID',
  START_SETTING_UP_ZANG_SPACES: 'Zang Spacesの設定を開始',
  COMPANY_DOMAIN: '会社のドメイン',
  THIS_FIELD_IS_REQUIRED: 'このフィールドは必要です。',
  PLEASE_ANSWER_THIS_QUESTION: 'この質問にお答えください。',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'AvayaパートナーIDを入力してください',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: '続行するにはプライバシーポリシーを読み、同意してください。',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: '続行するには代理店プログラムサービス利用規約を読み、同意してください。',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'このAvayaパートナーIDはすでに使用されています。',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'この税金登録番号はすでに使用されています。',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'これは有効なAvayaパートナーIDではありません。',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: '数量は整数にしてください',
  ORDER_COMPLETE: '注文が完了しました。',
  PLEASE_TRY_AGAIN: 'やり直してください',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: '整数を少なくとも1つ選択してください',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'アップグレードはまだ進行中です。後でやり直してください。',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: '個人ライセンスでは複数のユーザーを設定できません。プランをアップグレードまたはダウングレードするには、必要に応じて数量を変更してください。',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'このアカウントへのアクセス権がありません。',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: '現在のプランでは、ユーザー数を最初の人数から減らすことができません。このような調整をご希望の場合、customerservice@zang.ioにご連絡ください。',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'ご注文の送信の際にエラーが発生しました。全てのフィールドに有効な値が入力されていることを確認してください。エラーが続く場合は、Zangサポートにご連絡ください。',

  USE_EXISTING_NUMBER: '既存の番号を使用',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'プランでは既存の番号の使用を選択',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'フリーダイヤル番号を事前選択',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: '独自のフリーダイヤル番号をプランに追加することを選択',
  FIND_A_LOCAL_NUMBER: 'ローカル番号を検索',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'あなたの地域のローカル番号のリストから選択し、プランに追加',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: '市内番号を選択してプランに追加',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: '使用可能な電話番号を市外局番で検索',
  SEARCH_AVAILABLE_PHONE_NUMBERS: '使用可能な電話番号の検索',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: '転送する既存の番号を入力',


  ZANG_OFFICE_PHONE_APP: 'Zang Office Phoneアプリ',
  ZANG_OFFICE_SOFTPHONE: 'Zang Officeのソフトフォン',
  ZANG_OFFICE_PHONE_APPLICATION: 'Zang Office Phoneアプリケーション',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Zang Officeのソフトフォンには、デスクトップやモバイルデバイスに期待される通信機能が全て搭載されています。Zang OfficeのソフトフォンはZang Officeのサブスクリプションに無料で含まれているため、追加料金不要でZang Officeの素晴らしい機能を全て活用することができます。',
  E129_SIP_DESK_PHONE: 'E129 SIP Desk Phone',
  STANDARD_PHONE: '一般電話機',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Avaya E129 SIP Deskphoneは、手頃な価格ながら高機能のSIP電話機に求められる重要な通話処理機能を備えた電話機です。Avaya E129 SIP Deskphoneでは、通話の転送、ミュート、着信転送、保留に加えて、ボタンを押すだけでカンファレンスを開始できます。フルデュプレックススピーカが搭載されているため、ハンズフリーで会話ができます。PoEポートを備えているため、ネットワークへの接続にも便利です。十分な通話機能を備えたAvaya E129 SIP Deskphoneは、良心的な価格設定の魅力ある製品です。AC電源アダプタが付属しています。',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: '革新的なガラス製の専用デスクトップデバイスを使用して接続します。ワンタッチの接続で、音声やチャット、コラボレーションアプリを使用します。不自然に音声やビデオが途切れたり止まったりすることはありません。接続に複数のデバイスを管理する必要がありません。独自のカスタムの体験を、ワークフローとビジネスプロセスに組み入れます。この強力でカスタマイズ可能なデバイスはデスクフォンより有利で、アプリケーションプラットフォームの柔軟性を備えています。',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'B179 Conference Phone',
  CONFERENCE_PHONE: 'カンファレンス用電話機',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'B179 Conference Phoneは、ボードルームや10名以上に対応する広いカンファレンスルームでの利用に最適です。従業員の生産性を向上させ、コラボレーションを促進します。B179 Conference Phoneは既存のソリューションを補完し、企業の成長やニーズの変化に応じて再構築できる、多目的で高性能な電話機です。AC電源アダプタが付属しています。',
  PLAN: 'プラン',
  REDIRECTING: 'リダイレクト中',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: '全てのフィールドに有効な値が入力されていることを確認してください。',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Zang Officeの各プランには、ユーザータイプが少なくとも1つ必要です。デバイス選択のステップに戻り、設定を変更してください。',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Zang Officeアカウントに番号を何も選択していないようです。番号選択のステップに戻り、番号を選択してください。',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'そのZang Officeアカウント名は使用されています。別の名前にしてください',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: '選択したZang Officeの番号は、他のお客様がすでに購入しています。番号選択のステップに戻り、別の番号を選択してください。',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: '毎月プランの利用で<span class="text-400">30日間無料</span>(特に義務はなし)',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'または年間プランを契約してさらに有利な価格と',
  FREE_PHONE: '無料電話をプレゼント',
  DISCOUNT: '割引',
  DISCOUNTED_PHONE: '割引された電話',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: '電話の購入の合計金額から割引',
  LIMITED_TIME_OFFER: '期間限定オファー',
  PROMOTION: 'プロモーション',
  ZANG_SPACES_PROMOTION: 'Zang Spacesプロモーション',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: '電話番号の選択を続ける',
  DURATION: '期間',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'お知らせがあります。デバイスの注文の合計に利用できる<strong>{amount}</strong>のクレジットをお持ちです。',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: '適用される全ての割引は、最終的なご注文内で調整されます。',
  SHIPPING_TYPE: '配送タイプ',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: '当社の倉庫から商品が出荷された時点で、追跡の詳細が送信されます',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'どのデバイスの購入にも利用できる、1ユーザー当たり{amount}のクレジットを差し上げます。期間限定オファーです。',
  PARTNER_ORDERS: 'パートナーの注文',
  COMMISSION: 'コミッション',

  ADDITIONAL_DEVICES: '追加デバイス',
  NO_USER: 'ユーザーがいません',
  QUANTITY: '数量',
  BUY_DEVICES: 'デバイスの購入',
  DEVICE: 'デバイス',
  PRICE: '価格',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'エージェントを検索する場合は {chars} 文字以上入力してください',
  NO_RESULTS_FOUND: '結果はありません',
  RESULTS_COULD_NOT_BE_LOADED: '結果をロードできません',
  CLEAR_SELECTION: '選択解除',


  RESET_ALL_PURCHASES: 'すべての購入をクリア',
  LISTS: 'リスト',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: '見積もりを作成する前に電話番号を入力してください。',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: '見積もりを作成する前に請求/配送情報を入力してください',
  CALCULATING_TAXES_PLEASE_WAIT: '税金を計算しています。しばらくお待ちください...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: '選択したクレジットカードに間違いがあります。',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'このクレジットカードに問題があります。別のカードを使用してください',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: '注文への課金時にエラーが発生しました。別のクレジットカードを選択してください',
  INVALID_CREDIT_CARD: '無効なクレジットカード',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type} がクレジットカードの住所情報と一致しません',
  INVALID_SECURITY_CODE: '無効なセキュリティコード（cvc）',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: '該当する値引きとプロモーション価格が、この請求書に適用されています',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: '顧客アカウントを作成できませんでした。やり直してください',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'クレジットカードを作成できませんでした。やり直してください',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'このクレジットカードはすでに自動継続型サブスクリプションで使用されています。',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'このクレジットカードのデフォルトへの設定中にエラーが発生しました。',
  DEFAULT: 'デフォルト',
  SET_DEFAULT: 'デフォルトの設定',
  SALES_FORCE_QUOTE_ID: 'Salesforceの見積ID',
  SALES_FORCE_ORDER_ID: 'Salesforceの注文ID',
  SALES_FORCE_OPPORTUNITY_ID: 'Salesforceの機会ID',
  SALES_FORCE_CONTACT_ID: 'Salesforceの連絡ID',
  SALES_FORCE_CONTRACT_ID: 'Salesforceの契約ID',
  SALES_FORCE_ACCOUNT_ID: 'SalesforceのアカウントID',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '\'デバイスを追加\ するだけ' and connect it with a user.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'デバイスを追加するだけでユーザーに接続します。',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Zang Office アカウント用に別のデバイスを購入',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'おっと。ご注文に間違いがあります。ページを更新してご注文をクリアし、最初からやり直してください。',
  CREATE_A_NEW_COMPANY: '新しい会社を作成',
  ADD_A_NEW_COMPANY: '新しい会社を追加',
  PARTNER_DETAILS: 'パートナーの詳細',
  AGENTS: 'エージェント',
  PARTNER_PORTAL: 'パートナーポータル',
  AGENT: 'エージェント',
  AGENT_PORTAL: 'エージェントポータル',
  NO_AGENTS_FOUND: 'エージェントは見つかりません',
  NO_AGENT: 'エージェントなし',
  RELATION: '関係',
  OWNER: '開催者',
  ADMIN: '管理者',
  MANAGER: 'マネージャ',
  EMPLOYEE: '従業員',
  ACTIVE: '有効',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: '関連付けられたパートナーを 1 つ選択してください',
  APPLIED_ON: '適用日',
  JOIN_A_PARTNER: 'パートナーへの参加',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'あと 1 ステップで <b>{COMPANY_NAME}</b> 様の登録が完了します',
  JOIN_PLACEHOLDER_NOW: '{COMPANY_NAME} 様を今すぐ登録',
  UPDATE_AGENT_INFO: 'エージェント情報の更新',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup> で始めましょう',
  IN_ASSOCIATION_WITH_ZANG_TM: 'Zang™ 関連',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'シンプルでパワフルな統合コラボレーションソリューション',
  IP_OFFICE_DONT_PAY_TILL: '2018 年 4 月 15 日までお支払いは発生しません！',
  LOGIN: 'ログイン',
  DISCOVER: '発見する',
  SOLUTIONS: 'ソリューション',
  SERVICES: 'サービス',
  INDUSTRIES: '業種',
  CASE_STUDIES: '事例',
  PROGRAMS_AND_PROMOTIONS: 'プログラムとプロモーション',
  AUTHENTIC_AVAYA: 'オーセンティックアバイア',
  PERSPECTIVES: '展望',
  AVAYA_CONNECTED_BLOG: 'アバイアコネクテッドブログ',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: 'ソリューション検索',
  INFO_FOR: 'Info for',
  DEVELOPERS: '開発者',
  CHANNEL_PARTNERS: 'チャネルパートナー',
  TECHNOLOGY_PARTNERS: 'テクノロジーパートナー',
  CONSULTANTS: 'コンサルタント',
  INVESTORS: '投資家',
  MEDIA_ANALYSTS: 'メディアアナリスト',
  SUPPLIERS: 'サプライヤ',
  CONNECT_WITH_US: 'アバイアへの問い合わせ',
  FIND_A_CHANNEL_PARTNER: '国内認定パートナーを探す',
  FIND_A_TECHNOLOGY_PARTNER: 'テクノロジーパートナーを探す',
  EXECUTIVE_BRIEFING_CENTER: 'Executive Briefing Center',
  AVAYA_LEARNING_SERVICES: 'Avaya Learning Services',
  CONTACTS: '連絡先',
  ABOUT_AVAYA: 'アバイアについて',
  EVENTS: 'イベント',
  NEWSROOM: 'ニュースルーム',
  INVESTOR_RELATIONS: '投資家向け情報',
  CORPORATE_RESPONSIBILITY: '企業責任',
  OUR_COMPANY: '弊社',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'International Avaya Users Group - IAUG',
  CAREERS: 'キャリア',
  YOUR_PERSONAL_LINK: '貴社専用リンク',
  SITEMAP: 'サイトマップ',
  TERMS_OF_USE: '利用規約',
  PRIVACY: 'プライバシー',
  COOKIES: 'クッキー',
  AVAYA_INVOICE: 'ご請求',
  IP_OFFICE_ACCOUNT_NAME: 'Avaya Cloud アカウント名',
  IP_OFFICE_PLAN_NUMBER: 'Avaya Cloud プラン番号',
  IP_OFFICE_PHONE_APPLICATION: 'Avaya Cloud Solutions ソフトフォン',
  IP_OFFICE_PHONE_DESCRIPTION: 'Avaya Cloud Solutions ソフトフォンでは、ユーザーがすべてのコミュニケーションチャネルに 1 つのインターフェイスで簡単にアクセスできます。Avaya Cloud Solutions ソフトフォンでは、お使いの PC を使用して Avaya Cloud Solutions にログインし、デスクフォンの内線で音声通話やビデオ通話を送受信できます。ソフトフォンは Avaya Cloud Solutions Standard および Power ユーザーサブスクリプションに無料で付属しています。',
  PLAN_MONTH_1_MONTH_1: '月極プラン（デバイスクレジットなし）',
  PLAN_YEAR_1_MONTH_1: '1 年間プラン | 1 か月に 1 回ご請求',
  PLAN_YEAR_1_YEAR_1: '1 年間プラン（一括払い）',
  PLAN_YEAR_2_MONTH_1: '2 年間プラン | 1 か月に 1 回ご請求',
  PLAN_YEAR_2_YEAR_1: '2 年間プラン | 1 年に 1 回ご請求',
  PLAN_YEAR_2_YEAR_2: '2 年間プラン（一括払い）',
  PLAN_YEAR_3_MONTH_1: '3 年間プラン | 1 か月に 1 回ご請求',
  PLAN_YEAR_3_YEAR_1: '3 年間プラン | 1 年に 1 回ご請求',
  PLAN_YEAR_3_YEAR_3: '3 年間プラン（一括払い）',
  PLAN_YEAR_5_MONTH_1: '5 年間プラン | 1 か月に 1 回ご請求',
  ACCORDING_TO_PLAN: 'プランによる',
  TOTAL_USER_PLAN_FEE: '総合ユーザープラン料金',
  HEALTHCARE_DENY_MESSAGE: 'お客様のソリューションとして Avaya Cloud as your solutions をお選びいただき、ありがとうございます。残念ながら現時点ではまだ HIPAA に準拠しておりませんので、ヘルスケア分野のお客様にはサービスをご提供することができません。認定の取得後に必ず連絡させていただきますので、その際にあらためてご検討ください。ご不明点については <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a> までお気軽にお問い合わせください。',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup> 用デバイスの選択',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup> 番号の選択',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'ユーザーを調整してデバイスを割り当ててください。',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Avaya Cloud Solutions 用電話番号を追加してください。',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'ソリューションに電話番号を割り当ててください。',
  INVITE_A_NEW_AGENT: '新しいエージェントの招待',
  I_WANT_TO_INVITE_A: '招待対象：',
  CONTACT_EMAIL: '担当者の電子メール',
  CONTACT_NAME: '連絡先名',
  COMPANY_NAME: '会社名',
  CONTACT: 'お問い合わせ',
  COMPANY_IS_INCORPORATED: '会社は株式会社です',
  INDIVIDUAL: '個人',
  INDIVIDUALS: '個人',
  SEND_INVITATION_EMAIL: '招待メールの送信',
  SENDING_INVITATION_EMAIL: '招待メールを送信しています...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: '招待状が正常に送信されました',
  ALL_FIELDS_ARE_REQUIRED: 'すべてのフィールドが必要です',
  PARTNER_NOT_FOUND: 'パートナーが見つかりません',
  SALE_AGENT_REGISTRATION: 'セールスエージェント登録',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: '次のセールスエージェントとして登録するには以下のフォームに入力してください：',
  VIEW: '表示',
  COMPANIES: '会社',
  ADD_A_PARTNER: 'パートナーの追加',
  ADD_PARTNER: 'パートナーの追加',
  PARTNERS_PERSONAL_LINK: 'パートナーの個人リンク',
  MASTER_SALES_AGENT: 'マスターセールスエージェント',
  AVAYA_J129_LABEL: 'J129 IP Phone',
  AVAYA_J129_DESCRIPTION: '手頃な価格ながら高機能の SIP 電話機に求められる重要な通話処理機能をすべて備えた電話機が手に入ります。この電話ではあらゆる規模の企業でユーザーが必要とする主要機能を使用できます。1 回線の通話ディスプレイで 2 回線のコールアピアランスに対応できます。市場最先端の機種にも勝る確かな機能を備えた電話をお買い求めください。',
  AVAYA_J169_LABEL: 'J169 IP Phone',
  AVAYA_J169_DESCRIPTION: '手頃な価格ながら高機能の SIP 電話機に求められる重要な通話処理機能をすべて備えた電話機が手に入ります。この電話ではあらゆる規模の企業でユーザーが必要とする主要機能を使用できます。1 回線の通話ディスプレイで 2 回線のコールアピアランスに対応できます。市場最先端の機種にも勝る確かな機能を備えた電話をお買い求めください。',
  AVAYA_J179_LABEL: 'J179 IP Phone',
  AVAYA_J179_DESCRIPTION: '手頃な価格ながら高機能の SIP 電話機に求められる重要な通話処理機能をすべて備えた電話機が手に入ります。この電話ではあらゆる規模の企業でユーザーが必要とする主要機能を使用できます。1 回線の通話ディスプレイで 2 回線のコールアピアランスに対応できます。市場最先端の機種にも勝る確かな機能を備えた電話をお買い求めください。',
  AVAYA_K175_LABEL: 'Avaya Vantage™ K175',
  AVAYA_K175_DESCRIPTION: '手頃な価格ながら高機能の SIP 電話機に求められる重要な通話処理機能をすべて備えた電話機が手に入ります。この電話ではあらゆる規模の企業でユーザーが必要とする主要機能を使用できます。1 回線の通話ディスプレイで 2 回線のコールアピアランスに対応できます。市場最先端の機種にも勝る確かな機能を備えた電話をお買い求めください。',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: '9641GS IP Deskphone',
  AVAYA_9641G_DESCRIPTION: 'Avaya 9641GS は、電話業務の時間が多く、インテリジェントなコミュニケーション機能と生産性を高める機能性を必要とする場合に最適な多回線対応プレミアムデスクフォンです。9641GS は 5.0 インチカラーグラフィカルディスプレイと High Definition Audio の音質を装備しています。Wideband 音声コーデックを使用しているため、ハンドセット、ヘッドセット、スピーカーを含むすべての音声インターフェイスで卓抜したオーディオパフォーマンスを発揮します。',
  AVAYA_9608G_LABEL: '9608G IP Deskphone',
  AVAYA_9608G_DESCRIPTION: '9608G Deskphone は費用対効果の高い高機能電話機で、ギガビット通信機能と白黒ディスプレイを内蔵しています。PoE を装備しているため導入が簡単で、Wideband 音声コーデックを使用しているため、卓抜したオーディオパフォーマンスを発揮します。このあらゆる規模の企業に対応するよう作られたデスクフォンは 8 回線にアクセスでき集中管理可能なグラフィカルラベルを備えています。',
  AVAYA_9611G_LABEL: '9611G IP Deskphone',
  AVAYA_9611G_DESCRIPTION: '9611G モデルはギガビット通信機能と USB インターフェイスを内蔵しています。3.5 インチのグラフィカルカラーディスプレイと白色バックライト、集中管理可能なグラフィカルラベルを備えています。PoE を装備しているため導入が簡単で、Wideband 音声コーデックを使用しているため、卓抜したオーディオパフォーマンスを発揮します。',
  AVAYA_PHONE_B179_LABEL: 'B179 SIP Conference Phone',
  AVAYA_PHONE_B179_DESCRIPTION: 'Tolly による検証済みのこの柔軟な SIP ベースのカンファレンスフォンでは、特許を取得したアバイアの Wideband オーディオテクノロジー、OmniSound 2.0 により明瞭で自然な音声を実現します。一段と効率的に電話会議を行えるよう、この電話にはインテリジェント機能が多数搭載されています。カンファレンスガイドを使用して事前にプログラムされたグループに電話をかけることができます。Web インターフェイス経由で連絡先の詳細を簡単にインポートおよびエクスポートできます。個人ユーザープロファイル機能でユーザーごとに独自の連絡先リストを作成できます。',
  HAVE_LARGE_NUMBERS_OF_USERS: '多数のユーザーでご利用ですか？',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'アバイアの大口割引の内訳をご確認ください。',
  DEVICE_FEE: 'デバイス料金',
  UP_TO_DEVICE_CREDITE_PER_USER: 'ユーザー 1 人あたり最大 {$} のデバイスクレジット',
  PROMOTION_REMAINING_DETAIL_INFO: 'ご利用いただけるプロモーションのデバイスクレジットがまだ <b>{0}</b> 残っています。ご購入後に残ったクレジットはすべて無効となり、将来のご購入時に備えて残りをアカウントに移すことはできませんのでご注意ください。',
  VIEW_USER_FEATURES: 'ユーザー機能の表示',
  FREE_DEVICES_PER_USER_INFO: '{0}（ユーザー 1 人あたり最大 {1} のデバイスクレジット）',
  VALUE_OF_DEVICE_CREDIT: 'ユーザー数 {0} 人 = デバイスクレジット合計 {0}',
  PROMOTION_DELAYED_BILLING_INFO: 'プロモーション：正式な請求期間が始まったとき、詳細なレシートを発送します。また、お支払いが必要な場合はその全額をクレジットカードに課金いたします。',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'エージェントを選択してご注文手続きを完了してください',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: '有効なドメイン名（"例.com"）を入力してください',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Avaya Cloud Solution システムの準備が整いました。',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Avaya Cloud Solution システムの設定が完了しました。',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Avaya Cloud Solutions の電話番号',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Avaya Cloud Solutions の SIP ドメイン名',
  IP_OFFICE_SIP_DOMAIN_ID: 'Avaya Cloud Solutions の SIP ドメイン ID',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Avaya Cloud Solution システムを設定しています。',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'ご注文いただき、ありがとうございます。現在、お客様の Avaya Cloud Solutions システムを設定しています。設定が終わり次第、ご連絡します。<br />ご不明の点については、Avaya Cloud Solutions のサポート {IPO_SUPPORT_EMAIL} までお気軽にお問い合わせください',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'このアカウントのプロビジョニングに失敗しました',
  ERROR_CODE: 'エラーコード',
  ERROR_MESSAGE: 'エラーメッセージ',
  ADMIN_PORTAL_LINK: '管理者ポータルリンク',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Avaya Cloud Solutions のデフォルトのユーザーパスワード',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Avaya Cloud Solutions の一時電話番号',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'ベーシックユーザーの内線',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Standard ユーザーの内線',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'パワーユーザーの内線',
  IP_OFFICE_DEFAULT_USER_PIN: 'デフォルトのユーザーの暗証番号',
  IP_OFFICE_SAME_AS_PIN: '内線と同一（200 など）',
  IP_OFFICE_ORDERID: 'Avaya Cloud Solutions 注文 ID',
  IP_OFFICE_HOST_NAME: 'お客様の Avaya Cloud Solutions 用ホスト名',
  IP_OFFICE_IP_ADDRESS: 'お客様の Avaya Cloud Solutions 用 IP アドレス',
  IP_OFFICE_SUBSCRIPTIONID: 'お客様の Avaya Cloud Solutions サブスクリプション ID',
  CALCULATING: '計算中...',
  RESET_ALL_PARTNERS: 'パートナーデータのクリア',
  ERROR_GETTING_AGENTS: 'エージェントのチェック中にエラーが発生しました。もう一度お試しください',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: '同じチーム内にこのメールを使用しているエージェントがすでに存在します',
  AUTO_APPROVE_ACTIVATE_AGENT: 'エージェントの自動承認／有効化',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: '同じチーム内にこのメールを使用している会社がすでに存在します',
  MASTER_SALES_AGENT_PORTAL: 'マスターセールエージェントポータル',
  SALES_AGENT_PORTAL: 'セールスエージェントポータル',
  E911_ADDRESS: 'E911 のアドレス',
  OVERVIEW: '概要',
  ADD_COMPANY_OR_SALES_AGENT: '会社またはエージェントの追加',
  ADD_AN_AGENT: 'エージェントの追加先：',
  INACTIVE: '無効',
  AGENTS_PERSONAL_CONNECTION_LINK: 'エージェントの個人用接続リンク',
  PURCHASE_DATE_AND_CUSTOMER: '購入日とお客様',
  ORDER_DETAILS: '注文の詳細',
  SELECT_AGENT: 'すべてのエージェント',
  FROM: '発信元',
  TO: '宛先',
  EXPORT_REPORT: 'レポートのエクスポート',
  NO_SALES_FOUND: '売り上げが見つかりません',
  ADD_A_COMPANY: '会社の追加',
  AUTO_APPROVE_COMPANY: '会社の自動承認',
  AUTO_ACTIVATE_AGENT: 'エージェントの自動有効化',
  ADD_COMPANY: '会社の追加',
  ADD_COMPANY_NAME_AGENT_ADMIN: '{COMPANY_NAME} のエージェント／管理者の追加',
  ADD_AGENT_ADMIN: 'エージェント／管理者の追加',
  ALL_COMPANIES: 'すべての会社',
  START_DATE: '開始日',
  HEY: 'いつもご利用いただきありがとうございます。',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: '担当を務めさせていただくカスタマーサクセスマネージャです。お使いの Avaya Cloud Solutions の価値をご提供いたします。担当の Avaya Cloud Solutions サポートチームには、アバイアのテクニカルサポートチーム（<a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>）も属しています。',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: '数日中にキックオフコールのスケジュールし、担当サポートチームをご紹介して、システム設定を完了いたします。つきましては<strong><a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> までご連絡いただき、1 時間のキックオフコールを行うのにご都合のよい日時をお知らせください。<strong>',
  START_USING_YOUR_IP_OFFICE: 'Avaya Cloud Solutions システムの利用を今すぐ始めてください。',
  BELOW_ARE_DETAILS: '以下はご利用システムのアカウント情報、ユーザー資格情報、アプリケーションのダウンロードです。',
  YOUR_IP_OFFICE_INFO: 'ご利用システムの情報：',
  LOGIN_INFO_TABLE: 'ユーザー情報チャート：',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'ユーザーは誰でも、上部の情報を使用して各自のクラウドユーザーポータルにログインすると、各自の情報の設定、通話転送の調整、ボイスメールの再生などを実行できます。',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'ユーザーが使用できるアプリケーション：',
  DO_NOT_HESITATE_TO_EMAIL_US: 'ご不明の点については、お気軽に <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a> までお問い合わせください。',
  THANK_YOU: 'よろしくお願いいたします。',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web（Windows）</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web（Chrome Extension）</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile（IPO（iOS））</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile（IPO（Android））</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions ソフトコンソール（Windows）</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">インストールマニュアル</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">インストールマニュアル</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">インストールマニュアル</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">インストールマニュアル</a>',




  USER_NAMES_COLUMN: 'ユーザー名',
  EXTENSIONS_COLUMN: '内線',
  TEMP_PIN_COLUMN: '暗証番号',
  TEMP_PASSWORD_COLUMN: 'パスワード',
  USER_TYPE_COLUMN: 'ユーザータイプ',
  DEVICE_MODEL_COLUMN: 'デバイス',
  POWER_USER: 'Power',
  STANDARD_USER: 'Standard',
  BASIC_USER: 'ベーシック',
  ORDERID: '注文 ID',
  ACCOUNT_NAME: 'アカウント名',
  HOST_NAME: 'ホスト名',
  ADMIN_PORTAL: '管理者ポータル',
  IP_ADDRESS: 'IP アドレス',
  PHONE_NUMBER: '電話番号',
  TEMPORARY_PHONE_NUMBER: '一時電話番号',
  EXCITING_TIMES_AHEAD: 'イベントがあります',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'ドメイン名 {DOMAIN_NAME} は無効か別の会社に使用されています。',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'ドメイン名 {1} は無効か別の会社に使用されています。',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: '会社を確認できませんでした。もう一度お試しください。',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'N/Aの情報（ある場合）については Avaya Cloud サポートにお問い合わせください： ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Avaya Cloud アカウントのプロビジョニングを開始できませんでした',
  LEGAL: '法的情報',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: '1 年間またはそれ以上のプランをご選択いただいた場合、デバイスの購入時にお使いいただける期間限定のクレジットを各ユーザーに提供します。',
  USER_PORTAL: 'ユーザーポータル',
  E_911: 'E911',
  DECLINE: '拒否',
  ACCEPT: '承認',
  PRINT: '出力',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'ご注文を完了するには上記の規約すべてに同意してください',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'ユーザーにデバイスを割り当てます。',
  SELECT: '選択',
  USER_DETAILS: 'ユーザーの詳細',
  DEVICE_DETAILS: 'デバイスの詳細',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: '同意する前にアバイアの利用規約をお読みください。',
  PARTNER_ORDERS_RECORDS_HINT: '*すべての販売記録は参照用です。正式な最終的な販売レポートはマスターセールスエージェントの同意の下でアバイアのファイナンスから発行されます。',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: '見積もりを作成するセールスエージェントを選択してください',
  COMPANY_DETAILS: '会社の詳細',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'および該当する税金。',
  SELECT_PRODUCT: '製品の選択',
  CLOUD_UC_SMALL_MONTH1: 'Cloud UC Essentials（月極）',
  SMALL: '小',
  CLOUD_UC_SMALL_MONTH12: 'Cloud UC Essentials 1 年プラン',
  CLOUD_UC_SMALL_3YEARS: 'Cloud UC Essentials 3 年プラン',
  CLOUD_UC_SMALL_5YEARS: 'Cloud UC Essentials 5 年プラン',
  MEDIUM: '中',
  CLOUD_UC_MEDIUM_MONTL1: 'Cloud UC Business 月極プラン',
  CLOUD_UC_MEDIUM_MONTH12: 'Cloud UC Business 1 年プラン',
  CLOUD_UC_MEDIUM_3YEARS: 'Cloud UC Business 3 年プラン',
  CLOUD_UC_MEDIUM_5YEARS: 'Cloud UC Business 5 年プラン',
  LARGE: '大',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC 従量制（大）',
  CLOUD_UC_LARGE_MONTL12: 'Cloud UC 年間プラン（大）',
  CLOUD_UC_SMALL_SHORT_INFO: '従業員数 1～99 人',
  CLOUD_UC_MEDIUM_SHORT_INFO: '従業員数 100～999 人',
  CLOUD_UC_LARGE_SHORT_INFO: '従業員数 1000 人超',
  SELECTED: '選択済み',
  BASIC_PHONE_SERVICE: 'ベーシック電話サービス',
  UNLIMITED_NATIONAL_WIDE: '国内長距離電話無制限',
  STANDARD_FEATURES: 'Standard 機能',
  HOW_MANY_USERS: '必要なユーザー数は何人ですか？',
  ADD_ON_ADDITIONAL_FEATURES: '追加機能',
  ONETIME_FEE: '初期費用',
  RECURRING_FEE: '定期費用',
  SELECT_MAIN_NUMBER: 'メイン番号の選択',
  TOLL_FREE: 'フリーダイヤル番号',
  LOCAL_NUMBER: 'ローカル番号',
  TRANSFER_NUMBER: '番号転送',
  USERS_COUNT: '{qty} 人のユーザー',
  DEVICES_COUNT: '{qty} 件のデバイス',
  UC_OFFER_TITLE: '最適なソリューションをご用意しました。',
  UC_OFFER_DESCRIPTION: '中小企業から大企業まであらゆる企業規模に対応し、お探しのサービスをご提供します。企業タイプをお教えください。',

  // 'BASIC_PHONE_SERVICE': 'ベーシック電話サービス',

  TAX_CALC_ERROR_MSG: '税金を計算できません。請求先住所が正しいことをご確認ください。',
  'VIOLATION.FIELD_IS_EMPTY': '{1} は必須です',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} - {2} は必須です',
  'VIOLATION.FIELD_VALUE_INVALID': '{1} の値が無効です',
  'VIOLATION.FIELD_VALUE_INVALID2': '{1} - {2} の値が無効です',
  'VIOLATION.TAX_CALCULATION_FAILED': '税金の計算に失敗しました',
  'VIOLATION.AGREE_ON_LEGAL_DOC': '[{1}]を読み同意してください',
  'VIOLATION.CART_IS_EMPTY': 'カートは空です',
  'VIOLATION.CART_IS_TOO_BIG': 'カート内の項目数が大きすぎます',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} はカートから削除されました',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': '{1} の数量が {2} から {3} に調整されました',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': '{1} の割引が {2} から {3} に調整されました',
  'SALESMODELRULE.NOT_SAME_CURRENCY': '{1} 通貨建ての項目を {2} 通貨建てのカートには追加できません',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': '割引ルール {1} が未定義です',
  'SALESMODELRULE.UNKNOWN_ERROR': '不明なエラー',
  'SALESMODELRULE.INVALID_PARAMETER': '無効なパラメータ：{1}',
  ONE_TIME: 'ワンタイム',
  ADDON_PRICING_HINT: '*アドオンの価格設定は座席数を基準としすべてのユーザーに適用されます。ご購入後は管理者ポータル内から特定のアドオンをユーザーに追加できます。',
  ADD_TO_CART_HINT: 'カートに追加するには上述の手順を完了してください',
  ITEM_UNITS: '{qty} ユニット',
  ADDONS_COUNT: '{qty} 個のアドオン',
  ADDON_COUNT: '{qty} 個のアドオン',
  MULTIPLE_TYPES: '複数タイプ',
  MIXED: '混合',
  FREE_PRICE: '無料',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essentials',
  UC_ESSENTIALS_DESCRIPTION: 'あらゆる規模の企業に最適なクラウドベースコミュニケーションです。',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: 'クラウドでのトップクラスのエンタープライズコミュニケーションで企業を強化します',
  UC_BUSINESS_POWER_PACKAGE: 'POWER ユーザーへのアップグレード',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>ダイレクト電話番号：</strong>一意の専用番号で、事務所の代表番号や交換手（仮想または人間）を通さず電話を直接受けることができます。</li><li><strong>ダイレクトビデオ通話：</strong>ポイントツーポイントの通話にビデオを追加できます。</li><li><strong>Salesforce© の統合：</strong>Salesforce 内部から直接エンドユーザーと高度なコミュニケーションを行えます。</li><li><strong>Google© の統合：</strong>Google Chrome やさまざまな Google アプリから直接ブラウザベースのリアルタイムコミュニケーションを行えます。</li><li><strong>Skype for Business© との統合：</strong>Skype for Business を使用した、モダンで、簡素化された、使いやすいコラボレーションエクスペリエンスを確立します。</li></ul>',
  SHOW_MORE: '詳細の表示',
  HIDE: '非表示',
  VIEW_COMPLETE_FEATURE_LIST: ' 内蔵機能のリストを表示',
  FILTER_BY: '絞り込み',
  UC_OFFERS: 'UC ソリューション',
  PAY_MONTHLY: '月払い',
  PAY_ANNUALLY: '年払い',
  COMING_SOON: '近日発売',
  TAX_CALC_ERROR_MSG: '税金を計算できません。住所が正しいことをご確認ください。',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: '最新の長距離料金を確認するには、国名を入力してください。',
  LONG_DISTANCE_RATE_NOT_FOUND: 'この国の長距離料金は見つかりませんでした。この国の長距離通話の詳細については、{CUSTOMER_SUCCESS_EMAIL} にお問い合わせください。',
  AREA_CODE: '市外局番',
  INVALID_CREDIT_CARD_ZIP: 'クレジットカードと郵便番号が一致しません。',
  VIEW_LONG_DISTANCE_RATES: '長距離料金の表示',
  LONG_DISTANCE_SUBTITLE_TEXT: 'アバイアの低額長距離料金なら、世界中誰にでも連絡を取り合うことができます。',
  RATES_SUBJECT_TO_CHANGE: '*料金は予告なく変更される場合があります。',
  CREDIT_CARD_DECLINED: 'クレジットカードが却下されました。',
  ENTER_COUNTRY_NAME: '国名の入力',
  ADD_TO_CART: 'カートへの追加',
  UPDATE_CART: 'カートの更新',
  PER_USER: 'ユーザー 1 人あたり',
  COMPARE_UC_OFFERS: 'UC 商品の比較',
  PROCEED_TO_CHECKOUT: 'お会計',
  BEFORE_APPLICABLE_TAXES: '* 税加算前',
  YEAR_PLAN: '1 年プラン',
  YEARS_PLAN: '{0} 年プラン',
  MONTHS_PLAN: '{0} か月プラン',
  ENTER_NUMBER_OF_USERS: 'このソリューションで対応するユーザー数を入力',
  YEAR: '年',
  BILLED_MONTH: '1 か月に 1 回ご請求',
  COMPANY_INCORPORATED: '込み',
  COMPANY_NOT_INCORPORATED: '別',
  EXISTING_CONFIG_WARNING: '<br/><b>{0}</b> の既存設定があります。',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: '現在の設定を破棄しますか？',
  DISCARD_MY_CONFIGURATION: '設定の破棄',
  DISCARD: '破棄',
  EDIT_MY_CONFIGURATION: '現在の設定を編集',
  CONTINUE: '続行',
  SELECT_A_PLAN: 'プランの選択',
  PROMOTION_DETAIL_INFO: '* 合計 <b>{0} 人のユーザー</b>が選択されました。<br/>これは合計でデバイスクレジット <b>{1}</b> 分に相当します。',
  BILLED_MONTH_FREQUENCY: '{0} か月に 1 回ご請求',
  BILLED_YEAR_FREQUENCY: '{0} 年に 1 回ご請求',
  CONTACT_OUR_CUSTOMER_CARE: 'アバイアのカスタマーケアチームに連絡',
  NEED_HELP_INFO: 'サポートをご希望ですか？ご不明の点、問題、情報についていつでもサポートできるようアバイアの カスタマーケアチームが待機しています。',
  REMOVE: '削除',
  REMOVE_ITEM_FROM_CART_WARNING: 'カートから <b>{0}</b> を削除しますか？',
  NO_ITEM_IN_THE_CART: 'カート内に項目はありません。',
  CONTINUE_SHOPPING: 'ショッピングの続行',
  TOTAL_TAXES: '税金合計額',
  UC_SOLUTIONS: 'UC ソリューション',
  UNIFIED_COMMUNICATIONS: 'ユニファイドコミュニケーション',
  ADD_ONS: 'アドオン',
  SYSTEM_ADDONS: 'システムアドオン',
  ADD_DEVICES: 'デバイスの追加',
  SELECT_UPTO_DEVICES: '最大（<b>{0}</b>）のデバイス数を <b>{1}</b> に選択',
  DONE: '完了',
  SELECT_DEVICES: 'デバイスの選択',
  EDIT_DEVICE_SELECTION: 'デバイスの編集',
  ESSENTIAL_USERS: 'Essential ユーザー',
  BUSINESS_USERS: 'Business ユーザー',
  POWER_USERS: 'Power ユーザー',
  N_A: 'N/A'
}
