export default {
  PHONE_TYPES: '電話のタイプ',
  IMAGINE_A_BETTER_WAY: '今よりもよい方法は',
  OF_DOING_THINGS: 'きっとある。',
  GET_STARTED: '開始',
  PURCHASE: '購入する',
  DOWNLOADS_AND_EXTENSIONS: 'ダウンロード＆拡張機能',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS:'Zangの製品を最大限に活用するための必携アドオン',
  ALL: '全て',
  REFERRAL_AGENT: '紹介代理店',
  SALES_AGENT: '販売代理店',
  CART: 'カート',
  PARTNER_PROGRAMS: 'パートナープログラム',
  HOME: 'ホーム',
  MANAGE_CREDIT_CARDS: 'クレジットカードを管理',
  MY_PROFILE: 'マイプロフィール',
  MY_SETTINGS: 'マイ設定',
  MY_PARTNER_PORTAL: 'マイパートナーポータル',
  CLEAR_ZANG_OFFICE: 'Zang Officeをクリア',
  CLEAR_ZANG_SPACES: 'Avaya Spacesをクリア',
  FEATURE_BREAKDOWN: '機能詳細',
  PLAN_BREAKDOWN: 'プラン詳細', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: '必要な業務用電話を、低価格で',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Avaya Spaces で何ができるでしょうか',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '50% の割引は、チェックアウト後の合計金額に適用されます',
  HURRICANE_HARVEY_MESSAGE: 'AvayaとZangは、ハリケーン・ハービーの影響を受け、またハリケーン・イルマの影響を受ける可能性のある企業を支援したいと考えています。影響を受けた、テキサスおよびルイジアナ、フロリダ、アラバマ、ジョージア、ノースカロライナ、サウスカロライナ、テネシー、ミシシッピ州の企業はただちに、<b>Zang Office</b>と<b>Avaya Spacesを無料で</b>3か月受け取ることができます。',
  LEARN_MORE: '詳細',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ を利用できるようになりました',
  NEW: 'New!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'このすべてガラス製で使いやすい、音声とビデオ、チャットのコラボレーション電話で、Zang Officeのすべてをご体験ください。',
  LOG_IN: 'ログイン',
  SIGN_UP: '登録',
  SIGN_OUT: 'サインアウト',
  SIGN_IN: 'サインイン', //login to the system, connect
  ADMINISTRATION: '管理',
  PRODUCTS: '製品',
  ORDERS: '注文',
  PAGES: 'ページ',
  CUSTOMERS: '顧客',
  USERS: 'ユーザー',
  PLANS: 'プラン',
  ZANG_OFFICE: 'Zang Office',
  CDRS: 'CDR',
  CDR_CHECKS: 'CDRチェック',
  PARTNERS: 'パートナー',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'すでにZang Officeをご購入されているようです。これ以上Zang Officeの注文は行えません。',
  PARTNER_CONNECTIONS: 'パートナーコネクション',
  CHECK_OUT_GENERAL_FATAL_ERROR: '注文時にエラーが発生しました。詳細については、Zangサポート({SUPPORT_EMAIL})までお問い合わせください',
  APPLICATION_GENERAL_FATAL_ERROR: '申し込みの送信にエラーが発生しました。詳細については、Zangサポート({SUPPORT_EMAIL})までお問い合わせください',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: '続行するには少なくとも1つのユーザータイプを選択してください。',
  BACK: '戻る',
  SAVE_CHANGES: '変更を保存',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: '続行します。よろしいですか?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'クレジットに、あらゆるデバイスの購入に使える{PLACEHOLDER}があります。このクレジットは、注文を送信するとなくなります。',
  JUST_A_REMINDER: 'お知らせ',
  LAST_CHANCE: '最後のチャンス',
  IM_GOOD_PLACE_MY_ORDER: '了解 - 注文を発注',
  BUY_MORE_DEVICES: 'さらにデバイスを購入',
  YES_PLACE_MY_ORDER: 'はい、注文を発注します',
  NO_THANKS: 'いいえ、結構です。',
  YES: 'はい',
  ABOUT_US: '当社について',
  NEWS_AND_PRESS: 'ニュース＆プレス',
  CARREERS: '採用情報',
  CONTACT_US: 'お問い合わせ先',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'ご利用いただきありがとうございます。ご注文内容は以下のとおりです。',
  BLOG: 'ブログ',
  FAQS: 'FAQ',
  DOCUMENTATION: 'ドキュメント',
  TERMS_OF_SERVICE: 'サービス利用規約',
  HELP: 'ヘルプ',
  PRIVACY_STATEMENT: 'プライバシーポリシー',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. All Rights Reserved.',
  PROCESSING: '処理中です',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'しばらくお待ちください。少し時間がかかることがあります。',
  OPEN_IN_A_NEW_TAB: '新しいタブで開く',
  GOT_IT: '了解',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' このアクションを行うと次の結果になります:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'このプランの月間サブスクリプションを削除',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: '全てのサードパーティシステム上のアカウントが無効',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'このプランのステータスを無効に変更',
  LAST_ACTION_STEPS: '最後のアクションのステップ',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'アドオンは、アカウント作成後、Zang Office管理者ポータルを通じ購入します。',
  TYPE: 'タイプ',
  ADMIN: '管理者',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'このユーザーは、法人アカウントの主たる連絡先/請求先として設定されます。Zang Office管理者ポータルを通じ、いつでも変更できます。',
  DESCRIPTION: '内容',
  SUCCESS: '成功',
  REQUEST_CANCELATION: '解約依頼',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: '解約されるとのこと、残念です。',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '以下のフォームに記入し、解約手続きにお進みください。カスタマーサクセス部門の担当者が拝見し、1〜2営業日以内にご連絡します。',
  YOUR_NAME: 'お名前',
  COMPANY: '会社',
  SERVICE: 'サービス',
  REASON_FOR_CANCELING: '解約理由',
  SUBMIT: '送信',
  EXIT: '終了',
  REQUEST_SUBMITTED: 'リクエストが送信されました',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'カスタマーサクセス部門の担当者が拝見し、1〜2営業日以内にご連絡します。',
  DATE: '日付',
  PRODUCT: '製品',
  USER: 'ユーザー',
  STATUS: 'ステータス',
  ACTIONS: '操作',
  VIEW_DETAILS: '詳細を表示',
  DISABLE: '無効にする',
  ENABLE: '有効にする',
  CANCEL: 'キャンセル',
  PLAN_DETAILS: 'プランの詳細',
  SUMMARY: 'サマリー',
  QUANTITIES: '数量',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*合計にはプランの機能の料金が含まれます',
  TOTAL: '合計',
  BILLED: '請求済み',
  PLAN_INFORMATION: 'プラン情報',
  UPDATE_PLAN: 'プランをアップデート',
  ADMIN_ACTIONS: '管理者のアクション',
  NAME_ON_CREDIT_CARD: 'クレジットカード名義',
  CREDIT_CARD_BRAND: 'クレジットカードのブランド',
  VISA: 'VISA',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'MasterCard',
  CREDIT_CARD_NUMBER: 'クレジットカード番号',
  EXPIRATION: '有効期限',
  MONTH: '月',
  YEAR: '年',
  SECURITY_CODE: 'セキュリティコード',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'クレジットカードの裏面に記載されているコード',
  BACK_TO_CHECKOUT: 'チェックアウトに戻る',
  ADD: '追加',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: '新しいクレジットカードを追加するには、上のフォームを使用してください。必ず全てのフィールドに記入してください',
  NUMBER: '番号',
  EXPIRES: '有効期限',
  DELETE: '削除',
  ITEM_DETAILS: 'アイテムの詳細',
  FEE: '料金',
  ITEMS: '項目',
  SEARCH_BY_CONFIRMATION: '確認番号で検索',
  CONFIRMATION: '確認',
  CHECKOUT_STATUS: 'チェックアウトステータス',
  ORDER_STATUS_PROCESS: '注文ステータス',
  CREATED_ON: '作成日',
  ORDER_SUMMARY: '注文履歴',
  APPROVED: '承認されました', //example: partner application approved
  REJECTED: '拒否されました', //example: partner application rejected
  PENDING: '保留中', //example: partner application pending
  EDIT: '編集',
  ONE_TIME_FEE: '初期費用',
  SUB_TOTAL: '小計',
  TAXES: '税金',
  CHANGES: '変更',
  CREATE_A_QUOTE: '見積もりを作成',
  EXTRA_INFORMATION: '追加情報',
  THANK_YOU_FOR_YOUR_ORDER: 'ご注文ありがとうございます',
  ORDER_CONFIRMATION: '注文の確認',
  INVALID_ORDER: '注文が無効です',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'ご安心ください。これは電子メールでもお送りしています。',
  HELLO: 'こんにちは',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'ご利用いただきありがとうございます。商品の出荷が完了しましたら、確認のメールをお送りします。ご注文内容は以下のとおりです。',
  ACCOUNT_INFORMATION: 'アカウント情報',
  BILLING_INFORMATION: '請求情報',
  SHIPPING_INFORMATION: '配送情報',
  NAME: '名前',
  EMAIL: '電子メール',
  SEARCH: '検索',
  CLEAR: 'クリア',
  PARTNER: 'パートナー',
  NO_PARTNERS_FOUND: 'パートナーが見つかりません',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'パートナーコネクションは、お客様がパートナーの個人リンクからストアにアクセスしたときに作成されます。',
  CUSTOMER: 'お客様',
  AGENT: '代理店',
  NO_PARTNER_CONNECTIONS_FOUND: 'パートナーコネクションが見つかりません',
  I_HAVE_READ_AND_AGREE_WITH_THE: '私はこれを読み同意します：',
  ZANG_PRIVACY_STATEMENT: 'Zangのプライバシーポリシー',
  AGENT_PROGRAM_TERMS_OF_SERVICE: '代理店プログラムのサービス利用規約',
  SUBMIT_APPLICATION: '申し込みを送信',
  SUBMITTING: '送信',
  SUBMITTING_YOUR_APPLICATION: '申し込みを送信中',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: '銀行情報および口座情報は、当社の利用規約の下で機密情報として安全に保持されます。',
  BANK_NAME: '銀行名',
  ADDRESS: 'アドレス',
  COUNTRY: '国',
  SELECT_ONE: '- 1つ選択する -',
  STATE_PROVINCE: '都道府県',
  CITY: '市名',
  ZIP_POSTAL_CODE: '郵便番号',
  ACCOUNT_NUMBER: '口座番号',
  BANK_NUMBER: '銀行番号',
  TRANSIT_NUMBER: '転送番号',
  SWIFT_CODE: 'Swiftコード',
  TAX_REGISTRATION_NUMBER: '税金登録番号',
  SAVE_BANK_INFORMATION: '銀行情報を保存',
  SAVING_BANK_INFORMATION: '銀行情報を保存中',
  NO_CUSTOMERS_FOUND: 'お客様が見つかりません',
  YOU_ARE_A: 'あなたは ',
  A_DISCOUNT_OF: '割引',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'は、チェックアウト後の合計金額に適用されます。',
  FIRST_NAME: '名',
  LAST_NAME: '姓',
  COMPANY_NAME: '会社名',
  LEGAL_COMPANY_NAME: '登録名',
  PHONE_NUMBER: '電話番号',
  WEBSITE: 'ウェブサイト',
  OPERATIONAL_ADDRESS: '事業所住所',
  SAME_AS_ORGANIZATION_ADDRESS: '会社住所と同じ',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: '現在Avayaパートナーですか？',
  NO: 'いいえ',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'はいの場合、AvayaパートナーIDを入力してください',
  MY_PARTNER_PORTAL: 'マイパートナーポータル',
  THANK_YOU_FOR_APPLYING: 'お申し込みいただきありがとうございます。',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: '手続き完了まであと少しです。販売代理店への申し込みを完了するには、以下のリンクをたどり、全ての質問に回答してください。',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' 改良しない場合、 をご記入ください ',
  PLEASE_GIVE: 'をご記入ください',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: '現在Avayaパートナーの場合、以下のリンクはたどらないでください。<br />現在お客様のパートナーIDを見直しており、近日中にご連絡差し上げます。',
  BUSINESS: 'ビジネス',
  DAYS: '日',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'ほどお待ちください。弊社の幹部が貴社からのお申し込み検討を検討します。<br />その間、ご質問がありましたらこちらにお送りください。',
  COMPLETE_MY_APPLICATION: '申し込みを完了する',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'お申し込みについて検討しましたが、残念ながら、現時点では弊社のプログラムに適さないという結論に至りました。深刻なことではありませんが、これを解決するまでパートナーシップを前進させることはできません。ご希望に添えず申し訳ありません。現在その根拠を確認しています。詳細がわかり次第ご連絡差し上げます。それまでの間、このプロセスに関して何かご質問がありましたら、',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'までお気軽にお問い合わせください。',
  CONGRATULATIONS: 'お知らせがあります。',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: '貴社はZangの正式な代理店になりました。',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'まずは、個人のリンクを貴社の全ての見込み客と共有することから始め、',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: '今よりもよい方法を体験できるようサポートしてください。',
  CHANGE_STATUS: 'ステータスを変更',
  AGENT_DETAILS: '代理店の詳細',
  BANK_INFORMATION: '銀行方法',
  THIS_ORDER_WAS_PLACED_BY_A: '発注者は',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'が合計金額に適用されました',
  REFERRALS: '紹介',
  SALES: '販売',
  FOUND: '発見された',
  HOW_IT_WORKS: '仕組み',
  WHAT_YOU_GET: '特典',
  SUPPORT: 'サポート',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'プログラムの比較',
  WHY_JOIN: '参加すべき理由',
  QUOTE: '見積もり',
  PRINT_THIS_QUOTE: 'この見積もりを印刷',
  CLOSE_THIS_WINDOW: 'このウィンドウを閉じる',
  SEARCH_BY_PLAN: 'プランで検索',
  ACCESS_LEVEL: 'アクセスレベル',
  DISPLAY_NAME: '表示名',
  INDUSTRY: '業界',
  CONTACT_PHONE_NUMBER: '連絡先電話番号',
  EMAIL_ADDRESS: '電子メールアドレス',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'はい。Zangのニュース、アプリケーション、割引、特別イベントに関する電子メールを送ってください。',
  INFORMATION: '情報',
  ORDER_HISTORY: '注文履歴',
  FILTER: 'フィルター',
  ACCOUNT: 'アカウント',
  AMOUNT_CHARGED: '請求金額',
  DETAILS: '詳細',
  NO_RECORDS_FOUND: '録音がありません',
  CALL_LOGS: '通話ログ',
  EXPORT: 'エクスポート',
  CALLER_NAME: '発呼者名',
  DIALED_NUMBER: '発信元番号',
  DURATION_SEC: '持続時間(秒)',
  COST: '料金',
  CREDIT_CARD: 'クレジットカード',
  SHIPPING_ADDRESS: '送付先住所',
  SAME_AS_BILLING_ADDRESS: '請求書送付先住所と同じ',
  SHIPPING_OPTIONS: '配送方法',
  FREE_SHIPPING: '送料無料',
  ADDITIONAL_NOTES: '追加メモ',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: '私は次を読み同意します：',
  EMERGENCY_911_SERVICE_NOTICE: '緊急電話911サービスの通知',
  PLACE_MY_ORDER: '注文する',
  CLEAR_MY_ORDER: '注文をクリア',
  PLACING_YOUR_ORDER: '注文を送信しています',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'しばらくお待ちください。この処理には最長で1分ほどかかることがあります。',
  YOUR_NEW_NUMBER: '新しい番号',
  NO_NUMBER_SELECTED: '番号が選択されていません',
  WELL_THAT_WAS_EASY: '簡単でした。',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: '手続き完了まであと少しです。',
  NEXT: '次へ',
  TITLE: '役職',
  SUB_TITLE: 'サブタイトル',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: '市外局番で検索... (米国、カナダのみ)',
  SELECT_A_PREFIX: '局番を選択',
  PICK_THIS_NUMBER: 'この番号を選択',
  DEVICES: 'デバイス',
  BILLING: '請求',
  CHANGE: '変更',
  USER_INFO: 'ユーザー情報',
  USE_MY_INFORMATION: '自分の情報を使用',
  SELECT_YOUR_DEVICES: 'デバイスを選択',
  MONTHLY_FEE: '月間料金',
  ANNUAL_FEE: '年間料金',
  TWO_YEAR_FEE: '2年料金',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Zang Officeの各プランには、スタンダードまたはパワーユーザーが少なくとも1名必要です。',
  CHECKOUT: 'チェックアウト',
  MINE: '自分のもの',
  REMOVE_THIS_USER: 'このユーザーを削除',
  SELECT_A_DEVICE_FOR_THIS_USER: 'このユーザーのデバイスを選択',
  ADD_ANOTHER: '別のものを追加',
  GET_STARTED_WITH_ZANG_OFFICE: 'Zang Officeで始めましょう',
  BUNDLE: 'パッケージ',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: '1年に登録をすると、次の特典があります:',
  OFF: 'オフ',
  EACH_USER: '毎年',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'ユーザー数を調整するには、注文をクリアにするか、「デバイス」のステップに進む必要があります。',
  EVERY_TWO_YEARS: '2年ごと',
  YOU_VE_SAVED: '保存できました',
  INCLUDED: '含まれるもの',
  ADDONS: 'アドオン',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'ユーザーの好みに合わせてカスタマイズ。',
  UNITS_PER: 'あたりの単位',
  TALK_ANYWERE_ANYTIME: 'いつでも、どこからでも話ができる。',
  DOWNLOAD_FOR_MAC: 'Mac版のダウンロード',
  DOWNLOAD_FOR_WINDOWS: 'Windows版のダウンロード',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Zang Officeをお買い上げいただきありがとうございます。ご注文内容はこちらから確認できます。',
  CONTINUE_WITH_YOUR_PURCHASE: '購入を続けてください。',
  GET_STARTED_TODAY: '今日から始めましょう。',
  FEATURES: '機能',
  LETS_BREAK_IT_DOWN_FOR_YOU: '各プランの内容をご覧ください',
  BASIC: 'ベーシック',
  STANDARD: '標準',
  POWER: 'パワー',
  RATE_MIN_STARTING_FROM: '1分あたりの料金はこちらから*:',
  INTERNATIONAL_LONG_DISTANCE_RATES: '国際長距離料金',
  COMMON_DESTINATIONS: 'よくかける番号',
  BEST_DEAL: '一番お得',
  PER_ACTIVE_USER_PER_MONTH: 'アクティブなユーザー1名、1ヶ月あたり。',
  ACCORDING_TO_ANNUAL_CONTRACT: '年間の契約による',
  MONTHLY: '毎月',
  ANNUALLY: '年間',
  BILLED_ANNUALY: '1年に1回請求',
  BILLED_EVERY_TWO_YEARS: '2年に1回請求',
  CONFIGURE_YOUR_ADDONS: 'アドオンを設定',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: '利用可能な各アドオンの数量を選択',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'このアドオンの数量の上限は',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'このアドオンはこちらにのみ利用できます:',
  BILLING_AND_SHIPPING: '請求と配送',
  BILLING: '請求',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'これがZang Officeのアカウント名になります。',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Zang Officeの番号に既存の番号または通話料無料の番号を使用する場合、このフィールドで使用されている内線番号があるローカル番号を探してみます。',
  EVERYTHING_HAPPENS_IN_SPACES: 'Spacesが全ての中心に',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: '今まで欲しいと思いながらも見つからなかった、クラウドベースのチームコラボレーションツールです。',
  YOUR_CURRENT_PURCHASES: '現在の購入内容',
  PURCHASED_ON: '購入日',
  PLAN_NUMBER: 'プラン番号',
  UPDATE: '更新',
  OR: 'または',
  MAKE_A_NEW_PURCHASE: '新規購入',
  FEATURES_AND_ADDONS: '特徴とアドオン',
  FREE: '無料',
  PLUS: 'プラス',
  BUSINESS: 'BUSINESS',
  VIEW: '表示',
  TEAM: 'チーム',
  LETS_SETUP_YOUR_TEAM: 'チームを作成しましょう',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: '作成したいチームのタイプを選択し、個人の環境を作成して設定するだけです。',
  COMPANY_TYPE: '会社のタイプ',
  DOMAIN: 'ドメイン',
  NO_TEAM_IS_SETUP_YET: 'チームはまだ作成されていません',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'チームの作成は不要です',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Avaya Spacesをあなたのために購入しましょう。',
  CHOOSE_AN_EXISTING_COMPANY: '既存の会社を選択',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: '現在管理している会社の1つを選択してください。',
  CREATE_A_NEW_TEAM: '新しいチームを作成',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'チームメイトドメイン名を設定してください。',
  NO_DOMAIN_IS_CONFIGURED: 'ドメインが設定されていません。',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'ドメイン名を設定してください(例: \'zang.io\')',
  CHECK: '確認',
  TEAM_DOMAIN: 'チームドメイン(例: \'zang.io\')',
  TEAM_NAME: 'チーム名(例: \'Zang\')',
  OK: 'OK',
  ZANG_SPACES_ADMIN_CONSOLE: 'Avaya Spaces管理者コンソール',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: '以下の値を変更してプランを更新できます',
  CHARGABLE_USERS: '有償ユーザー',
  TOTAL_USERS: 'ユーザーの合計',
  CURRENT_PRICE: '現在の価格',
  SAVE: '保存',
  SAVE_CHANGES_AND_UPDATE_PLAN: '変更を保存してプランをアップデートしますか？',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: '続行するには少なくとも1つのタイプのユーザーを選択してください',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Avaya Spacesを購入します：',
  BUY_NOW: '今すぐ購入',
  UP_TO: '最大',
  NO_PURCHASE_REQUIRED: '購入不要',
  NO_BILLING_OF_UPFRONT_COMMITMENT: '請求や前払いの契約はありません。',
  SIGN_UP_FOR_FREE: '登録無料',
  ONE_YEAR_PLAN: '1年プラン',
  MONTHLY_PLAN: '月間プラン',
  TWO_YEAR_PLAN: '2年プラン',
  MONTHS: '月',
  ZANG_OFFICE_ACCOUNT_NAME: 'Zang Officeアカウント名',
  ZANG_OFFICE_PLAN_NUMBER: 'Zang Officeプラン番号',
  TEMPORARY_NUMBER: '仮番号',
  START_SETTING_UP_ZANG_OFFICE: 'Zang Officeの設定を始めましょう。',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: '既存の番号をZang Officeソリューションに移行する場合は、LNP Authorization Formと最新の電話請求書のコピーをzosupport@zang.ioまで電子メールでお送りいただく必要があります。フリーダイヤル番号を移行する場合は、RODAAフォームもメールでお送りください。移行完了まで、最長10営業日かかります。ご了承ください。',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: '選択したZang Office番号の購入/有効化にエラーが発生しました。番号を手動で有効化/購入するには、「Zang Officeの設定を開始」をクリックします。既存の番号の使用を選択した場合、移行プロセスは影響を受けません。',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: '注意：既存の番号をZang Officeアカウントに移行する場合は、この<a href="{LNP_FORM_LINK}" target="_blank" rel="noopener noreferrer">LNP Authorization Form</a>と最新の電話請求書のコピーを電子メールでお送りいただく必要があります。フリーダイヤル番号を移行する場合は、この<a href="{RODAA_LINK}" target="_blank" rel="noopener noreferrer">RODAAフォーム</a>にもご記入ください。すべての書類を<a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>にお送りください。電話番号の移行プロセスには、最大で10営業日ほどかかる場合があります。',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: '電話番号の移行プロセスには、最大で10営業日ほどかかる場合があることにご注意ください。その間、アカウント内で使用するための、一時的な電話番号を添付します。',
  PLAN_STATUS: 'プランのステータス',
  PLAN_ID: 'プランID',
  SUBSCRIPTION_ID: 'サブスクリプションID',
  STRIPE_PLAN_ID: 'ストライププランID',
  ACCOUNT_ID: 'アカウントID',
  START_SETTING_UP_ZANG_SPACES: 'Avaya Spacesの設定を開始',
  COMPANY_DOMAIN: '会社のドメイン',
  THIS_FIELD_IS_REQUIRED: 'このフィールドは必要です。',
  PLEASE_ANSWER_THIS_QUESTION: 'この質問にお答えください。',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'AvayaパートナーIDを入力してください',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: '続行するにはプライバシーポリシーを読み、同意してください。',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: '続行するには代理店プログラムサービス利用規約を読み、同意してください。',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'このAvayaパートナーIDはすでに使用されています。',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'この税金登録番号はすでに使用されています。',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'これは有効なAvayaパートナーIDではありません。',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: '数量は整数にしてください',
  ORDER_COMPLETE: '注文が完了しました。',
  PLEASE_TRY_AGAIN: 'やり直してください',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: '整数を少なくとも1つ選択してください',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'アップグレードはまだ進行中です。後でやり直してください。',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: '個人ライセンスでは複数のユーザーを設定できません。プランをアップグレードまたはダウングレードするには、必要に応じて数量を変更してください。',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'このアカウントへのアクセス権がありません。',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: '現在のプランでは、ユーザー数を最初の人数から減らすことができません。このような調整をご希望の場合、customerservice@zang.ioにご連絡ください。',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'ご注文の送信の際にエラーが発生しました。全てのフィールドに有効な値が入力されていることを確認してください。エラーが続く場合は、Zangサポートにご連絡ください。',
  USE_EXISTING_NUMBER: '既存の番号を使用',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'プランでは既存の番号の使用を選択',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'フリーダイヤル番号を事前選択',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: '独自のフリーダイヤル番号をプランに追加することを選択',
  FIND_A_LOCAL_NUMBER: 'ローカル番号を検索',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'あなたの地域のローカル番号のリストから選択し、プランに追加',
  ZANG_OFFICE_PHONE_APP: 'Zang Office Phoneアプリ',
  ZANG_OFFICE_SOFTPHONE: 'Zang Officeのソフトフォン',
  ZANG_OFFICE_PHONE_APPLICATION: 'Zang Office Phoneアプリケーション',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Zang Officeのソフトフォンには、デスクトップやモバイルデバイスに期待される通信機能が全て搭載されています。Zang OfficeのソフトフォンはZang Officeのサブスクリプションに無料で含まれているため、追加料金不要でZang Officeの素晴らしい機能を全て活用することができます。',
  E129_SIP_DESK_PHONE: 'E129 SIP Desk Phone',
  STANDARD_PHONE: '一般電話機',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Avaya E129 SIP Deskphoneは、手頃な価格ながら高機能のSIP電話機に求められる重要な通話処理機能を備えた電話機です。Avaya E129 SIP Deskphoneでは、通話の転送、ミュート、着信転送、保留に加えて、ボタンを押すだけでカンファレンスを開始できます。フルデュプレックススピーカが搭載されているため、ハンズフリーで会話ができます。PoEポートを備えているため、ネットワークへの接続にも便利です。十分な通話機能を備えたAvaya E129 SIP Deskphoneは、良心的な価格設定の魅力ある製品です。AC電源アダプタが付属しています。',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: '革新的なガラス製の専用デスクトップデバイスを使用して接続します。ワンタッチの接続で、音声やチャット、コラボレーションアプリを使用します。不自然に音声やビデオが途切れたり止まったりすることはありません。接続に複数のデバイスを管理する必要がありません。独自のカスタムの体験を、ワークフローとビジネスプロセスに組み入れます。この強力でカスタマイズ可能なデバイスはデスクフォンより有利で、アプリケーションプラットフォームの柔軟性を備えています。',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'B179 Conference Phone',
  CONFERENCE_PHONE: 'カンファレンス用電話機',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'B179 Conference Phoneは、ボードルームや10名以上に対応する広いカンファレンスルームでの利用に最適です。従業員の生産性を向上させ、コラボレーションを促進します。B179 Conference Phoneは既存のソリューションを補完し、企業の成長やニーズの変化に応じて再構築できる、多目的で高性能な電話機です。AC電源アダプタが付属しています。',
  PLAN: 'プラン',
  REDIRECTING: 'リダイレクト中',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: '全てのフィールドに有効な値が入力されていることを確認してください。',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Zang Officeの各プランには、ユーザータイプが少なくとも1つ必要です。デバイス選択のステップに戻り、設定を変更してください。',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Zang Officeアカウントに番号を何も選択していないようです。番号選択のステップに戻り、番号を選択してください。',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'そのZang Officeアカウント名は使用されています。別の名前にしてください',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: '選択したZang Officeの番号は、他のお客様がすでに購入しています。番号選択のステップに戻り、別の番号を選択してください。',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: '毎月プランの利用で<span class="text-400">30日間無料</span>(特に義務はなし)',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'または年間プランを契約してさらに有利な価格と',
  FREE_PHONE: '無料電話をプレゼント',
  DISCOUNT: '割引',
  DISCOUNTED_PHONE: '割引された電話',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: '電話の購入の合計金額から割引',
  LIMITED_TIME_OFFER: '期間限定オファー',
  PROMOTION: 'プロモーション',
  ZANG_SPACES_PROMOTION: 'Avaya Spacesプロモーション',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: '電話番号の選択を続ける',
  DURATION: '期間',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'お知らせがあります。デバイスの注文の合計に利用できる<strong>{amount}</strong>のクレジットをお持ちです。',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: '適用される全ての割引は、最終的なご注文内で調整されます。',
  SHIPPING_TYPE: '配送タイプ',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: '当社の倉庫から商品が出荷された時点で、追跡の詳細が送信されます',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'どのデバイスの購入にも利用できる、1ユーザー当たり{amount}のクレジットを差し上げます。期間限定オファーです。',
  PARTNER_ORDERS: 'パートナーの注文',
  COMMISSION: 'コミッション',

  ADDITIONAL_DEVICES: '追加デバイス',
  NO_USER: 'ユーザーがいません',
  QUANTITY: '数量',
  BUY_DEVICES: 'デバイスの購入',
  DEVICE: 'デバイス',
  PRICE: '価格',


  RESET_ALL_PURCHASES: 'すべての購入をクリア',
  LISTS: 'リスト',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: '見積もりを作成する前に電話番号を入力してください。',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: '見積もりを作成する前に請求/配送情報を入力してください',
  CALCULATING_TAXES_PLEASE_WAIT: '税金を計算しています。しばらくお待ちください...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: '選択したクレジットカードに間違いがあります。',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'このクレジットカードに問題があります。別のカードを使用してください',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: '注文への課金時にエラーが発生しました。別のクレジットカードを選択してください',
  INVALID_CREDIT_CARD: '無効なクレジットカード',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type} がクレジットカードの住所情報と一致しません',
  INVALID_SECURITY_CODE: '無効なセキュリティコード（cvc）',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: '該当する値引きとプロモーション価格が、この請求書に適用されています',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: '顧客アカウントを作成できませんでした。やり直してください',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'クレジットカードを作成できませんでした。やり直してください',
  SALES_FORCE_QUOTE_ID: 'Salesforceの見積ID',
  SALES_FORCE_ORDER_ID: 'Salesforceの注文ID',
  SALES_FORCE_OPPORTUNITY_ID: 'Salesforceの機会ID',
  SALES_FORCE_CONTACT_ID: 'Salesforceの連絡ID',
  SALES_FORCE_CONTRACT_ID: 'Salesforceの契約ID',
  SALES_FORCE_ACCOUNT_ID: 'SalesforceのアカウントID',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'デバイスを追加 するだけ',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'デバイスを追加 するだけ',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Zang Office アカウント用に別のデバイスを購入',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'おっと。ご注文に間違いがあります。ページを更新してご注文をクリアし、最初からやり直してください。',
  CREATE_A_NEW_COMPANY: '新しい会社を作成',
  ADD_A_NEW_COMPANY: '新しい会社を追加',

}
