export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: '계정 시스템에서 데이터의 비밀번호를 해독할 수 없습니다.',
  PHONE_TYPES: '전화기 유형',
  IMAGINE_A_BETTER_WAY: '일을 잘할 수 있는 방법을',
  OF_DOING_THINGS: '상상해 보세요.',
  GET_STARTED: '시작하기',
  PURCHASE: '구매',
  DOWNLOADS_AND_EXTENSIONS: '다운로드 및 연장',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: '이 필수 추가 기능으로 Zang 제품을 최대한 활용십시오!',
  ALL: '모두',
  REFERRAL_AGENT: '의뢰 에이전트',
  SALES_AGENT: '영업 에이전트',
  CART: '카트',
  PARTNER_PROGRAMS: '파트너 프로그램',
  HOME: '홈',
  MANAGE_CREDIT_CARDS: '신용카드 관리',
  MANAGE_PAYMENT_OPTIONS: '지급 옵션 관리',
  MANAGE_BILLING_ACCOUNT: '결제 계정 관리',
  LIMIT: "한도",
  MY_PROFILE: '내 프로필',
  MY_SETTINGS: '내 설정',
  MY_PARTNER_PORTAL: '내 파트너 포털',
  CLEAR_ZANG_OFFICE: 'Zang Office 지우기',
  CLEAR_ZANG_SPACES: 'Zang Spaces 지우기',
  FEATURE_BREAKDOWN: '기능 세부 사항',
  PLAN_BREAKDOWN: '계획 세부 사항', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: '요청하신 회사 전화입니다. 가격대에 만족하실 것입니다',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Zang Spaces에서 할 수 있는 일을 상상해 보세요',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '체크아웃 후에 총 금액에 50%의 할인이 적용됩니다',
  HURRICANE_HARVEY_MESSAGE: 'Avaya와 Zang은 허리케인 하비로 피해를 입은 비즈니스와 허리케인 어마로 피해를 입을 수 있는 비즈니스를 돕고자 합니다. TX, LA, FL, AL, GA, NC, SC, TN 및 MS 주에서 피해를 입은 모든 회사는 즉시 <b>Zang Office</b>와 <b>Zang Spaces를 3개월간 무료로 사용할 수 있습니다</b>.',
  LEARN_MORE: '자세히',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ 출시',
  NEW: '신규!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: '음성, 영상 및 채팅 협업을 위한 완전 유리의 사용이 편리한 이 전화기로 최고의 Zang Office를 경험하십시오.',
  LOG_IN: '로그인',
  SIGN_UP: '가입',
  SIGN_OUT: '로그아웃',
  SIGN_IN: '로그인', //login to the system, connect
  ADMINISTRATION: '관리',
  PRODUCTS: '제품',
  ORDERS: '주문',
  PAGES: '페이지',
  CUSTOMERS: '고객',
  USERS: '사용자',
  PLANS: '공장',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP 사무실',
  CDRS: 'Cdrs',
  CDR_CHECKS: 'Cdr 확인',
  PARTNERS: '파트너',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: '이미 Zang Office를 구매하신 것 같습니다. Zang Office에 대한 추가 주문을 제출할 수 없습니다.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: '이 회사의 Avaya Cloud를 이미 구매하신 것 같습니다. 다른 회사를 선택하십시오.',
  PARTNER_CONNECTIONS: '파트너 연결',
  CHECK_OUT_GENERAL_FATAL_ERROR: '주문하는 중 오류가 발생했습니다. 자세한 내용은 Zang 지원팀({SUPPORT_EMAIL})에 문의하십시오.',
  APPLICATION_GENERAL_FATAL_ERROR: '귀하의 신청 제출 중 오류가 발생했습니다. 자세한 내용은 Zang 지원팀({SUPPORT_EMAIL})에 문의하십시오.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: '계속하려면 하나 이상의 사용자 유형을 선택하십시오',
  BACK: '뒤로',
  SAVE_CHANGES: '변경 사항 저장',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: '진행하시겠습니까?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: '장치 구매까지 {PLACEHOLDER}크레딧을 더 써야 합니다. 주문을 제출하면 크레딧이 소멸됩니다.',
  JUST_A_REMINDER: '미리 알림',
  LAST_CHANCE: '마지막 기회',
  IM_GOOD_PLACE_MY_ORDER: '알고 있음 - 내 주문 제출',
  BUY_MORE_DEVICES: '추가 장치 구매',
  YES_PLACE_MY_ORDER: '예. 내 주문 제출',
  NO_THANKS: '아니요, 괜찮습니다!',
  YES: '예',
  ABOUT_US: '당사 소개',
  NEWS_AND_PRESS: '뉴스 및 보도',
  CARREERS: '채용',
  CONTACT_US: '연락처',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: '구매해 주셔서 감사합니다. 주문 상세 정보는 아래에 나와 있습니다.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: '이 정보에 대해서는 <a href="mailto:{EMAIL}">{EMAIL}</a>에 문의하십시오.',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: '귀하의 시스템이 준비되면 고객 지원 팀 및 기술 지원 팀에서 연락을 드립니다. <br/><br/><b>시스템이 설치되는 데 최대 1시간이 소요될 수 있습니다.</b>',
  QUESTION_CUSTOMER_SERVICE: '질문이 있는 경우 <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a> 주소로 이메일을 보내 주십시오.',
  BLOG: '블로그',
  FAQS: 'FAQ',
  DOCUMENTATION: '문서',
  TERMS_OF_SERVICE: '서비스 약관',
  HELP: '도움말',
  PRIVACY_STATEMENT: '개인정보 보호 방침',
  GENERAL_PRIVACY_STATEMENT: '일반 개인 정보 보호 정책',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: '일반 서비스 약관 - Avaya Cloud Solutions',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. All Rights Reserved.',
  PROCESSING: '처리 중',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: '잠시 기다려 주십시오. 처리하는 데 시간이 걸릴 수 있습니다',
  OPEN_IN_A_NEW_TAB: '새 탭에서 열기',
  GOT_IT: '완료되었습니다!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' 이 작업의 결과는 다음과 같습니다.',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: '이 플랜의 월 구독 삭제',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: '타사 시스템에서 계정 비활성화',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: '이 플랜의 상태를 비활성화로 변경',
  LAST_ACTION_STEPS: '마지막 작업 단계',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: '계정이 생성되면 Zang Office 관리 포털을 통해 추가 기능을 구매할 수 있습니다.',
  TYPE: '유형',
  ADMIN: '관리자',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: '이 사용자는 기업 계정의 기본/대금 청구 연락처로 구성됩니다. Zang Office 관리 포털에서 언제든지 변경할 수 있습니다.',
  DESCRIPTION: '설명',
  SUCCESS: '성공',
  REQUEST_CANCELATION: '요청 취소 제출됨',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: '귀하가 취소하길 원하신다니 아쉽습니다.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '취소 처리를 시작하려면 아래 양식을 작성하여 주십시오. 당사의 고객 성공 부서 직원이 1~2 업무일 내에 귀하의 요청을 검토하고 빈틈없이 요청에 대한 후속조치 진행할 것입니다.',
  YOUR_NAME: '귀하의 이름',
  COMPANY: '회사',
  SERVICE: '서비스',
  REASON_FOR_CANCELING: '취소 사유',
  SUBMIT: '제출',
  EXIT: '종료',
  REQUEST_SUBMITTED: '요청서 제출됨!',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '당사의 고객 성공 부서 직원이 1~2 업무일 내에 귀하의 요청을 검토하고 빈틈없이 요청에 대한 후속조치 진행할 것입니다.',
  DATE: '날짜',
  PRODUCT: '제품',
  USER: '사용자',
  STATUS: '상태',
  ACTIONS: '조치',
  VIEW_DETAILS: '상세 정보 보기',
  DISABLE: '사용 중지',
  ENABLE: '사용',
  CANCEL: '취소',
  PLAN_DETAILS: '플랜 상세 정보',
  SUMMARY: '요약',
  QUANTITIES: '수량',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*합계에는 플랜 기능의 가격이 포함됩니다.',
  TOTAL: '합계',
  BILLED: '청구됨',
  PLAN_INFORMATION: '플랜 정보',
  UPDATE_PLAN: '플랜 업데이트',
  ADMIN_ACTIONS: '관리자 작업',
  NAME_ON_CREDIT_CARD: '신용카드에 인쇄된 이름',
  CREDIT_CARD_BRAND: '신용카드 브랜드',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: '신용카드 번호',
  EXPIRATION: '만료',
  MONTH: '월',
  YEAR: '연도',
  SECURITY_CODE: '보안 코드',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: '신용카드 뒷면의 코드',
  BACK_TO_CHECKOUT: '체크아웃으로 돌아가기',
  NO_ORDERS_FOUND: '주문을 찾을 수 없음',
  ADD: '추가',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: '새 신용카드를 추가하려면 위의 양식을 사용하십시오. 입력란을 모두 작성하십시오',
  NUMBER: '번호',
  EXPIRES: '만료일',
  DELETE: '삭제',
  ITEM_DETAILS: '항목 상세 정보',
  FEE: '요금',
  ITEMS: '항목',
  SEARCH_BY_CONFIRMATION: '확인별 검색',
  CONFIRMATION: '확인',
  CHECKOUT_STATUS: '체크아웃 상태',
  ORDER_STATUS_PROCESS: '주문 상태 프로세스',
  CREATED_ON: '생성일',
  ORDER_SUMMARY: '주문 요약',
  APPROVED: '승인됨', //example: partner application approved
  REJECTED: '거절됨', //example: partner application rejected
  APPROVE: '승인', //example: partner application approved
  REJECT: '거부', //example: partner application rejected
  PENDING: '보류 중', //example: partner application pending
  EDIT: '편집',
  ONE_TIME_FEE: '일회 요금',
  SUB_TOTAL: '소계',
  TAXES: '세금',
  CHANGES: '변경 사항',
  CREATE_A_QUOTE: '견적 만들기',
  EXTRA_INFORMATION: '추가 정보',
  THANK_YOU_FOR_YOUR_ORDER: '주문해 주셔서 감사합니다',
  ORDER_CONFIRMATION: '주문 확인',
  INVALID_ORDER: '유효하지 않은 주문',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: '걱정하지 마십시오. 귀하에게도 이메일을 발송했습니다 :)',
  HELLO: '안녕하세요.',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: '구매해 주셔서 감사합니다. 귀하의 물품이 배송되면 확인 메일을 보내드립니다. 주문 상세 정보는 아래에 나와 있습니다.',
  ACCOUNT_INFORMATION: '계정 정보',
  BILLING_INFORMATION: '청구 정보',
  SHIPPING_INFORMATION: '배송 정보',
  NAME: '이름',
  EMAIL: '이메일',
  SEARCH: '검색',
  CLEAR: '지우기',
  PARTNER: '파트너',
  NO_PARTNERS_FOUND: '파트너를 찾을 수 없음',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: '고객이 파트너의 개인 링크로부터 상점에 들어올 경우 파트너 연결이 생성됩니다.',
  CUSTOMER: '고객',
  AGENT: '에이전트',
  NO_PARTNER_CONNECTIONS_FOUND: '파트너 연결을 찾을 수 없음',
  I_HAVE_READ_AND_AGREE_WITH_THE: '본인은 Zang 개인정보보호 방침을',
  ZANG_PRIVACY_STATEMENT: '읽고 이에 동의합니다',
  AGENT_PROGRAM_TERMS_OF_SERVICE: '에이전트 프로그램 서비스 조건',
  SUBMIT_APPLICATION: '신청서 제출',
  SUBMITTING: '제출 중',
  SUBMITTING_YOUR_APPLICATION: '귀하의 신청 제출 중',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: '모든 은행 및 계좌 정보는 당사의 약관에 따라 비공개 및 기밀로 유지됩니다.',
  BANK_NAME: '은행 이름',
  ADDRESS: '주소',
  COUNTRY: '국가',
  SELECT_ONE: '- 하나를 선택 -',
  STATE_PROVINCE: '시/도',
  CITY: '도시',
  ZIP_POSTAL_CODE: '우편번호',
  ACCOUNT_NUMBER: '계좌 번호',
  BANK_NUMBER: '은행 번호',
  TRANSIT_NUMBER: '등록 은행 번호',
  SWIFT_CODE: '은행식별(Swift) 코드',
  TAX_REGISTRATION_NUMBER: '사업자등록번호',
  SAVE_BANK_INFORMATION: '은행 정보 저장',
  SAVING_BANK_INFORMATION: '은행 정보 저장 중',
  NO_CUSTOMERS_FOUND: '고객을 찾을 수 없음',
  YOU_ARE_A: '귀하는 ',
  A_DISCOUNT_OF: '할인은',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '체크아웃 후에 총 금액에 적용됩니다.',
  FIRST_NAME: '이름',
  LAST_NAME: '성',
  COMPANY_NAME: '회사 이름',
  LEGAL_COMPANY_NAME: '법적 회사 이름',
  PHONE_NUMBER: '전화번호',
  WEBSITE: '웹 사이트',
  OPERATIONAL_ADDRESS: '회사 주소',
  SAME_AS_ORGANIZATION_ADDRESS: '조직 주소와 동일',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: '귀하는 기존 Avaya 파트너입니까?',
  NO: '아니요',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: '예, Avaya 파트너 ID를 입력하십시오',
  MY_PARTNER_PORTAL: '내 파트너 포털',
  THANK_YOU_FOR_APPLYING: '신청해 주셔서 감사합니다!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: '한 단계만 더 진행하면 완료됩니다! 영업 에이전트 신청을 완료하려면 아래 링크에 따라 모든 질문에 답해 주십시오.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' 아닌 경우 다음을 제공해 주십시오. ',
  PLEASE_GIVE: '다음을 제공해 주십시오.',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: '기존 Avaya 파트너인 경우 아래 링크로 이동하지 마십시오. <br />현재 귀하의 파트너 ID를 검토하고 있습니다. 곧 연락드리겠습니다.',
  BUSINESS: '업무일',
  DAYS: '일',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: '고위 관리진에서 귀하의 신청을 검토합니다. <br />중간에 모든 질문은 다음으로 전송할 수 있습니다',
  COMPLETE_MY_APPLICATION: '내 신청 완료',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: '당사가 귀하의 신청을 검토했습니다. 아쉽게도, 이번에는 당사의 프로그램에 적합하지 않다고 결정했습니다. 심각한 사항은 없는 것 같지만 당사가 이를 파악할 때까지 파트너십을 진행할 수 없습니다. 이 결정이 실망스러울 수 있다는 점을 이해합니다. 당사가 근거를 찾고 있으므로 이해해 주십시오. 자세한 정보를 얻으면 연락드리겠습니다. 중간에, 이 프로세스에 관해 질문이 있으시면',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: '언제든지 문의해 주십시오.',
  CONGRATULATIONS: '축하합니다!',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: '귀하는 이제 공식적인 Zang 에이전트입니다!',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: '귀하의 개인 링크를 공유하여 영업 기회를 시작하고',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: '일을 잘할 수 있는 방법을 경험할 수 있도록 도와 주십시오.',
  CHANGE_STATUS: '상태 변경',
  AGENT_DETAILS: '에이전트 상세 정보',
  BANK_INFORMATION: '은행 정보',
  THIS_ORDER_WAS_PLACED_BY_A: '이 주문은 다음에 의해 제출되었습니다',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: '합계 금액에 적용되었습니다',
  REFERRALS: '의뢰',
  SALES: '영업',
  FOUND: '검색됨',
  HOW_IT_WORKS: '작동 방법',
  WHAT_YOU_GET: '가능한 결과',
  SUPPORT: '지원',
  WHICH_PROGRAM_IS_BEST_FOR_ME: '나에게 가장 적합한 프로그램은 무엇입니까?',
  WHY_JOIN: '왜 가입해야 하나요?',
  QUOTE: '견적',
  PRINT_THIS_QUOTE: '이 견적서 인쇄',
  CLOSE_THIS_WINDOW: '이 창을 닫습니다.',
  SEARCH_BY_PLAN: '플랜으로 검색',
  ACCESS_LEVEL: '액세스 수준',
  DISPLAY_NAME: '표시 이름',
  INDUSTRY: '산업',
  COMPANY_INDUSTRY: '회사 업종',
  CONTACT_PHONE_NUMBER: '연락처 전화번호',
  EMAIL_ADDRESS: '이메일 주소',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: '예, 나에게 Zang 소식, 애플리케이션, 혜택 및 특별 행사에 관해 이메일을 보내주십시오!',
  INFORMATION: '정보',
  ORDER_HISTORY: '주문 이력',
  FILTER: '필터',
  ACCOUNT: '계정',
  AMOUNT_CHARGED: '청구된 금액',
  DETAILS: '세부 정보',
  NO_RECORDS_FOUND: '레코드를 찾을 수 없습니다',
  CALL_LOGS: '통화 로그',
  EXPORT: '내보내기',
  CALLER_NAME: '발신자 이름',
  DIALED_NUMBER: '전화건 번호',
  DURATION_SEC: '지속 시간(초)',
  COST: '비용',
  PAYMENT_METHOD: '결제 방법',
  PURCHASE_ORDER: '구매 주문서',
  PURCHASE_ORDERS: '구매 주문서',
  CREDIT_CARD: '신용카드',
  SHIPPING_ADDRESS: '배송 주소',
  SAME_AS_BILLING_ADDRESS: '배송 주소와 같음',
  SAME_AS_SHIPPING_ADDRESS: '배송지 주소와 같음',
  OTHER: '기타',
  SHIPPING_OPTIONS: '배송 옵션',
  FREE_SHIPPING: '무료 배송',
  ADDITIONAL_NOTES: '추가 메모',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: '본인은 다음을 준수하기로 동의합니다.',
  EMERGENCY_911_SERVICE_NOTICE: '비상 911 서비스 고지',
  PLACE_MY_ORDER: '내 주문하기',
  CLEAR_MY_ORDER: '내 주문 지우기',
  PLACING_YOUR_ORDER: '귀하의 주문하기',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: '잠시 기다려 주십시오. 이 프로세스는 최대 1분이 걸릴 수 있습니다.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: '이 프로세스가 진행되는 데에는 다소 시간이 걸릴 수 있습니다. 기다려 주셔서 감사합니다. 주문이 중단되지 않도록 하려면 이 브라우저 창을 닫거나 뒤로 버튼 또는 새로 고침 버튼을 클릭하지 마십시오.',
  YOUR_NEW_NUMBER: '귀하의 새 번호',
  NO_NUMBER_SELECTED: '선택된 번호 없음',
  WELL_THAT_WAS_EASY: '아주 쉬웠습니다!',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: '추가로 두 단계만 더 진행하면 완료됩니다 :)',
  NEXT: '다음',
  TITLE: '제목',
  SUB_TITLE: '부제목',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: '지역 코드로 검색... (미국 및 캐나다 전용)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: '지역 코드 입력...(미국만 해당)',
  SELECT_A_PREFIX: '접두사 선택',
  PICK_THIS_NUMBER: '이 번호 선택',
  DEVICES: '장치',
  BILLING: '청구',
  CHANGE: '변경',
  USER_INFO: '사용자 정보',
  USE_MY_INFORMATION: '내 정보 사용',
  SELECT_YOUR_DEVICES: '귀하의 장치 선택',
  MONTHLY_FEE: '월 요금',
  ANNUAL_FEE: '연 요금',
  TWO_YEAR_FEE: '2년 요금',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: '각 Zang Office 플랜은 최소한 하나의 표준 또는 고급 사용자가 필요합니다.',
  CHECKOUT: '체크아웃',
  MINE: '나의 것',
  REMOVE_THIS_USER: '이 사용자 제거',
  SELECT_A_DEVICE_FOR_THIS_USER: '이 사용자에 대한 장치 선택',
  ADD_ANOTHER: '다른 항목 추가',
  GET_STARTED_WITH_ZANG_OFFICE: 'Zang Office로 시작',
  BUNDLE: '번들',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: '1년 가입 및 혜택',
  OFF: '끄기',
  EACH_USER: '각 사용자',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: '사용자 수량을 조정하려면 귀하의 주문을 지우거나 ‘장치’ 단계를 계속해야 합니다.',
  EVERY_TWO_YEARS: '2년 마다',
  YOU_VE_SAVED: '저장했음',
  INCLUDED: '포함됨',
  ADDONS: '추가 기능',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: '각 사용자의 취향대로 사용자 정의하십시오!',
  UNITS_PER: '단위 개수',
  TALK_ANYWERE_ANYTIME: '언제 어디서나 대화하세요!',
  DOWNLOAD_FOR_MAC: 'MAC용 다운로드',
  DOWNLOAD_FOR_WINDOWS: 'Windows용 다운로드',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Zang Office를 구매해 주셔서 감사합니다! 여기서 주문을 확인하십시오!',
  CONTINUE_WITH_YOUR_PURCHASE: '구매를 계속하십시오!',
  GET_STARTED_TODAY: '지금 시작!',
  FEATURES: '기능',
  LETS_BREAK_IT_DOWN_FOR_YOU: '자세히 설명하겠습니다!',
  BASIC: '기본',
  STANDARD: '표준',
  POWER: '고급',
  RATE_MIN_STARTING_FROM: '요금/분, 시작*:',
  RATE_MIN_STARTING_FROM_1: '요금/분, 시작',
  LONG_DISTANCE: '국제 장거리 요금',
  INTERNATIONAL_LONG_DISTANCE_RATES: '국제 장거리 요금',
  COMMON_DESTINATIONS: '공통 대상',
  BEST_DEAL: '최고의 혜택',
  PER_ACTIVE_USER_PER_MONTH: '활성 사용자 당, 매월',
  ACCORDING_TO_ANNUAL_CONTRACT: '연간 계약에 따라',
  BILLED_ACCORDING_TO_SELECTED_PLAN: '선택한 플랜에 따라 요금이 청구됩니다.',
  MONTHLY: '매월',
  ANNUALLY: '매년',
  BILLED_ANNUALY: '매년 청구됨',
  BILLED_EVERY_TWO_YEARS: '2년마다 청구됨',
  CONFIGURE_YOUR_ADDONS: '추가 기능 구성',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: '이용 가능한 추가 기능 각각의 수량을 선택하십시오.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: '이 추가 기능의 최대 수량은',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: '이 추가 기능은 오직 다음에 대해서만 이용 가능합니다',
  BILLING_AND_SHIPPING: '청구 및 배송',
  BILLING: '청구',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: '귀하의 Zang Office 계정 이름이 됩니다!',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: '이 이름은 Avaya Cloud 계정 이름으로 사용됩니다.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: '귀하의 기존 또는 무료 전화 번호를 귀하의 Zang Office 번호로 사용하도록 선택한 경우, 당사는 이 필드에 사용된 내선과 함께 시내 번호를 찾습니다.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Spaces에서 모두 가능합니다',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: '항상 원했지만 찾을 수 없었던 클라우드 기반 협업 도구.',
  YOUR_CURRENT_PURCHASES: '현재 구매',
  PURCHASED_ON: '구매일',
  PLAN_NUMBER: '플랜 번호',
  UPDATE: '업데이트',
  UPDATED: '업데이트됨',
  OR: '또는',
  MAKE_A_NEW_PURCHASE: '새로 구매하기',
  FEATURES_AND_ADDONS: '기능 및 추가 기능',
  FREE: '무료',
  PLUS: '플러스',
  BUSINESS: '고급',
  VIEW: '보기',
  TEAM: '팀',
  LETS_SETUP_YOUR_TEAM: '팀을 설정하겠습니다',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: '생성하기 원하는 팀 유형을 선택하고 귀하의 개인 환경을 설정하면 됩니다.',
  COMPANY_TYPE: '회사 유형',
  DOMAIN: '도메인',
  NO_TEAM_IS_SETUP_YET: '아직 팀이 설정되지 않았음',
  DO_NOT_SETUP_A_TEAM_FOR_ME: '나를 위해 팀을 설정하지 않음',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: '바로 자신을 위해 Zang Spaces를 구매하십시오.',
  CHOOSE_AN_EXISTING_COMPANY: '기존 회사 선택',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: '귀하가 현재 관리하고 있는 회사 중 하나를 선택하십시오.',
  CREATE_A_NEW_TEAM: '새 팀 만들기',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: '팀과 도메인 이름을 입력하십시오.',
  NO_DOMAIN_IS_CONFIGURED: '도메인이 구성되지 않았습니다.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: '도메인 이름을 입력하십시오(예: \'zang.io\')',
  CHECK: '확인',
  TEAM_DOMAIN: '팀 도메인(예: \'zang.io\')',
  TEAM_NAME: '팀 이름(예: \'Zang\')',
  OK: '확인',
  ZANG_SPACES_ADMIN_CONSOLE: 'Zang Spaces 관리자 콘솔',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: '플랜을 업데이트하기 위해 아래 값을 변경할 수 있습니다',
  CHARGABLE_USERS: '청구 가능 사용자',
  TOTAL_USERS: '총 사용자',
  CURRENT_PRICE: '현재 가격',
  SAVE: '저장',
  SAVE_CHANGES_AND_UPDATE_PLAN: '변경 사항을 저장하고 플랜을 업데이트하겠습니까?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: '계속하려면 하나 이상의 유형을 선택하십시오',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: '귀하는 다음을 위해 Zang Spaces를 구매하고 있습니다',
  BUY_NOW: '지금 구매',
  SELECT: "선택",
  UP_TO: '최대',
  NO_PURCHASE_REQUIRED: '구매 필요 없음',
  NO_BILLING_OF_UPFRONT_COMMITMENT: '청구 또는 선불 의무 없음.',
  SIGN_UP_FOR_FREE: '무료로 가입하세요!',
  ONE_YEAR_PLAN: '1년 플랜',
  MONTHLY_PLAN: '월간 플랜',
  TWO_YEAR_PLAN: '2년 플랜',
  MONTHS: '월',
  ZANG_OFFICE_ACCOUNT_NAME: 'Zang Office 계정 이름',
  ZANG_OFFICE_PLAN_NUMBER: 'Zang Office 플랜 번호',
  TEMPORARY_NUMBER: '임시 번호',
  START_SETTING_UP_ZANG_OFFICE: 'Zang Office 설정을 시작하세요!',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: '기존 번호를 Zang Office 솔루션으로 이전하는 경우, LNP 승인 양식 및 가장 최근 전화 청구서 사본과 함께 zosupport@zang.io로 이메일을 보내야 합니다. 수신자부담 무료 전화를 이전하는 경우에도 RODAA 양식을 이메일로 보내주십시오. 이전이 완료되려면 10 업무일이 걸릴 수 있음을 참고하십시오.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: '선택된 Zang Office 번호를 구매/활성화는 중 오류가 발생했습니다. 수동으로 번호를 활성화/구매하려면 \'Zang Office 설정 시작\'을 클릭하십시오. 기존 번호를 사용하기로 선택한 경우, 포팅 프로세스에 영향을 주지 않습니다.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: '참고: 기존 번호를 Zang Office 계정으로 이전하는 경우, <a href="{LNP_FORM_LINK}" target="blank">LNP 승인 양식</a>을 작성하고 가장 최근의 전화 청구서 사본과 함께 이메일을 보내야 합니다. 수신자부담 무료 전화를 이전하는 경우 <a href="{RODAA_LINK}" target="blank">RODAA 양식</a>도 작성해 주십시오. 해당하는 모든 서류를 <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>(으)로 보내 주십시오. 전화번호 이전 프로세스는 최대 10일(업무일 기준)이 소요될 수 있습니다.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: '참고로 전화번호 이전 프로세스는 최대 10일(업무일 기준)이 소요될 수 있습니다. 그 동안은 계정 내에서 사용할 수 있는 임시 전화번호를 연결해 드립니다.',
  PLAN_STATUS: '플랜 상태',
  PLAN_ID: '플랜 ID',
  SUBSCRIPTION_ID: '구독 ID',
  STRIPE_PLAN_ID: '스트라이프 플랜 ID',
  ACCOUNT_ID: '계정 ID',
  START_SETTING_UP_ZANG_SPACES: 'Zang Spaces 설정 시작',
  COMPANY_DOMAIN: '회사 도메인',
  THIS_FIELD_IS_REQUIRED: '이 필드는 필수입니다.',
  PLEASE_ANSWER_THIS_QUESTION: '이 질문에 답해 주십시오.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: '귀하의 Avaya 파트너 ID를 입력하십시오.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: '계속하려면 개인정보보호 방침을 읽고 동의해 주십시오.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: '계속하려면 에이전트 프로그램 서비스 조건을 읽고 동의해 주십시오.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: '이 Avaya 파트너 ID는 이미 사용 중입니다.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: '이 사업자등록번호는 이미 사용 중입니다.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: '유효한 Avaya 파트너 ID가 아닙니다.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: '수량은 양수여야 합니다.',
  ORDER_COMPLETE: '주문 완료!',
  PLEASE_TRY_AGAIN: '다시 시도해 주십시오.',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: '최소한 하나의 양수 값을 선택하십시오',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: '아직 업데이트가 진행 중입니다. 나중에 다시 시도하십시오.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: '하나의 개인 라이센스에 둘 이상의 사용자를 가질 수 없습니다. 플랜을 업그레이드하거나 다운그레이드하려면 이에 따라 수량을 변경하십시오.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: '이 계정에 대한 액세스 권한이 없습니다.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: '귀하의 현재 플랜은 원래 인원수보다 적게 사용자를 줄이도록 허용하지 않습니다. 귀하가 조정하고자 하는 경우, customerservice@zang.io에서 당사에 문의하십시오.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: '귀하의 주문에 오류가 있었습니다.모든 필드가 유효한 값을 갖는지 확인하고, 오류가 지속될 경우, Zang 지원팀에 자세한 내용을 문의하십시오.',

  USE_EXISTING_NUMBER: '기존 번호 사용',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: '귀하의 플랜에 기존 번호를 사용하려면 선택',
  PRE_SELECT_A_TOLL_FREE_NUMBER: '수신자부담 번호 사전 선택',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: '귀하의 플랜에 혼자만의 수신자부담 번호를 추가하려면 선택',
  FIND_A_LOCAL_NUMBER: '시내 번호 찾기',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: '플랜에 추가하려면 귀하의 지역에 있는 시내 번호 목록에서 선택',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: '요금제에 지역 번호를 추가하도록 선택',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: '지역 코드별로 사용 가능한 전화번호 검색',
  SEARCH_AVAILABLE_PHONE_NUMBERS: '사용 가능한 전화번호 검색',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: '전달할 기존 번호 입력',


  ZANG_OFFICE_PHONE_APP: 'Zang Office 전화 앱',
  ZANG_OFFICE_SOFTPHONE: 'Zang Office 소프트폰',
  ZANG_OFFICE_PHONE_APPLICATION: 'Zang Office 전화 애플리케이션',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Zang Office 소프트폰은 귀하가 데스크톱이나 모바일 장치에서 기대하는 모든 통신 기능을 포함하고 있습니다. Zang Office 소프트폰이 귀하의 Zang Office 구독에 무료로 포함되기 때문에 비용 부담 없이 훌륭한 Zang Office 기능을 모두 활용하십시오!',
  E129_SIP_DESK_PHONE: 'E129 SIP 탁상용 전화',
  STANDARD_PHONE: '표준 전화',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Avaya E129 SIP 데스크폰은 귀하가 저렴하지만 기능이 우수한 SIP 전화에서 기대하던 모든 필수 통화 처리 기능을 담고 있습니다. Avaya E129 데스크폰을 이용하면 사용자가 통화를 전환, 음소거, 전달 및 보류할 수 있을 뿐 아니라 하나의 버튼을 눌러 임시 컨퍼런스를 시작할 수 있습니다. 전이중 스피커폰에서 핸즈프리 대화가 가능하며, PoE(Power over Ethernet) 포트를 통해 네트워크에 편리하게 연결할 수 있습니다. Avaya E129 SIP 데스크폰은 적절한 통화 기능을 가지며, 저렴하면서도 매력적입니다. AC 전원 어댑터가 포함되어 있습니다.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: '혁신적인 완전 유리의 전용 데스크톱 장치를 업무에 사용하십시오. 원터치 연결을 통해 음성, 채팅 및 협업 앱을 사용할 수 있습니다. 비정상적인 끊김이나 일시 중지 현상이 발생하지 않습니다. 여러 대의 업무용 장치를 관리할 필요도 없습니다. 고유하고 적절한 맞춤형 경험을 워크플로우와 비즈니스 프로세스에 적용하십시오. 이 강력한 맞춤형 장치는 데스크폰의 장점과 애플리케이션 플랫폼의 유연성을 동시에 제공합니다.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'B179 컨퍼런스 전화',
  CONFERENCE_PHONE: '컨퍼런스 전화',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: '중역 회의실 및 10명 이상의 그룹을 가진 대형 컨퍼런스 룸에 가장 적합한 B179 컨퍼런스 전화는 직원 생산성과 협업을 개선하는 데 도움이 됩니다. B179 컨퍼런스 폰은 다재다능한 고성능 장치로서 기존 솔루션을 보완하며, 회사의 성장이나 요구 변화에 맞게 쉽게 재배치가 가능합니다. AC 전원 어댑터가 포함되어 있습니다.',
  PLAN: '플랜',
  REDIRECTING: '재전송 중...',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: '모든 필드가 유효한 값을 갖는지 확인하십시오',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: '각 Zang Office 플랜은 하나 이상의 사용자 유형이 필요합니다. 장치 선택 단계로 돌아가서 구성을 변경하십시오.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: '귀하가 Zang Office 계정에 아무 번호도 선택하지 않은 것 같습니다. 번호 선택 단계로 돌아가서 번호를 선택하십시오.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: '해당 Zang Office 계정 이름이 적용되었습니다. 다른 번호 시도',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: '귀하가 선택한 Zang Office 번호는 이미 다른 고객이 구매했습니다. 번호 선택 단계로 돌아가서 다른 번호를 선택하십시오.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: '약정 없는 월별 플랜으로 이동하고 <span class="text-400">첫 30일간 무료</span>로 사용할 수 있습니다.',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: '또는 가격이 더 저렴한 연간 플랜을 약정할 수 있습니다.',
  FREE_PHONE: '무료 전화',
  DISCOUNT: '할인',
  DISCOUNTED_PHONE: '할인된 전화',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: '전화 구매 총 가격에서 할인',
  LIMITED_TIME_OFFER: '한정 기간 제공',
  PROMOTION: '프로모션',
  ZANG_SPACES_PROMOTION: 'Zang Spaces 프로모션',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: '전화번호 선택으로 계속',
  DURATION: '지속 시간',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: '축하합니다! 전체 장치 주문 금액을 지불할 수 있는 <strong>{amount}</strong>의 크레딧이 제공됩니다!',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: '모든 해당 할인은 귀하의 최종 주문 요약에서 저정됩니다.',
  SHIPPING_TYPE: '배송 유형',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: '상세 추적 정보는 귀하의 품목이 당사 창고에서 배송되면 발송됩니다.',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: '장치 구매를 위해 사용자당 {amount} 크레딧을 받으십시오. 한정 기간에만 제공됩니다.',
  PARTNER_ORDERS: '파트너 주문',
  COMMISSION: '커미션',

  ADDITIONAL_DEVICES: '추가 장치',
  NO_USER: '사용자 없음',
  QUANTITY: '수량',
  BUY_DEVICES: '장치 구매',
  DEVICE: '장치',
  PRICE: '가격',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: '에이전트를 검색하려면 {chars}자 이상 입력하십시오.',
  NO_RESULTS_FOUND: '결과를 찾을 수 없음',
  RESULTS_COULD_NOT_BE_LOADED: '결과를 로드할 수 없습니다.',
  CLEAR_SELECTION: '선택 지우기',


  RESET_ALL_PURCHASES: '모든 구매 지우기',
  LISTS: '목록',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: '견적을 생성하기 전에 전화번호를 작성하십시오.',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: '견적을 생성하기 전에 청구 및 배송 정보를 작성하십시오',
  CALCULATING_TAXES_PLEASE_WAIT: '세금을 계산 중입니다. 기다려 주십시오...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: '선택한 신용카드에 문제가 있습니다.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: '이 신용카드에 문제가 있습니다. 다른 신용카드를 사용하십시오.',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: '주문 결제 중에 오류가 발생했습니다. 다른 신용카드를 선택하십시오.',
  INVALID_CREDIT_CARD: '유효하지 않은 신용카드',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type}이(가) 신용카드 주소 정보와 일치하지 않습니다',
  INVALID_SECURITY_CODE: '잘못된 보안 코드(cvc)',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: '이 계산서에 해당하는 할인 및 프로모션 가격이 적용되었습니다.',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: '고객 계정을 생성할 수 없습니다. 다시 시도해 주십시오.',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '신용카드를 생성할 수 없습니다. 다시 시도해 주십시오.',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '이 신용 카드는 정기 서브스크립션에 사용 중입니다.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '이 신용 카드를 기본 카드로 설정하는 동안 오류가 발생했습니다.',
  DEFAULT: '기본값',
  SET_DEFAULT: '기본값으로 설정',
  SALES_FORCE_QUOTE_ID: 'Salesforce 견적 ID',
  SALES_FORCE_ORDER_ID: 'Salesforce 주문 ID',
  SALES_FORCE_OPPORTUNITY_ID: 'Salesforce 기회 ID',
  SALES_FORCE_CONTACT_ID: 'Salesforce 연락처 ID',
  SALES_FORCE_CONTRACT_ID: 'Salesforce 계약 ID',
  SALES_FORCE_ACCOUNT_ID: 'Salesforce 계정 ID',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '\'장치 추가\' and connect it with a user.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '간단히 \'장치를 추가\'하고 사용자에게 연결하십시오.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Zang Office 계정의 추가 장치 구입',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: '죄송합니다! 주문에 문제가 발생했습니다. 페이지를 새로 고치고 주문을 지운 후 다시 시작하십시오.',
  CREATE_A_NEW_COMPANY: '새 회사 생성',
  ADD_A_NEW_COMPANY: '새 회사 추가',
  PARTNER_DETAILS: '파트너 세부 정보',
  AGENTS: '에이전트',
  PARTNER_PORTAL: '파트너 포털',
  AGENT: '에이전트',
  AGENT_PORTAL: '에이전트 포털',
  NO_AGENTS_FOUND: '에이전트를 찾을 수 없음',
  NO_AGENT: '에이전트가 없음',
  RELATION: '관계',
  OWNER: '소유자',
  ADMIN: '관리자',
  MANAGER: '매니저',
  EMPLOYEE: '직원',
  ACTIVE: '활성',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: '관련 파트너 중 하나를 선택하십시오.',
  APPLIED_ON: '신청한 날짜',
  JOIN_A_PARTNER: '파트너 가입',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: '<b>{COMPANY_NAME}</b> 가입이 얼마 남지 않았습니다.',
  JOIN_PLACEHOLDER_NOW: '지금 {COMPANY_NAME} 가입',
  UPDATE_AGENT_INFO: '에이전트 정보 업데이트',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup> 시작',
  IN_ASSOCIATION_WITH_ZANG_TM: 'Zang™과 연계',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: '간편하고 강력한 통합 공동 작업 솔루션',
  IP_OFFICE_DONT_PAY_TILL: '2018년 4월 15일까지 무료로 사용할 수 있습니다.',
  LOGIN: '로그인',
  DISCOVER: '찾기',
  SOLUTIONS: '솔루션',
  SERVICES: '서비스',
  INDUSTRIES: '업종',
  CASE_STUDIES: '사례 연구',
  PROGRAMS_AND_PROMOTIONS: '프로그램 및 프로모션',
  AUTHENTIC_AVAYA: 'Authentic Avaya',
  PERSPECTIVES: 'Perspectives',
  AVAYA_CONNECTED_BLOG: 'Avaya Connected Blog',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: '솔루션 찾기',
  INFO_FOR: '관련 정보',
  DEVELOPERS: '개발자',
  CHANNEL_PARTNERS: '채널 파트너',
  TECHNOLOGY_PARTNERS: '기술 파트너',
  CONSULTANTS: '컨설턴트',
  INVESTORS: '투자자',
  MEDIA_ANALYSTS: '미디어 분석가',
  SUPPLIERS: '공급업체',
  CONNECT_WITH_US: 'Avaya에 문의하기',
  FIND_A_CHANNEL_PARTNER: '채널 파트너 찾기',
  FIND_A_TECHNOLOGY_PARTNER: '기술 파트너 찾기',
  EXECUTIVE_BRIEFING_CENTER: '솔루션 체험 센터',
  AVAYA_LEARNING_SERVICES: 'Avaya 학습 서비스',
  CONTACTS: '연락처',
  ABOUT_AVAYA: 'Avaya 정보',
  EVENTS: '이벤트',
  NEWSROOM: '뉴스룸',
  INVESTOR_RELATIONS: '투자자 관계',
  CORPORATE_RESPONSIBILITY: '사회적 책임',
  OUR_COMPANY: 'Avaya',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'International Avaya Users Group - IAUG',
  CAREERS: '경력',
  YOUR_PERSONAL_LINK: '개인 링크',
  SITEMAP: '사이트맵',
  TERMS_OF_USE: '사용 약관',
  PRIVACY: '프라이버시',
  COOKIES: '쿠키',
  AVAYA_INVOICE: '송장',
  IP_OFFICE_ACCOUNT_NAME: 'Avaya Cloud 계정 이름',
  IP_OFFICE_PLAN_NUMBER: 'Avaya Cloud 플랜 번호',
  IP_OFFICE_PHONE_APPLICATION: 'Avaya Cloud Solutions 소프트폰',
  IP_OFFICE_PHONE_DESCRIPTION: 'Avaya Cloud Solutions 소프트폰의 단일 인터페이스를 통해 모든 통신 채널에 간편하게 액세스할 수 있습니다. Avaya Cloud Solutions 소프트폰을 사용하면 Avaya Cloud Solutions에 로그인한 후 PC를 사용하여 일반 전화기 내선으로 음성 및 화상 통화를 걸고 받을 수 있습니다. 소프트폰은 Avaya Cloud Solutions 표준 및 고급 사용자 서브스크립션에 가입하면 무료로 사용할 수 있습니다.',
  PLAN_MONTH_1_MONTH_1: '월간 플랜(장치 크레딧 없음)',
  PLAN_YEAR_1_MONTH_1: '간1년 플랜 | 월 단위 청구',
  PLAN_YEAR_1_YEAR_1: '1년 플랜, 일시불',
  PLAN_YEAR_2_MONTH_1: '2년 플랜 | 월 단위 청구',
  PLAN_YEAR_2_YEAR_1: '2년 플랜 | 연 단위 청구',
  PLAN_YEAR_2_YEAR_2: '2년 플랜, 일시불',
  PLAN_YEAR_3_MONTH_1: '3년 플랜 | 월 단위 청구',
  PLAN_YEAR_3_YEAR_1: '3년 플랜 | 연 단위 청구',
  PLAN_YEAR_3_YEAR_3: '3년 플랜, 일시불',
  PLAN_YEAR_5_MONTH_1: '5년 플랜 | 월 단위 청구',
  ACCORDING_TO_PLAN: '플랜에 따라',
  TOTAL_USER_PLAN_FEE: '총 사용자 플랜 요금',
  HEALTHCARE_DENY_MESSAGE: 'Avaya Cloud를 귀사 솔루션으로 선택해 주셔서 감사합니다. 죄송하지만 당사 제품은 아직 HIPAA를 준수하지 않으므로 의료 업종에 해당하는 귀사에 서비스를 제공해 드릴 수 없습니다. 당사의 인증이 완료되는 대로 알려드리겠습니다. 그때 함께 일하게 되길 바랍니다. 질문이 있는 경우 <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a>로 언제든지 문의해 주십시오.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup> 장치 선택',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup> 번호 선택',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: '사용자를 조정한 후 장치를 할당하십시오.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Avaya Cloud Solutions에 사용할 전화번호를 추가하십시오.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: '솔루션에 전화번호를 할당하십시오.',
  INVITE_A_NEW_AGENT: '새 에이전트 초대',
  I_WANT_TO_INVITE_A: '초대하고 싶은 대상:',
  CONTACT_EMAIL: '담당자 이메일',
  CONTACT_NAME: '담당자 이름',
  COMPANY_NAME: '회사 이름',
  CONTACT: '연락처',
  COMPANY_IS_INCORPORATED: '법인',
  INDIVIDUAL: '개인',
  INDIVIDUALS: '개인',
  SEND_INVITATION_EMAIL: '초대 이메일 보내기',
  SENDING_INVITATION_EMAIL: '초대 이메일을 보내는 중...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: '초대가 성공적으로 발송되었습니다',
  ALL_FIELDS_ARE_REQUIRED: '모든 필드는 필수입니다.',
  PARTNER_NOT_FOUND: '파트너를 찾을 수 없음',
  SALE_AGENT_REGISTRATION: '판매 에이전트 등록',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: '판매 에이전트가 되려면 아래 양식을 작성하십시오.',
  VIEW: '보기',
  COMPANIES: '회사',
  ADD_A_PARTNER: '파트너 추가',
  ADD_PARTNER: '파트너 추가',
  PARTNERS_PERSONAL_LINK: '파트너 개인 링크',
  MASTER_SALES_AGENT: '마스터 판매 에이전트',
  AVAYA_J129_LABEL: 'J129 IP 폰',
  AVAYA_J129_DESCRIPTION: '합리적인 가격으로 우수한 기능을 제공하는 SIP 폰의 모든 핵심 통화 처리 기능을 이용해 보십시오. 이 전화기는 기업 규모와 관계없이 사용자에게 필요한 핵심 기능을 제공합니다. 또한 단일 회선 통화 디스플레이에서 2개의 통화 표시 형식을 지원합니다. 오늘날 시중에서 판매되는 그 어떤 제품보다 강력한 기능을 제공하는 이 전화기를 구매해 보십시오.',
  AVAYA_J169_LABEL: 'J169 IP 폰',
  AVAYA_J169_DESCRIPTION: '합리적인 가격으로 우수한 기능을 제공하는 SIP 폰의 모든 핵심 통화 처리 기능을 이용해 보십시오. 이 전화기는 기업 규모와 관계없이 사용자에게 필요한 핵심 기능을 제공합니다. 또한 단일 회선 통화 디스플레이에서 2개의 통화 표시 형식을 지원합니다. 오늘날 시중에서 판매되는 그 어떤 제품보다 강력한 기능을 제공하는 이 전화기를 구매해 보십시오.',
  AVAYA_J179_LABEL: 'J179 IP 폰',
  AVAYA_J179_DESCRIPTION: '합리적인 가격으로 우수한 기능을 제공하는 SIP 폰의 모든 핵심 통화 처리 기능을 이용해 보십시오. 이 전화기는 기업 규모와 관계없이 사용자에게 필요한 핵심 기능을 제공합니다. 또한 단일 회선 통화 디스플레이에서 2개의 통화 표시 형식을 지원합니다. 오늘날 시중에서 판매되는 그 어떤 제품보다 강력한 기능을 제공하는 이 전화기를 구매해 보십시오.',
  AVAYA_K175_LABEL: 'Avaya Vantage™ K175',
  AVAYA_K175_DESCRIPTION: '합리적인 가격으로 우수한 기능을 제공하는 SIP 폰의 모든 핵심 통화 처리 기능을 이용해 보십시오. 이 전화기는 기업 규모와 관계없이 사용자에게 필요한 핵심 기능을 제공합니다. 또한 단일 회선 통화 디스플레이에서 2개의 통화 표시 형식을 지원합니다. 오늘날 시중에서 판매되는 그 어떤 제품보다 강력한 기능을 제공하는 이 전화기를 구매해 보십시오.',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: '9641GS IP 데스크폰',
  AVAYA_9641G_DESCRIPTION: 'Avaya 9641GS는 많은 시간 동안 전화로 업무를 하고 인텔리전트 통신 및 생산성 향상 기능에 의존하는 사용자들에게 적합한 다중 회선 프리미엄 데스크폰입니다. 9641GS는 5.0인치 컬러 그래픽 디스플레이, 한층 확장된 터치스크린 및 HD 오디오 품질을 자랑합니다. 이 전화기의 광대역 오디오 코덱은 송수화기, 헤드셋 및 스피커폰을 비롯한 모든 오디오 인터페이스에서 뛰어난 오디오 성능을 제공합니다.',
  AVAYA_9608G_LABEL: '9608G IP 데스크폰',
  AVAYA_9608G_DESCRIPTION: '통합형 기가비트 및 흑백 디스플레이를 지원하는 9608G Deskphone은 완벽한 기능을 갖춘 비용 효과적인 전화기입니다. PoE(Power over Ethernet) 기술로 간편하게 구축 가능하고 광대역 오디오 코덱이 뛰어난 오디오 성능을 제공합니다. 중소기업부터 대기업까지 모든 규모의 기업에 적합한 이 데스크폰은 8개 회선을 활용하며 중앙 관리식 그래픽 레이블을 제공합니다.',
  AVAYA_9611G_LABEL: '9611G IP 데스크폰',
  AVAYA_9611G_DESCRIPTION: '9611G 모델에는 통합형 기가비트 및 USB 인터페이스가 포함되어 있습니다. 또한 화이트 백라이트의 3.5인치 그래픽 컬러 디스플레이와 중앙 관리식 그래픽 레이블을 제공합니다. PoE(Power over Ethernet) 기술로 간편하게 구축 가능하고 광대역 오디오 코덱이 뛰어난 오디오 성능을 제공합니다.',
  AVAYA_PHONE_B179_LABEL: 'B179 SIP 컨퍼런스 전화',
  AVAYA_PHONE_B179_DESCRIPTION: 'Tolly의 테스트를 거친 이 유연한 SIP 기반 컨퍼런스 전화는 Avaya의 특허받은 광대역 오디오 기술인 OmniSound 2.0을 사용하여 선명하고 자연스러운 사운드를 제공합니다. 이 전화기에는 더욱 효율적인 컨퍼런스 통화를 위한 인텔리전트 기능이 포함되어 있습니다. 컨퍼런스 가이드를 사용하면 미리 프로그래밍된 그룹과 통화할 수 있습니다. 또한 웹 인터페이스를 통해 연락처 세부 정보를 편리하게 가져오고 내보낼 수 있습니다. 개인 사용자 프로필 기능을 사용하면 자신만의 연락처 목록을 만들 수 있습니다.',
  HAVE_LARGE_NUMBERS_OF_USERS: '사용자가 많나요?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: '볼륨 할인 방식을 검토해 보십시오.',
  DEVICE_FEE: '장치 요금',
  UP_TO_DEVICE_CREDITE_PER_USER: '사용자당 최대 {$}의 장치 크레딧',
  PROMOTION_REMAINING_DETAIL_INFO: '프로모션 장치 크레딧이 <b>{0}</b> 남아 있습니다. 구매 후에는 남은 크레딧이 모두 소멸되며 향후 구매를 위해 귀하의 계정으로 이월되지 않습니다.',
  VIEW_USER_FEATURES: '사용자 기능 보기',
  FREE_DEVICES_PER_USER_INFO: '{0}(사용자당 최대 {1}의 장치 크레딧)',
  VALUE_OF_DEVICE_CREDIT: '{0}명 사용자 = 총 {0}의 장치 크레딧',
  PROMOTION_DELAYED_BILLING_INFO: '프로모션: 상세한 영수증이 제공되며, 청구 주기가 공식적으로 시작되면 미결 잔액이 신용 카드로 청구됩니다.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: '주문을 완료하려면 에이전트를 선택하십시오.',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: '유효한 도메인 이름(example.com)을 입력하십시오.',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Avaya Cloud Solution 시스템이 준비됐습니다!',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Avaya Cloud Solution 시스템이 설정되었습니다.',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Avaya Cloud Solutions 전화번호',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Avaya Cloud Solutions SIP 도메인 이름',
  IP_OFFICE_SIP_DOMAIN_ID: 'Avaya Cloud Solutions SIP 도메인 ID',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Avaya Cloud Solution 시스템을 구성 중입니다.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: '주문해 주셔서 감사합니다. 현재 귀하의 Avaya Cloud Solutions 시스템을 설정하고 있으며 구성이 완료되면 알려 드리겠습니다. <br /> 질문이 있으면 Avaya Cloud Solutions 지원 팀({IPO_SUPPORT_EMAIL})으로 언제든지 문의해 주십시오.',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: '이 계정을 프로비저닝하지 못했습니다.',
  ERROR_CODE: '오류 코드',
  ERROR_MESSAGE: '오류 메시지',
  ADMIN_PORTAL_LINK: '관리자 포털 링크',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Avaya Cloud Solutions 기본 사용자 비밀번호',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Avaya Cloud Solutions 임시 전화번호',
  IP_OFFICE_BASIC_EXTENSION_RANGE: '기본 사용자 내선 번호',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: '표준 사용자 내선 번호',
  IP_OFFICE_POWER_EXTENSION_RANGE: '고급 사용자 내선 번호',
  IP_OFFICE_DEFAULT_USER_PIN: '기본 사용자 PIN',
  IP_OFFICE_SAME_AS_PIN: '내선과 동일(예: 200)',
  IP_OFFICE_ORDERID: 'Avaya Cloud Solutions 주문 ID',
  IP_OFFICE_HOST_NAME: 'Avaya Cloud Solutions 호스트 이름',
  IP_OFFICE_IP_ADDRESS: 'Avaya Cloud Solutions IP 주소',
  IP_OFFICE_SUBSCRIPTIONID: 'Avaya Cloud Solutions 서브스크립션 ID',
  CALCULATING: '계산 중...',
  RESET_ALL_PARTNERS: '파트너 데이터 지우기',
  ERROR_GETTING_AGENTS: '에이전트를 확인하는 동안 오류가 발생했습니다. 다시 시도하십시오.',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: '이 이메일을 사용하는 에이전트가 팀에 이미 있습니다.',
  AUTO_APPROVE_ACTIVATE_AGENT: '자동 승인/에이전트 활성화',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: '이 이메일을 사용하는 회사가 팀에 이미 있습니다.',
  MASTER_SALES_AGENT_PORTAL: '마스터 판매 에이전트 포털',
  SALES_AGENT_PORTAL: '판매 에이전트 포털',
  E911_ADDRESS: 'E911 주소',
  OVERVIEW: '개요',
  ADD_COMPANY_OR_SALES_AGENT: '회사 또는 에이전트 추가',
  ADD_AN_AGENT: '에이전트 추가',
  INACTIVE: '비활성',
  AGENTS_PERSONAL_CONNECTION_LINK: '에이전트의 개인 연결 링크',
  PURCHASE_DATE_AND_CUSTOMER: '구매 날짜 및 고객',
  ORDER_DETAILS: '짜주문 상세 정보',
  SELECT_AGENT: '모든 에이전트',
  FROM: '시작',
  TO: '끝',
  EXPORT_REPORT: '보고서 내보내기',
  NO_SALES_FOUND: '판매 기록 찾을 수 없음',
  ADD_A_COMPANY: '회사 추가',
  AUTO_APPROVE_COMPANY: '회사 자동 승인',
  AUTO_ACTIVATE_AGENT: '에이전트 자동 활성화',
  ADD_COMPANY: '회사 추가',
  ADD_COMPANY_NAME_AGENT_ADMIN: '{COMPANY_NAME} 에이전트/관리자 추가',
  ADD_AGENT_ADMIN: '에이전트/관리자 추가',
  ALL_COMPANIES: '모든 회사',
  START_DATE: '시작 날짜',
  HEY: '안녕하세요!',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: '저희는 귀하의 고객 지원 매니저입니다. Avaya Cloud Solutions를 효과적으로 활용할 수 있도록 도움을 드리기 위해 연락드렸습니다. Avaya Cloud Solutions 지원 팀에는 당사의 기술 지원 팀(<a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>)도 포함되어 있습니다.',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: '며칠 후에 지원 팀을 소개하고 시스템 구성을 마치기 위한 킥오프 통화를 진행하려고 합니다. <strong><a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> 주소로 1시간 정도 진행될 킥오프 통화를 위한 편한 날짜와 시간을 알려 주십시오.<strong>',
  START_USING_YOUR_IP_OFFICE: '소지금 바로 Avaya Cloud Solutions 시스템을 사용해 보십시오!',
  BELOW_ARE_DETAILS: '귀하의 시스템 계정 정보, 사용자 자격 증명 및 애플리케이션 다운로드는 다음과 같습니다.',
  YOUR_IP_OFFICE_INFO: '시스템 정보:',
  LOGIN_INFO_TABLE: '사용자 정보 차트:',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: '모든 사용자는 위 정보로 개별 클라우드 사용자 포털에 로그인하여 자신의 정보를 구성하고, 착신 통화 전환을 조정하고, 음성 메일을 수신할 수 있습니다.',
  AVAILABLE_APPLICATIONS_FOR_USERS: '귀하의 사용자가 사용 가능한 애플리케이션:',
  DO_NOT_HESITATE_TO_EMAIL_US: '질문이 있는 경우 주저하지 말고 <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a> 주소로 이메일을 보내 주십시오.',
  THANK_YOU: '감사합니다!',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web(Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web(Chrome 확장 프로그램)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO(iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO(Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions Soft Console(Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">설치 설명서</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">설치 설명서</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">설치 설명서</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">설치 설명서</a>',




  USER_NAMES_COLUMN: '사용자 이름',
  EXTENSIONS_COLUMN: '내선',
  TEMP_PIN_COLUMN: '고정',
  TEMP_PASSWORD_COLUMN: '비밀번호',
  USER_TYPE_COLUMN: '사용자 유형',
  DEVICE_MODEL_COLUMN: '장치',
  POWER_USER: '고급',
  STANDARD_USER: '표준',
  BASIC_USER: '기본',
  ORDERID: '주문 ID',
  ACCOUNT_NAME: '계정 이름',
  HOST_NAME: '호스트 이름',
  ADMIN_PORTAL: '관리자 포털',
  IP_ADDRESS: 'IP 주소',
  PHONE_NUMBER: '전화번호',
  TEMPORARY_PHONE_NUMBER: '임시 전화번호',
  EXCITING_TIMES_AHEAD: '향후 즐거운 혜택',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: '도메인 이름 {DOMAIN_NAME}은(는) 잘못된 도메인 이름이거나 다른 회사에서 사용 중인 도메인 이름입니다.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: '도메인 이름 {1}은(는) 잘못된 도메인 이름이거나 다른 회사에서 사용 중인 도메인 이름입니다.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: '시스템에서 귀사를 검증하지 못했습니다. 다시 시도하십시오.',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'N/A 정보(있는 경우)의 경우 Avaya Cloud 지원 팀에 문의하십시오.',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Avaya Cloud 계정이 프로비저닝을 시작하지 못했습니다.',
  LEGAL: '법률 고지',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: '1년 플랜(또는 그 이상)을 선택하면 모든 장치 구입 시 사용자당 1 크레딧을 받을 수 있습니다. 기간 한정 서비스입니다.',
  USER_PORTAL: '사용자 포털',
  E_911: 'E911',
  DECLINE: '거절',
  ACCEPT: '수락',
  PRINT: '인쇄',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: '주문을 완료하려면 위 약관에 모두 동의하십시오.',
  ASSING_A_DEVICE_TO_YOUR_USERS: '사용자에게 장치를 할당하십시오.',
  SELECT: '선택',
  USER_DETAILS: '사용자 세부 정보',
  DEVICE_DETAILS: '장치 세부 정보',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: '사용 약관을 잘 읽은 후에 동의하십시오.',
  PARTNER_ORDERS_RECORDS_HINT: '*모든 판매 기록은 참조용일 뿐입니다. 공식적인 최종 판매 보고서는 마스터 판매 에이전트 계약에 따라 Avaya 재무 팀에서 제공합니다.',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: '견적을 생성하려면 판매 에이전트를 선택하십시오.',
  COMPANY_DETAILS: '회사 세부 정보',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: '해당 세금이 추가됩니다.',
  SELECT_PRODUCT: '제품 선택',
  CLOUD_UC_SMALL_MONTH1: 'Cloud UC Essential 월간 플랜',
  SMALL: '소규모',
  CLOUD_UC_SMALL_MONTH12: 'Cloud UC Essential 1년 플랜',
  CLOUD_UC_SMALL_3YEARS: '클라우드 UC Essential 3년 플랜',
  CLOUD_UC_SMALL_5YEARS: '클라우드 UC Essential 5년 플랜',
  MEDIUM: '중간 규모',
  CLOUD_UC_MEDIUM_MONTL1: 'Cloud UC Business 월간 플랜',
  CLOUD_UC_MEDIUM_MONTH12: 'Cloud UC Business 1년 플랜',
  CLOUD_UC_MEDIUM_3YEARS: 'Cloud UC Business 3년 플랜',
  CLOUD_UC_MEDIUM_5YEARS: 'Cloud UC Business 5년 플랜',
  LARGE: '대규모',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC Large 종량제',
  CLOUD_UC_LARGE_MONTL12: 'Cloud UC Large 연간 플랜',
  CLOUD_UC_SMALL_SHORT_INFO: '1-99명 직원',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100-999명 직원',
  CLOUD_UC_LARGE_SHORT_INFO: '1000+명 직원',
  SELECTED: '선택됨',
  BASIC_PHONE_SERVICE: '기본 전화 서비스',
  UNLIMITED_NATIONAL_WIDE: '무제한 국내 장거리 전화',
  STANDARD_FEATURES: '표준 기능',
  HOW_MANY_USERS: '몇 명의 사용자가 필요한가요?',
  ADD_ON_ADDITIONAL_FEATURES: '추가 기능',
  ONETIME_FEE: '일회 요금',
  RECURRING_FEE: '정기 요금',
  SELECT_MAIN_NUMBER: '주 번호 선택',
  TOLL_FREE: '수신자 부담 전화',
  LOCAL_NUMBER: '로컬 번호',
  TRANSFER_NUMBER: '전환 번호',
  USERS_COUNT: '{qty}명 사용자',
  DEVICES_COUNT: '{qty}대 장치',
  UC_OFFER_TITLE: '귀하에게 딱 맞는 솔루션이 있습니다.',
  UC_OFFER_DESCRIPTION: '기업 규모와 관계없이 귀하가 원하는 솔루션을 제공해 드리겠습니다. 귀하의 비즈니스 유형을 선택해 주십시오.',

  // 'BASIC_PHONE_SERVICE': '기본 전화 서비스',

  TAX_CALC_ERROR_MSG: '세금을 계산할 수 없습니다. 청구 주소가 올바른지 확인하십시오.',
  'VIOLATION.FIELD_IS_EMPTY': '{1}은(는) 필수 항목입니다.',
  'VIOLATION.FIELD_IS_EMPTY2': '{1}-{2}은(는) 필수 항목입니다.',
  'VIOLATION.FIELD_VALUE_INVALID': '{1} 값이 올바르지 않습니다.',
  'VIOLATION.FIELD_VALUE_INVALID2': '{1}-{2} 값이 올바르지 않습니다.',
  'VIOLATION.TAX_CALCULATION_FAILED': '세금을 계산하지 못했습니다.',
  'VIOLATION.AGREE_ON_LEGAL_DOC': '"{1}"을(를) 읽고 동의해야 합니다.',
  'VIOLATION.CART_IS_EMPTY': '장바구니가 비어 있습니다.',
  'VIOLATION.CART_IS_TOO_BIG': '장바구니에 너무 많은 항목이 들어 있습니다.',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1}이(가) 장바구니에서 제거됩니다.',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': '{1} 수량이 {2}에서 {3}(으)로 조정됩니다.',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': '{1} 할인이 {2}에서 {3}(으)로 조정됩니다.',
  'SALESMODELRULE.NOT_SAME_CURRENCY': '{1} 통화의 항목을 {2} 통화의 장바구니에 추가할 수 없습니다.',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': '할인 규칙 {1}이(가) 정의되어 있지 않습니다.',
  'SALESMODELRULE.UNKNOWN_ERROR': '알 수 없는 오류',
  'SALESMODELRULE.INVALID_PARAMETER': '잘못된 파라미터: {1}',
  ONE_TIME: '일회',
  ADDON_PRICING_HINT: '*추가 기능 가격은 사용자당 부과되며 모든 사용자에게 적용됩니다. 관리 포털에서 추가 기능을 구매한 후에 사용자에게 특정 추가 기능을 추가할 수 있습니다.',
  ADD_TO_CART_HINT: '장바구니에 추가하려면 위 단계를 완료하십시오.',
  ITEM_UNITS: '{qty}개 단위',
  ADDONS_COUNT: '{qty}개 추가 기능',
  ADDON_COUNT: '{qty}개 추가 기능',
  MULTIPLE_TYPES: '다중 유형',
  MIXED: '혼합형',
  FREE_PRICE: '무료',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essential',
  UC_ESSENTIALS_DESCRIPTION: '모든 규모의 기업에 적합한 최고의 클라우드 기반 통신을 제공합니다.',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: '클라우드에서 최고의 엔터프라이즈 통신이 가능합니다.',
  UC_BUSINESS_POWER_PACKAGE: '고급 사용자로 업그레이드',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>직통 전화번호:</strong> 전용의 고유 번호로 누구든지 사무실 대표 번호나 안내원(가상 또는 실제 직원)을 통하지 않고 직접 귀하와 통화할 수 있습니다.</li><li><strong>직통 화상 통화:</strong> 지점 간 전화 통화에 화상 기능을 추가합니다.</li><li><strong>Salesforce© 통합:</strong> Salesforce 내에서 직접 최종 사용자와 완전하고 풍부한 통신이 가능합니다.</li><li><strong>Google© 통합:</strong> Google Chrome과 모든 Google 앱에서 직접 브라우저 기반의 실시간 통신이 가능합니다.</li><li><strong>비즈니스용 Skype© 통합:</strong> 비즈니스용 Skype로 간소화되고 사용하기 쉬운 최신 공동 작업 환경을 제공할 수 있습니다.</li></ul>',
  SHOW_MORE: '더 보기',
  HIDE: '숨기기',
  VIEW_COMPLETE_FEATURE_LIST: '전체 기능 목록 보기',
  FILTER_BY: '필터 기준',
  UC_OFFERS: 'UC 솔루션',
  PAY_MONTHLY: '월간 결제',
  PAY_ANNUALLY: '연간 결제',
  COMING_SOON: '출시 예정',
  TAX_CALC_ERROR_MSG: '세금을 계산할 수 없습니다. 주소가 올바른지 확인하십시오.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: '현재 장거리 요금을 검토하려면 국가 이름을 입력하십시오.',
  LONG_DISTANCE_RATE_NOT_FOUND: '이 국가에 대한 장거리 요금을 찾을 수 없습니다. 이 국가의 장거리 통화에 대한 자세한 내용은 {CUSTOMER_SUCCESS_EMAIL} 주소로 문의하십시오.',
  AREA_CODE: '지역 코드',
  INVALID_CREDIT_CARD_ZIP: '신용 카드가 우편 번호와 일치하지 않습니다.',
  VIEW_LONG_DISTANCE_RATES: '장거리 요금 보기',
  LONG_DISTANCE_SUBTITLE_TEXT: '당사의 저렴한 장거리 통화 요금으로 전 세계 누구와도 마음 놓고 연락할 수 있습니다.',
  RATES_SUBJECT_TO_CHANGE: '*요금은 예고 없이 변경될 수 있습니다.',
  CREDIT_CARD_DECLINED: '신용 카드가 거부되었습니다.',
  ENTER_COUNTRY_NAME: '국가 이름 입력',
  ADD_TO_CART: '장바구니에 추가',
  UPDATE_CART: '장바구니 업데이트',
  PER_USER: '사용자 기준',
  COMPARE_UC_OFFERS: 'UC 제품 비교',
  PROCEED_TO_CHECKOUT: '계산 진행',
  BEFORE_APPLICABLE_TAXES: '* 세금 부과 전',
  YEAR_PLAN: '1년 플랜',
  YEARS_PLAN: '{0}년 플랜',
  MONTHS_PLAN: '{0}개월 플랜',
  ENTER_NUMBER_OF_USERS: '이 솔루션에 포함할 사용자 수 입력',
  YEAR: '연도',
  BILLED_MONTH: '월 단위로 청구됨',
  COMPANY_INCORPORATED: '법인',
  COMPANY_NOT_INCORPORATED: '비법인',
  EXISTING_CONFIG_WARNING: '<br/><b>{0}</b>에 대한 기존 구성이 있습니다.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: '현재 구성을 취소하시겠습니까?',
  DISCARD_MY_CONFIGURATION: '내 구성 취소',
  DISCARD: '무시',
  EDIT_MY_CONFIGURATION: '현재 구성 편집',
  CONTINUE: '계속',
  SELECT_A_PLAN: '플랜 선택',
  PROMOTION_DETAIL_INFO: '*총 <b>{0}명의 사용자</b>를 선택하셨습니다.<br/> 총 장치 크레딧 <b>{1}</b>에 해당합니다.',
  BILLED_MONTH_FREQUENCY: '{0}개월마다 청구됨',
  BILLED_YEAR_FREQUENCY: '{0}년마다 청구됨',
  CONTACT_OUR_CUSTOMER_CARE: '고객 관리 팀에 문의',
  NEED_HELP_INFO: '도움이 필요하십니까? 당사의 고객 관리 팀은 질문 사항, 문제 또는 정보에 대해 도움을 드릴 수 있도록 항상 대기하고 있습니다.',
  REMOVE: '제거',
  REMOVE_ITEM_FROM_CART_WARNING: '장바구니에서 <b>{0}</b>을(를) 제거하시겠습니까?',
  NO_ITEM_IN_THE_CART: '장바구니에 항목이 없습니다.',
  CONTINUE_SHOPPING: '계속 쇼핑하기',
  TOTAL_TAXES: '총 세금',
  UC_SOLUTIONS: 'UC 솔루션',
  UNIFIED_COMMUNICATIONS: '통합 커뮤니케이션',
  ADD_ONS: '추가 기능',
  SYSTEM_ADDONS: '시스템 추가 기능',
  ADD_DEVICES: '장치 추가',
  SELECT_UPTO_DEVICES: '<b>{1}</b>에 대해 최대 (<b>{0}</b>)대의 장치 선택',
  DONE: '완료됨',
  SELECT_DEVICES: '장치 선택',
  EDIT_DEVICE_SELECTION: '장치 편집',
  ESSENTIAL_USERS: 'Essential 사용자',
  BUSINESS_USERS: 'Business 사용자',
  POWER_USERS: '고급 사용자',
  N_A: 'N/A'
}
