export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'Não é possível descriptografar os dados do sistema de contas',
  PHONE_TYPES: 'Tipos de telefone',
  IMAGINE_A_BETTER_WAY: 'Imagine uma melhor forma',
  OF_DOING_THINGS: 'de fazer as coisas.',
  GET_STARTED: 'Iniciar',
  PURCHASE: 'Comprar',
  DOWNLOADS_AND_EXTENSIONS: 'Downloads e extensões',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: 'Aproveite o máximo dos seus produtos Zang com esses complementos imperdíveis!',
  ALL: 'Todos',
  REFERRAL_AGENT: 'Agente de referência',
  SALES_AGENT: 'Agente de vendas',
  CART: 'Carrinho',
  PARTNER_PROGRAMS: 'Programas de parceiros',
  HOME: 'Início',
  MANAGE_CREDIT_CARDS: 'Gerenciar cartões de crédito',
  MANAGE_PAYMENT_OPTIONS: 'Gerenciar opções de pagamento',
  MANAGE_BILLING_ACCOUNT: 'Gerenciar conta de cobrança',
  LIMIT: "Limite",
  MY_PROFILE: 'Meu perfil',
  MY_SETTINGS: 'Minhas configurações',
  MY_PARTNER_PORTAL: 'Meu portal de parceiro',
  CLEAR_ZANG_OFFICE: 'Limpar Zang Office',
  CLEAR_ZANG_SPACES: 'Limpar Zang Spaces',
  FEATURE_BREAKDOWN: 'Divisão de funcionalidade',
  PLAN_BREAKDOWN: 'Divisão de plano', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'O telefone empresarial que você precisa a um preço que adora',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Imagine o que você pode fazer no Zang Spaces',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'Será aplicado um desconto de 50% ao seu valor total depois de finalizar a compra',
  HURRICANE_HARVEY_MESSAGE: 'A Avaya e o Zang gostariam de ajudar as empresas afetadas pelo furacão Harvey e possivelmente pelo Irma. Qualquer empresa afetada nos estados do TX, LA, FL, AL, GA, NC, SC, TN e MS pode receber <b>imediatamente 3 meses do Zang Office</b> e <b>Zang Spaces GRATUITAMENTE</b>.',
  LEARN_MORE: 'Saiba mais',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'O AVAYA VANTAGE™ ESTÁ DISPONÍVEL',
  NEW: 'NOVO!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Experimente o melhor do Zang Office com esse telefone de colaboração por voz, vídeo e bate-papo que é transparente e fácil de usar!',
  LOG_IN: 'Login',
  SIGN_UP: 'Cadastrar-se',
  SIGN_OUT: 'Sair',
  SIGN_IN: 'Entrar', //login to the system, connect
  ADMINISTRATION: 'Administração',
  PRODUCTS: 'Produtos',
  ORDERS: 'Pedidos',
  PAGES: 'Páginas',
  CUSTOMERS: 'Clientes',
  USERS: 'Usuários',
  PLANS: 'Planos',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'Cdrs',
  CDR_CHECKS: 'Verificações Cdr',
  PARTNERS: 'Parceiros',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'Parece que você já comprou o Zang Office. Não é possível fazer mais pedidos do Zang Office.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'Parece que você já comprou o Avaya Cloud para essa empresa. Selecione uma empresa diferente.',
  PARTNER_CONNECTIONS: 'Conexões dos parceiros',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'Houve um erro ao fazer o seu pedido. Entre em contato com o suporte do Zang ({SUPPORT_EMAIL}) para mais informações.',
  APPLICATION_GENERAL_FATAL_ERROR: 'Houve um erro ao enviar o seu pedido. Entre em contato com o suporte do Zang ({SUPPORT_EMAIL}) para mais informações.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Selecione ao menos um tipo de usuário para continuar.',
  BACK: 'Voltar',
  SAVE_CHANGES: 'Salvar alterações',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: 'Realmente deseja continuar?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'Você tem {PLACEHOLDER} de crédito para gastar na compra de qualquer dispositivo. Esse crédito será perdido após o envio de seu pedido.',
  JUST_A_REMINDER: 'Apenas um lembrete',
  LAST_CHANCE: 'ÚLTIMA CHANCE',
  IM_GOOD_PLACE_MY_ORDER: 'Estou certo disso - fazer meu pedido',
  BUY_MORE_DEVICES: 'Comprar mais dispositivos',
  YES_PLACE_MY_ORDER: 'Sim, fazer meu pedido',
  NO_THANKS: 'Não, obrigado!',
  YES: 'Sim',
  ABOUT_US: 'Sobre nós',
  NEWS_AND_PRESS: 'Notícias e imprensa',
  CARREERS: 'Carreiras',
  CONTACT_US: 'Entre em contato conosco',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Obrigado por comprar conosco. Os detalhes do seu pedido estão indicados abaixo.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: 'Entre em contato com <a href="mailto:{EMAIL}">{EMAIL}</a> para obter essa informação',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'Nossas equipes de Sucesso do Cliente e Suporte Técnico entrarão em contato com você quando seu sistema estiver pronto. <br/><br/><b>Observe que a configuração de seu sistema pode levar até 1 hora.</b>',
  QUESTION_CUSTOMER_SERVICE: 'Envie um e-mail para <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a> caso tenha qualquer dúvida!',
  BLOG: 'Blog',
  FAQS: 'Perguntas frequentes',
  DOCUMENTATION: 'Documentação',
  TERMS_OF_SERVICE: 'Termos de serviço',
  HELP: 'Ajuda',
  PRIVACY_STATEMENT: 'Declaração de privacidade',
  GENERAL_PRIVACY_STATEMENT: 'Declaração geral de privacidade',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: 'Termos gerais de serviço – Avaya Cloud Solutions',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. Todos os direitos reservados.',
  PROCESSING: 'Processando',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Tenha paciência. O processo pode levar algum tempo',
  OPEN_IN_A_NEW_TAB: 'Abrir numa nova aba',
  GOT_IT: 'Entendido!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' Esta ação terá os seguintes resultados:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Excluir a assinatura mensal para este plano',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Desabilitar qualquer conta em quaisquer sistemas terceiros',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Alterar o status deste plano para DESABILITADO',
  LAST_ACTION_STEPS: 'Passos da última ação',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'Os complementos são adquiridos por meio do portal de administração do Zang Office após a criação da conta.',
  TYPE: 'Tipo',
  ADMIN: 'Administrador',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'Esse usuário será configurado como o contato principal/de faturamento para a conta corporativa. É possível alterá-lo a qualquer momento por meio do portal de administração do Zang Office.',
  DESCRIPTION: 'Descrição',
  SUCCESS: 'Sucesso',
  REQUEST_CANCELATION: 'Solicitar cancelamento',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Isso não é bom! Sinto muito em ouvir que você deseja cancelar.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Preencha o formulário abaixo para começar o processo de cancelamento. Um membro de nosso departamento de atendimento ao cliente revisará e acompanhará sua solicitação em 1 a 2 dias úteis para que esse processo ocorra perfeitamente.',
  YOUR_NAME: 'Seu nome',
  COMPANY: 'Empresa',
  SERVICE: 'Serviço',
  REASON_FOR_CANCELING: 'Motivo do cancelamento',
  SUBMIT: 'Enviar',
  EXIT: 'Sair',
  REQUEST_SUBMITTED: 'Solicitação enviada!',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Um membro de nosso departamento de atendimento ao cliente revisará e acompanhará sua solicitação em 1 a 2 dias úteis para que esse processo ocorra perfeitamente.',
  DATE: 'Data',
  PRODUCT: 'Produto',
  USER: 'Usuário',
  STATUS: 'Status',
  ACTIONS: 'Ações',
  VIEW_DETAILS: 'Ver detalhes',
  DISABLE: 'Desativar',
  ENABLE: 'Ativar',
  CANCEL: 'Cancelar',
  PLAN_DETAILS: 'Planejar detalhes',
  SUMMARY: 'Resumo',
  QUANTITIES: 'Quantidades',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*O total inclui os preços de recursos do plano',
  TOTAL: 'Total',
  BILLED: 'Faturado',
  PLAN_INFORMATION: 'Informações do plano',
  UPDATE_PLAN: 'Atualizar plano',
  ADMIN_ACTIONS: 'Ações do administrador',
  NAME_ON_CREDIT_CARD: 'Nome no cartão de crédito',
  CREDIT_CARD_BRAND: 'Bandeira do cartão de crédito',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: 'Número do cartão de crédito',
  EXPIRATION: 'Validade',
  MONTH: 'Mês',
  YEAR: 'Ano',
  SECURITY_CODE: 'Código de segurança',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'O código atrás do seu cartão de crédito',
  BACK_TO_CHECKOUT: 'Voltar para finalizar compra',
  NO_ORDERS_FOUND: 'Nenhum pedido encontrado',
  ADD: 'Adicionar',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Use o formulário acima para adicionar um novo cartão de crédito. Certifique-se de preencher todos os campos',
  NUMBER: 'Número',
  EXPIRES: 'Expira',
  DELETE: 'Excluir',
  ITEM_DETAILS: 'Detalhes do item',
  FEE: 'Taxa',
  ITEMS: 'Itens',
  SEARCH_BY_CONFIRMATION: 'Pesquisar por confirmação',
  CONFIRMATION: 'Confirmação',
  CHECKOUT_STATUS: 'Status de finalização de compra',
  ORDER_STATUS_PROCESS: 'Processo do status do pedido',
  CREATED_ON: 'Criado em',
  ORDER_SUMMARY: 'Resumo do pedido',
  APPROVED: 'Aprovado', //example: partner application approved
  REJECTED: 'Rejeitado', //example: partner application rejected
  APPROVE: 'Aprovar', //example: partner application approved
  REJECT: 'Rejeitar', //example: partner application rejected
  PENDING: 'Pendente', //example: partner application pending
  EDIT: 'Editar',
  ONE_TIME_FEE: 'Taxa única',
  SUB_TOTAL: 'Subtotal',
  TAXES: 'Impostos',
  CHANGES: 'Alterações',
  CREATE_A_QUOTE: 'Criar uma cotação',
  EXTRA_INFORMATION: 'Informações extras',
  THANK_YOU_FOR_YOUR_ORDER: 'Obrigado pelo seu pedido',
  ORDER_CONFIRMATION: 'Confirmação de pedido',
  INVALID_ORDER: 'Pedido inválido',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'Não se preocupe, também enviamos isso por e-mail para você :)',
  HELLO: 'Olá',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Obrigado por comprar conosco. Vamos enviar uma confirmação quando os seus itens tiverem sido enviados. Os detalhes do seu pedido estão indicados abaixo.',
  ACCOUNT_INFORMATION: 'Informações da conta',
  BILLING_INFORMATION: 'Informações de cobrança',
  SHIPPING_INFORMATION: 'Informações de envio',
  NAME: 'Nome',
  EMAIL: 'E-mail',
  SEARCH: 'Pesquisar',
  CLEAR: 'Limpar',
  PARTNER: 'Parceiro',
  NO_PARTNERS_FOUND: 'Nenhum parceiro encontrado',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'Uma conexão do parceiro é criada quando um cliente chega na loja a partir do link pessoal de um parceiro.',
  CUSTOMER: 'Cliente',
  AGENT: 'Agente',
  NO_PARTNER_CONNECTIONS_FOUND: 'Nenhuma conexão do parceiro encontrada',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'Li e concordo com a',
  ZANG_PRIVACY_STATEMENT: 'Declaração de privacidade do Zang',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'Termos de Serviço do Programa de Agente',
  SUBMIT_APPLICATION: 'Enviar aplicativo',
  SUBMITTING: 'Enviando',
  SUBMITTING_YOUR_APPLICATION: 'Enviando o seu aplicativo',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'Todas as informações bancárias e de conta são mantidas privadas e seguras sob os nossos termos e condições.',
  BANK_NAME: 'Nome do banco',
  ADDRESS: 'Endereço',
  COUNTRY: 'País',
  SELECT_ONE: '- Selecione um -',
  STATE_PROVINCE: 'Estado/província',
  CITY: 'Cidade',
  ZIP_POSTAL_CODE: 'CEP/Código postal',
  ACCOUNT_NUMBER: 'Número da conta',
  BANK_NUMBER: 'Número do banco',
  TRANSIT_NUMBER: 'Número de trânsito',
  SWIFT_CODE: 'Código Swift',
  TAX_REGISTRATION_NUMBER: 'Número de registro fiscal',
  SAVE_BANK_INFORMATION: 'Salvar informações bancárias',
  SAVING_BANK_INFORMATION: 'Salvando informações bancárias',
  NO_CUSTOMERS_FOUND: 'Nenhum cliente encontrado',
  YOU_ARE_A: 'Você é um ',
  A_DISCOUNT_OF: 'Um desconto de',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'será aplicado à sua quantidade total depois de finalizar a compra.',
  FIRST_NAME: 'Nome',
  LAST_NAME: 'Sobrenome',
  COMPANY_NAME: 'Nome da empresa',
  LEGAL_COMPANY_NAME: 'Nome da empresa jurídica',
  PHONE_NUMBER: 'Número de telefone',
  WEBSITE: 'Site',
  OPERATIONAL_ADDRESS: 'Endereço operacional',
  SAME_AS_ORGANIZATION_ADDRESS: 'Mesmo endereço da organização',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: 'Você já é parceiro da Avaya?',
  NO: 'Não',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Se for, insira o seu ID de parceiro da Avaya',
  MY_PARTNER_PORTAL: 'Meu portal de parceiro',
  THANK_YOU_FOR_APPLYING: 'obrigado por se inscrever!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'Mais um passo e você está pronto! Para concluir o pedido do agente de vendas, siga o link abaixo e responda a todas as perguntas.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' Caso contrário, forneça ',
  PLEASE_GIVE: 'Forneça',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'Caso seja um parceiro Avaya existente, NÃO siga o link abaixo. <br />Atualmente estamos avaliando seu ID de parceiro e entraremos em contato em breve.',
  BUSINESS: 'dias',
  DAYS: 'úteis',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'para que a gerência sênior revise o seu pedido.<br /> Enquanto isso, todas as perguntas podem ser enviadas para',
  COMPLETE_MY_APPLICATION: 'Concluir meu pedido',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'Analisamos o seu pedido. Infelizmente, neste momento, determinamos que não é adequado ao nosso programa. Provavelmente não é nada grave, mas não podemos seguir adiante com nossa parceria enquanto isso não for resolvido. Sabemos que isso pode ser frustrante. Saiba que vamos analisar as razões e entraremos em contato assim que possível quando tivermos mais informações. Enquanto isso, sinta-se à vontade para entrar em contato',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'com quaisquer perguntas em relação a este processo.',
  CONGRATULATIONS: 'parabéns',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: 'Agora você é um agente oficial do Zang!',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Comece compartilhando o seu link pessoal com todos os seus contatos',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'e ajude-os a experimentar uma melhor forma de fazer as coisas.',
  CHANGE_STATUS: 'Alterar status',
  AGENT_DETAILS: 'Detalhes do agente',
  BANK_INFORMATION: 'Informações do banco',
  THIS_ORDER_WAS_PLACED_BY_A: 'Este pedido foi feito por um',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'foi aplicado à quantidade total',
  REFERRALS: 'Referências',
  SALES: 'Vendas',
  FOUND: 'Encontrado',
  HOW_IT_WORKS: 'Como funciona',
  WHAT_YOU_GET: 'O que você recebe',
  SUPPORT: 'Suporte',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'Que programa é melhor para mim?',
  WHY_JOIN: 'Por que se juntar?',
  QUOTE: 'Cotação',
  PRINT_THIS_QUOTE: 'Imprimir esta cotação',
  CLOSE_THIS_WINDOW: 'Fechar esta janela',
  SEARCH_BY_PLAN: 'Pesquisar por plano',
  ACCESS_LEVEL: 'Nível de acesso',
  DISPLAY_NAME: 'Nome de exibição',
  INDUSTRY: 'Indústria',
  COMPANY_INDUSTRY: 'Setor da empresa',
  CONTACT_PHONE_NUMBER: 'Número de telefone',
  EMAIL_ADDRESS: 'Endereço de e-mail',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Sim, envie-me um e-mail com notícias do Zang, aplicativos, acordos e eventos especiais!',
  INFORMATION: 'Informações',
  ORDER_HISTORY: 'Histórico do pedido',
  FILTER: 'Filtrar',
  ACCOUNT: 'Conta',
  AMOUNT_CHARGED: 'Quantia cobrada',
  DETAILS: 'Detalhes',
  NO_RECORDS_FOUND: 'Nenhum registro encontrado',
  CALL_LOGS: 'Logs de chamada',
  EXPORT: 'Exportar',
  CALLER_NAME: 'Nome do chamador',
  DIALED_NUMBER: 'Número discado',
  DURATION_SEC: 'Duração (Seg)',
  COST: 'Custo',
  PAYMENT_METHOD: 'Método de pagamento',
  PURCHASE_ORDER: 'Ordem de compra',
  PURCHASE_ORDERS: 'Ordens de compra',
  CREDIT_CARD: 'Cartão de crédito',
  SHIPPING_ADDRESS: 'Endereço de envio',
  SAME_AS_BILLING_ADDRESS: 'Mesmo endereço de cobrança',
  SAME_AS_SHIPPING_ADDRESS: 'Igual ao endereço para entrega',
  OTHER: 'Outros',
  SHIPPING_OPTIONS: 'Opções de envio',
  FREE_SHIPPING: 'Envio GRÁTIS',
  ADDITIONAL_NOTES: 'Notas adicionais',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'Li e concordo com o seguinte:',
  EMERGENCY_911_SERVICE_NOTICE: 'Aviso de serviço de Emergência 911',
  PLACE_MY_ORDER: 'Fazer meu pedido',
  CLEAR_MY_ORDER: 'Limpar meu pedido',
  PLACING_YOUR_ORDER: 'Fazendo seu pedido',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'Tenha paciência. Este processo pode levar até 1 minuto.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'Esse processo pode levar algum tempo. Obrigado por sua paciência. Para garantir que seu pedido não seja interrompido, evite fechar esta janela do navegador ou clicar nos botões voltar ou atualizar.',
  YOUR_NEW_NUMBER: 'Seu novo número',
  NO_NUMBER_SELECTED: 'Nenhum número selecionado',
  WELL_THAT_WAS_EASY: 'Bem, isso foi fácil!',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'Mais alguns passos e você estará pronto :)',
  NEXT: 'Próximo',
  TITLE: 'Título',
  SUB_TITLE: 'Subtítulo',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Pesquisar por código de área... (apenas EUA e Canadá)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: 'Insira o código de área... (apenas EUA)',
  SELECT_A_PREFIX: 'Selecionar um prefixo',
  PICK_THIS_NUMBER: 'Escolher este número',
  DEVICES: 'Dispositivos',
  BILLING: 'Cobrança',
  CHANGE: 'Alterar',
  USER_INFO: 'Informações do usuário',
  USE_MY_INFORMATION: 'Usar minhas informações',
  SELECT_YOUR_DEVICES: 'Selecione seus dispositivos',
  MONTHLY_FEE: 'Taxa mensal',
  ANNUAL_FEE: 'Taxa anual',
  TWO_YEAR_FEE: 'Taxa bianual',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'Cada plano do Zang Office exige pelo menos um usuário Padrão OU Avançado.',
  CHECKOUT: 'Finalizar compra',
  MINE: 'Meu',
  REMOVE_THIS_USER: 'Remover este usuário',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Selecione um dispositivo para este usuário',
  ADD_ANOTHER: 'Adicionar outro',
  GET_STARTED_WITH_ZANG_OFFICE: 'Começar a usar o Zang Office',
  BUNDLE: 'pacote',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Cadastre-se para um ano e receba',
  OFF: 'Desconto',
  EACH_USER: 'cada usuário',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'Para ajustar as suas quantidades do usuário, deve limpar o seu pedido ou continuar no passo \'dispositivos\'.',
  EVERY_TWO_YEARS: 'A cada 2 anos',
  YOU_VE_SAVED: 'Você salvou',
  INCLUDED: 'Incluído',
  ADDONS: 'Complementos',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Personalize cada usuário como quiser!',
  UNITS_PER: 'Unidades por',
  TALK_ANYWERE_ANYTIME: 'Fale em qualquer lugar, a qualquer momento!',
  DOWNLOAD_FOR_MAC: 'Download para MAC',
  DOWNLOAD_FOR_WINDOWS: 'Download para Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Obrigado por comprar o Zang Office! Veja o seu pedido aqui!',
  CONTINUE_WITH_YOUR_PURCHASE: 'Continue com a sua compra!',
  GET_STARTED_TODAY: 'Comece hoje!',
  FEATURES: 'Recursos',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Vamos detalhar para você!',
  BASIC: 'Básico',
  STANDARD: 'Padrão',
  POWER: 'Avançado',
  RATE_MIN_STARTING_FROM: 'Taxa/min, a partir de*:',
  RATE_MIN_STARTING_FROM_1: 'Taxa/min, a partir de',
  LONG_DISTANCE: 'Internacional de longa distância',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'Taxas internacionais de longa distância',
  COMMON_DESTINATIONS: 'Destinos comuns',
  BEST_DEAL: 'melhor oferta',
  PER_ACTIVE_USER_PER_MONTH: 'Por usuário ativo, por mês.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'de acordo com o contrato anual',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'Cobrado de acordo com o plano selecionado.',
  MONTHLY: 'Mensalmente',
  ANNUALLY: 'Anualmente',
  BILLED_ANNUALY: 'Cobrado anualmente',
  BILLED_EVERY_TWO_YEARS: 'Cobrado a cada 2 anos',
  CONFIGURE_YOUR_ADDONS: 'Configure os seus complementos',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Selecione uma quantidade para cada um dos complementos disponíveis.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'A quantidade máxima para este complemento é',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'Este complemento só está disponível para',
  BILLING_AND_SHIPPING: 'Cobrança e envio',
  BILLING: 'Cobrança',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'Este será o seu nome da conta do Zang Office.',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'Esse será o nome de sua conta Avaya Cloud.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Se você tiver escolhido usar o seu número existente ou um número grátis como o seu número do Zang Office, tentaremos encontrar um número local com o complemento usado neste campo.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Tudo acontece no Spaces',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'A ferramenta de colaboração da equipe baseada na nuvem que você sempre quis, mas nunca encontrou.',
  YOUR_CURRENT_PURCHASES: 'Suas compras atuais',
  PURCHASED_ON: 'Comprado em',
  PLAN_NUMBER: 'Número do plano',
  UPDATE: 'Atualizar',
  UPDATED: 'Atualizado em',
  OR: 'ou',
  MAKE_A_NEW_PURCHASE: 'Fazer uma nova compra',
  FEATURES_AND_ADDONS: 'Recursos e complementos',
  FREE: 'FREE',
  PLUS: 'PLUS',
  BUSINESS: 'POWER',
  VIEW: 'Visualizar',
  TEAM: 'Equipe',
  LETS_SETUP_YOUR_TEAM: 'Vamos organizar a sua Equipe',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Simplesmente selecione o tipo de equipe que deseja criar e configure o seu ambiente particular.',
  COMPANY_TYPE: 'Tipo de empresa',
  DOMAIN: 'Domínio',
  NO_TEAM_IS_SETUP_YET: 'Nenhuma equipe está configurada ainda',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'Não configure uma equipe para mim',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Compre Zang Spaces só para você.',
  CHOOSE_AN_EXISTING_COMPANY: 'Escolha uma empresa existente',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Selecione uma das empresas que administra atualmente.',
  CREATE_A_NEW_TEAM: 'Criar uma nova equipe',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Insira um nome de equipe e domínio.',
  NO_DOMAIN_IS_CONFIGURED: 'Nenhum domínio está configurado.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Forneça um nome de domínio (ex: \'zang.io\')',
  CHECK: 'Marcar',
  TEAM_DOMAIN: 'Domínio da equipe (ex: \'zang.io\')',
  TEAM_NAME: 'Nome da equipe (ex: \'Zang\')',
  OK: 'OK',
  ZANG_SPACES_ADMIN_CONSOLE: 'Console de administração do Zang Spaces',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'Você pode alterar os valores abaixo para atualizar o seu plano',
  CHARGABLE_USERS: 'Usuários que podem ser cobrados',
  TOTAL_USERS: 'Total de usuários',
  CURRENT_PRICE: 'Preço atual',
  SAVE: 'Salvar',
  SAVE_CHANGES_AND_UPDATE_PLAN: 'Salvar alterações e atualizar o plano?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Selecione pelo menos um tipo de usuário para continuar',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Você está comprando Zang Spaces para',
  BUY_NOW: 'Compre agora',
  SELECT: "Selecionar",
  UP_TO: 'Até',
  NO_PURCHASE_REQUIRED: 'nenhuma compra necessária',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'Nenhuma cobrança ou comprometimento antecipado.',
  SIGN_UP_FOR_FREE: 'Cadastre-se GRÁTIS!',
  ONE_YEAR_PLAN: 'Plano de 1 ano',
  MONTHLY_PLAN: 'Plano mensal',
  TWO_YEAR_PLAN: 'Plano de 2 anos',
  MONTHS: 'Meses',
  ZANG_OFFICE_ACCOUNT_NAME: 'Nome da conta do Zang Office',
  ZANG_OFFICE_PLAN_NUMBER: 'Número do plano do Zang Office',
  TEMPORARY_NUMBER: 'Número temporário',
  START_SETTING_UP_ZANG_OFFICE: 'Comece a configurar o Zang Office!',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'Se você estiver transferindo um número existente para a sua solução Zang Office, precisa enviar um e-mail para zosupport@zang.io com o Formulário de Autorização LNP e uma cópia da sua conta de telefone mais recente. Se você estiver transferindo um número grátis, também envie por e-mail o formulário RODAA. Observe que pode levar até 10 dias úteis para completar as transferências.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'Houve um erro ao comprar/ativar os números escolhidos do Zang Office. Clique em \'Iniciar configuração do Zang Office\' to activate/buy your numbers manually. In case you\'ve chosen to use your existing number, the porting process will not be affected.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'Obs.: Caso esteja transferindo um número existente para sua conta Zang Office, será necessário preencher e enviar por e-mail este <a href="{LNP_FORM_LINK}" target="blank">Formulário de autorização LNP</a> e uma cópia de sua conta de telefone mais recente. Caso esteja transferindo um número de chamada gratuita, preencha também este <a href="{RODAA_LINK}" target="blank">formulário RODAA</a>. Envie toda a documentação aplicável para <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. O processo de transferência de número telefônico por levar até 10 dias úteis.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Observe que o processo de transferência de número telefônico por levar até 10 dias úteis. Nesse período, vincularemos um número temporário para você usar em sua conta.',
  PLAN_STATUS: 'Status do plano',
  PLAN_ID: 'ID do plano',
  SUBSCRIPTION_ID: 'ID da assinatura',
  STRIPE_PLAN_ID: 'ID do plano da faixa',
  ACCOUNT_ID: 'ID da conta',
  START_SETTING_UP_ZANG_SPACES: 'Iniciar configuração do Zang Office',
  COMPANY_DOMAIN: 'Domínio da empresa',
  THIS_FIELD_IS_REQUIRED: 'Este campo é obrigatório.',
  PLEASE_ANSWER_THIS_QUESTION: 'Responda a esta pergunta.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Insira o seu ID de Parceiro da Avaya.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Leia e concorde com a Declaração de Privacidade para continuar.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Leia e concorde com os Termos de Serviço do Programa de Agente para continuar.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'Este ID de Parceiro da Avaya já está sendo usado.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'Este número de registro fiscal já está sendo usado.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'Este não é um ID de Parceiro da Avaya válido.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'O valor deve ser um número positivo',
  ORDER_COMPLETE: 'Pedido concluído!',
  PLEASE_TRY_AGAIN: 'Tente novamente',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Selecione pelo menos um valor positivo',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'A atualização ainda está em andamento. Tente novamente depois.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'Você não pode ter mais de um usuário para uma licença pessoal. Para atualizar ou diminuir o seu plano, altere os valores, conforme o caso.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'Você não tem acesso a esta conta.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Seu plano atual não permite que você diminua os usuários menos que a sua quantidade original. Se isso for algo que você gostaria de ajustar, entre em contato conosco em customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'Ocorreu um erro ao fazer o seu pedido. Certifique-se de que todos os campos tenham valores válidos e, se o erro continuar, entre em contato com o suporte do Zang para mais informações.',

  USE_EXISTING_NUMBER: 'Usar número existente',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Selecione para usar o seu número existente com o seu plano',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Selecione previamente um número GRÁTIS',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Selecione para adicionar o seu próprio número grátis para o seu plano',
  FIND_A_LOCAL_NUMBER: 'Encontrar um número local',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Selecione a partir de uma lista de números locais na sua área para adicionar ao seu plano',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: 'Selecione para adicionar um número local ao seu plano',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: 'Usar código de área para pesquisar por números de telefone disponíveis',
  SEARCH_AVAILABLE_PHONE_NUMBERS: 'Pesquisar números de telefone disponíveis',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: 'Digite o número existente que planeja transferir',


  ZANG_OFFICE_PHONE_APP: 'Aplicativo de telefone do Zang Office',
  ZANG_OFFICE_SOFTPHONE: 'Softphone do Zang Office',
  ZANG_OFFICE_PHONE_APPLICATION: 'Aplicativo de telefone do Zang Office',
  SOFTPHONE_MARKETING_DESCRIPTION: 'O softphone do Zang Office inclui todos os recursos de comunicação que você espera diretamente em seu desktop ou dispositivo móvel. Aproveite todos os grandes recursos do Zang Office sem ultrapassar o orçamento, pois o softphone Zang Office é incluído gratuitamente com a sua assinatura do Zang Office!',
  E129_SIP_DESK_PHONE: 'Telefone de mesa E129 SIP',
  STANDARD_PHONE: 'Telefone padrão',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'O telefone de mesa Avaya E129 SIP contém todos os recursos essenciais de tratamento de chamadas que você espera num telefone SIP acessível, porém altamente funcional. O telefone de mesa Avaya E129 permite a transferência, mudo, encaminhamento e chamadas em espera, assim como inicia conferências ad-hoc pressionando um único botão. O alto-falante totalmente bidirecional permite conversas com as mãos livres, e a sua porta de energia por ethernet proporciona conexão conveniente à rede. O telefone de mesa Avaya E129 SIP tem as capacidades de chamadas certas e é acessível e atraente. Adaptador de energia AC incluído.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Comunique-se usando um inovador e transparente dispositivo exclusivo para desktop. Use aplicativos de voz, bate-papo e colaboração por meio de conexões com um único toque. Sem interrupções ou pausas estranhas. Sem a necessidade de gerenciar vários dispositivos para a comunicação. Integre experiências personalizadas singulares em seus fluxos de trabalho e processos de negócios. Esse dispositivo avançado e personalizável oferece a vantagem de um telefone de mesa e a flexibilidade de uma plataforma de aplicativos.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'Telefone de conferência B179',
  CONFERENCE_PHONE: 'Telefone de conferência',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Mais adequado para salas de diretoria e grandes salas de conferência com grupos maiores que 10 pessoas, o telefone de conferência B179 ajuda a melhorar a produtividade dos funcionários e a colaboração. O telefone de conferência B179 é versátil e de alto desempenho que complementa as suas soluções e pode ser facilmente migrado à medida que o seu negócio cresce ou conforme as necessidades. Adaptador de energia AC incluído.',
  PLAN: 'Plano',
  REDIRECTING: 'Redirecionando',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Certifique-se de que todos os campos tenham valores válidos',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'Cada plano do Zang Office exige ao menos um tipo de usuário. Volte para o passo de seleção de dispositivos e mude a sua configuração.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Parece que você não selecionou nenhum número para a sua conta do Zang Office. Volte para o passo de seleção de número para selecionar um número.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'O nome da conta do Zang Office já está sendo usado. Tente outro',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'O número do Zang Office que você selecionou já foi comprado por outro cliente. Volte para o passo de seleção de número e selecione um número diferente.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Pague a cada mês, sem compromissos, e ganhe os <span class="text-400">30 PRIMEIROS DIAS DE GRAÇA</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'ou assine um plano anual e obtenha um preço melhor e um',
  FREE_PHONE: 'TELEFONE GRÁTIS',
  DISCOUNT: 'desconto',
  DISCOUNTED_PHONE: 'telefone descontado',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'desconto do valor total de suas compras de telefone',
  LIMITED_TIME_OFFER: 'Oferta por tempo limitado',
  PROMOTION: 'Promoção',
  ZANG_SPACES_PROMOTION: 'Promoção do Zang Spaces',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Continuar para a seleção de número do telefone',
  DURATION: 'Duração',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'Parabéns! Você tem um crédito de <strong>{amount}</strong> para colocar no total do seu pedido de dispositivos!',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'Todos os descontos aplicáveis serão ajustados dentro do seu resumo de pedido final.',
  SHIPPING_TYPE: 'Tipo de envio',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'Detalhes de rastreamento serão enviados quando os seus itens forem enviados a partir do nosso depósito',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Receba {amount} de crédito por usuário para a compra de qualquer dispositivo. Oferta por tempo limitado.',
  PARTNER_ORDERS: 'Pedidos de parceiros',
  COMMISSION: 'Comissão',

  ADDITIONAL_DEVICES: 'Dispositivos adicionais',
  NO_USER: 'Nenhum usuário',
  QUANTITY: 'Quantidade',
  BUY_DEVICES: 'Comprar dispositivos',
  DEVICE: 'Dispositivo',
  PRICE: 'Preço',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'Digite ao menos {chars} caracteres para pesquisar um Agente',
  NO_RESULTS_FOUND: 'Nenhum resultado encontrado',
  RESULTS_COULD_NOT_BE_LOADED: 'Não foi possível carregar os resultados',
  CLEAR_SELECTION: 'Limpar seleção',


  RESET_ALL_PURCHASES: 'Limpar todas as compras',
  LISTS: 'Listas',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Preencha o seu número de telefone antes de criar um orçamento.',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Preencha as informações de faturamento e envio antes de criar um orçamento',
  CALCULATING_TAXES_PLEASE_WAIT: 'Calculando impostos. Aguarde...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Há algo errado com o cartão de crédito escolhido.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Há algo errado com este cartão de crédito. Use outro',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'Houve um erro ao cobrar seu pedido. Escolha outro cartão de crédito',
  INVALID_CREDIT_CARD: 'Cartão de crédito inválido',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: 'O {address_type} não corresponde à informação de endereço de cartão de crédito',
  INVALID_SECURITY_CODE: 'Código de segurança inválido (cvc)',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Qualquer desconto e preço promocional foi aplicado a esta fatura',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'Não conseguimos criar sua conta de cliente. Tente novamente',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Não conseguimos criar seu cartão de crédito. Tente novamente',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Esse cartão de crédito está em uso para uma assinatura recorrente.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Erro ao definir esse cartão de crédito como padrão.',
  DEFAULT: 'Padrão',
  SET_DEFAULT: 'Definir como padrão',
  SALES_FORCE_QUOTE_ID: 'ID de cotação no Salesforce',
  SALES_FORCE_ORDER_ID: 'ID de pedido no Salesforce',
  SALES_FORCE_OPPORTUNITY_ID: 'ID de oportunidade no Salesforce',
  SALES_FORCE_CONTACT_ID: 'ID de contato no Salesforce',
  SALES_FORCE_CONTRACT_ID: 'ID de contrato no Salesforce',
  SALES_FORCE_ACCOUNT_ID: 'ID de conta no Salesforce',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Simplesmente \'Add a device\' and connect it with a user.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Basta \”Adicionar um dispositivo\” e conectá-lo a um usuário.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Comprar dispositivos adicionais para a sua conta Zang Office',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'Opa! Há algo de errado com seu pedido. Atualize a página, exclua seu pedido e comece novamente.',
  CREATE_A_NEW_COMPANY: 'Criar uma nova empresa',
  ADD_A_NEW_COMPANY: 'Adicionar uma nova empresa',
  PARTNER_DETAILS: 'Detalhes de parceiro',
  AGENTS: 'Agentes',
  PARTNER_PORTAL: 'Portal de parceiro',
  AGENT: 'Agente',
  AGENT_PORTAL: 'Portal do Agente',
  NO_AGENTS_FOUND: 'Nenhum Agente encontrado',
  NO_AGENT: 'Nenhum agente',
  RELATION: 'Relação',
  OWNER: 'Proprietário',
  ADMIN: 'Administrador',
  MANAGER: 'Gerente',
  EMPLOYEE: 'Funcionário',
  ACTIVE: 'Ativo',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: 'Um dos parceiros ao qual você está associado',
  APPLIED_ON: 'Aplicado em',
  JOIN_A_PARTNER: 'Juntar-se a um parceiro',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'Você está a um passo de juntar-se à <b>{COMPANY_NAME}</b>',
  JOIN_PLACEHOLDER_NOW: 'Juntar-se à {COMPANY_NAME} agora',
  UPDATE_AGENT_INFO: 'Atualizar informações de agente',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Comece a usar o Avaya Cloud Solutions <sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'Em associação com o Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'Uma solução simples, avançada e unificada de colaboração',
  IP_OFFICE_DONT_PAY_TILL: 'Só pague após 15 de abril de 2018!',
  LOGIN: 'Logon',
  DISCOVER: 'Descobrir',
  SOLUTIONS: 'Soluções',
  SERVICES: 'Serviços',
  INDUSTRIES: 'Setores',
  CASE_STUDIES: 'Estudos de caso',
  PROGRAMS_AND_PROMOTIONS: 'Programas e promoções',
  AUTHENTIC_AVAYA: 'Autenticamente Avaya',
  PERSPECTIVES: 'Perspectivas',
  AVAYA_CONNECTED_BLOG: 'Blog Avaya Connected',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: 'Localizador de soluções',
  INFO_FOR: 'Informações para',
  DEVELOPERS: 'Desenvolvedores',
  CHANNEL_PARTNERS: 'Parceiros de canal',
  TECHNOLOGY_PARTNERS: 'Parceiros de tecnologia',
  CONSULTANTS: 'Consultores',
  INVESTORS: 'Investidores',
  MEDIA_ANALYSTS: 'Analistas de mídia',
  SUPPLIERS: 'Fornecedores',
  CONNECT_WITH_US: 'Conecte-se a nós',
  FIND_A_CHANNEL_PARTNER: 'Localize um parceiro de canal',
  FIND_A_TECHNOLOGY_PARTNER: 'Localize um parceiro de tecnologia',
  EXECUTIVE_BRIEFING_CENTER: 'Central de briefing executivo',
  AVAYA_LEARNING_SERVICES: 'Avaya Learning Services',
  CONTACTS: 'Contatos',
  ABOUT_AVAYA: 'Sobre a Avaya',
  EVENTS: 'Eventos',
  NEWSROOM: 'Sala de imprensa',
  INVESTOR_RELATIONS: 'Relações com investidores',
  CORPORATE_RESPONSIBILITY: 'Responsabilidade corporativa',
  OUR_COMPANY: 'Nossa empresa',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'Grupo internacional de usuários Avaya (International Avaya Users Group, IAUG)',
  CAREERS: 'Carreiras',
  YOUR_PERSONAL_LINK: 'Seu link pessoal',
  SITEMAP: 'Mapa do site',
  TERMS_OF_USE: 'Termos de uso',
  PRIVACY: 'Privacidade',
  COOKIES: 'Cookies',
  AVAYA_INVOICE: 'Fatura',
  IP_OFFICE_ACCOUNT_NAME: 'Nome da conta Avaya Cloud',
  IP_OFFICE_PLAN_NUMBER: 'Número do plano Avaya Cloud',
  IP_OFFICE_PHONE_APPLICATION: 'Softphone do Avaya Cloud Solutions',
  IP_OFFICE_PHONE_DESCRIPTION: 'O softphone do Avaya Cloud Solutions permite que os usuários tenham acesso simplificado a todos os canais de comunicação a partir de uma só interface. O softphone do Avaya Cloud Solutions permite que você faça logon em seu Avaya Cloud Solutions e faça e receba chamadas de voz e vídeo a partir do ramal de seu telefone de mesa usando seu PC. O softphone é fornecido gratuitamente nas assinaturas Avaya Cloud Solutions Standard e Power.',
  PLAN_MONTH_1_MONTH_1: 'Plano mensal (sem crédito para dispositivo)',
  PLAN_YEAR_1_MONTH_1: 'Plano de 1 ano | Cobrança mensal',
  PLAN_YEAR_1_YEAR_1: 'Plano de 1 ano, parcela única',
  PLAN_YEAR_2_MONTH_1: 'Plano de 2 anos | Cobrança mensal',
  PLAN_YEAR_2_YEAR_1: 'Plano de 2 anos | Cobrança anual',
  PLAN_YEAR_2_YEAR_2: 'Plano de 2 anos, parcela única',
  PLAN_YEAR_3_MONTH_1: 'Plano de 3 anos | Cobrança mensal',
  PLAN_YEAR_3_YEAR_1: 'Plano de 3 anos | Cobrança anual',
  PLAN_YEAR_3_YEAR_3: 'Plano de 3 anos, parcela única',
  PLAN_YEAR_5_MONTH_1: 'Plano de 5 anos | Cobrança mensal',
  ACCORDING_TO_PLAN: 'De acordo com o plano',
  TOTAL_USER_PLAN_FEE: 'Tarifa total do plano de usuário',
  HEALTHCARE_DENY_MESSAGE: 'Obrigado por escolher o Avaya Cloud como sua solução. Infelizmente ainda não temos conformidade com HIPAA e consequentemente não podemos oferecer nosso serviço porque você está no setor de assistência médica. Notificaremos você assim que obtivermos nossa certificação, e esperamos que possamos atender sua empresa em tal ocasião! Entre em contato com <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a> caso tenha qualquer dúvida.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Selecione os dispositivos de sua Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Selecione o número de seu Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>-',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'Ajuste seus usuários e atribua dispositivos a eles.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Adicione um número de telefone que deseja usar para seu Avaya Cloud Solutions.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'Atribua um número de telefone à sua solução.',
  INVITE_A_NEW_AGENT: 'Convidar um novo Agente',
  I_WANT_TO_INVITE_A: 'Desejo convidar um',
  CONTACT_EMAIL: 'E-mail de contato',
  CONTACT_NAME: 'Nome do contato',
  COMPANY_NAME: 'Nome da empresa',
  CONTACT: 'Contato',
  COMPANY_IS_INCORPORATED: 'A empresa é incorporada',
  INDIVIDUAL: 'Indivíduo',
  INDIVIDUALS: 'Indivíduos',
  SEND_INVITATION_EMAIL: 'Enviar e-mail de convite',
  SENDING_INVITATION_EMAIL: 'Enviando e-mail de convite…',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: 'O convite foi enviado com êxito',
  ALL_FIELDS_ARE_REQUIRED: 'É necessário preencher todos os campos',
  PARTNER_NOT_FOUND: 'Parceiro não encontrado',
  SALE_AGENT_REGISTRATION: 'Inscrição de Agente de vendas',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: 'Basta preencher o formulário abaixo para se tornar um Agente de vendas da',
  VIEW: 'EXIBIR',
  COMPANIES: 'Empresas',
  ADD_A_PARTNER: 'Adicionar um parceiro',
  ADD_PARTNER: 'Adicionar parceiro',
  PARTNERS_PERSONAL_LINK: 'Link pessoal do parceiro',
  MASTER_SALES_AGENT: 'Agente de vendas principal',
  AVAYA_J129_LABEL: 'J129 IP Phone',
  AVAYA_J129_DESCRIPTION: 'Obtenha todos os seus recursos essenciais de atendimento de chamadas em um telefone SIP acessível e altamente funcional. Esse telefone fornece os principais recursos exigidos por usuários em empresas de qualquer tamanho. O telefone é compatível com duas apresentações de chamada com exibição de chamada em linha única. Adquira um telefone com recursos sólidos e que supera o que está disponível no mercado atualmente.',
  AVAYA_J169_LABEL: 'J169 IP Phone',
  AVAYA_J169_DESCRIPTION: 'Obtenha todos os seus recursos essenciais de atendimento de chamadas em um telefone SIP acessível e altamente funcional. Esse telefone fornece os principais recursos exigidos por usuários em empresas de qualquer tamanho. O telefone é compatível com duas apresentações de chamada com exibição de chamada em linha única. Adquira um telefone com recursos sólidos e que supera o que está disponível no mercado atualmente.',
  AVAYA_J179_LABEL: 'J179 IP Phone',
  AVAYA_J179_DESCRIPTION: 'Obtenha todos os seus recursos essenciais de atendimento de chamadas em um telefone SIP acessível e altamente funcional. Esse telefone fornece os principais recursos exigidos por usuários em empresas de qualquer tamanho. O telefone é compatível com duas apresentações de chamada com exibição de chamada em linha única. Adquira um telefone com recursos sólidos e que supera o que está disponível no mercado atualmente.',
  AVAYA_K175_LABEL: 'Avaya Vantage™ K175',
  AVAYA_K175_DESCRIPTION: 'Obtenha todos os seus recursos essenciais de atendimento de chamadas em um telefone SIP acessível e altamente funcional. Esse telefone fornece os principais recursos exigidos por usuários em empresas de qualquer tamanho. O telefone é compatível com duas apresentações de chamada com exibição de chamada em linha única. Adquira um telefone com recursos sólidos e que supera o que está disponível no mercado atualmente.',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: '9641GS IP deskphone',
  AVAYA_9641G_DESCRIPTION: 'O Avaya 9641GS é um deskphone premium multilinhas ideal para indivíduos que passam quantidades consideráveis de tempo no telefone e dependem de capacidades inteligentes para aprimorar as comunicações e a produtividade. O 9641GS tem uma tela colorida de 5 pol., uma tela maior sensível ao toque e qualidade de áudio de alta definição. Seu codec de áudio de banda ampla fornece desempenho excepcional de áudio em todas as interfaces de áudio, inclusive monofone, fone de ouvido e viva-voz.',
  AVAYA_9608G_LABEL: '9608G IP deskphone',
  AVAYA_9608G_DESCRIPTION: 'O deskphone 9608G é um telefone acessível e totalmente funcional com suporte integrado a gigabit e tela monocromática. A tecnologia Power over Ethernet simplifica a implantação e seu codec de áudio de banda ampla fornece desempenho excepcional de áudio. Projetado para empresas de pequeno a grande porte, esse deskphone inclui acesso a oito linhas e rótulos gráficos que podem ser administrados de maneira central.',
  AVAYA_9611G_LABEL: '9611G IP deskphone',
  AVAYA_9611G_DESCRIPTION: 'O modelo 9611G inclui gigabit integrado e uma interface USB. Ele tem uma tela colorida de 3,5 pol. com retroiluminação branca e rótulos gráficos que podem ser administrados de maneira central. A tecnologia Power over Ethernet simplifica a implantação e seu codec de áudio de banda ampla fornece desempenho excepcional de áudio.',
  AVAYA_PHONE_B179_LABEL: 'B179 SIP Conference Phone',
  AVAYA_PHONE_B179_DESCRIPTION: 'Testado pela Tolly, esse telefone baseado em SIP para conferências é flexível e fornece som claro e natural por meio do OmniSound 2.0, a tecnologia patenteada de áudio de banda ampla da Avaya. O telefone está repleto de recursos inteligentes para maior eficiência nas chamadas em conferência. Use o guia de conferência para chamar grupos pré-programados. Importe e exporte detalhes de contato convenientemente por meio da interface Web. Crie sua própria lista de contatos com o recurso perfil de usuário pessoal.',
  HAVE_LARGE_NUMBERS_OF_USERS: 'Tem um grande número de usuários?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'Analise nosso detalhamento de desconto por volume.',
  DEVICE_FEE: 'Taxa por dispositivo',
  UP_TO_DEVICE_CREDITE_PER_USER: 'Até {$} de crédito de dispositivo por usuário',
  PROMOTION_REMAINING_DETAIL_INFO: 'Você ainda tem <b>{0}</b> em crédito promocional de dispositivo para gastar. Observe que qualquer crédito remanescente será invalidado após sua compra e não será transferido para sua conta para ser usado em compras futuras.',
  VIEW_USER_FEATURES: 'Exibir recursos de usuário',
  FREE_DEVICES_PER_USER_INFO: '{0} (até {1} de crédito de dispositivo por usuário)',
  VALUE_OF_DEVICE_CREDIT: '{0} usuários = {0} em total de crédito de dispositivos',
  PROMOTION_DELAYED_BILLING_INFO: 'Promoção: você receberá recibos detalhados e seu cartão de crédito será cobrado com qualquer saldo pendente quando seu ciclo de cobrança começar oficialmente.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'Selecione um agente para concluir o pedido',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: 'Informe um nome de domínio válido (exemplo.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Seu sistema Avaya Cloud Solution está pronto!',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Agora seu sistema Avaya Cloud Solution está configurado!',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Número de telefone do Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Nome de domínio SIP do Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_ID: 'ID de domínio SIP do Avaya Cloud Solutions',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Seu sistema Avaya Cloud Solution está sendo configurado.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'Agradecemos seu pedido. No momento estamos configurando seu sistema Avaya Cloud Solutions e entraremos em contato assim que o processo estiver concluído. <br /> Caso tenha qualquer dúvida, entre em contato com o suporte do Avaya Cloud Solutions em {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'A provisão dessa conta falhou',
  ERROR_CODE: 'Código de erro',
  ERROR_MESSAGE: 'Mensagem de erro',
  ADMIN_PORTAL_LINK: 'Link para o portal do administrador',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Senha de usuário padrão do Avaya Cloud Solutions',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Número de telefone temporário do Avaya Cloud Solutions',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'Ramais de usuário básico',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Ramais de usuário padrão',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'Ramais de usuário Power',
  IP_OFFICE_DEFAULT_USER_PIN: 'PIN de usuário padrão',
  IP_OFFICE_SAME_AS_PIN: 'Igual ao ramal (p. ex.: 200)',
  IP_OFFICE_ORDERID: 'ID do pedido do Avaya Cloud Solutions',
  IP_OFFICE_HOST_NAME: 'Nome do host de seu Avaya Cloud Solutions',
  IP_OFFICE_IP_ADDRESS: 'Endereço IP de seu Avaya Cloud Solutions',
  IP_OFFICE_SUBSCRIPTIONID: 'ID da assinatura do Avaya Cloud Solutions',
  CALCULATING: 'calculando…',
  RESET_ALL_PARTNERS: 'Excluir dados de parceiro',
  ERROR_GETTING_AGENTS: 'Erro ao verificar os agentes. Tente novamente',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Já existe um agente com esse e-mail em sua equipe',
  AUTO_APPROVE_ACTIVATE_AGENT: 'Aprovar/ativar agente automaticamente',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'Já existe uma empresa com esse e-mail em sua equipe',
  MASTER_SALES_AGENT_PORTAL: 'Portal do agente de vendas principal',
  SALES_AGENT_PORTAL: 'Portal do agente de vendas',
  E911_ADDRESS: 'Endereço E911',
  OVERVIEW: 'Visão geral',
  ADD_COMPANY_OR_SALES_AGENT: 'Adicionar uma empresa ou um agente',
  ADD_AN_AGENT: 'Adicionar um agente a',
  INACTIVE: 'Inativo',
  AGENTS_PERSONAL_CONNECTION_LINK: 'Link de conexão pessoal do agente',
  PURCHASE_DATE_AND_CUSTOMER: 'Data de compra e cliente',
  ORDER_DETAILS: 'Informações do pedido',
  SELECT_AGENT: 'Todos os agentes',
  FROM: 'de',
  TO: 'para',
  EXPORT_REPORT: 'Exportar relatório',
  NO_SALES_FOUND: 'Nenhuma venda encontrada',
  ADD_A_COMPANY: 'Adicionar uma empresa',
  AUTO_APPROVE_COMPANY: 'Aprovar empresa automaticamente',
  AUTO_ACTIVATE_AGENT: 'Ativar agente automaticamente',
  ADD_COMPANY: 'Adicionar empresa',
  ADD_COMPANY_NAME_AGENT_ADMIN: 'Adicionar agente/administrador da {COMPANY_NAME}',
  ADD_AGENT_ADMIN: 'Adicionar agente/administrador',
  ALL_COMPANIES: 'Todas as empresas',
  START_DATE: 'Data de início',
  HEY: 'Olá',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: 'Sou seu gerente de Sucesso do cliente. Estou aqui para ajudar você a obter o máximo de retorno de suas soluções Avaya Cloud. Sua equipe de suporte do Avaya Cloud Solutions também inclui a Equipe de suporte técnico – <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: 'Gostaríamos de agendar uma chamada de início do serviço nos próximos dias, a fim de apresentar sua equipe de suporte e finalizar a configuração de seu sistema. <strong>Entre em contato comigo por meio de <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> para informar um dia e hora convenientes para uma chamada de início do serviço que dura cerca de 1 hora.<strong>',
  START_USING_YOUR_IP_OFFICE: 'Comece a usar seu sistema Avaya Cloud Solutions agora!',
  BELOW_ARE_DETAILS: 'Abaixo você encontrará as informações de conta, credenciais e downloads de aplicativo de seu sistema:',
  YOUR_IP_OFFICE_INFO: 'As informações de seu sistema:',
  LOGIN_INFO_TABLE: 'O gráfico de informações de seu usuário:',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'Todos os seus usuários podem configurar suas respectivas informações, ajustar o encaminhamento de chamadas, escutar mensagens na caixa postal e mais usando as informações acima e fazendo logon nos portais individuais de usuário do Cloud.',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'Aplicativos disponíveis para seus usuários:',
  DO_NOT_HESITATE_TO_EMAIL_US: 'Não deixe de entrar em contato conosco em <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a> caso tenha qualquer dúvida!',
  THANK_YOU: 'Obrigado,',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web (extensão para Chrome)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions Soft Console (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">Documento de instalação</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">Documento de instalação</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">Documento de instalação</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">Documento de instalação</a>',




  USER_NAMES_COLUMN: 'Nome de usuário',
  EXTENSIONS_COLUMN: 'Ramal',
  TEMP_PIN_COLUMN: 'PIN',
  TEMP_PASSWORD_COLUMN: 'Senha',
  USER_TYPE_COLUMN: 'Tipo de usuário',
  DEVICE_MODEL_COLUMN: 'Dispositivo',
  POWER_USER: 'Power',
  STANDARD_USER: 'Padrão',
  BASIC_USER: 'Básico',
  ORDERID: 'ID do pedido',
  ACCOUNT_NAME: 'Nome da conta',
  HOST_NAME: 'Nome do host',
  ADMIN_PORTAL: 'Portal do administrador',
  IP_ADDRESS: 'Endereço IP',
  PHONE_NUMBER: 'Número de telefone',
  TEMPORARY_PHONE_NUMBER: 'Número temporário de telefone',
  EXCITING_TIMES_AHEAD: 'Momentos empolgantes estão por vir',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'O nome de domínio {DOMAIN_NAME} é um nome de domínio inválido ou está sendo usado por outra empresa.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'O nome de domínio {1} é um nome de domínio inválido ou está sendo usado por outra empresa.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: 'O sistema não conseguiu validar sua empresa. Tente novamente',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'Para qualquer informação N/A (caso exista), entre em contato com o suporte do Avaya Cloud: ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Falha na inicialização do provisionamento de uma conta do Avaya Cloud',
  LEGAL: 'Jurídico',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Selecione um plano de 1 ano (ou mais) e receba um crédito por usuário para a compra de qualquer dispositivo. Oferta por tempo limitado.',
  USER_PORTAL: 'Portal do usuário',
  E_911: 'E911',
  DECLINE: 'Rejeitar',
  ACCEPT: 'Aceitar',
  PRINT: 'Imprimir',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'Aceite todos os termos acima para concluir seu pedido',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'Atribua um dispositivo a seus usuários.',
  SELECT: 'Selecionar',
  USER_DETAILS: 'Detalhes do usuário',
  DEVICE_DETAILS: 'Detalhes do dispositivo',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: 'Leia cuidadosamente nossos Termos de serviços antes de aceitá-los.',
  PARTNER_ORDERS_RECORDS_HINT: '*Todos os registros de vendas servem apenas para referência. Os relatórios de vendas finais e oficiais serão fornecidos pela pelo departamento financeiro da Avaya conforme o contrato do Agente de vendas principal.',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: 'Selecione um Agente de vendas para criar uma cotação',
  COMPANY_DETAILS: 'Detalhes da empresa',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'Além dos tributos aplicáveis.',
  SELECT_PRODUCT: 'Selecionar produto',
  CLOUD_UC_SMALL_MONTH1: 'Plano Cloud UC Essentials mensal',
  SMALL: 'Pequeno',
  CLOUD_UC_SMALL_MONTH12: 'Plano Cloud UC Essentials de 1 ano',
  CLOUD_UC_SMALL_3YEARS: 'Plano Cloud UC Essentials de 3 anos',
  CLOUD_UC_SMALL_5YEARS: 'Plano Cloud UC Essentials de 5 anos',
  MEDIUM: 'Médio',
  CLOUD_UC_MEDIUM_MONTL1: 'Plano Cloud UC Business mensal',
  CLOUD_UC_MEDIUM_MONTH12: 'Plano Cloud UC Business de 1 ano',
  CLOUD_UC_MEDIUM_3YEARS: 'Plano Cloud UC Business de 3 anos',
  CLOUD_UC_MEDIUM_5YEARS: 'Plano Cloud UC Business de 5 anos',
  LARGE: 'Grande',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC Large pré-pago',
  CLOUD_UC_LARGE_MONTL12: 'Plano Cloud UC Large anual',
  CLOUD_UC_SMALL_SHORT_INFO: '1 a 99 funcionários',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100 a 999 funcionários',
  CLOUD_UC_LARGE_SHORT_INFO: 'Mais de 1.000 funcionários',
  SELECTED: 'Selecionado',
  BASIC_PHONE_SERVICE: 'Serviço telefônico básico',
  UNLIMITED_NATIONAL_WIDE: 'Chamadas nacionais de longa distância ilimitadas',
  STANDARD_FEATURES: 'Recursos padrão',
  HOW_MANY_USERS: 'De quantos usuários você precisa?',
  ADD_ON_ADDITIONAL_FEATURES: 'Recursos adicionais',
  ONETIME_FEE: 'Taxa avulsa',
  RECURRING_FEE: 'Taxa recorrente',
  SELECT_MAIN_NUMBER: 'Selecione o nome principal',
  TOLL_FREE: 'Números de chamada gratuita',
  LOCAL_NUMBER: 'Número local',
  TRANSFER_NUMBER: 'Número de transferência',
  USERS_COUNT: '{qty} usuários',
  DEVICES_COUNT: '{qty} dispositivo(s)',
  UC_OFFER_TITLE: 'Temos a solução certa para você!',
  UC_OFFER_DESCRIPTION: 'Não importa se você é uma empresa de porte pequeno, médio ou grande, temos o que você está buscando! Em qual dos tipos seus negócios se encaixam?',

  // 'BASIC_PHONE_SERVICE': 'Serviço telefônico básico',

  TAX_CALC_ERROR_MSG: 'Não foi possível calcular os tributos. Verifique se o endereço para cobrança está correto.',
  'VIOLATION.FIELD_IS_EMPTY': '{1} é obrigatório',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} - {2} é obrigatório',
  'VIOLATION.FIELD_VALUE_INVALID': 'O valor {1} é inválido',
  'VIOLATION.FIELD_VALUE_INVALID2': 'O valor {1} - {2} é inválido',
  'VIOLATION.TAX_CALCULATION_FAILED': 'Falha no cálculo dos tributos',
  'VIOLATION.AGREE_ON_LEGAL_DOC': 'É necessário ler e concordar com “{1}”',
  'VIOLATION.CART_IS_EMPTY': 'Seu carrinho está vazio',
  'VIOLATION.CART_IS_TOO_BIG': 'O carrinho tem muitos itens',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} foi removido do carrinho',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': 'A quantidade de {1} foi ajustada de {2} para {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': 'O desconto de {1} foi ajustado de {2} para {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': 'Não é possível adicionar o item com a moeda {1} ao carrinho com a moeda {2}',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': 'A regra de desconto {1} não está definida',
  'SALESMODELRULE.UNKNOWN_ERROR': 'Erro desconhecido',
  'SALESMODELRULE.INVALID_PARAMETER': 'Parâmetro inválido: {1}',
  ONE_TIME: 'Uma vez',
  ADDON_PRICING_HINT: '*Os preços dos complementos são por pessoa e aplicados a todos os usuários. É possível adicionar complementos específicos aos usuários após a compra em seu portal de administrador.',
  ADD_TO_CART_HINT: 'Finalize as etapas acima para adicionar ao carrinho',
  ITEM_UNITS: '{qty} unidades',
  ADDONS_COUNT: '{qty} complementos',
  ADDON_COUNT: '{qty} complemento',
  MULTIPLE_TYPES: 'Vários tipos',
  MIXED: 'Misto',
  FREE_PRICE: 'GRATUITO',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC Essentials',
  UC_ESSENTIALS_DESCRIPTION: 'O melhor das comunicações baseadas em nuvem para empresa de qualquer porte.',
  UC_BUSINESS: 'UC Business',
  UC_BUSINESS_DESCRIPTION: 'Habilite sua empresa com a última palavra em comunicações empresariais na nuvem',
  UC_BUSINESS_POWER_PACKAGE: 'Atualizar para usuários POWER',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>Número telefônico direto:</strong> número dedicado e exclusivo, para que qualquer um possa chamar você diretamente em vez de passar pelo número principal do escritório e pela recepção (virtual ou humana).</li><li><strong>Chamada direta de vídeo:</strong> adicione vídeo a suas chamadas telefônicas ponto a ponto.</li><li><strong>Integração com Salesforce©:</strong> comunicações completas e avançadas para usuários finais diretamente a partir do Salesforce.</li><li><strong>Integração com Google©:</strong> comunicações em tempo real baseadas em navegador diretamente a partir do Google Chrome e em todos os seus aplicativos Google.</li><li><strong>Integração com Skype for Business©:</strong> experiência de colaboração moderna, simplificada e fácil de usar com o Skype for Business.</li></ul>',
  SHOW_MORE: 'Exibir mais',
  HIDE: 'Ocultar',
  VIEW_COMPLETE_FEATURE_LIST: ' Exibir a lista completa de recursos',
  FILTER_BY: 'Filtrar por',
  UC_OFFERS: 'UC Solutions',
  PAY_MONTHLY: 'Pagamento mensal',
  PAY_ANNUALLY: 'Pagamento anual',
  COMING_SOON: 'Em breve',
  TAX_CALC_ERROR_MSG: 'Não foi possível calcular os tributos. Verifique se o endereço está correto.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: 'Insira o nome de um país para avaliar as taxas atuais para chamada de longa distância.',
  LONG_DISTANCE_RATE_NOT_FOUND: 'Taxa de longa distância não encontrada para esse país, entre em contato com o {CUSTOMER_SUCCESS_EMAIL} para informações sobre chamadas de longa distância para esse país.',
  AREA_CODE: 'Código de área',
  INVALID_CREDIT_CARD_ZIP: 'O cartão de crédito não corresponde ao CEP.',
  VIEW_LONG_DISTANCE_RATES: 'Exibir taxas de longa distância',
  LONG_DISTANCE_SUBTITLE_TEXT: 'Nossas taxas de chamadas de longa distância mantêm você em contato com todos ao redor do mundo.',
  RATES_SUBJECT_TO_CHANGE: '*Taxas sujeitas a alterações sem aviso prévio.',
  CREDIT_CARD_DECLINED: 'O cartão de crédito foi recusado.',
  ENTER_COUNTRY_NAME: 'Insira o nome do país',
  ADD_TO_CART: 'Adicionar ao carrinho',
  UPDATE_CART: 'Atualizar carrinho',
  PER_USER: 'Por usuário',
  COMPARE_UC_OFFERS: 'Comparar ofertas do UC',
  PROCEED_TO_CHECKOUT: 'Continuar para finalizar a compra',
  BEFORE_APPLICABLE_TAXES: '*Antes dos tributos aplicáveis',
  YEAR_PLAN: 'Plano de 1 ano',
  YEARS_PLAN: 'Plano de {0} anos',
  MONTHS_PLAN: 'Plano de {0} meses',
  ENTER_NUMBER_OF_USERS: 'Insira o número de usuários que deseja para essa solução',
  YEAR: 'Ano',
  BILLED_MONTH: 'Cobrado mensalmente',
  COMPANY_INCORPORATED: 'Incorporado',
  COMPANY_NOT_INCORPORATED: 'Não incorporado',
  EXISTING_CONFIG_WARNING: 'Você tem uma configuração existente para <br/><b>{0}</b>.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: 'Deseja descartar sua configuração atual?',
  DISCARD_MY_CONFIGURATION: 'Descartar minha configuração',
  DISCARD: 'Descartar',
  EDIT_MY_CONFIGURATION: 'Editar minha configuração atual',
  CONTINUE: 'Continuar',
  SELECT_A_PLAN: 'Selecionar um plano',
  PROMOTION_DETAIL_INFO: '*Você selecionou um total de <b>{0} usuários</b>!<br/> Equivalente a <b>{1}</b> em crédito total de dispositivos.',
  BILLED_MONTH_FREQUENCY: 'Cobrados a cada {0} meses',
  BILLED_YEAR_FREQUENCY: 'Cobrados a cada {0} anos',
  CONTACT_OUR_CUSTOMER_CARE: 'Entrar em contato com nossa equipe de Atendimento ao cliente',
  NEED_HELP_INFO: 'Precisa de ajuda? Nossa equipe de Atendimento ao cliente sempre está a postos para ajudar você com qualquer possível dúvida, problema ou informação.',
  REMOVE: 'Remover',
  REMOVE_ITEM_FROM_CART_WARNING: 'Deseja remover <b>{0}</b> do carrinho?',
  NO_ITEM_IN_THE_CART: 'Não há itens em seu carrinho.',
  CONTINUE_SHOPPING: 'Continuar as compras',
  TOTAL_TAXES: 'Total de tributos',
  UC_SOLUTIONS: 'UC Solutions',
  UNIFIED_COMMUNICATIONS: 'Unified Communications',
  ADD_ONS: 'Complementos',
  SYSTEM_ADDONS: 'Complementos do sistema',
  ADD_DEVICES: 'Adicionar dispositivos',
  SELECT_UPTO_DEVICES: 'Selecione até (<b>{0}</b>) dispositivos para <b>{1}</b>',
  DONE: 'Concluído',
  SELECT_DEVICES: 'Selecionar dispositivos',
  EDIT_DEVICE_SELECTION: 'Editar dispositivos',
  ESSENTIAL_USERS: 'Usuários Essential',
  BUSINESS_USERS: 'Usuários Business',
  POWER_USERS: 'Usuários Power',
  N_A: 'N/A'
}
