export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: 'Не удалось расшифровать данные из системы учетных записей',
  PHONE_TYPES: 'Типы телефонов',
  IMAGINE_A_BETTER_WAY: 'Новый подход',
  OF_DOING_THINGS: 'к привычному.',
  GET_STARTED: 'Начало работы',
  PURCHASE: 'Покупка',
  DOWNLOADS_AND_EXTENSIONS: 'Загрузки и расширения',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: 'Весь арсенал средств в специальных надстройках и дополнениях Zang.',
  ALL: 'Все',
  REFERRAL_AGENT: 'Полномочный представитель',
  SALES_AGENT: 'Агент по продажам',
  CART: 'Корзина',
  PARTNER_PROGRAMS: 'Партнерские программы',
  HOME: 'Главная',
  MANAGE_CREDIT_CARDS: 'Управление кредитными картами',
  MANAGE_PAYMENT_OPTIONS: 'Управление параметрами оплаты',
  MANAGE_BILLING_ACCOUNT: 'Управление учетной записью для выставления счетов',
  LIMIT: "Лимит",
  MY_PROFILE: 'Мой профиль',
  MY_SETTINGS: 'Мои настройки',
  MY_PARTNER_PORTAL: 'Портал для партнеров',
  CLEAR_ZANG_OFFICE: 'Удалить Zang Office',
  CLEAR_ZANG_SPACES: 'Удалить Zang Spaces',
  FEATURE_BREAKDOWN: 'Разбиение функции',
  PLAN_BREAKDOWN: 'Информация о плане', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'Оптимальный телефон для бизнеса по привлекательной цене',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Представьте все возможности Zang Spaces',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'Скидка 50% будет применена к итоговой сумме после оформления заказа',
  HURRICANE_HARVEY_MESSAGE: 'Avaya и Zang желают помочь компаниям, которые пострадали от ураганов Харви и Ирма. Пострадавшие компании из Техаса, Луизианы, Флориды, Алабамы, Джорджии, Северной и Южной Каролины, Теннесси и Миссисипи могут уже сейчас <b>получить 3 месяца пользования Zang Office</b> и <b>Zang Spaces БЕСПЛАТНО</b>.',
  LEARN_MORE: 'Дополнительные сведения',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'УСТРОЙСТВО AVAYA VANTAGE™ ТЕПЕРЬ ДОСТУПНО',
  NEW: 'НОВИНКА!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Раскройте все возможности Zang Office — удобный покрытый стеклом телефон для голосовой связи, видеосвязи и чатов.',
  LOG_IN: 'Войти',
  SIGN_UP: 'Зарегистрироваться',
  SIGN_OUT: 'Выйти',
  SIGN_IN: 'Войти', //login to the system, connect
  ADMINISTRATION: 'Администрирование',
  PRODUCTS: 'Продукты',
  ORDERS: 'Заказы',
  PAGES: 'Страницы',
  CUSTOMERS: 'Заказчики',
  USERS: 'Пользователи',
  PLANS: 'Тарифные планы',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'Подробная информация о вызовах',
  CDR_CHECKS: 'Проверки информации о вызовах',
  PARTNERS: 'Партнеры',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'Вы уже купили Zang Office. Вы больше не можете заказать Zang Office.',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: 'Похоже, что вы уже приобрели Avaya Cloud для этой компании. Выберите другую компанию.',
  PARTNER_CONNECTIONS: 'Связь с партнерами',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'При размещении заказа произошла ошибка. За дополнительной информацией обратитесь в службу поддержки Zang ({SUPPORT_EMAIL}).',
  APPLICATION_GENERAL_FATAL_ERROR: 'При отправке заявки произошла ошибка. За дополнительной информацией обратитесь в службу поддержки Zang ({SUPPORT_EMAIL}).',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Для продолжения выберите по меньшей мере один тип пользователей.',
  BACK: 'Назад',
  SAVE_CHANGES: 'Сохранить изменения',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: 'Продолжить?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'У вас кредит {PLACEHOLDER} на покупку любого устройства. Этот кредит будет потерян, как только ваш заказ будет подтвержден.',
  JUST_A_REMINDER: 'Напоминание',
  LAST_CHANCE: 'ПОСЛЕДНИЙ ШАНС',
  IM_GOOD_PLACE_MY_ORDER: 'Хорошо. Оформить заказ',
  BUY_MORE_DEVICES: 'Купить еще устройства',
  YES_PLACE_MY_ORDER: 'Да, оформить заказ',
  NO_THANKS: 'Нет, спасибо.',
  YES: 'Да',
  ABOUT_US: 'О компании',
  NEWS_AND_PRESS: 'Новости и публикации',
  CARREERS: 'Карьера',
  CONTACT_US: 'Свяжитесь с нами',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Спасибо за покупку! Ниже приведены сведения о заказе.',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: 'Для получения этой информации обратитесь по адресу <a href="mailto:{EMAIL}">{EMAIL}</a>',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: 'Наши специалисты по работе с клиентами и представители службы поддержки свяжутся с вами, когда система будет готова. <br/><br/><b>Обратите внимание, что настройка системы может занять до одного часа.</b>',
  QUESTION_CUSTOMER_SERVICE: 'Если у вас есть вопросы, обратитесь по адресу <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>.',
  BLOG: 'Блог',
  FAQS: 'Часто задаваемые вопросы',
  DOCUMENTATION: 'Документация',
  TERMS_OF_SERVICE: 'Условия предоставления услуг',
  HELP: 'Справка',
  PRIVACY_STATEMENT: 'Заявление о конфиденциальности',
  GENERAL_PRIVACY_STATEMENT: 'Общее заявление о конфиденциальности данных',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: 'Общие условия обслуживания — Avaya Cloud Solutions',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. Все права защищены.',
  PROCESSING: 'Обработка',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Подождите. Этот процесс может занять какое-то время',
  OPEN_IN_A_NEW_TAB: 'Открыть в новой вкладке',
  GOT_IT: 'Готово!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' Это действие может привести к следующим результатам:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Удаление месячной подписки на этот тарифный план',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Отключение учетных записей на сторонних системах',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Изменение статуса тарифного плана на «ОТКЛЮЧЕН»',
  LAST_ACTION_STEPS: 'Этапы выполнения последнего действия',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'Надстройки приобретаются через портал администратора Zang Office после создания учетной записи.',
  TYPE: 'Тип',
  ADMIN: 'Администратор',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'Этот пользователь будет выбран в качестве основного контакта/контакта для выставления счетов для корпоративной учетной записи. Его можно изменить в любое время на портале администратора Zang Office.',
  DESCRIPTION: 'Описание',
  SUCCESS: 'Успешно',
  REQUEST_CANCELATION: 'Отмена заявки',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Жаль, что вы покидаете нас.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Заполните форму ниже, чтобы начать отмену заявки. Чтобы все прошло без проблем, представитель нашей службы поддержки рассмотрит ваш запрос и свяжется с вами в течение 1–2 рабочих дней.',
  YOUR_NAME: 'Ваше имя',
  COMPANY: 'Компания',
  SERVICE: 'Служба',
  REASON_FOR_CANCELING: 'Причина отмены заявки',
  SUBMIT: 'Отправить',
  EXIT: 'Выход',
  REQUEST_SUBMITTED: 'Запрос отправлен.',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Чтобы все прошло без проблем, представитель нашей службы поддержки рассмотрит ваш запрос и свяжется с вами в течение 1–2 рабочих дней.',
  DATE: 'Дата',
  PRODUCT: 'Продукт',
  USER: 'Пользователь',
  STATUS: 'Статус',
  ACTIONS: 'Действия',
  VIEW_DETAILS: 'Просмотреть дополнительные сведения',
  DISABLE: 'Отключить',
  ENABLE: 'Включить',
  CANCEL: 'Отмена',
  PLAN_DETAILS: 'Сведения о плане',
  SUMMARY: 'Общая информация',
  QUANTITIES: 'Объемы предоставления услуг',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '* Итоговая сумма отображает общую стоимость выбранных услуг плана',
  TOTAL: 'Всего',
  BILLED: 'К оплате',
  PLAN_INFORMATION: 'Сведения о плане',
  UPDATE_PLAN: 'Перейти на другой план',
  ADMIN_ACTIONS: 'Действия администратора',
  NAME_ON_CREDIT_CARD: 'Имя владельца кредитной карты',
  CREDIT_CARD_BRAND: 'Платежная система кредитной карты',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: 'Номер кредитной карты',
  EXPIRATION: 'Срок действия',
  MONTH: 'Месяц',
  YEAR: 'Год',
  SECURITY_CODE: 'Код безопасности',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'Код на обратной стороне кредитной карты',
  BACK_TO_CHECKOUT: 'Назад к оформлению заказа',
  NO_ORDERS_FOUND: 'Заказы не найдены',
  ADD: 'Добавить',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Для добавления кредитной карты воспользуйтесь формой ниже. Убедитесь, что заполнены все поля',
  NUMBER: 'Номер',
  EXPIRES: 'Действительна до',
  DELETE: 'Удалить',
  ITEM_DETAILS: 'Подробные сведения о покупке',
  FEE: 'Стоимость',
  ITEMS: 'Элементы',
  SEARCH_BY_CONFIRMATION: 'Поиск по подтверждению',
  CONFIRMATION: 'Подтверждение',
  CHECKOUT_STATUS: 'Статус оформления заказа',
  ORDER_STATUS_PROCESS: 'Обработка статуса заказа',
  CREATED_ON: 'Создано:',
  ORDER_SUMMARY: 'Сводка заказа',
  APPROVED: 'Утверждено', //example: partner application approved
  REJECTED: 'Отклонено', //example: partner application rejected
  APPROVE: 'Утвердить', //example: partner application approved
  REJECT: 'Отклонить', //example: partner application rejected
  PENDING: 'Ожидание', //example: partner application pending
  EDIT: 'Изменить',
  ONE_TIME_FEE: 'Одноразовая комиссия',
  SUB_TOTAL: 'Промежуточная сумма',
  TAXES: 'Налоги',
  CHANGES: 'Изменения',
  CREATE_A_QUOTE: 'Создать смету',
  EXTRA_INFORMATION: 'Дополнительные сведения',
  THANK_YOU_FOR_YOUR_ORDER: 'Благодарим за заказ!',
  ORDER_CONFIRMATION: 'Подтверждение заказа',
  INVALID_ORDER: 'Недействительный заказ',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'Не беспокойтесь, мы также отправили его по электронной почте :)',
  HELLO: 'Здравствуйте!',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Спасибо за покупку! После отправки товаров мы отправим подтверждение. Ниже приведены сведения о заказе.',
  ACCOUNT_INFORMATION: 'Сведения о счете',
  BILLING_INFORMATION: 'Платежные реквизиты',
  SHIPPING_INFORMATION: 'Сведения для доставки',
  NAME: 'Имя',
  EMAIL: 'Электронная почта',
  SEARCH: 'Поиск',
  CLEAR: 'Очистить',
  PARTNER: 'Партнер',
  NO_PARTNERS_FOUND: 'Партнеры не найдены',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'Связь с партнером создается, когда покупатель переходит в магазин по ссылке, предоставленной партнером.',
  CUSTOMER: 'Заказчик',
  AGENT: 'Агент',
  NO_PARTNER_CONNECTIONS_FOUND: 'Не обнаружены контактные данные партнеров',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'Прочитав, я принимаю',
  ZANG_PRIVACY_STATEMENT: 'заявление о конфиденциальности Zang',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'Условия предоставления услуг в рамках агентской программы',
  SUBMIT_APPLICATION: 'Отправить форму',
  SUBMITTING: 'Отправка',
  SUBMITTING_YOUR_APPLICATION: 'Отправка формы',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'По условиям предоставления услуг мы обязуемся обеспечивать сохранность и конфиденциальность банковской информации и сведений учетных записей.',
  BANK_NAME: 'Название банка',
  ADDRESS: 'Адрес',
  COUNTRY: 'Страна',
  SELECT_ONE: '- Выберите -',
  STATE_PROVINCE: 'Штат/область',
  CITY: 'Населенный пункт',
  ZIP_POSTAL_CODE: 'Почтовый индекс',
  ACCOUNT_NUMBER: 'Расчетный счет',
  BANK_NUMBER: 'Банковский номер',
  TRANSIT_NUMBER: 'Инкассовый код',
  SWIFT_CODE: 'Код SWIFT',
  TAX_REGISTRATION_NUMBER: 'Регистрационный номер налогоплательщика',
  SAVE_BANK_INFORMATION: 'Сохранить банковские реквизиты',
  SAVING_BANK_INFORMATION: 'Сохранение банковских реквизитов',
  NO_CUSTOMERS_FOUND: 'Заказчики не найдены',
  YOU_ARE_A: 'Вы ',
  A_DISCOUNT_OF: 'Скидка',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'будет применена к полной сумме после оформления заказа.',
  FIRST_NAME: 'Имя',
  LAST_NAME: 'Фамилия',
  COMPANY_NAME: 'Название компании',
  LEGAL_COMPANY_NAME: 'Наименование юридического лица',
  PHONE_NUMBER: 'Номер телефона',
  WEBSITE: 'Веб-сайт',
  OPERATIONAL_ADDRESS: 'Адрес осуществления деятельности',
  SAME_AS_ORGANIZATION_ADDRESS: 'Совпадает с юридическим адресом',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: 'Вы являетесь партнером Avaya?',
  NO: 'Нет',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Если да, введите идентификатор партнера Avaya',
  MY_PARTNER_PORTAL: 'Портал для партнеров',
  THANK_YOU_FOR_APPLYING: 'Спасибо за заявку!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'Остался один шаг. Чтобы завершить оформление заявки на агента по продажам, перейдите по ссылке ниже и ответьте на все вопросы.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' Если нет, сообщите ',
  PLEASE_GIVE: 'Сообщите',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'Если вы уже партнер Avaya, НЕ переходите по ссылке. <br />Мы проверим ваш ИД партнера и свяжемся с вами в ближайшее время.',
  BUSINESS: 'рабочих',
  DAYS: 'дн.',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'руководство рассмотрит вашу заявку.<br /> А пока все вопросы можно отправлять',
  COMPLETE_MY_APPLICATION: 'Завершить заявку',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'Мы рассмотрели вашу заявку. К сожалению, сейчас мы не можем включить вас в программу. Вряд ли причина серьезная, но пока мы с ней не разберемся, вы не можете стать нашим партнером. Понимаем, что эта новость может вас расстроить. Мы выясним, почему заявка отклонена, и свяжемся с вами. А пока вы можете обращаться',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'с любыми вопросами, касающимися данной процедуры.',
  CONGRATULATIONS: 'Поздравляем!',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: 'Теперь вы официальный агент Zang.',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Поделитесь своей ссылкой со всеми потенциальными клиентами',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'и помогите им узнать, как лучше вести бизнес.',
  CHANGE_STATUS: 'Изменить статус',
  AGENT_DETAILS: 'Сведения об агенте',
  BANK_INFORMATION: 'Банковские реквизиты',
  THIS_ORDER_WAS_PLACED_BY_A: 'Этот заказ был принят',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'была вычтена из общей сумме',
  REFERRALS: 'Рефералы',
  SALES: 'Продажи',
  FOUND: 'Найдено',
  HOW_IT_WORKS: 'Принцип работы',
  WHAT_YOU_GET: 'Что вы получаете',
  SUPPORT: 'Поддержка',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'Какая программа больше всего подходит мне?',
  WHY_JOIN: 'Почему стоит присоединиться?',
  QUOTE: 'Предложение',
  PRINT_THIS_QUOTE: 'Распечатать это предложение',
  CLOSE_THIS_WINDOW: 'Закрыть это окно',
  SEARCH_BY_PLAN: 'Поиск по плану',
  ACCESS_LEVEL: 'Уровень доступа',
  DISPLAY_NAME: 'Отображаемое имя',
  INDUSTRY: 'Вид деятельности',
  COMPANY_INDUSTRY: 'Сфера деятельности компании',
  CONTACT_PHONE_NUMBER: 'Контактный номер телефона',
  EMAIL_ADDRESS: 'Адрес электронной почты',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Да, я хочу получать рассылку о новостях, приложениях, предложениях и мероприятиях Zang.',
  INFORMATION: 'Информация',
  ORDER_HISTORY: 'История заказов',
  FILTER: 'Фильтр',
  ACCOUNT: 'Учетная запись',
  AMOUNT_CHARGED: 'Сумма списания',
  DETAILS: 'Дополнительные сведения',
  NO_RECORDS_FOUND: 'Записи не найдены',
  CALL_LOGS: 'Журналы вызовов',
  EXPORT: 'Экспорт',
  CALLER_NAME: 'Имя абонента',
  DIALED_NUMBER: 'Набранный номер',
  DURATION_SEC: 'Длительность (с)',
  COST: 'Стоимость',
  PAYMENT_METHOD: 'Способ оплаты',
  PURCHASE_ORDER: 'Заказ на покупку',
  PURCHASE_ORDERS: 'Заказы на покупку',
  CREDIT_CARD: 'Кредитная карта',
  SHIPPING_ADDRESS: 'Адрес доставки',
  SAME_AS_BILLING_ADDRESS: 'Совпадает с адресом для выставления счетов',
  SAME_AS_SHIPPING_ADDRESS: 'Совпадает с адресом доставки',
  OTHER: 'Другое',
  SHIPPING_OPTIONS: 'Варианты доставки',
  FREE_SHIPPING: 'БЕСПЛАТНАЯ доставка',
  ADDITIONAL_NOTES: 'Дополнительные замечания',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'Прочитав, я соглашаюсь с приведенными ниже условиями:',
  EMERGENCY_911_SERVICE_NOTICE: 'Разъяснение по обслуживанию номеров экстренных служб',
  PLACE_MY_ORDER: 'Оформить заказ',
  CLEAR_MY_ORDER: 'Удалить заказ',
  PLACING_YOUR_ORDER: 'Оформление заказов',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'Подождите. Эта процедура может занять до 1 минуты.',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: 'Эта процедура может занять некоторое время. Благодарим за терпение. Чтобы не прервать обработку вашего заказа, не закрывайте это окно браузера и не щелкайте кнопки "Назад" и "Обновить".',
  YOUR_NEW_NUMBER: 'Ваш новый номер',
  NO_NUMBER_SELECTED: 'Номер не выбран',
  WELL_THAT_WAS_EASY: 'Это было несложно.',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'Еще чуть-чуть и готово :)',
  NEXT: 'Следующий',
  TITLE: 'Обращение',
  SUB_TITLE: 'Подзаголовок',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Поиск по коду области... (только США и Канада)',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: 'Введите междугородный код... (только для США)',
  SELECT_A_PREFIX: 'Выберите префикс',
  PICK_THIS_NUMBER: 'Приобрести этот номер',
  DEVICES: 'Устройства',
  BILLING: 'Тарификация',
  CHANGE: 'Изменить',
  USER_INFO: 'Сведения о пользователе',
  USE_MY_INFORMATION: 'Использовать мои сведения',
  SELECT_YOUR_DEVICES: 'Выберите устройства',
  MONTHLY_FEE: 'Стоимость в месяц',
  ANNUAL_FEE: 'Стоимость годовой подписки',
  TWO_YEAR_FEE: 'Стоимость двухгодичной подписки',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'В каждом плане Zang Office должен быть как минимум один пользователь со стандартными ИЛИ расширенными правами.',
  CHECKOUT: 'Оформить заказ',
  MINE: 'Мои',
  REMOVE_THIS_USER: 'Удалить этого пользователя',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Выберите устройство для этого пользователя',
  ADD_ANOTHER: 'Добавить',
  GET_STARTED_WITH_ZANG_OFFICE: 'Начать работу с Zang Office',
  BUNDLE: 'пакет',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Оформите годовую подписку и получите',
  OFF: 'ВЫКЛ.',
  EACH_USER: 'каждый пользователь',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'Чтобы настроить количество пользователей, удалите свой заказ либо перейдите к выбору устройств.',
  EVERY_TWO_YEARS: 'Каждые 2 года',
  YOU_VE_SAVED: 'Сохранено',
  INCLUDED: 'Включено',
  ADDONS: 'Дополнения',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Индивидуальная настройка пользователей.',
  UNITS_PER: 'Единиц в',
  TALK_ANYWERE_ANYTIME: 'Общайтесь когда и где угодно.',
  DOWNLOAD_FOR_MAC: 'Скачать для MAC',
  DOWNLOAD_FOR_WINDOWS: 'Скачать для Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Благодарим за приобретение Zang Office! Просмотреть заказ можно здесь.',
  CONTINUE_WITH_YOUR_PURCHASE: 'Продолжить покупку.',
  GET_STARTED_TODAY: 'Приступить к работе сейчас.',
  FEATURES: 'Функции',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Посмотрим подробнее.',
  BASIC: 'Базовый',
  STANDARD: 'Стандарт',
  POWER: 'Расширенный',
  RATE_MIN_STARTING_FROM: 'тариф/мин., начальный*:',
  RATE_MIN_STARTING_FROM_1: 'Тариф в мин., начиная с',
  LONG_DISTANCE: 'Международные вызовы',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'Тарифы на международные звонки (на большие дистанции)',
  COMMON_DESTINATIONS: 'Обычные адресаты',
  BEST_DEAL: 'лучшее предложение',
  PER_ACTIVE_USER_PER_MONTH: 'За активного пользователя в месяц.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'согласно годовому контракту',
  BILLED_ACCORDING_TO_SELECTED_PLAN: 'Тарификация в соответствии с выбранным планом.',
  MONTHLY: 'Ежемесячно',
  ANNUALLY: 'В год',
  BILLED_ANNUALY: 'С выставлением счетов раз в год',
  BILLED_EVERY_TWO_YEARS: 'С выставлением счетов раз в 2 года',
  CONFIGURE_YOUR_ADDONS: 'Настроить дополнения',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Выберите количество для каждого из доступных дополнений.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'Максимальное количество для данного дополнения —',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'Это дополнение доступно только для',
  BILLING_AND_SHIPPING: 'Тарификация и доставка',
  BILLING: 'Тарификация',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'Это ваша учетная запись Zang Office.',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: 'Это будет именем вашей учетной записи Avaya Cloud.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Если вы решили использовать в качестве номера Zang Office существующий или бесплатный номер, мы попытаемся найти местный номер с расширением, указанным в этом поле.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Благодаря Spaces возможно все',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'Инструмент для совместной работы на основе облака: удивительно, что никто до сих пор его не создал.',
  YOUR_CURRENT_PURCHASES: 'Ваши текущие покупки',
  PURCHASED_ON: 'Приобретено по',
  PLAN_NUMBER: 'Тарифный номер',
  UPDATE: 'Обновить',
  UPDATED: 'Обновлено',
  OR: 'или',
  MAKE_A_NEW_PURCHASE: 'Сделать еще одну покупку',
  FEATURES_AND_ADDONS: 'Функции и дополнения',
  FREE: 'БЕСПЛАТНЫЙ',
  PLUS: 'ПЛЮС',
  BUSINESS: 'КЛЮЧЕВОЙ',
  VIEW: 'Просмотр',
  TEAM: 'Группа',
  LETS_SETUP_YOUR_TEAM: 'Давайте организуем группу',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Выберите тип группы и настройте вашу личную среду.',
  COMPANY_TYPE: 'Тип компании',
  DOMAIN: 'Домен',
  NO_TEAM_IS_SETUP_YET: 'Пока не организована ни одна группа',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'Не организовывать группы для меня',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Приобретите Zang Spaces только для себя.',
  CHOOSE_AN_EXISTING_COMPANY: 'Выберите существующую компанию',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Выберите одну из компаний, которую сейчас администрируете.',
  CREATE_A_NEW_TEAM: 'Создать группу',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Укажите название группы и доменное имя.',
  NO_DOMAIN_IS_CONFIGURED: 'Не настроен ни один домен.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Укажите доменное имя (например, zang.io)',
  CHECK: 'Проверить',
  TEAM_DOMAIN: 'Домен группы (например, zang.io)',
  TEAM_NAME: 'Название группы (например, Zang)',
  OK: 'ОК',
  ZANG_SPACES_ADMIN_CONSOLE: 'Консоль администратора Zang Spaces',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'Вы можете изменить значения ниже, чтобы модернизировать тарифный план',
  CHARGABLE_USERS: 'Платные пользователи',
  TOTAL_USERS: 'Всего пользователей',
  CURRENT_PRICE: 'Действующая цена',
  SAVE: 'Сохранить',
  SAVE_CHANGES_AND_UPDATE_PLAN: 'Сохранить изменения и модернизировать тарифный план?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Для продолжения выберите по меньшей мере один тип пользователей',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Вы приобретаете Zang Spaces за',
  BUY_NOW: 'Купить сейчас',
  SELECT: "Выбрать",
  UP_TO: 'До',
  NO_PURCHASE_REQUIRED: 'покупка не требуется',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'Отсутствуют счета или авансовые обязательства.',
  SIGN_UP_FOR_FREE: 'Подписка на бесплатную версию.',
  ONE_YEAR_PLAN: 'Тарифный план на 1 год',
  MONTHLY_PLAN: 'Месячный план',
  TWO_YEAR_PLAN: 'Тарифный план на 2 года',
  MONTHS: 'мес.',
  ZANG_OFFICE_ACCOUNT_NAME: 'Имя учетной записи Zang Office',
  ZANG_OFFICE_PLAN_NUMBER: 'Номер тарифа Zang Office',
  TEMPORARY_NUMBER: 'Временный номер',
  START_SETTING_UP_ZANG_OFFICE: 'Приступить к настройке Zang Office.',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'Чтобы перевести существующий номер в систему Zang Office, отправьте форму для LNP-авторизации и копию последнего счета за телефон по адресу zosupport@zang.io. При переводе бесплатного номера понадобится также форма RODAA. Обратите внимание, что на перевод понадобится до 10 рабочих дней.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'При покупке/активации выбранного номера Zang Office произошла ошибка. Щелкните «Приступить к настройке Zang Office», чтобы приобрести/активировать номера вручную. Если вы решили использовать существующий номер, это никак не повлияет на процесс переноса номеров.',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'Примечание. Чтобы перевести существующий номер в учетную запись Zang Office, заполните и отправьте <a href="{LNP_FORM_LINK}" target="blank">форму для LNP-авторизации</a> и копию последнего счета за телефон на наш электронный адрес. При переводе бесплатного номера понадобится также <a href="{RODAA_LINK}" target="blank">форма RODAA</a>. Отправьте необходимые документы по адресу <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. Перевод телефонного номера может длиться до 10 рабочих дней.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Обратите внимание, что перевод телефонного номера может длиться до 10 рабочих дней. Тем временем мы выдадим вам временный номер.',
  PLAN_STATUS: 'Статус тарифного плана',
  PLAN_ID: 'Идентификатор тарифного плана',
  SUBSCRIPTION_ID: 'Идентификатор подписки',
  STRIPE_PLAN_ID: 'Идентификатор тарифного плана Stripe',
  ACCOUNT_ID: 'Идентификационные данные учетной записи',
  START_SETTING_UP_ZANG_SPACES: 'Приступить к настройке Zang Spaces',
  COMPANY_DOMAIN: 'Домен компании',
  THIS_FIELD_IS_REQUIRED: 'Это обязательное поле.',
  PLEASE_ANSWER_THIS_QUESTION: 'Ответьте на этот вопрос.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Введите идентификатор партнера Avaya.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Для продолжения прочтите и примите заявление о конфиденциальности.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Для продолжения прочтите и примите условия предоставления услуг в рамках агентской программы.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'Этот идентификатор партнера Avaya уже используется.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'Этот регистрационный номер налогоплательщика уже используется.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'Указан недействительный идентификатор партнера Avaya Partner.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'Количество должно быть положительным',
  ORDER_COMPLETE: 'Заказ оформлен.',
  PLEASE_TRY_AGAIN: 'Повторите попытку',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Выберите как минимум одно положительное значение',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'Обновление еще не завершено. Повторите попытку позже.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'Персональная лицензия не позволяет иметь несколько пользователей. Чтобы перейти на более высокий или низкий тарифный план, выберите соответствующее количество.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'У вас нет доступа к этой учетной записи.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Ваш текущий тарифный план не позволяет уменьшить исходное количество пользователей. Если требуется изменить какие-либо условия тарифного плана, обратитесь к нам по адресу customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'При регистрации заказа произошла ошибка. Убедитесь, что во всех полях указаны действительные значения,. Если ошибка повторяется, обратитесь в службу поддержки Zang',

  USE_EXISTING_NUMBER: 'Использовать существующий номер',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Выберите, чтобы использовать в тарифном плане существующий номер',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Предварительно выберите БЕСПЛАТНЫЙ номер',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Выберите, чтобы добавить в тарифный план персональный бесплатный номер',
  FIND_A_LOCAL_NUMBER: 'Найти местный номер',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Из списка локальных номеров вашей области выберите те, которые необходимо включить в тарифный план',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: 'Выберите, чтобы добавить местный номер в ваш план',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: 'Поиск доступных номеров телефонов по междугородному коду',
  SEARCH_AVAILABLE_PHONE_NUMBERS: 'Поиск доступных номеров телефонов',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: 'Введите существующий номер, который вы собираетесь перенести',


  ZANG_OFFICE_PHONE_APP: 'Приложение для телефонии Zang Office',
  ZANG_OFFICE_SOFTPHONE: 'Программный телефон Zang Office',
  ZANG_OFFICE_PHONE_APPLICATION: 'Приложение для телефонии Zang Office',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Программный телефон Zang Office обеспечивает необходимые функции связи непосредственно на вашем ПК или мобильном устройстве. Пользуйтесь всеми функциями Zang Office без дополнительных затрат — бесплатный программный телефон Zang Office уже включен в вашу подписку Zang Office.',
  E129_SIP_DESK_PHONE: 'Настольный SIP-телефон E129',
  STANDARD_PHONE: 'Обычный телефон',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Настольный SIP-телефон Avaya E129 обладает всеми важными функциями обработки вызовов, которые можно ожидать от этого доступного по цене и в то же время весьма функционального устройства. Пользователи могут отключать микрофон, переносить, переадресовывать и удерживать вызовы, а также одним нажатием кнопки организовывать конференции по запросу. Полнодуплексный телефон с громкоговорителем может работать в режиме громкой связи, а благодаря наличию порта POE его удобно подключить к сети компании. Благодаря функциональности и доступной цене аппарат для SIP-телефонии Avaya E129 подойдет широкому кругу пользователей. Блок питания переменного тока в комплекте.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Современное устройство для общения, покрытое стеклом. Доступ к голосовой связи, чатам и приложениям для совместной работы одним нажатием кнопки. Никаких прерываний и пауз. Не нужно управлять множеством устройств. Уникальные функции помогут организовать рабочий процесс и расширят функционал деловых приложений. Этот мощный настраиваемый IP-телефон обладает преимуществами настольного телефона и гибкостью программного.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'Конференц-телефон B179',
  CONFERENCE_PHONE: 'Конференц-телефон',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Телефон для конференц-связи B179 предназначен специально для мероприятий, рассчитанных более чем на 10 участников. Он существенно повышает эффективность индивидуальной и командной работы. Это мощный многофункциональный инструмент, который дополнит существующие коммуникационные решения и легко адаптируется под растущие потребности предприятия. Блок питания переменного тока в комплекте.',
  PLAN: 'Тарифный план',
  REDIRECTING: 'Перенаправление',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Во всех полях должны быть указаны действительные значения',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'В каждом плане Zang Office должен быть как минимум один тип пользователя. Вернитесь к выбору устройств и измените конфигурацию.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Вероятно, вы не выбрали номер для учетной записи Zang Office. Вернитесь к выбору номеров.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'Это имя учетной записи Zang Office занято. Введите другое имя',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'Выбранный номер Zang Office принадлежит другому клиенту. Вернитесь к выбору номеров и укажите другой.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Выберите помесячный вариант тарификации и получите <span class="text-400">ПЕРВЫЕ 30 ДНЕЙ БЕСПЛАТНО</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'или выберите годовой план и получите более выгодную цену и',
  FREE_PHONE: 'БЕСПЛАТНЫЙ ТЕЛЕФОН',
  DISCOUNT: 'скидка',
  DISCOUNTED_PHONE: 'телефон со скидкой',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'от общей суммы купленного телефона',
  LIMITED_TIME_OFFER: 'Предложение с ограниченным сроком действия',
  PROMOTION: 'Промоакция',
  ZANG_SPACES_PROMOTION: 'Акционные предложения Zang Spaces',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Перейти к выбору номера',
  DURATION: 'Продолжительность',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'Поздравляем! Вы получаете кредит <strong>{amount}</strong> на общую сумму заказанных устройств.',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'Все применимые скидки будут учтены в итоговой сумме заказа.',
  SHIPPING_TYPE: 'Тип доставки',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'Данные для отслеживания заказа будут отправлены, как только заказанные изделия будут отгружены со склада',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Получите {amount} на пользователя на покупку любого устройства. Предложение с ограниченным сроком действия.',
  PARTNER_ORDERS: 'Заказы партнеров',
  COMMISSION: 'Комиссия',

  ADDITIONAL_DEVICES: 'Дополнительные устройства',
  NO_USER: 'Нет пользователя',
  QUANTITY: 'Количество',
  BUY_DEVICES: 'Купить устройства',
  DEVICE: 'Устройство',
  PRICE: 'Цена',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: 'Введите не менее {chars} символов для поиска агента',
  NO_RESULTS_FOUND: 'Ничего не найдено',
  RESULTS_COULD_NOT_BE_LOADED: 'Не удалось загрузить результаты',
  CLEAR_SELECTION: 'Снять выделение',


  RESET_ALL_PURCHASES: 'Очистить историю покупок',
  LISTS: 'Списки',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Введите номер телефона перед созданием предложения',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Введите данные для выставления счетов и доставки перед созданием предложения',
  CALCULATING_TAXES_PLEASE_WAIT: 'Расчет налоговых выплат. Подождите...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Платеж с помощью текущей кредитной карты отклонен.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Платеж с помощью кредитной карты отклонен. Используйте другую карту.',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'При оплате заказа произошла ошибка. Используйте другую карту.',
  INVALID_CREDIT_CARD: 'Кредитная карта недействительна',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type} не совпадает с адресом, указанным в данных кредитной карты',
  INVALID_SECURITY_CODE: 'Недопустимый код безопасности (CVC)',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Скидки и рекламные цены включены в счет.',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'Не удалось создать учетную запись клиента. Повторите попытку',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Не удалось добавить кредитную карту. Повторите попытку',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Эта кредитная карта используется для обновления подписки.',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Ошибка при назначении кредитной карты по умолчанию.',
  DEFAULT: 'По умолчанию',
  SET_DEFAULT: 'Назначить по умолчанию',
  SALES_FORCE_QUOTE_ID: 'ИД предложения Salesforce',
  SALES_FORCE_ORDER_ID: 'ИД заказа Salesforce',
  SALES_FORCE_OPPORTUNITY_ID: 'ИД возможности Salesforce',
  SALES_FORCE_CONTACT_ID: 'ИД контакта Salesforce',
  SALES_FORCE_CONTRACT_ID: 'ИД контракта Salesforce',
  SALES_FORCE_ACCOUNT_ID: 'ИД учетной записи Salesforce',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Просто щелкните "Добавить устройство" и свяжите это устройство с пользователем.',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Просто щелкните "Добавить устройство" и свяжите это устройство с пользователем.',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Купите дополнительные устройства для вашей учетной записи Zang Office',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'Ой! Что-то не так с вашим заказом. Обновите страницу и создайте новый заказ.',
  CREATE_A_NEW_COMPANY: 'Создать новую компанию',
  ADD_A_NEW_COMPANY: 'Добавить новую компанию',
  PARTNER_DETAILS: 'Сведения о партнере',
  AGENTS: 'Агенты',
  PARTNER_PORTAL: 'Портал для партнеров',
  AGENT: 'Агент',
  AGENT_PORTAL: 'Портал для агентов',
  NO_AGENTS_FOUND: 'Агенты не найдены',
  NO_AGENT: 'Нет агентов',
  RELATION: 'Отношение',
  OWNER: 'Владелец',
  ADMIN: 'Администратор',
  MANAGER: 'Менеджер',
  EMPLOYEE: 'Сотрудник',
  ACTIVE: 'Активный',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: 'Один из партнеров, с которым вы связаны',
  APPLIED_ON: 'Применено',
  JOIN_A_PARTNER: 'Присоединиться к партнеру',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: 'Вы почти присоединились к <b>{COMPANY_NAME}</b>',
  JOIN_PLACEHOLDER_NOW: 'Присоединиться к {COMPANY_NAME} прямо сейчас',
  UPDATE_AGENT_INFO: 'Обновить данные агента',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: 'Начать работу с Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'Совместно с Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: 'Простое, производительное, унифицированное решение для совместной работы',
  IP_OFFICE_DONT_PAY_TILL: 'Оплата не требуется до 15 апреля 2018 г.',
  LOGIN: 'Войти в систему',
  DISCOVER: 'Обнаружение',
  SOLUTIONS: 'Решения',
  SERVICES: 'Службы',
  INDUSTRIES: 'Сферы деятельности',
  CASE_STUDIES: 'Примеры использования',
  PROGRAMS_AND_PROMOTIONS: 'Программы и акции',
  AUTHENTIC_AVAYA: 'Authentic Avaya',
  PERSPECTIVES: 'Перспективы',
  AVAYA_CONNECTED_BLOG: 'Блог Avaya Connected',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: 'Поиск решений',
  INFO_FOR: 'Информация для',
  DEVELOPERS: 'разработчиков',
  CHANNEL_PARTNERS: 'партнеров по каналу',
  TECHNOLOGY_PARTNERS: 'партнеров по технологиям',
  CONSULTANTS: 'консультантов',
  INVESTORS: 'инвесторов',
  MEDIA_ANALYSTS: 'медиа-аналитиков',
  SUPPLIERS: 'поставщиков',
  CONNECT_WITH_US: 'Присоединяйтесь к нам',
  FIND_A_CHANNEL_PARTNER: 'Найти партнера по каналу',
  FIND_A_TECHNOLOGY_PARTNER: 'Найти партнера по технологиям',
  EXECUTIVE_BRIEFING_CENTER: 'Центр совещаний для руководителей',
  AVAYA_LEARNING_SERVICES: 'Образовательные службы Avaya',
  CONTACTS: 'Контакты',
  ABOUT_AVAYA: 'О компании Avaya',
  EVENTS: 'События',
  NEWSROOM: 'Новости',
  INVESTOR_RELATIONS: 'Отношения с инвесторами',
  CORPORATE_RESPONSIBILITY: 'Корпоративная ответственность',
  OUR_COMPANY: 'Наша компания',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'Международная группа пользователей Avaya — IAUG',
  CAREERS: 'Вакансии',
  YOUR_PERSONAL_LINK: 'Ваша персональная ссылка',
  SITEMAP: 'Карта сайта',
  TERMS_OF_USE: 'Условия использования',
  PRIVACY: 'Конфиденциальность',
  COOKIES: 'Файлы cookie',
  AVAYA_INVOICE: 'Счет',
  IP_OFFICE_ACCOUNT_NAME: 'Имя учетной записи Avaya Cloud',
  IP_OFFICE_PLAN_NUMBER: 'Номер плана Avaya Cloud',
  IP_OFFICE_PHONE_APPLICATION: 'Софтфон Avaya Cloud Solutions',
  IP_OFFICE_PHONE_DESCRIPTION: 'Софтфон Avaya Cloud Solutions предоставляет пользователям простой доступ ко всем каналам связи через единый интерфейс. Софтфон Avaya Cloud Solutions позволяет выполнять вход в Avaya Cloud Solutions, выполнять и принимать голосовые и видеовызовы с внутреннего номера стационарного телефона через ПК. Софтфон входит в стоимость подписок Avaya Cloud Solutions для пользователей со стандартными и расширенными правами.',
  PLAN_MONTH_1_MONTH_1: 'Месячный план (без кредитных средств)',
  PLAN_YEAR_1_MONTH_1: 'Годовой план | С ежемесячным выставлением счетов',
  PLAN_YEAR_1_YEAR_1: 'Годовой план, с полной единовременной оплатой',
  PLAN_YEAR_2_MONTH_1: 'Двухлетний план | С ежемесячным выставлением счетов',
  PLAN_YEAR_2_YEAR_1: 'Двухлетний план | С ежегодным выставлением счетов',
  PLAN_YEAR_2_YEAR_2: 'Двухлетний план, с полной единовременной оплатой',
  PLAN_YEAR_3_MONTH_1: 'Трехлетний план | С ежемесячным выставлением счетов',
  PLAN_YEAR_3_YEAR_1: 'Трехлетний план | С ежегодным выставлением счетов',
  PLAN_YEAR_3_YEAR_3: 'Трехлетний план, с полной единовременной оплатой',
  PLAN_YEAR_5_MONTH_1: 'Пятилетний план | С ежемесячным выставлением счетов',
  ACCORDING_TO_PLAN: 'В соответствии с выбранным планом',
  TOTAL_USER_PLAN_FEE: 'Суммарные выплаты по плану пользователя',
  HEALTHCARE_DENY_MESSAGE: 'Благодарим за выбор решений Avaya Cloud. К сожалению, в настоящее время наши продукты не отвечают требованиям HIPAA, а это значит, что мы не можем предоставлять вам услуги, так как вы работаете в области здравоохранения. Мы обязательно сообщим вам о прохождении сертификации и надеемся, что после этого вы вернетесь к нашим продуктам. Если у вас есть вопросы, обратитесь по адресу <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a>.',
  SELECT_YOUR_IP_OFFICE_DEVICES: 'Выберите устройства для Avaya Cloud Solutions<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  SELECT_YOUR_IP_OFFICE_NUMBER: 'Выберите номер для Avaya Cloud Solution<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: 'Настройте пользователей и назначьте им устройства.',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: 'Добавьте номер телефона, который вы хотите использовать для Avaya Cloud Solutions.',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: 'Назначьте номер телефона для вашего решения.',
  INVITE_A_NEW_AGENT: 'Пригласить нового агента',
  I_WANT_TO_INVITE_A: 'Я хочу пригласить',
  CONTACT_EMAIL: 'Электронная почта контакта',
  CONTACT_NAME: 'Имя контакта',
  COMPANY_NAME: 'Название компании',
  CONTACT: 'Контакт',
  COMPANY_IS_INCORPORATED: 'Компания является корпорацией',
  INDIVIDUAL: 'Физическое лицо',
  INDIVIDUALS: 'Физические лица',
  SEND_INVITATION_EMAIL: 'Отправить приглашение по электронной почте',
  SENDING_INVITATION_EMAIL: 'Отправка приглашения по электронной почте...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: 'Приглашение отправлено успешно',
  ALL_FIELDS_ARE_REQUIRED: 'Все поля являются обязательными',
  PARTNER_NOT_FOUND: 'Партнер не найден',
  SALE_AGENT_REGISTRATION: 'Регистрация торговых агентов',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: 'Просто заполните форму внизу, чтобы стать торговым агентом',
  VIEW: 'ПРОСМОТРЕТЬ',
  COMPANIES: 'Компании',
  ADD_A_PARTNER: 'Добавить партнера',
  ADD_PARTNER: 'Добавить партнера',
  PARTNERS_PERSONAL_LINK: 'Персональная ссылка партнера',
  MASTER_SALES_AGENT: 'Главный агент по продажам',
  AVAYA_J129_LABEL: 'IP-телефон J129',
  AVAYA_J129_DESCRIPTION: 'Вы получаете все необходимые средства для обработки вызовов в многофункциональном SIP-телефоне по приемлемой цене. Телефон предоставляет ключевые функции, необходимые пользователям в организациях любого размера. В телефоне предусмотрены два представления вызова, а вызов отображается на одной строке. Купите надежный телефон, который превосходит все доступные аналоги.',
  AVAYA_J169_LABEL: 'IP-телефон J169',
  AVAYA_J169_DESCRIPTION: 'Вы получаете все необходимые средства для обработки вызовов в многофункциональном SIP-телефоне по приемлемой цене. Телефон предоставляет ключевые функции, необходимые пользователям в организациях любого размера. В телефоне предусмотрены два представления вызова, а вызов отображается на одной строке. Купите надежный телефон, который превосходит все доступные аналоги.',
  AVAYA_J179_LABEL: 'IP-телефон J179',
  AVAYA_J179_DESCRIPTION: 'Вы получаете все необходимые средства для обработки вызовов в многофункциональном SIP-телефоне по приемлемой цене. Телефон предоставляет ключевые функции, необходимые пользователям в организациях любого размера. В телефоне предусмотрены два представления вызова, а вызов отображается на одной строке. Купите надежный телефон, который превосходит все доступные аналоги.',
  AVAYA_K175_LABEL: 'Avaya Vantage™ K175',
  AVAYA_K175_DESCRIPTION: 'Вы получаете все необходимые средства для обработки вызовов в многофункциональном SIP-телефоне по приемлемой цене. Телефон предоставляет ключевые функции, необходимые пользователям в организациях любого размера. В телефоне предусмотрены два представления вызова, а вызов отображается на одной строке. Купите надежный телефон, который превосходит все доступные аналоги.',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: 'Стационарный IP-телефон 9641GS',
  AVAYA_9641G_DESCRIPTION: 'Avaya 9641GS — это многолинейный стационарный телефон премиум-класса, предназначенный для работников, которые проводят много времени у телефона и заинтересованы в применении средств интеллектуальной связи и повышения производительности. 9641GS оборудован 5-дюймовым цветным дисплеем, большим сенсорным экраном и обеспечивает звук высокой четкости. Благодаря широкополосному аудиокодеку звук исключительного качества доступен во всех интерфейсах, включая трубку, гарнитуру и динамик.',
  AVAYA_9608G_LABEL: 'Стационарный IP-телефон 9608G',
  AVAYA_9608G_DESCRIPTION: 'Стационарный телефон 9608G представляет собой экономичное полнофункциональное устройство с гигабитным подключением и встроенным монохромным дисплеем. Питание через порт Ethernet упрощает развертывание, а широкополосный аудиокодек обеспечивает звук исключительного качества. Телефон подходит для предприятий любого размера и предоставляет доступ к восьми линиям и графическим меткам с централизованным администрированием.',
  AVAYA_9611G_LABEL: 'Стационарный IP-телефон 9611G',
  AVAYA_9611G_DESCRIPTION: 'Телефон 9611G включает гигабитное подключение и интерфейс USB. В его 3,5-дюймовом цветном дисплее предусмотрены белая подсветка и графические метки с централизованным администрированием. Питание через порт Ethernet упрощает развертывание, а широкополосный аудиокодек обеспечивает звук исключительного качества.',
  AVAYA_PHONE_B179_LABEL: 'SIP-телефон для конференц-связи B179',
  AVAYA_PHONE_B179_DESCRIPTION: 'Протестированный Tolly, SIP-телефон для конференц-связи с гибкой конфигурацией обеспечивает чистое, естественное звучание благодаря запатентованной Avaya технологии широкополосного аудио OmniSound 2.0. Телефон оснащен интеллектуальными функциями для повышения эффективности конференц-вызовов. Организатор конференций позволяет вызывать предварительно заданные группы. Оцените удобный импорт и экспорт сведений о контактах через веб-интерфейс. Создайте собственный список контактов с помощью функции персонального профиля пользователя.',
  HAVE_LARGE_NUMBERS_OF_USERS: 'Много пользователей?',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: 'У нас предусмотрена система скидок для крупных заказов.',
  DEVICE_FEE: 'Стоимость подписки для одного устройства',
  UP_TO_DEVICE_CREDITE_PER_USER: 'До {$} кредитных средств на одного пользователя',
  PROMOTION_REMAINING_DETAIL_INFO: 'У вас осталось еще <b>{0}</b> кредитных средств, которые могут быть потрачены в рамках рекламной акции. Обратите внимание, что после совершения покупки у вас не останется кредитных средств и их нельзя будет использовать в учетной записи при совершении покупок в будущем.',
  VIEW_USER_FEATURES: 'Просмотреть свойства пользователя',
  FREE_DEVICES_PER_USER_INFO: '{0} (до {1} кредитных средств на одного пользователя)',
  VALUE_OF_DEVICE_CREDIT: '{0} пользователей = всего {0} кредитных средств',
  PROMOTION_DELAYED_BILLING_INFO: 'Рекламная акция: вы получите подробные квитанции, а с вашей кредитной карты будут списаны средства в счет погашения задолженностей в момент установленного начала периода оплаты.',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: 'Выберите агента, чтобы выполнить заказ',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: 'Введите действительное доменное имя (example.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: 'Ваша система Avaya Cloud Solution готова.',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: 'Ваша система Avaya Cloud Solution настроена.',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Номер телефона Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Доменное имя SIP Avaya Cloud Solutions',
  IP_OFFICE_SIP_DOMAIN_ID: 'Идентификатор домена SIP Avaya Cloud Solutions',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: 'Выполняется настройка вашей системы Avaya Cloud Solution.',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: 'Благодарим за размещение заказа. В настоящее время мы настраиваем вашу систему Avaya Cloud Solutions и свяжемся с вами после завершения настройки. <br /> Если у вас есть вопросы, обратитесь в службу поддержки Avaya Cloud Solutions по адресу {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: 'Не удалось подготовить эту учетную запись',
  ERROR_CODE: 'Код ошибки',
  ERROR_MESSAGE: 'Сообщение об ошибке',
  ADMIN_PORTAL_LINK: 'Ссылка на портал для администраторов',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Пароль пользователя Avaya Cloud Solutions по умолчанию',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Временный номер телефона Avaya Cloud Solutions',
  IP_OFFICE_BASIC_EXTENSION_RANGE: 'Расширения базового пользователя',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: 'Расширения стандартного пользователя',
  IP_OFFICE_POWER_EXTENSION_RANGE: 'Расширения ключевого пользователя',
  IP_OFFICE_DEFAULT_USER_PIN: 'ПИН пользователя по умолчанию',
  IP_OFFICE_SAME_AS_PIN: 'Совпадает с внутренним номером (например, 200)',
  IP_OFFICE_ORDERID: 'Идентификатор заказа Avaya Cloud Solutions',
  IP_OFFICE_HOST_NAME: 'Имя хоста Avaya Cloud Solutions',
  IP_OFFICE_IP_ADDRESS: 'IP-адрес Avaya Cloud Solutions',
  IP_OFFICE_SUBSCRIPTIONID: 'Идентификатор подписки Avaya Cloud Solutions',
  CALCULATING: 'вычисление...',
  RESET_ALL_PARTNERS: 'Очистить данные партнера',
  ERROR_GETTING_AGENTS: 'Ошибка при проверке агентов. Повторите попытку',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'В вашей рабочей группе уже есть агент с таким адресом электронной почты',
  AUTO_APPROVE_ACTIVATE_AGENT: 'Автоматическое утверждение/активация агента',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: 'В вашей рабочей группе уже есть компания с таким адресом электронной почты',
  MASTER_SALES_AGENT_PORTAL: 'Портал для главных агентов по продажам',
  SALES_AGENT_PORTAL: 'Портал для агентов по продажам',
  E911_ADDRESS: 'Адрес экстренных служб',
  OVERVIEW: 'Обзор',
  ADD_COMPANY_OR_SALES_AGENT: 'Добавить компанию или агента',
  ADD_AN_AGENT: 'Добавить агента в',
  INACTIVE: 'Неактивный',
  AGENTS_PERSONAL_CONNECTION_LINK: 'Персональная ссылка агента для подключения',
  PURCHASE_DATE_AND_CUSTOMER: 'Дата покупки и клиент',
  ORDER_DETAILS: 'Сведения о заказе',
  SELECT_AGENT: 'Все агенты',
  FROM: 'от',
  TO: 'кому',
  EXPORT_REPORT: 'Экспорт отчета',
  NO_SALES_FOUND: 'Продажи не найдены',
  ADD_A_COMPANY: 'Добавить компанию',
  AUTO_APPROVE_COMPANY: 'Автоматическое утверждение компании',
  AUTO_ACTIVATE_AGENT: 'Автоматическая активация агента',
  ADD_COMPANY: 'Добавить компанию',
  ADD_COMPANY_NAME_AGENT_ADMIN: 'Добавить агента/администратора {COMPANY_NAME}',
  ADD_AGENT_ADMIN: 'Добавить агента/администратора',
  ALL_COMPANIES: 'Все компании',
  START_DATE: 'Дата начала',
  HEY: 'Приветствуем!',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: 'Мы — команда специалистов по работе с клиентами. Мы поможем вам извлечь максимум из решения Avaya Cloud Solutions. В вашем распоряжении также находится команда технических специалистов (<a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>).',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: 'Мы хотели бы назначить время пробного звонка в один из ближайших дней, чтобы познакомиться с вами и завершить процедуру настройки вашей системы. <strong>Свяжитесь с нами по адресу <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a>, чтобы обговорить дату и время пробного звонка, который займет около часа.<strong>',
  START_USING_YOUR_IP_OFFICE: 'Начните использовать вашу систему Avaya Cloud Solutions прямо сейчас!',
  BELOW_ARE_DETAILS: 'Далее приведена информация о вашей системе, учетные данные пользователей и ссылки на скачивание приложений:',
  YOUR_IP_OFFICE_INFO: 'Информация о системе:',
  LOGIN_INFO_TABLE: 'Таблица с данными пользователей:',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: 'Все ваши пользователи могут вносить изменения в свои данные, настраивать параметры переадресации вызовов, прослушивать голосовые сообщения и выполнять другие действия с использованием приведенной далее информации после входа на собственные порталы пользователей Cloud.',
  AVAILABLE_APPLICATIONS_FOR_USERS: 'Приложения, доступные вашим пользователям:',
  DO_NOT_HESITATE_TO_EMAIL_US: 'Если у вас есть вопросы, не раздумывая пишите нам по адресу <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a>.',
  THANK_YOU: 'Спасибо.',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web (расширение Chrome)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions Soft Console (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">Документация по установке</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">Документация по установке</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">Документация по установке</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">Документация по установке</a>',




  USER_NAMES_COLUMN: 'Имя пользователя',
  EXTENSIONS_COLUMN: 'Внутренний номер',
  TEMP_PIN_COLUMN: 'Прикрепить',
  TEMP_PASSWORD_COLUMN: 'Пароль',
  USER_TYPE_COLUMN: 'Тип пользователя',
  DEVICE_MODEL_COLUMN: 'Устройство',
  POWER_USER: 'Расширенный',
  STANDARD_USER: 'Стандарт',
  BASIC_USER: 'Базовый',
  ORDERID: 'Идентификатор заказа',
  ACCOUNT_NAME: 'Имя учетной записи',
  HOST_NAME: 'Имя хоста',
  ADMIN_PORTAL: 'Портал для администраторов',
  IP_ADDRESS: 'IP-адрес',
  PHONE_NUMBER: 'Номер телефона',
  TEMPORARY_PHONE_NUMBER: 'Временный номер телефона',
  EXCITING_TIMES_AHEAD: 'Впереди много интересного',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: 'Доменное имя {DOMAIN_NAME} недействительно или используется другой компанией.',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: 'Доменное имя {1} недействительно или используется другой компанией.',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: 'Не удалось выполнить проверку компании. Повторите попытку',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: 'Если какие-либо данные недоступны, обратитесь в службу поддержки Avaya Cloud: ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Не удалось начать подготовку учетной записи Avaya Cloud',
  LEGAL: 'Юридическая информация',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Выберите годовой (или более продолжительный) план и получите кредитные средства на каждого пользователя для покупки любого устройства. Срок действия предложения ограничен.',
  USER_PORTAL: 'Портал для пользователей',
  E_911: 'Экстренные вызовы',
  DECLINE: 'Отклонить',
  ACCEPT: 'Принять',
  PRINT: 'Печать',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: 'Примите все вышеперечисленные условия, чтобы завершить оформление заказа',
  ASSING_A_DEVICE_TO_YOUR_USERS: 'Назначьте устройство для ваших пользователей.',
  SELECT: 'Выбрать',
  USER_DETAILS: 'Сведения о пользователе',
  DEVICE_DETAILS: 'Сведения об устройстве',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: 'Внимательно прочитайте и примите условия предоставления услуг.',
  PARTNER_ORDERS_RECORDS_HINT: '*Все записи, касающиеся продаж, приведены только для справки. Официальные и окончательные отчеты по продажам будут предоставлены финансовым отделом Avaya в соответствии с соглашением, которое было заключено с главным агентом по продажам.',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: 'Выберите агента по продажам, чтобы создать предложение',
  COMPANY_DETAILS: 'Сведения о компании',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: 'Плюс применимые налоговые сборы.',
  SELECT_PRODUCT: 'Выберите продукт',
  CLOUD_UC_SMALL_MONTH1: 'Базовый пакет Cloud UC с ежемесячным выставлением счетов',
  SMALL: 'Маленький',
  CLOUD_UC_SMALL_MONTH12: 'Базовый пакет Cloud UC с годовым тарифным планом',
  CLOUD_UC_SMALL_3YEARS: 'Базовый пакет Cloud UC с трехлетним тарифным планом',
  CLOUD_UC_SMALL_5YEARS: 'Базовый пакет Cloud UC с пятилетним тарифным планом',
  MEDIUM: 'Средний',
  CLOUD_UC_MEDIUM_MONTL1: 'Пакет Cloud UC для бизнеса с ежемесячным выставлением счетов',
  CLOUD_UC_MEDIUM_MONTH12: 'Пакет Cloud UC для бизнеса с годовым тарифным планом',
  CLOUD_UC_MEDIUM_3YEARS: 'Пакет Cloud UC для бизнеса с трехлетним тарифным планом',
  CLOUD_UC_MEDIUM_5YEARS: 'Пакет Cloud UC для бизнеса с пятилетним тарифным планом',
  LARGE: 'Крупный',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC для крупных компаний с оплатой текущих расходов',
  CLOUD_UC_LARGE_MONTL12: 'Cloud UC для крупных компаний с ежегодной оплатой',
  CLOUD_UC_SMALL_SHORT_INFO: '1–99 сотрудников',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100–999 сотрудников',
  CLOUD_UC_LARGE_SHORT_INFO: '1000+ сотрудников',
  SELECTED: 'Выбранный',
  BASIC_PHONE_SERVICE: 'Базовая телефонная служба',
  UNLIMITED_NATIONAL_WIDE: 'Неограниченные междугородные вызовы по всей стране',
  STANDARD_FEATURES: 'Стандартные функции',
  HOW_MANY_USERS: 'Сколько пользователей вам нужно?',
  ADD_ON_ADDITIONAL_FEATURES: 'Дополнительные функции',
  ONETIME_FEE: 'Однократное внесение средств',
  RECURRING_FEE: 'Регулярное внесение средств',
  SELECT_MAIN_NUMBER: 'Выберите главный номер',
  TOLL_FREE: 'Бесплатный номер',
  LOCAL_NUMBER: 'Местный номер',
  TRANSFER_NUMBER: 'Номер для перевода вызовов',
  USERS_COUNT: 'Пользователей: {qty}',
  DEVICES_COUNT: 'Устройств: {qty}',
  UC_OFFER_TITLE: 'У нас есть подходящее решение для вас!',
  UC_OFFER_DESCRIPTION: 'Каким бы ни был размер вашего бизнеса, у нас есть то, что вы ищете! Какое предприятие вы представляете?',

  // 'BASIC_PHONE_SERVICE': 'Базовая телефонная служба',

  TAX_CALC_ERROR_MSG: 'Не удалось рассчитать налог. Проверьте адрес для выставления счетов.',
  'VIOLATION.FIELD_IS_EMPTY': '{1} является обязательным',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} — {2} является обязательным',
  'VIOLATION.FIELD_VALUE_INVALID': 'Недопустимое значение {1}',
  'VIOLATION.FIELD_VALUE_INVALID2': '{1} — {2} является недопустимым значением',
  'VIOLATION.TAX_CALCULATION_FAILED': 'Не удалось рассчитать налог',
  'VIOLATION.AGREE_ON_LEGAL_DOC': 'Прочитайте и примите "{1}"',
  'VIOLATION.CART_IS_EMPTY': 'Корзина пуста',
  'VIOLATION.CART_IS_TOO_BIG': 'В корзине слишком много товаров',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': 'Удален из корзины: {1}',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': 'Количество {1} изменено с {2} на {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': 'Скидка на {1} изменена с {2} на {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': 'Нельзя добавить товар с валютой {1} в корзину с валютой {2}',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': 'Правило скидки {1} не определено',
  'SALESMODELRULE.UNKNOWN_ERROR': 'Неизвестная ошибка',
  'SALESMODELRULE.INVALID_PARAMETER': 'Недопустимый параметр: {1}',
  ONE_TIME: 'Однократная',
  ADDON_PRICING_HINT: '*Цены на дополнения указаны для одного рабочего места и применимы ко всем пользователям. Добавить конкретные дополнения пользователям можно после совершения покупки на портале для администраторов.',
  ADD_TO_CART_HINT: 'Выполните указанные выше шаги, чтобы добавить товар в корзину',
  ITEM_UNITS: 'Единиц: {qty}',
  ADDONS_COUNT: 'Дополнений: {qty}',
  ADDON_COUNT: 'Дополнений: {qty}',
  MULTIPLE_TYPES: 'Разные типы',
  MIXED: 'Смешанный',
  FREE_PRICE: 'БЕСПЛАТНЫЙ',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'Базовый пакет UC',
  UC_ESSENTIALS_DESCRIPTION: 'Лучшие облачные средства связи для бизнеса любого размера.',
  UC_BUSINESS: 'Пакет UC для бизнеса',
  UC_BUSINESS_DESCRIPTION: 'Первоклассные корпоративные средства связи в облачной среде для вашей компании',
  UC_BUSINESS_POWER_PACKAGE: 'Обновление до КЛЮЧЕВЫХ пользователей',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>Прямой номер телефона:</strong> выделенный, уникальный номер, чтобы клиенты могли звонить вам, а не на главный номер вашей компании или номер ресепшн (виртуальный или физический).</li><li><strong>Прямые видеовызовы:</strong> включайте видео в двусторонних телефонных разговорах.</li><li><strong>Интеграция с Salesforce©:</strong> многофункциональные средства связи для конечных пользователей в среде Salesforce.</li><li><strong>Интеграция с Google©:</strong> связь в реальном времени через браузер Google Chrome и любые приложения Google.</li><li><strong>Интеграция со Skype for Business©:</strong> современные, оптимизированные и простые в использовании средства для совместной работы в Skype for Business.</li></ul>',
  SHOW_MORE: 'Показать еще',
  HIDE: 'Скрыть',
  VIEW_COMPLETE_FEATURE_LIST: ' Просмотреть полный список функций',
  FILTER_BY: 'Фильтрация по',
  UC_OFFERS: 'Решения UC',
  PAY_MONTHLY: 'Ежемесячное внесение оплаты',
  PAY_ANNUALLY: 'Ежегодное внесение оплаты',
  COMING_SOON: 'Скоро',
  TAX_CALC_ERROR_MSG: 'Не удалось рассчитать налог. Проверьте адрес.',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: 'Введите название страны для просмотра текущих тарифов на междугородные вызовы.',
  LONG_DISTANCE_RATE_NOT_FOUND: 'Тарифы на междугородные вызовы в этой стране не найдены. Для получения информации обратитесь по адресу {CUSTOMER_SUCCESS_EMAIL}.',
  AREA_CODE: 'Междугородный код',
  INVALID_CREDIT_CARD_ZIP: 'Кредитная карта не совпадает с почтовым индексом.',
  VIEW_LONG_DISTANCE_RATES: 'Просмотреть тарифы на междугородные вызовы',
  LONG_DISTANCE_SUBTITLE_TEXT: 'Благодаря нашим низким тарифам на междугородные вызовы вы будете оставаться на связи с вашими партнерами по всему миру.',
  RATES_SUBJECT_TO_CHANGE: '*Тарифы могут быть изменены без уведомления.',
  CREDIT_CARD_DECLINED: 'Кредитная карта отклонена.',
  ENTER_COUNTRY_NAME: 'Введите название страны',
  ADD_TO_CART: 'Добавить в корзину',
  UPDATE_CART: 'Обновить корзину',
  PER_USER: 'На пользователя',
  COMPARE_UC_OFFERS: 'Сравнить предложения UC',
  PROCEED_TO_CHECKOUT: 'Оформить заказ',
  BEFORE_APPLICABLE_TAXES: '*Без налоговых выплат',
  YEAR_PLAN: 'Годовой тарифный план',
  YEARS_PLAN: 'Тарифный план на {0} г.',
  MONTHS_PLAN: 'Тарифный план на {0} мес.',
  ENTER_NUMBER_OF_USERS: 'Введите предполагаемое количество пользователей этого решения',
  YEAR: 'Год',
  BILLED_MONTH: 'Ежемесячное выставление счетов',
  COMPANY_INCORPORATED: 'Является корпорацией',
  COMPANY_NOT_INCORPORATED: 'Не является корпорацией',
  EXISTING_CONFIG_WARNING: 'У вас есть готовая конфигурация <br/><b>{0}</b>.',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: 'Сбросить текущую конфигурацию?',
  DISCARD_MY_CONFIGURATION: 'Сбросить мою конфигурацию',
  DISCARD: 'Сбросить',
  EDIT_MY_CONFIGURATION: 'Редактировать мою текущую конфигурацию',
  CONTINUE: 'Продолжить',
  SELECT_A_PLAN: 'Выбрать план',
  PROMOTION_DETAIL_INFO: '*Вы выбрали <b>{0} пользователей</b>.<br/> Это эквивалентно <b>{1}</b> кредитным средствам.',
  BILLED_MONTH_FREQUENCY: 'Выставление счетов раз в {0} мес.',
  BILLED_YEAR_FREQUENCY: 'Выставление счетов раз в {0} г.',
  CONTACT_OUR_CUSTOMER_CARE: 'Свяжитесь с нашими специалистами по работе с клиентами',
  NEED_HELP_INFO: 'Нужна помощь? Наши специалисты по работе с клиентами всегда готовы помочь в решении ваших вопросов и проблем и могут предоставить необходимую информацию.',
  REMOVE: 'Удалить',
  REMOVE_ITEM_FROM_CART_WARNING: 'Удалить <b>{0}</b> из корзины?',
  NO_ITEM_IN_THE_CART: 'В вашей корзине нет товаров.',
  CONTINUE_SHOPPING: 'Продолжить покупки',
  TOTAL_TAXES: 'Итоговые налоговые выплаты',
  UC_SOLUTIONS: 'Решения UC',
  UNIFIED_COMMUNICATIONS: 'Unified Communications',
  ADD_ONS: 'Дополнения',
  SYSTEM_ADDONS: 'Дополнения системы',
  ADD_DEVICES: 'Добавить устройства',
  SELECT_UPTO_DEVICES: 'Выберите до (<b>{0}</b>) устройств для <b>{1}</b>',
  DONE: 'Готово',
  SELECT_DEVICES: 'Выберите устройства',
  EDIT_DEVICE_SELECTION: 'Редактировать устройства',
  ESSENTIAL_USERS: 'Базовые пользователи',
  BUSINESS_USERS: 'Бизнес-пользователи',
  POWER_USERS: 'Ключевые пользователи',
  N_A: 'Н/Д'
}
