export default {
  PHONE_TYPES: 'Типы телефонов',
  IMAGINE_A_BETTER_WAY: 'Новый подход',
  OF_DOING_THINGS: 'к привычному.',
  GET_STARTED: 'Начало работы',
  PURCHASE: 'Покупка',
  DOWNLOADS_AND_EXTENSIONS: 'Загрузки и расширения',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS:'Весь арсенал средств в специальных надстройках и дополнениях Zang.',
  ALL: 'Все',
  REFERRAL_AGENT: 'Полномочный представитель',
  SALES_AGENT: 'Агент по продажам',
  CART: 'Корзина',
  PARTNER_PROGRAMS: 'Партнерские программы',
  HOME: 'Главная',
  MANAGE_CREDIT_CARDS: 'Управление кредитными картами',
  MY_PROFILE: 'Мой профиль',
  MY_SETTINGS: 'Мои настройки',
  MY_PARTNER_PORTAL: 'Портал для партнеров',
  CLEAR_ZANG_OFFICE: 'Удалить Zang Office',
  CLEAR_ZANG_SPACES: 'Удалить Avaya Spaces',
  FEATURE_BREAKDOWN: 'Разбиение функции',
  PLAN_BREAKDOWN: 'Информация о плане', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: 'Оптимальный телефон для бизнеса по привлекательной цене',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: 'Представьте все возможности Avaya Spaces',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'Скидка 50% будет применена к итоговой сумме после оформления заказа',
  HURRICANE_HARVEY_MESSAGE: 'Avaya и Zang желают помочь компаниям, которые пострадали от ураганов Харви и Ирма. Пострадавшие компании из Техаса, Луизианы, Флориды, Алабамы, Джорджии, Северной и Южной Каролины, Теннесси и Миссисипи могут уже сейчас <b>получить 3 месяца пользования Zang Office</b> и <b>Avaya Spaces БЕСПЛАТНО</b>.',
  LEARN_MORE: 'Дополнительные сведения',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'УСТРОЙСТВО AVAYA VANTAGE™ ТЕПЕРЬ ДОСТУПНО',
  NEW: 'НОВИНКА!',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: 'Раскройте все возможности Zang Office — удобный покрытый стеклом телефон для голосовой связи, видеосвязи и чатов.',
  LOG_IN: 'Войти',
  SIGN_UP: 'Зарегистрироваться',
  SIGN_OUT: 'Выйти',
  SIGN_IN: 'Войти', //login to the system, connect
  ADMINISTRATION: 'Администрирование',
  PRODUCTS: 'Продукты',
  ORDERS: 'Заказы',
  PAGES: 'Страницы',
  CUSTOMERS: 'Заказчики',
  USERS: 'Пользователи',
  PLANS: 'Тарифные планы',
  ZANG_OFFICE: 'Zang Office',
  CDRS: 'Подробная информация о вызовах',
  CDR_CHECKS: 'Проверки информации о вызовах',
  PARTNERS: 'Партнеры',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: 'Вы уже купили Zang Office. Вы больше не можете заказать Zang Office.',
  PARTNER_CONNECTIONS: 'Связь с партнерами',
  CHECK_OUT_GENERAL_FATAL_ERROR: 'При размещении заказа произошла ошибка. За дополнительной информацией обратитесь в службу поддержки Zang ({SUPPORT_EMAIL}).',
  APPLICATION_GENERAL_FATAL_ERROR: 'При отправке заявки произошла ошибка. За дополнительной информацией обратитесь в службу поддержки Zang ({SUPPORT_EMAIL}).',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: 'Для продолжения выберите по меньшей мере один тип пользователей.',
  BACK: 'Назад',
  SAVE_CHANGES: 'Сохранить изменения',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: 'Продолжить?',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: 'У вас кредит {PLACEHOLDER} на покупку любого устройства. Этот кредит будет потерян, как только ваш заказ будет подтвержден.',
  JUST_A_REMINDER: 'Напоминание',
  LAST_CHANCE: 'ПОСЛЕДНИЙ ШАНС',
  IM_GOOD_PLACE_MY_ORDER: 'Хорошо. Оформить заказ',
  BUY_MORE_DEVICES: 'Купить еще устройства',
  YES_PLACE_MY_ORDER: 'Да, оформить заказ',
  NO_THANKS: 'Нет, спасибо.',
  YES: 'Да',
  ABOUT_US: 'О компании',
  NEWS_AND_PRESS: 'Новости и публикации',
  CARREERS: 'Карьера',
  CONTACT_US: 'Свяжитесь с нами',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Спасибо за покупку! Ниже приведены сведения о заказе.',
  BLOG: 'Блог',
  FAQS: 'Часто задаваемые вопросы',
  DOCUMENTATION: 'Документация',
  TERMS_OF_SERVICE: 'Условия предоставления услуг',
  HELP: 'Справка',
  PRIVACY_STATEMENT: 'Заявление о конфиденциальности',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. Все права защищены.',
  PROCESSING: 'Обработка',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: 'Подождите. Этот процесс может занять какое-то время',
  OPEN_IN_A_NEW_TAB: 'Открыть в новой вкладке',
  GOT_IT: 'Готово!',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' Это действие может привести к следующим результатам:',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: 'Удаление месячной подписки на этот тарифный план',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: 'Отключение учетных записей на сторонних системах',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: 'Изменение статуса тарифного плана на «ОТКЛЮЧЕН»',
  LAST_ACTION_STEPS: 'Этапы выполнения последнего действия',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: 'Надстройки приобретаются через портал администратора Zang Office после создания учетной записи.',
  TYPE: 'Тип',
  ADMIN: 'Администратор',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: 'Этот пользователь будет выбран в качестве основного контакта/контакта для выставления счетов для корпоративной учетной записи. Его можно изменить в любое время на портале администратора Zang Office.',
  DESCRIPTION: 'Описание',
  SUCCESS: 'Успешно',
  REQUEST_CANCELATION: 'Отмена заявки',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: 'Жаль, что вы покидаете нас.',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Заполните форму ниже, чтобы начать отмену заявки. Чтобы все прошло без проблем, представитель нашей службы поддержки рассмотрит ваш запрос и свяжется с вами в течение 1–2 рабочих дней.',
  YOUR_NAME: 'Ваше имя',
  COMPANY: 'Компания',
  SERVICE: 'Служба',
  REASON_FOR_CANCELING: 'Причина отмены заявки',
  SUBMIT: 'Отправить',
  EXIT: 'Выход',
  REQUEST_SUBMITTED: 'Запрос отправлен.',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: 'Чтобы все прошло без проблем, представитель нашей службы поддержки рассмотрит ваш запрос и свяжется с вами в течение 1–2 рабочих дней.',
  DATE: 'Дата',
  PRODUCT: 'Продукт',
  USER: 'Пользователь',
  STATUS: 'Статус',
  ACTIONS: 'Действия',
  VIEW_DETAILS: 'Просмотреть дополнительные сведения',
  DISABLE: 'Отключить',
  ENABLE: 'Включить',
  CANCEL: 'Отмена',
  PLAN_DETAILS: 'Сведения о плане',
  SUMMARY: 'Общая информация',
  QUANTITIES: 'Объемы предоставления услуг',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '* Итоговая сумма отображает общую стоимость выбранных услуг плана',
  TOTAL: 'Всего',
  BILLED: 'К оплате',
  PLAN_INFORMATION: 'Сведения о плане',
  UPDATE_PLAN: 'Перейти на другой план',
  ADMIN_ACTIONS: 'Действия администратора',
  NAME_ON_CREDIT_CARD: 'Имя владельца кредитной карты',
  CREDIT_CARD_BRAND: 'Платежная система кредитной карты',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: 'Номер кредитной карты',
  EXPIRATION: 'Срок действия',
  MONTH: 'Месяц',
  YEAR: 'Год',
  SECURITY_CODE: 'Код безопасности',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: 'Код на обратной стороне кредитной карты',
  BACK_TO_CHECKOUT: 'Назад к оформлению заказа',
  ADD: 'Добавить',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: 'Для добавления кредитной карты воспользуйтесь формой ниже. Убедитесь, что заполнены все поля',
  NUMBER: 'Номер',
  EXPIRES: 'Действительна до',
  DELETE: 'Удалить',
  ITEM_DETAILS: 'Подробные сведения о покупке',
  FEE: 'Стоимость',
  ITEMS: 'Элементы',
  SEARCH_BY_CONFIRMATION: 'Поиск по подтверждению',
  CONFIRMATION: 'Подтверждение',
  CHECKOUT_STATUS: 'Статус оформления заказа',
  ORDER_STATUS_PROCESS: 'Обработка статуса заказа',
  CREATED_ON: 'Создано:',
  ORDER_SUMMARY: 'Сводка заказа',
  APPROVED: 'Утверждено', //example: partner application approved
  REJECTED: 'Отклонено', //example: partner application rejected
  PENDING: 'Ожидание', //example: partner application pending
  EDIT: 'Изменить',
  ONE_TIME_FEE: 'Одноразовая комиссия',
  SUB_TOTAL: 'Промежуточная сумма',
  TAXES: 'Налоги',
  CHANGES: 'Изменения',
  CREATE_A_QUOTE: 'Создать смету',
  EXTRA_INFORMATION: 'Дополнительные сведения',
  THANK_YOU_FOR_YOUR_ORDER: 'Благодарим за заказ!',
  ORDER_CONFIRMATION: 'Подтверждение заказа',
  INVALID_ORDER: 'Недействительный заказ',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: 'Не беспокойтесь, мы также отправили его по электронной почте :)',
  HELLO: 'Здравствуйте!',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: 'Спасибо за покупку! После отправки товаров мы отправим подтверждение. Ниже приведены сведения о заказе.',
  ACCOUNT_INFORMATION: 'Сведения о счете',
  BILLING_INFORMATION: 'Платежные реквизиты',
  SHIPPING_INFORMATION: 'Сведения для доставки',
  NAME: 'Имя',
  EMAIL: 'Электронная почта',
  SEARCH: 'Поиск',
  CLEAR: 'Очистить',
  PARTNER: 'Партнер',
  NO_PARTNERS_FOUND: 'Партнеры не найдены',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: 'Связь с партнером создается, когда покупатель переходит в магазин по ссылке, предоставленной партнером.',
  CUSTOMER: 'Заказчик',
  AGENT: 'Агент',
  NO_PARTNER_CONNECTIONS_FOUND: 'Не обнаружены контактные данные партнеров',
  I_HAVE_READ_AND_AGREE_WITH_THE: 'Прочитав, я принимаю',
  ZANG_PRIVACY_STATEMENT: 'заявление о конфиденциальности Zang',
  AGENT_PROGRAM_TERMS_OF_SERVICE: 'Условия предоставления услуг в рамках агентской программы',
  SUBMIT_APPLICATION: 'Отправить форму',
  SUBMITTING: 'Отправка',
  SUBMITTING_YOUR_APPLICATION: 'Отправка формы',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: 'По условиям предоставления услуг мы обязуемся обеспечивать сохранность и конфиденциальность банковской информации и сведений учетных записей.',
  BANK_NAME: 'Название банка',
  ADDRESS: 'Адрес',
  COUNTRY: 'Страна',
  SELECT_ONE: '- Выберите -',
  STATE_PROVINCE: 'Штат/область',
  CITY: 'Населенный пункт',
  ZIP_POSTAL_CODE: 'Почтовый индекс',
  ACCOUNT_NUMBER: 'Расчетный счет',
  BANK_NUMBER: 'Банковский номер',
  TRANSIT_NUMBER: 'Инкассовый код',
  SWIFT_CODE: 'Код SWIFT',
  TAX_REGISTRATION_NUMBER: 'Регистрационный номер налогоплательщика',
  SAVE_BANK_INFORMATION: 'Сохранить банковские реквизиты',
  SAVING_BANK_INFORMATION: 'Сохранение банковских реквизитов',
  NO_CUSTOMERS_FOUND: 'Заказчики не найдены',
  YOU_ARE_A: 'Вы ',
  A_DISCOUNT_OF: 'Скидка',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: 'будет применена к полной сумме после оформления заказа.',
  FIRST_NAME: 'Имя',
  LAST_NAME: 'Фамилия',
  COMPANY_NAME: 'Название компании',
  LEGAL_COMPANY_NAME: 'Наименование юридического лица',
  PHONE_NUMBER: 'Номер телефона',
  WEBSITE: 'Веб-сайт',
  OPERATIONAL_ADDRESS: 'Адрес осуществления деятельности',
  SAME_AS_ORGANIZATION_ADDRESS: 'Совпадает с юридическим адресом',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: 'Вы являетесь партнером Avaya?',
  NO: 'Нет',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Если да, введите идентификатор партнера Avaya',
  MY_PARTNER_PORTAL: 'Портал для партнеров',
  THANK_YOU_FOR_APPLYING: 'Спасибо за заявку!',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: 'Остался один шаг. Чтобы завершить оформление заявки на агента по продажам, перейдите по ссылке ниже и ответьте на все вопросы.',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' Если нет, сообщите ',
  PLEASE_GIVE: 'Сообщите',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: 'Если вы уже партнер Avaya, НЕ переходите по ссылке. <br />Мы проверим ваш ИД партнера и свяжемся с вами в ближайшее время.',
  BUSINESS: 'рабочих',
  DAYS: 'дн.',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: 'руководство рассмотрит вашу заявку.<br /> А пока все вопросы можно отправлять',
  COMPLETE_MY_APPLICATION: 'Завершить заявку',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: 'Мы рассмотрели вашу заявку. К сожалению, сейчас мы не можем включить вас в программу. Вряд ли причина серьезная, но пока мы с ней не разберемся, вы не можете стать нашим партнером. Понимаем, что эта новость может вас расстроить. Мы выясним, почему заявка отклонена, и свяжемся с вами. А пока вы можете обращаться',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: 'с любыми вопросами, касающимися данной процедуры.',
  CONGRATULATIONS: 'Поздравляем!',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: 'Теперь вы официальный агент Zang.',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: 'Поделитесь своей ссылкой со всеми потенциальными клиентами',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: 'и помогите им узнать, как лучше вести бизнес.',
  CHANGE_STATUS: 'Изменить статус',
  AGENT_DETAILS: 'Сведения об агенте',
  BANK_INFORMATION: 'Банковские реквизиты',
  THIS_ORDER_WAS_PLACED_BY_A: 'Этот заказ был принят',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: 'была вычтена из общей сумме',
  REFERRALS: 'Рефералы',
  SALES: 'Продажи',
  FOUND: 'Найдено',
  HOW_IT_WORKS: 'Принцип работы',
  WHAT_YOU_GET: 'Что вы получаете',
  SUPPORT: 'Поддержка',
  WHICH_PROGRAM_IS_BEST_FOR_ME: 'Какая программа больше всего подходит мне?',
  WHY_JOIN: 'Почему стоит присоединиться?',
  QUOTE: 'Предложение',
  PRINT_THIS_QUOTE: 'Распечатать это предложение',
  CLOSE_THIS_WINDOW: 'Закрыть это окно',
  SEARCH_BY_PLAN: 'Поиск по плану',
  ACCESS_LEVEL: 'Уровень доступа',
  DISPLAY_NAME: 'Отображаемое имя',
  INDUSTRY: 'Вид деятельности',
  CONTACT_PHONE_NUMBER: 'Контактный номер телефона',
  EMAIL_ADDRESS: 'Адрес электронной почты',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: 'Да, я хочу получать рассылку о новостях, приложениях, предложениях и мероприятиях Zang.',
  INFORMATION: 'Информация',
  ORDER_HISTORY: 'История заказов',
  FILTER: 'Фильтр',
  ACCOUNT: 'Учетная запись',
  AMOUNT_CHARGED: 'Сумма списания',
  DETAILS: 'Дополнительные сведения',
  NO_RECORDS_FOUND: 'Записи не найдены',
  CALL_LOGS: 'Журналы вызовов',
  EXPORT: 'Экспорт',
  CALLER_NAME: 'Имя абонента',
  DIALED_NUMBER: 'Набранный номер',
  DURATION_SEC: 'Длительность (с)',
  COST: 'Стоимость',
  CREDIT_CARD: 'Кредитная карта',
  SHIPPING_ADDRESS: 'Адрес доставки',
  SAME_AS_BILLING_ADDRESS: 'Совпадает с адресом для выставления счетов',
  SHIPPING_OPTIONS: 'Варианты доставки',
  FREE_SHIPPING: 'БЕСПЛАТНАЯ доставка',
  ADDITIONAL_NOTES: 'Дополнительные замечания',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: 'Прочитав, я соглашаюсь с приведенными ниже условиями:',
  EMERGENCY_911_SERVICE_NOTICE: 'Разъяснение по обслуживанию номеров экстренных служб',
  PLACE_MY_ORDER: 'Оформить заказ',
  CLEAR_MY_ORDER: 'Удалить заказ',
  PLACING_YOUR_ORDER: 'Оформление заказов',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: 'Подождите. Эта процедура может занять до 1 минуты.',
  YOUR_NEW_NUMBER: 'Ваш новый номер',
  NO_NUMBER_SELECTED: 'Номер не выбран',
  WELL_THAT_WAS_EASY: 'Это было несложно.',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: 'Еще чуть-чуть и готово :)',
  NEXT: 'Следующий',
  TITLE: 'Обращение',
  SUB_TITLE: 'Подзаголовок',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: 'Поиск по коду области... (только США и Канада)',
  SELECT_A_PREFIX: 'Выберите префикс',
  PICK_THIS_NUMBER: 'Приобрести этот номер',
  DEVICES: 'Устройства',
  BILLING: 'Тарификация',
  CHANGE: 'Изменить',
  USER_INFO: 'Сведения о пользователе',
  USE_MY_INFORMATION: 'Использовать мои сведения',
  SELECT_YOUR_DEVICES: 'Выберите устройства',
  MONTHLY_FEE: 'Стоимость в месяц',
  ANNUAL_FEE: 'Стоимость годовой подписки',
  TWO_YEAR_FEE: 'Стоимость двухгодичной подписки',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: 'В каждом плане Zang Office должен быть как минимум один пользователь со стандартными ИЛИ расширенными правами.',
  CHECKOUT: 'Оформить заказ',
  MINE: 'Мои',
  REMOVE_THIS_USER: 'Удалить этого пользователя',
  SELECT_A_DEVICE_FOR_THIS_USER: 'Выберите устройство для этого пользователя',
  ADD_ANOTHER: 'Добавить',
  GET_STARTED_WITH_ZANG_OFFICE: 'Начать работу с Zang Office',
  BUNDLE: 'пакет',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: 'Оформите годовую подписку и получите',
  OFF: 'ВЫКЛ.',
  EACH_USER: 'каждый пользователь',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: 'Чтобы настроить количество пользователей, удалите свой заказ либо перейдите к выбору устройств.',
  EVERY_TWO_YEARS: 'Каждые 2 года',
  YOU_VE_SAVED: 'Сохранено',
  INCLUDED: 'Включено',
  ADDONS: 'Дополнения',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: 'Индивидуальная настройка пользователей.',
  UNITS_PER: 'Единиц в',
  TALK_ANYWERE_ANYTIME: 'Общайтесь когда и где угодно.',
  DOWNLOAD_FOR_MAC: 'Скачать для MAC',
  DOWNLOAD_FOR_WINDOWS: 'Скачать для Windows',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: 'Благодарим за приобретение Zang Office! Просмотреть заказ можно здесь.',
  CONTINUE_WITH_YOUR_PURCHASE: 'Продолжить покупку.',
  GET_STARTED_TODAY: 'Приступить к работе сейчас.',
  FEATURES: 'Функции',
  LETS_BREAK_IT_DOWN_FOR_YOU: 'Посмотрим подробнее.',
  BASIC: 'Базовый',
  STANDARD: 'Стандарт',
  POWER: 'Расширенный',
  RATE_MIN_STARTING_FROM: 'тариф/мин., начальный*:',
  INTERNATIONAL_LONG_DISTANCE_RATES: 'Тарифы на международные звонки (на большие дистанции)',
  COMMON_DESTINATIONS: 'Обычные адресаты',
  BEST_DEAL: 'лучшее предложение',
  PER_ACTIVE_USER_PER_MONTH: 'За активного пользователя в месяц.',
  ACCORDING_TO_ANNUAL_CONTRACT: 'согласно годовому контракту',
  MONTHLY: 'Ежемесячно',
  ANNUALLY: 'В год',
  BILLED_ANNUALY: 'С выставлением счетов раз в год',
  BILLED_EVERY_TWO_YEARS: 'С выставлением счетов раз в 2 года',
  CONFIGURE_YOUR_ADDONS: 'Настроить дополнения',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: 'Выберите количество для каждого из доступных дополнений.',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: 'Максимальное количество для данного дополнения —',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: 'Это дополнение доступно только для',
  BILLING_AND_SHIPPING: 'Тарификация и доставка',
  BILLING: 'Тарификация',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: 'Это ваша учетная запись Zang Office.',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: 'Если вы решили использовать в качестве номера Zang Office существующий или бесплатный номер, мы попытаемся найти местный номер с расширением, указанным в этом поле.',
  EVERYTHING_HAPPENS_IN_SPACES: 'Благодаря Spaces возможно все',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: 'Инструмент для совместной работы на основе облака: удивительно, что никто до сих пор его не создал.',
  YOUR_CURRENT_PURCHASES: 'Ваши текущие покупки',
  PURCHASED_ON: 'Приобретено по',
  PLAN_NUMBER: 'Тарифный номер',
  UPDATE: 'Обновить',
  OR: 'или',
  MAKE_A_NEW_PURCHASE: 'Сделать еще одну покупку',
  FEATURES_AND_ADDONS: 'Функции и дополнения',
  FREE: 'БЕСПЛАТНЫЙ',
  PLUS: 'ПЛЮС',
  BUSINESS: 'BUSINESS',
  VIEW: 'Просмотр',
  TEAM: 'Группа',
  LETS_SETUP_YOUR_TEAM: 'Давайте организуем группу',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: 'Выберите тип группы и настройте вашу личную среду.',
  COMPANY_TYPE: 'Тип компании',
  DOMAIN: 'Домен',
  NO_TEAM_IS_SETUP_YET: 'Пока не организована ни одна группа',
  DO_NOT_SETUP_A_TEAM_FOR_ME: 'Не организовывать группы для меня',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: 'Приобретите Avaya Spaces только для себя.',
  CHOOSE_AN_EXISTING_COMPANY: 'Выберите существующую компанию',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: 'Выберите одну из компаний, которую сейчас администрируете.',
  CREATE_A_NEW_TEAM: 'Создать группу',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: 'Укажите название группы и доменное имя.',
  NO_DOMAIN_IS_CONFIGURED: 'Не настроен ни один домен.',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: 'Укажите доменное имя (например, zang.io)',
  CHECK: 'Проверить',
  TEAM_DOMAIN: 'Домен группы (например, zang.io)',
  TEAM_NAME: 'Название группы (например, Zang)',
  OK: 'ОК',
  ZANG_SPACES_ADMIN_CONSOLE: 'Консоль администратора Avaya Spaces',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: 'Вы можете изменить значения ниже, чтобы модернизировать тарифный план',
  CHARGABLE_USERS: 'Платные пользователи',
  TOTAL_USERS: 'Всего пользователей',
  CURRENT_PRICE: 'Действующая цена',
  SAVE: 'Сохранить',
  SAVE_CHANGES_AND_UPDATE_PLAN: 'Сохранить изменения и модернизировать тарифный план?',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: 'Для продолжения выберите по меньшей мере один тип пользователей',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: 'Вы приобретаете Avaya Spaces за',
  BUY_NOW: 'Купить сейчас',
  UP_TO: 'До',
  NO_PURCHASE_REQUIRED: 'покупка не требуется',
  NO_BILLING_OF_UPFRONT_COMMITMENT: 'Отсутствуют счета или авансовые обязательства.',
  SIGN_UP_FOR_FREE: 'Подписка на бесплатную версию.',
  ONE_YEAR_PLAN: 'Тарифный план на 1 год',
  MONTHLY_PLAN: 'Месячный план',
  TWO_YEAR_PLAN: 'Тарифный план на 2 года',
  MONTHS: 'мес.',
  ZANG_OFFICE_ACCOUNT_NAME: 'Имя учетной записи Zang Office',
  ZANG_OFFICE_PLAN_NUMBER: 'Номер тарифа Zang Office',
  TEMPORARY_NUMBER: 'Временный номер',
  START_SETTING_UP_ZANG_OFFICE: 'Приступить к настройке Zang Office.',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: 'Чтобы перевести существующий номер в систему Zang Office, отправьте форму для LNP-авторизации и копию последнего счета за телефон по адресу zosupport@zang.io. При переводе бесплатного номера понадобится также форма RODAA. Обратите внимание, что на перевод понадобится до 10 рабочих дней.',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: 'При покупке/активации выбранного номера Zang Office произошла ошибка. Щелкните «Приступить к настройке Zang Office», чтобы приобрести/активировать номера вручную. Если вы решили использовать существующий номер, это никак не повлияет на процесс переноса номеров.' ,
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: 'Примечание. Чтобы перевести существующий номер в учетную запись Zang Office, заполните и отправьте <a href="{LNP_FORM_LINK}" target="_blank" rel="noopener noreferrer">форму для LNP-авторизации</a> и копию последнего счета за телефон на наш электронный адрес. При переводе бесплатного номера понадобится также <a href="{RODAA_LINK}" target="_blank" rel="noopener noreferrer">форма RODAA</a>. Отправьте необходимые документы по адресу <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>. Перевод телефонного номера может длиться до 10 рабочих дней.',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: 'Обратите внимание, что перевод телефонного номера может длиться до 10 рабочих дней. Тем временем мы выдадим вам временный номер.',
  PLAN_STATUS: 'Статус тарифного плана',
  PLAN_ID: 'Идентификатор тарифного плана',
  SUBSCRIPTION_ID: 'Идентификатор подписки',
  STRIPE_PLAN_ID: 'Идентификатор тарифного плана Stripe',
  ACCOUNT_ID: 'Идентификационные данные учетной записи',
  START_SETTING_UP_ZANG_SPACES: 'Приступить к настройке Avaya Spaces',
  COMPANY_DOMAIN: 'Домен компании',
  THIS_FIELD_IS_REQUIRED: 'Это обязательное поле.',
  PLEASE_ANSWER_THIS_QUESTION: 'Ответьте на этот вопрос.',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: 'Введите идентификатор партнера Avaya.',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: 'Для продолжения прочтите и примите заявление о конфиденциальности.',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: 'Для продолжения прочтите и примите условия предоставления услуг в рамках агентской программы.',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: 'Этот идентификатор партнера Avaya уже используется.',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: 'Этот регистрационный номер налогоплательщика уже используется.',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: 'Указан недействительный идентификатор партнера Avaya Partner.',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: 'Количество должно быть положительным',
  ORDER_COMPLETE: 'Заказ оформлен.',
  PLEASE_TRY_AGAIN: 'Повторите попытку',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: 'Выберите как минимум одно положительное значение',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: 'Обновление еще не завершено. Повторите попытку позже.',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: 'Персональная лицензия не позволяет иметь несколько пользователей. Чтобы перейти на более высокий или низкий тарифный план, выберите соответствующее количество.',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: 'У вас нет доступа к этой учетной записи.',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: 'Ваш текущий тарифный план не позволяет уменьшить исходное количество пользователей. Если требуется изменить какие-либо условия тарифного плана, обратитесь к нам по адресу customerservice@zang.io.',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: 'При регистрации заказа произошла ошибка. Убедитесь, что во всех полях указаны действительные значения,. Если ошибка повторяется, обратитесь в службу поддержки Zang',
  USE_EXISTING_NUMBER: 'Использовать существующий номер',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: 'Выберите, чтобы использовать в тарифном плане существующий номер',
  PRE_SELECT_A_TOLL_FREE_NUMBER: 'Предварительно выберите БЕСПЛАТНЫЙ номер',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: 'Выберите, чтобы добавить в тарифный план персональный бесплатный номер',
  FIND_A_LOCAL_NUMBER: 'Найти местный номер',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: 'Из списка локальных номеров вашей области выберите те, которые необходимо включить в тарифный план',
  ZANG_OFFICE_PHONE_APP: 'Приложение для телефонии Zang Office',
  ZANG_OFFICE_SOFTPHONE: 'Программный телефон Zang Office',
  ZANG_OFFICE_PHONE_APPLICATION: 'Приложение для телефонии Zang Office',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Программный телефон Zang Office обеспечивает необходимые функции связи непосредственно на вашем ПК или мобильном устройстве. Пользуйтесь всеми функциями Zang Office без дополнительных затрат — бесплатный программный телефон Zang Office уже включен в вашу подписку Zang Office.',
  E129_SIP_DESK_PHONE: 'Настольный SIP-телефон E129',
  STANDARD_PHONE: 'Обычный телефон',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Настольный SIP-телефон Avaya E129 обладает всеми важными функциями обработки вызовов, которые можно ожидать от этого доступного по цене и в то же время весьма функционального устройства. Пользователи могут отключать микрофон, переносить, переадресовывать и удерживать вызовы, а также одним нажатием кнопки организовывать конференции по запросу. Полнодуплексный телефон с громкоговорителем может работать в режиме громкой связи, а благодаря наличию порта POE его удобно подключить к сети компании. Благодаря функциональности и доступной цене аппарат для SIP-телефонии Avaya E129 подойдет широкому кругу пользователей. Блок питания переменного тока в комплекте.',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: 'Современное устройство для общения, покрытое стеклом. Доступ к голосовой связи, чатам и приложениям для совместной работы одним нажатием кнопки. Никаких прерываний и пауз. Не нужно управлять множеством устройств. Уникальные функции помогут организовать рабочий процесс и расширят функционал деловых приложений. Этот мощный настраиваемый IP-телефон обладает преимуществами настольного телефона и гибкостью программного.',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'Конференц-телефон B179',
  CONFERENCE_PHONE: 'Конференц-телефон',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'Телефон для конференц-связи B179 предназначен специально для мероприятий, рассчитанных более чем на 10 участников. Он существенно повышает эффективность индивидуальной и командной работы. Это мощный многофункциональный инструмент, который дополнит существующие коммуникационные решения и легко адаптируется под растущие потребности предприятия. Блок питания переменного тока в комплекте.',
  PLAN: 'Тарифный план',
  REDIRECTING: 'Перенаправление',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: 'Во всех полях должны быть указаны действительные значения',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: 'В каждом плане Zang Office должен быть как минимум один тип пользователя. Вернитесь к выбору устройств и измените конфигурацию.',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: 'Вероятно, вы не выбрали номер для учетной записи Zang Office. Вернитесь к выбору номеров.',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: 'Это имя учетной записи Zang Office занято. Введите другое имя',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: 'Выбранный номер Zang Office принадлежит другому клиенту. Вернитесь к выбору номеров и укажите другой.',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: 'Выберите помесячный вариант тарификации и получите <span class="text-400">ПЕРВЫЕ 30 ДНЕЙ БЕСПЛАТНО</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: 'или выберите годовой план и получите более выгодную цену и',
  FREE_PHONE: 'БЕСПЛАТНЫЙ ТЕЛЕФОН',
  DISCOUNT: 'скидка',
  DISCOUNTED_PHONE: 'телефон со скидкой',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: 'от общей суммы купленного телефона',
  LIMITED_TIME_OFFER: 'Предложение с ограниченным сроком действия',
  PROMOTION: 'Промоакция',
  ZANG_SPACES_PROMOTION: 'Акционные предложения Avaya Spaces',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: 'Перейти к выбору номера',
  DURATION: 'Продолжительность',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: 'Поздравляем! Вы получаете кредит <strong>{amount}</strong> на общую сумму заказанных устройств.',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: 'Все применимые скидки будут учтены в итоговой сумме заказа.',
  SHIPPING_TYPE: 'Тип доставки',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: 'Данные для отслеживания заказа будут отправлены, как только заказанные изделия будут отгружены со склада',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: 'Получите {amount} на пользователя на покупку любого устройства. Предложение с ограниченным сроком действия.',
  PARTNER_ORDERS: 'Заказы партнеров',
  COMMISSION: 'Комиссия',

  ADDITIONAL_DEVICES: 'Дополнительные устройства',
  NO_USER: 'Нет пользователя',
  QUANTITY: 'Количество',
  BUY_DEVICES: 'Купить устройства',
  DEVICE: 'Устройство',
  PRICE: 'Цена',


  RESET_ALL_PURCHASES: 'Очистить историю покупок',
  LISTS: 'Списки',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: 'Введите номер телефона перед созданием предложения',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: 'Введите данные для выставления счетов и доставки перед созданием предложения',
  CALCULATING_TAXES_PLEASE_WAIT: 'Расчет налоговых выплат. Подождите...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: 'Платеж с помощью текущей кредитной карты отклонен.',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: 'Платеж с помощью кредитной карты отклонен. Используйте другую карту.',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: 'При оплате заказа произошла ошибка. Используйте другую карту.',
  INVALID_CREDIT_CARD: 'Кредитная карта недействительна',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type} не совпадает с адресом, указанным в данных кредитной карты',
  INVALID_SECURITY_CODE: 'Недопустимый код безопасности (CVC)',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: 'Скидки и рекламные цены включены в счет.',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: 'Не удалось создать учетную запись клиента. Повторите попытку',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: 'Не удалось добавить кредитную карту. Повторите попытку',
  SALES_FORCE_QUOTE_ID: 'ИД предложения Salesforce',
  SALES_FORCE_ORDER_ID: 'ИД заказа Salesforce',
  SALES_FORCE_OPPORTUNITY_ID: 'ИД возможности Salesforce',
  SALES_FORCE_CONTACT_ID: 'ИД контакта Salesforce',
  SALES_FORCE_CONTRACT_ID: 'ИД контракта Salesforce',
  SALES_FORCE_ACCOUNT_ID: 'ИД учетной записи Salesforce',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Просто добавьте устройство',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: 'Просто добавьте устройство',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: 'Купите дополнительные устройства для вашей учетной записи Zang Office',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: 'Ой! Что-то не так с вашим заказом. Обновите страницу и создайте новый заказ.',
  CREATE_A_NEW_COMPANY: 'Создать новую компанию',
  ADD_A_NEW_COMPANY: 'Добавить новую компанию',

}
