export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: '无法解密帐户系统中的数据',
  PHONE_TYPES: '电话类型',
  IMAGINE_A_BETTER_WAY: '想象一下用更好的',
  OF_DOING_THINGS: '方式工作。',
  GET_STARTED: '开始使用',
  PURCHASE: '购买',
  DOWNLOADS_AND_EXTENSIONS: '下载和扩展',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: '通过这些必备的加载项充分利用 Zang 产品！',
  ALL: '所有',
  REFERRAL_AGENT: '推荐代理',
  SALES_AGENT: '销售代理',
  CART: '购物车',
  PARTNER_PROGRAMS: '合作伙伴计划',
  HOME: '主页',
  MANAGE_CREDIT_CARDS: '管理信用卡',
  MANAGE_PAYMENT_OPTIONS: '管理付款选项',
  MANAGE_BILLING_ACCOUNT: '管理账单帐户',
  LIMIT: "限制",
  MY_PROFILE: '我的个人资料',
  MY_SETTINGS: '我的设置',
  MY_PARTNER_PORTAL: '我的合作伙伴门户',
  CLEAR_ZANG_OFFICE: '清除 Zang Office',
  CLEAR_ZANG_SPACES: '清除 Zang Spaces',
  FEATURE_BREAKDOWN: '功能详细列表',
  PLAN_BREAKDOWN: '计划详细列表', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: '您需要的办公电话。提供您喜欢的价格。',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: '想想您可以在 Zang Spaces 中完成的事情',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '您结账后的总金额将可享受半价折扣',
  HURRICANE_HARVEY_MESSAGE: 'Avaya 和 Zang 希望帮助那些遭受飓风哈维和可能遭受飓风厄玛影响的公司。德克萨斯州、路易斯安那州、佛罗里达州、亚拉巴马州、佐治亚州、北卡罗来纳州、南卡罗来纳州、田纳西州和密西西比州受影响的所有公司可立即<b>免费获得 3 个月的 Zang Office</b> 和 <b>Zang Spaces</b>。',
  LEARN_MORE: '了解更多',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ 现已推出',
  NEW: '新消息！',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: '使用这款易于使用的全玻璃语音、视频和聊天协作电话，获得最佳 Zang Office 使用体验。',
  LOG_IN: '登录',
  SIGN_UP: '注册',
  SIGN_OUT: '退出',
  SIGN_IN: '登录', //login to the system, connect
  ADMINISTRATION: '管理',
  PRODUCTS: '产品',
  ORDERS: '订单',
  PAGES: '页',
  CUSTOMERS: '客户',
  USERS: '用户',
  PLANS: '计划',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'Office',
  CDRS: 'Cdr',
  CDR_CHECKS: 'Cdr 检查',
  PARTNERS: '合作伙伴',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: '您好像已购买 Zang Office。您无法再下更多 Zang Office 订单。',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: '您好像已经为此公司购买了 Avaya Cloud。请选择其他公司。',
  PARTNER_CONNECTIONS: '合作伙伴连接',
  CHECK_OUT_GENERAL_FATAL_ERROR: '下订单时发生错误。请联系 Zang 支持 ({SUPPORT_EMAIL}) 获取更多信息。',
  APPLICATION_GENERAL_FATAL_ERROR: '提交申请时发生错误。请联系 Zang 支持 ({SUPPORT_EMAIL}) 获取更多信息。',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: '请至少选择一种用户类型以继续。',
  BACK: '返回',
  SAVE_CHANGES: '保存更改',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: '确定要继续？',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: '您拥有 {PLACEHOLDER} 个信用券可用于购买任何设备。此信用券将在您提交订单后消失。',
  JUST_A_REMINDER: '温馨提示',
  LAST_CHANCE: '机不可失，失不再来',
  IM_GOOD_PLACE_MY_ORDER: '我已确认 - 请为我下单',
  BUY_MORE_DEVICES: '购买更多设备',
  YES_PLACE_MY_ORDER: '是的，请为我下单',
  NO_THANKS: '不，谢谢！',
  YES: '是',
  ABOUT_US: '关于我们',
  NEWS_AND_PRESS: '新闻资讯',
  CARREERS: '招贤纳士',
  CONTACT_US: '联系我们',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: '感谢您的选购。您的订单详情如下所示。',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: '请联系 <a href="mailto:{EMAIL}">{EMAIL}</a> 了解此信息',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: '我们的客户成功和技术支持团队会在您的系统就绪时与您联系。<br/><br/><b>请注意，最多需要一个小时的时间来设置您的系统。</b>',
  QUESTION_CUSTOMER_SERVICE: '如果有任何问题或疑问，请通过以下电子邮件地址与我们联系：<a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>！',
  BLOG: '博客',
  FAQS: 'FAQ',
  DOCUMENTATION: '文档',
  TERMS_OF_SERVICE: '服务条款',
  HELP: '帮助',
  PRIVACY_STATEMENT: '隐私声明',
  GENERAL_PRIVACY_STATEMENT: '一般隐私权声明',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: '一般服务条款 - Avaya Cloud 解决方案',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. 保留所有权利。',
  PROCESSING: '正在处理',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: '请耐心等待。该过程可能需要一些时间',
  OPEN_IN_A_NEW_TAB: '在新标签页中打开',
  GOT_IT: '收到！',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' 此项操作将会产生下列结果：',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: '删除该计划的每月订阅服务',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: '禁用任何第三方系统上的任何帐户',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: '将该计划的状态更改为“已禁用”',
  LAST_ACTION_STEPS: '上次操作步骤',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: '创建帐户后，通过 Zang Office 管理员门户购买加载项。',
  TYPE: '类型',
  ADMIN: '管理员',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: '该用户将被配置为公司帐户的主要/付款联系人。可随时通过 Zang Office 管理员门户更改。',
  DESCRIPTION: '描述',
  SUCCESS: '成功',
  REQUEST_CANCELATION: '请求取消',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: '这样不好啊！很遗憾听到您想离开。',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '请填写以下表格开始取消过程。我们的客户成功部门员工将在 1-2 个工作日内审核和跟进您的请求，实现无缝对接。',
  YOUR_NAME: '您的姓名',
  COMPANY: '公司',
  SERVICE: '服务',
  REASON_FOR_CANCELING: '取消原因',
  SUBMIT: '提交',
  EXIT: '退出',
  REQUEST_SUBMITTED: '请求已提交！',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '我们的客户成功部门员工将在 1-2 个工作日内审核和跟进您的请求，实现无缝对接。',
  DATE: '日期',
  PRODUCT: '产品',
  USER: '用户',
  STATUS: '状态',
  ACTIONS: '操作',
  VIEW_DETAILS: '查看详情',
  DISABLE: '禁用',
  ENABLE: '启用',
  CANCEL: '取消',
  PLAN_DETAILS: '计划详情',
  SUMMARY: '摘要',
  QUANTITIES: '数量',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*总计含计划功能的价格',
  TOTAL: '总计',
  BILLED: '已出账单',
  PLAN_INFORMATION: '计划信息',
  UPDATE_PLAN: '更新计划',
  ADMIN_ACTIONS: '管理员操作',
  NAME_ON_CREDIT_CARD: '信用卡持有人姓名',
  CREDIT_CARD_BRAND: '信用卡品牌',
  VISA: 'Visa',
  AMERICAN_EXPRESS: 'American Express',
  MASTER_CARD: 'Master Card',
  CREDIT_CARD_NUMBER: '信用卡号码',
  EXPIRATION: '过期',
  MONTH: '月',
  YEAR: '年',
  SECURITY_CODE: '安全码',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: '信用卡背面的代码',
  BACK_TO_CHECKOUT: '返回结账',
  NO_ORDERS_FOUND: '未发现订单',
  ADD: '添加',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: '使用上面的表格添加新信用卡。务必填写所有字段',
  NUMBER: '号码',
  EXPIRES: '过期',
  DELETE: '删除',
  ITEM_DETAILS: '物品详情',
  FEE: '费用',
  ITEMS: '物品',
  SEARCH_BY_CONFIRMATION: '按确认搜索',
  CONFIRMATION: '确认',
  CHECKOUT_STATUS: '结账状态',
  ORDER_STATUS_PROCESS: '订单状态进程',
  CREATED_ON: '创建日期',
  ORDER_SUMMARY: '订单摘要',
  APPROVED: '已批准', //example: partner application approved
  REJECTED: '已拒绝', //example: partner application rejected
  APPROVE: '批准', //example: partner application approved
  REJECT: '拒绝', //example: partner application rejected
  PENDING: '待定', //example: partner application pending
  EDIT: '编辑',
  ONE_TIME_FEE: '一次性费用',
  SUB_TOTAL: '小计',
  TAXES: '税费',
  CHANGES: '更改',
  CREATE_A_QUOTE: '创建报价单',
  EXTRA_INFORMATION: '其他信息',
  THANK_YOU_FOR_YOUR_ORDER: '感谢您的订购',
  ORDER_CONFIRMATION: '订单确认',
  INVALID_ORDER: '无效的订单',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: '不用担心，我们已将其用电子邮件发送给您 :)',
  HELLO: '您好',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: '感谢您的选购。我们会在您的物品发出之后发送确认函。您的订单详情如下所示。',
  ACCOUNT_INFORMATION: '帐户信息',
  BILLING_INFORMATION: '账单信息',
  SHIPPING_INFORMATION: '配送信息',
  NAME: '姓名',
  EMAIL: '电子邮件地址',
  SEARCH: '搜索',
  CLEAR: '清除',
  PARTNER: '合作伙伴',
  NO_PARTNERS_FOUND: '未找到合作伙伴',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: '当客户从合作伙伴的个人链接进入商店时，将会创建合作伙伴连接。',
  CUSTOMER: '客户',
  AGENT: '代理',
  NO_PARTNER_CONNECTIONS_FOUND: '未找到合作伙伴连接',
  I_HAVE_READ_AND_AGREE_WITH_THE: '我已阅读并同意',
  ZANG_PRIVACY_STATEMENT: 'Zang 隐私声明',
  AGENT_PROGRAM_TERMS_OF_SERVICE: '代理计划服务条款',
  SUBMIT_APPLICATION: '提交申请',
  SUBMITTING: '正在提交',
  SUBMITTING_YOUR_APPLICATION: '正在提交您的申请',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: '我们将根据条款和条件，确保所有银行和帐户信息的隐私和安全。',
  BANK_NAME: '开户行',
  ADDRESS: '地址',
  COUNTRY: '国家/地区',
  SELECT_ONE: '- 选择一个 -',
  STATE_PROVINCE: '州/省',
  CITY: '城市',
  ZIP_POSTAL_CODE: '邮政编码',
  ACCOUNT_NUMBER: '帐号',
  BANK_NUMBER: '银行代码',
  TRANSIT_NUMBER: '交易号码',
  SWIFT_CODE: '银行国际代码',
  TAX_REGISTRATION_NUMBER: '纳税登记号',
  SAVE_BANK_INFORMATION: '保存银行信息',
  SAVING_BANK_INFORMATION: '正在保存银行信息',
  NO_CUSTOMERS_FOUND: '未找到客户',
  YOU_ARE_A: '您是 ',
  A_DISCOUNT_OF: '折扣',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '将用于您结账后的总金额。',
  FIRST_NAME: '名字',
  LAST_NAME: '姓氏',
  COMPANY_NAME: '公司名称',
  LEGAL_COMPANY_NAME: '法定公司名称',
  PHONE_NUMBER: '电话号码',
  WEBSITE: '网站',
  OPERATIONAL_ADDRESS: '营业地址',
  SAME_AS_ORGANIZATION_ADDRESS: '与组织地址相同',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: '您当前是否为 Avaya 合作伙伴？',
  NO: '否',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: '如果是，请输入您的 Avaya 合作伙伴 ID',
  MY_PARTNER_PORTAL: '我的合作伙伴门户',
  THANK_YOU_FOR_APPLYING: '感谢您的申请！',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: '还差一步即可完成！为完成销售代理申请，请单击以下链接，回答所有问题。',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' 否则，请提供 ',
  PLEASE_GIVE: '请提供',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: '如果您是 Avaya 的现有合作伙伴，请不要访问以下链接。<br />我们正在审查您的合作伙伴 ID，并将尽快与您联系。',
  BUSINESS: '营业',
  DAYS: '天数',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: '以便高级管理层审核您的申请。<br />与此同时，可将所有问题发送至',
  COMPLETE_MY_APPLICATION: '完成我的申请',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: '我们已审核您的申请。很遗憾，此刻我们确定其不适合我们的计划。这可能并不要紧，但在我们确定清楚之前，我们无法推进双方的合作伙伴关系。我们知道这可能会令人沮丧。请注意，我们会详加论证，如果有更多信息的话，我们会尽快联系您。与此同时，对于此过程如有任何问题，请随时发送电子邮件至',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: '。',
  CONGRATULATIONS: '恭喜',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: '您现已成为正式的 Zang 代理！',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: '首先请将您的个人链接告知您的所有潜在客户，',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: '帮助他们体验更好的工作方式。',
  CHANGE_STATUS: '更改状态',
  AGENT_DETAILS: '代理详情',
  BANK_INFORMATION: '银行信息',
  THIS_ORDER_WAS_PLACED_BY_A: '下达此订单的是',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: '适用于总金额',
  REFERRALS: '推荐',
  SALES: '销售',
  FOUND: '已找到',
  HOW_IT_WORKS: '工作原理',
  WHAT_YOU_GET: '您的所得',
  SUPPORT: '支持',
  WHICH_PROGRAM_IS_BEST_FOR_ME: '哪项计划最适合我？',
  WHY_JOIN: '为何加入？',
  QUOTE: '报价单',
  PRINT_THIS_QUOTE: '打印此报价单',
  CLOSE_THIS_WINDOW: '关闭此窗口',
  SEARCH_BY_PLAN: '按计划搜索',
  ACCESS_LEVEL: '访问级别',
  DISPLAY_NAME: '显示姓名',
  INDUSTRY: '行业',
  COMPANY_INDUSTRY: '公司所在行业',
  CONTACT_PHONE_NUMBER: '联系人电话号码',
  EMAIL_ADDRESS: '电子邮件地址',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: '是，请将关于 Zang 新闻、应用程序、交易和特别活动的电子邮件发送给我！',
  INFORMATION: '信息',
  ORDER_HISTORY: '订单历史',
  FILTER: '过滤器',
  ACCOUNT: '帐户',
  AMOUNT_CHARGED: '收取金额',
  DETAILS: '详情',
  NO_RECORDS_FOUND: '未找到任何记录',
  CALL_LOGS: '呼叫日志',
  EXPORT: '导出',
  CALLER_NAME: '呼叫人姓名',
  DIALED_NUMBER: '已拨号码',
  DURATION_SEC: '持续时间（秒）',
  COST: '费用',
  PAYMENT_METHOD: '付款方式',
  PURCHASE_ORDER: '采购订单',
  PURCHASE_ORDERS: '采购订单',
  CREDIT_CARD: '信用卡',
  SHIPPING_ADDRESS: '配送地址',
  SAME_AS_BILLING_ADDRESS: '与账单地址相同',
  SAME_AS_SHIPPING_ADDRESS: '与配送地址相同',
  OTHER: '其他',
  SHIPPING_OPTIONS: '配送选项',
  FREE_SHIPPING: '免费配送',
  ADDITIONAL_NOTES: '补充说明',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: '我已阅读并同意以下条款：',
  EMERGENCY_911_SERVICE_NOTICE: '紧急 911 服务通知',
  PLACE_MY_ORDER: '请为我下订单',
  CLEAR_MY_ORDER: '清除我的订单',
  PLACING_YOUR_ORDER: '正在为您下订单',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: '请耐心等待。该过程可能需要 1 分钟时间。',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: '此过程需要一些时间。感谢您的耐心等待。为确保您的订单不中断，请不要关闭此浏览器窗口或单击“后退”或“刷新”按钮。',
  YOUR_NEW_NUMBER: '您的新号码',
  NO_NUMBER_SELECTED: '未选择号码',
  WELL_THAT_WAS_EASY: '就是这么简单！',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: '还差几步即可完成 :)',
  NEXT: '下一个',
  TITLE: '标题',
  SUB_TITLE: '子标题',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: '按区号搜索... （仅限美国和加拿大）',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: '输入区号...（仅限美国）',
  SELECT_A_PREFIX: '选择前缀',
  PICK_THIS_NUMBER: '选择这个号码',
  DEVICES: '设备',
  BILLING: '账单',
  CHANGE: '更改',
  USER_INFO: '用户信息',
  USE_MY_INFORMATION: '使用我的信息',
  SELECT_YOUR_DEVICES: '选择您的设备',
  MONTHLY_FEE: '月费',
  ANNUAL_FEE: '年费',
  TWO_YEAR_FEE: '2 年费用',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: '每个 Zang Office 计划至少需要一个标准或高级用户。',
  CHECKOUT: '结账',
  MINE: '我的',
  REMOVE_THIS_USER: '删除此用户',
  SELECT_A_DEVICE_FOR_THIS_USER: '为此用户选择设备',
  ADD_ANOTHER: '添加另一个',
  GET_STARTED_WITH_ZANG_OFFICE: '开始使用 Zang Office',
  BUNDLE: '捆绑',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: '注册一年并享受',
  OFF: '折扣',
  EACH_USER: '每个用户',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: '如要调整用户数量，您必须清除订单或继续执行“设备”步骤。',
  EVERY_TWO_YEARS: '每 2 年',
  YOU_VE_SAVED: '您已保存',
  INCLUDED: '已包含',
  ADDONS: '加载项',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: '根据他们的喜好自定义每个用户！',
  UNITS_PER: '单位/',
  TALK_ANYWERE_ANYTIME: '随时随地沟通！',
  DOWNLOAD_FOR_MAC: 'MAC 版下载',
  DOWNLOAD_FOR_WINDOWS: 'Windows 版下载',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: '感谢您购买 Zang Office！在此处查看您的订单！',
  CONTINUE_WITH_YOUR_PURCHASE: '继续购买！',
  GET_STARTED_TODAY: '立即开始使用！',
  FEATURES: '功能',
  LETS_BREAK_IT_DOWN_FOR_YOU: '让我们为您讲解一下！',
  BASIC: '基本',
  STANDARD: '标准',
  POWER: '高级',
  RATE_MIN_STARTING_FROM: '费率/分钟，始于*：',
  RATE_MIN_STARTING_FROM_1: '费率/分钟，始于：',
  LONG_DISTANCE: '国际长途',
  INTERNATIONAL_LONG_DISTANCE_RATES: '国际长途费率',
  COMMON_DESTINATIONS: '共同目的地',
  BEST_DEAL: '最划算',
  PER_ACTIVE_USER_PER_MONTH: '/活跃用户/月。',
  ACCORDING_TO_ANNUAL_CONTRACT: '根据年度合同',
  BILLED_ACCORDING_TO_SELECTED_PLAN: '根据所选套餐计费。',
  MONTHLY: '每月',
  ANNUALLY: '每年',
  BILLED_ANNUALY: '每年账单',
  BILLED_EVERY_TWO_YEARS: '每 2 年账单',
  CONFIGURE_YOUR_ADDONS: '配置加载项',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: '为每个可用的加载项选择数量。',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: '此加载项的最大数量为',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: '此加载项仅适用于',
  BILLING_AND_SHIPPING: '账单和配送',
  BILLING: '账单',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: '这是您的 Zang Office 帐户名。',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: '这将是您的 Avayay Cloud 帐户名。',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: '如果您选择使用现有或免费号码作为您的 Zang Office 号码，我们将尝试查找带有该字段所用分机的本地号码。',
  EVERYTHING_HAPPENS_IN_SPACES: '一切都发生在 Spaces',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: '一款您一直想要却从未找到的基于云的团队协作工具。',
  YOUR_CURRENT_PURCHASES: '您当前的购买',
  PURCHASED_ON: '购买日期',
  PLAN_NUMBER: '计划号码',
  UPDATE: '更新',
  UPDATED: '已更新',
  OR: '或者',
  MAKE_A_NEW_PURCHASE: '进行新的购买',
  FEATURES_AND_ADDONS: '功能和加载项',
  FREE: 'FREE',
  PLUS: 'PLUS',
  BUSINESS: '高级',
  VIEW: '查看',
  TEAM: '团队',
  LETS_SETUP_YOUR_TEAM: '我们来组建您的团队。',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: '只需选择您要创建的团队类型，建立您的私人环境即可。',
  COMPANY_TYPE: '公司类型',
  DOMAIN: '域',
  NO_TEAM_IS_SETUP_YET: '尚未组建团队',
  DO_NOT_SETUP_A_TEAM_FOR_ME: '不要为我组建团队',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: '仅为您自己购买 Zang Spaces。',
  CHOOSE_AN_EXISTING_COMPANY: '选择现有公司',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: '选择您当前正在管理的公司之一。',
  CREATE_A_NEW_TEAM: '新建团队',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: '提供团队和域名。',
  NO_DOMAIN_IS_CONFIGURED: '未配置域。',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: '请提供域名（“zang.io”除外）',
  CHECK: '检查',
  TEAM_DOMAIN: '团队域（“zang.io”除外）',
  TEAM_NAME: '团队名称（“zang”除外）',
  OK: '确定',
  ZANG_SPACES_ADMIN_CONSOLE: 'Zang Spaces 管理控制台',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: '您可以更改下列值，以更新您的计划',
  CHARGABLE_USERS: '应付费的用户',
  TOTAL_USERS: '用户总数',
  CURRENT_PRICE: '现价',
  SAVE: '保存',
  SAVE_CHANGES_AND_UPDATE_PLAN: '保存更改并更新计划？',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: '请至少选择一种类型的用户继续',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: '您正在为该用户购买 Zang Spaces',
  BUY_NOW: '立即购买',
  SELECT: "选择",
  UP_TO: '多达',
  NO_PURCHASE_REQUIRED: '无需购买',
  NO_BILLING_OF_UPFRONT_COMMITMENT: '无需计费或提前支付。',
  SIGN_UP_FOR_FREE: '免费注册！',
  ONE_YEAR_PLAN: '1 年计划',
  MONTHLY_PLAN: '月度计划',
  TWO_YEAR_PLAN: '2 年计划',
  MONTHS: '月',
  ZANG_OFFICE_ACCOUNT_NAME: 'Zang Office 帐户名',
  ZANG_OFFICE_PLAN_NUMBER: 'Zang Office 计划号码',
  TEMPORARY_NUMBER: '临时号码',
  START_SETTING_UP_ZANG_OFFICE: '开始设置 Zang Office！',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: '如果您要将现有号码转移到 Zang Office 解决方案，您需要将 LNP 授权书和最近的话费账单副本用电子邮件发送至 zosupport@zang.io。如果您要转移免费号码，还请用电子邮件发送 RODAA 表。注意，最多可能需要 10 个工作日完成转移。',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: '购买/激活选择的 Zang Office 号码时出错。请单击“开始设置 Zang Office”手动激活/购买您的号码。如果您已选择使用现有号码，移植过程将不会受到影响。',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: '请注意：如果您要将现有号码转移到 Zang Office 帐户，需要填写 <a href="{LNP_FORM_LINK}" target="blank">LNP 授权书</a>并将其与最近的话费账单副本通过电子邮件发送。如果您要转移免费号码，还请填写此 <a href="{RODAA_LINK}" target="blank">RODAA 表</a>。请将所有适用的文件发送至 <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>。电话号码转移过程最多可能需要 10 个工作日。',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: '请注意，电话号码转移过程最多可能需要 10 个工作日。在此期间，我们将附上一个临时电话号码供您在帐户内使用。',
  PLAN_STATUS: '计划状态',
  PLAN_ID: '计划 ID',
  SUBSCRIPTION_ID: '订阅 ID',
  STRIPE_PLAN_ID: 'Stripe 计划 ID',
  ACCOUNT_ID: '帐户 ID',
  START_SETTING_UP_ZANG_SPACES: '开始设置 Zang Spaces',
  COMPANY_DOMAIN: '公司域',
  THIS_FIELD_IS_REQUIRED: '该字段为必填。',
  PLEASE_ANSWER_THIS_QUESTION: '请回答这个问题。',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: '请输入您的 Avaya 合作伙伴 ID。',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: '请阅读并同意“隐私声明”以继续。',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: '请阅读并同意“代理计划服务条款”以继续。',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: '此 Avaya 合作伙伴 ID 已在使用。',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: '此纳税登记号已在使用。',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: '无效的 Avaya 合作伙伴 ID。',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: '数量必须为正数',
  ORDER_COMPLETE: '订单已完成！',
  PLEASE_TRY_AGAIN: '请重试',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: '请至少选择一个正值',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: '更新仍在进行当中，请稍后重试。',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: '对于个人许可证，不能拥有超过一个用户。如要升级或降级您的计划，请对数量进行相应更改。',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: '您没有访问此帐户的权限。',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: '您的当前计划不允许您将用户减少至少于原数量。如果您希望进行这样的调整，请通过 customerservice@zang.io 与我们联系。',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: '下订单时出错。务必确保所有字段的值有效，如果错误依然存在，请联系 Zang 支持获取更多信息。',

  USE_EXISTING_NUMBER: '使用现有号码',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: '选择对您的计划使用现有号码',
  PRE_SELECT_A_TOLL_FREE_NUMBER: '预先选择一个免费号码',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: '选择将您自己的免费号码添加至您的计划',
  FIND_A_LOCAL_NUMBER: '查找当地号码',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: '从您所在区域的当地号码列表中选择，添加至您的计划',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: '选择将本地号码添加到计划',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: '按区号搜索可用的电话号码',
  SEARCH_AVAILABLE_PHONE_NUMBERS: '搜索可用的电话号码',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: '输入您计划转接的现有号码',


  ZANG_OFFICE_PHONE_APP: 'Zang Office 手机应用',
  ZANG_OFFICE_SOFTPHONE: 'Zang Office 软电话',
  ZANG_OFFICE_PHONE_APPLICATION: 'Zang Office 手机应用程序',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Zang Office 软电话包含您在桌面或移动设备上想要的所有通信功能。无需花费巨资即可使用 Zang Office 的全部出色功能，因为 Zang Office 软电话已在您订用 Zang Office 时免费包含在内！',
  E129_SIP_DESK_PHONE: 'E129 SIP 座机',
  STANDARD_PHONE: '标准电话',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Avaya E129 SIP 座机包含了您在经济实惠而又功能强大的 SIP 电话中想要的所有基本呼叫处理功能。使用 Avaya E129 座机时，用户按下按钮即可转接、静音、转移和保持呼叫以及召开临时会议。双向免持听筒允许进行免提通话，其以太网供电端口可实现对网络的便捷连接。Avaya E129 SIP 座机拥有合适的呼叫功能，经济实惠而又外形美观。随附交流电源适配器。',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: '使用创新的全玻璃专用桌面设备进行互动。通过一键式连接使用语音、聊天和协作应用程序。不会发生异常中断或暂停的情况。无需管理多个互动设备。在您的工作流程和业务流程中融入独特的定制体验。这款功能强大的可定制设备兼具座机的优势和应用程序平台的灵活性。',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'B179 会议电话',
  CONFERENCE_PHONE: '会议电话',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'B179 会议电话最适合董事会会议室和超过 10 人的团体大会议室，有助于改善员工的工作效率和协作。B179 会议电话功能多样，性能卓越，是对您现有解决方案的完美补充，并能随着您业务的发展或需求的变更轻松进行重新部署。随附交流电源适配器。',
  PLAN: '计划',
  REDIRECTING: '正在重定向',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: '务必确保所有字段的值有效',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: '每个 Zang Office 计划至少需要一种用户类型。请返回设备选择步骤，更改配置。',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: '您可能没有为 Zang Office 帐户选择任何号码。请返回号码选择步骤，选择号码。',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: '该 Zang Office 帐户名已在使用。试试另一个',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: '您选择的 Zang Office 号码已被另一客户购买。请返回号码选择步骤，选择其他号码。',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: '选择月度计划，获得无附加条款的 <span class="text-400">30 天免费试用</span>。',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: '或者选择年度计划，享受更优惠的价格',
  FREE_PHONE: '并获得一部免费电话',
  DISCOUNT: '折扣',
  DISCOUNTED_PHONE: '折扣电话',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: '从您所购买电话的总价值中扣除',
  LIMITED_TIME_OFFER: '限时供应',
  PROMOTION: '促销',
  ZANG_SPACES_PROMOTION: 'Zang Spaces 促销',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: '继续选择电话号码',
  DURATION: '持续时间',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: '恭喜！您拥有 <strong>{amount}</strong> 的信用券，可用来支付您的设备订单总额！',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: '您的最终订单摘要内所有适用的折扣都将有所调整。',
  SHIPPING_TYPE: '配送类型',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: '一旦您的物品从我们的仓库发出，我们将发送跟踪详情。',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: '为每位用户领取 {amount} 信用券，用来购买任何设备。限时供应。',
  PARTNER_ORDERS: '合作伙伴订单',
  COMMISSION: '佣金',

  ADDITIONAL_DEVICES: '其他设备',
  NO_USER: '无用户',
  QUANTITY: '数量',
  BUY_DEVICES: '购买设备',
  DEVICE: '设备',
  PRICE: '价格',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: '请至少输入 {chars} 个字符以搜索代理',
  NO_RESULTS_FOUND: '未找到结果',
  RESULTS_COULD_NOT_BE_LOADED: '无法加载结果',
  CLEAR_SELECTION: '清除所选内容',


  RESET_ALL_PURCHASES: '清除所有购买',
  LISTS: '列表',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: '请在创建报价单前填写您的电话号码。',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: '请在创建报价单前填写您的账单和配送信息',
  CALCULATING_TAXES_PLEASE_WAIT: '正在计算税费，请稍候...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: '您选择的信用卡存在问题。',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: '此信用卡存在问题。请使用其他信用卡。',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: '对您的订单进行收费时发生错误。请选择其他信用卡',
  INVALID_CREDIT_CARD: '无效信用卡',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type} 与信用卡地址信息不匹配',
  INVALID_SECURITY_CODE: '安全码 (cvc) 无效',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: '任何适用的折扣和促销价格已应用至此发票',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: '无法为您创建客户帐户。请重试',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '无法为您创建信用卡。请重试',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '此信用卡已用于周期性订阅。',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '将此信用卡设置为默认时出错。',
  DEFAULT: '默认',
  SET_DEFAULT: '设为默认',
  SALES_FORCE_QUOTE_ID: 'Salesforce 报价 ID',
  SALES_FORCE_ORDER_ID: 'Salesforce 订单 ID',
  SALES_FORCE_OPPORTUNITY_ID: 'Salesforce 机会 ID',
  SALES_FORCE_CONTACT_ID: 'Salesforce 联系人 ID',
  SALES_FORCE_CONTRACT_ID: 'Salesforce 合同 ID',
  SALES_FORCE_ACCOUNT_ID: 'Salesforce 帐户 ID',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '只需“添加设备”',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '只需添加设备并将其与用户关联即可。',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: '购买其他设备以使用您的 Zang Office 帐户',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: '哎哟！您的订单出错了。请刷新网页、清除订单，然后重新开始。',
  CREATE_A_NEW_COMPANY: '创建新公司',
  ADD_A_NEW_COMPANY: '添加新公司',
  PARTNER_DETAILS: '合作伙伴详细信息',
  AGENTS: '代理',
  PARTNER_PORTAL: '我的合作伙伴门户',
  AGENT: '代理',
  AGENT_PORTAL: '代理门户',
  NO_AGENTS_FOUND: '未找到代理',
  NO_AGENT: '无代理',
  RELATION: '关系',
  OWNER: '所有人',
  ADMIN: '管理员',
  MANAGER: '经理',
  EMPLOYEE: '员工',
  ACTIVE: '活动',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: '请输入与您关联的其中一个合作伙伴',
  APPLIED_ON: '申请日期',
  JOIN_A_PARTNER: '加入合作伙伴',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: '您离加入 <b>{COMPANY_NAME}</b> 只差一步',
  JOIN_PLACEHOLDER_NOW: '立即加入 {COMPANY_NAME}',
  UPDATE_AGENT_INFO: '更新代理信息',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: '开始使用 Avaya Cloud 解决方案<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: '关联 Zang™',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: '操作简单、功能强大的统一协作解决方案',
  IP_OFFICE_DONT_PAY_TILL: '请勿在 2018 年 4 月 15 日之前付款！',
  LOGIN: '登录',
  DISCOVER: '发现',
  SOLUTIONS: '解决方案',
  SERVICES: '服务',
  INDUSTRIES: '行业',
  CASE_STUDIES: '案例研究',
  PROGRAMS_AND_PROMOTIONS: '计划和促销活动',
  AUTHENTIC_AVAYA: 'Authentic Avaya',
  PERSPECTIVES: '前景',
  AVAYA_CONNECTED_BLOG: 'Avaya 关联博客',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: '解决方案查找工具',
  INFO_FOR: '信息',
  DEVELOPERS: '开发人员',
  CHANNEL_PARTNERS: '渠道合作伙伴',
  TECHNOLOGY_PARTNERS: '技术合作伙伴',
  CONSULTANTS: '顾问',
  INVESTORS: '投资者',
  MEDIA_ANALYSTS: '媒体分析师',
  SUPPLIERS: '供应商',
  CONNECT_WITH_US: '与我们交流',
  FIND_A_CHANNEL_PARTNER: '查找渠道合作伙伴',
  FIND_A_TECHNOLOGY_PARTNER: '查找技术合作伙伴',
  EXECUTIVE_BRIEFING_CENTER: '创新体验中心',
  AVAYA_LEARNING_SERVICES: 'Avaya 学习服务',
  CONTACTS: '联系人',
  ABOUT_AVAYA: '关于 Avaya',
  EVENTS: '事件',
  NEWSROOM: '新闻编辑部',
  INVESTOR_RELATIONS: '投资者关系',
  CORPORATE_RESPONSIBILITY: '企业责任',
  OUR_COMPANY: '我们的公司',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'International Avaya Users Group - IAUG',
  CAREERS: '拓展事业',
  YOUR_PERSONAL_LINK: '您的个人链接',
  SITEMAP: '站点地图',
  TERMS_OF_USE: '使用条款',
  PRIVACY: '隐私',
  COOKIES: 'Cookie',
  AVAYA_INVOICE: '发票',
  IP_OFFICE_ACCOUNT_NAME: 'Avaya Cloud 帐户名',
  IP_OFFICE_PLAN_NUMBER: 'Avaya Cloud 计划号码',
  IP_OFFICE_PHONE_APPLICATION: 'Avaya Cloud 解决方案软电话',
  IP_OFFICE_PHONE_DESCRIPTION: 'Avaya Cloud 解决方案软电话让用户可在单一界面中轻松访问所有通信通道。Avaya Cloud 解决方案软电话让您可登录自己的 Avaya Cloud 解决方案，以及使用 PC 从座机分机拨打和接收语音和视频呼叫。Avaya Cloud 解决方案的标准用户和高级用户订阅中免费包含软电话。',
  PLAN_MONTH_1_MONTH_1: '每月计划（无设备积分）',
  PLAN_YEAR_1_MONTH_1: '1 年计划 | 按月计费',
  PLAN_YEAR_1_YEAR_1: '1 年计划，一次付清',
  PLAN_YEAR_2_MONTH_1: '2 年计划 | 按月计费',
  PLAN_YEAR_2_YEAR_1: '2 年计划 | 按年计费',
  PLAN_YEAR_2_YEAR_2: '2 年计划，一次付清',
  PLAN_YEAR_3_MONTH_1: '3 年计划 | 按月计费',
  PLAN_YEAR_3_YEAR_1: '3 年计划 | 按年计费',
  PLAN_YEAR_3_YEAR_3: '3 年计划，一次付清',
  PLAN_YEAR_5_MONTH_1: '5 年计划 | 按月计费',
  ACCORDING_TO_PLAN: '根据计划',
  TOTAL_USER_PLAN_FEE: '用户计划总费用',
  HEALTHCARE_DENY_MESSAGE: '感谢您选择 Avaya Cloud 解决方案，很遗憾，我们尚不符合 HIPAA 的要求，因为您所在的行业是医疗保健业，因此无法向您提供我们的服务。我们必定会在获得认证后通知您，希望届时您仍然会选择我们！如果有任何问题或疑问，请随时通过以下电子邮件地址与我们联系：<a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a>。',
  SELECT_YOUR_IP_OFFICE_DEVICES: '开始使用 Avaya Cloud 解决方案<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  SELECT_YOUR_IP_OFFICE_NUMBER: '选择您的 Avaya Cloud 解决方案<sup style="font-size:50%;vertical-align:middle;">™</sup> 号码',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: '调整用户并向其分配设备。',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: '添加要用于您的 Avaya Cloud 解决方案的电话号码。',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: '向您的解决方案分配电话号码。',
  INVITE_A_NEW_AGENT: '邀请新代理',
  I_WANT_TO_INVITE_A: '我要邀请',
  CONTACT_EMAIL: '联系人电子邮件地址',
  CONTACT_NAME: '联系人姓名',
  COMPANY_NAME: '公司名称',
  CONTACT: '联系人',
  COMPANY_IS_INCORPORATED: '公司合并',
  INDIVIDUAL: '个人',
  INDIVIDUALS: '个人',
  SEND_INVITATION_EMAIL: '发送邀请电子邮件',
  SENDING_INVITATION_EMAIL: '正在发送邀请电子邮件...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: '已成功发送邀请',
  ALL_FIELDS_ARE_REQUIRED: '所有字段为必填',
  PARTNER_NOT_FOUND: '未找到合作伙伴',
  SALE_AGENT_REGISTRATION: '销售代理注册',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: '只需填写以下表单即可成为销售代理',
  VIEW: '查看',
  COMPANIES: '公司',
  ADD_A_PARTNER: '添加合作伙伴',
  ADD_PARTNER: '添加合作伙伴',
  PARTNERS_PERSONAL_LINK: '合作伙伴的个人链接',
  MASTER_SALES_AGENT: '主要销售代理',
  AVAYA_J129_LABEL: 'J129 IP 电话',
  AVAYA_J129_DESCRIPTION: '价格实惠的实用 SIP 电话可提供所有必要的呼叫处理功能。此电话可以提供各种规模企业的用户所需的关键功能。该电话的单线路呼叫显示屏支持两种呼叫状态。立即购买优于市场现有产品的功能更强大的话机。',
  AVAYA_J169_LABEL: 'J169 IP 电话',
  AVAYA_J169_DESCRIPTION: '价格实惠的实用 SIP 电话可提供所有必要的呼叫处理功能。此电话可以提供各种规模企业的用户所需的关键功能。该电话的单线路呼叫显示屏支持两种呼叫状态。立即购买优于市场现有产品的功能更强大的话机。',
  AVAYA_J179_LABEL: 'J179 IP 电话',
  AVAYA_J179_DESCRIPTION: '价格实惠的实用 SIP 电话可提供所有必要的呼叫处理功能。此电话可以提供各种规模企业的用户所需的关键功能。该电话的单线路呼叫显示屏支持两种呼叫状态。立即购买优于市场现有产品的功能更强大的话机。',
  AVAYA_K175_LABEL: 'Avaya Vantage™',
  AVAYA_K175_DESCRIPTION: '价格实惠的实用 SIP 电话可提供所有必要的呼叫处理功能。此电话可以提供各种规模企业的用户所需的关键功能。该电话的单线路呼叫显示屏支持两种呼叫状态。立即购买优于市场现有产品的功能更强大的话机。',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: '9641GS IP 座机',
  AVAYA_9641G_DESCRIPTION: 'Avaya 9641GS 是多线路高级座机，非常适合超长时间使用电话的用户以及依赖智能通信和生产力提升功能的用户。9641GS 配备 5.0 英寸的彩色图形显示器、更大的触摸屏和高清音频质量。其宽频音频编解码器可在所有音频接口（包括话筒、耳机和扬声器）上提供卓越的音频性能。',
  AVAYA_9608G_LABEL: '9608G IP 座机',
  AVAYA_9608G_DESCRIPTION: '9608G 座机是经济高效、功能完善的电话，支持集成千兆位以太网结构，采用黑白显示屏。以太网电源可简化部署，并且其宽频音频编解码器可提供卓越的音频性能。此座机面向各种规模的企业设计，可接入八条线路并且包含可集中管理的图形标签。',
  AVAYA_9611G_LABEL: '9611G IP 座机',
  AVAYA_9611G_DESCRIPTION: '9611G 型号包含集成的千兆位接口和 USB 接口。3.5 英寸的彩色图形显示屏具有白色的后灯和可集中管理的图形标签。以太网电源可简化部署，并且其宽频音频编解码器可提供卓越的音频性能。',
  AVAYA_PHONE_B179_LABEL: 'B179 SIP 会议电话',
  AVAYA_PHONE_B179_DESCRIPTION: '经 Tolly 测试，这款基于 SIP 的灵活会议电话可通过 Avaya 获得专利的宽频音频技术 OmniSound 2.0 提供清晰自然的声音。该电话具备智能功能，可实现更高效的电话会议。使用会议指南呼叫预先编程的群组。可通过 Web 界面方便地导入和导出联系人详细信息。您可以使用个人用户配置文件功能创建自己的联系人列表。',
  HAVE_LARGE_NUMBERS_OF_USERS: '用户数量众多？',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: '请查看我们的批量采购折扣明细。',
  DEVICE_FEE: '设备费用',
  UP_TO_DEVICE_CREDITE_PER_USER: '每个用户高达 {$} 设备积分',
  PROMOTION_REMAINING_DETAIL_INFO: '您还有 <b>{0}</b> 促销设备积分尚未使用。请注意，所有剩余积分将在您购买后失效，且不会计入帐户供未来购买使用。',
  VIEW_USER_FEATURES: '查看用户功能',
  FREE_DEVICES_PER_USER_INFO: '{0}（每个用户高达 {1} 设备积分）',
  VALUE_OF_DEVICE_CREDIT: '{0} 个用户 = {0}（设备积分总计）',
  PROMOTION_DELAYED_BILLING_INFO: '促销：账单周期正式开始后，我们将提供详细收据，并向您的信用卡收取未结款项。',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: '请选择代理以完成订单',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: '请提供有效的域名 (example.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: '您的 Avaya Cloud 解决方案系统已准备就绪！',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: '您的 Avaya Cloud 解决方案系统已准备就绪！',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Avaya Cloud 解决方案电话号码',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Avaya Cloud 解决方案 SIP 域名',
  IP_OFFICE_SIP_DOMAIN_ID: 'Avaya Cloud 解决方案 SIP 域名',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: '您的 Avaya Cloud 解决方案系统正在配置中。',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: '感谢您下订单。我们目前正在设置您的 Avaya Cloud 解决方案系统，配置完成后，我们将与您联系。<br />如有任何问题或疑问，请随时与 Avaya Cloud 解决方案支持团队联系 {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: '此帐户配置失败',
  ERROR_CODE: '错误代码',
  ERROR_MESSAGE: '错误消息',
  ADMIN_PORTAL_LINK: '管理员门户链接',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Avaya Cloud 解决方案默认用户密码',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Avaya Cloud 解决方案电话号码',
  IP_OFFICE_BASIC_EXTENSION_RANGE: '基本用户分机',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: '标准用户分机',
  IP_OFFICE_POWER_EXTENSION_RANGE: '高级用户分机',
  IP_OFFICE_DEFAULT_USER_PIN: '默认用户 PIN 码',
  IP_OFFICE_SAME_AS_PIN: '与分机相同（例如：200）',
  IP_OFFICE_ORDERID: 'Avaya Cloud 解决方案订单 ID',
  IP_OFFICE_HOST_NAME: '您的 Avaya Cloud 解决方案主机名称',
  IP_OFFICE_IP_ADDRESS: '您的 Avaya Cloud 解决方案 IP 地址',
  IP_OFFICE_SUBSCRIPTIONID: 'Avaya Cloud 解决方案订阅 ID',
  CALCULATING: '正在计算...',
  RESET_ALL_PARTNERS: '清除合作伙伴数据',
  ERROR_GETTING_AGENTS: '检查代理时出现错误。请重试',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: '您的团队中已经有代理使用此电子邮件地址',
  AUTO_APPROVE_ACTIVATE_AGENT: '自动批准/激活代理',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: '您的团队中已经有代理使用此电子邮件地址',
  MASTER_SALES_AGENT_PORTAL: '主要销售代理门户',
  SALES_AGENT_PORTAL: '销售代理门户',
  E911_ADDRESS: 'E911 地址',
  OVERVIEW: '概述',
  ADD_COMPANY_OR_SALES_AGENT: '添加公司或代理',
  ADD_AN_AGENT: '添加代理至',
  INACTIVE: '非活动',
  AGENTS_PERSONAL_CONNECTION_LINK: '代理的个人关联链接',
  PURCHASE_DATE_AND_CUSTOMER: '购买日期和客户',
  ORDER_DETAILS: '订单详细信息',
  SELECT_AGENT: '所有代理',
  FROM: '从',
  TO: '至',
  EXPORT_REPORT: '导出报告',
  NO_SALES_FOUND: '未找到销售',
  ADD_A_COMPANY: '添加公司',
  AUTO_APPROVE_COMPANY: '自动批准公司',
  AUTO_ACTIVATE_AGENT: '自动激活代理',
  ADD_COMPANY: '添加公司',
  ADD_COMPANY_NAME_AGENT_ADMIN: '添加 {COMPANY_NAME} 代理/管理员',
  ADD_AGENT_ADMIN: '添加代理/管理员',
  ALL_COMPANIES: '所有公司',
  START_DATE: '开始日期',
  HEY: '您好：',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: '我们是您的客户成功经理。我们将帮您通过 Avaya Cloud 解决方案获得价值。您的 Avaya Cloud 解决方案支持团队也包括我们的技术支持团队 - <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>。',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: '我们希望在接下来的几天内安排一次开始呼叫，目的是介绍您的支持团队和完成系统配置。<strong>请通过以下电子邮件地址与我联系，告知我们合适的日期和时间，以便展开一次时长一小时的开始呼叫：<a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a>。<strong>',
  START_USING_YOUR_IP_OFFICE: '立即开始使用 Avaya Cloud 解决方案系统！',
  BELOW_ARE_DETAILS: '以下是您的系统帐户信息、用户凭据和应用程序下载：',
  YOUR_IP_OFFICE_INFO: '您的系统信息：',
  LOGIN_INFO_TABLE: '您的用户信息图表：',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: '您的所有用户都可以使用上述信息登录其个人云用户门户来配置自己的信息、调整呼叫转接、收听语音邮件等。',
  AVAILABLE_APPLICATIONS_FOR_USERS: '用户可用的应用程序：',
  DO_NOT_HESITATE_TO_EMAIL_US: '如有任何问题或疑问，请随时通过以下电子邮件地址与我们联系：<a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a>！',
  THANK_YOU: '谢谢！',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web（Chrome 扩展程序）</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions Soft Console (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">安装文档</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">安装文档</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">安装文档</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">安装文档</a>',




  USER_NAMES_COLUMN: '用户名',
  EXTENSIONS_COLUMN: '分机',
  TEMP_PIN_COLUMN: 'PIN 码',
  TEMP_PASSWORD_COLUMN: '密码',
  USER_TYPE_COLUMN: '用户类型',
  DEVICE_MODEL_COLUMN: '设备',
  POWER_USER: '高级',
  STANDARD_USER: '标准',
  BASIC_USER: '基本',
  ORDERID: '订单 ID',
  ACCOUNT_NAME: '帐户名称',
  HOST_NAME: '主机名',
  ADMIN_PORTAL: '管理员门户',
  IP_ADDRESS: 'IP 地址',
  PHONE_NUMBER: '电话号码',
  TEMPORARY_PHONE_NUMBER: '临时电话号码',
  EXCITING_TIMES_AHEAD: '未来激动人心的时刻',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: '域名 {DOMAIN_NAME} 无效，或者已被其他公司使用。',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: '域名 {1} 无效，或者已被其他公司使用。',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: '系统无法验证您的公司。请重试',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: '对于任何不适用的信息（如果有），请与 Avaya Cloud 支持团队联系： ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: 'Avaya Cloud 帐户未能开始配置',
  LEGAL: '法律',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: '选择 1 年计划（或更多）并接收每个用户购买任意设备所获得的积分。限时提供。',
  USER_PORTAL: '用户门户',
  E_911: 'E911',
  DECLINE: '拒绝',
  ACCEPT: '接受',
  PRINT: '打印',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: '请同意上述所有条款以完成订单',
  ASSING_A_DEVICE_TO_YOUR_USERS: '为用户分配设备。',
  SELECT: '选择',
  USER_DETAILS: '用户详细信息',
  DEVICE_DETAILS: '设备详细信息',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: '请仔细阅读我们的服务条款，然后再接受。',
  PARTNER_ORDERS_RECORDS_HINT: '*所有销售记录仅供参考。官方和最终销售报告将由 Avaya 财务部门根据主要销售代理协议提供。',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: '请选择销售代理以创建报价',
  COMPANY_DETAILS: '公司详细信息',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: '加上适用税费。',
  SELECT_PRODUCT: '选择产品',
  CLOUD_UC_SMALL_MONTH1: 'Cloud UC 基础版（每月计划）',
  SMALL: '小',
  CLOUD_UC_SMALL_MONTH12: 'Cloud UC 基础版（1 年计划）',
  CLOUD_UC_SMALL_3YEARS: 'Cloud UC 基础版（3 年计划）',
  CLOUD_UC_SMALL_5YEARS: 'Cloud UC 基础版（5 年计划）',
  MEDIUM: '中',
  CLOUD_UC_MEDIUM_MONTL1: 'Cloud UC 商务版（每月计划）',
  CLOUD_UC_MEDIUM_MONTH12: 'Cloud UC 商务版（1 年计划）',
  CLOUD_UC_MEDIUM_3YEARS: 'Cloud UC 商务版（3 年计划）',
  CLOUD_UC_MEDIUM_5YEARS: 'Cloud UC 商务版（5 年计划）',
  LARGE: '大',
  CLOUD_UC_LARGE_MONTL1: 'Cloud UC 大型（即用即付）',
  CLOUD_UC_LARGE_MONTL12: 'Cloud UC 大型（年度计划）',
  CLOUD_UC_SMALL_SHORT_INFO: '1 - 99 名员工',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100 - 999 名员工',
  CLOUD_UC_LARGE_SHORT_INFO: '1000 名员工以上',
  SELECTED: '已选',
  BASIC_PHONE_SERVICE: '基本电话服务',
  UNLIMITED_NATIONAL_WIDE: '无限国内长途',
  STANDARD_FEATURES: '标准功能',
  HOW_MANY_USERS: '您需要多少用户？',
  ADD_ON_ADDITIONAL_FEATURES: '其他功能',
  ONETIME_FEE: '一次性费用',
  RECURRING_FEE: '定期支付费用',
  SELECT_MAIN_NUMBER: '选择总机号码',
  TOLL_FREE: '免费号码',
  LOCAL_NUMBER: '本地号码',
  TRANSFER_NUMBER: '转接号码',
  USERS_COUNT: '{qty} 个用户',
  DEVICES_COUNT: '{qty} 台设备',
  UC_OFFER_TITLE: '我们为您准备了合适的解决方案！',
  UC_OFFER_DESCRIPTION: '无论您是小型、中型还是大型企业，都能如您所愿！您的企业属于哪种类型？',

  // 'BASIC_PHONE_SERVICE': '基本电话服务',

  TAX_CALC_ERROR_MSG: '无法计算税费。请检查账单地址是否正确。',
  'VIOLATION.FIELD_IS_EMPTY': '{1} 必填',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} 必填',
  'VIOLATION.FIELD_VALUE_INVALID': '{1} 值无效',
  'VIOLATION.FIELD_VALUE_INVALID2': '{1} 值无效',
  'VIOLATION.TAX_CALCULATION_FAILED': '无法计算税费',
  'VIOLATION.AGREE_ON_LEGAL_DOC': '您必须阅读并同意“{1}”',
  'VIOLATION.CART_IS_EMPTY': '购物车为空',
  'VIOLATION.CART_IS_TOO_BIG': '购物车中商品过多',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '{1} 已移出购物车',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': '{1} 数量从 {2} 调整为 {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': '{1} 折扣从 {2} 调整为 {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': '无法使用 {2} 货币将使用 {1} 货币的商品添加到购物车',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': '未定义折扣规则 {1}',
  'SALESMODELRULE.UNKNOWN_ERROR': '未知错误',
  'SALESMODELRULE.INVALID_PARAMETER': '无效参数：{1}',
  ONE_TIME: '一次性',
  ADDON_PRICING_HINT: '*加载项按座席定价，并且适用于所有用户。可在您的管理员门户中完成购买后为用户添加特定加载项。',
  ADD_TO_CART_HINT: '完成上述步骤以添加到购物车',
  ITEM_UNITS: '{qty} 个单位',
  ADDONS_COUNT: '{qty} 个加载项',
  ADDON_COUNT: '{qty} 个加载项',
  MULTIPLE_TYPES: '多个类型',
  MIXED: '混合',
  FREE_PRICE: 'FREE',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: 'UC 基础版',
  UC_ESSENTIALS_DESCRIPTION: '适用于任何规模企业的最佳云通信。',
  UC_BUSINESS: 'UC 企业版',
  UC_BUSINESS_DESCRIPTION: '借助云中的出色企业通信功能助力公司的发展',
  UC_BUSINESS_POWER_PACKAGE: '升级为高级用户',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>直接电话号码：</strong>专用的唯一号码，任何人都可以直接呼叫您，而无需通过办公室总机号码或接线员（虚拟或人工）进行呼叫。</li><li><strong>直接视频呼叫：</strong>向您的点对点电话呼叫中添加视频。</li><li><strong>Salesforce© 集成：</strong>直接在 Salesforce 内部为最终用户提供完整、功能丰富的通信。</li><li><strong>Google© 集成：</strong>直接从在 Google Chrome 以及您的所有 Google 应用中进行基于浏览器的实时通信。</li><li><strong>Skype for Business© 集成：</strong>借助 Skype for Business 实现现代化的简单、易操作的协作体验。</li></ul>',
  SHOW_MORE: '显示更多',
  HIDE: '隐藏',
  VIEW_COMPLETE_FEATURE_LIST: ' 查看完整功能列表',
  FILTER_BY: '过滤条件',
  UC_OFFERS: 'UC 解决方案',
  PAY_MONTHLY: '按月付费',
  PAY_ANNUALLY: '按年付费',
  COMING_SOON: '即将推出',
  TAX_CALC_ERROR_MSG: '无法计算税费。请检查账单地址是否正确。',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: '请输入国家/地区的名称以查看当前的长途费率。',
  LONG_DISTANCE_RATE_NOT_FOUND: '未找到此国家/地区的长途费率，请联系 {CUSTOMER_SUCCESS_EMAIL} 获取有关拨打此国家/地区的长途呼叫的信息。',
  AREA_CODE: '区号',
  INVALID_CREDIT_CARD_ZIP: '信用卡与邮政编码不匹配。',
  VIEW_LONG_DISTANCE_RATES: '查看长途费率',
  LONG_DISTANCE_SUBTITLE_TEXT: '我们的长途呼叫费率很低，可让您与全球各地的所有联系人保持联系。',
  RATES_SUBJECT_TO_CHANGE: '*费率如有变更，恕不另行通知。',
  CREDIT_CARD_DECLINED: '信用卡遭到拒绝。',
  ENTER_COUNTRY_NAME: '输入国家/地区名称',
  ADD_TO_CART: '添加至购物车',
  UPDATE_CART: '更新购物车',
  PER_USER: '每用户',
  COMPARE_UC_OFFERS: '比较 UC 产品',
  PROCEED_TO_CHECKOUT: '去结算',
  BEFORE_APPLICABLE_TAXES: '* 税前',
  YEAR_PLAN: '1 年计划',
  YEARS_PLAN: '{0} 年计划',
  MONTHS_PLAN: '{0} 月计划',
  ENTER_NUMBER_OF_USERS: '为此解决方案输入用户数量',
  YEAR: '年',
  BILLED_MONTH: '按月计费',
  COMPANY_INCORPORATED: '合并',
  COMPANY_NOT_INCORPORATED: '不合并',
  EXISTING_CONFIG_WARNING: '您有 <br/><b>{0}</b> 的现有配置。',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: '是否要放弃当前配置？',
  DISCARD_MY_CONFIGURATION: '放弃我的配置',
  DISCARD: '放弃',
  EDIT_MY_CONFIGURATION: '编辑我的当前配置',
  CONTINUE: '继续',
  SELECT_A_PLAN: '选择计划',
  PROMOTION_DETAIL_INFO: '*您总共选择了 <b>{0} 位用户！</b>设备积分<br/>共计 <b>{1}</b>。',
  BILLED_MONTH_FREQUENCY: '每 {0} 个月结算一次',
  BILLED_YEAR_FREQUENCY: '每 {0} 年结算一次',
  CONTACT_OUR_CUSTOMER_CARE: '联系我们的客户服务团队',
  NEED_HELP_INFO: '需要帮助？我们的客户服务团队随时帮您解决任何可能存在的疑问、问题或向您提供相关信息。',
  REMOVE: '删除',
  REMOVE_ITEM_FROM_CART_WARNING: '是否要从购物车中删除 <b>{0}</b>？',
  NO_ITEM_IN_THE_CART: '您的购物车中没有任何商品。',
  CONTINUE_SHOPPING: '继续购物',
  TOTAL_TAXES: '总税费',
  UC_SOLUTIONS: 'UC 解决方案',
  UNIFIED_COMMUNICATIONS: '统一通信',
  ADD_ONS: '加载项',
  SYSTEM_ADDONS: '系统加载项',
  ADD_DEVICES: '添加设备',
  SELECT_UPTO_DEVICES: '最多可为 <b>{1}</b> 选择 (<b>{0}</b>) 台设备',
  DONE: '完成',
  SELECT_DEVICES: '选择设备',
  EDIT_DEVICE_SELECTION: '编辑设备',
  ESSENTIAL_USERS: '基础用户',
  BUSINESS_USERS: '商务用户',
  POWER_USERS: '高级用户',
  N_A: '不适用'
}
