export default {
  APPAUTH_CALLBACK_ERRORMESSAGE: '無法解密來自帳戶系統的資料',
  PHONE_TYPES: '電話類型',
  IMAGINE_A_BETTER_WAY: '想像一種更好',
  OF_DOING_THINGS: '的做事方式。',
  GET_STARTED: '準備開始',
  PURCHASE: '購買',
  DOWNLOADS_AND_EXTENSIONS: '下載與延伸',
  MAKE_THE_MOST_OF_YOUR_ZANG_PRODUCTS_WITH_THESE_MUST_HAVE_ADDONS: '使用這些必備附加程式充分利用你的Zang產品！',
  ALL: '全部',
  REFERRAL_AGENT: '推薦代理',
  SALES_AGENT: '銷售代理',
  CART: '購物車',
  PARTNER_PROGRAMS: '合作夥伴計畫',
  HOME: '主頁',
  MANAGE_CREDIT_CARDS: '管理信用卡',
  MANAGE_PAYMENT_OPTIONS: '管理付款選項',
  MANAGE_BILLING_ACCOUNT: '管理收費帳戶',
  LIMIT: "限制",
  MY_PROFILE: '我的個人檔案',
  MY_SETTINGS: '我的設定',
  MY_PARTNER_PORTAL: '我的合作夥伴入口網站',
  CLEAR_ZANG_OFFICE: '清除Zang Office',
  CLEAR_ZANG_SPACES: '清除Zang Spaces',
  FEATURE_BREAKDOWN: '功能細目分類',
  PLAN_BREAKDOWN: '計畫細目分類', //sales, business plan
  THE_BUSINESS_PHONE_YOU_NEED_AT_A_PRICE_YOULL_LOVE: '以最相宜的價格為你提供所需的辦公電話。',
  IMAGINE_WHAT_YOU_CAN_GET_DONE_IN_ZANG_SPACES: '了解Zang Spaces可協助你解決哪些問題',
  A_DISCOUNT_OF_50_PERCENT_WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '在你結賬後，50%的折扣將套用到你的總金額',
  HURRICANE_HARVEY_MESSAGE: 'Avaya 與 Zang 希望能幫助受颶風「哈維」和可能受颶風「艾瑪」影響的企業。德州、路易斯安那州、佛羅里達州、阿拉巴馬州、喬治亞州、北卡羅萊納州、南卡羅來納州、田納西州與密西西比州的公司可立即<b>獲得 Zang Office</b> 與 <b>Zang Spaces</b> 3 個月的免費使用。',
  LEARN_MORE: '瞭解更多',
  NEW_AVAYA_VANTAGE_IS_NOW_AVAILABLE: 'AVAYA VANTAGE™ 現已可用',
  NEW: '全新！',
  EXPERIENCE_THE_BEST_OF_ZANG_OFFICE_WITH_THIS_ALL_GLASS_EASY_TO_USE_VOICE_VIDEO_AND_CHAT_COLLABORATION_PHONE: '使用這個全玻璃、容易操作的語音、視訊與聊天協作電話，獲得最佳的 Zang Office 體驗。',
  LOG_IN: '登入',
  SIGN_UP: '註冊',
  SIGN_OUT: '登出',
  SIGN_IN: '登入', //login to the system, connect
  ADMINISTRATION: '管理',
  PRODUCTS: '產品',
  ORDERS: '訂單',
  PAGES: '頁',
  CUSTOMERS: '客戶',
  USERS: '使用者',
  PLANS: '計畫',
  ZANG_OFFICE: 'Zang Office',
  IP_OFFICE: 'IP Office',
  CDRS: 'Cdrs',
  CDR_CHECKS: 'Cdr檢查',
  PARTNERS: '合作夥伴',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_ZANG_OFFICE_THE_ORDER_CANNOT_BE_PLACED: '你似乎已經購買 Zang Office。你不能再提交 Zang Office 訂單。',
  IT_SEEMS_THAT_YOU_HAVE_ALREADY_PURCHASED_IP_OFFICE_FOR_THIS_COMPANY_THE_ORDER_CANNOT_BE_PLACED: '你似乎已為此公司購買 Avaya 雲端，請選擇其他公司。',
  PARTNER_CONNECTIONS: '合作夥伴連接',
  CHECK_OUT_GENERAL_FATAL_ERROR: '提交訂單時出錯。請聯絡Zang支援部門({SUPPORT_EMAIL})，瞭解更多資訊。',
  APPLICATION_GENERAL_FATAL_ERROR: '提交申請時出錯。請聯絡Zang支援部門({SUPPORT_EMAIL})，瞭解更多資訊。',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_CONTINUE: '請選擇至少一個使用者類型以繼續。',
  BACK: '返回',
  SAVE_CHANGES: '儲存變更',
  ARE_YOU_SURE_YOU_WANT_TO_PROCEED: '你確定要繼續嗎？',
  IT_SEEMS_THAT_YOU_HAVE_PLACEHOLDER_REMAINING_OF_FREE_MONEY_TO_SPEND_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_THAT_YOU_WILL_NOT_BE_ABLE_TO_CARRY_OVER_ONCE_YOUR_ORDER_HAS_BEEN_SUBMITTED_DO_YOU_WISH_TO_CONTINUE: '你還有 {PLACEHOLDER} 的抵用金可用於購買任何裝置。提交訂單後，抵用金即用罄。',
  JUST_A_REMINDER: '提醒你',
  LAST_CHANCE: '最後機會',
  IM_GOOD_PLACE_MY_ORDER: '沒問題，提交我的訂單',
  BUY_MORE_DEVICES: '購買更多裝置',
  YES_PLACE_MY_ORDER: '是，提交我的訂單',
  NO_THANKS: '不要，謝謝！',
  YES: '是',
  ABOUT_US: '關於我們',
  NEWS_AND_PRESS: '新聞通訊',
  CARREERS: '電訊商',
  CONTACT_US: '聯絡我們',
  THANK_YOU_FOR_SHOPPING_WITH_US_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: '感謝你向我們購買。你的訂單詳情如下。',
  PLEASE_CONTACT_EMAIL_FOR_THIS_INFORMATION: '如需了解此資訊，請聯絡 <a href="mailto:{EMAIL}">{EMAIL}</a>',
  ORDER_CUSTOMER_SERVICE_SYSTEM_SETUP_INFO: '你的系統備妥時，我們的客戶成功與技術支援團隊便會與你聯絡。<br/><br/><b>請注意，設定系統可能需要長達一小時。</b>',
  QUESTION_CUSTOMER_SERVICE: '如有任何疑問，請發送電郵至 <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a> 與我們聯絡！',
  BLOG: '網誌',
  FAQS: '常見問題',
  DOCUMENTATION: '說明文件',
  TERMS_OF_SERVICE: '服務條款',
  HELP: '說明',
  PRIVACY_STATEMENT: '隱私聲明',
  GENERAL_PRIVACY_STATEMENT: '一般私隱聲明',
  GENERAL_TERMS_OF_SERVICE_AVAYA_CLOUD_IP_OFFICE: '一般服務條款 - Avaya 雲端解決方案',
  ZANG_INC_ALL_RIGHTS_RESERVED: 'Zang, Inc. 保留所有權利。',
  PROCESSING: '正在處理',
  PLEASE_BE_PATIENT_THE_PROCESS_MIGHT_TAKE_SOME_TIME: '請耐心等待。該過程可能需要一些時間',
  OPEN_IN_A_NEW_TAB: '在新標籤中開啟',
  GOT_IT: '收到！',
  THIS_ACTION_WILL_HAVE_THE_FOLLOWING_RESULTS: ' 此動作將產生以下結果：',
  DELETE_THE_SUBSCRIPTION_FOR_THIS_PLAN: '刪除此計畫的每月訂閱',
  DISABLE_ANY_ACCOUNT_ON_ANY_THIRD_PARTY_SYSTEMS: '在任何第三方系統上停用任何帳戶',
  CHANGE_THE_STATUS_OF_THIS_PLAN_TO_DISABLED: '將此計畫的狀態變更為已停用',
  LAST_ACTION_STEPS: '最後行動步驟',
  ADDONS_ARE_PURCHASED_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL_ONCE_THE_ACCOUNT_HAS_BEEN_CREATED: '帳戶建立之後，即可透過 Zang Office 管理門戶購買附加程式。',
  TYPE: '類型',
  ADMIN: '管理員',
  THIS_USER_WILL_BE_THE_PRIMARY_BILLING_CONTACT_FOR_THE_CORPORATE_ACCOUNT_IT_CAN_BE_CHANGED_AT_ANYTIME_THROUGH_THE_ZANG_OFFICE_ADMIN_PORTAL: '該使用者會設定為此公司帳戶的主要/帳單聯絡人。您隨時可以透過 Zang Office 管理門戶變更此設定。',
  DESCRIPTION: '說明',
  SUCCESS: '成功',
  REQUEST_CANCELATION: '請求取消',
  WELL_THIS_ISNT_GOOD_SORRY_TO_HEAR_THAT_YOU_WANT_TO_LEAVE: '好吧，這不是很好！聽說你要離開，很遺憾。',
  PLEASE_FILL_OUT_THE_FORM_BELOW_TO_START_THE_CANCELATION_PROCESS_A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '請填寫下表以開始取消過程。客戶成功部門的成員將在1-2個營業日內審核並跟進你的請求，使其成為一個無縫的過程。',
  YOUR_NAME: '你的姓名',
  COMPANY: '公司',
  SERVICE: '服務',
  REASON_FOR_CANCELING: '取消的理由',
  SUBMIT: '提交',
  EXIT: '退出',
  REQUEST_SUBMITTED: '請求已提交！',
  A_MEMBER_OF_OUR_CUSTOMER_SUCCESS_DEPARTMENT_WILL_REVIEW_AND_FOLLOW_UP_YOUR_REQUEST_WITHIN_1_2_BUSINESS_DAYS_TO_MAKE_THIS_A_SEAMLESS_PROCESS: '客戶成功部門的成員將在1-2個營業日內審核並跟進你的請求，使其成為一個無縫的過程。',
  DATE: '日期',
  PRODUCT: '產品',
  USER: '使用者',
  STATUS: '狀態',
  ACTIONS: '動作',
  VIEW_DETAILS: '檢視詳情',
  DISABLE: '停用',
  ENABLE: '啟用',
  CANCEL: '取消',
  PLAN_DETAILS: '計畫詳情',
  SUMMARY: '摘要',
  QUANTITIES: '數量',
  TOTAL_INCLUDES_THE_PRICES_OF_PLAN_FEATURES: '*總計包括計畫功能的價格',
  TOTAL: '總計',
  BILLED: '已收費',
  PLAN_INFORMATION: '計畫資訊',
  UPDATE_PLAN: '更新計畫',
  ADMIN_ACTIONS: '管理員動作',
  NAME_ON_CREDIT_CARD: '信用卡上的姓名',
  CREDIT_CARD_BRAND: '信用卡品牌',
  VISA: '簽證',
  AMERICAN_EXPRESS: '美國運通',
  MASTER_CARD: 'Master卡',
  CREDIT_CARD_NUMBER: '信用卡卡號',
  EXPIRATION: '過期',
  MONTH: '月',
  YEAR: '年',
  SECURITY_CODE: '安全碼',
  THE_CODE_ON_THE_BACK_OF_YOUR_CREDIT_CARD: '信用卡背面的代碼',
  BACK_TO_CHECKOUT: '返回到結賬台',
  NO_ORDERS_FOUND: '未找到訂單',
  ADD: '新增',
  USE_THE_FORM_ABOVE_TO_ADD_A_NEW_CREDIT_CARD_PLEASE_MAKE_SURE_YOUR_FILL_ALL_THE_FIELDS: '使用上表新增一張新的信用卡 請確保填寫所有欄位',
  NUMBER: '號碼',
  EXPIRES: '過期',
  DELETE: '刪除',
  ITEM_DETAILS: '項目詳情',
  FEE: '費用',
  ITEMS: '項目',
  SEARCH_BY_CONFIRMATION: '透過確認搜尋',
  CONFIRMATION: '確認',
  CHECKOUT_STATUS: '結賬狀態',
  ORDER_STATUS_PROCESS: '訂單狀態程序',
  CREATED_ON: '建立日期',
  ORDER_SUMMARY: '訂單摘要',
  APPROVED: '已批准', //example: partner application approved
  REJECTED: '已拒絕', //example: partner application rejected
  APPROVE: '批准', //example: partner application approved
  REJECT: '拒絕', //example: partner application rejecte
  PENDING: '等待中', //example: partner application pending
  EDIT: '編輯',
  ONE_TIME_FEE: '一次性費用',
  SUB_TOTAL: '小計',
  TAXES: '稅收',
  CHANGES: '變更',
  CREATE_A_QUOTE: '建立報價',
  EXTRA_INFORMATION: '額外資訊',
  THANK_YOU_FOR_YOUR_ORDER: '感謝你的訂單',
  ORDER_CONFIRMATION: '訂單確認',
  INVALID_ORDER: '無效的訂單',
  DONT_WORRY_WE_VE_ALSO_EMAILED_THIS_TO_YOU: '別擔心，我們也透過電郵將此項傳送給你 :)',
  HELLO: '你好',
  THANK_YOU_FOR_SHOPPING_WITH_US_WE_LL_SEND_A_CONFIRMATION_ONCE_YOUR_ITEMS_HAVE_SHIPPED_YOUR_ORDER_DETAILS_ARE_INDICATED_BELOW: '感謝你向我們購買。一旦你的物品已發貨，我們會向你傳送確認。你的訂單詳情如下。',
  ACCOUNT_INFORMATION: '帳戶資訊',
  BILLING_INFORMATION: '收費資訊',
  SHIPPING_INFORMATION: '發貨資訊',
  NAME: '姓名',
  EMAIL: '電郵',
  SEARCH: '搜尋',
  CLEAR: '清除',
  PARTNER: '合作夥伴',
  NO_PARTNERS_FOUND: '找不到合作夥伴',
  A_PARTNER_CONNECTION_IS_CREATED_WHEN_CUSTOMER_LANDS_ON_THE_STORE_FROM_A_PARTNERS_PERSONAL_LINK: '當客戶從合作夥伴的個人連結登入商店時，將建立合作夥伴連接。',
  CUSTOMER: '客戶',
  AGENT: '代理',
  NO_PARTNER_CONNECTIONS_FOUND: '找不到合作夥伴連接',
  I_HAVE_READ_AND_AGREE_WITH_THE: '我已閱讀並同意',
  ZANG_PRIVACY_STATEMENT: 'Zang隱私聲明',
  AGENT_PROGRAM_TERMS_OF_SERVICE: '代理計畫服務條款',
  SUBMIT_APPLICATION: '提交申請',
  SUBMITTING: '正在提交',
  SUBMITTING_YOUR_APPLICATION: '正在提交你的申請',
  ALL_BANK_AND_ACCOUNT_INFORMATION_IS_HELD_PRIVATE_AND_SECURE_UNDER_OUR_TERMS_AND_CONDITIONS: '根據我們的條款和條件，所有銀行和帳戶資訊均被保密。',
  BANK_NAME: '銀行名稱',
  ADDRESS: '地址',
  COUNTRY: '國家',
  SELECT_ONE: '- 選擇一項 -',
  STATE_PROVINCE: '州/省',
  CITY: '城市',
  ZIP_POSTAL_CODE: '郵遞區號/郵編',
  ACCOUNT_NUMBER: '帳號',
  BANK_NUMBER: '銀行編號',
  TRANSIT_NUMBER: '銀行代號',
  SWIFT_CODE: '銀行國際代碼',
  TAX_REGISTRATION_NUMBER: '稅務登記號',
  SAVE_BANK_INFORMATION: '儲存銀行資訊',
  SAVING_BANK_INFORMATION: '正在儲存銀行資訊',
  NO_CUSTOMERS_FOUND: '找不到客戶',
  YOU_ARE_A: '你是 ',
  A_DISCOUNT_OF: '...的折扣',
  WILL_BE_APPLIED_TO_YOUR_TOTAL_AMOUNT_AFTER_YOU_CHECKOUT: '在你結賬後，將套用到你的總金額。',
  FIRST_NAME: '名字',
  LAST_NAME: '姓氏',
  COMPANY_NAME: '公司名稱',
  LEGAL_COMPANY_NAME: '法定公司名稱',
  PHONE_NUMBER: '電話號碼',
  WEBSITE: '網站',
  OPERATIONAL_ADDRESS: '經營地址',
  SAME_AS_ORGANIZATION_ADDRESS: '與組織地址相同',
  ARE_YOU_AN_EXISTING_AVAYA_PARTNER: '你是現有的Avaya合作夥伴嗎？',
  NO: '否',
  IF_YES_PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: '如果是，請輸入Avaya合作夥伴ID',
  MY_PARTNER_PORTAL: '我的合作夥伴入口網站',
  THANK_YOU_FOR_APPLYING: '感謝你申請！',
  ONE_MORE_STEP_AND_YOU_RE_DONE_TO_COMPLETE_YOUR_SALES_AGENT_APPLICATION_PLEASE_FOLLOW_THE_LINK_BELOW_AND_ANSWER_ALL_QUESTIONS: '再多一步，就完成了！為完成銷售代理申請，請你根據下方連接回答所有提問。',
  IF_THIS_STEP_HAS_ALREADY_BEEN_COMPLETED_PLEASE_GIVE: ' 如果不是，請提供 ',
  PLEASE_GIVE: '請提供',
  IF_YOU_ARE_AN_EXISTING_AVAYA_PARTNER_PLEASE_DO_NOT_FOLLOW_THE_LINK_BELOW: '如果你是現有的 Avaya 合作夥伴，請勿按照下方連結操作。<br />我們正在審核你的合作夥伴 ID，並會盡快聯絡你。',
  BUSINESS: '個營業',
  DAYS: '日',
  FOR_A_SENIOR_MANAGEMENT_TO_REVIEW_YOUR_APPLICATION_IN_THE_MEANTIME_ALL_QUESTIONS_CAN_BE_SENT_TO: '供高層管理審查你的申請。<br />同時，所有問題將被傳輸至',
  COMPLETE_MY_APPLICATION: '完成我的申請',
  WE_HAVE_REVIEWED_YOUR_APPLICATION_UNFORTUNATELY_AT_THIS_TIME_WE_HAVE_DETERMINED_THAT_IT_IS_UNFIT_FOR_OUR_PROGRAM_ITS_PROBABLY_NOTHING_SERIOUS_BUT_WE_CANNOT_MOVE_FORWARD_WITH_OUR_PARTNERSHIP_UNTIL_WE_FIGURE_THIS_OUT_WE_UNDERSTAND_THIS_MIGHT_BE_FRUSTRATING_PLEASE_BE_AWARE_THAT_WE_ARE_LOOKING_INTO_THE_REASONING_AND_WILL_CONTACT_YOU_AS_SOON_AS_WE_HAVE_MORE_INFORMATION_IN_THE_MEANTIME_FEEL_FREE_TO_CONTACT: '我們已審閱你的申請。遺憾的是，目前，我們已確定它不適合我們的計劃。這可能沒有什麼大不了的，但在解決這個問題之前，我們不能繼續我們的夥伴關係。我們明白這可能令人沮喪。敬請知悉我們正在研究推理，一旦有更多信息將盡快聯繫你。同時，請隨時就此程序',
  WITH_ANY_QUESTIONS_REGARDING_THIS_PROCESS: '的任何疑問聯絡我們',
  CONGRATULATIONS: '恭喜',
  YOU_ARE_NOW_AN_OFFICIAL_ZANG_AGENT: '你現在是一名正式的Zang代理！',
  GET_STARTED_BY_SHARING_YOUR_PERSONAL_LINK_WITH_ALL_OF_OUR_LEADS: '首先與你的所有潛在客戶分享個人連結',
  AND_HELP_THEM_EXPERIENCE_A_BETTER_WAY_OF_DOING_THINGS: '並幫他們體驗更好的做事方式。',
  CHANGE_STATUS: '變更狀態',
  AGENT_DETAILS: '代理詳情',
  BANK_INFORMATION: '銀行資訊',
  THIS_ORDER_WAS_PLACED_BY_A: '此訂單的提交者是',
  WAS_APPLIED_TO_THE_TOTAL_AMOUNT: '套用到總金額',
  REFERRALS: '推薦',
  SALES: '銷售',
  FOUND: '找到',
  HOW_IT_WORKS: '它的工作原理',
  WHAT_YOU_GET: '你獲得什麼',
  SUPPORT: '支援',
  WHICH_PROGRAM_IS_BEST_FOR_ME: '哪個計畫最適合我？',
  WHY_JOIN: '為什麼加入？',
  QUOTE: '報價',
  PRINT_THIS_QUOTE: '列印此報價',
  CLOSE_THIS_WINDOW: '關閉此視窗',
  SEARCH_BY_PLAN: '透過計畫搜尋',
  ACCESS_LEVEL: '存取級別',
  DISPLAY_NAME: '顯示名稱',
  INDUSTRY: '行業',
  COMPANY_INDUSTRY: '公司行業',
  CONTACT_PHONE_NUMBER: '聯絡人電話號碼',
  EMAIL_ADDRESS: '電郵地址',
  YES_SEND_ME_EMAIL_REGARDING_ZANG_NEWS_APPLICATIONS_DEALS_AND_SPECIAL_EVENTS: '是的，向我傳送關於zang新聞、應用程式、交易和特別活動的電子郵件！',
  INFORMATION: '資訊',
  ORDER_HISTORY: '訂單記錄',
  FILTER: '篩選器',
  ACCOUNT: '帳戶',
  AMOUNT_CHARGED: '收取金額',
  DETAILS: '詳情',
  NO_RECORDS_FOUND: '找不到記錄',
  CALL_LOGS: '通話記錄',
  EXPORT: '匯出',
  CALLER_NAME: '來電者姓名',
  DIALED_NUMBER: '所撥的電話號碼',
  DURATION_SEC: '時間長度（秒）',
  COST: '費用',
  PAYMENT_METHOD: '付款方式',
  PURCHASE_ORDER: '採購訂單',
  PURCHASE_ORDERS: '採購訂單',
  CREDIT_CARD: '信用卡',
  SHIPPING_ADDRESS: '發貨地址',
  SAME_AS_BILLING_ADDRESS: '與收費地址相同',
  SAME_AS_SHIPPING_ADDRESS: '與收貨地址相同',
  OTHER: '其他',
  SHIPPING_OPTIONS: '發貨選項',
  FREE_SHIPPING: '免費發貨',
  ADDITIONAL_NOTES: '其他附註',
  I_HAVE_READ_AND_I_AGREE_TO_THE_FOLLOWING: '我已閱讀並同意以下內容：',
  EMERGENCY_911_SERVICE_NOTICE: '緊急911服務通知',
  PLACE_MY_ORDER: '提交我的訂單',
  CLEAR_MY_ORDER: '清除我的訂單',
  PLACING_YOUR_ORDER: '正在提交你的訂單',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_UP_TO_1_MINUTE: '請耐心等待。此過程可能需要長達1分鐘。',
  PLEASE_BE_PATIENT_THIS_PROCESS_MIGHT_TAKE_SOME_TIME: '此程序可能需耗費一些時間，感謝你耐心等候。為確保訂單處理過程不會中斷，請勿關閉此瀏覽器視窗，也請勿按下返回或重新整理按鈕。',
  YOUR_NEW_NUMBER: '你的新號碼',
  NO_NUMBER_SELECTED: '未選擇號碼',
  WELL_THAT_WAS_EASY: '嗯，那很容易！',
  A_COUPLE_MORE_STEPS_AND_YOU_ARE_DONE: '再多幾個步驟，就完成了:)',
  NEXT: '下一頁',
  TITLE: '標題',
  SUB_TITLE: '副標題',
  SEARCH_BY_AREA_CODE_US_AND_CANADA_ONLY: '按區碼搜尋... （僅限美國和加拿大）',
  ENTER_AREA_CODE_US_AND_CANADA_ONLY: '輸入區碼...(僅限美國)',
  SELECT_A_PREFIX: '選擇前綴',
  PICK_THIS_NUMBER: '挑選此號碼',
  DEVICES: '裝置',
  BILLING: '收費',
  CHANGE: '更改',
  USER_INFO: '使用者資訊',
  USE_MY_INFORMATION: '使用我的資訊',
  SELECT_YOUR_DEVICES: '選擇你的裝置',
  MONTHLY_FEE: '月費',
  ANNUAL_FEE: '年費',
  TWO_YEAR_FEE: '2年費用',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER: '每個Zang Office計畫需要至少一個標准或進階使用者。',
  CHECKOUT: '結賬',
  MINE: '我的',
  REMOVE_THIS_USER: '移除此使用者',
  SELECT_A_DEVICE_FOR_THIS_USER: '為此使用者選擇一個裝置',
  ADD_ANOTHER: '新增其他',
  GET_STARTED_WITH_ZANG_OFFICE: 'Zang Office入門',
  BUNDLE: '搭售方案',
  SING_UP_FOR_A_YEAR_AND_RECEIVE: '註冊一年並接收',
  OFF: '關',
  EACH_USER: '每個使用者',
  TO_ADJUST_YOUR_USER_QUANTITIES_YOU_MUST_EITHER_CLEAR_YOUR_ORDER_OR_CONTINUE_TO_THE_DEVICES_STEP: '要調整使用者數量，必須清除你的訂單或繼續進行「裝置」步驟。',
  EVERY_TWO_YEARS: '每2年',
  YOU_VE_SAVED: '你已儲存',
  INCLUDED: '隨附的',
  ADDONS: '附加程式',
  CUSTOMIZE_EACH_USER_TO_THEIR_LIKING: '按其喜好自訂每個使用者！',
  UNITS_PER: '單位/',
  TALK_ANYWERE_ANYTIME: '隨時隨地聊天！',
  DOWNLOAD_FOR_MAC: '下載 Mac 版本',
  DOWNLOAD_FOR_WINDOWS: '下載 Windows 版本',
  THANK_YOU_FOR_BUYING_ZANG_OFFICE_VIEW_YOUR_ORDER_HERE: '感謝你購買Zang Office！在這裡檢視你的訂單！',
  CONTINUE_WITH_YOUR_PURCHASE: '繼續購買！',
  GET_STARTED_TODAY: '立即開始！',
  FEATURES: '功能',
  LETS_BREAK_IT_DOWN_FOR_YOU: '讓我們為你慢慢道來！',
  BASIC: '基本',
  STANDARD: '標準',
  POWER: '高級',
  RATE_MIN_STARTING_FROM: '費率/分鐘，始於*：',
  RATE_MIN_STARTING_FROM_1: '費率/分鐘，始於',
  LONG_DISTANCE: '國際長途',
  INTERNATIONAL_LONG_DISTANCE_RATES: '國際長途費率',
  COMMON_DESTINATIONS: '共同目的地',
  BEST_DEAL: '最佳交易',
  PER_ACTIVE_USER_PER_MONTH: '每名使用中的使用者，每月。',
  ACCORDING_TO_ANNUAL_CONTRACT: '根據年度契約',
  BILLED_ACCORDING_TO_SELECTED_PLAN: '根據所選的方案收費。',
  MONTHLY: '每月',
  ANNUALLY: '每年',
  BILLED_ANNUALY: '每年收費',
  BILLED_EVERY_TWO_YEARS: '每2年收費',
  CONFIGURE_YOUR_ADDONS: '設定你的附加程式',
  SELECT_A_QUANTITY_FOR_EACH_OF_THE_AVAILABLE_ADD_ONS: '為每個可用的附加程式選擇數量。',
  MAXIMUM_QUANTITY_FOR_THIS_ADDON_IS: '此附加程式的最大數量是',
  THIS_ADDON_IS_ONLY_AVAILABLE_FOR: '此附加程式僅適用於',
  BILLING_AND_SHIPPING: '收費和發貨',
  BILLING: '收費',
  THIS_WILL_BE_YOUR_ZANG_OFFICE_ACCOUNT_NAME: '這將為你的Zang Office帳戶名稱。',
  THIS_WILL_BE_YOUR_IP_OFFICE_ACCOUNT_NAME: '這將是你的 Avaya 雲端帳戶名稱。',
  IF_YOUR_VE_CHOSEN_TO_USE_YOUR_EXISTING_OR_A_TOLLFREE_NUMBER_WE_WILL_TRY_TO_FIND_A_LOCAL_NUMBER_WITH_THE_EXTENSION_USED_IN_THIS_FIELD: '如果你選擇將現有號碼或免費電話號碼用作你的Zang Office號碼，我們將嘗試尋找一個此欄位中使用內線的本地號碼。',
  EVERYTHING_HAPPENS_IN_SPACES: '一切在Spaces中發生',
  A_CLOUD_BASED_TEAM_COLLABORATION_TOOL_YOU_VE_ALWAYS_WANTED_BUT_COULD_NEVER_FOUND: '一個你夢寐以求但遍尋不獲的雲端式團隊協作工具。',
  YOUR_CURRENT_PURCHASES: '你目前購買的產品',
  PURCHASED_ON: '購買於',
  PLAN_NUMBER: '計畫編號',
  UPDATE: '更新',
  UPDATED: '已更新',
  OR: '或',
  MAKE_A_NEW_PURCHASE: '購買新產品',
  FEATURES_AND_ADDONS: '功能和附加程式',
  FREE: '有空',
  PLUS: '加值',
  BUSINESS: '高級',
  VIEW: '檢視',
  TEAM: '團隊',
  LETS_SETUP_YOUR_TEAM: '讓我們設定你的團隊',
  SIMPLY_SELECT_THE_TYPE_OF_THE_TEAM_YOU_WANT_TO_CREATE_AND_SETUP_YOUR_PRIVATE_ENVIRONMENT: '只需選擇你要建立的團隊類型並設定你的私人環境。',
  COMPANY_TYPE: '公司類型',
  DOMAIN: '網域',
  NO_TEAM_IS_SETUP_YET: '尚未設定團隊',
  DO_NOT_SETUP_A_TEAM_FOR_ME: '請勿為我設定團隊',
  PURCHASE_ZANG_SPACES_JUST_FOR_YOU: '只為你購買Zang Spaces。',
  CHOOSE_AN_EXISTING_COMPANY: '選擇一個現有公司',
  SELECT_ONE_OF_THE_COMPANIES_YOU_RE_CURRENTLY_ADMINISTRATING: '選擇你目前管理的公司之一。',
  CREATE_A_NEW_TEAM: '建立一個新團隊',
  PROVIDE_A_TEAM_AND_DOMAIN_NAME: '提供團隊和域名。',
  NO_DOMAIN_IS_CONFIGURED: '未設定網域。',
  PLEASE_PROVIDE_A_DOMAIN_NAME_EX_ZANG_IO: '請提供域名（例如：\'zang.io\'）',
  CHECK: '檢查',
  TEAM_DOMAIN: '團隊網域（例如：\'zang.io\'）',
  TEAM_NAME: '團隊名稱（例如：\'Zang\'）',
  OK: '確定',
  ZANG_SPACES_ADMIN_CONSOLE: 'Zang Spaces管理主控台',
  YOU_CAN_CHANGE_THE_VALUES_BELOW_TO_UPDATE_YOUR_PLAN: '你可以變更以下值以更新你的計畫',
  CHARGABLE_USERS: '收費使用者',
  TOTAL_USERS: '使用者總數',
  CURRENT_PRICE: '目前價格',
  SAVE: '儲存',
  SAVE_CHANGES_AND_UPDATE_PLAN: '儲存變更並更新計畫？',
  PLEASE_SELECT_AT_LEAST_ONE_TYPE_OF_USER_TO_CONTINUE: '請選擇至少一類使用者以繼續',
  YOU_RE_PURCHASING_ZANG_SPACES_FOR: '你將購買Zang Spaces',
  BUY_NOW: '立即購買',
  SELECT: "選擇",
  UP_TO: '多達',
  NO_PURCHASE_REQUIRED: '不需購買',
  NO_BILLING_OF_UPFRONT_COMMITMENT: '無收費或預付款。',
  SIGN_UP_FOR_FREE: '免費註冊！',
  ONE_YEAR_PLAN: '1年計畫',
  MONTHLY_PLAN: '每月計畫',
  TWO_YEAR_PLAN: '2年計畫',
  MONTHS: '個月',
  ZANG_OFFICE_ACCOUNT_NAME: 'Zang Office帳戶名稱',
  ZANG_OFFICE_PLAN_NUMBER: 'Zang Office計畫編號',
  TEMPORARY_NUMBER: '臨時號碼',
  START_SETTING_UP_ZANG_OFFICE: '開始設定Zang Office！',
  IF_YOU_RE_TRANSFERRING_AN_EXISTING_NUMBER_TO_YOUR_ZANG_OFFICE_SOLUTION_YOU_NEED_TO_EMAIL_ZOSUPPORT_ZANGIO_WITH_THE_LNP_AUTHORIZATION_FORM_AND_A_COPY_OF_YOUR_MOST_RECENT_PHONE_BILL_IF_YOU_RE_TRANSFERRING_A_TOLL_FREE_NUMBER_PLEASE_ALSO_EMAIL_THE_RODAA_FORM_NOTE_THAT_IT_COULD_TAKE_UP_TO_10_BUSINESS_DAYS_TO_COMPLETE_THE_TRANSFERS: '如果你將現有號碼轉駁到你的Zang Office解決方案，需透過電郵向zosupport@zang.io傳送LNP授權書和最新電話帳單的副本。如果你要轉駁免費號碼，也請透過電郵傳送RODAA表。請注意完成轉駁可能需要最多 10 個營業日。',
  THERE_WAS_AN_ERROR_BUYING_ACTIVATING_THE_CHOSEN_ZANG_OFFICE_NUMBERSCLICK_START_SETTING_UP_ZANG_OFFICE_TO_ACTIVATE_BUY_YOUR_NUMBERS_MANUALLY_IN_CASE_YOUVE_CHOSEN_TO_USE_YOUR_EXISTING_NUMBER_THE_PORTING_PROCESS_WILL_NOT_BE_AFFECTED: '購買/啟動所選Zang Office號碼時發生錯誤。按\'開始設定Zang Office\'以手動啟動/購買你的號碼。如果你選擇使用現有號碼，轉移過程不受影響。',
  ORDER_OFFICE_TRANSFER_INSTRUCTIONS: '請注意：如果你將現有號碼轉移到你的 Zang Office 帳戶，需填寫此 <a href="{LNP_FORM_LINK}" target="blank">LNP 授權書</a>，並透過電子郵件傳送此授權書和最新電話帳單的副本。如果你要轉駁免費號碼，也請填寫 <a href="{RODAA_LINK}" target="blank">RODAA 表</a>。請將所有適用文件傳送至 <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>。電話號碼轉移程序最多將需時 10 個工作天。',
  USE_EXISTING_NUMBER_POPUP_INFORMATION: '請注意，電話號碼轉移程序最多將需時 10 個工作天。在此期間，我們會在你的帳戶內附加一個臨時電話號碼供你使用。',
  PLAN_STATUS: '計畫狀態',
  PLAN_ID: '計畫ID',
  SUBSCRIPTION_ID: '訂閱ID',
  STRIPE_PLAN_ID: 'Stripe計畫ID',
  ACCOUNT_ID: '帳戶ID',
  START_SETTING_UP_ZANG_SPACES: '開始設定Zang Spaces',
  COMPANY_DOMAIN: '公司網域',
  THIS_FIELD_IS_REQUIRED: '此欄位為必填項。',
  PLEASE_ANSWER_THIS_QUESTION: '請回答此問題。',
  PLEASE_ENTER_YOUR_AVAYA_PARTNER_ID: '請輸入Avaya合作夥伴ID。',
  PLEASE_READ_AND_AGREE_WITH_THE_PRIVACY_STATEMENT_TO_CONTINUE: '請閱讀並同意隱私聲明以繼續。',
  PLEASE_READ_AND_AGREE_WITH_THE_AGENT_PROGRAM_TERMS_OF_SERVICE_TO_CONTINUE: '請閱讀並同意代理計畫服務條款以繼續。',
  THIS_AVAYA_PARTNER_ID_IS_ALREADY_IN_USE: '此Avaya合作夥伴ID已在使用中。',
  THIS_TAX_REGISTRATION_NUMBER_IS_ALREADY_IN_USE: '此稅務登記號已在使用中。',
  THIS_IS_NOT_A_VALID_AVAYA_PARTNER_ID: '這不是有效的Avaya合作夥伴ID。',
  QUANTITY_MUST_BE_A_POSITIVE_NUMBER: '數量必須為正數',
  ORDER_COMPLETE: '訂單完成！',
  PLEASE_TRY_AGAIN: '請再試一次',
  PLEASE_SELECT_AT_LEAST_ONE_POSITIVE_VALUE: '請選擇至少一個正值',
  UPDATE_IS_STILL_IN_PROGRESS_PLEASE_TRY_AGAIN_LATER: '更新仍在進行。請稍後再試。',
  YOU_CANNOT_HAVE_MORE_THAN_ONE_USER_FOR_A_PERSONAL_LICENSE_TO_UPGRADE_OR_DOWNGRADE_YOUR_PLAN_CHANGE_THE_QUANTITES_ACCORDINGLY: '個人授權不能有多個使用者。要升級或降級計畫，請相應地變更數量。',
  YOU_DONT_HAVE_ACCESS_TO_THIS_ACCOUNT: '你對此帳戶沒有存取權限。',
  YOUR_CURRENT_PLAN_DOES_NOT_ALLOW_YOU_TO_DECREASE_USERS_LESS_THAN_YOUR_ORIGINAL_AMOUNT_IF_THIS_IS_SOMETHING_YOUD_LIKE_TO_ADJUST_PLEASE_CONTACT_US_AT_CUSTOMERSERVICE_ZANGIO: '你目前的計畫不允許你減少使用者到少於原始數量。如果對此進行調整，請聯絡我們：customerservice@zang.io。',
  THERE_WAS_AN_ERROR_PLACING_YOUR_ORDER_PLEASE_ENSURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES_AND_IF_THE_ERROR_INSISTS_CONTACT_ZANG_SUPPORT_FOR_MORE_INFORMATION: '在提交你的訂單時出錯。請確保所有欄位都有有效值，如果錯誤仍然存在，請聯絡Zang支援以獲取更多資訊',

  USE_EXISTING_NUMBER: '使用現有號碼',
  SELECT_TO_USE_YOUR_EXISTING_NUMBER_WITH_YOUR_PLAN: '選擇將你現有的號碼用於你的計畫',
  PRE_SELECT_A_TOLL_FREE_NUMBER: '預選擇一個免費號碼',
  SELECT_TO_ADD_YOUR_VERY_OWN_TOLL_FREE_NUMBER_TO_YOUR_PLAN: '選擇將你自己的免費號碼新增至你的計畫',
  FIND_A_LOCAL_NUMBER: '尋找一個本地號碼',
  SELECT_FROM_A_LIST_OF_LOCAL_NUMBERS_IN_YOUR_AREA_TO_ADD_TO_YOUR_PLAN: '從你的區域的本地號碼清單選擇以新增至你的計畫',
  SELEC_TO_ADD_A_LOCAL_NUMBER_TO_YOUR_PLAN: '選擇將本地號碼新增至你的計畫',

  SEARCH_BY_AREA_CODE_FOR_AVAILABLE_PHONE_NUMBERS: '按區碼搜尋可用的電話號碼',
  SEARCH_AVAILABLE_PHONE_NUMBERS: '搜尋可用的電話號碼',
  ENTER_EXISTING_NUMBER_YOU_PLAN_TO_TRANSFER: '輸入你打算轉駁的現有號碼',


  ZANG_OFFICE_PHONE_APP: 'Zang Office電話應用程式',
  ZANG_OFFICE_SOFTPHONE: 'Zang Office 軟件電話',
  ZANG_OFFICE_PHONE_APPLICATION: 'Zang Office電話應用程式',
  SOFTPHONE_MARKETING_DESCRIPTION: 'Zang Office 軟件電話包括你預期在桌面裝置或流動裝置上提供的所有通訊功能。利用所有絕佳的Zang Office功能，而不會耗盡資源，因為Zang Office訂閱免費隨附Zang Office軟體電話！',
  E129_SIP_DESK_PHONE: 'E129 SIP台式電話',
  STANDARD_PHONE: '標準電話',
  DESKTOP_HARDPHONE_MARKETING_DESCRIPTION: 'Avaya E129 SIP台式電話將你所期望的所有必要的呼叫處理功能封裝於經濟實惠且功能強大的SIP電話中。Avaya E129台式電話讓使用者可以一鍵轉駁、靜音和撥打電話，並啟動臨時會議。全雙工免提聽筒允許進行免提通話，而其乙太網供電連接埠可方便地連接網路。Avaya E129 SIP台式電話具有具有正確的呼叫能力，既經濟實惠又有吸引力。隨附交流電源適配器。',
  DESKTOP_VANTAGE_HARDPHONE_MARKETING_DESCRIPTION: '使用這款創新、全玻璃的專用台式電話溝通。透過一鍵連線，使用語音、聊天和協作應用程式。再也沒有意外的中斷或停頓。並且無須管理多部裝置就能溝通。將獨特的自訂體驗融入你的工作流程與企業程序中。這部強大且可自訂的裝置兼備台式電話的優點與應用程式平台的彈性。',
  DESKTOP_VANTAGE_HARDPHONE_LABEL: 'Avaya Vantage™',
  B179_CONFERENCE_PHONE: 'B179會議電話',
  CONFERENCE_PHONE: '會議電話',
  CONFERENCE_HARDPHONE_MARKETING_DESCRIPTION: 'B179會議電話最適合擁有10人以上群組的董事會會議室和大型會議室，可幫助提高員工的工作效率和協作。B179會議電話是一台多功能、表現卓越的電話，可以補充你現有的解決方案，並可隨著企業發展或需求改變輕鬆地重新部署。隨附交流電源適配器。',
  PLAN: '計畫',
  REDIRECTING: '正在重新導向',
  PLEASE_MAKE_SURE_THAT_ALL_THE_FIELDS_HAVE_VALID_VALUES: '請確保所有欄位都有有效值',
  EACH_ZANG_OFFICE_PLAN_REQUIRES_AT_LEAST_ONE_STANDARD_OR_POWER_USER_PLEASE_GO_BACK_TO_THE_DEVICES_SELECTION_STEP_AND_CHANGE_YOUR_CONFIGURATION: '每個 Zang Office 計畫需要至少一個使用者類型。請返回到裝置選擇步驟並變更你的組態。',
  IT_SEEMS_THAT_YOU_HAVENT_SELECTED_ANY_NUMBER_FOR_YOUR_ZANG_OFFICE_ACCOUNT_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_TO_SELECT_A_NUMBER: '你似乎沒有為Zang Office帳戶選擇任何號碼。請返回到號碼選擇步驟以選擇號碼。',
  THAT_ZANG_OFFICE_ACCOUNT_NAME_IS_TAKEN_TRY_ANOTHER: '該Zang Office帳戶名稱已被採用。嘗試其他',
  THE_ZANG_OFFICE_NUMBER_YOU_SELECTED_HAS_ALREADY_BEEN_PURCHASED_BY_ANOTHER_CUSTOMER_PLEASE_GO_BACK_TO_THE_NUMBER_SELECTION_STEP_AND_SELECT_A_DIFFERENT_NUMBER: '你選擇的Zang Office號碼已被其他客戶購買。請返回到號碼選擇步驟並選擇其他號碼。',
  GO_MONTH_TO_MONTH_AND_GET_30_DAYS_WITH_NO_COMMITMENT: '選擇逐月支付，不受束縛，並獲得<span class="text-400">首 30 天免費</span>',
  OR_COMMIT_TO_AN_ANNUAL_PLAN_AND_GET_A: '或選擇年繳計畫，獲得更優惠的價格，以及',
  FREE_PHONE: '免費電話',
  DISCOUNT: '折扣',
  DISCOUNTED_PHONE: '折扣的電話',
  OFF_THE_TOTAL_VALUE_OF_YOUR_PHONE_PURCHASES: '購買電話的總價值折扣',
  LIMITED_TIME_OFFER: '限時優惠',
  PROMOTION: '促銷',
  ZANG_SPACES_PROMOTION: 'Zang Spaces促銷',
  CONTINUE_TO_PHONE_NUMBER_SELECTION: '繼續選擇電話號碼',
  DURATION: '時間長度',
  CONGRATULATIONS_YOU_HAVE_A_CREDIT_OF_PLACEHOLDER_TO_PUT_TOWWARDS_THE_PURCHASE_OF_ANY_PHONE_DEVICE: '恭喜！你有<strong>{amount}</strong>的抵用金來抵扣裝置訂單的總額！',
  ALL_APPLICABLE_DISCOUNTS_WILL_BE_ADJUSTED_WITHIN_YOUR_ORDER_SUMMARY: '所有適用的折扣將在你的最終訂單摘要中進行調整。',
  SHIPPING_TYPE: '發貨類型',
  TRACKING_DETAIL_WILL_BE_SENT_ONCE_YOUR_ITEMS_HAVE_SHIPPED_FROM_OUR_WAREHOUSE: '一旦你的商品從倉庫發貨，就將傳送追蹤詳情',
  RECEIVE_PLACEHOLDER_CREDIT_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: '每位使用者可獲得 {amount} 抵用金以抵扣購買任何裝置的費用。限時優惠。',
  PARTNER_ORDERS: '合作夥伴訂單',
  COMMISSION: '傭金',

  ADDITIONAL_DEVICES: '其他裝置',
  NO_USER: '沒有使用者',
  QUANTITY: '數量',
  BUY_DEVICES: '購買裝置',
  DEVICE: '裝置',
  PRICE: '價格',
  PLEASE_TYPE_AT_LEAST_PLACEHOLDER_CHARACTERS_TO_SEARCH_FOR_AN_AGENT: '請輸入至少 {chars} 個字元以搜尋代理商',
  NO_RESULTS_FOUND: '未找到結果',
  RESULTS_COULD_NOT_BE_LOADED: '無法載入結果',
  CLEAR_SELECTION: '清除選擇項目',


  RESET_ALL_PURCHASES: '清除所有購買商品',
  LISTS: '清單',
  PLEASE_FILL_OUT_YOUR_PHONE_NUMBER_BEFORE_YOU_CREATE_A_QUOTE: '在你建立報價之前，請先填妥你的電話號碼。',
  PLEASE_FILL_OUT_YOUR_BILLING_AND_SHIPPING_INFORMATION_BEFORE_YOU_CREATE_A_QUOTE: '在你建立報價之前，請先填妥你的收費和發貨資訊',
  CALCULATING_TAXES_PLEASE_WAIT: '正在計算稅金，請稍候...',
  SOMETHING_IS_WRONG_WITH_THE_CREDIT_CARD_YOU_CHOSE: '你選擇的信用卡有問題。',
  SOMETHING_IS_WRONG_WITH_THIS_CREDIT_CARD_PLEASE_USE_A_DIFFERENT_ONE: '這張信用卡有問題。請使用其他信用卡',
  THERE_WAS_EN_ERROR_CHARGING_YOUR_ORDER_PLEASE_CHOOSE_A_DIFFERENT_CREDIT_CARD: '就此訂單向你收費時發生錯誤。請選擇另一張信用卡',
  INVALID_CREDIT_CARD: '信用卡無效',
  THE_PLACEHOLDER_DOES_NOT_MATCH_WITH_THE_CREDIT_CARD_INFORMATION: '{address_type}不符合信用卡地址資訊',
  INVALID_SECURITY_CODE: '無效的安全碼(cvc)',
  ANY_APPLICABLE_DISCOUNTS_PROMOTIONAL_PRICING_HAS_BEEN_APPLIED_TO_THIS_INVOICE: '本發票已使用任何適用的折扣與優惠價格',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CUSTOMER_ACCOUNT_PLEASE_TRY_AGAIN: '我們無法建立你的客戶帳戶。請再試一次',
  WE_WERE_UNABLE_TO_CREATE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '我們無法建立你的信用卡。請再試一次',
  WE_WERE_UNABLE_TO_DELETE_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '此信用卡正用於支付定期訂購的費用。',
  WE_WERE_UNABLE_TO_SET_DEFAULT_YOUR_CREDIT_CARD_PLEASE_TRY_AGAIN: '將此信用卡設為預設時發生錯誤。',
  DEFAULT: '預設',
  SET_DEFAULT: '設定為預設',
  SALES_FORCE_QUOTE_ID: 'Salesforce 報價 ID',
  SALES_FORCE_ORDER_ID: 'Salesforce 訂單 ID',
  SALES_FORCE_OPPORTUNITY_ID: 'Salesforce 機會 ID',
  SALES_FORCE_CONTACT_ID: 'Salesforce 聯絡人 ID',
  SALES_FORCE_CONTRACT_ID: 'Salesforce 合約 ID',
  SALES_FORCE_ACCOUNT_ID: 'Salesforce 帳戶 ID',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '只要「新增裝置」',
  SIMPLY_ADD_A_DEVICE_AND_CONNECT_IT_WITH_A_USER: '只需「新增裝置」並與使用者連線即可。',
  BUY_ADDITIONAL_DEVICES_FOR_YOUR_ZANG_OFFICE_ACCOUNT: '為你的Zang Office帳戶購買其他裝置',
  OOPS_SOMETHING_IS_WRONG_WITH_YOUR_ORDER_REFRESH_THE_PAGE_CLEAR_YOUR_ORDER_AND_START_OVER: '哎喲 系統處理你的訂單時發生問題。請重新整理頁面、清除訂單，然後重新執行。',
  CREATE_A_NEW_COMPANY: '創建新公司',
  ADD_A_NEW_COMPANY: '新增公司',
  PARTNER_DETAILS: '合作夥伴詳情',
  AGENTS: '代理商',
  PARTNER_PORTAL: '我的合作夥伴入口網站',
  AGENT: '代理商',
  AGENT_PORTAL: '代理商入口網站',
  NO_AGENTS_FOUND: '未找到代理商',
  NO_AGENT: '無代理商',
  RELATION: '關係',
  OWNER: '擁有者',
  ADMIN: '管理員',
  MANAGER: '經理',
  EMPLOYEE: '員工',
  ACTIVE: '使用中',
  PLEASE_CHOOSE_ONE_OF_THE_PARTNERS_YOU_ARE_ASSOCIATED_WITH: '請選擇與你關聯的其中一個合作夥伴',
  APPLIED_ON: '申請時間：',
  JOIN_A_PARTNER: '加入合作夥伴',
  YOU_ARE_A_STEP_AWAY_FROM_JOINING_PLACEHOLDER: '你離加入 <b>{COMPANY_NAME}</b> 只有一步之遙了',
  JOIN_PLACEHOLDER_NOW: '立即加入 {COMPANY_NAME}',
  UPDATE_AGENT_INFO: '更新代理商資料',
  GET_STARTED_WITH_AVAYA_IP_OFFICE_TM_PLATFORM: '開始使用 Avaya 雲端解決方案<sup style="font-size:50%;vertical-align:middle;">™</sup>',
  IN_ASSOCIATION_WITH_ZANG_TM: 'Zang™ 聯盟公司',
  A_SIMPLE_POWERFUL_UNIFIED_COLLABORATION_SOLUTION: '簡單且功能強大的統一協作解決方案',
  IP_OFFICE_DONT_PAY_TILL: '2018 年 4 月 15 日前！',
  LOGIN: '登入',
  DISCOVER: '探索',
  SOLUTIONS: '解決方案',
  SERVICES: '服務',
  INDUSTRIES: '行業',
  CASE_STUDIES: '個案研究',
  PROGRAMS_AND_PROMOTIONS: '計畫與推廣活動',
  AUTHENTIC_AVAYA: 'Authentic Avaya',
  PERSPECTIVES: '觀點',
  AVAYA_CONNECTED_BLOG: 'Avaya Connected Blog',
  AVAYA_TV: 'Avaya TV',
  SOLUTION_FINDER: '解決方案搜尋器',
  INFO_FOR: '為以下身份提供的專屬資料：',
  DEVELOPERS: '開發人員',
  CHANNEL_PARTNERS: '渠道合作夥伴',
  TECHNOLOGY_PARTNERS: '技術合作夥伴',
  CONSULTANTS: '顧問',
  INVESTORS: '投資者',
  MEDIA_ANALYSTS: '傳媒分析師',
  SUPPLIERS: '供應商',
  CONNECT_WITH_US: '聯絡我們',
  FIND_A_CHANNEL_PARTNER: '尋找渠道合作夥伴',
  FIND_A_TECHNOLOGY_PARTNER: '尋找技術合作夥伴',
  EXECUTIVE_BRIEFING_CENTER: '產品展示中心',
  AVAYA_LEARNING_SERVICES: 'Avaya 學習服務',
  CONTACTS: '聯絡人',
  ABOUT_AVAYA: '關於 Avaya',
  EVENTS: '活動',
  NEWSROOM: '新聞中心',
  INVESTOR_RELATIONS: '投資者關係',
  CORPORATE_RESPONSIBILITY: '公司責任',
  OUR_COMPANY: '我們的公司',
  INTERNATIONAL_AVAYA_USERS_GROUP_IAUG: 'International Avaya Users Group - IAUG',
  CAREERS: '就業機會',
  YOUR_PERSONAL_LINK: '你的個人連結',
  SITEMAP: '網站地圖',
  TERMS_OF_USE: '使用條款',
  PRIVACY: '私隱',
  COOKIES: 'Cookie',
  AVAYA_INVOICE: '發票',
  IP_OFFICE_ACCOUNT_NAME: 'Avaya 雲端帳戶名稱',
  IP_OFFICE_PLAN_NUMBER: 'Avaya 雲端計畫編號',
  IP_OFFICE_PHONE_APPLICATION: 'Avaya 雲端解決方案軟件電話',
  IP_OFFICE_PHONE_DESCRIPTION: '透過 Avaya 雲端解決方案軟件電話，使用者便能透過單一介面，輕鬆使用存取所有通訊渠道。你可使用 Avaya 雲端解決方案軟件電話登入 Avaya 雲端解決方案，以及使用電腦從台式電話內線撥打和接聽語音與視像通話。Avaya 雲端解決方案標準和高級版使用者訂購均免費隨附軟件電話。',
  PLAN_MONTH_1_MONTH_1: '月付計畫 (無裝置抵用金)',
  PLAN_YEAR_1_MONTH_1: '1 年計畫 | 每月付費',
  PLAN_YEAR_1_YEAR_1: '1 年計畫，一次付清',
  PLAN_YEAR_2_MONTH_1: '2 年計畫 | 每月付費',
  PLAN_YEAR_2_YEAR_1: '2 年計畫 | 每年付費',
  PLAN_YEAR_2_YEAR_2: '2 年計畫，一次付清',
  PLAN_YEAR_3_MONTH_1: '3 年計畫 | 每月付費',
  PLAN_YEAR_3_YEAR_1: '3 年計畫 | 每年付費',
  PLAN_YEAR_3_YEAR_3: '3 年計畫，一次付清',
  PLAN_YEAR_5_MONTH_1: '5 年計畫 | 每月付費',
  ACCORDING_TO_PLAN: '根據計畫',
  TOTAL_USER_PLAN_FEE: '使用者計畫總費用',
  HEALTHCARE_DENY_MESSAGE: '感謝你選擇 Avaya 雲端解決方案，很遺憾，由於你屬於醫療保健行業，而我們尚未符合 HIPAA 規範，因此無法向你提供服務。一旦我們取得認證，一定會通知你，屆時希望你再次選擇我們！如有任何疑問，歡迎隨時透過 <a href="mailto:{SUCCESS_EMAIL}">{SUCCESS_EMAIL}</a> 聯絡我們。',
  SELECT_YOUR_IP_OFFICE_DEVICES: '選擇你的 Avaya 雲端解決方案<sup style="font-size:50%;vertical-align:middle;">™</sup> 裝置',
  SELECT_YOUR_IP_OFFICE_NUMBER: '選擇你的 Avaya 雲端解決方案<sup style="font-size:50%;vertical-align:middle;">™</sup> 號碼',
  ADJUST_YOUR_USERS_AND_ASSIGN_THE_DEVICES: '調整你的使用者並為他們指派裝置。',
  ADD_A_PHONE_NUMBER_YOU_WANT_TO_USE_FOR_YOUR_COMPANY: '新增你希望用於 Avaya 雲端解決方案的電話號碼。',
  ASSIGN_A_PHONE_NUMBER_TO_YOUR_SOLUTION: '為你的解決方案指派一個電話號碼。',
  INVITE_A_NEW_AGENT: '邀請新代理商',
  I_WANT_TO_INVITE_A: '我想邀請',
  CONTACT_EMAIL: '聯絡電郵',
  CONTACT_NAME: '聯絡人姓名',
  COMPANY_NAME: '公司名稱',
  CONTACT: '聯絡人',
  COMPANY_IS_INCORPORATED: '股份有限公司',
  INDIVIDUAL: '個人',
  INDIVIDUALS: '個人',
  SEND_INVITATION_EMAIL: '傳送邀請電郵',
  SENDING_INVITATION_EMAIL: '正在傳送邀請電郵...',
  THE_INVITATION_WAS_SENT_SUCCESSFULLY: '已成功傳送邀請',
  ALL_FIELDS_ARE_REQUIRED: '所有欄位都為必填項',
  PARTNER_NOT_FOUND: '未找到合作夥伴',
  SALE_AGENT_REGISTRATION: '銷售代理商註冊',
  SIMPLY_FILL_OUT_THE_FORM_BELOW_TO_BECOME_A_SALES_AGENT_FOR: '只需填妥下表即可成為以下項目的銷售代理商：',
  VIEW: '檢視',
  COMPANIES: '公司',
  ADD_A_PARTNER: '新增合作夥伴',
  ADD_PARTNER: '新增合作夥伴',
  PARTNERS_PERSONAL_LINK: '合作夥伴個人連結',
  MASTER_SALES_AGENT: '主要銷售代理商',
  AVAYA_J129_LABEL: 'J129 IP 電話',
  AVAYA_J129_DESCRIPTION: 'SIP 電話價格實惠而且功能完整，可提供所有基本通話處理功能。這款電話適合任何規模的企業，能為使用者提供所需的重要功能。這款電話支援兩個通話狀態配搭單線通話顯示螢幕。這款功能完善的電話堪稱市面上最優異的產品，值得你購買。',
  AVAYA_J169_LABEL: 'J169 IP 電話',
  AVAYA_J169_DESCRIPTION: 'SIP 電話價格實惠而且功能完整，可提供所有基本通話處理功能。這款電話適合任何規模的企業，能為使用者提供所需的重要功能。這款電話支援兩個通話狀態配搭單線通話顯示螢幕。這款功能完善的電話堪稱市面上最優異的產品，值得你購買。',
  AVAYA_J179_LABEL: 'J179 IP 電話',
  AVAYA_J179_DESCRIPTION: 'SIP 電話價格實惠而且功能完整，可提供所有基本通話處理功能。這款電話適合任何規模的企業，能為使用者提供所需的重要功能。這款電話支援兩個通話狀態配搭單線通話顯示螢幕。這款功能完善的電話堪稱市面上最優異的產品，值得你購買。',
  AVAYA_K175_LABEL: 'Avaya Vantage™',
  AVAYA_K175_DESCRIPTION: 'SIP 電話價格實惠而且功能完整，可提供所有基本通話處理功能。這款電話適合任何規模的企業，能為使用者提供所需的重要功能。這款電話支援兩個通話狀態配搭單線通話顯示螢幕。這款功能完善的電話堪稱市面上最優異的產品，值得你購買。',
  
  AVAYA_PHONE_S850_LABEL: 'DECT Gigaset S850 GO',
  AVAYA_HT802_LABEL: 'Analog Adapter 2 Ports',
  AVAYA_9641G_LABEL: '9641GS IP 台式電話',
  AVAYA_9641G_DESCRIPTION: 'Avaya 9641GS 是款多線頂級台式電話，適用於需長時間通話以及依賴智能通訊及提高生產力功能的使用者。9641GS 配備 5.0 吋彩色圖形顯示螢幕、大觸控螢幕與高解析度音訊品質。其寬頻音訊轉碼器可在所有音訊介面 (包括話筒、耳機與麥克風電話) 上提供卓越的音訊效能。',
  AVAYA_9608G_LABEL: '9608G IP 台式電話',
  AVAYA_9608G_DESCRIPTION: '9608G 台式電話是款經濟實惠且功能完善的電話，支援整合式 Gigabit 與單色螢幕。以太網絡供電簡化了部署程序，而其寬頻音訊轉碼器更提供卓越的音訊效能。這款台式電話專為小至大型企業設計，可使用八條線路，並提供可於中央管理的圖形標籤。',
  AVAYA_9611G_LABEL: '9611G IP 台式電話',
  AVAYA_9611G_DESCRIPTION: '9611G 機型包括整合式 Gigabit 與 USB 介面，配備 3.5 吋圖形彩色顯示螢幕，配搭白色背光及可於中央管理的圖形標籤。以太網絡供電簡化了部署程序，而其寬頻音訊轉碼器更提供卓越的音訊效能。',
  AVAYA_PHONE_B179_LABEL: 'B179 SIP 會議電話',
  AVAYA_PHONE_B179_DESCRIPTION: '這款靈活的 SIP 型會議電話經 Tolly 測試，透過 OmniSound 2.0 (Avaya 的專利寬頻音訊技術) 傳遞清晰自然的聲音。這款電話具備各種智能功能，可提高會議通話效率。使用會議導覽功能即可致電預先程式化的群組。而 Web 介面可方便你匯入和匯出聯絡人詳細資料。透過個人使用者個人檔案功能，即可建立你的聯絡人清單。',
  HAVE_LARGE_NUMBERS_OF_USERS: '使用者數量龐大？',
  REVIEW_OUR_VOLUME_DISCOUNT_BREAKDOWN: '查看我們的大量折扣細目分類。',
  DEVICE_FEE: '裝置費用',
  UP_TO_DEVICE_CREDITE_PER_USER: '每位使用者最多 {$} 裝置抵用金',
  PROMOTION_REMAINING_DETAIL_INFO: '你尚餘 <b>{0}</b> 可使用的推廣裝置抵用金。請注意，消費後所有剩餘的抵用金即會失效，且無法轉至你的帳戶以供未來消費使用。',
  VIEW_USER_FEATURES: '檢視使用者功能',
  FREE_DEVICES_PER_USER_INFO: '{0} (每位使用者最多 {1} 裝置抵用金)',
  VALUE_OF_DEVICE_CREDIT: '{0} 使用者 = {0} 裝置抵用金總額',
  PROMOTION_DELAYED_BILLING_INFO: '推廣：你的收費週期正式開始時，我們將提供詳細收據，並向你的信用卡收取任何未付餘額。',
  PLEASE_SELECT_AN_AGENT_TO_PLACE_THE_ORDER: '請選擇代理商以完成訂單',
  PLEASE_PROVIDE_A_VALID_DOMAIN_NAME: '請提供有效的網域名稱 (example.com)',
  AVAYA_ORDER_YOUR_NEW_IP_OFFICE_ACCOUNT: '你的 Avaya 雲端解決方案系統已備妥！',
  CONGRATULATIONS_YOUR_IP_OFFICE_ACCOUNT_IS_SETUP_SUCCESSFULLY: '你的 Avaya 雲端解決方案系統已安裝完畢！',
  HERE_IS_SOME_USEFUL_INFORMATION_ABOUT_YOUR_ACCOUNT: '',
  IP_OFFICE_PHONE_NUMBER: 'Avaya 雲端解決方案電話號碼',
  IP_OFFICE_SIP_DOMAIN_NAME: 'Avaya 雲端解決方案 SIP 網域名稱',
  IP_OFFICE_SIP_DOMAIN_ID: 'Avaya 雲端解決方案 SIP 網域 ID',
  YOUR_IP_OFFICE_ACCOUNT_IS_CURRENTLY_BEING_PROVISIONED: '你的 Avaya 雲端解決方案系統已設定完畢。',
  IP_OFFICE_FAILURE_PROVISION_MESSAGE: '感謝你的訂購。我們目前正在設定你的 Avaya 雲端解決方案系統，設定完成後將會與你聯絡。<br />如有任何疑問，歡迎隨時聯絡 Avaya 雲端解決方案支援 {IPO_SUPPORT_EMAIL}',
  IP_OFFICE_FAILURE_PROVISION_SUPPORT_MESSAGE: '此帳戶無法進行佈建',
  ERROR_CODE: '錯誤代碼',
  ERROR_MESSAGE: '錯誤訊息',
  ADMIN_PORTAL_LINK: '管理員入口網站連結',
  IP_OFFICE_DEFAULT_USER_PASSWORD: 'Avaya 雲端解決方案預設使用者密碼',
  IP_OFFICE_TEMPORARY_PHONE_NUMBER: 'Avaya 雲端解決方案臨時電話號碼',
  IP_OFFICE_BASIC_EXTENSION_RANGE: '基本版使用者內線',
  IP_OFFICE_STANDARD_EXTENSION_RANGE: '標準版使用者內線',
  IP_OFFICE_POWER_EXTENSION_RANGE: '高級版使用者內線',
  IP_OFFICE_DEFAULT_USER_PIN: '預設使用者 PIN',
  IP_OFFICE_SAME_AS_PIN: '與內線相同 (例如：200)',
  IP_OFFICE_ORDERID: 'Avaya 雲端解決方案訂單 ID',
  IP_OFFICE_HOST_NAME: '你的 Avaya 雲端解決方案主機名稱',
  IP_OFFICE_IP_ADDRESS: '你的 Avaya 雲端解決方案 IP 位址',
  IP_OFFICE_SUBSCRIPTIONID: 'Avaya 雲端解決方案訂購 ID',
  CALCULATING: '正在計算...',
  RESET_ALL_PARTNERS: '清除合作夥伴資料',
  ERROR_GETTING_AGENTS: '檢查代理商時發生錯誤。請再試一次',
  THERE_IS_ALREADY_AN_AGENT_WITH_THIS_EMAIL_IN_YOUR_TEAM: '你的團隊中已有使用此電郵的代理商',
  AUTO_APPROVE_ACTIVATE_AGENT: '自動批准/啟動代理商',
  THERE_IS_ALREADY_A_COMPANY_WITH_THIS_EMAIL_IN_YOUR_TEAM: '你的團隊中已有使用此電郵的公司',
  MASTER_SALES_AGENT_PORTAL: '主要銷售代理商入口網站',
  SALES_AGENT_PORTAL: '銷售代理商入口網站',
  E911_ADDRESS: 'E911 地址',
  OVERVIEW: '概觀',
  ADD_COMPANY_OR_SALES_AGENT: '新增公司或代理商',
  ADD_AN_AGENT: '新增代理商至',
  INACTIVE: '非使用中',
  AGENTS_PERSONAL_CONNECTION_LINK: '代理商的個人聯繫連結',
  PURCHASE_DATE_AND_CUSTOMER: '購買日期與客戶',
  ORDER_DETAILS: '訂單詳情',
  SELECT_AGENT: '所有代理商',
  FROM: '由',
  TO: '至',
  EXPORT_REPORT: '匯出報告',
  NO_SALES_FOUND: '未找到銷售資料',
  ADD_A_COMPANY: '新增公司',
  AUTO_APPROVE_COMPANY: '自動批准公司',
  AUTO_ACTIVATE_AGENT: '自動啟動代理商',
  ADD_COMPANY: '新增公司',
  ADD_COMPANY_NAME_AGENT_ADMIN: '新增 {COMPANY_NAME} 代理商/管理員',
  ADD_AGENT_ADMIN: '新增代理商/管理員',
  ALL_COMPANIES: '全部公司',
  START_DATE: '開始日期',
  HEY: '嗨！',
  CUSTOMER_SUCCESS_EMAIL_WELCOME: '我們是你的客戶成功經理，我們將協助你運用 Avaya 雲端解決方案並從中獲益。你的 Avaya 雲端解決方案支援團隊也包括我們的技術支援團隊 - <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>。',
  CUSTOMER_SUCCESS_EMAIL_PROVISION_SUCCESS: '我們希望能在接下來幾天內安排初次通話，讓我們向你介紹支援團隊及完成你的系統設定。<strong>請透過 <a href="mailto:{CUSTOMER_SUCCESS_EMAIL}">{CUSTOMER_SUCCESS_EMAIL}</a> 與我聯絡，並告知你方便進行一小時初次通話的日期與時間。<strong>',
  START_USING_YOUR_IP_OFFICE: '立即開始使用你的 Avaya 雲端解決方案系統！',
  BELOW_ARE_DETAILS: '以下是你的系統帳戶資料、使用者認證和應用程式下載項目：',
  YOUR_IP_OFFICE_INFO: '你的系統資料：',
  LOGIN_INFO_TABLE: '你的使用者資料表：',
  ALL_USERS_CAN_CONFIGURE_ADMIN_PORTAL: '所有使用者都可使用上述資料設定自已的資料、調整來電轉駁、收聽語音郵件和使用其他功能，並可登入其個人的雲端使用者入口網站。',
  AVAILABLE_APPLICATIONS_FOR_USERS: '適用於你使用者的應用程式：',
  DO_NOT_HESITATE_TO_EMAIL_US: '如有任何疑問，歡迎隨時透過電郵 <a href="mailto:{CS_EMAIL}">{CS_EMAIL}</a> 與我們聯絡！',
  THANK_YOU: '多謝，',
  AVAYA_COMMUNICATOR_FOR_WEB_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/Avaya-Communicator-2.1.4.0.msi">Avaya Communicator for Web (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_LINK: '<a href="https://chrome.google.com/webstore/detail/avaya-communicator-for-we/pjkjihhnegikngnamahchimifhdlfhkm">Avaya Communicator for Web (Chrome 擴展程序)</a>',
  IP_OFFICE_FOR_IOS_LINK: '<a href="https://itunes.apple.com/us/app/avaya-one-x-mobile-preferred-for-ipo/id509229173?mt=8">Avaya one-X® Mobile Preferred for IPO (iOS)</a>',
  IP_OFFICE_FOR_ANDROID_LINK: '<a href="https://play.google.com/store/apps/details?id=com.avaya.ScsCommander">Avaya one-X® Mobile Preferred for IPO (Android)</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_LINK: '<a href="https://sipsw.com/ipocloud/AvayaIPOfficeSoftConsole_10.1.100.5.exe">Avaya Cloud Solutions Soft Console (Windows)</a>',


  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_EXT_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dD000a">安裝文件</a>',
  IP_OFFICE_FOR_IOS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dE000a">安裝文件</a>',
  IP_OFFICE_FOR_ANDROID_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dF000a">安裝文件</a>',
  IP_OFFICE_FOR_SOFT_CONSOLE_WINDOWS_DOC_LINK: '<a href="http://resources.zang.io/Sys/Document/Open/7Ot0000000000dL000a">安裝文件</a>',




  USER_NAMES_COLUMN: '使用者名稱',
  EXTENSIONS_COLUMN: '內線',
  TEMP_PIN_COLUMN: 'Pin',
  TEMP_PASSWORD_COLUMN: '密碼',
  USER_TYPE_COLUMN: '使用者類型',
  DEVICE_MODEL_COLUMN: '裝置',
  POWER_USER: '高級',
  STANDARD_USER: '標準',
  BASIC_USER: '基本',
  ORDERID: '訂單 ID',
  ACCOUNT_NAME: '帳戶名稱',
  HOST_NAME: '主機名稱',
  ADMIN_PORTAL: '管理員入口網站',
  IP_ADDRESS: 'IP 位址',
  PHONE_NUMBER: '電話號碼',
  TEMPORARY_PHONE_NUMBER: '臨時電話號碼',
  EXCITING_TIMES_AHEAD: '精彩時刻，就在眼前',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY: '網域名稱 {DOMAIN_NAME} 為無效的網域名稱，或已有另一間公司使用此網域名稱。',
  THE_DOMAIN_NAME_PLACEHOLDER_IS_EITHER_AN_INVALID_DOMAIN_NAME_OR_IS_BEING_USED_BY_ANOTHER_COMPANY2: '網域名稱 {1} 為無效的網域名稱，或已有另一間公司使用此網域名稱。',
  THE_SYSTEM_COULD_NOT_VALIDATE_YOUR_COMPANY_PLEASE_TRY_AGAIN: '系統無法驗證你的公司。請再試一次',
  FOR_ANY_NA_VALUES_IF_ANY_PLEASE_CONTACT_IP_OFFICE_SUPPORT: '如有任何不適用的資料 (如有)，請聯絡 Avaya 雲端支援： ',
  IP_OFFICE_FATAL_ERROR_EMAIL_SUBJECT: '有一個 Avaya 雲端帳戶無法開始佈建',
  LEGAL: '法律',
  SELECT_AN_1_YEAR_PLAN_OR_MORE_AND_RECEIVE_A_CREDIT_PER_USER_TOWARDS_THE_PURCHASE_OF_ANY_DEVICE_LIMITED_TIME_OFFER: '選擇 1 年計畫 (或以上)，每位使用者即可獲得抵用金，可用於購買任何裝置。限時優惠。',
  USER_PORTAL: '使用者入口網站',
  E_911: 'E911',
  DECLINE: '拒絕',
  ACCEPT: '接受',
  PRINT: '列印',
  PLEASE_AGREE_TO_ALL_LEGAL_TERMS_IN_ORDER_TO_CONTINUE: '請同意上述條款以完成訂購',
  ASSING_A_DEVICE_TO_YOUR_USERS: '為你的使用者指派一部裝置。',
  SELECT: '選擇',
  USER_DETAILS: '使用者詳情',
  DEVICE_DETAILS: '裝置詳情',
  PLEASE_CAREFULLY_READ_OUR_TERMS_OF_SERVICE_BEFORE_ACCEPTING: '請詳閱我們的服務條款並接受。',
  PARTNER_ORDERS_RECORDS_HINT: '*所有銷售記錄僅供參考。Avaya 財務部門將按照主要銷售代理商合約提供正式和最終銷售報告。',
  PLEASE_SELECT_A_SALES_AGENT_TO_CREATE_A_QUOTE: '請選擇一個銷售代理商以建立報價',
  COMPANY_DETAILS: '公司詳情',
  AVAYA_COMMUNICATOR_FOR_WEB_CHROME_DOC_LINK: '',
  PLUS_APPLICABLE_TAXES: '加上適用稅項。',
  SELECT_PRODUCT: '選擇產品',
  CLOUD_UC_SMALL_MONTH1: '雲端統一通訊基本版月付計畫',
  SMALL: '小型',
  CLOUD_UC_SMALL_MONTH12: '雲端統一通訊基本版 1 年計畫',
  CLOUD_UC_SMALL_3YEARS: '雲端統一通訊基本版 3 年計畫',
  CLOUD_UC_SMALL_5YEARS: '雲端統一通訊基本版 5 年計畫',
  MEDIUM: '中型',
  CLOUD_UC_MEDIUM_MONTL1: '雲端統一通訊商務版月付計畫',
  CLOUD_UC_MEDIUM_MONTH12: '雲端統一通訊商務版 1 年計畫',
  CLOUD_UC_MEDIUM_3YEARS: '雲端統一通訊商務版 3 年計畫',
  CLOUD_UC_MEDIUM_5YEARS: '雲端統一通訊商務版 5 年計畫',
  LARGE: '大型',
  CLOUD_UC_LARGE_MONTL1: '雲端統一通訊大型版隨付即用計畫',
  CLOUD_UC_LARGE_MONTL12: '雲端統一通訊大型版年付計畫',
  CLOUD_UC_SMALL_SHORT_INFO: '1 - 99 名員工',
  CLOUD_UC_MEDIUM_SHORT_INFO: '100 - 999 名員工',
  CLOUD_UC_LARGE_SHORT_INFO: '1000+ 名員工',
  SELECTED: '已選擇',
  BASIC_PHONE_SERVICE: '基本電話服務',
  UNLIMITED_NATIONAL_WIDE: '無限制國內長途',
  STANDARD_FEATURES: '標準功能',
  HOW_MANY_USERS: '你需要幾位使用者？',
  ADD_ON_ADDITIONAL_FEATURES: '其他功能',
  ONETIME_FEE: '一次性費用',
  RECURRING_FEE: '定期費用',
  SELECT_MAIN_NUMBER: '選擇主號碼',
  TOLL_FREE: '免費電話號碼',
  LOCAL_NUMBER: '本地號碼',
  TRANSFER_NUMBER: '轉駁號碼',
  USERS_COUNT: '{qty} 位使用者',
  DEVICES_COUNT: '{qty} 部裝置',
  UC_OFFER_TITLE: '我們提供最適合你的解決方案！',
  UC_OFFER_DESCRIPTION: '無論你是小、中或大型企業，我們都能提供你所需的解決方案！你是哪類型的企業？',

  // 'BASIC_PHONE_SERVICE': '基本電話服務',

  TAX_CALC_ERROR_MSG: '無法計算稅項。請確認帳單地址是否正確。',
  'VIOLATION.FIELD_IS_EMPTY': '{1} 為必填',
  'VIOLATION.FIELD_IS_EMPTY2': '{1} - {2} 為必填',
  'VIOLATION.FIELD_VALUE_INVALID': '{1} 值無效',
  'VIOLATION.FIELD_VALUE_INVALID2': '{1} - {2} 值無效',
  'VIOLATION.TAX_CALCULATION_FAILED': '無法計算稅項',
  'VIOLATION.AGREE_ON_LEGAL_DOC': '你必須閱讀並同意「{1}」',
  'VIOLATION.CART_IS_EMPTY': '購物車中沒有任何項目',
  'VIOLATION.CART_IS_TOO_BIG': '購物車中項目過多',
  'SALESMODELRULE.REMOVE_OTHER_ITEMS': '已從購物車中移除 {1}',
  'SALESMODELRULE.QUANTITY_AUTO_ADJUSTED': '{1} 數量已從 {2} 調整為 {3}',
  'SALESMODELRULE.DISCOUNT_AUTO_ADJUSTED': '{1} 折扣已從 {2} 調整為 {3}',
  'SALESMODELRULE.NOT_SAME_CURRENCY': '無法將使用 {1} 貨幣的項目新增至使用 {2} 貨幣的購物車',
  'SALESMODELRULE.DISCOUNT_RULE_MISSING': '折扣規則 {1} 未定義',
  'SALESMODELRULE.UNKNOWN_ERROR': '不明錯誤',
  'SALESMODELRULE.INVALID_PARAMETER': '無效的參數：{1}',
  ONE_TIME: '一次性',
  ADDON_PRICING_HINT: '*附件程式定價以用戶端為單位，且適用於所有使用者。可在購買後於管理員入口網站中為使用者新增特定附加程式。',
  ADD_TO_CART_HINT: '完成上述步驟以新增至購物車',
  ITEM_UNITS: '{qty} 個單位',
  ADDONS_COUNT: '{qty} 個附加程式',
  ADDON_COUNT: '{qty} 個附加程式',
  MULTIPLE_TYPES: '多種類型',
  MIXED: '混合',
  FREE_PRICE: '免費',

  // AVAYACLOUD UC OFFERS
  UC_ESSENTIALS: '統一通訊基本版',
  UC_ESSENTIALS_DESCRIPTION: '適合任何規模企業的最佳雲端型通訊。',
  UC_BUSINESS: '統一通訊商務版',
  UC_BUSINESS_DESCRIPTION: '透過卓越的企業級雲端通訊，讓貴公司如虎添翼',
  UC_BUSINESS_POWER_PACKAGE: '升級為高級版使用者',
  UC_BUSINESS_POWER_PACKAGE_DESCRIPTION: '<ul><li><strong>直連電話號碼：</strong>專用的唯一號碼，所有人都可直接致電給你，無需透過公司的主號碼和接線生 (虛擬或真人)。</li><li><strong>直連視像通話：</strong>新增視訊至你的點對點電話通話。</li><li><strong>Salesforce© 整合：</strong>直接從 Salesforce 中為使用者提供完整且豐富的通訊功能。</li><li><strong>Google© 整合：</strong>直接從 Google Chrome 和所有 Google 應用程式提供瀏覽器式的即時通訊功能。</li><li><strong>Skype for Business© 整合：</strong>現代化、簡便且易於使用的 Skype for Business 協作體驗。</li></ul>',
  SHOW_MORE: '顯示更多',
  HIDE: '隱藏',
  VIEW_COMPLETE_FEATURE_LIST: ' 檢視完整功能清單',
  FILTER_BY: '篩選條件',
  UC_OFFERS: '統一通訊解決方案',
  PAY_MONTHLY: '每月付費',
  PAY_ANNUALLY: '每年付費',
  COMING_SOON: '即將推出',
  TAX_CALC_ERROR_MSG: '無法計算稅項。請確認地址是否正確。',
  LONG_DISTANCE_RATE_CHOOSE_COUNTRY: '請輸入國家/地區名稱以檢閱目前的長途通話費用。',
  LONG_DISTANCE_RATE_NOT_FOUND: '未找到此國家/地區的長途通話費用，請聯絡 {CUSTOMER_SUCCESS_EMAIL} 詢問有關此國家/地區的長途通話資料。',
  AREA_CODE: '區碼',
  INVALID_CREDIT_CARD_ZIP: '信用卡與郵區編號不符。',
  VIEW_LONG_DISTANCE_RATES: '檢視長途通話費用',
  LONG_DISTANCE_SUBTITLE_TEXT: '我們的長途通話費用價格相宜，讓你與世界各地的人保持聯繫。',
  RATES_SUBJECT_TO_CHANGE: '*費用可能會變動，恕不另行通知。',
  CREDIT_CARD_DECLINED: '信用卡遭拒絕。',
  ENTER_COUNTRY_NAME: '輸入國家/地區名稱',
  ADD_TO_CART: '新增至購物車',
  UPDATE_CART: '更新購物車',
  PER_USER: '每位使用者',
  COMPARE_UC_OFFERS: '比較統一通訊產品項目',
  PROCEED_TO_CHECKOUT: '前往結帳',
  BEFORE_APPLICABLE_TAXES: '* 未計算適用稅項前',
  YEAR_PLAN: '1 年計畫',
  YEARS_PLAN: '{0} 年計畫',
  MONTHS_PLAN: '{0} 個月計畫',
  ENTER_NUMBER_OF_USERS: '輸入你希望用於此解決方案的使用者數量',
  YEAR: '年',
  BILLED_MONTH: '每月付費',
  COMPANY_INCORPORATED: '已加入',
  COMPANY_NOT_INCORPORATED: '未加入',
  EXISTING_CONFIG_WARNING: '你已有 <br/><b>{0}</b> 的現有組態。',
  DO_YOU_WANT_TO_DISCARD_CURRENT_CONFIG: '是否要捨棄目前的組態？',
  DISCARD_MY_CONFIGURATION: '捨棄我的組態',
  DISCARD: '捨棄',
  EDIT_MY_CONFIGURATION: '編輯我目前的組態',
  CONTINUE: '繼續',
  SELECT_A_PLAN: '選擇計畫',
  PROMOTION_DETAIL_INFO: '*你已選擇共 <b>{0} 名使用者</b>！<br/>等同於<b>{1}</b> 裝置抵用金總額。',
  BILLED_MONTH_FREQUENCY: '每 {0} 個月收費',
  BILLED_YEAR_FREQUENCY: '每 {0} 年收費',
  CONTACT_OUR_CUSTOMER_CARE: '聯絡我們的客戶關懷團隊',
  NEED_HELP_INFO: '需要協助嗎？我們的客戶關懷團隊隨時準備好協助你解答任何疑問、解決問題或提供資訊。',
  REMOVE: '移除',
  REMOVE_ITEM_FROM_CART_WARNING: '是否要從購物車中移除 <b>{0}</b>？',
  NO_ITEM_IN_THE_CART: '你的購物車中無任何項目。',
  CONTINUE_SHOPPING: '繼續購物',
  TOTAL_TAXES: '稅項總額',
  UC_SOLUTIONS: '統一通訊解決方案',
  UNIFIED_COMMUNICATIONS: '統一通訊',
  ADD_ONS: '附加程式',
  SYSTEM_ADDONS: '系統附加程式',
  ADD_DEVICES: '新增裝置',
  SELECT_UPTO_DEVICES: '為 <b>{1}</b> 設定最多 (<b>{0}</b>) 部裝置',
  DONE: '完成',
  SELECT_DEVICES: '選擇裝置',
  EDIT_DEVICE_SELECTION: '編輯裝置',
  ESSENTIAL_USERS: '基本版使用者',
  BUSINESS_USERS: '商務版使用者',
  POWER_USERS: '高級版使用者',
  N_A: '不適用'
}
