import mongoose, { Schema } from 'mongoose';

var PaymentGatewaySchema = new Schema({
    sku: String,    //Human readable unique identifier of the object. This is the reference generated by the store
    gateway: String,   //e.g.: Stripe
    objectType: String,     //Type of object to map to on provider system (e.g.: Plan, Product, TAX_CODE, etc.)
    objectId: String,   //ID of object on provider system
    metadata: {}
});

export default mongoose.model('PaymentGatewaySchema', PaymentGatewaySchema);