import mongoose, { Schema } from 'mongoose';

var TaxGatewaySchema = new Schema({
    sku: String,    //Human readable unique identifier of the object. This is the reference generated by the store
    gateway: String,   //e.g.: Avalara
    objectType: String,
    metadata: {},
    taxCodes: {
        transactionType: Number,
        serviceType: Number
    }
});

export default mongoose.model('TaxGatewaySchema', TaxGatewaySchema);