const PRODUCT_ENGINE_NAME = 'zang-spaces';

const SPACES_LICENSETYPE_BASIC = 'zangspaces_free';
const SPACES_LICENSETYPE_PLUS = 'zangspaces_team';
const SPACES_LICENSETYPE_BUSINESS = 'zangspaces_business';
const SPACES_LICENSETYPE_DIALIN = 'zangspaces_dial';
const SPACES_LICENSETYPES = [
  SPACES_LICENSETYPE_BASIC,
  SPACES_LICENSETYPE_PLUS,
  SPACES_LICENSETYPE_BUSINESS,
  SPACES_LICENSETYPE_DIALIN
];

module.exports = {
  PRODUCT_ENGINE_NAME,

  SPACES_LICENSETYPE_BASIC,
  SPACES_LICENSETYPE_PLUS,
  SPACES_LICENSETYPE_BUSINESS,
  SPACES_LICENSETYPE_DIALIN,
  SPACES_LICENSETYPES,
};
