export const PRODUCT_TYPES = {
  ALL: 'all',
  GROUP: 'group',
  DIRECT: 'direct'
};



export const ACTION_TYPES = {
  FETCH_OFFERS: 'FETCH_OFFERS',
  FETCH_OFFERS_SUCCESS: 'FETCH_OFFERS_SUCCESS',
  FETCH_OFFERS_ERROR: 'FETCH_OFFERS_ERROR',

  FETCH_OFFERS_BY_CATEGORY: 'FETCH_OFFERS_BY_CATEGORY',
  FETCH_OFFERS_BY_CATEGORY_SUCCESS: 'FETCH_OFFERS_BY_CATEGORY_SUCCESS',
  FETCH_OFFERS_BY_CATEGORY_ERROR: 'FETCH_OFFERS_BY_CATEGORY_ERROR',

  FETCH_OFFER: 'FETCH_OFFER',
  FETCH_OFFER_SUCCESS: 'FETCH_OFFER_SUCCESS',
  FETCH_OFFER_FAILURE: 'FETCH_OFFER_FAILURE',

  CREATE_PRODUCT: 'CREATE_PRODUCT',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',

  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',

  FETCH_OFFERS_WIZARD_DEFAULTS: 'FETCH_OFFERS_WIZARD_DEFAULTS',
  FETCH_OFFERS_WIZARD_DEFAULTS_SUCCESS: 'FETCH_OFFERS_WIZARD_DEFAULTS_SUCCESS',
  FETCH_OFFERS_WIZARD_DEFAULTS_FAILURE: 'FETCH_OFFERS_WIZARD_DEFAULTS_FAILURE',

  SELECT_OFFER: 'SELECT_OFFER',
  SELECT_OFFER_IDENTIFIER: 'SELECT_OFFER_IDENTIFIER',
  SET_USER_CART_DATA_SELECTION: 'SET_USER_CART_DATA_SELECTION',

  
  FETCH_TOPLEVEL_OFFER: 'FETCH_TOPLEVEL_OFFER',
  FETCH_TOPLEVEL_OFFER_SUCCESS: 'FETCH_TOPLEVEL_OFFER_SUCCESS',
  FETCH_TOPLEVEL_OFFER_FAILURE: 'FETCH_TOPLEVEL_OFFER_FAILURE',
};
