export const ACTION_TYPES = {
  FETCH_COUNTRIES: 'FETCH_COUNTRIES',
  FETCH_COUNTRIES_SUCCESS: 'FETCH_COUNTRIES_SUCCESS',
  FETCH_COUNTRIES_ERROR: 'FETCH_COUNTRIES_ERROR',

  FETCH_STATES: 'FETCH_STATES',
  FETCH_STATES_SUCCESS: 'FETCH_STATES_SUCCESS',
  FETCH_STATES_ERROR: 'FETCH_STATES_ERROR'
}