export const ACTION_TYPES = {
  FETCH_SALESMODEL: 'FETCH_SALESMODEL',
  FETCH_SALESMODEL_SUCCESS: 'FETCH_SALESMODEL_SUCCESS',
  FETCH_SALESMODEL_FAILURE: 'FETCH_SALESMODEL_FAILURE',

  FETCH_DEFAULT_SALESMODEL: 'FETCH_DEFAULT_SALESMODEL',
  FETCH_DEFAULT_SALESMODEL_SUCCESS: 'FETCH_DEFAULT_SALESMODEL_SUCCESS',
  FETCH_DEFAULT_SALESMODEL_FAILURE: 'FETCH_DEFAULT_SALESMODEL_FAILURE',

  SET_DEFAULT_SALESMODEL: 'SET_DEFAULT_SALESMODEL',
};

export const PRODUCT_TAG_STANDARD_FEATURES = 'standard-features'
export const PRODUCT_TAG_SYSTEM_ADDON = 'system-addon'
export const PRODUCT_TAG_SYSTEM_USAGE_RATES = 'usage-flat-rate-addon'
export const PRODUCT_TAG_USER_TYPES = 'user-types'
export const PRODUCT_TAG_ADDON_BY_USER_TYPES = 'addon-by-usertypes'
export const PRODUCT_TAG_ADDON_FEATURES = 'addon-features'
export const PRODUCT_TAG_DISCOUNT = 'discount'
export const PRODUCT_TAG_DEVICES = 'devices'
export const PRODUCT_TAG_DID_MAIN = 'did-main'
export const PRODUCT_TAG_NO_CONFIG = 'no-config'
export const PRODUCT_TAG_DID = 'did'
export const PRODUCT_TAG_USER_DID = 'user-did'